### ISSUE TITLE
Unable to load sheet with columns more than 256

### ISSUE THREAD

**Issue by darlenya** [SheetJS/js-xlsx#1000]
Hi Team, 
I have an Excel sheet with more than 256 column. But the last column which is imported is 'IV' column 256. Is this a known limitation?
In the debugger I could see that the sheet did not contain more columns after loading.
There is no Error, just the data is missing.

```javascript
// Version "xlsx": "^0.12.1"
import XLSX from 'xlsx'

// Load file with more than 256 columns
const workbook = XLSX.readFile('./myExcel.xls')
const sheet = workbook.Sheets['mySheet']

console.log(sheet['IV1']) // works
console.log(sheet['JK1']) // undefined
```

It also not works with '.xlsx'

Thanks

**Comment by darlenya** [comment]
This was an error caused by openoffice. There the columns where cut. So no issue!

**Comment by reviewher** [comment]
OO / LibreOffice also used to (still does?) truncate at 65536 rows (see #189)
