### ISSUE TITLE
How to get active sheet index or name?

### ISSUE THREAD

**Issue by amit-mn** [SheetJS/js-xlsx#1008]
I have multiple sheets in one excel. I want to read data from active sheet or last saved sheet in excel.
Is it possible to do this or any other solution for doing this?

**Comment by amit-mn** [comment]
please tell, Is it possible or not?
Or I use another module for doing this.

**Comment by amit-mn** [comment]
I found the solution for this by debugging the workbook object. Thanks by the way.

**Comment by fandzaz** [comment]
> I found the solution for this by debugging the workbook object. Thanks by the way.

How can you do it?

**Comment by mittaus** [comment]
> > I found the solution for this by debugging the workbook object. Thanks by the way.
> 
> How did you do that ?

``` javascript
var activeTab = 0;
if (typeof workbook.Workbook.WBView !== 'undefined') {
  if (Array.isArray(workbook.Workbook.WBView) && workbook.Workbook.WBView.length > 0) { 
     activeTab = workbook.Workbook.WBView[0].activeTab;
  }
}
```

**Comment by Michael-F-Chen** [comment]
> > > 我通过调试工作簿对象找到了解决方案。顺便谢谢。
> > 
> > 
> > 你是怎么做到的 ？
> 
> ```js
> var activeTab = 0;
> if (typeof workbook.Workbook.WBView !== 'undefined') {
>   if (Array.isArray(workbook.Workbook.WBView) && workbook.Workbook.WBView.length > 0) { 
>      activeTab = workbook.Workbook.WBView[0].activeTab;
>   }
> }
> ```



> > > 我通过调试工作簿对象找到了解决方案。顺便谢谢。
> > 
> > 
> > 你是怎么做到的 ？
> 
> ```js
> var activeTab = 0;
> if (typeof workbook.Workbook.WBView !== 'undefined') {
>   if (Array.isArray(workbook.Workbook.WBView) && workbook.Workbook.WBView.length > 0) { 
>      activeTab = workbook.Workbook.WBView[0].activeTab;
>   }
> }
> ```


This waydoes not work and has no activeTab attribute
