### ISSUE TITLE
Integrity error when npm install xlsx

### ISSUE THREAD

**Issue by Worlor** [SheetJS/js-xlsx#1009]
Hello, 

I am unable to install correctly the extension with NPM, it throw an EINTEGRITY error.
The integrity checksum at install fails beginning from version 0.11.19
0.11.18 and before works well.

logs related : [https://gist.github.com/Worlor/495a4e44a78655141463b525ad0b3d3c](https://gist.github.com/Worlor/495a4e44a78655141463b525ad0b3d3c)

System : Windows 7 X64
Node v8.9.4
Npm v5.6.0

**Comment by reviewher** [comment]
Can't reproduce on the same configuration (Windows 7 64-bit with node 8.9.4 npm 5.6.0) and can't reproduce with the same node/npm versions on ubuntu or osx.  You might have a cache or package lock issue.  Try reporting to [the npm issue tracker](https://github.com/npm/npm/issues).

**Comment by Worlor** [comment]
I already tried to clear cache, delete package-lock and npm-module with no success.

**Comment by Worlor** [comment]
Anyway, the problem start with the version 0.11.19, it seems it come from the package

Related : https://github.com/npm/npm/issues/19951

**Comment by vlzware** [comment]
I just had the same problem with xlsx 0.20.0 when using `npm ci`.

Here is the relevant section in package-lock.json :
```json
    "node_modules/xlsx": {
      "version": "0.20.0",
      "resolved": "https://cdn.sheetjs.com/xlsx-latest/xlsx-latest.tgz",
      "integrity": "sha512-adg5edVTkXXGTnb0iWrc3Z47ViGgwmD47yx6VfSCZhfdKPtHcElYGs48OtcO4nwOu90Pjz5mmyl0HLcvbSRYTQ==",
      "license": "Apache-2.0",
      "bin": {
        "xlsx": "bin/xlsx.njs"
      },
      "engines": {
        "node": ">=0.8"
      }
    },
```
And the error message:
```bash
npm WARN tarball tarball data for xlsx@https://cdn.sheetjs.com/xlsx-latest/xlsx-latest.tgz (sha512-adg5edVTkXXGTnb0iWrc3Z47ViGgwmD47yx6VfSCZhfdKPtHcElYGs48OtcO4nwOu90Pjz5mmyl0HLcvbSRYTQ==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-adg5edVTkXXGTnb0iWrc3Z47ViGgwmD47yx6VfSCZhfdKPtHcElYGs48OtcO4nwOu90Pjz5mmyl0HLcvbSRYTQ== integrity checksum failed when using sha512: wanted sha512-adg5edVTkXXGTnb0iWrc3Z47ViGgwmD47yx6VfSCZhfdKPtHcElYGs48OtcO4nwOu90Pjz5mmyl0HLcvbSRYTQ== but got sha512-hA7SYmn/H3cJ1VGi7kmSKxbEXCEn5UVJlwYFSFXhLe54wPUvW+80TmR5l+TZh4nJCw8G/e0SuZUfvqlTIh40hw==. (2389616 bytes)
```

The problem is that in my package-lock.json `resolved` points to the latest release - currently 0.20.1, which indeed has the checksum `sha512-hA7SYmn/H3cJ1VGi7kmSKxbEXCEn5UVJlwYFSFXhLe54wPUvW+80TmR5l+TZh4nJCw8G/e0SuZUfvqlTIh40hw==`. Comparing this to the checksum of 0.20.0 would of course not work.

So, the solution is to set a specific version, instead of `latest`. For example:
```bash
npm i --save https://cdn.sheetjs.com/xlsx-0.20.0/xlsx-0.20.0.tgz
```
