### ISSUE TITLE
Can XLSX.read be used to parse a BLOB containing an XLSX generated in the browser's memory?

### ISSUE THREAD

**Issue by martinmarchetta** [SheetJS/js-xlsx#1011]
Hi all,

I've a 3rd party JS library that exports a JS grid as an XLSX file, and I can get the exported XLSX BLOB (ultimately built using JSZip) inside the browser before it's saved to the disk. I need to customize this file by adding some data to some cells. 

I tried this:
```javascript
// blobXLSX contains the XLSX file exported by the other library
var workbook = XLSX.read(blobXLSX, { type: "binary" });
```

But the workbook doesn't seem to be populated with the contents of the file (sheets, cell values, etc). 
If I save the BLOB to the disk directly, without opening with JS-XLSX (e.g. using [this approach](https://jsfiddle.net/koldev/cW7W5/)), the contents are there though, so the BLOB does contain the XLSX.

All this happens in the browser, without any trips to the server.

I looked over the other issues in the list and the documentation, but didn't find a case like this. Any help would be appreciated.

Thanks

**Comment by reviewher** [comment]
As explained in https://docs.sheetjs.com/#output-type , the `"binary"` type corresponds to a binary string.  If you can generate a Uint8Array or ArrayBuffer, you can read with the `"array"` type.  If you have an actual JS `Blob` object, you have to use `FileReader` to read the blob into a binary string:

```js
var reader = new FileReader();
reader.onload = function(e) {
  var data = e.target.result;
  var workbook = XLSX.read(data, 'binary');
  /* DO SOMETHING WITH workbook HERE */
};
reader.readAsBinaryString(blob);
```

**Comment by martinmarchetta** [comment]
Thanks!

Is the full API documented somewhere?
