### ISSUE TITLE
Quoted numerics are treated inconsistently (CSV)

### ISSUE THREAD

**Issue by bean5** [SheetJS/js-xlsx#1012]
**Expected**
String numerics are either treated as dates or as numerics in JSON output.

**Actual**
Sometimes quoted numerics (for example `"11"`, `"2018"`) are treated as dates, but sometimes as numbers (example: `"10001"`). 

At first I was bothered by the fact that they are treated as dates, but then I realized it isn't consistent. It seems like they are being put through a call to `Date()` to determine whether they might be a date before they come out as JSON.

**Steps to reproduce**
Consider the following CSV contents for opening at http://oss.sheetjs.com/. Note that some numbers come out as dates while others do not.

```
"quoted small","quoted under 1900","quoted over 9999","not quoted",1899,1900,9999
"11","1899","10000",11,1899,1900,9999
```

**Disclaimer:** I tested with CSV only. Not sure what occurs for XLS. I assume XLS exports doesn't stringify numerics...

Keep up the good work!

**Comment by SheetJSDev** [comment]
Thanks for the heads up!  Turns out the worker script was pulling in an older version of the library, [fixing the reference](https://github.com/SheetJS/SheetJS.github.io/commit/b7bb01c0ed51c1e303a1f18837a4ec006f7df343) seems to have resolved the issue.

**Comment by bean5** [comment]
Thanks!
