### ISSUE TITLE
XLSX.utils.sheet_to_json returning empty array

### ISSUE THREAD

**Issue by thomasledoux1** [SheetJS/js-xlsx#1015]
Hey,

I am trying to give our users the possibility to upload an XLSX file (through ng-file-uploader), and to convert this XLSX file to JSON data afterwards.
The uploading of the file works fine, this is the result when I print $scope.file in the console: 
<img width="587" alt="screen shot 2018-03-02 at 10 08 16" src="https://user-images.githubusercontent.com/10978632/36891365-ac73e816-1e01-11e8-91ff-9f86620af2c6.png">

When I try to use the sheet to json function, I get an empty array back, while there is a lot of data in the uploaded XLSX file.

In my code I use the following: 
`XLSX.utils.sheet_to_json($scope.file);`

This returns an empty array as said before. 
Is there something I'm forgetting or should execute differently?

Kind regards,

Thomas

**Comment by thomasledoux1** [comment]
Update: I got the file into the XLSX tool now. I was able to create the workbook, but now I'm trying to use the XLSX.utils.sheet_to_json on one of the sheets inside the workbook in the following way, and I'm getting an error: 
`var roa = XLSX.utils.json_to_sheet(workbook)`
The error: 
<img width="530" alt="screen shot 2018-03-02 at 11 00 51" src="https://user-images.githubusercontent.com/10978632/36893632-133a1c30-1e09-11e8-8ab0-64632d6e0f10.png">

This is my workbook object: 
<img width="822" alt="screen shot 2018-03-02 at 11 02 47" src="https://user-images.githubusercontent.com/10978632/36893691-4b669886-1e09-11e8-8683-76abb6363742.png">

**Comment by jvicensfarrus** [comment]
any solution on this?

**Comment by jvicensfarrus** [comment]
@Xsmael I solved this setting a the name of the sheet you want to use and also the header, which might help you to identify each column.

```
var workbook = XLSX.read(bstr, {type:'binary'});
var form = XLSX.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[3]], {header:["headerName1","headerName2","headerName3"]});
```
I hope this helps you

**Comment by shamseerahammedm** [comment]
@jvicensfarrus proving headers just outputs an array with provided headers, no other sheet data is prasent ? anything else we need to do ?
```
const wb = XLSX.read( bufferArray, { type: 'buffer' } );
      const wsname = wb.SheetNames[7];
      const ws = wb.Sheets[wsname];
      const data = XLSX.utils.sheet_to_json(ws, {
        raw : true,
        header : ['Date','Currency','Income','Expense','Fee','Balance','Reason','Remarks']
      });
```

**Comment by jvicensfarrus** [comment]
> @jvicensfarrus proving headers just outputs an array with provided headers, no other sheet data is prasent ? anything else we need to do ?
> 
> ```
> const wb = XLSX.read( bufferArray, { type: 'buffer' } );
>       const wsname = wb.SheetNames[7];
>       const ws = wb.Sheets[wsname];
>       const data = XLSX.utils.sheet_to_json(ws, {
>         raw : true,
>         header : ['Date','Currency','Income','Expense','Fee','Balance','Reason','Remarks']
>       });
> ```

@shamseerahammedm 
you could try to not use constants and creating the 'ws' directly within the wb.SheetName[7]
```var wb = XLSX.read( bufferArray, { type: 'buffer' } );
      var ws = wb.SheetNames[7];
      var data = XLSX.utils.sheet_to_json(ws, {
        raw : true,
        header : ['Date','Currency','Income','Expense','Fee','Balance','Reason','Remarks']
      });```
