### ISSUE TITLE
Editing existing .xls and saving it to the server

### ISSUE THREAD

**Issue by BeginnerJS** [SheetJS/js-xlsx#1018]
Hi

What would be the simplest and fastest way to edit existing .xls file and then saving it to the server. By editing I mean, editing specific cells.

**Comment by SheetJSDev** [comment]
There are many different options, so you need to be specific.  Let's say you want to edit cell A1 of the first worksheet to say "HI".  The worksheet manipulation function would be:

```js
function change_workbook(wb) {
  // get the first worksheet
  var ws_name = wb.SheetNames[0];
  var ws = wb.Sheets[ws_name];

  // Change cell A1 to the text "HI"
  ws["A1"] = {
    t: 's', // <-- t: 's' indicates the cell is a text cell
    v: "HI" // <-- v holds the value
  };
}
```

If you are using node.js and the file resides on the server and you want to edit it in the location, you can read the file, then change and write the file:

```js
var XLSX = require('xlsx');
var wb = XLSX.readFile("original.xls");

change_workbook(wb); // ***

XLSX.writeFile(wb, "new.xls");
```

If the file resides on the client, you can upload and transform on the server side.  The [server demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/server) shows [how to read uploaded data using `formidable`](https://github.com/SheetJS/js-xlsx/tree/master/demos/server#responding-to-form-uploads):

```js
var formidable = require('formidable');
var XLSX = require('xlsx');
var server = http.createServer(function(req, res) {
	var form = new formidable.IncomingForm();
	form.parse(req, function(err, fields, files) {
		var f = files[Object.keys(files)[0]];
		var wb = XLSX.readFile(f.path);

		change_workbook(wb); // ***

		res.setHeader('Content-Disposition', 'attachment; filename="download.xls";');
		res.end(XLSX.write(wb, {type:"buffer", bookType:ext})); // send the new file back to the client
	});
}).listen(PORT);
```

You can also transform on the client side and upload:

```js
// assuming <input type="file" name="xlfile" id="xlf" /> is somewhere in the page 
function do_file(files) {
	var f = files[0];
	var reader = new FileReader();
	reader.onload = function(e) {
		var data = e.target.result;
		var wb = X.read(data, {type: 'binary'}));

		change_workbook(wb); // ***
		
		// the rest is explained in the XHR demo
		var wbout = XLSX.write(wb, {bookType:'xls', type:'base64'});
		var fd = new FormData();
		fd.append('data', wbout);
		var req = new XMLHttpRequest();
		req.open("POST", "/upload", true);
		req.send(fd);
	};
	reader.readAsBinaryString(f);
};

var xlf = document.getElementById('input_element');
xlf.addEventListener('change', function(e) { do_file(e.target.files); }, false);
```

**Comment by fthdgn68** [comment]
İt doesn't work. I tried, when I send base 64 type I can't get files field. Is there any way to rewrite file type?

**Comment by fthdgn68** [comment]
It doesn't work.

**Comment by fthdgn68** [comment]
It doesn't work.

**Comment by fthdgn68** [comment]
It doesn't work.

**Comment by fthdgn68** [comment]
It doesn't work.

**Comment by fthdgn68** [comment]
It doesn't work.

**Comment by fthdgn68** [comment]
It doesn't work.

**Comment by fthdgn68** [comment]
It doesn't work.

**Comment by fthdgn68** [comment]
It doesn't work.

**Comment by fthdgn68** [comment]
It doesn't work.

**Comment by felippi** [comment]
If the field not exist, you need use sheet_add_aoa:

`function change_workbook(wb) {
  // get the first worksheet
  var ws_name = wb.SheetNames[0];
  var ws = wb.Sheets[ws_name];

  // Change cell A1 to the text "HI"
  ws["A1"] = {
    t: 's', // <-- t: 's' indicates the cell is a text cell
    v: "HI" // <-- v holds the value
  };
  // Add if not exist cell on original
  XLSX.utils.sheet_add_aoa(ws, [["HI"]], {origin: 'A1'});
}`

**Comment by felippi** [comment]
If the field not exist, you need use sheet_add_aoa:

```javascript
function change_workbook(wb) {
// get the first worksheet
var ws_name = wb.SheetNames[0];
var ws = wb.Sheets[ws_name];

// Change cell A1 to the text "HI"
ws["A1"] = {
t: 's', // <-- t: 's' indicates the cell is a text cell
v: "HI" // <-- v holds the value
};
// Add if not exist cell on original
XLSX.utils.sheet_add_aoa(ws, [["HI"]], {origin: 'A1'});
}
```
