### ISSUE TITLE
issue downloading xlsx file

### ISSUE THREAD

**Issue by inimesh07** [SheetJS/js-xlsx#1020]
I am using angular 4 and was able to successfully download an excel file  using the XLSX using the "0.11.8". However, when i took the latest version "0.12.3" the functionality break. The file was downloaded with correct size but showed as having corrupted data.

**Comment by reviewher** [comment]
Can't reproduce with the demo project https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2 .  Can you share a project showing the error?

**Comment by sergcamc13** [comment]
Having exactly the same issue after upgrading XLSX to latest version:
Here my stack technology:
Angular CLI: 1.7.3 (e)
Node: 7.10.1
OS: win32 x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.7.2
webpack-dev-server: 2.11.2

**Comment by SheetJSDev** [comment]
Can't reproduce using the demo, @sergcamc13 please try to reproduce using the following steps and see if it works:

Switch to node 7.10.1 using `nvm` or `n`, then

```
npm install -g @angular/cli
ng new SheetJS
cd SheetJS
ng version
```

Go into the project and:

- replace `src/index.html` with the demo https://raw.githubusercontent.com/SheetJS/js-xlsx/master/demos/angular2/src/index.html
- replace `src/app/app.module.ts` with the demo https://raw.githubusercontent.com/SheetJS/js-xlsx/master/demos/angular2/src/app/app.module.ts
- create a new file `src/app/sheetjs.component.ts` using the demo https://raw.githubusercontent.com/SheetJS/js-xlsx/master/demos/angular2/src/app/sheetjs.component.ts

Then run `ng serve` to start the server, go to http://localhost:4200 using Chrome 65 (64-bit) and click "Export" and try to open the generated file.

---

P.S.: 

1) The displayed typescript version is 2.5.3 and it uses webpack 3.11.0:

```
Angular CLI: 1.7.3
Node: 7.10.1
OS: darwin x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

2) NPM does not show any version `1.7.3 (e)`.  Run `npm show @angular/cli versions --json` to see:

```
  "1.7.0",
  "1.7.1",
  "1.7.2",
  "1.7.3",  <-- current version
  "6.0.0-beta.2",
  "6.0.0-beta.3",
  "6.0.0-beta.4",
  "6.0.0-beta.5"
```

**Comment by sergcamc13** [comment]
Now its working for me with latest version of xlsx ("xlsx": "^0.12.5")
I just replaced my code by the one provided in the sheetjs.component.ts
Thank you for your help

**Comment by xiaoyaoyao** [comment]
Hi,I met the same problem,How can  I  fix this issue?
