### ISSUE TITLE
Uncaught Error: Cannot access file .....  

### ISSUE THREAD

**Issue by BeginnerJS** [SheetJS/js-xlsx#1021]
I am trying to read XLSX file one cell data. but I get an error "Uncaught Error: Cannot access file"
My coal is to replace one cell value to the variable _hind_ 
I attached the full code as well. 

My code:

**JS**
[New Text Document.txt](https://github.com/SheetJS/js-xlsx/files/1784104/New.Text.Document.txt)
[js.txt](https://github.com/SheetJS/js-xlsx/files/1784105/js.txt)
`
    var workbook = XLSX.readFile('Hinnapakkumine.xlsx');
    /* DO SOMETHING WITH workbook HERE */
    var first_sheet_name = workbook.SheetNames[0];
    var address_of_cell = 'G18';

    /* Get worksheet */
    var worksheet = workbook.Sheets[first_sheet_name];

    /* Find desired cell */
    var desired_cell = worksheet[address_of_cell];

    /* Get the value */
    var desired_value = (desired_cell ? desired_cell.v : undefined);
    window.alert(desired_value);
`

**Comment by SheetJSDev** [comment]
Unfortunately [you can't use `readFile` in the browser](https://docs.sheetjs.com/#parsing-workbooks):

> `readFile` is only available in server environments. Browsers have no API for reading arbitrary files given a path, so another strategy must be used.

Demos like http://oss.sheetjs.com/js-xlsx show drag and drop as well as file input elements.  Other examples are listed [in the README](https://github.com/sheetjs/js-xlsx#parsing-workbooks).
