### ISSUE TITLE
Missing Types - Typescript definitions excluded from npm and bower

### ISSUE THREAD

**Issue by two-bridges** [SheetJS/js-xlsx#1023]
I'm not finding typing files for xlsx/js-xlsx.  

What's the recommended way to acquire the `index.d.ts` file?  

- Tried `npm install xlsx`.  No types found in xlsx folder (however the dependent cfb and ssf packages ***do*** include their typings).  
- Tried `bower install js-xlsx`.  No types found in js-xlsx folder (in this case, no typings for cfb or ssf either).  
- Tried `npm @types/xlsx`.  This was empty.  Just a message saying to get the types from `npm install xlsx`.  

cheers

**Comment by SheetJSDev** [comment]
They are included in the [`/types/index.d.ts` file in the npm package](https://unpkg.com/xlsx/types/index.d.ts).  The `package.json` in the npm module references it.

To be sure, test with visual studio code with a typescript file with the contents

```typescript
import * as XLSX from 'xlsx'

XLSX.utils.aoa_to_sheet
```

It appeared to find the correct type definitions:

<img width="1074" alt="" src="https://user-images.githubusercontent.com/6070939/37067620-a3a9014c-2178-11e8-8aa1-5261b2f115a2.png">

**Comment by two-bridges** [comment]
For me, types is missing from node_modules/xlsx/types:
![image](https://user-images.githubusercontent.com/1709902/37068005-bb1721fa-2200-11e8-87f0-e906fbea3e4f.png)

Update:
I re-ran `node install xlsx --save` and `types` now appears! 
![image](https://user-images.githubusercontent.com/1709902/37068106-2a9fb03c-2201-11e8-9dfb-21b5046e1eb1.png)

Thanks for the response, I'm closing this issue now.
