### ISSUE TITLE
CSV file seems different depending on the program.

### ISSUE THREAD

**Issue by hr5959** [SheetJS/js-xlsx#1024]
I made a csv file:
var stream = XLSX.stream.to_csv(ws);
stream.pipe(fs.createWriteStream(fileName));

then uploaded the file to S3 and returned url.

When I download the file and open it, it looks well on my pc. (open on OS X using Numbers.)
But when I trying to open the same file on window OS using ms office, characters are broken.
it's Korean characters. and I want to encode the file UTF-8.
How can I resolve this problem?

it's the file.
[20180307105408.csv.zip](https://github.com/SheetJS/js-xlsx/files/1787451/20180307105408.csv.zip)

**Comment by SheetJSDev** [comment]
The utility currently doesn't (but should) write the UTF8 BOM.  As a temporary workaround:

```js
var stream = XLSX.stream.to_csv(ws);
var out = fs.createWriteStream(fileName);
out.on('open', function(fd) {
  out.write(new Buffer([0xEF,0xBB,0xBF]));
  stream.pipe(out);
});
```

If you would like to contribute a fix, in the [`write_csv_stream` function](https://github.com/SheetJS/js-xlsx/blob/master/bits/97_node.js#L18) add a line to push the BOM if it hasn't been written:

```js
var BOM = false;
stream._read = function() {
	if(!BOM) { BOM = true; return stream.push("\uFEFF"); }
```

**Comment by hr5959** [comment]
It works. Thanks!!
