### ISSUE TITLE
Datatable to xlsx

### ISSUE THREAD

**Issue by Jcardo97** [SheetJS/js-xlsx#1029]
I can transfer a table to xlsx?

**Comment by SheetJSDev** [comment]
For a single HTML table on a web page:

```js
var table_dom_elt = document.getElementById("data-table");
var wb = XLSX.utils.table_to_book(table_dom_elt);
XLSX.writeFile(wb, "export.xlsx");
```

If you are using a library like [`canvas-datagrid`](https://github.com/TonyGermaneri/canvas-datagrid) the documentation will generally tell you how to export data as an array of arrays or an array of row objects.  [`json_to_sheet`](https://docs.sheetjs.com/#array-of-objects-input) will generate a worksheet object from an array of objects, and [`aoa_to_sheet`](https://docs.sheetjs.com/#array-of-arrays-input) generates a worksheet object from an array of arrays of data.
