### ISSUE TITLE
usage in typescript file

### ISSUE THREAD

**Issue by Apul800010** [SheetJS/js-xlsx#1032]
Hi,
Can you please send / upload .d.ts file for xlsx-style, so that it can be used in typescript file and can be imported there.

**Comment by reviewher** [comment]
Types are included in the [`xlsx` npm package at `/types/index.d.ts`](https://unpkg.com/xlsx/types/index.d.ts)

**Comment by Apul800010** [comment]
Hi,
It's there for XLSX and not for xlsx- style.

Is there any  way to style cell background using XLSX only.

**Comment by Apul800010** [comment]
Have been trying to make use of "Cell.s" , but not able to.
Tried giving the styles format in xml and json, but with no success.
Since am not able to use style using xlsx, have asked for xlsx-style .d.ts file or
any way to include style using xlsx.
below is my code:

public exportAsExcelFile(json: any[], excelFileName: string): void {
        const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
        var wscols = [
            { width: 20 },
            { width: 15 },
            { width: 20 },
            { width: 15 },
            { width: 13 },
            { width: 15 },
            { width: 30 },
            { width: 15 }
        ];

        worksheet['!cols'] = wscols;
        worksheet['!rows'] = [{ hpx: 40 }];

        const workbook: XLSX.WorkBook = { Sheets: { 'data': worksheet }, SheetNames: ['data'] };
        const excelBuffer: any = XLSX.write(workbook, { bookType: 'xlsx', type: 'array', cellDates: true, cellStyles: true });
        this.saveAsExcelFile(excelBuffer, excelFileName);
    }

    private saveAsExcelFile(buffer: any, fileName: string): void {
        const data: Blob = new Blob([buffer], {
            type: EXCEL_TYPE
        });
        FileSaver.saveAs(data, fileName + '_export_' + new Date().getTime() + EXCEL_EXTENSION);
    }
