### ISSUE TITLE
How to use xlsx-style in typescript file

### ISSUE THREAD

**Issue by Apul800010** [SheetJS/js-xlsx#1034]
Have been trying to make use of "Cell.s" in XLSX, but not able to.
Tried giving the styles format in xml and json, but with no success.
Since am not able to use style using xlsx, have asked for xlsx-style .d.ts file or
any way to include style using xlsx.
below is my code:

It would be very helpful if you are able to provide any example where i can give background colour in cell row or header using XLSX (in typescript file, please don't give for .js)

public exportAsExcelFile(json: any[], excelFileName: string): void {
const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
var wscols = [
{ width: 20 },
{ width: 15 },
{ width: 20 },
{ width: 15 },
{ width: 13 },
{ width: 15 },
{ width: 30 },
{ width: 15 }
];

    worksheet['!cols'] = wscols;
    worksheet['!rows'] = [{ hpx: 40 }];

    const workbook: XLSX.WorkBook = { Sheets: { 'data': worksheet }, SheetNames: ['data'] };
    const excelBuffer: any = XLSX.write(workbook, { bookType: 'xlsx', type: 'array', cellDates: true, cellStyles: true });
    this.saveAsExcelFile(excelBuffer, excelFileName);
}

private saveAsExcelFile(buffer: any, fileName: string): void {
    const data: Blob = new Blob([buffer], {
        type: EXCEL_TYPE
    });
    FileSaver.saveAs(data, fileName + '_export_' + new Date().getTime() + EXCEL_EXTENSION);
}

**Comment by Apul800010** [comment]
Also please don't give link for .d.ts file of XLSX, because i already have it.
need the same for XLSX-style

**Comment by reviewher** [comment]
See https://github.com/SheetJS/js-xlsx/issues/1032 -- this is the repo for the `xlsx` project.
