### ISSUE TITLE
sheet_to_json not generating keys for cells containing '#N/A'

### ISSUE THREAD

**Issue by arijitkanrar** [SheetJS/js-xlsx#1035]
To begin with, Thank you so much for this library! It has been a lifesaver!
I've been able to do so much with it. 

Been stuck with an issue. 
I've a large excel sheet (~5500 rows with around 35 columns).
Some columns have a value of '#N/A' (formula referring to a missing value) and some have the text '#N/A' in them. 
When I use sheet_to_json with the option {defval : null} but the keys are missing in the generated JSON. 

Any idea why it might be?

Thanks Again!

Arijit

**Comment by SheetJSDev** [comment]
Currently, [Error cells are explicitly suppressed](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L60), even if a default value is specified.  That probably should be changed.
