### ISSUE TITLE
Sheetname invalid character leads to binary error within excel file

### ISSUE THREAD

**Issue by GPlay97** [SheetJS/js-xlsx#1039]
Hello!

Using characters such as `\` within the sheet name, are automatically detected as invalid and the sheetname then gets automatically reverted to default ("Sheet1") for example.

However, when I have a sheet name with a `&` character, the sheet name will not be sanitized.

Then, when I try to open the generated excel file, the excel file is corrupt. It shows me a binary error input/output error. No matter, which application I use.

That's the code

// sheet.name is "Foo Bar &" 
wb.SheetNames.push(sheet.name); 
wb.Sheets[sheet.name] = sheet_from_array_of_arrays(sheet.data);

Thanks in advance.

**Comment by SheetJSDev** [comment]
I can't reproduce this in node or browser for the `xlsx / xlsb / xls / xml` formats.  Here's a fiddle: https://jsfiddle.net/sheetjs/kv0yq5ru/

```js
//var XLSX = require("xlsx"); // uncomment in nodejs
var wb = XLSX.utils.book_new();
var ws = XLSX.utils.aoa_to_sheet([["a","b"],[1,2]]);
XLSX.utils.book_append_sheet(wb, ws, "Foo Bar &");
["xlsx", "xlsb", "xls", "xml"].forEach(n => XLSX.writeFile(wb, "issue1039." + n));
```

Make sure you are using the latest version.  If it is still reproducible from the latest version, can you console.log(wb) and share the output?
