### ISSUE TITLE
hidding the cellComment or object for cell

### ISSUE THREAD

**Issue by abhishek4kahol** [SheetJS/js-xlsx#1047]
Can we add cellComment or object to a cell while writing the xlsx file, which cannot be visible to a user reading the sheet, but can be readable while reading the file programmatically, which can later be used for further operations.

**Comment by SheetJSDev** [comment]
If you really need to hide data in a workbook, the most common approach is to add a column and hide it.  If you don't want the user to be able to see or access the data, there's an alternative involving very hidden worksheets.  See https://github.com/SheetJS/js-xlsx/blob/gh-pages/tests/write.js#L131 for an example.  Very hidden worksheets are not available in the UI normally -- you have to go into VBA editor to change the visibility back to hidden or visible

**Comment by abhishek4kahol** [comment]
sorry for responding late but can you help me how to use veryHidden, I use it the same way we use hidden but it's not working.

and can we use the hidden property on author of the comment.
