### ISSUE TITLE
file type 'zip archive', not compatible with some app

### ISSUE THREAD

**Issue by Dotcra** [SheetJS/js-xlsx#1048]
I'm using **bookType 'xlsx'** to generate xlsx files, and I found they can not be read by some apps. 
I check the **file type**, and it shows that js-xlsx generates 'xlsx' files with file type  **'Zip archive data'**, not like normal xlsx files have **'Microsoft Excel 2007+'** file type.

```
[230018 dot@anne ~]$ file l/stat.xlsx 
l/stat.xlsx: Microsoft Excel 2007+
[230027 dot@anne ~]$ file l/test.xlsx 
l/test.xlsx: Zip archive data, at least v1.0 to extract
```
Actually, I don't know if this is the reason causing the problem. But is **'Zip archive data'** what we expected?

**Comment by SheetJSDev** [comment]
XLSX files are in fact ZIP files that contain entries according to the Open Packaging Conventions.  The actual magic used by the file program is flawed, and we've had an email conversation with Ralf Brown on the matter.

If the generated files can be read by Excel but not by some other apps, it's likely a bug with the reader app (out of curiosity, what app?)
