### ISSUE TITLE
Browse button to Drag and Drop

### ISSUE THREAD

**Issue by varunchandran333** [SheetJS/js-xlsx#1049]
I want to make the browse file button to a Drag and drop Style.
I have tried to add Dropify but gives
**Cannot read property '0' of undefined** this error.
Suggest me some methods to change that browse button?

**Comment by reviewher** [comment]
If you are talking about https://github.com/JeremyFagis/dropify, it appears to read in as base64:

```js
            reader.readAsDataURL(file);
            reader.onload = function(_file) {
                srcBase64 = _file.target.result;
```

You should be able to read with type `"base64"` after stripping out the header (there will be a comma before the actual data starts).
