### ISSUE TITLE
Compute formula value after change

### ISSUE THREAD

**Issue by BrunoMarchesson** [SheetJS/js-xlsx#105]
Hello,

Not sure that it is an issue or a known limitation, but is it possible to refresh/recompute a formula value after changing a cell one ?
(for example, C1 has formula A1+B1, and I would like to get the C1 value updated after changing A1 value).

**Comment by greyarch** [comment]
Is there any progress on the basic formula support? Would be much appreciated.

**Comment by fabiooshiro** [comment]
@d00001 I started a project, the goal is to make easy to any one write contributions to cover the xlsx formulas.
```js
XLSX_CALC.set_fx('ABS', function(num) {
  return Math.abs(num);
});
```
see the code at https://github.com/fabiooshiro/xlsx-calc

**Comment by reviewher** [comment]
There are packages that do this exact thing, like https://github.com/fabiooshiro/xlsx-calc,

**Comment by SheetJSDev** [comment]
The formula bodies are currently round-tripped (so if you read a file, edit a value, write a new file and open the new file in Excel, you will see the new values).  Formula recalculation is supported in the Pro version and we may eventually make it open source.
