### ISSUE TITLE
Cannot use XLSX.utils.aoa_to_sheet on Angular 4 and SystemJs

### ISSUE THREAD

**Issue by hungnguyenhee** [SheetJS/js-xlsx#1054]
I follow this thread [#618](https://github.com/SheetJS/js-xlsx/issues/618)  but cannot manage to make the XLSX to work, still return error:

XLSX.utils.aoa_to_sheet is not a function 

Any clear configuration for Angular 4 + SystemJS that can work now?

Thank you.

**Comment by reviewher** [comment]
You are probably using an older version.  Try updating to the latest version and see if the error shows up.
