### ISSUE TITLE
chinese Language problem.

### ISSUE THREAD

**Issue by sangeethaharidass** [SheetJS/js-xlsx#1060]
I am upload chinese file to upload but i am getting character in wrong format while i am using uploaded file as csv file.please any one to help me.

[Upload Template_Planner问卷申请模板.xlsx](https://github.com/SheetJS/js-xlsx/files/1867336/Upload.Template_Planner.xlsx)

**Comment by SheetJSDev** [comment]
If you are passing UTF8-encoded CSV, the file must start with the UTF8 BOM.  If it does not start with a BOM, you can override with the option [`codepage:65001`](https://docs.sheetjs.com/#parsing-options).

If you are using Simplified or Traditional Chinese, you have to set the appropriate codepage (936 for Simplified, 950 to Traditional).
