### ISSUE TITLE
Writing array of numeric to numeric

### ISSUE THREAD

**Issue by nagro** [SheetJS/js-xlsx#1067]
Hi, I'm trying to write an array of numbers to xlsx. The problem is that when i open the xlsx file with excel, the number a considered as string an i cannot use excel to sort them. Is it something wrong in my code?
`var myflag = true;
    try { var wb = XLSX.readFile('myfinalstats.xlsx', {cellNF:true});
  }
    catch(err) {
       var wb = XLSX.utils.book_new();
     
      var ws = XLSX.utils.aoa_to_sheet([
        ["ID", "Temps", "nombre 1", "nombre 2", "nombre 3",
         "nombre 4", "nombre 5", "nombre 6", "nombre 7", "nombre 8",
          "nombre 9", "nombre 10", "nombre 11", "nombre 12", "nombre 13",
           "nombre 14", "nombre 15", "nombre 16", "nombre 17", "nombre 18",
            "nombre 19", "nombre 20", "somme 5 premiers", "total"]
      ]);
      myflag = false;
    };
      
 if (myflag) {
    var ws = wb.Sheets['stats'];
 }
    XLSX.utils.sheet_add_aoa(ws, result, {origin: -1});
     if (!myflag) XLSX.utils.book_append_sheet(wb, ws, "stats");
    XLSX.writeFile(wb, 'myfinalstats.xlsx');`

**Comment by SheetJSDev** [comment]
You didn't include the `result` value, but if result contains strings then the final result will be a string.  Here's an example showing the difference: https://jsfiddle.net/sheetjs/t2wp8xzr/

```js
/* A2:A3 will be text, B2:B3 will be numeric */
var ws = XLSX.utils.aoa_to_sheet([
  ["Text", "Number"],
  ["123", 123],
  ["0.1", 0.1]
]);
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "result");
XLSX.writeFile(wb, "issue1067.xlsx");
```
