### ISSUE TITLE
Add new row to Exel

### ISSUE THREAD

**Issue by illonage** [SheetJS/js-xlsx#1069]
Hi,

I am using your package for a project. It is great but I have a quick question: How do you add a row to an existing excel document please?

**Comment by SheetJSDev** [comment]
If you want to add a row to the end of a worksheet, there are two helper functions [`sheet_add_aoa`](https://docs.sheetjs.com/#array-of-arrays-input) and [`sheet_add_json`](https://docs.sheetjs.com/#array-of-objects-input).

Calling either function with the option `origin:-1` adds to the end of the worksheet:

```js
XLSX.utils.sheet_add_aoa(worksheet, [
  ["new data", 1, 2, 3]
], {origin: -1});
```

Here's a sample fiddle which fetches an XLS file, adds a new row to the first worksheet and exports to XLSX: https://jsfiddle.net/sheetjs/y459abLf/

<details><summary><b>Fiddle code</b> (click to show)</summary>

```js
fetch('https://crossorigin.me/https://obamawhitehouse.archives.gov/sites/default/files/omb/budget/fy2014/assets/receipts.xls').then(r => r.arrayBuffer()).then(r => {
  var wb = XLSX.read(r, {type:"array"});
  var ws = wb.Sheets[wb.SheetNames[0]];
  XLSX.utils.sheet_add_aoa(ws, [
    ["new data", 1, 2, 3]
  ], {origin: -1});
  XLSX.writeFile(wb, 'new.xlsx');
});
```

</details>

**Comment by sy813** [comment]
> If you want to add a row to the end of a worksheet, there are two helper functions [`sheet_add_aoa`](https://docs.sheetjs.com/#array-of-arrays-input) and [`sheet_add_json`](https://docs.sheetjs.com/#array-of-objects-input).
> 
> Calling either function with the option `origin:-1` adds to the end of the worksheet:
> 
> ```js
> XLSX.utils.sheet_add_aoa(worksheet, [
>   ["new data", 1, 2, 3]
> ], {origin: -1});
> ```
> 
> Here's a sample fiddle which fetches an XLS file, adds a new row to the first worksheet and exports to XLSX: https://jsfiddle.net/sheetjs/y459abLf/
> 
> Fiddle code (click to show)

how to insert rows at the start of a sheet , do not replace data?

**Comment by Mohamad-Hamad91** [comment]
just set  {origin:"A1"} instead of {origin: -1}

**Comment by sampathmora** [comment]
how to insert data to start off the sheet after using table_to_sheet utility.

**Comment by gattinaroma** [comment]
@sdev-code 
My workaround is to add two empty row at the start of the table

```
const element = document.getElementById('my-table-id') as HTMLTableElement;
element.insertRow(0);
element.insertRow(0);
const ws: XLSX.WorkSheet = XLSX.utils.table_to_sheet(element);
const myNewData = [['My header']];
XLSX.utils.sheet_add_aoa(ws, myNewData);
const wb: XLSX.WorkBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, 'My sheet');
XLSX.writeFile(wb, 'myfilename.xlsx');
```

**Comment by smajot** [comment]
I needed a way to insert or delete rows at random locations in a vanilla xlsx. Couldn't find anything, so this is what I came up with. Might break formatting stored elsewhere in the template. Not sure.

`
wb = insert_delete_rows_at('insert', 6, 1, wb, 'Sheet1');
wb = insert_delete_rows_at('delete', 8, 1, wb, 'Sheet1');

function insert_delete_rows_at(action, origin_row, num_of_rows, wb, sheet_name) {
	
	let coords = Object.keys(wb['Sheets'][sheet_name]);
	coords = coords.filter(item => (item.charAt(0) != '!'));
	
	let incremented_coords = {};
	
	// this thing is the bounding coords i guess, so it needs to be incremented
	let wb_ref = wb['Sheets'][sheet_name]['!ref'];
	let wb_ref_arr = wb_ref.split(':');
	let deepest_coord = wb_ref_arr[1];
	
	let deepest_row, deepest_col;
	if (/\d/.test(deepest_coord.charAt(1))) {
		//second char in coord is a digit (e.g. A12)
		deepest_row = deepest_coord.substring(1);
		deepest_col = deepest_coord.substring(0, 1);
	}
	else {
		deepest_row = deepest_coord.substring(2);
		deepest_col = deepest_coord.substring(0, 2);
	}
	
	switch(action) {
		case "insert": 
			deepest_row = (parseInt(deepest_row) + parseInt(num_of_rows)).toString();
		break;
		case "delete":
			deepest_row = (parseInt(deepest_row) - parseInt(num_of_rows)).toString();
		break;
	}
	
	let new_wb_ref = 	wb_ref_arr[0] + ':' + deepest_col + deepest_row;
	wb['Sheets'][sheet_name]['!ref'] = new_wb_ref;

	for (let i=0; i<coords.length; i++) {
		
		let row, col;
		
		if (/\d/.test(coords[i].charAt(1))) {
			//second char in coord is a digit (e.g. A12)
			row = coords[i].substring(1);
			col = coords[i].substring(0, 1);

		}
		else {
			//second char in coord is NOT a digit (e.g. AC1)
			row = coords[i].substring(2);
			col = coords[i].substring(0, 2);
		}
		
		if (row >= origin_row) {
			// store the coords if they're >= to specified origin row
			let new_row;
			
			switch(action) {
				case "insert": 
					new_row = (parseInt(row) + parseInt(num_of_rows)).toString();
				break;
				case "delete":
					new_row = (parseInt(row) - parseInt(num_of_rows)).toString();
				break;
			}

			incremented_coords[coords[i]] = col + new_row;
		}
		
	}
	
	for (let orig_coord in incremented_coords) {
		// insert new rows prepended with an underscore so we don't overwrite the coords that 
		// haven't been copied yet
		let tmp_new_coord = '_'+incremented_coords[orig_coord];
		wb['Sheets'][sheet_name][tmp_new_coord] = wb['Sheets'][sheet_name][orig_coord];
	}
	
	for (let orig_coord in incremented_coords) {
		// now delete all the original coords
		let tmp_new_coord = '_'+incremented_coords[orig_coord];
		delete(wb['Sheets'][sheet_name][orig_coord]);
	}
	
	for (let orig_coord in incremented_coords) {
		// and finally, removed the underscore to make the tmp coords official
		let tmp_new_coord = '_'+incremented_coords[orig_coord];
		let real_new_coord = incremented_coords[orig_coord];
		wb['Sheets'][sheet_name][real_new_coord] = wb['Sheets'][sheet_name][tmp_new_coord];
		delete(wb['Sheets'][sheet_name][tmp_new_coord]);
	}
	
	return wb;
	
}
`

**Comment by aislanmaia** [comment]
I need to append new rows to a huge excel file. How to do it without to read the entiry file in the memory, which can potencially slowing down the process and heap out of memory error ?
