### ISSUE TITLE
How to get the name of the workbook ?

### ISSUE THREAD

**Issue by harsh-a1** [SheetJS/js-xlsx#1070]
I have read an excel and it is now available as a json object. But in the json there is nowhere the name of the excel file which was read to make the excel. Is the filename available in the parsed excel file json??

     function test(event){
            var XLSX = require('xlsx');

            var reader = new FileReader();

            reader.onload = function ( evt ) { 
                var data = evt.target.result;
                var wb = XLSX.read(data, {type: 'binary'});

                 /* IS THE FILENAME AVAILABLE IN THE "wb" OBJECT?? */

                debugger
                
            }
            reader.readAsBinaryString(event.target.elements.excelFile.files[0]);      
        }

Thanks

**Comment by reviewher** [comment]
It is not available in the object since the original excel file doesn't store the filename.  If you are using a `FileReader` you can get the [name from the File object](https://developer.mozilla.org/en-US/docs/Web/API/File/name):

```js
 function test(event){
        var XLSX = require('xlsx');

        var reader = new FileReader();

        var file = event.target.elements.excelFile.files[0]; // this is a File object
        var filename = file.name; // see https://developer.mozilla.org/en-US/docs/Web/API/File/name

        reader.onload = function ( evt ) { 
            var data = evt.target.result;
            var wb = XLSX.read(data, {type: 'binary'});

            // `filename` is available here

            debugger
            
        }
        reader.readAsBinaryString(file);      
    }
```

**Comment by harsh-a1** [comment]
:D how come i missed that...thanks
