### ISSUE TITLE
Decimal delimiter on utils.xlsx_to_csv

### ISSUE THREAD

**Issue by FrankvanZ** [SheetJS/js-xlsx#1071]
Hi there,

I was wondering if there would be the possibility to have a decimal delimiter as an optional argument in the xls_to_csv function. As per now the field containing the comma will get escaped. My requirements for the project I'm working on is that we can have a variable user chosen (toolwide) field separator as well as a decimal separator.

**Comment by SheetJSDev** [comment]
[`sheet_to_csv` takes an options argument](https://docs.sheetjs.com/#delimiter-separated-output) and the `FS` option controls the field separator.  It will correctly quote values that contain the delimiter.

If the file does not specify a number format, it uses the default `Number` conversion which uses the decimal point as separator.  If you want to manually override it, you can go back and edit the formatted text directly:

```js
/* ws is the worksheet you want to convert to CSV */
var range = XLSX.utils.decode_range(ws['!ref']);
for(var R = range.s.r; R <= range.e.r; ++R) {
  for(var C = range.s.c; C <= range.e.c; ++C) {
    var cell = ws[XLSX.utils.encode_cell({r:R, c:C})];
    if(!cell || cell.t !== 'n') continue;
    /* cell.w is the formatted text */
    cell.w = cell.v.toString(10).replace(/\./, NEW_DECIMAL_SEPARATOR);
  }
}
```
