### ISSUE TITLE
sheet_to_json does not skip blank rows

### ISSUE THREAD

**Issue by cemremengu** [SheetJS/js-xlsx#1078]
I have the following configuration which works fine in general:

```
    let lte = await XLSX.utils.sheet_to_json(workbook.Sheets['Sheet1'], {
      blankRows: false,
      defval: '',
    });
```

However, I have an excel with 14K rows. I deleted the values in all but one row for test (there is styling in empty rows such as borders and colors but no values). When parsing, sheetjs still attempts to parse all of 14K rows for some reason.

Any ideas what's causing it ?

**Comment by SheetJSDev** [comment]
Can you share the file?

**Comment by cemremengu** [comment]
@SheetJSDev  There has to be something with the file itself... If I copy contents to a new file, it would not behave like that
[sample.xlsx](https://github.com/SheetJS/js-xlsx/files/1925918/sample.xlsx)

**Comment by SheetJSDev** [comment]
This is a funny logical error: [when a default value is specified, the row is marked as nonempty](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L54).  That doesn't really make sense in retrospect.  The fix is simple:

```diff
--- a/bits/90_utils.js
+++ b/bits/90_utils.js
@@ -51,7 +51,7 @@ function sheet_to_json(sheet/*:Worksheet*/, opts/*:?Sheet2JSONOpts*/) {
                        val = dense ? sheet[R][C] : sheet[cols[C] + rr];
                        if(val === undefined || val.t === undefined) {
                                if(defval === undefined) continue;
-                               if(hdr[C] != null) { row[hdr[C]] = defval; isempty = false; }
+                               if(hdr[C] != null) { row[hdr[C]] = defval; }
                                continue;
                        }
                        v = val.v;
```

**Comment by sainiankit** [comment]
I'm currently using the version "0.14.0". I'm facing the same issue.
`
range.s.c = 0;
range.e.c = rules.length - 1;
const new_range = XLSX.utils.encode_range(range);
let excelInJSON = XLSX.utils.sheet_to_json(ws, { header: 1, blankRows: false, defval: '', range: new_range });
`
still parses all the blank rows. Does this issue still persists ?

**Comment by samimw** [comment]
@SheetJSDev I am getting same issue as @sainiankit.

using version 0.14.0 setting blankRows and defVal doesn't work:

`var sheetThreeArray = X.utils.sheet_to_row_object_array(workbook.Sheets[sheetThree], {blankRows: false, defval: ''});`

**Comment by CamiNefilim** [comment]
Hi, on version 0.14.2, I modified the plugin on the function adding on line 20545:

` if (typeof v === 'string' || v instanceof String) {
                v = v.toString().trim();
            }`

and modifying on line 20562

`if (v != null && v.toString().trim().length > 0) isempty = false;`

Complete function code:

` function make_json_row(sheet, r, R, cols, header, hdr, dense, o) {
        var rr = encode_row(R);
        var defval = o.defval, raw = o.raw || !o.hasOwnProperty("raw");
        var isempty = true;
        var row = (header === 1) ? [] : {};
        if (header !== 1) {
            if (Object.defineProperty) try { Object.defineProperty(row, '__rowNum__', { value: R, enumerable: false }); } catch (e) { row.__rowNum__ = R; }
            else row.__rowNum__ = R;
        }
        if (!dense || sheet[R]) for (var C = r.s.c; C <= r.e.c; ++C) {
            var val = dense ? sheet[R][C] : sheet[cols[C] + rr];
            if (val === undefined || val.t === undefined || val === " " ) {
                if (defval === undefined) continue;
                if (hdr[C] != null) { row[hdr[C]] = defval; }
                continue;
            }
            var v = val.v;
            if (typeof v === 'string' || v instanceof String) {
                v = v.toString().trim();
            }
            switch (val.t) {
                case 'z': if (v == null) break; continue;
                case 'e': v = void 0; break;
                case 's': case 'd': case 'b': case 'n': break;
                default: throw new Error('unrecognized type ' + val.t);
            }
            if (hdr[C] != null) {
                if (v == null) {
                    if (defval !== undefined) row[hdr[C]] = defval;
                    else if (raw && v === null) row[hdr[C]] = null;
                    else continue;
                } else {
                    row[hdr[C]] = raw ? v : format_cell(val, v, o);
                }
                if (v != null && v.toString().trim().length > 0) isempty = false;
            }
        }
        return { row: row, isempty: isempty };
    }`

**Comment by mehars-jalin** [comment]
I faced the same issue, and after spending 1 hour, I decided to take a look at the function and discovered that the keyname is NOT camelcase, as documented. So use, **blankrows** NOT blankRows

**Comment by zzbo** [comment]
> I faced the same issue, and after spending 1 hour, I decided to take a look at the function and discovered that the keyname is NOT camelcase, as documented. So use, **blankrows** NOT blankRows

It worked for me.

**Comment by zzbo** [comment]
Thanks for @mehars-jalin , it worked for me.

**Comment by Niveditanandy** [comment]
I am using version 0.8.2. Using:
var sheerray = X.utils.sheet_to_row_object_array(workbook.Sheets[sheet], {blankRows: false});

I opened my excel and added 2 rows. Later I deleted 1 row. Yet when I try to upload it,  sheet_to_row_objects takes 2 rows though I deleted 1 and uploaded.  Any fixes??

**Comment by b-hexsoul** [comment]
This is still happening. using { blankrows: true }

**Comment by b-hexsoul** [comment]
There is some issue with the sheet I was using. If you are running into an issue with { blankrows: false } then make sure to clear contents of all cells below.

**Comment by nithin-neewee** [comment]
@SheetJSDev  

Please help
//Note: Empty cell are there, shown when uploaded the excel but i need one favor
//how can i higlight the empty cell with border-color and an error message to the user for understanding the empty cell.


let workBook = null;
    let jsonData = null;
    this.fileData = this.files[0]
    const reader = new FileReader();
    const file = this.files[0];
    reader.onload = (event) => {
      const data = reader.result;
      workBook = XLSX.read(data, { type: 'binary' });
      jsonData = workBook.SheetNames.reduce((initial, name) => {
        const sheet = workBook.Sheets[name];
        
       this.fileData = XLSX.utils.sheet_to_json(sheet,{header:1,defval:"",blankrows :false 
//Note: Empty cell are there, shown when uploaded the excel but i need one favor
//how can i higlight the empty cell with border-color and an error message to the user for understanding the empty cell.
});
        
        
       alert(this.fileData)
       
this.router.navigate(['/demand']);
this.heroService.tableDemostructure.next( this.fileData)
        return initial;
      }, {}
     );
      var dataString = JSON.stringify(jsonData);
      localStorage.setItem("testJSON", dataString);

      let text = localStorage.getItem("testJSON");
let obj = JSON.parse(text);
//document.getElementById("demo").innerHTML = obj;
      //document.getElementById('output').innerHTML = dataString.slice(0, 300).concat("...");
      //this.setDownload(dataString);
    }
    
    reader.readAsBinaryString(file)

**Comment by crazyjat** [comment]
I am experiencing this issue when trying to read an xlsx file from user upload that contains empty formulas. For example, I have cells that are empty that contain a formula such as `=IF($A12 <> "", VLOOKUP(ObjectivesUI!G12,ENUM!E:F,2,0),"")`  The imported cells look like `{ t: "s", v: "" } and nothing I do will prevent them. 

Please help.

**Comment by ajmalhassan** [comment]
Can someone please help with the issue posted by @crazyjat [above](https://github.com/SheetJS/sheetjs/issues/1078#issuecomment-1154492739).

**Comment by SheetJSDev** [comment]
There are a number of semi-related questions after the issue was closed.

https://docs.sheetjs.com/docs/api/utilities#array-output documentation

The property is `blankrows` .  If the option is not specified, the default behavior depends on `header`:

- When `header` is `1`, the default is to generate blank rows. `blankrows` must be set to false to skip blank rows.
- When `header` is not `1`, the default is to skip blank rows. `blankrows` must be true to generate blank rows

--

@CamiNefilim @crazyjat @ajmalhassan the ultimate question is whether a blank string value has meaning.  Consider:

```js
var ws = XLSX.utils.aoa_to_sheet([
  ["a","b"], // "a" , "b"
  [],        // (no value) , (no value)
  ["",]      // (blank string), (no value)
]);
```

In this call, `sheet_to_json` will interpret the first row as headers by default.  The second row (first object in the result) is `{}`.  The third row (second object in the result) is `{a: ""}`.

In this call, `sheet_to_json` will skip blank rows (since we did not specify `header: 1`).  The `{a: ""}` object is generated since the `a` property has a value.

We could consider modifying the behavior, but that is a separate discussion (please leave feedback at https://git.sheetjs.com/sheetjs/sheetjs/issues/2836 )

The workaround is to filter the result using `Array#filter` and `Object.values`:

```js
var data = XLSX.utils.sheet_to_json(ws);
var filtered = data.filter(row => Object.values(row).some(v => v !== ""));
```
