### ISSUE TITLE
'dist/cpexcel'  is missing

### ISSUE THREAD

**Issue by 6gunner** [SheetJS/js-xlsx#1079]
This relative module was not found when I update version to 0.12.10

* ./dist/cpexcel.js in ./node_modules/xlsx/xlsx.js

**Comment by 6gunner** [comment]
![image](https://user-images.githubusercontent.com/7445659/39092416-f6a75998-463f-11e8-8308-fb47055973a3.png)

**Comment by SheetJSDev** [comment]
The module structure hasn't changed, and [the `dist/cpexcel.js` file is in the `0.12.10` tarball](https://unpkg.com/xlsx@0.12.10/dist/).  How are you trying to load the script?  (note, in a browser context, you should load the dist file `dist/xlsx.full.min.js` directly)

**Comment by 6gunner** [comment]
For now, it's restored. (BTW:  I am using `import xlsx from 'xlsx'` before. The error is reported by webpack )
![image](https://user-images.githubusercontent.com/7445659/39172532-a0a33706-47d4-11e8-8a9e-0997cf9f70a4.png)

**Comment by gotexis** [comment]
I having the same problem in 2020 - using vue 2

```

This relative module was not found:

* ./ in ./node_modules/@vue/cli-plugin-typescript/node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--13-2!./node_mo
dules/@vue/cli-plugin-typescript/node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/modules/transfer/List.vue?vue&type=scri
pt&lang=ts&

```


google search points me here, but wtf is this

**Comment by SheetJSDev** [comment]
@gotexis Can you check what version of xlsx you are trying to import, and can you share a code snippet / a small project so we can dig further?
