### ISSUE TITLE
Excel could not open file_name.xlsx because some content is unreadable. Do you want to open and repair this workbook?

### ISSUE THREAD

**Issue by tilakz** [SheetJS/js-xlsx#1081]
I am generating xlsx file with Node and Hapi. After clicking on open and repair, I am able to see the file, and this is one of the line it shows in Repair Result.xml file created by Microsoft Excel. <repairedPart>Repaired Part: /xl/worksheets/sheet1.xml with XML error.  Load error. Line 2, column 182.</repairedPart>. Please help me with this.

     /* generate workbook */
      const ws = XLSX.utils.aoa_to_sheet(finalInput);
      const wb = XLSX.utils.book_new();

    XLSX.utils.book_append_sheet(wb, ws, 'Sheet');
    /* generate buffer */
    const buf = XLSX.write(wb, { type: 'buffer', bookSST: true, bookType: 'xlsx' });

     return reply(buf)
         .header('Content-Disposition', `attachment; filename= ${file_name}.xlsx`)
         .type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');

**Comment by SheetJSDev** [comment]
Try writing the buffer to a file and opening it:

```js
/* generate buffer */
const buf = XLSX.write(wb, { type: 'buffer', bookSST: true, bookType: 'xlsx' });
/* write to test.xlsx */
fs.writeFileSync("test.xlsx", buf); // <-- add this line to your code
/* send the file back to client */
return reply(buf)
     .header('Content-Disposition', `attachment; filename= ${file_name}.xlsx`)
     .type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
```

That should write a file `"test.xlsx"` that you can open.

If that file is valid, then there's something happening with how Hapi is transmitting binary data and you should raise an issue with them.  

If that file is not valid, then there's an issue with the library, and we would ask if you could share the generated file.

**Comment by yonimoses** [comment]
Same here, not on node, but rather angular 5. (2+) code is 

`const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet( json );
    const workbook: XLSX.WorkBook = {Sheets: {'data': worksheet}, SheetNames: [ 'data' ]};
    const excelBuffer: any = XLSX.write( workbook, {bookType: 'xlsx', type: 'buffer'} );
    const data: Blob = new Blob( [ excelBuffer ], {
      type: EXCEL_TYPE
    } );`

**Comment by tilakz** [comment]
@SheetJSDev I transpose the data because there were many columns, the issue is solved. I think issue isn't with SheetJS. Thanks.

**Comment by reviewher** [comment]
@yonimoses in the browser, use type `"array"` before constructing the blob.  Alternatively, use the `writeFile` helper function: `XLSX.writeFile(workbook, "out.xlsx")`.

@tilakz the writer now automatically truncates if you try writing beyond the number of columns that Excel supports.

**Comment by yonimoses** [comment]
@reviewher 
Cheers, works!

**Comment by himanshusaini-fa** [comment]
But transposing is not always an option like in my case. Running on node 12+ when I preview the json data or write it it gives no error. But trying to read that file it says heap out of memory.

**Comment by reviewher** [comment]
@himanshusaini-fa that sounds like an unrelated issue, can you raise a new issue with the file that gives you the "heap out of memory" error?

**Comment by himanshusaini-fa** [comment]
@reviewher  turns out I was just writing the unprocessed data which caused the error as unprocessed data had too many columns.
