### ISSUE TITLE
An array without keys will be sliced ？

### ISSUE THREAD

**Issue by wkchen66** [SheetJS/js-xlsx#1083]
```
  let ws = XLSX.utils.json_to_sheet(data)
  let wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "SheetJS")
```
 data like  ["one", "two", "three"]

 |1|2|3|
 |o|n|e|
 |t|w|o|

**Comment by reviewher** [comment]
`json_to_sheet` expects an array of objects.  Under the hood, it [loops across the keys of each entry](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L193-L194).

The keys of a string literal are the numeric indices, and the values are the individual characters:

```js
Object.entries("one") // [ [ '0', 'o' ], [ '1', 'n' ], [ '2', 'e' ] ]
```

So when the converter sees the string `"one"`, it is interpreted in the same way as the object `{0:"o", 1:"n", 2:"e"}`!

You should always pass objects.  If you intend to export a single row, you should use `aoa_to_sheet`:

```js
let data = [
    ["one", "two", "three"]
];
let ws = XLSX.utils.aoa_to_sheet(data)
let wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "SheetJS")
```

That will generate a single row with A1="one", B1="two", and C1="three"
