### ISSUE TITLE
How to transpose the data in xlsx file, data consists of array of arrays

### ISSUE THREAD

**Issue by tilakz** [SheetJS/js-xlsx#1085]
/* generate workbook */
    const ws = XLSX.utils.aoa_to_sheet(finalInput);
    const wb = XLSX.utils.book_new();
   
    XLSX.utils.book_append_sheet(wb, ws, 'Sheet');
    /* generate buffer */
    const buf = XLSX.write(wb, { type: 'buffer', bookSST: true, bookType: 'xlsx' });
    /* send to client */
    return reply(buf)
      .header('Content-Disposition', `attachment; filename= ${file_name}.xlsx`)
      .type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    
<img width="866" alt="screen shot 2018-04-25 at 6 56 40 pm" src="https://user-images.githubusercontent.com/24534864/39277252-e5535250-48ba-11e8-876c-ffea3c28ae4e.png">
(url)

**Comment by reviewher** [comment]
The utility assumes that the data will be written in row-major order.  You can [transpose the data before writing](https://github.com/SheetJS/js-xlsx/tree/master/demos/array#exporting-typed-arrays-to-a-worksheet):

```js
var aoa = [];
for(var i = 0; i < finalInput.length; ++i) {
  for(var j = 0; j < finalInput[i].length; ++j) {
    if(!aoa[j]) aoa[j] = [];
    aoa[j][i] = finalInput[i][j];
  }
}
const ws = XLSX.utils.aoa_to_sheet(aoa);
```

**Comment by tilakz** [comment]
@reviewher that worked out, thanks!

**Comment by mifff-lunglinh** [comment]
Hi, what is finalInput here?
