### ISSUE TITLE
any possibility of skipping the Sheet name while generating the json

### ISSUE THREAD

**Issue by skorlepara** [SheetJS/js-xlsx#1086]
Hi Team,
am new to Sheet Js library is there any possibility to avoid the name and read the readme file didn't find much Information.What changes need to be done to get the expected result
current Code:
	var to_json = function to_json(workbook) {
		var result = {};
		workbook.SheetNames.forEach(function(sheetName) {
			var roa = X.utils.sheet_to_json(workbook.Sheets[sheetName], {header:[ "EntityName","StateID","City","County","TypeOfBusiness","Date", "Email"], range:1});
			if(roa.length) result[sheetName] = roa;
		});
		return JSON.stringify(result, 2, 2);
		
	};

![image](https://user-images.githubusercontent.com/38859317/39430098-dc39465e-4c5a-11e8-8f2e-6d9047aae1aa.png)

**Comment by SheetJSDev** [comment]
The original function was designed to handle multiple worksheets.  Instead of looping across the worksheets, just use the first one:

```js
var roa = X.utils.sheet_to_json(workbook.Sheets[workbook.SheetNames[0]], ...)
return JSON.stringify(result, 2, 2)
```

**Comment by skorlepara** [comment]
I just want to get it as single JSON so that can produce a result
