### ISSUE TITLE
fix usage of global object in browser environment / Angular no longer supporting it

### ISSUE THREAD

**Issue by cristhiank** [SheetJS/js-xlsx#1088]
Browser code should not rely on things that are not available in browser environments. Otherwise it throws error global is undefined.

see [angular-cli issue](https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814)

**Comment by SheetJSDev** [comment]
This hasn't been an issue in angular 2/4/5.  Can you share a sample project using a beta version of angular 6?

**Comment by cristhiank** [comment]
Sure, you can check in [this link](https://github.com/cristhiank/xlsx-issue)
Just clone and run ng serve and you will see the following error in the console:
![image](https://user-images.githubusercontent.com/1218220/39555597-ff568ca0-4e3f-11e8-883b-e3bb28ffaab6.png)

**Comment by SheetJSDev** [comment]
We're going to cut a new release today.  Based on some tests against your sample project, it should be sufficient to add a global typeof guard:

```diff
 if(typeof module !== "undefined" && typeof require !== 'undefined') {
-       if(typeof cptable === 'undefined') global.cptable = require('./dist/cpexcel.js');
+       if(typeof cptable === 'undefined') {
+               if(typeof global !== 'undefined') global.cptable = require('./dist/cpexcel.js');
+               else if(typeof window !== 'undefined') window.cptable = require('./dist/cpexcel.js');
+       }
 }

```

**Comment by cristhiank** [comment]
Yes, that will work! Thanks for the quick reply.
