### ISSUE TITLE
js-xlsx upload to Java - Save to database - MySQL

### ISSUE THREAD

**Issue by carvalho149** [SheetJS/js-xlsx#1091]
Is there a solution for saving xlsx file data to a database (MySQL)?

I'm using Java. I was able to upload xlsx to my browser, which displays in the console a list like this:

{SheetNames: Array (1), sheets: {...}}
SheetNames: ["Sheet1"]
Sheets:
Sheet1:
! ref: "A1: Y49"
A1: {t: "s", v: "drive: 00100"}
A2: {t: "s", v: "Date: between 04/20/2018 (12013) and 04/20/2018 (12013)"}
A3: {t: "s", v: ""}
A6: {t: "s", v: "Operator"}

**Comment by SheetJSDev** [comment]
We have a [database demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/database) which gives a strategy for generating SQL queries from worksheets.  Check the [`sheet_to_sql`](https://github.com/SheetJS/js-xlsx/blob/master/demos/database/SheetJSSQL.js) function.  The MySQL demo runs in nodejs and uses the [`mysql2`](https://www.npmjs.com/package/mysql2) interface.

At a high level the workflow is

1. parse file
2. generate queries
3. execute

So there are a few ways to split up the load:

A) If you are in a trusted environment and you insist on using Java as a backend, you run the first two steps in the browser itself (the `sheet_to_sql` function returns an array of string queries), send the raw queries to the server, and execute in a transaction using your Java app.

B) If you can use nodejs on the backend, you can run the first step in the browser and send the JS object to the backend (and the backend can generate queries and execute)

C) You can always just upload the file to the server-side and perform the entire workflow in nodejs.
