### ISSUE TITLE
Use minified version on Angular 5?

### ISSUE THREAD

**Issue by rscherer** [SheetJS/js-xlsx#1100]
Is there a correct way to use minified XLSX on an Angular 5 project?

Currently I'm using it as:
`import * as XLSX from 'xlsx';`

Using this import like:
`const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
`
And
`const workbook: XLSX.WorkBook = XLSX.utils.book_new();`

It works just fine, but produces a very large bundle object inside my build:
![image](https://user-images.githubusercontent.com/30807941/39827994-e914faee-538f-11e8-96a9-a8b83b241c91.png)

I want to know if it's possible to use the .min files, to help reduce the bundle size. And if so, how to import and use it properly?

**Comment by SheetJSDev** [comment]
[The minified version itself is about that size.](https://unpkg.com/xlsx@0.12.13/dist/)  There is a smaller `xlsx.core.min.js` file ~460KB (~145KB gzipped) that omits the cpexcel blob.

To omit the cpexcel blob in the build without having to reference the separate file, you can [suppress `cpexcel.js` in the webpack config, as shown in the webpack demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/webpack#omitting-optional-dependencies).  If you are using the angular cli, you may need to eject.

**Comment by sareeshv** [comment]
Hi,
How can we configure this for angular cli build?

**Comment by negberts** [comment]
@sareeshv try this: https://dev.to/meltedspark/customizing-angular-cli-6-buildan-alternative-to-ng-eject-1oc4

**Comment by 904492381** [comment]
How can we configure this for react?
