### ISSUE TITLE
Feature request: ignore hidden cells in table_to_sheet/book

### ISSUE THREAD

**Issue by Finesse** [SheetJS/js-xlsx#1115]
It would be great if SheetJS ignores hidden rows and cells when parsing a DOM table using the `table_to_sheet` and `table_to_book` functions.

For example, the following table:

```html
<table>
  <tr>
    <td>One</td>
    <td style="display: none;">Two</td>
    <td>Three</td>
  </tr>
  <tr>
    <td>1</td>
    <td class="hidden">2</td>
    <td>3</td>
  </tr>
  <tr style="display: none;">
    <td>Раз</td>
    <td>Два</td>
    <td>Три</td>
  </tr>
</table>

<style>
  .hidden {
    display: 'none';
  }
</style>
```

Would be parsed as:

| One | Three |
|-----|-----|
| 1 | 3 |

Detecting whether the cell is hidden can be done by detecting a `display: none` style:

```js
if (getComputedStyle(cell).getPropertyValue('display') === 'none') {
    continue;
}
```

Ignoring hidden cells and rows can be optional:

```js
XLSX.utils.table_to_sheet(table, {
    ignoreHiddenRows: true,
    ignoreHiddenCells: true
});
```

If you support this feature, I can make a pull request.

**Comment by Finesse** [comment]
@SheetJSDev I think that a user expects to see in a worksheet exactly what he/she sees in the browser, therefore SheetJS should behave the same as browsers (completely ignore hidden cells).

**Comment by SheetJSDev** [comment]
@Finesse It's probably best to follow Excel's example.  If you take the first example, save as an HTML file, and open in Excel, you will find that it hides the row but does not hide the column:

<img width="397" alt="" src="https://user-images.githubusercontent.com/6070939/40515562-4d89e808-5f7b-11e8-8b2f-d4c5235f3054.png">

So the specific approach that we'd be willing to accept is: if available, use `getComputedStyle` on the TR element to determine whether the TR is visible.  If it is not visible, mark the row as hidden.  [The feature is controlled in the worksheet `!row` array](https://docs.sheetjs.com/#row-properties)

**Comment by Finesse** [comment]
@SheetJSDev What about cells (`<td/>`s and `<th/>`s)? Must hidden cells be ignored? I insist to ignore them to conform the HTML behaviour.

Should the described behaviour be the default behaviour? Should there be a possibility to enable/disable it using the `ignoreHiddenRows` and `ignoreHiddenCells` parameters?

**Comment by SheetJSDev** [comment]
Excel treats the singleton `<td/>` and `<th/>` as if they were empty text (stub cells).  It probably makes sense to generate stub cells if `sheetStubs` is true (to be consistent with the other formats).

The original objection was based on how Excel handles the underlying HTML, but upon reflection your argument makes sense.  Let's try:

- The default behavior should include every cell and only hide rows if the TR element is hidden.

- Create a new `display` option (default false) that omits every hidden cell and every hidden row if true (as if the hidden cells were not included in the first place).

**Comment by Finesse** [comment]
@SheetJSDev Let's recap it.

There will be a new option called `display` in the `table_to_sheet` and `table_to_book` methods. The default value of this option is `false`.

If `display` value is `false`, the result table (created from the HTML from my first my) looks this way:

![image](https://user-images.githubusercontent.com/9006227/40529559-d20a2b48-6038-11e8-9179-70e3494b0913.png)

If `display` value is `true`, the result table looks this way:

![image](https://user-images.githubusercontent.com/9006227/40529590-f2b991c6-6038-11e8-8296-4a52f816bbd4.png)

Is it correct?

**Comment by SheetJSDev** [comment]
@Finesse correct.  That makes the most sense since the default behavior lines up with how Excel handles HTML tables while the new behavior lines up with what people would expect.

https://www.caniuse.com/#feat=getcomputedstyle suggests IE9+ support getComputedStyle, so it should not be assumed to exist (IE8 is still a target in the browser test matrix).  If getComputedStyle is not available, just proceed as if nothing was hidden.

**Comment by Finesse** [comment]
@SheetJSDev Ok! I will make a pull request in a few days.
