### ISSUE TITLE
Bools read as strings

### ISSUE THREAD

**Issue by Chriller855** [SheetJS/js-xlsx#1116]
I have an export of Json into EXCEL,

email | history | firstname | lastname | locale | companyUid | changePassword | enabled | loginAttempts | deleted | avatar | phone
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
zqtylv87@email.com | | zqtylv87 | zqtylv87 | en-gb | 0015fad3-1247-461a-b318-a57d602fffd8 | FALSE | TRUE | 0 | FALSE | 2 | zqtylv87
whxtpxt@cannot_be_trusted.dk | | Mads Mølgaard | Andersen | en-gb | 00fdd79f-f4d1-41bd-99d8-f25d432dc82a | FALSE | TRUE | 0 | FALSE | 2 | 123456768

and when i import it using.
 var workbook = XLSX.read(data, {type: 'binary'});
 var sheet = workbook.Sheets[workbook.SheetNames[0]];
 var sheetAsAOA = XLSX.utils.sheet_to_row_object_array(sheet);

then i get something like
{
avatar:"2",
changePassword:"FALSE",
companyUid:"0015fad3-1247-461a-b318-a57d602fffd8",
deleted:"FALSE",
email:"zqtylv87@email.com",
enabled:"TRUE",
firstname:"zqtylv87",
id:"extModel195-1",
lastname:"zqtylv87",
locale:"en-gb",
phone:"zqtylv87"
}

when i want,
{
avatar:"2",
changePassword:FALSE,
companyUid:"0015fad3-1247-461a-b318-a57d602fffd8",
deleted:FALSE,
email:"zqtylv87@email.com",
enabled:TRUE,
firstname:"zqtylv87",
id:"extModel195-1",
lastname:"zqtylv87",
locale:"en-gb",
phone:"zqtylv87"
}

**Comment by SheetJSDev** [comment]
The option is [`raw:true`](https://docs.sheetjs.com/#json).  Here's an example REPL session:

```js
> var ws = XLSX.read("a,b,c\n1,2,3\nTRUE,FALSE", {type:"binary"}).Sheets.Sheet1
> ws
{ A1: { t: 's', v: 'a' },
  B1: { t: 's', v: 'b' },
  C1: { t: 's', v: 'c' },
  A2: { t: 'n', w: '1', v: 1 }, // A2 is numeric
  B2: { t: 'n', w: '2', v: 2 }, // B2 is numeric
  C2: { t: 'n', w: '3', v: 3 }, // C2 is numeric
  A3: { t: 'b', v: true },      // A3 is boolean
  B3: { t: 'b', v: false },     // B3 is boolean
  '!ref': 'A1:C3' }
> XLSX.utils.sheet_to_json(ws)             // the formatted text values are returned
[ { a: '1', b: '2', c: '3' }, { a: 'TRUE', b: 'FALSE' } ]
> XLSX.utils.sheet_to_json(ws, {raw:true}) // the raw values are returned
[ { a: 1, b: 2, c: 3 }, { a: true, b: false } ]
```
