### ISSUE TITLE
Is there any another way Instead of replace xlsx-style/dist/cpexcel.js with xlsx/dist/cpexcel.js in node_moduls directory?

### ISSUE THREAD

**Issue by jeevanreddyneerudu02** [SheetJS/js-xlsx#1117]
Currently am working with the grid data to export excel and download excel using xlsx and xlsx-styles.
But the functionality is working when replace xlsx-style/dist/cpexcel.js with xlsx/dist/cpexcel.js in node_moduls directory.
I have seen that there is a bug in node modules.
Is there any another way to avoid this manual copy process?

**Comment by SheetJSDev** [comment]
we don't control the `xlsx-style` node module
