### ISSUE TITLE
Exporting comma separated number doesn't work properly

### ISSUE THREAD

**Issue by sancit** [SheetJS/js-xlsx#1120]
When i construct a CellObject as follows

cellObject = {
                           v: '43,323,123',
                            t: 'n',
                     };

It is not exported as a number type in excel.. (this is actually supported as number in excel when you input directly)

At the same time following CellObjects are properly exported

cellObject = {
                            v: '32323',
                            t: 'n',
                     };

cellObject = {
                            v: '1.3232',
                            t: 'n',
                     };

Any thoughts on why this isn't supported?

**Comment by SheetJSDev** [comment]
For numeric cells (type `n`), the value `v` is expected to be an actual number.  The specific format is controlled by the `z` field of the cell, which is expected to be an excel number format string or one of the built-in indices as shown in the [format table](https://github.com/SheetJS/js-xlsx/blob/master/bits/10_ssf.js#L43).

https://jsfiddle.net/sheetjs/3ag0g0rn/ is an example.  You should be writing:

```js
cellObject = {
    v: 43323123,
    t: 'n',
    z: '#,##0' // at least one digit, thousands-grouping 
};
```

**Comment by DavideArgellati** [comment]
Hi regarding this, what about when we have a list of numbers? currently list is only strings ?
  /** Array of strings for a fixed dropdown List (List only) */
  l?: string[];

**Comment by SheetJSDev** [comment]
@DavideArgellati if this relates to the Pro software, please send an email to pro@sheetjs.com
