### ISSUE TITLE
How to upload a dynamically created workbook to S3 without storing it to a file?

### ISSUE THREAD

**Issue by mandeepm91** [SheetJS/js-xlsx#1127]
I am creating a workbook in a Node.js program. Here is an example:

```
const XLSX = require('xlsx');
const wb = XLSX.utils.book_new();
const new_ws_name = "SheetJS";
const ws_data = [
  [ "S", "h", "e", "e", "t", "J", "S" ],
  [  1 ,  2 ,  3 ,  4 ,  5 ]
];
const ws = XLSX.utils.aoa_to_sheet(ws_data);
XLSX.utils.book_append_sheet(wb, ws, new_ws_name);

```

Now I want to upload this file as an `xlsx` file to an S3 bucket on AWS. One way would be that I create a temporary local file using:

```
XLSX.writeFile(wb, 'out.xlsx');
```

And then upload this `out.xlsx` file to S3 by creating a readStream from it. Isn't there any direct method where I can create a read stream from my workbook and directly upload it to S3?

**Comment by SheetJSDev** [comment]
`XLSX.write(wb, {type:'buffer', bookType:'xlsx'})` generates a Buffer of the export in the XLSX format, which you can directly upload to s3 using the `putObject` function [as shown in the `aws-sdk` example](https://github.com/aws/aws-sdk-js/blob/master/ts/s3.ts#L120).

**Comment by morganzysman** [comment]
Hi, I'm stuck with the same issue. 
The code uploads the file to the s3 server. But I always get a corrupted file when downloading it.

`   getPreSignedUrl() {
      aws.config.update({
        accessKeyId: "xxx",
        secretAccessKey: "xxx"
      });

      const s3 = new aws.S3();
      const params = {
        Bucket: "xxx",
        Expires: 600,
        Key: "dataSample.xlsx",
        ContentType: "application/octet-stream",
        ACL: "public-read"
      };
      var _self = this;
      s3.getSignedUrl("putObject", params, function(err, url) {
        console.log("signedurl", url);
        _self.uploadFile(url);
      });
    },
    uploadFile(signedUrl) {
      const workbook = XLSX.utils.book_new();
      const worksheet = XLSX.utils.json_to_sheet(this.data, {
        header: ["lastName", "firstName"]
      });
      XLSX.utils.book_append_sheet(workbook, worksheet, "sheet1");

      const file = XLSX.write(workbook, {
        type: "buffer",
        bookType: "xlsx",
        bookSST: false
      });

      const options = {
        headers: {
          "Content-Type": "application/octet-stream"
        }
      };

      this.axios
        .put(signedUrl, file, options)
        .then(result => {
          alert("Sucess " + JSON.stringify(result));
        })
        .catch(error => {
          alert("Error " + JSON.stringify(error));
        });
    }
  }`

Do you know what I am missing, I have tried buffer base64, and many other ways.

**Comment by aislanmaia** [comment]
@morganzysman have you accomplished to upload an valid file ?

**Comment by heaxo** [comment]
@SheetJSDev Why did I not respond, return results, or report any errors when using XLSX. write (wb, {type:'buffer ', bookType:'xlsx'})
