### ISSUE TITLE
Modify example does not export if file is uploaded

### ISSUE THREAD

**Issue by amitm02** [SheetJS/js-xlsx#1130]
The modify example [link](http://sheetjs.com/demos/modify.html) does not export back an uploaded excel file.
showing:
```
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at xv (xlsx.full.min.js:21)
    at Object.yv [as table_to_book] (xlsx.full.min.js:21)
    at doit (modify.html:48)
    at HTMLInputElement.onclick (modify.html:84)
```

attached a simple excel that failed to be exported back.
[Book1.xlsx](https://github.com/SheetJS/js-xlsx/files/2068909/Book1.xlsx)

**Comment by SheetJSDev** [comment]
The id of the element was changed but the new table generation was using the old id.  It should be fixed now.
