### ISSUE TITLE
ReactJS Tutorial for js-xlsx

### ISSUE THREAD

**Issue by ajiejot** [SheetJS/js-xlsx#1131]
Is there any tutorial for ReactJS? Like how import/export excel file works in ReactJS components?

**Comment by SheetJSDev** [comment]
We have a demo at https://github.com/SheetJS/js-xlsx/tree/master/demos/react which shows a very simple state structure using an array of arrays.  It shows import and export in the standard browser deployment, react-native, next.js, and even using Preact!

**Comment by ajiejot** [comment]
I tried it but I am getting no valid entry for _cols_ state when importing it and displaying to the render. I want to ask what is the correct format in excel to be able the array of column objects displayed properly in the table in render() ?

**Comment by ajiejot** [comment]
This is my example data of array of objects:

![image](https://user-images.githubusercontent.com/36364052/41010036-adcba9ea-6967-11e8-98fb-5354f65af337.png)

**Comment by thuckate96** [comment]
**kio** tryrty ###  
### fghfgh 
_gfhgfh_

**Comment by locnt1501** [comment]
Have you fixed this?
