### ISSUE TITLE
international limits on community version vs pro version

### ISSUE THREAD

**Issue by greggman** [SheetJS/js-xlsx#1133]
On [the page with info about the "Pro" version](http://sheetjs.com/pro) it says

> Support for international data

Is there somewhere that clarifies what the differences are in the community edition vs the pro edition with regards to international data?

**Comment by SheetJSDev** [comment]
Excel has no concept of universal time -- all datetime values are based on an epoch which is different for each time zone.  The value 12345 corresponds to different UTC times if the file was saved in New York or Paris or Moscow or Delhi or Shanghai, and the values are displayed differently if the file is opened in different locations.  https://github.com/SheetJS/js-xlsx/issues/560#issuecomment-280403917 includes some screenshots of the same file opened when the computer settings were changed.

Unfortunately none of the Excel formats store metadata necessary to determine either the locale or the time zone on save.  This is arguably *a defect in Excel*.  There are quite a few places in the code where the `en_US` locale and eastern time zone are assumed.  To mitigate the problem we've added a few knobs like the `dateNF` option to control output.

The pro version international support overhauls the formatter to support session-wide locales and localized features, including the [language-specific phrases like property names](https://github.com/SheetJS/js-xlsx/blob/master/bits/34_extprops.js#L34), locale-specific formats like the venerable date code 14, workarounds for inconsistent and undocumented Excel quirks like their handling of the Indian numbering system (1e10 is 10,00,00,00,000), and a fun little optional VBA-powered workaround to normalize date codes when exporting files.

P.S.: feel free to send an email.  I promise, we don't bite!
