### ISSUE TITLE
Truncate Excel on writeFile

### ISSUE THREAD

**Issue by alfredosalzillo** [SheetJS/js-xlsx#1137]
Hi,

i try reading this file 
[PivotGrid (23).xlsx](https://github.com/SheetJS/js-xlsx/files/2104200/PivotGrid.23.xlsx)

and writing him back, and i get this one, he only print 2 columns
[export (13).xlsx](https://github.com/SheetJS/js-xlsx/files/2104202/export.13.xlsx)

there is a part of my code:

        const workbook = XLSX.read(
          report.data, {
            type: 'binary',
          });
        console.log(workbook);
        await new Promise((resolve => setTimeout(resolve, 3000)));
        const file = XLSX.writeFile(workbook, 'export.xlsx', {
          type: 'base64',
          bookType: 'xlsx',
        });

if i inspect the first console.log i see that all the columns and row are in the workbook.

**Comment by SheetJSDev** [comment]
The file reports a range of `A1:C1`:

![](https://user-images.githubusercontent.com/6070939/41441464-aae1efb0-7000-11e8-9448-3576d738501b.png)

The [`update_sheet_range` helper function in the wiki](https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions) will recalculate the range. Call it after reading the file and before writing.
