### ISSUE TITLE
Output file is 10x bigger than the original

### ISSUE THREAD

**Issue by diegovdc** [SheetJS/js-xlsx#1138]
Hello, I am testing this module for project in which I need to input an xlsxl file process it and output the modified version.

My first trail was just reading and writing the same file, using some code I found on the docs.  My input file is around 30mb, and the output is 300mb.  Once I open it on Excel and save it, the file size is reduced to 30mb.

```js
var fs = require('fs');
var XLSX = require('xlsx');
function process_RS(stream/*:ReadStream*/, cb/*:(wb:Workbook)=>void*/)/*:void*/{
  var buffers = [];
  stream.on('data', function(data) { buffers.push(data); });
  stream.on('end', function() {
    var buffer = Buffer.concat(buffers);
    var workbook = XLSX.read(buffer, {type:"buffer"});
    cb(workbook);
  });
}

process_RS(
  fs.createReadStream('../test-files/myfile.xlsx'),
  wb => { XLSX.writeFile( wb, './rewritten.xlsx')}
);
```

Is there anything I might be missing?

**Comment by SheetJSDev** [comment]
Set the option `compression:true` -- this enables ZIP compression (using DEFLATE rather than raw storage):

```js
  wb => { XLSX.writeFile( wb, './rewritten.xlsx', compression:true); }
```

If the worksheet has many string values that are repeated, set the option `bookSST:true` (this turns on Excel string dedupe):

```js
  wb => { XLSX.writeFile( wb, './rewritten.xlsx', compression:true, bookSST:true); }
```
