### ISSUE TITLE
Unable to use sheet_to_txt 

### ISSUE THREAD

**Issue by raghavchawla7** [SheetJS/js-xlsx#1139]
Hi SheetJsDev and developer community,I want to use sheet_to_txt function but every time I call this method there is an error Uncaught TypeError: XLXS.utils.sheet_to_txt is not a function .I am using xlxs.js shim.js jszip.js for using this.It would be very helpful if I got to know if there is any way of using sheet_to_txt function.I want the text to be in Unicode format. SheetJSDev it's urgent.kindly help asap.Thanks in advance

**Comment by raghavchawla7** [comment]
SheetJSDev please reply asap.And Thanks for this great library

**Comment by raghavchawla7** [comment]
@SheetJSDev kindly help

**Comment by SheetJSDev** [comment]
What version are you using?  you can check with `console.log(XLSX.version)`.

Can you also check what utils are available?  `console.log(Object.keys(XLSX.utils))`

**Comment by raghavchawla7** [comment]
@SheetJSDev I am using 0.11.3 version and it has 31 utils in which sheet_to_txt is not present.Kindly tell what should I do.Thanks for your quick response and I hope I will get that now also.

**Comment by raghavchawla7** [comment]
I am using 0.11.3 version and it has 31 utils in which sheet_to_txt is not
present.Kindly tell what should I do.Thanks for your quick response and I
hope I will get that now also.

**Comment by SheetJSDev** [comment]
It was added in `0.11.11`.  If you need to use it in `0.11.3`, you can get the same effect by calling `write` with `bookType:"txt"` setting `sheet` to the desired sheet, but it is easier to just upgrade.  See https://github.com/SheetJS/js-xlsx/issues/905#issuecomment-347039780

**Comment by raghavchawla7** [comment]
Thanks a lot for that.Could you please help me with one more issue.I am
getting my Excel file by downloading it from the server.Now when I parse it
using sheet_to_* it parses only the first three rows.But when I open that
downloaded file in Ms Excel and save it without doing anything else and
then I again parse it ,it parses all the rows perfectly.If you can tell me
what I need to do so that it get parsed completely without saving the file
in Excel it would be very helpful.Thanks a lot again.I want this to get
resolved asap
