### ISSUE TITLE
xlsb errors

### ISSUE THREAD

**Issue by WorkMAE** [SheetJS/js-xlsx#1140]
I cannot get this to work with an XLSB file.

Since fileRead won't work to pull the file off the server, I use a $.get(serverFile) to load the data, but then when I try and use XLSX.read(data) it throws an error no matter what I put in there for type:
if I use binary: I get "undefind TypeError: Cannot read property '0' of undefined"

if I use buffer I get "Unrecongnized type [object Object]"

I simply want to grab the file data and parse it into JSON.  How can I do this with an XLSB file?

**Comment by SheetJSDev** [comment]
You need to use an XMLHttpRequest to get data from the server.  See [the `xhr` demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/xhr) for more information
