### ISSUE TITLE
csv to excel 

### ISSUE THREAD

**Issue by mohamed-hendawy** [SheetJS/js-xlsx#1144]
i want to read csv file and export as excel file but the delimiter is  | and i do not have option to open csv file to add sep=| at the first of file any solution ?

**Comment by SheetJSDev** [comment]
No version of Excel will honor the pipe delimiter without a hint.

You can prepend the header to the file in memory.  For example, in nodejs:

```js
var buf = fs.readFileSync("file.psv");
var data = Buffer.concat([new Buffer("sep=|\n"), buf]);
var wb = XLSX.read(data);
```

In the browser, you can prepend the header to the binary string or create a new Uint8Array.
