### ISSUE TITLE
Add a jason data to an existing sheet.

### ISSUE THREAD

**Issue by ahgan84** [SheetJS/js-xlsx#1147]
Hi guys,
From previous example, we know that after reading a file, we can add new data into that particular sheet:

```
var XLSX = require('xlsx');
var wb = XLSX.readFile('sheetjs.xlsx');
add_cell_to_sheet(wb.Sheets.SheetJS, "F6", 12345);
XLSX.writeFile('sheetjs-new.xlsx', wb);
```
But how to do if my data is not just a single cell? I have a json data that I would like to add into the file that I read. How to add the json data?

**Comment by SheetJSDev** [comment]
[`XLSX.utils.sheet_add_aoa`](https://docs.sheetjs.com/#array-of-arrays-input) takes an array of array and [`XLSX.utils.sheet_add_json`](https://docs.sheetjs.com/#array-of-objects-input) takes an array of objects.

**Comment by ahgan84** [comment]
After we read a file, it is under a workbook right?
But the sheet_add_json doesn't specify the workbook name:
`sheet_add_json(ws: WorkSheet, data: any[], opts?: SheetJSONOpts): WorkSheet;`
It only specify the worksheet name.

**Comment by SheetJSDev** [comment]
A literal conversion of the first example would be:

```js
var XLSX = require('xlsx');
var wb = XLSX.readFile('sheetjs.xlsx');
XLSX.utils.sheet_add_json(
  wb.Sheets.SheetJS, // worksheet
  [{number: 12345}], // data
  { // options
    header: ["number"], // properties to read from each object
    skipHeader:true, // do not include header row
    origin: "F6" // start from cell F6
  }
);
XLSX.writeFile('sheetjs-new.xlsx', wb);
```

This example writes F6="a", F7="b", G6=1, G7=2:

```js
XLSX.utils.sheet_add_json(
  wb.Sheets.SheetJS,
  [
    {text: "a", number: 1},
    {number:2, text: "b"}
  ],
  {
    header: ["text", "number"],
    skipHeader:true,
    origin: "F6"
  }
);
```

**Comment by ahgan84** [comment]
Can explain "wb.Sheets.SheetJS"?
wb=workbook that we read
How bout Sheets.SheetJs? Is it the sheet name?

**Comment by ahgan84** [comment]
Ok. I can add a json file into my read workbook already.
But the workbook that I read did not preserved the styles like bold word or underline. How to preserved the styles?

**Comment by harbhub** [comment]
You would need the SheetJS Pro version in order to access the styles.
https://sheetjs.com/pro

**Comment by NikicaCh** [comment]
@harbhub  and what is the price of the pro version ?

**Comment by harbhub** [comment]
It varies based on the use case.  You'd have to email their support team at pro@sheetjs.com to find out.

**Comment by harbhub** [comment]
@NikicaCh ^

**Comment by NikicaCh** [comment]
@harbhub, I emailed them this morning, but still waiting for the reply, and was wondering if it is to expensive.I don't need it for something big, just for populating some daily report templates and maybe invoices and nothing more.

**Comment by harbhub** [comment]
@NikicaCh unfortunately I don't know how quickly you can expect a response, but you can try to expedite the process by joining the IRC webchat.  Sometimes a representative is present there, in which case you can ask about your email and have it attended to more quickly.  The official channel is #SheetJS

**Comment by NikicaCh** [comment]
@harbhub thanks for the reply again.They responded later that day, but I am not ready to pay the sum they ask since it is a simple project I build for myself and not a client.
Do you know a alternative to this package, something that will do the job for me ?

**Comment by harbhub** [comment]
@NikicaCh I'm sorry to hear that.  Unfortunately, I do not know of any comparable library for handling spreadsheets in JavaScript.  SheetJS is the most robust solution to my knowledge.

Did you specify that this was for personal use in your email to their support team?

**Comment by Madmals** [comment]
this is what working with me..after getting error
`var ext = o.file.slice(o.file.lastIndexOf(".")).toLowerCase();
                                      ^
TypeError: o.file.lastIndexOf is not a function`


`
	var wb = XLSX.readFile('./data.xlsx');
	const ws = XLSX.utils.sheet_add_json(
		wb.Sheets.Sheet1, // worksheet
		[{ number: 12345 }], // data
		{ // options
			header: ["number"], // properties to read from each object
			skipHeader: true, // do not include header row
			origin: "A3" // start from cell F6
		}
	);

	XLSX.utils.book_append_sheet(wb, ws)
	XLSX.writeFile(wb, 'data.xlsx');

`
