### ISSUE TITLE
how to download file?

### ISSUE THREAD

**Issue by wvicioso** [SheetJS/js-xlsx#1149]
The docs are pretty messy. All I want to do is generate an xlsx file and then give the user the option to download the new file to their computer.

I am using angular. I already can generate the file. I need help with the downloading part.

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/#writing-functions

> `XLSX.writeFile(wb, filename, write_opts)` attempts to write `wb` to `filename`. In browser-based environments, it will attempt to force a client-side download.

The angular demo has an example of generating a file and triggering a download: https://github.com/SheetJS/js-xlsx/blob/master/demos/angular/SheetJS-angular.js#L18

**Comment by wvicioso** [comment]
Is there an example with angular 2+? @SheetJSDev

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2 includes examples of a plain angular 2+ app as well as ionic and nativescript targets
