### ISSUE TITLE
This code works in FF & Edge but not Chrome

### ISSUE THREAD

**Issue by Ban5hee** [SheetJS/js-xlsx#1153]
Hi there,

I'm not a bug hunter so not sure if this is a bug or not.
I posted a question on SO 2 days ago and have had 2 replies but neither are particularly useful.
This is the SO question;

https://stackoverflow.com/questions/50931271/filesaver-js-chrome-issue-multiple-documents

But for completeness I'll include the content here;

SO QUESTION START::
------------------------
I'm using Chrome v67 and FileSaver.js.

This code works in FF & Edge but not in Chrome.

var ajaxSettings = {
    url: "my/api/method",
    data: JSON.stringify(myItems),
    success: function (data) {
        if (data) {
            var dateToAppend = moment().format("YYYYMMDD-HHmmss");
            createPdf("pdfDoc_" + dateToAppend + ".pdf", data[0]);
            saveFile("txtDoc_" + dateToAppend + ".txt", data[1]);

            //sleep(2000).then(() => {
            //    saveFile("txtDoc_" + dateToAppend + ".txt", data[1]);
            //});
        }
    }
}

//function sleep(time) {
    //return new Promise((resolve) => setTimeout(resolve, time));
//}

function createPdf(filename, pdfBytes) {
    if (navigator.appVersion.indexOf("MSIE 9") > -1) {
        window.open("data:application/pdf;base64," + encodeURIComponent(pdfBytes));
    }
    else {
        saveFile(fileName, data);
    }
}

function saveFile(fileName, data) {
    var decodedByte64 = atob(data);
    var byteVals = new Array(decodedByte64.length);
    for (var i = 0; i < decodedByte64.length; i++) {
        byteVals[i] = decodedByte64.charCodeAt(i);
    }
    var byte8bitArray = new Uint8Array(byteVals);

    var blob = new Blob([byte8bitArray]);
    saveAs(blob, fileName); //FileSaver.js
}`

The result of calling the API is an array with 2 byte arrays in it. The byte arrays are the documents.

If I run this code, as a user would, then what happens is that the first document gets "downloaded" but the second does not. Attempting to do this a second time without refreshing the page results in no documents being "downloaded". The "download" word is in quotes because it already has been downloaded, what I'm really trying to do is generate the documents from the byte arrays.

This is the strange bit ... if I open the console and place a breakpoint on the "saveFile" call and immediately hit continue when the debugger lands on the breakpoint then all is well with the world and the 2 documents get downloaded/generated (sic).

I initially thought it was a timing issue so I put a 2 second delay on this to see if that was it, but it wasn't. The only thing I've managed to get working is the breakpoint which I'm obviously not going to be able to convince the users to start doing no matter how much I want them to.

Any help or pointers are much appreciated
SO QUESTION END::
------------------------

Is this a bug or am I being a muppet?

Cheers
(apologise for the formatting in this post)

**Comment by SheetJSDev** [comment]
This issue is unrelated.  You probably meant to raise an issue with the FileSaver repo https://github.com/eligrey/FileSaver.js
