### ISSUE TITLE
Problem installing the package

### ISSUE THREAD

**Issue by saideep** [SheetJS/js-xlsx#1155]
Problem: While trying to install the package, I am getting the below token error.

npm ERR! Unexpected token } in JSON at position 8263 while parsing near '...gBcVa+g=="
npm ERR!     },
npm ERR!   }
npm ERR! }
npm ERR! '

npm ERR! A complete log of this run can be found in:
=======

I tried clearing the cache but of No help.

[2018-06-22T21_14_33_237Z-debug.log](https://github.com/SheetJS/js-xlsx/files/2129184/2018-06-22T21_14_33_237Z-debug.log)

**Comment by SheetJSDev** [comment]
This is almost certainly a local or npm issue, completely outside of our control.  Try the following:

- remove package-lock.json and install again (based on comments from https://github.com/npm/npm/issues/17340 )

- temporarily move your package.json, install, then restore it

- roll back to an older version of npm (like 4.3.0) and try installing

and if none of those work, raise an issue with npm: https://github.com/npm/npm/issues/

**Comment by saideep** [comment]
Yes. Creating a new node package worked. Thank you.
