### ISSUE TITLE
How to iterate over nested objects

### ISSUE THREAD

**Issue by kpvf** [SheetJS/js-xlsx#1157]
Hi is there a way to iterate over nested objects for example i have a object

`[{ id: 3,
  driver_id: null,
  first_name: 'test',
  last_name: 'test',
  date_booking: '2018-05-27T20:21:00',
  delivered: [ { id: 3, akes: 0, pmcs: 0, pallets: 2, parcels: 4 } ],
  parcels:
   [ { id: 1,
       quantity: 2,
       customer_id: 1,
       weight: 1,
       cargo_id: 3,
       customer: '3D Total' },
     { id: 2,
       quantity: 1,
       customer_id: 2,
       weight: 2,
       cargo_id: 3,
       customer: '3T Express' } ],
  pallets: null }]`

what i would like to do is to display data in the rows and nested one in the columns from top to the bottom and process to the another one

Thanks for the help

**Comment by SheetJSDev** [comment]
The utility functions don't handle nested objects (as you can see, there's no general approach that works for all nested datasets), but you can always linearize manually and generate an array of arrays.

For example, supposing there were a maximum of 3 delivered items and 5 parcels, the array for the row would be:

```js
var r = data[0];
var row = [r.id, r.driver_id, r.first_name, r.name, r.date_booking];
/* delivered */
for(var i = 0; i < 3; ++i) {
  var del = r.delivered[i];
  if(del) row.push(del.id, del.akes, del.pmcs, del.pallets, del.parcels)
  else row.push.call(row, null, null, null, null, null)
}
/* parcels */
for(i = 0; i < 5; ++i) {
  var par = r.parcels[i];
  if(par) row.push(par.id, par.quantity, par.customer_id, par.weight, par.cargo_id, par.customer)
  else row.push.call(row, null, null, null, null, null, null)
}
row.push(r.pallets)
```

It's pretty straightforward to calculate the maxima instead of hardcoding:

```js
var max_del = data.reduce((acc, r) => Math.max(acc, (r.delivered ||[]).length), 0)
var max_par = data.reduce((acc, r) => Math.max(acc, (r.parcels ||[]).length), 0)
```

And the actual titles are similarly straightforward:

```js
var title1 = ["", "", "", "", ""], title2 = ["id", "driver_id", "first_name", "last_name", "date_booking"];
var merges = [];
for(var i = 0; i < max_del; ++i) {
  merges.push({s: {r:0, c:title1.length}, e: {r:0, c:title1.length + 4}});
  title1.push.call(title1, "delivered[" + i + "]", null, null, null, null);
  title2.push.call(title2, "id", "akes", "pmcs", "pallets", "parcels");
}
for(var i = 0; i < max_par; ++i) {
  merges.push({s: {r:0, c:title1.length}, e: {r:0, c:title1.length + 5}});
  title1.push.call(title1, "parcels[" + i + "]", null, null, null, null, null);
  title2.push.call(title2, "id", "quantity", "customer_id", "weight", "cargo_id", "customer");
}
title2.push("pallets");
```

A complete fiddle: https://jsfiddle.net/sheetjs/qoLf750v/

**Comment by pawanvivekananda** [comment]
Hi i am trying to formate the in similar format.
Is it possible to created Sheet in the below format.
  
[out_formated.xlsx](https://github.com/SheetJS/js-xlsx/files/2639989/out_formated.xlsx)
