### ISSUE TITLE
Strange cast to date from string  "Nymex - Crude Oil. Light Sweet. Sep 2008" to 1.9.2008 in xlsx

### ISSUE THREAD

**Issue by vbnr** [SheetJS/js-xlsx#1160]
When some column have for example that value "Nymex - Crude Oil. Light Sweet. Sep 2008" when  export table i get this value in that cell 1.9.2008
Thank you!

**Comment by SheetJSDev** [comment]
Chrome's date parsing is extremely aggressive, as you can test in your browser console:

```js
> new Date("Nymex - Crude Oil. Light Sweet. Sep 2008");
Mon Sep 01 2008 00:00:00 GMT-0400 (Eastern Daylight Time)
```

The `raw:true` option suppresses value interpretation.
