### ISSUE TITLE
Always the same Output while using XLSX.read

### ISSUE THREAD

**Issue by bab00n87** [SheetJS/js-xlsx#1162]
Hey guys I have an issue. Every time I try to read in a .xlsx I am getting the same console log.

![bildschirmfoto 2018-06-28 um 14 59 10](https://user-images.githubusercontent.com/11557024/42035734-f29d19fe-7ae3-11e8-921c-e3961677dd8f.png)

I import the file like this

import newXlsx from './assets/neu.xlsx';

const wb = XLSX.read(newXlsx,{type: 'binary' })
    console.log(wb)

It does not matter how many sheets I have or how they called. it is always the same result. 

"react": "^16.4.1",
"xlsx": "^0.13.1"

regards 

flo

**Comment by SheetJSDev** [comment]
The bundler is returning the URL rather than the file itself, so you're effectively parsing a file whose contents is "/static/media/neu.304ba648.xlsx" Configure your bundler to return the raw data.
