### ISSUE TITLE
The engine "node" is incompatible erorr during yarn install

### ISSUE THREAD

**Issue by fatihkurt** [SheetJS/js-xlsx#1164]
Installer throw error on version 0.13. Sure, i cannot switch to node 8 for now.

> error source-map@0.7.3: The engine "node" is incompatible with this module. Expected version ">= 8".

**Comment by fatihkurt** [comment]
Ops sorry, false flag. You can close issue.

**Comment by SheetJSDev** [comment]
The support surface area for this library is node 0.8+, not 8.0, as indicated in the engines field (yes, we know that 0.8 is very old, as is 0.10 and 0.12, but we'd prefer not to break backwards compatibility).

As that error message shows, the problem is with the `source-map` module
