### ISSUE TITLE
!autofilter noob

### ISSUE THREAD

**Issue by glococo** [SheetJS/js-xlsx#1165]
Autofilter feature is not working

```
const XLSX  = require('xlsx')
var wb = XLSX.utils.book_new() 
var ws = XLSX.utils.aoa_to_sheet([ ["Foo", "Bar", "Baz", "Qux"],  [1,2,3,4],  [2,3,4,5],  [3,4,5,6] ]) 
ws['!autofilter'] = { ref:"A1:D4" }
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");

XLSX.writeFile(wb, 'auto.ods')
XLSX.writeFile(wb, 'auto.xls')
XLSX.writeFile(wb, 'auto.xlsx')

**Comment by SheetJSDev** [comment]
Browser Fiddle: http://jsfiddle.net/sheetjs/8drvn0w3/

Generated File: [auto.xlsx](https://github.com/SheetJS/js-xlsx/files/2152990/auto.xlsx)

The table A1:D4 is marked as autofilter and the four columns have a dropdown that you can filter.

The same approach works in nodejs.

**Comment by glococo** [comment]
Hi sir,
I forgot to mention, not working in LIBREOFFICE 6+
Exporting in .xlsx, xls and ods. None of them works in LibreOFFICE.

**Comment by SheetJSDev** [comment]
According to the XLSX and XLSB specs, all that is necessary to indicate that AutoFilter applies to a table is a single record (xlsx uses `<autoFilter>`).  LibreOffice appears to expect more.

In testing with a sample file, LO generates a drawing (that corresponds to the 4 dropdown buttons) as well as the `_FilterDatabase` defined name.  Even though this is a bug in LibreOffice, we'll reopen and investigate further

**Comment by SheetJSDev** [comment]
Relevant LO issue: https://bugs.documentfoundation.org/show_bug.cgi?id=118592

**Comment by reviewher** [comment]
This seems to be a bug in LibreOffice, which we can't control :/
