### ISSUE TITLE
How to store value in number format while exporting json to  xlsx.

### ISSUE THREAD

**Issue by Mahendra789** [SheetJS/js-xlsx#1166]
First, I think your library is amazing. Thank you!

I am trying to write a file and include number formats. I have multiple columns with string and number format.
My problem is all number values are coming as string when i download the file. And i am not able to do calculation in my xlsx file.

Thanks again.

**Comment by SheetJSDev** [comment]
XLSX doesn't support CSV-style formatted string interpretation (so there's no way to put a text like "$1,234" in the XLSX file and have Excel interpret it).  The format stores IEEE754 numbers in the worksheet.  Style settings control the formatting applied to it.

You need to pass raw numbers into `json_to_sheet` then add back the number formats to the generated worksheet.  If you're passing text, then it will generate text objects.

To give an example:

```js
XLSX.utils.json_to_sheet([{a:1,b:"2"}], {header:["a","b"]})
// the call returns VVV
{
  A2: { t: 'n', v: 1 }, // number in, number out
  B2: { t: 's', v: '2' }, // text in, text out (even if it happens to represent a number)
  A1: { t: 's', v: 'a' },
  B1: { t: 's', v: 'b' },
  '!ref': 'A1:B2'
}
```

We will be adding a way to modify the formatting through the options, but in the meanwhile you can go back and manually add a specified format:

```js
/*
  ws: worksheet object
  C: 0-based index of the column you want to change, C = 1 means column "B"
  Z: number format string
*/
function sheet_set_column_format(ws, C, Z) {
  var range = XLSX.utils.decode_range(ws["!ref"]);
  /* this loop starts on the second row, as it assumes the first row is a header */
  for(var R = range.s.r + 1; R <= range.e.r; ++R) {
    var cell = ws[XLSX.utils.encode_cell({r:R,c:C})];
    if(!cell) continue;
    cell.z = Z;
  }
}
```
