### ISSUE TITLE
Modify !ref

### ISSUE THREAD

**Issue by mohamed-hendawy** [SheetJS/js-xlsx#1167]
any way to Modify !ref  because i want to remove the last row or remove any number of rows or columns  ?
ex if !ref=A1:K10  want to be !ref=A1:K9

**Comment by SheetJSDev** [comment]
Workbooks and worksheets are plain objects.  Just change the value!

For example, to remove the last row:

```js
var ws = wb.Sheets.Sheet1;

/* generate a range object */
var range = XLSX.utils.decode_range(ws["!ref"]);

/* remove the last row */
range.e.r--;

/* remove the last column */
range.e.c--;

/* reencode the range */
ws["!ref"] = XLSX.utils.encode_range(range);
```

This is discussed in more detail in the README at https://docs.sheetjs.com/#general-structures
