### ISSUE TITLE
Warning msg: 'This seems to be a pre-built javascript file'

### ISSUE THREAD

**Issue by ccamusso** [SheetJS/js-xlsx#1170]
Is possibile remove this warning on project startup?
```
Warning in ./~/xlsx/jszip.js
Critical dependencies:
25:159-166 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/xlsx/jszip.js 25:159-166
```
I using "xlsx": "^0.13.1"

**Comment by SheetJSDev** [comment]
What webpack version are you running?  The [webpack demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/webpack) does not show that message when running against 3.4.1 or 4.15.1. (clone the repo, `cd demos/webpack` and `make`)

Can you share a small demo project that triggers the error?

**Comment by ccamusso** [comment]
I'm very old webpack version: 1.14.0

**Comment by visualhu** [comment]
I have the same problem, I try ` externals: {'./jszip': 'jszip'}` to webpack config , but it remain.

**Comment by iHadDream** [comment]
I have the same problem

**Comment by iHadDream** [comment]
> I have the same problem

#565 can resolve this question

**Comment by dawangong** [comment]
me too, help ~  I try to use noParse in webpack config, but it don't work.  
—— webpack version: 1.12.14

**Comment by dawangong** [comment]
My final webpack config is:
**module: { noParse: [/jszip.js$/]}**
This configuration solves my problem.

**Comment by reviewher** [comment]
see https://github.com/SheetJS/js-xlsx/issues/285#issuecomment-240680073 (which is identical to the recommendation in this thread).
