### ISSUE TITLE
sheet_to_json

### ISSUE THREAD

**Issue by dobariyadhaval007** [SheetJS/js-xlsx#1171]
When i am use this function and convert it to json it will not create object key value pair for null value cell data it would be create problem in data parsing 

Part Value Type
1                Hardware
2       V1    Software

Output excepted:
 
{"Part":1,"Value":'',"Type":"Hardware}
{"Part":2,"Value":'V1',"Type":"Software}

Actual Output Comes":
{"Part":1,"Type":"Hardware}
{"Part":2,"Value":'V1',"Type":"Software}

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/#json the option is `defval`
