### ISSUE TITLE
How to insert a first row?

### ISSUE THREAD

**Issue by RonaldoLopes** [SheetJS/js-xlsx#1173]
Hello, I'm new to the tool and I'm having trouble inserting one before entering the data. I need to insert a header before the items.
I did the following:
`const wb = { 
        SheetNames: [], Sheets: {} 
    };

    wb.Props = {
        Title: "Outorga",
        Subject: "Dados de outorga",
        Author: "AAA",
        CreateDate: new Date()
    };

    let jsonText
    jsonText = JSON.stringify(getDados(data), "\t")//load data(getDados)
    jsonText = JSON.parse(jsonText)

    var wscols = [
        {wch:15},
        {wch:20},
        {wch:20},
        {wch:20},
        {wch:20},
        {wch:20},
        {wch:20},
        {wch:20},
        {wch:20}
    ]

    var ws = XLSX.utils.json_to_sheet(
        jsonText
    ) 
    var ws_name = "Outorga"
    XLSX.utils.book_append_sheet(wb, ws, ws_name)
    let wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'binary' })
    saveAs(new Blob([s2ab(wbout)], { type: "application/octet-stream" }), 'Outorga.xlsx');`

![cab](https://user-images.githubusercontent.com/6193224/42388156-03884db4-811b-11e8-85cd-7016c41bb5b2.png)

How to make this?
Sorry about my poor english...

**Comment by SheetJSDev** [comment]
Create a worksheet with that cell first:

```js
var ws = XLSX.utils.json_to_sheet([
  ["Cabe.."]
]);
```

Then add the data using [`sheet_add_json`](https://docs.sheetjs.com/#array-of-objects-input):

```js
XLSX.utils.sheet_add_json(ws, jsonText, {origin: "A2"}); 
```

There are other steps too, like merging the cell:

```js
if(!ws["!merges"]) ws["!merges"] = [];
ws["!merges"].push(XLSX.utils.decode_range("A1:H1")); // merge cells A1:H1
```

**Comment by RonaldoLopes** [comment]
Good morning and thank you for the reply. When I do the proposed, the header returns zero. I can not seem to get the text inside.
thankful

**Comment by jonnyshao** [comment]
@RonaldoLopes ,Hi, How do you resolved it?

**Comment by RonaldoLopes** [comment]
`if(!ws["!merges"]) ws["!merges"] = [];
    ws["!merges"].push(XLSX.utils.decode_range("A1:H1")); // merge cells A1:H1
    if(!ws["!merges"]) ws["!merges"] = [];
    ws["!merges"].push(XLSX.utils.decode_range("A2:H2")); // merge cells A1:H1

    XLSX.utils.sheet_add_json(ws, jsonText, {origin: "A3"});`

**Comment by RonaldoLopes** [comment]
@jonnyshao 
I used the merge function in the cells I wanted, for example:
`if(!ws["!merges"]) ws["!merges"] = [];
		ws["!merges"].push(XLSX.utils.decode_range("A1:H1")); // merge cells A1:H1
    if(!ws["!merges"]) ws["!merges"] = [];
		ws["!merges"].push(XLSX.utils.decode_range("A2:H2")); // merge cells A2:H2`
` XLSX.utils.sheet_add_json(ws, jsonText, {origin: "A3"});`

**Comment by RonaldoLopes** [comment]
@jonnyshao I did the following
`if(!ws["!merges"]) ws["!merges"] = [];`
// merge cells A1:H1
`ws["!merges"].push(XLSX.utils.decode_range("A1:H1"));`
`if(!ws["!merges"]) ws["!merges"] = [];`
// merge cells A2:H2
`ws["!merges"].push(XLSX.utils.decode_range("A2:H2"));`

Then I plotted the data
`XLSX.utils.sheet_add_json(ws, jsonText, {origin: "A3"}); `
