### ISSUE TITLE
Support for creating ListObjects?

### ISSUE THREAD

**Issue by filipjnc** [SheetJS/js-xlsx#1175]
I see no mention of ListObjects (aka Table created via CTRL+T in Excel) in SheetJS and any other Excel-related JavaScript library. Is it a general limitation of JavaScript?

**Comment by SheetJSDev** [comment]
"Format as Table", along with PivotTables and other styling features, is offered in the Pro compendium (our paid offering).  The Community version is primarily focused on data preservation.

https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021 is our general commentary.

**Comment by TarasTielkes** [comment]
Is is possible to _read_ `ListObject`s using the community version?
Specifically, to iterate the names of `ListObject`s on a given sheet.
