### ISSUE TITLE
Save a file after just reading changes it

### ISSUE THREAD

**Issue by kutlaykural** [SheetJS/js-xlsx#1179]
Hi all,
After reading and save new file not same as original file. Even it is very different. How can it be same as original. Maybe styles or codes or something else are ignored I think.

```js
var XLSX = require('xlsx/dist/xlsx.extendscript');

var inWorkbook = XLSX.readFile("input.xlsx"); 
var outWorkBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(outWorkBook, inWorkbook.Sheets["Sheet1"], "Sheet1");
XLSX.writeFile(outWorkBook, 'output.xlsx');
```
Thanks,

**Comment by SheetJSDev** [comment]
The Community version (this one) supports round-tripping data.  Pro builds support roundtripping styles and charts, among other features.
