### ISSUE TITLE
Question - WriteFile include Path

### ISSUE THREAD

**Issue by DFredrick78** [SheetJS/js-xlsx#1180]
Everything in my programmer mind is saying duh if this was allowed anyone could create simple malware/virus programs but I have to ask to make sure I have tried everything.

I basically have a local standalone browser application a co-worker is requesting.  In the end basically it needs to open an Excel file update some data and close it.  I have seen in other posts modification is not part of the Community side only read and write new.  I have three questions:

1. Is modification client side completely working in Pro version in that in a stand alone local (offline) environment the local javascript code would be able to open, modify and save changes to an excel file?

2. Is there away in the Community version when doing WriteFile to specificy a location to write?  I had thought of a possible work around but  when I do writefile it continues to create new files in download folder - I had hoped that I could use writefile and replace the existing file.

3. Does anyone have any other work around thoughts - I would think someone in the community has needed to do something similar to modifying data in a Excel vs creating a new file each time, and if a new file has to be created having a way to replace the old with the new.

Thanks
Debby

**Comment by SheetJSDev** [comment]
The fundamental problem is that the web Browser is sandboxed.   You can read files, modify and generate new files, but you can't edit files in place (that would violate the security sandbox).

For IE6-9 on Windows XP and Windows 7, there's a way to bypass the sandbox with a VBScript call to the `Scripting.FileSystemObject` control.  The internet explorer demo https://github.com/SheetJS/js-xlsx/tree/master/demos/oldie#activex-based-download discusses this further.  The shim inserts a [helper function](https://github.com/SheetJS/js-xlsx/blob/master/shim.js#L112):

```vbs
Function IE_SaveFile_Impl(FileName, payload)
  Dim data, plen, i, bit
  data = CStr(payload)
  plen = Len(data)
  Set fso = CreateObject("Scripting.FileSystemObject")
  fso.CreateTextFile FileName, True
  Set f = fso.GetFile(FileName)
  Set stream = f.OpenAsTextStream(2, 0)
  For i = 1 To plen Step 3
    bit = Mid(data, i, 2)
    stream.write Chr(CLng("&h" & bit))
  Next
  stream.Close
  IE_SaveFile_Impl = True
End Function
```

The shim also includes a similar method for reading from a file input: by attaching to the change event, you can get the filename and set up FSO to read bytes from that specified file name.
