### ISSUE TITLE
cellStyles: true

### ISSUE THREAD

**Issue by hartill** [SheetJS/js-xlsx#1183]
Hi, when reading an excel file with cellStyles: true, I am confused by the results and how I can use them. What I want to achieve is to read the color of the font on the incoming file so that I can distinguish between different types of color-coded data. When I can use cellStyles: true, it adds a 'styles' object to the data where there is an array holding all the fonts and colors from the imported data. However I cannot see how this color information can be mapped to cells... The cells themselves have a property 's'... and this has some style information like fgColor, but the font color I cannot find. Is there any documentation on this style information? Thanks

**Comment by Waseemrajashaik** [comment]
@hartill  Can you bold the header field  ?

**Comment by hartill** [comment]
@Waseemrajashaik sorry I don't understand what you mean or how it would help with what I want to achieve, could you explain a bit please?

**Comment by dhwang** [comment]
website says to contact them for Pro version that supports it

**Comment by bean5** [comment]
@hartill may this be closed?
