### ISSUE TITLE
For angular 2 ,the file is not loaded in excel format

### ISSUE THREAD

**Issue by Navya-adft** [SheetJS/js-xlsx#1185]
i implement the angular 2 demo..but file is displayed but,not in excel format ,it is in HTML format

![image](https://user-images.githubusercontent.com/32817841/42932585-3f126ec8-8b75-11e8-9eb5-ecc17e830e8d.png)

not possible to select columns or rows ..how to solve this problem ?

**Comment by SheetJSDev** [comment]
The point of the demo was to show how to work with data in a simple component.  There are third-party data display components that support column and row selection.

**Comment by Navya-adft** [comment]
So, you mean need to use third party component for that...But for sheet js demo ,excel format is shown...is it use third party component?which component you prefer ?

**Comment by SheetJSDev** [comment]
This project is specifically focused on reading and writing data.  There are excellent third party libraries for displaying an editable grid.  The https://sheet.js.org/ demo uses the canvas-datagrid library to display the data: https://github.com/TonyGermaneri/canvas-datagrid
