### ISSUE TITLE
sheetjs should provide minimum header title as bold functionality 

### ISSUE THREAD

**Issue by Waseemrajashaik** [SheetJS/js-xlsx#1187]
The minimum styling should be include in open source code for just header field as Bold.

**Comment by Waseemrajashaik** [comment]
@SheetJSDev  Please answer it

**Comment by kami23** [comment]
I agree

**Comment by kennylbj** [comment]
+1

**Comment by strerene** [comment]
+1

**Comment by Nesvet** [comment]
+1

**Comment by curiousalok** [comment]
+1

**Comment by dumbdonkey** [comment]
+1

**Comment by ResioSoftware** [comment]
+1

**Comment by SheetJSDev** [comment]
At its infancy, SheetJS was envisioned as a solution to a specific problem involving reading data from various file formats.  A bunch of default options are related to the fact that the original target was generating CSV (so by default, all values are processed by the number formatter).

We are unsure when the open source build will expand scope, but in the short term the main focus is data processing.  We offer extended functionality like styling and charts in a separate paid offering as described in https://sheetjs.com/pro
