### ISSUE TITLE
XLS BIFF8 export cannot be read by Numbers OSX

### ISSUE THREAD

**Issue by clicktravel-antonrand** [SheetJS/js-xlsx#1188]
Hello,

I have an XLS file - I read it:

```
var workbook = XLSX.readFile('./template/amendments.xls');
```

I don't even modify it - and write it back out:

```
XLSX.writeFile(workbook, './template/amendments-2.xls');
```

The resulting file cannot be previewed/opened - if I save it with the `.xslx` extension it works.

Have you dropped support for the `xls` format? Documentation suggests it is supported: https://docs.sheetjs.com/#supported-output-formats

I've added the bookType with `biff8` but still unviewable. I don't think the file I'm using is relevant.

Thank you

**Comment by SheetJSDev** [comment]
Can you share that `amendments.xls` file?  GH doesn't support XLS attachments so please send an email to support [at] sheetjs [dot] com and attach the file

**Comment by clicktravel-antonrand** [comment]
Hello - I've forwarded over. Let me know if you need any more information

**Comment by guojiaqi1027** [comment]
Any updates? I'm facing the same issue on Numbers

**Comment by SheetJSDev** [comment]
@clicktravel-antonrand @guojiaqi1027 finally had a moment to dig further, this is a funny issue with a fortunately easy fix.  If you'd like to submit this as a PR we'd accept:

```diff
+++ b/bits/78_writebiff.js
@@ -191,7 +191,7 @@ function write_ws_biff8(idx/*:number*/, opts, wb/*:Workbook*/) {
        write_biff_rec(ba, "HCenter", writebool(false));
        write_biff_rec(ba, "VCenter", writebool(false));
        /* ... */
-       write_biff_rec(ba, "Dimensions", write_Dimensions(range, opts));
+       write_biff_rec(ba, 0x200, write_Dimensions(range, opts));
        /* ... */
 
        if(b8) ws['!links'] = [];
```

Explanation: BIFF8 XLS, like other BIFF formats, ultimately stores the data and metadata as a stream of records.  There are two officially recognized record types for the Dimensions record (which stores the worksheet dimensions):

- `0x200 = 512` (record enumeration table at https://msdn.microsoft.com/en-us/library/dd945945.aspx)
- `0x000 = 0` (used in old Excel versions like Excel 3.0, see page 14 of http://www.idea2ic.com/File_Formats/excel_biff.pdf)

For some reason, Numbers only accepts the first type but Excel accepts both.  Version 0.12.1 added support for the `0`-type Dimensions record, which changed the export record type.  The included change forces the 512 record type
