### ISSUE TITLE
add formula (if-condition) is not working

### ISSUE THREAD

**Issue by donquan** [SheetJS/js-xlsx#1192]
hello friends,

i am trying to add so if-coditions as formula in my excel-sheet but in one case it is not working.
here is the source code:

addFormulaToWorksheeet: function(oWorksheet, data) {
			var ws = oWorksheet;
			for (var i = 3; i < data.length + 3; i++) {
				var cellAbweichungUmsatz = "I" + i;
				var cell1AbweichungUmsatz = "G" + i; 
				var cell2AbweichungUmsatz = "H" + i;
				ws[cellAbweichungUmsatz] = {
					f: 100 + "*" + cell1AbweichungUmsatz + "/" + cell2AbweichungUmsatz + "-100" --> this formula works fine!
				};
				ws[cellAbweichungUmsatz].z = "#,##0.00";
				var cellAbweichungTickets = "M" + i;
				var cell1AbweichungTickets = "L" + i; 
				var cell2AbweichungTickets = "K" + i; 
				ws[cellAbweichungTickets] = {
					 f: "IF(" + cell1AbweichungTickets + "=0;0)" -->This is not working (when open the generated excel, it says that something is not correct with the excel file.
				};
				ws[cellAbweichungTickets].z = "#,##0.00";
			}
			return ws;
		},

does somebody knows why using if conditions is not working?

thanks in advance for your help.

best regards,

Quan

**Comment by reviewher** [comment]
Formula expressions use the `en_US` form of the formula.  Commas should separate function arguments, not semicolons.
(Even though Excel displays the formula using semicolon delimiters, it actually writes commas in the file)

**Comment by donquan** [comment]
Hi reviewher,

thank you very much for your input.
I have tried this and it works fine.

thank you for your help.

best regards,

Quan
