### ISSUE TITLE
Compression on buffer output

### ISSUE THREAD

**Issue by glococo** [SheetJS/js-xlsx#1201]
Hi,
I can't save a compressed ODS buffer, see example:
```
var file = XLSX.write( book, { bookType:'ods', type:'buffer', compression:true } )
```
Buffer output comes uncompressed. Am I doing something wrong ?

**Comment by SheetJSDev** [comment]
ODS uses a ZIP based container.  The `compression` option refers to using the DEFLATE compression (mode 8) when generating said ZIP file.  To confirm the data is actually compressed, write the file somewhere to the file system and inspect using `unzip -lv`.  This test was done using the `xlsx` command line script that is installed when you install the module globally:

```
$ xlsx -o compressed.ods --ods --compress sheetjs.xlsx
$ xlsx -o uncompressed.ods --ods sheetjs.xlsx
$ unzip -lv uncompressed.ods 
Archive:  uncompressed.ods
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
      46  Stored       46   0% 08-05-2018 14:18 8a396c85  mimetype
    7308  Stored     7308   0% 08-05-2018 14:18 c36a102c  content.xml
     789  Stored      789   0% 08-05-2018 14:18 b6e63268  styles.xml
     406  Stored      406   0% 08-05-2018 14:18 aad088a0  meta.xml
    1232  Stored     1232   0% 08-05-2018 14:18 b351ed0b  manifest.rdf
     692  Stored      692   0% 08-05-2018 14:18 f2109d07  META-INF/manifest.xml
--------          -------  ---                            -------
   10473            10473   0%                            6 files
$ unzip -lv compressed.ods 
Archive:  compressed.ods
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
      46  Defl:N       44   4% 08-05-2018 14:18 8a396c85  mimetype
    7308  Defl:N     1195  84% 08-05-2018 14:18 c36a102c  content.xml
     789  Defl:N      260  67% 08-05-2018 14:18 b6e63268  styles.xml
     406  Defl:N      214  47% 08-05-2018 14:18 aad088a0  meta.xml
    1232  Defl:N      295  76% 08-05-2018 14:18 b351ed0b  manifest.rdf
     692  Defl:N      232  67% 08-05-2018 14:18 f2109d07  META-INF/manifest.xml
--------          -------  ---                            -------
   10473             2240  79%                            6 files
$ wc -c *compressed.ods
    2858 compressed.ods
   11091 uncompressed.ods
   13949 total
```

The method column shows how the data was persisted.  "Stored" is an uncompressed dump (method 0) and "Defl:N" uses the deflate algorithm (method 8).

The files are attached.  Unfortunately github doesn't support the ODS extension so they have been renamed to .zip -- remove the .zip extension if you want to view the files

[uncompressed.ods.zip](https://github.com/SheetJS/js-xlsx/files/2260593/uncompressed.ods.zip)
[compressed.ods.zip](https://github.com/SheetJS/js-xlsx/files/2260594/compressed.ods.zip)

**Comment by glococo** [comment]
Hi,

Thanks a lot for your explanation, I appreciate your effort. But probably I miss to point out that writing to the file system works good for me.

But I want to use a buffer to send it through a Telegram Bot as a document attachment, and in that point is where ZIP isn't working. If I write to Buffer, it compose the buffer uncompressed. If I write to filesystem it output zipped.
I can't write the ODS to the filesystem, send it, and delete that file later. I would like to send a buffer straight to the Telegram Bot, without writing to the FS.

Is it possible ?
Thanks a lot

**Comment by SheetJSDev** [comment]
You are running this in nodejs.  Ultimately writeFile calls write, so compression should be behaving the same in both places.  You can manually confirm, by writing the Buffer to a file, whether the file is compressed:

```js
var file = XLSX.write( book, { bookType:'ods', type:'buffer', compression:true } )
fs.writeFileSync("out.ods", file);
```

Can you check (using the `unzip -lv` approach described above) whether the generated file is compressed"?
