### ISSUE TITLE
Can not resolve xlsx on reactpoilerplate 

### ISSUE THREAD

**Issue by MehrnooshHajkhalil** [SheetJS/js-xlsx#1202]
Related to my question on stackoverflow : https://stackoverflow.com/questions/51694902/react-boilerplate-error-cant-resolve-xlsx-in-users-react-boilerplate-no

I am using react-boilerplate when I do run npm install I see these errors:

WARNING in ./node_modules/xlsx-style/ods.js
Module not found: Error: Can't resolve '../xlsx' in '/Users/mehrnooshhajkhalil/react-boilerplate/node_modules/xlsx-style'
 @ ./node_modules/xlsx-style/ods.js
 @ ./node_modules/xlsx-style/xlsx.js
 @ ./node_modules/node-excel-export/lib/excel.js
 @ ./node_modules/node-excel-export/index.js
 @ dll reactBoilerplateDeps

I did also try

 rm -rf node-modules,
 npm clean cache --force,
 npm install

But none of them did not solve my problem

Node version : v10.8.0 npm version : 6.2.0

**Comment by SheetJSDev** [comment]
`xlsx-style` is a separate project
