### ISSUE TITLE
"Cannot find file [Content_Types].xml in zip" over AWS

### ISSUE THREAD

**Issue by nicolaspfernandes** [SheetJS/js-xlsx#1206]
Hi! I'm using your library and so far it is being awesome for my solutions that needs to gather and dig excel data, thanks for the initiative!

However, I found a strange error. I'm running a method that will read a excel file buffer and convert it to a JSON/CSV by using the `sheet_to_json` and `sheet_to_csv` util methods. They are working perfectly fine on my local environment. However, when I deploy the code to a AWS lambda function, I got a strange issue when trying to parse a .xlsx file:

```
2018-08-07T12:05:49.773Z	388597f6-9a3a-11e8-bb18-532d0441f92d	Error: Cannot find file [Content_Types].xml in zip
at getzipfile (/var/task/node_modules/xlsx/xlsx.js:2084:22)
at getzipstr (/var/task/node_modules/xlsx/xlsx.js:2095:30)
at parse_zip (/var/task/node_modules/xlsx/xlsx.js:19172:22)
at read_zip (/var/task/node_modules/xlsx/xlsx.js:19501:9)
at Object.readSync [as read] (/var/task/node_modules/xlsx/xlsx.js:19566:69)
at Object.parseExcelToJson (/var/task/src/services/excel-service.js:14:31)
at module.exports.handler (/var/task/src/functions/customer/customer-bulk-create.js:24:42)
```

It runs perfectly fine on my local environment, only over AWS this error occurs. 
Another issue is: when I'm parsing a .xls file, it reads the file easily, but when it tries to convert the data, the information is not recognized as UTF-8 and isn't parsed properly. The data is available to me is:

![image](https://user-images.githubusercontent.com/7490993/43775374-d1a796bc-9a22-11e8-84ad-6cfe3f376dd6.png)
 
The data is being parsed like this, even though I'm forcing the `utf-8` encoding on my code:
```
    const fileContents = xlsx.read(excelData.content, {
      type: 'buffer',
      encoding: 'utf-8'
    });
```

Can you please help me to solve this issue? Thank you!

**Comment by SheetJSDev** [comment]
Lambda unfortunately parses the body by default and presents it as a UTF8 string, which makes it impossible to read from the body directly.  When we built the [`function` demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/function), to get around the limitation `base64` was used.  This is out of our control

Using S3, https://github.com/SheetJS/js-xlsx/issues/479 sketches how to read data using `getObject` -- you can concatenate the stream and parse with type `buffer`

**Comment by Cittadini** [comment]
Hi @nicolaspfernandes, do you have a solution for this issue?

Andrea
