### ISSUE TITLE
String 001, converted to 1 question

### ISSUE THREAD

**Issue by wubodanran** [SheetJS/js-xlsx#1207]
The td value read by XLSX.read is 001 (string type), which will be converted to 1, and 00 will be removed. How can I not convert?

**Comment by SheetJSDev** [comment]
`table_to_book` and `table_to_sheet` accept the `raw` option that skips all value interpretation, as explained in the documentation at https://docs.sheetjs.com/#html-table-input

**Comment by wubodanran** [comment]
![image](https://user-images.githubusercontent.com/29586966/44316508-a2cc9e00-a45e-11e8-94d1-1db7320c0dee.png)
After exporting, it becomes like this:
![image](https://user-images.githubusercontent.com/29586966/44316524-b11aba00-a45e-11e8-8da0-4b6fc2aaa1c3.png)
