### ISSUE TITLE
Support site is down ?

### ISSUE THREAD

**Issue by tochinet** [SheetJS/js-xlsx#1209]
Hi, The github site says that for "general support issues", the https://discourse.sheetjs.com/ should be used. But I get there a "Error 1016 Origin DNS error" . Any idea what I should do ? I'm a new user of xlsx, and I get an error (undefined "0" parameter ?) that I fail to understand. Am I allowed to post the question on this part of the site ?

**Comment by SheetJSDev** [comment]
At some point, Discourse offered a free instance for open source projects.  We tried but was ultimately unsuccessful in making that work, and they eventually shut it down.  That link should be removed; ask any questions here.

**Comment by tochinet** [comment]
Thanks. Will do in a separate thread.
