### ISSUE TITLE
How to export nested json files. When I tried it is missing few parameters

### ISSUE THREAD

**Issue by Shrinivassab** [SheetJS/js-xlsx#1213]
myjson = {
  "Name": "David",
  "pet name": "",
  "breakdown": "Daily",
  "dateRange": {
    "name": "Predefined",
    "valueInPredefined": {
      "name": "Yesterday",
      "code": "Yesterday"
    }
  },
  "reportOptions": "Run Now",
  "scheduled_date_ranges": {
    "startDate": "",
    "endDate": ""
  },
  "frequencyOptions": {
    "frequency": "",
    "timeUnit": "Monday"
  },
  "format": "CSV",
  "filterCriteria": [],
  "attributes": [
    {
      "rollnumber": 1146,
      "name": "aaa",
      "sex": "male"
    }
  ],
  "metrics": [
    {
      "metricId": 2,
      "name": "bsr",
      "customName": "CLICKS",
      "description": "gaming"
    },
  {
      "metricId": 1,
      "name": "bsrqwe",
      "customName": "DoubleCLICKS",
      "description": "gaming"
    }
  ]
}

How to export it as .xlsx file.

my export-component.ts

  public exportAsExcelFile(json: any[],excelFileName: string): void {
    // console.log(json)
    const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
    console.log('worksheet', worksheet);
    const workbook: XLSX.WorkBook = {
      Sheets: {
        'data': worksheet
      },
      SheetNames: ['data']
    };
    const excelBuffer: any = XLSX.write(workbook, {
      bookType: 'xlsx',
      type: 'array'
    });
    this.saveAsExcelFile(excelBuffer, excelFileName);
  }

  private saveAsExcelFile(buffer: any, fileName: string): void {
    const data: Blob = new Blob([buffer], {
      type: EXCEL_TYPE
    });
    FileSaver.saveAs(data, fileName + '_export_' + new Date().getTime() + EXCEL_EXTENSION);
  }

**Comment by SheetJSDev** [comment]
Nested objects are not supported (among other issues, how do you handle columns when different rows have objects of different shapes?). 

The easiest approach is to flatten the data objects yourself or generate an array of arrays.
