### ISSUE TITLE
how client download xlsx file

### ISSUE THREAD

**Issue by nvcken** [SheetJS/js-xlsx#122]
My node.js code
var file = fs.readFileSync('./report/output/out.xlsx', 'binary');
        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader('Content-Disposition', "attachment; filename=" + "out.xlsx")
        return res.end(file, 'binary');
How javascript client download this file ? I have try many way but get open file corrupt
Thanks for help

**Comment by lukelafountaine** [comment]
I encountered the same issue. Using the base64 type and File-Saver, I was able to get it to work. This post was very helpful with it: http://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript in case anyone else is stuck.

**Comment by ak4wrapp** [comment]
@nvcken nvcken  Do you have any sample Code for downloading excel export using Safari?

**Comment by BryanYang** [comment]
@nvcken so what ended up working for you? could you share your code ?

**Comment by SheetJSDev** [comment]
@ak4wrapp @BryanYang @lukelafountaine @nvcken @notatestuser Safari downloads are problematic, see [the relevant filesaver.js issue](https://github.com/eligrey/FileSaver.js/issues/12) for a longer discussion.  The best approach if you need to support generation in safari is to punt to the server.

http://sheetjs.com/demos/table.html demonstrates generating and downloading files using filesaver.js as well as [downloadify.js](https://github.com/dcneiner/downloadify), manually tested back to IE6.

The actual code that generates the file runs in Safari, which you should be able to verify by roundtripping in the browser:

```js
var outfile = XLSX.write(wb, {type:'binary'});
var new_wb = XLSX.read(outfile, {type:'binary'});
```

**Comment by Chipintoza** [comment]
Please Look at:
https://stackoverflow.com/a/34552682/5086654

> Could it because you are using connect-livereload plugin? The plugin seems cause corrupted binary files being transferred. I've encountered the same, and solved it by adding 'ignore' when initiate connect-livereload plugin.
> 
> app.use(require('connect-livereload')({
>     ignore:['.xls', '.xlsx']
> }));
> See this post for detail: https://github.com/intesso/connect-livereload/issues/39

**Comment by Terry-Su** [comment]
Just solved this problem. 
**Client**:
```js
const url = '/excel'

$.post(url, function (data) {
    const blob = new Blob([new Uint8Array(data.data)])
    download(blob, 'out.xlsx')
})
```
**Server**:
```js
const express = require('express')
const app = express()
const FS = require('fs')

const buffer = FS.readFileSync('./origin.xlsx')

app.use(express.static('./'))

app.post('/excel', function (req, res) {
    res.json(buffer)
})

app.listen(3000)
```


Having tried lots of possible answers on the internet, but they both seemed not work. So i created a simple client and server testing case and found the answer finally.   
(**Attachment**: [download.js](http://danml.com/download.html))

**Comment by DyuldinKS** [comment]
@Terry-Su, thanks a lot.
Maybe it's obvious, but I spent a few hours searching for an error. The key detail is to send **buffer** as **json**. If you are using `res.send` instead of `res.json` you will receive broken data.

In addition, short example with the generation of a xlsx on the server:

```js
// generate empty workbook
const wb = xlsx.utils.book_new();
const table = [['a', 'b', 'c'], [1, 2, 3]]
const ws = xlsx.utils.aoa_to_sheet(table);
xlsx.utils.book_append_sheet(wb, ws, 'test');

// write options
const wopts = { bookType: 'xlsx', bookSST: false, type: 'buffer' };
const buffer = xlsx.write(wb, wopts);
res.json(buffer);
```

**Comment by bscaspar** [comment]
For those still struggling - I ended up going with the response provided by @lukelafountaine . There are a few gotchas, so providing the full example here. [This post](https://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript) ended up being helpful.

server:
```
app.get('/', function (req, res) {
  
  res.setHeader('Content-Type', 'application/octet-stream');

  var dataArray = [{
    "id": 0,
    "species": "elk",
    "sex": "male"
  },{
    "id": 1,
    "species": "moose",
    "sex": "female"
  }];

  var wb = XLSX.utils.book_new();
  var ws = XLSX.utils.json_to_sheet(dataArray);
  XLSX.utils.book_append_sheet(wb, ws, "TestWB.xlsx");

  var wbopts = {
    type: 'base64',
    bookType: "xlsx",
    bookSST: false
  }

  var wbout = XLSX.write(wb, wbopts);

  console.log(wbout);

  res.send(wbout);
})
```
client:
```
    axios.get('http://localhost:3000', 
    {
      responseType: 'text',
      headers: { 'Content-Type': 'application/octet-stream'}
    }).then((res) => {
      var byteCharacters = atob(res.data);
      var byteNumbers = new Array(byteCharacters.length);
      for (var i = 0; i < byteCharacters.length; i++) {
        byteNumbers[i] = byteCharacters.charCodeAt(i);
      }
      var byteArray = new Uint8Array(byteNumbers);
      var blob = new Blob([byteArray], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
      
      fileSaver.saveAs(blob, 'xlsx.xlsx');
    })
```
