### ISSUE TITLE
EE is not a constructor

### ISSUE THREAD

**Issue by jakob-fuchs** [SheetJS/js-xlsx#1222]
I'm following this tutorial here: https://redstapler.co/sheetjs-tutorial-convert-excel-html-table/

The error message I get is: `Uncaught TypeError: Ee is not a constructor`

My code is here: https://kind-knuth-cf9a2f.netlify.com/ https://kind-knuth-cf9a2f.netlify.com/index.js

Since I don't know much about this library I don't have any clue why that is happening. I'd appreciate any help.

**Comment by xama5** [comment]
I don't think it has something to do with your code. I've been using similar code for 4 weeks and it broke just recently. Jumping back in my commit history back 4 weeks ago makes no difference, the same exception is thrown.

Tried downgrading via NPM down to 0.13.1 and also using the current master branch state.

Oddly enough the angular2 (angular5) demo works flawlessly. There must be something we're missing.

`ng --version`

```
Angular CLI: 6.1.4
Node: 8.11.1
OS: darwin x64
Angular: 6.0.7
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.4
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.7.4
@angular-devkit/schematics        0.7.4
@angular/cli                      6.1.4
@angular/compiler-cli             6.0.6
@ngtools/webpack                  6.1.2
@schematics/angular               0.7.4
@schematics/update                0.7.4
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.9.2
```

**Comment by SheetJSDev** [comment]
@jakob-fuchs @xama5 can you try rolling back to Angular 5.x?

**Comment by jakob-fuchs** [comment]
I'm loading the xlsx.min file form the dist directory with a script tag. I guess that's the correct way?

**Comment by xama5** [comment]
In the demo you provided you're not using the full dist.

It should be

`<script lang="javascript" src="./node_modules/xlsx/dist/xlsx.full.min.js"></script>`

instead of

`<script src="./node_modules/xlsx/dist/xlsx.min.js"></script>`

Can you verify?

**Comment by jakob-fuchs** [comment]
Yes, I missed that. Thanks for catching that.

**Comment by brickspert** [comment]
`import XLSX from 'xlsx/dist/xlsx.full.min';`  work for me!
but `import XLSX from 'xlsx';` or `import XLSX from 'xlsx/dist/xlsx.min';` not work for me!

early, i use `import XLSX from 'xlsx'`, it work!  but now ,it not work!  why??

**Comment by xama5** [comment]
@brickspert Read my reply more carefully.

It should be `import * as XLSX from 'xlsx';`

Everything else will not work.

**Comment by brickspert** [comment]
@xama5 no，i used `import * as XLSX from 'xlsx'`  one month ago, it worked for me！

but,  i have not change any code , it broke just recently. the error message is `ke is not a constructor`.

i must change it to `import XLSX from 'xlsx/dist/xlsx.full.min'`,  it works for me!

so , i don't know why~~

**Comment by xama5** [comment]
@brickspert That's strange. Do you have your code somewhere on GitHub?

**Comment by brickspert** [comment]
@xama5  no, it's a private project.   i think that's so strange !

now i use `import XLSX from 'xlsx/dist/xlsx.full.min'`, it work for me .

some days ago, i use `import * as XLSX from 'xlsx'` . but now ,it not work!

are you chinese??

**Comment by selcukoguz** [comment]
@brickspert it work for me to. I think because of routes includes lazy component.
