### ISSUE TITLE
How to export excel sheet with full size of hearders?

### ISSUE THREAD

**Issue by AlaaFarok** [SheetJS/js-xlsx#1224]
I'm using aoa to export data to excel sheet.
```
    const ws: XLSX.WorkSheet = XLSX.utils.aoa_to_sheet(this.eportedData);
    const wb: XLSX.WorkBook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Sheet1');
```
I want the headers that are in the excel sheet take the full size of the header name, no need for the user to resize them manually.

**Comment by SheetJSDev** [comment]
Unfortunately Excel exposes no option to mark columns to automatically resize.  You can get a reasonable estimate by manually walking the cells of each column, figuring out the max number of characters in a cell, and setting the [column width object's `wch` property](https://docs.sheetjs.com/#column-properties)

In our Pro builds, auto widths are determined by inspecting individual cell text and fonts to calculate what the correct width would be.
