### ISSUE TITLE
Export with cell AND text formating (fiddle included)

### ISSUE THREAD

**Issue by cyberjetx** [SheetJS/js-xlsx#1226]
How would I export while maintaining the format of both the cells and the contained text given the simple table here: .  

Fiddle: 
http://jsfiddle.net/Cyberjetx/k3gjanwm/ 

<table id="myTableName" class=".datatbl ">
  <thead id="myTableNameHdr">
    <tr>
      <th style="background-color:navy;color:white;">Test</th></tr>
  </thead>
  <tbody id="myTableNameBod" class="greenbar">
    <tr class="GreenBar">
      <td>
        Choose
        <span style="color:red">RED </span> or
        <span style="color:blue">BLUE </span> colors...
      </td>
    </tr>
    <tr class="GreenBar">
      <td>
        Choose
        <span style="color:Green">Green </span> or
        <span style="color:#3300DD">3300DD </span> colors...
      </td>
    </tr>
  </tbody>
</table>

**Comment by SheetJSDev** [comment]
These are features offered in our Pro builds, inquire at pro@sheetjs.com
