### ISSUE TITLE
String 004, converted to 4 question...

### ISSUE THREAD

**Issue by wubodanran** [SheetJS/js-xlsx#1227]
![20180820112707](https://user-images.githubusercontent.com/29586966/44319123-7e77be00-a46c-11e8-886b-aade73dc7778.png)

After exporting, it becomes like this:

![44316524-b11aba00-a45e-11e8-8da0-4b6fc2aaa1c3](https://user-images.githubusercontent.com/29586966/44319083-4a040200-a46c-11e8-9758-80c4f61b0010.png)

The export result I want is also 004;

**Comment by SheetJSDev** [comment]
There are currently two ways to do this:

1) set the option `raw:true` when calling `table_to_sheet` or `table_to_book`.  This will treat all values as text, so it will return `"10003"` and `"004"`

2) if you know which cells you want to set as text in advance, set the `t` attribute of the `TD` element to `"s"`.  Example fiddle: http://jsfiddle.net/8Lq6crex/

```
<td>004</td>  <!-- interpreted as number 4 -->
<td t="s">004</td> <!-- interpreted as string "004" -->
```
