### ISSUE TITLE
The sheet name included in DefinedName garbled.

### ISSUE THREAD

**Issue by feuxfollets1013** [SheetJS/js-xlsx#1229]
When a sheet name includes Japanese, the sheet name included in WorkBook.Names[].Ref garbled.

## Steps to Reproduce
Link:https://codesandbox.io/s/1v87rk3lpj

1. select xlsx
2. input form onchange fired.
3. read workbook
4. this issue occured.

## Context
I would like to the following.
~~~
/**
 * @params workbook {XSLX.WorkBook}
 * @params sheetName string
 * @params definedName string
 */
const getCellValueByDefinedName = (workbook, sheetName, definedName) => {
  const targetSheetNameRegex = new RegExp(`'${sheetName}'!.*`);
  for( name of workbook.Names) {
    if (name.Name === definedName && name.Ref.match(targetSheetNameRegex)) {
      const cell = name.Ref.replace(/'.*'\!/, '').replace(/\$/, ''); // Ref: 'sheetName'!$A$1 -> A1
      return workbook[sheetName][cell].v;
    }
  }
  return null;
}

const definedNamedCellValue = getCellValueByDefinedName(workbook, 'あいうえお', 'hello');
~~~

## My Environment
| Tech         | Version |
|--------------|---------|
| language  |  Japanese(UTF-8) |
| Excel |  MS Office 2016 |
| Browser      |   Chrome r68      |
| OS   |    windows7 64bit     |

**Comment by SheetJSDev** [comment]
The offending line is https://github.com/SheetJS/js-xlsx/blob/master/bits/72_wbxml.js#L89, it should be:

```js
dname.Ref = unescapexml(utf8read(data.slice(dnstart, idx)));
```

We'd accept a PR with that change.

P.S.: If you could make a throwaway file we can add it to the test suite.

**Comment by feuxfollets1013** [comment]
Thank you for your reply.

In addition, I think that the following modification is necessary.
https://github.com/SheetJS/js-xlsx/blob/master/bits/72_wbxml.js#L83
~~~
dname.Name = utf8read(y.name);
~~~

Attached is the TestWorkBook.It includes the following patterns.
SheetName/DefinedName
1. Ascii only.
2. Japanese only.
3. Starting with ascii and the end is Japanese.
4. Starting with Japanese and the end is ascii.
5. Starting with ascii, including Japanese.

[TestBook.xlsx](https://github.com/SheetJS/js-xlsx/files/2308604/TestBook.xlsx)

**Comment by SheetJSDev** [comment]
@feuxfollets1013 thanks a lot, we can strip this down and add some more test cases.

If you would like, you can make a PR with the two changes.  If not, we can push a change tomorrow
