### ISSUE TITLE
need to  take number's as in excel format

### ISSUE THREAD

**Issue by anyboose** [SheetJS/js-xlsx#1232]
![screenshot_1](https://user-images.githubusercontent.com/42623368/44490602-20b7c180-a678-11e8-9e84-77a318166136.png)

Hi there 
How i can take numer with format as in excel. Now it get more longer.

function excel(value) {
    var desired_cell = worksheet[value];
    var result  = (desired_cell ? desired_cell.v : undefined);
    results.push(result)
    console.log(result);
}
results = []
if(typeof require !== 'undefined') XLSX = require('xlsx');
var workbook = XLSX.readFile('EDS.xlsx');
var first_sheet_name = workbook.SheetNames[0];
var worksheet = workbook.Sheets[first_sheet_name];
var address = ['B1','B2','B3','D1','D2','D3','A5','E1'];

address.forEach(excel);

**Comment by SheetJSDev** [comment]
the `.v` values are the raw numbers, and what you're seeing is an IEEE754 artifact.  You're probably familiar with the classic `0.1 + 0.2 != 0.3`:

```js
> 0.1+0.2
0.30000000000000004
```

the `.w` field has the formatted text.
