### ISSUE TITLE
数据导出问题

### ISSUE THREAD

**Issue by syf1211** [SheetJS/js-xlsx#1233]
为什么数据会重复一次，显示两个

**Comment by shikelong** [comment]
Please use english in github.

**Comment by keithbox** [comment]
very interesting, let me be your translator.

syf1211: 为什么数据会重复一次，显示两个
(why the exported records got twice)

reviewher: Can you share an example?
(上傳你的例範以提供更多詳情)

**Comment by SheetJSDev** [comment]
Please rephrase in English
