### ISSUE TITLE
How can I export table to excel when I use ant-design-pro

### ISSUE THREAD

**Issue by m26597** [SheetJS/js-xlsx#1235]
The project I am developing is using the antd pro, I need to export the table component to excel .
How could I do this by the use of SheetJS? Could you help me in detail? Thanks.

**Comment by SheetJSDev** [comment]
Assuming you are referring to 
https://ant.design/components/table/#header , you can export the generated table or you can export the source data.

To export the generated table, use `table_to_sheet` on the TABLE DOM element to generate a worksheet.

To export the source data, you can call `json_to_sheet` on the array of JS objects to generate a worksheet.

**Comment by m26597** [comment]
Cool! Thank you. So helpful website,but if I only want to use the function of exporting table to excel, need I use the all xlsx or is there a new-hand introduce ? Besides, could you tell me how to get the table element like `var elt = document.getElementById('data-table');` in antd?

**Comment by m26597** [comment]
Yes! What I want to do is the export to xlsx function in the link "[http://sheetjs.com/demos/table](url).

**Comment by m26597** [comment]
Where could I see the source code ? Please give me a link, thank you

**Comment by SheetJSDev** [comment]
@m26597 that's a question better addressed to the ant developers.  You need to get a reference to the generated TABLE.

P.S.: the source to the page is unminified.  You can view source

**Comment by m26597** [comment]
I've read the source code through F12, so the last problem is "need I use the all xlsx or is there a new-hand introduce ? Besides, could you tell me how to get the table element like var elt = document.getElementById('data-table'); in antd?"

**Comment by m26597** [comment]
All right, I would try to realize the function. Anyway, Thank you very much.

**Comment by m26597** [comment]
I'm sorry, I have another issue, Is the exported excel a similar excel but actually  a text or html just like a excel?

**Comment by dave-wind** [comment]
you can try to see
https://github.com/dave-wind/excel
