### ISSUE TITLE
issue downloading xlsx file with latest version (0.13.3) and angular 6+

### ISSUE THREAD

**Issue by arunprasathv** [SheetJS/js-xlsx#1243]
able to download excel file (json to excel) but when i open the file, getting an error as corrupted.  unable to view the file. 
does 0.13.3 compatible with angular 6 ?

package.json file 

"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
  "xlsx": "^0.13.3",
    "zone.js": **"0.8.26"**

devDependencies
  "@angular-devkit/build-angular": "~0.6.8",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.0",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "2.7.2"

Code
  public exportAsExcelFile(json: any[], excelFileName: string): void {
    const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
    const workbook: XLSX.WorkBook = { Sheets: { 'data': worksheet }, SheetNames: ['data'] };
    const excelBuffer: any = XLSX.write(workbook, { bookType: 'xlsx', type: 'buffer' });
    this.saveAsExcelFile(excelBuffer, excelFileName);
  }

  private saveAsExcelFile(buffer: any, fileName: string): void {
    const data: Blob = new Blob([buffer], {
      type: EXCEL_TYPE
    });
    FileSaver.saveAs(data, fileName + '_export_' + new Date().getTime() + EXCEL_EXTENSION);
  }

**Comment by SheetJSDev** [comment]
Try using writeFile directly instead of write:

```js
XLSX.writeFile(workbook, fileName + 'export' + new Date().getTime())
```

**Comment by arunprasathv** [comment]
thanks, it works.
