### ISSUE TITLE
how can i save edited file into one of my project folder?

### ISSUE THREAD

**Issue by ShirGrinblat** [SheetJS/js-xlsx#1246]
Hey,
I'm trying to figure how to save edited file into one of my project folder.
thank's for your help!

**Comment by SheetJSDev** [comment]
Using node.js you would specify the directory in the filename:

```js
XLSX.writeFile(wb, "/tmp/test.xlsx"); // writes to the file test.xlsx in the /tmp directory
```

In the browser, you can't generally specify an output path (security restrictions).  Generated files will show up in your Downloads directory and you can move them manually.

**Comment by ShirGrinblat** [comment]
I don't think you got me.
I don't want to save it locally, I want to save it in a folder on my
project

בתאריך יום ד׳, 29 באוג׳ 2018, 18:13, מאת SheetJSDev ‏<
notifications@github.com>:

**Comment by SheetJSDev** [comment]
The `write` function can generate Uint8Array:

```js
var u8a = XLSX.write(wb, {type:"array", bookType: "xlsx"});
```

From there, you can upload or do something else.  The actual logistics of saving the file elsewhere is outside the scope, but you can see demos like [`xhr`](https://github.com/SheetJS/js-xlsx/tree/master/demos/xhr).

**Comment by ShirGrinblat** [comment]
Forgive me, but i don't see in the Demo a write function that uses
Uint8Array (only a read function and i need to upload a file to a folder-
so i need a write function).
I would love your help

‫בתאריך יום ד׳, 29 באוג׳ 2018 ב-20:07 מאת ‪SheetJSDev‬‏ <‪
notifications@github.com‬‏>:‬
