### ISSUE TITLE
Add a sheet_to_aoa function 

### ISSUE THREAD

**Issue by kasbah** [SheetJS/js-xlsx#1258]
Would be handy to be able to turn the sheet into an array of arrays. 

```js
for (const row of xlsx.utils.sheet_to_aoa(s)) {
  for (const cell of row) {
  //...
  } 
}
```

May also help with #1234

**Comment by kasbah** [comment]
Here is a workaround implementation via tab-separated-values:

```js
const xlsx = require('xlsx')

function sheet_to_aoa(sheet)  {
  const FS = '\t'
  return xlsx.utils.sheet_to_csv(sheet, {FS}).split('\n').map(r => r.split(FS))
}
```

**Comment by kasbah** [comment]
Just found out about `header: 1` in sheet_to_json, so above can become: 

```js
function sheet_to_aoa(sheet) {
  return xlsx.utils.sheet_to_json(sheet, {header: 1})
}
```

**Comment by tarwin** [comment]
I also find it quite strange that this function doesn't exist. I understand you can get the same thing using `sheet_to_json` but this is not what you would think you would do to get data in this format. Seeing as there is a bunch of functionality that requires data in this format for writing, it makes a lot of sense to have it for reading too.
