### ISSUE TITLE
Date cells

### ISSUE THREAD

**Issue by elad** [SheetJS/js-xlsx#126]
Excel supports cells that display formatted dates. For testing purposes I created a file with only one cell (A1) and entered the value `2014-09-28`. The value was immediately formatted as a date and displayed as `9/28/14`.

I wanted to see how I can reliably extract back the original date. I used the following program:

```
var xlsx = require('xlsx');

var workbook = xlsx.readFile(process.argv[2]);
for (var i = 0; i < workbook.SheetNames.length; i++){
    var worksheet = workbook.Sheets[workbook.SheetNames[i]];
    console.log(worksheet);
}
```

And got the following output (after running it with `node myfile.xlsx`);

```
{ A1: { t: 'n', v: 41910, w: '9/28/14' }, '!ref': 'A1' }
{}
{}
```

I see several problems here:
- The number 41910 is the number of days from some epoch, either 1900 or 1904, depending on where the file was created (Windows or Mac). There should be a way to tell how to treat this value.
- The `t` field (for type) indicates this is a number. Can it instead indicate it's a date? or should there be a different property?
- There's no way to retrieve the actual value that was entered - `2014-09-28` - so the original date, along with a reliable way of retrieving it, seems to be lost.

All of the above also applies for time fields.

Am I missing something? Is there a way to reliably get 2014-09-28 from the cell data?

**Comment by Aymkdn** [comment]
Any clue ? :-)

**Comment by SheetJSDev** [comment]
@Aymkdn haven't forgotten, muddling through some other uncommitted SSF changes.

**Comment by satya-dash** [comment]
Hi Everyone.Can you please tell me how to put a formula in a cell of my excel like SUM(E2:E26).

I have some numbers in a column and want to add them with a SUM formula at the end of the data.So I tried to put the the formula in that particular cell but i couldn't.I am not able to use the cell object key "f" for the formula.So can anyone tell me how to use the formula in the excel so that my created Excel sheets will work more intelligently.

**Comment by SystemParadox** [comment]
@satya-dash what has that got to do with dates? Please open a new issue.

**Comment by satya-dash** [comment]
Nothing with date.Am creating a new issue in guthub regarding my query.

The query is all about the use of the cell object key *f *for putting
formula in the excel sheet cell.
From the documentation it is not clear and am not getting anything about it
from google also.So thought of asking directly to you.

Please reply me so that i can create a new thread regarding this issue.

**Comment by Aymkdn** [comment]
My suggestion is to add `fmt` and `fmtid` to the returned cell object, so the developer can then look at these values and decide what to do on his/her hand: https://github.com/Aymkdn/js-xlsx/blob/fb4e4ef4ea5fdbf3efc78174740f4567587b2e59/xlsx.js#L7250-L7252

For example if it's a date, the cell will have `cell.t == "n"` but also `cell.fmt == "[$-409]d\-mmm\-yy;@"` -- the developer can detect this special `fmt` and then he/she can use `XLSX.SSF.parse_date_code(cell.v)` to get the related date!

**Comment by despairblue** [comment]
@Aymkdn that would be awesome. When parsing the sheet I'm not sure if I got a date or a number, the mapping to my application model happens at a later point. It would be useful to differentiate between number and date when reading the file.

**Comment by Aymkdn** [comment]
@despairblue you can look at my library here http://aymkdn.github.io/ExcelPlus/ that does  what I stated here :-)

**Comment by despairblue** [comment]
@Aymkdn sadly I need a nodejs package :pensive:

**Comment by despairblue** [comment]
I settled for a simple, albeit dirty, solution: 

```js
const cellToType = (cell) => {
  switch (cell.t) {
    // ...
    case 'n':
      // see https://github.com/SheetJS/js-xlsx/issues/126
      if (cell.w.includes('/')) {
        return new Date(cell.w)
      }
      return Number.parseFloat(cell.w)
    // ...
    default:
      throw new Error(`${cell} is no valid Cell.`)
  }
}
```

**Comment by lucianoybanez** [comment]
be carefull with this solution if the date is 10/10/3000 it takes like 1/1/00 and when convert to date it converts to 10 october " 2000"

**Comment by lucianoybanez** [comment]
`if((new Date(val.w) !== "Invalid Date" && !isNaN(new Date(val.w)))){
                var dateSplited = val.w.split('/');
                if(dateSplited[2].length==4){                    
                    ret = new Date(val.w);
                }else{
                    throw 'XLSX library known issue. Select format date on excel m/d/yyyy';
                }           `

**Comment by lucianoybanez** [comment]
```
if((new Date(val.w) !== "Invalid Date" && !isNaN(new Date(val.w)))){
                var dateSplited = val.w.split('/');
                if(dateSplited[2].length==4){                    
                    ret = new Date(val.w);
                }else{
                    throw 'XLSX library known issue. Select format date on excel m/d/yyyy';
                }           
```

**Comment by despairblue** [comment]
@lucianoybanez thanks, that looks more robust. I'm going to use this, although we don't have to handle any dates later than about year 2100.

**Comment by SheetJSDev** [comment]
We're making the following changes to address this:

- `SSF.is_date(fmt)` uses the tokenizer from the formatter to determine if a format string is a date
- `cellDates:true` option for every format will look at the number format and generate dates (type `d`) if the format is a date format

**Comment by pradeepntip** [comment]
Hi,

I have some epoch timestamps in my data set. How can convert them date string while writing to xlsx ?
Any help!!

**Comment by rajeshprkpp** [comment]
Recently I found this link https://lifesaver.codes/answer/format-date-question, it has provided me the solution to converting date to yyyy-mm-dd. If we have date format yyyy-mm-dd in excel, while uploading it, the date is converting to format yyyy/mm/dd.

It says
var wb = XLSX.read(binary, {type:'binary', cellDates:true, cellNF: false, cellText:false});
XLSX.utils.sheet_to_json(ws, {dateNF:"YYYY-MM-DD"})

I applied this code and it worked for me.

So this is applicable even if you have date format as dd-mm-yyyyy in your excel and also if you have date columns as Text formatted in your excel.

**Comment by ligang-code2020** [comment]
Now I want to turn off the date conversion. For example, I want to export the string '1.9.3', and sheet.js is automatically installed and replaced with 2003/1/9. How to turn it off

**Comment by ligang-code2020** [comment]
> Now I want to turn off the date conversion. For example, I want to export the string '1.9.3', and sheet.js is automatically installed and replaced with 2003/1/9. How to turn it off

well. i find way to resolve my question.just to set up {type:"array",raw:"true"}
