### ISSUE TITLE
As of release 0.14.0, dates in CSV come through as floats/epoch

### ISSUE THREAD

**Issue by bean5** [SheetJS/js-xlsx#1260]
**Expected**
String comes through as a string.
**Actual**
TimeStamp string is converted to a float.

**Steps to Reproduce**
```
ID,TimeStamp
25,2018/09/06 07:38:27
```

The timestamp ends up as `43349.31836805555`. It appears to be an epoch time, but that epoch converted a date yields `GMT: Thursday, January 1, 1970 12:02:29.318 PM` (mismatches primary input).

**Discussion**
Is this a feature or a bug? If it is a feature, is there a setting to force the new version to do what version 0.13.5 was doing?

**Comment by SheetJSDev** [comment]
0.14.0 flipped the default of the `raw` option to `sheet_to_json`.  Long story short, the old behavior should not have been the default and it was causing gnarly workarounds elsewhere like in [the gatsby excel transform](
https://github.com/gatsbyjs/gatsby/issues/7790#issuecomment-417829074).  To recover the original string behavior, explicitly pass the option `raw:false`:

```js
XLSX.utils.sheet_to_json(ws, {raw: false})
```

Alternatively, in the specific case of handling dates, you can also pass the option `cellDates:true` to the read function:

```js
XLSX.read(..., {..., cellDates: true})
```

**Comment by bean5** [comment]
Thanks for the quick response, @SheetJSDev .

**Comment by bean5** [comment]
FWIW Your site at http://oss.sheetjs.com uses the new way. For CSV files, this means that rather than showing the data as-is from the CSV, it gets converted. This comes across as strange. It makes demoing your library counter-intuitive (kinda ruining the demo for me).

**Comment by SheetJSDev** [comment]
Good catch, the site should update soon.  Relevant commit: https://github.com/SheetJS/SheetJS.github.io/commit/6fbde36e53be14ef9dd081918ff04573ceefe24f

**Comment by bean5** [comment]
Cool.
