### ISSUE TITLE
cell style issue

### ISSUE THREAD

**Issue by BruceAndLee** [SheetJS/js-xlsx#1267]
why cell style has no effective,such as backgroud color,font color? Whether professional version can resolve this issue?

**Comment by harbhub** [comment]
Cell styles are handled by the Pro Version: https://sheetjs.com/pro

If interested, then you can send an email inquiry to: pro@sheetjs.com

**Comment by StephenXier** [comment]
Could you tell me how to use the Pro version

**Comment by BruceAndLee** [comment]
> Could you tell me how to use the Pro version

I has given up，used kendo instead:https://www.telerik.com/kendo-angular-ui/components/excelexport/api/CellOptions/
