### ISSUE TITLE
Set cell format to short date format

### ISSUE THREAD

**Issue by prajwal78** [SheetJS/js-xlsx#1268]
I have the below snippet of code which generates an excel for my project:

![image](https://user-images.githubusercontent.com/10049692/45413100-a7106380-b678-11e8-824d-82de48d2ae0b.png)

My question is how do I programmatically each cell within the excel sheet to short date format ?

**Comment by reviewher** [comment]
The "Short Date" format is [Format code `14`](https://github.com/SheetJS/js-xlsx/blob/master/bits/11_ssfutils.js#L7), you can set the `.z` field of each relevant cell object in the workbook to the number 14 (or to the text `m/d/yy`)
