### ISSUE TITLE
XLSX.utils.sheet_to_csv doesn't work?

### ISSUE THREAD

**Issue by hqxf** [SheetJS/js-xlsx#1269]
var wb = this.$XLSX.utils.table_to_book(document.querySelector("#out-table"));
      var wbout = this.$XLSX.write(wb, {
        bookType: format,
        bookSST: true,
        type: "array"
      });
      // This method does not take effect and return value is null
      console.log(this.$XLSX.utils.sheet_to_csv(wb, { FS: "***", strip: true }))
      try {
        FileSaver.saveAs(
          new Blob([wbout], { type: "application/octet-stream" }),
          "devicenIformation." + format
        );
      } catch (e) {
        this.$message.error('export error')
      }

thanks

**Comment by reviewher** [comment]
`wb` is a workbook object, but `sheet_to_csv` expects a worksheet object.  To convert the first worksheet:

```js
var ws1 = wb.Sheets[wb.SheetNames[0]];
var csv = this.$XLSX.utils.sheet_to_csv(ws1, { FS: "***", strip: true });
console.log(csv)
```

**Comment by hqxf** [comment]
var wb = this.$XLSX.utils.table_to_book(document.querySelector("#out-table"));
var ws1 = wb.Sheets[wb.SheetNames[0]]
 this.$XLSX.utils.sheet_to_csv(ws1, { FS: "***", strip: true });

Invalid regular expression: /***+$/: Nothing to repeat
