### ISSUE TITLE
read to more decimal places

### ISSUE THREAD

**Issue by SpeedyH30** [SheetJS/js-xlsx#1271]
I'm using js-xlsx inside a react app to read a spreadsheet. Some of the numbers in it are 12 decimal places long but when I see the results of what has been read I only get 8. I didn't think this would be an issue but apparently according to the accountants that use this system those extra decimal places are important.

So the question is. 
Is there a way to stipulate how many decimal places to read to or is 8 the max/default

fileDropped = files=> {
    const reader = new FileReader()
    this.setState({
        loading: true,
        message: 'blah'
    })
    reader.addEventListener('load', () => {
        this.workbook = XLSX.read(reader.result, {
            type: 'binary',
            cellHTML: false,
            cellText: false,
            cellNF: false,
            bookSheets: false,
            cellDates: true
        })
        this.setState({
            loading: false,
            message: 'blah'
            sheets: this.workbook.SheetNames
        })
    })
    reader.readAsBinaryString(files[0])
}

The above is my reader part

**Comment by reviewher** [comment]
Can you share a sample file?

**Comment by SpeedyH30** [comment]
unfortunately  not

**Comment by SheetJSDev** [comment]
The `v` property of each numeric cell is the exact value stored by Excel.  If you are only seeing 8 decimal places, that is your JS code displaying only 8 digits.

If `cellNF: false` is set, then any subsequent function that touches the cell will set the formatted text as if the "General" format is applied.  Note that this is *different* from what is shown in the formula bar.  The unfortunate problem is that the number you see in the formula bar isn't stored anywhere.  It's literally the raw text form of the IEEE754 number In XLSX, or a 34-bit RkNumber in XLS.
