### ISSUE TITLE
"Save as" functionality of browsers

### ISSUE THREAD

**Issue by ratikanta-sdrc** [SheetJS/js-xlsx#1272]
While downloading, the user wants to select the directory where he wants to save. This is not available now.  

Something like following
```
let saveAs: boolean = true
XLSX.writeFile(workbook, filename, saveAs)
```

**Comment by SheetJSDev** [comment]
There are a [handful of techniques for downloading a file](https://github.com/SheetJS/js-xlsx/blob/master/bits/19_fsutils.js#L11).  None of them, with the notable exception of the rarely-used IE6-9 ActiveX approach, lets you programmatically control the output directory.  Showing the "Save As" dialog is controlled by browser settings.  This is outside our control until browser vendors add this option
