### ISSUE TITLE
error when open generated xls file in exel 2016 or exel online

### ISSUE THREAD

**Issue by Lebed71** [SheetJS/js-xlsx#1275]
But xlsx file correct  (only change bookType "xls" => "xlsx")
Attach files - https://drive.google.com/open?id=1cLfXMfskb8eYzIBG2xcrntObzk6va-wH

**Comment by SheetJSDev** [comment]
How was the xls file generated?  If you used bookType "xls" the generated file would have been an XLS file.  This looks like a mal-formed XLSX file.

To verify the file type, look at the first few bytes:

```
$ xxd test.xlsx | head -n 2
00000000: 504b 0304 0a00 0000 0000 bc82 334d d692  PK..........3M..
00000010: 7c11 5a01 0000 5a01 0000 1100 0000 646f  |.Z...Z.......do

$ xxd test.xls | head -n 2
00000000: 504b 0304 0a00 0000 0000 e781 334d d692  PK..........3M..
00000010: 7c11 5a01 0000 5a01 0000 1100 0000 646f  |.Z...Z.......do

$ xlsx -8 test.xlsx # generate an XLS file using the library
$ xxd test.xlsx.xls | head -n 2
00000000: d0cf 11e0 a1b1 1ae1 0000 0000 0000 0000  ................
00000010: 0000 0000 0000 0000 3e00 0300 feff 0900  ........>.......
```

XLS files generated by the library will start with 0xD0 0xCF 0x11 0xE0, while XLSX files start with the ZIP marker 0x50 0x4b 0x03 0x04

**Comment by Lebed71** [comment]
Sorry, but why Node.js XLSX module doesn't supported biff8 type?
Quote from source model code (typical path to file: "./node_modules/xlsx/xlsx.js", line number: 12542):
`function writeSync(wb, opts) {
	var o = opts||{};
	switch(o.bookType || 'xlsx') {
		case 'xml': return write_string_type(write_xlml(wb, o), o);
		case 'csv': return write_string_type(write_csv_str(wb, o), o);
		case 'fods': return write_string_type(write_ods(wb, o), o);
		case 'biff2': return write_binary_type(write_biff_buf(wb, o), o);
		case 'xlsx':
		case 'xlsm':
		case 'xlsb':
		case 'ods': return write_zip_type(wb, o);
		default: throw new Error ("Unrecognized bookType |" + o.bookType + "|");
	}
}`
