### ISSUE TITLE
Need help, Attempting to use this on a isolated network

### ISSUE THREAD

**Issue by CasualRocket** [SheetJS/js-xlsx#1283]
Move the xlsx.min.full.js to my isolated network but the code does not work once its moved. SPD doesnt even recognize it as code. 

I could barely get the example to work on the internet side of my office. 

Simply i am just trying to use the excel -> HTML table part of the whole thing.

**Comment by SheetJSDev** [comment]
It sounds like you are hosting the file from a folder that is not using the proper encoding.  You have to change the default page encoding to UTF-8
