### ISSUE TITLE
ERROR in ./node_modules/xlsx-styles/dist/cpexcel.js

### ISSUE THREAD

**Issue by Hamza945** [SheetJS/js-xlsx#1285]
Hi,
I am using Mean stack App. when I run build command "npm run build" then i get this below errors.
I have tried to run build using angular-cli version 1.0.0 to 6.x.x but still same error occur.

ERROR in ./node_modules/xlsx-styles/dist/cpexcel.js
Module not found: Error: Can't resolve './cptable' in 'F:\Freelance Projects\ReC                                                                                                    ycleAssociation\syncbizz\node_modules\xlsx-styles\dist'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-full-stack@5.0.3 build: `ng build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-full-stack@5.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                    ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\M Hamza\AppData\Roaming\npm-cache\_logs\2018-09-24T19_44_2                                                                                                    3_377Z-debug.log

Please need your support.

**Comment by dawlat-netlinks** [comment]
It seems that there is a bug in the xlsx-style/dist/cpexcel.js file.

(function(root, factory){ "use strict"; if(typeof cptable === "undefined") { if(typeof require !== "undefined"){ var cpt = require('cpt' + 'able'); <<--

The last line should be: var cpt = cptable;

This will fix your problem

You'll find this piece of code starting on line 807 in the mentioned file

You should check this [78](https://github.com/protobi/js-xlsx/issues/78)

**Comment by SheetJSDev** [comment]
This is the repository for the `xlsx` module
