### ISSUE TITLE
NodeJS minimal write example

### ISSUE THREAD

**Issue by mgcrea** [SheetJS/js-xlsx#129]
I'm having a hard time to have a functional `XLSX.write` in NodeJS:

``` js
function Workbook() {
  if(!(this instanceof Workbook)) return new Workbook();
  this.SheetNames = [];
  this.Sheets = {};
}
var data = [[1,2,3],[true, false, null, 'sheetjs'],['foo','bar',new Date('2014-02-19T14:30Z'), '0.3'], ['baz', null, 'qux']];
var ws_name = 'SheetJS';
var wb = new Workbook(), ws = sheet_from_array_of_arrays(data);
wb.SheetNames.push(ws_name);
wb.Sheets[ws_name] = ws;
var wbout = XLSX.write(wb, '/tmp/out.xlsx',{bookType:'xlsx', bookSST:false, type: 'binary'});
```

I get:

```
/node_modules/j/node_modules/xlsx/xlsx.js:4996
        opts.revssf = evert_num(wb.SSF); opts.revssf[wb.SSF[65535]] = 0;
                                                                    ^
TypeError: Cannot set property 'General' of undefined
```

As a side note, I'm not sure why I have to manually create a workbook class while it could/should be provided by the module itself.

While working on node-xlsx, had an API like:

``` js
var data = [[1,2,3],[true, false, null, 'sheetjs'],['foo','bar',new Date('2014-02-19T14:30Z'), '0.3'], ['baz', 
var buffer = xlsx.build({worksheets: [{"name":"mySheetName", "data": data});
```

Kinda miss it!

**Comment by willyelm** [comment]
according the documentation as you are passing a file path to write the file you should be using: `XLSX.writeFile(wb, '/tmp/out.xlsx')`
to generate a file without writing it:
`XLSX.write(wb, {bookType:'xlsx', bookSST:false, type: 'binary'})`

**Comment by SheetJSDev** [comment]
We are maintaining a [kitchen-sink write script](https://raw.githubusercontent.com/SheetJS/js-xlsx/master/tests/write.js) and slowly adding examples to the README.  We are also using [gitbook](https://sheetjs.gitbooks.io/docs/#xlsx) for a better rendering of the README.

Please take a skim of the README and let us know if it makes enough sense to produce a minimal write example.  If not, let us know how we can improve the documentation
