### ISSUE TITLE
Issue with book_append_sheet method

### ISSUE THREAD

**Issue by reachmehere89** [SheetJS/js-xlsx#1290]
When I call book_append_sheet method with 2 arguments : workbook and worksheet and don't provide sheet name it adds Sheet1 as default sheet name. This is fine because no sheet name was given.

But when I add wb.SheetNames = ["mysheet"], it adds mysheet as well as Sheet1.

**Comment by SheetJSDev** [comment]
`book_append_sheet` does exactly two things: add the worksheet to the `wb.Sheets` object and add the name of the worksheet (defaulting to `Sheet###` like Excel) to the `wb.SheetNames` array.  If you add an extraneous name that doesn't have a corresponding worksheet, the writer generates a blank worksheet.
