### ISSUE TITLE
ERROR: "r.forEach is not a function" on json_to_sheet call

### ISSUE THREAD

**Issue by sonjadeissenboeck** [SheetJS/js-xlsx#1291]
I'd like to export a SAPui5 xml table like this:

```
onDataExportXLS: function() {
if (!this._oTable) {
	this._oTable = this.byId("testdata3");
	}
        oTable = this._oTable;
	oRowBinding = oTable.getBinding("items");
        var oModel = oRowBinding.getModel(); 
	 var ws_data = oModel.getJSON();
	 var ws = XLSX.utils.json_to_sheet(ws_data);
        XLSX.writeFile(ws, "export.xlsx");
}
```
However, whenever I try to export a table, it stops at the line "var ws = XLSX.utils..." and throws the error message I mentioned above. I debugged my code and the ws_data looks like a fine JSON object, so I don't know what I'm doing wrong.
Please advise me with any mistakes I did. (I already read other questions about this but they were different)!

**Comment by colleenDunlap** [comment]
Did you figure this out?? I'm having the same problem
