### ISSUE TITLE
While I export the date cell, I am getting the one day back instead of actual

### ISSUE THREAD

**Issue by phani17c** [SheetJS/js-xlsx#1293]
Ex: sheet[address] = {t: "d", v: 1537833600000 , z: "[locale]d-mm-yyyy;@"}

And the cell in the excel has 24 Sep 2018 instead of 25 Sep 2018
![image](https://user-images.githubusercontent.com/22199164/46105986-803c4c00-c1a5-11e8-8188-9cc6fe8aeedb.png)

**Comment by phani17c** [comment]
Never mind! This issue got resolved. But I would like to point out this bug

new Date(Date.parse('09/25/2108'))
Tue Sep 25 2018 00:00:00 GMT-0400 (Eastern Daylight Time)
WHILE
new Date(Date.parse('09-25-2108'))
Mon Sep 24 2018 20:00:00 GMT-0400 (Eastern Daylight Time)

This was the error. So I did change the format to mm/dd/yyyy instead of mm-dd-yyyy

**Comment by timratha** [comment]
@phani17c Can I know how did you fix your issue?
