### ISSUE TITLE
Doesn't work in iPad

### ISSUE THREAD

**Issue by GuofuHuang** [SheetJS/js-xlsx#1297]
It works in browsers in computers but doesn't work in the iPads, will you fix this in the future?

**Comment by SheetJSDev** [comment]
This is a known issue with iOS safari, outside of the control of JS libraries as a whole.  Unfortunately the browser has to provide a mechanism to trigger a download, and none of [the known techniques](https://github.com/SheetJS/js-xlsx/blob/master/bits/19_fsutils.js#L10) work consistently on iOS.
