### ISSUE TITLE
ge is not a constructor

### ISSUE THREAD

**Issue by ZSH-HSZ** [SheetJS/js-xlsx#1302]
There is no problem when NPM is used without CDN, but after CDN is used the export will report an error, ge is not a constructor

**Comment by tangdw** [comment]
浏览器里需要使用完整版本：xlsx.full.min.js 而不是 xlsx.min.js

**Comment by SheetJSDev** [comment]
@ZSH-HSZ what CDN?  can you reproduce using a service like jsfiddle?
