### ISSUE TITLE
import excel contain chinese

### ISSUE THREAD

**Issue by heheda11** [SheetJS/js-xlsx#1303]
I want to import excel contain chinese, like this
![image](https://user-images.githubusercontent.com/25971029/46600677-83c4c100-cb1d-11e8-88f1-c3817aba2026.png)

Is there any function to change the chinese into english? when I used this method: XLSX.utils.sheet_to_json(workbook.Sheets[sheet])

**Comment by SheetJSDev** [comment]
If you are asking whether there is a way to translate the values in the worksheet to English, you would have to do it manually.  Before calling `sheet_to_json`, you can manually edit the column names as follows:

```js
delete ws["A1"].w;
ws["A1"].v = "column A"; // change to whatever column label you want to use
```
