### ISSUE TITLE
How to get first rows of particular range in each sheet?

### ISSUE THREAD

**Issue by sanjaya** [SheetJS/js-xlsx#1307]
I want to get only rows from, let say 10 to 20. How can I do this?

**Comment by SheetJSDev** [comment]
`read` and `readFile` have a [`sheetRows` option](https://github.com/SheetJS/js-xlsx#parsing-options) controlling the total number of rows.  You can grab the first 20 for processing.  If you're using something like `sheet_to_json` to convert the data to an array, you can slice that resulting array (`arr.slice(-10)`) to pull the bottom 10 rows.
