### ISSUE TITLE
Single Column issues

### ISSUE THREAD

**Issue by vdurante** [SheetJS/js-xlsx#1309]
I am trying to write an Excel file, but sometimes the data will contain a single column. In such scenarios, how should I proceed?
```js
let data = "Corridas Realizadas\r\n21239\r\n";
var wb = XLSX.read(result.data, { type: "string" });
XLSX.writeFile(wb, "test.xlsx");
```

The code above yields the following result:

![image](https://user-images.githubusercontent.com/5401232/47050070-8191e080-d175-11e8-8d43-7f3ff88ae463.png)

I have tried adding a `sep=,` to the beginning of the text, but didn't work.

Thanks in advance.

**Comment by SheetJSDev** [comment]
Thanks for reporting!

The overarching problem is that without a delimiter, the default is to interpret as lotus formatted text.  See https://docs.sheetjs.com/#guessing-file-type for an explanation of how plaintext formats are deduced.  Clearly that needs to be revisited.

The separator check is specifically looking for "\n" (char code 10) in the sixth character, which is clearly incorrect.  After https://github.com/SheetJS/js-xlsx/blob/master/bits/40_harb.js#L774 there should be something like:

```js
else if(str.slice(0,4) == "sep=" && str.charCodeAt(5) == 13 && str.charCodeAt(6) == 10) { sep = str.charAt(4); str = str.slice(7); }
```

To disable the PRN parsing entirely, https://github.com/SheetJS/js-xlsx/blob/master/bits/40_harb.js#L848 should be changed to call `dsv_to_sheet_str`

**Comment by vdurante** [comment]
Thank you! I have added `data = data.split('\r\n').join(',\n');` as an intermediate step and it worked!
