### ISSUE TITLE
dateNF seems to be ignored

### ISSUE THREAD

**Issue by sonjadeissenboeck** [SheetJS/js-xlsx#1317]
I read about the exact same issue and tried to adapt the solution found there, but I still can't upload my dates in the correct format. the default format is constantly applied and the format I sat seems to be ignored. 

> getRowData: function(worksheet) {
>             var data = XLSX.utils.sheet_to_json(worksheet, {dateNF: 'dd"."mm"."yy', raw: false}); --> here's my issue!
>             return data;
> },

when I read my workbook, it looks like this:
`var wb = XLSX.read(data, {type: 'binary', cellDates: true,cellText:false,cellNF: true});` --> I tried to add a locale property but that didn't help either.

My output still looks like this:
![image](https://user-images.githubusercontent.com/30501609/47201653-ecf8cf80-d37a-11e8-84e8-3b2b04acdf55.png)

Any help is appreciated!

**Comment by AiswariyaP** [comment]
Is this issue resolved? I am also facing the same problem
