### ISSUE TITLE
Uncaught TypeError: Cannot set property 'hidden' of undefined

### ISSUE THREAD

**Issue by huangchuxian** [SheetJS/js-xlsx#1326]
### error msg:
`
Uncaught TypeError: Cannot set property 'hidden' of undefined
    at Object.click (contextMenu.js:450)
    at HTMLDivElement.<anonymous> (contextMenu.js:108)
`
### step:
1. open url:  

> https://oss.sheetjs.com/
2. input a excel file
3. then click  table's left side 

> Hide RowHeaderCell
4. error code part:
`
t.cell && t.cell.header && t.items.push({
         title: e.attributes.hideColumnText.replace(/%s/gi, t.cell.header.title || t.cell.header.name),
                 click: function (o) {
                              e.getSchema()[t.cell.columnIndex].hidden = !0,
                                   o.preventDefault(),
                                        e.stopPropagation(o),
                                         e.disposeContextMenu(),
                                            e.setStorageData(),
                                             setTimeout(function () {
                                                 e.resize(!0)
                                     },
                               10)
      }
`

**Comment by huangchuxian** [comment]
![qq 20181025115632](https://user-images.githubusercontent.com/9958489/47475217-2b93fb80-d84d-11e8-9536-d4ca6b2a533e.png)
![qq 20181025115717](https://user-images.githubusercontent.com/9958489/47475222-30f14600-d84d-11e8-8015-4e1f0ac247c0.png)

**Comment by SheetJSDev** [comment]
This seems to be an issue with the data grid component used.  https://github.com/TonyGermaneri/canvas-datagrid/issues/176 is the issue to follow.

**Comment by huangchuxian** [comment]
> This seems to be an issue with the data grid component used. [TonyGermaneri/canvas-datagrid#176](https://github.com/TonyGermaneri/canvas-datagrid/issues/176) is the issue to follow.

thanks
