### ISSUE TITLE
XLSX.writeFile creates empty xlsx file

### ISSUE THREAD

**Issue by sonjadeissenboeck** [SheetJS/js-xlsx#1327]
My exported excel file is empty even though there's data in my function.
```
		onDataExportXLS: function(oEvent) {
			var oTable = oEvent.getSource().getParent();
			var oModel = oTable.getModel(); 
			var ws_data = oModel.getData().rows;
			if(typeof XLSX == 'undefined') XLSX = require('xlsx');
			var ws = XLSX.utils.json_to_sheet(ws_data);
			var wb = XLSX.utils.book_new();
			XLSX.utils.book_append_sheet(wb, ws_data, "Table Export2");
			XLSX.writeFile(wb, "export.xlsx");
		},
```
I looked at "wb" in my last line and all the table data is in there. Export.xlsx gets created and downloaded but it is completely empty.. Even though wb contains a cell range with the table data..

Please help!

**Comment by SheetJSDev** [comment]
@sonjadeissenboeck if this is coming from the browser, can you check the error console?  Alternatively, before calling writeFile, try converting the worksheet to csv and logging the contents:

```js
console.log(XLSX.utils.sheet_to_csv(ws));
```

**Comment by sonjadeissenboeck** [comment]
There is no error, that's the weirdest thing about it. The file gets downloaded but when opening, it's empty..

Just for comprehension: why a sheet_to_csv conversion?

**Comment by sonjadeissenboeck** [comment]
ok, so logging "console.log(XLSX.utils.sheet_to_csv(ws));" gives me a correct output of all the table data..

**Comment by SheetJSDev** [comment]
There may be an error in your code:

```js
			XLSX.utils.book_append_sheet(wb, ws_data, "Table Export2");
```

That should be

```js
			XLSX.utils.book_append_sheet(wb, ws, "Table Export2");
```

**Comment by sonjadeissenboeck** [comment]
thanks, did the trick!
