### ISSUE TITLE
sheet_to_csv: field containing line breaks(CRLF) are not quote escaped 

### ISSUE THREAD

**Issue by shusson** [SheetJS/js-xlsx#1330]
It doesn't look like `js-xlsx.utils.sheet_to_csv` is currently quote escaping strings that contain CRLFs. 

Based on https://tools.ietf.org/html/rfc4180 2.6

> Fields containing line breaks (CRLF), double quotes, and commas
should be enclosed in double-quotes.

e.g I would expect the field 

`I\nLove\nLamp` 

to be transformed to 

`"I\nLove\nLamp"`

**Comment by reviewher** [comment]
It seems to be doing that just fine.  Here's a test using `aoa_to_sheet` to generate the worksheet:

```js
var ws = XLSX.utils.aoa_to_sheet([["a\nb\nc\n", "d\ne\nf\n"], ["g\nh\ni\n", "j\nk\nl\n"]]);
console.log(XLSX.utils.sheet_to_csv(ws))
```

Here's a test reading from a CSV:

```js
var ws = XLSX.read('"a\nb\nc\n","d\ne\nf\n"\n"g\nh\ni\n","j\nk\nl\n"', {type: "binary"}).Sheets.Sheet1;
console.log(XLSX.utils.sheet_to_csv(ws))
```

This also works with CRLF:

```js
var ws = XLSX.read('"a\nb\nc\n","d\ne\nf\n"\n"g\nh\ni\n","j\nk\nl\n"'.replace(/\n/g, "\r\n"), {type: "binary"}).Sheets.Sheet1;
console.log(XLSX.utils.sheet_to_csv(ws))
```

http://jsfiddle.net/dy1orkn4/ is the same set of examples in JSFiddle.  Confirm you are using the latest version (currently 0.14.0).  If you can find a reproducible issue against the latest version, please reopen this issue.

**Comment by shusson** [comment]
@reviewher Please see [http://jsfiddle.net/5xzo6vrL](http://jsfiddle.net/5xzo6vrL). It happens if the RS(Record Separator) option is set to anything besides `\n`.

And sorry I didn't add an example from the beginning.

**Comment by reviewher** [comment]
Excel doesn't follow RFC4180, and the library tries to mimic Excel's behavior rather than the spec when they disagree.  For example, there's a special carveout for the Excel `sep=` metadata

`RS` record separator and `FS` field separator (nomenclature follows AWK) are not actually supported in the RFC4180!

```
   1.  Each record is located on a separate line, delimited by a line
       break (CRLF).  For example:

       aaa,bbb,ccc CRLF
       zzz,yyy,xxx CRLF

...

   4.  Within the header and each record, there may be one or more
       fields, separated by commas.  Each line should contain the same
       number of fields throughout the file.  Spaces are considered part
       of a field and should not be ignored.  The last field in the
       record must not be followed by a comma.  For example:

       aaa,bbb,ccc
```

It is useful to change the row as well as the field delimiter in practice.

The part you referenced is:

```
   6.  Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.  For example:

       "aaa","b CRLF
       bb","ccc" CRLF
       zzz,yyy,xxx
```

Excel extrapolates as follows:

```
       Fields containing the row separator character, double quotes, or
       field separator character should be enclosed in double-quotes.
```

and this is the current behavior.

**Comment by shusson** [comment]
yeah ok, we can work around this by converting all our fields to use the same line breaks as our row separator or just remove line breaks from our fields. Thanks for your help @reviewher.

**Comment by Xiaomaixiangseng** [comment]
aaaaa↵bbbbb 
sheet_to_csv之后
aaaaa
bbbb
怎样结果是 aaaaabbbbb
