### ISSUE TITLE
A way to specify date formating when using XLSX.utils.sheet_to_row_object_array()

### ISSUE THREAD

**Issue by rotemtam** [SheetJS/js-xlsx#134]
Hi

Is there a way to specify date formatting to "dd/mm/yyyy" when converting a sheet to object array?

Currently function returns "mm/dd/yyyy" seems like this is hardcoded into SSF somewhere as a default.

**Comment by SheetJSDev** [comment]
Note: these changes are in the repo and will appear in version 0.9.5.

If you read in with `cellDates:true`, the date-stored-as-number cells will be proper dates.  

If you set the `dateNF` key of the options object to a number format string, the formatter will use it. Following the example from [my previous comment](https://github.com/SheetJS/js-xlsx/issues/134#issuecomment-58664998):

```js
> var wb = XLSX.readFile('write.xlsx', {cellDates:true});
> wb.Sheets.SheetJS.C3
{ t: 'd', v: 2014-02-19T14:30:00.000Z, w: '2/19/14' } // <-- note: v is a date object
> delete wb.Sheets.SheetJS.C3.w
true
> XLSX.utils.format_cell(wb.Sheets.SheetJS.C3);
'2/19/14' <-- defaults to the number format code 14
> delete wb.Sheets.SheetJS.C3.w
true
> XLSX.utils.format_cell(wb.Sheets.SheetJS.C3, null, {dateNF:"YYYY-MM-DD"});
'2014-02-19' <-- uses the override
```

**Comment by EvanCarroll** [comment]
Where is the arguments to `format_cell` even documented? I just see it mentioned in the docs.
