### ISSUE TITLE
hard to get started

### ISSUE THREAD

**Issue by son1cman** [SheetJS/js-xlsx#1349]
im having a lot of errors since im implemeting from 0
Theres no simple code to copy/paste and get started

**Comment by Lebed71** [comment]
https://docs.sheetjs.com/#parsing-workbooks

Enjoy! :)

**Comment by SheetJSDev** [comment]
There are a bunch of examples in the README as well as linked demos in specific use cases.  https://github.com/SheetJS/js-xlsx/tree/master/demos/ has some examples for inspiration.
