### ISSUE TITLE
Cell names in formulas get lowercased

### ISSUE THREAD

**Issue by dandv** [SheetJS/js-xlsx#1361]
```js
const XLSX = require('xlsx');

const wb = XLSX.utils.book_new();

// couldn't figure out how to simply create a row; wb[Sheets[wb.SheetNames[0]] has no rows
const ws = XLSX.utils.json_to_sheet([
  { dummy: '' },
]);

XLSX.utils.book_append_sheet(wb, ws, 'Bug sheet');

ws.A1 = { t: 'n', f: 'formula_ABC' };  // BUG? gets written as formula_abc

XLSX.writeFile(wb, 'bug.ods');
```

Is it expected behavior for cell names to be normalized to lowercase?

My use case is that I'm generating new sheets that I paste manually into to a master sheet that has certain cell names containing uppercase characters (.e.g. `expenses_USD`).

**Comment by reviewher** [comment]
It is written as uppercase.  See http://jsfiddle.net/fvembtrz/1/ for an example.

PS: there are two ways to write a single row: [pass the option `skipHeader` to `json_to_sheet`](https://docs.sheetjs.com/#array-of-objects-input) or [pass an array of arrays to `aoa_to_sheet`](https://docs.sheetjs.com/#array-of-arrays-input)

**Comment by dandv** [comment]
I see it as lowercase in LibreCalc 5.4:

![image](https://user-images.githubusercontent.com/33569/48666621-56ebbe00-ea7a-11e8-87a3-aa1cab5e0e50.png)

**Comment by reviewher** [comment]
The file generates the name in uppercase:

![file](https://user-images.githubusercontent.com/24845478/48666867-f4091f80-ea97-11e8-858f-38fe43b25b49.png)

Excel 2019 displays it as uppercase:

![xl](https://user-images.githubusercontent.com/24845478/48666882-41858c80-ea98-11e8-9364-336fd202d181.png)

However, LibreOffice seems to be automatically renaming everything to lowercase.  To verify, open the file and try setting the value to `=formula_ABC` manually, it is automatically converted to lowercase.

This stackoverflow comment suggests that is known behavior: https://superuser.com/a/1231904

>  When entering a formula, Calc changes any unrecognized references to lower case. This happens for both sheet and variable-name references.
