### ISSUE TITLE
Embedded images

### ISSUE THREAD

**Issue by SheetJSDev** [SheetJS/js-xlsx#137]
h/t @samoberes on Twitter: https://twitter.com/SamOberes/status/524023213106274304

**Comment by oising** [comment]
Seconded.

**Comment by mikehedman** [comment]
I also have a requirement to get images out of the sheets.  Thanks.

**Comment by aaronmccall** [comment]
This is a high priority feature for me, as well.

**Comment by maertz** [comment]
Another guy which would like to see that :)

**Comment by tcs-apeters** [comment]
Me too. We would like to avoid to switch.

**Comment by morficus** [comment]
+1 for being able to embed images

**Comment by tnrich** [comment]
+1

**Comment by KarstenKlein79** [comment]
+1

**Comment by Mithgol** [comment]
+1

**Comment by cranesandcaff** [comment]
Files are stored if you set the file option to true, they're stored as JSZip ZipObjects.

I'm looking into unzipping them in the browser but so far no luck.

**Comment by oising** [comment]
I unzip/extract and even update images in xlsx files in the browser using the JSZip library. It's definitely possible.

**Comment by cranesandcaff** [comment]
In the browser I had a JSZip ZipObject, but it didn't seem to have the inherited methods, when I tried instantiating it as a new `ZipObject` with the constructor it threw an error. I kind of dismissed it because it's of low importance right now, would you mind show a small code example of getting an image out of an xlsx file?

**Comment by congyuandong** [comment]
+1

**Comment by Setup007** [comment]
+1

**Comment by reviewher** [comment]
Related: https://github.com/SheetJS/js-xls/issues/90 @parthivpn

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
