### ISSUE TITLE
XLSX.utils.json_to_sheet doesn't work with huge json (200 000 rows to xls)

### ISSUE THREAD

**Issue by amidf** [SheetJS/js-xlsx#1373]
For example, I have an array of 200 000 js objects and when I'm using `XLSX.utils.json_to_sheet` I get a file where only 10-20 items from my original array. This problem happens only with `.xls` format. Converting works correctly with `.xlsx`. I don't know is there may be a limitation on a number of rows?

**Comment by GreggOD** [comment]
Are you doing this browser or server side?

**Comment by amidf** [comment]
I do it in a service worker so it's a browser.

**Comment by amidf** [comment]
Hmmm, it's sad news. Anyway, thanks a lot for your answer. I close the issue.
