### ISSUE TITLE
Is there any method to limit the cell content

### ISSUE THREAD

**Issue by QAQMiao** [SheetJS/js-xlsx#1376]
I'm using js-xlsx to write a excel

```
    const sheet = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, sheet, 'staffInfo');

    const wbbuf = XLSX.write(wb, {
      type: 'base64'
    });
```

I want to a column of cells content can be limited like picture. Which api can do this? QwQ
![image](https://user-images.githubusercontent.com/8213657/49433833-d05f0c80-f7ed-11e8-9fb2-0d5e12128850.png)

**Comment by SheetJSDev** [comment]
The feature you are describing is called "Data Validations", an advanced feature included in our [Pro version](https://sheetjs.com/pro)
