### ISSUE TITLE
Can't write cells.

### ISSUE THREAD

**Issue by mateo2181** [SheetJS/js-xlsx#1378]
Hello!
I am working with js-xlsx in Express and consume this API from Vuejs. 
I am trying to create and xlsx file but always get an object in the first cell.
This is my method in Express:
![selection_001](https://user-images.githubusercontent.com/12451246/49669692-e44e7c80-fa40-11e8-8633-582934f4e046.png)

and my code in Vuejs:
![selection_002](https://user-images.githubusercontent.com/12451246/49669712-f4fef280-fa40-11e8-9043-e6b6bdc465ad.png)

My excel file:
 
![selection_003](https://user-images.githubusercontent.com/12451246/49669793-2c6d9f00-fa41-11e8-9eb8-5c5905e1912e.png)

Someone have the same problem? 

Thanks!

**Comment by reviewher** [comment]
remove the `wb.SheetNames.push` line -- `book_append_sheet` does that part for you already.

**Comment by mateo2181** [comment]
I tried but not works. This line XLSX.utils.book_append_sheet(wb, ws_data, "People"); is neccesary to add the data.

**Comment by SheetJSDev** [comment]
Cannot reproduce, here is a JSFiddle: http://jsfiddle.net/7ung60jd/ 

One possibility for further exploration: do the write with type `buffer` to generate a NodeJS buffer -- express might be doing something else behind the scenes
