### ISSUE TITLE
sheet_to_json skips empty rows

### ISSUE THREAD

**Issue by tamlyn** [SheetJS/js-xlsx#139]
When calling `xlsx.utils.sheet_to_json(sheet, {header: 1})` I would expect to receive an array of arrays _including_ empty rows. However the function explicitly skips out empty rows which makes it impossible to select a particular row in the results. It would be good to make this behaviour configurable.

As a workaround, I have used `sheet_to_csv`, which doesn't skip rows, followed by [csv-parse](https://github.com/wdavidw/node-csv-parse).

**Comment by jeffgunderson** [comment]
Also experiencing the same issue as Kevzz. Any updates?

**Comment by rdmurphy** [comment]
Can also confirm I'm having this issue. Empty cells in `xlsx` files don't convert properly.

**Comment by marcioaguiar** [comment]
Same issue here

**Comment by simonbergstrom** [comment]
eagerly awaiting on an update here :)

**Comment by shenlong** [comment]
+1

require support for empty cell.

**Comment by Extano** [comment]
Hmmm, too bad, thought this would save my day :(
But the empty cells bug is still even in 0.8.0
The only way so convert also empty cells, is to save the xlsx table as xls. 
Unfortunatley not an option for me since this destroys my table.

**Comment by shenlong** [comment]
Yeah. For me, I go thru the each row and each header to check for undefined values and put '' for empty field.

```javascript
 workbook.SheetNames.forEach(function (sheetName) {
                // Get headers.
                var headers = [];
                var sheet = workbook.Sheets[sheetName];
                var range = XLSX.utils.decode_range(sheet['!ref']);
                var C, R = range.s.r;
                /* start in the first row */
                /* walk every column in the range */
                for (C = range.s.c; C <= range.e.c; ++C) {
                    var cell = sheet[XLSX.utils.encode_cell({c: C, r: R})];
                    /* find the cell in the first row */

                    var hdr = "UNKNOWN " + C; // <-- replace with your desired default
                    if (cell && cell.t) {
                        hdr = XLSX.utils.format_cell(cell);
                    }
                    headers.push(hdr);
                }
                // For each sheets, convert to json.
                var roa = X.utils.sheet_to_json(workbook.Sheets[sheetName]);
                if (roa.length > 0) {
                    roa.forEach(function (row) {
                        // Set empty cell to ''.
                        headers.forEach(function (hd) {
                            if (row[hd] == undefined) {
                                row[hd] = '';
                            }
                        });
                    });
                }
            });
```

**Comment by codeofsumit** [comment]
+1 the key should be included in the json objects with an empty string or `null`

**Comment by abartolo** [comment]
@SheetJSDev Hi, any update when this will be fixed? I am still seeing this issue.

BTW great library!

**Comment by mjza** [comment]
@abartolo Go to xlsx.js file, find `sheet_to_json` function and change it like as this:

`function sheet_to_json(sheet, opts){
	var val, row, range, header = 0, offset = 1, r, hdr = [], isempty, R, C, v;
	var o = opts != null ? opts : {};
	var raw = o.raw;
	if(sheet == null || sheet["!ref"] == null) return [];
	range = o.range !== undefined ? o.range : sheet["!ref"];
	if(o.header === 1) header = 1;
	else if(o.header === "A") header = 2;
	else if(Array.isArray(o.header)) header = 3;
	switch(typeof range) {
		case 'string': r = safe_decode_range(range); break;
		case 'number': r = safe_decode_range(sheet["!ref"]); r.s.r = range; break;
		default: r = range;
	}
	if(header > 0) offset = 0;
	var rr = encode_row(r.s.r);
	var cols = new Array(r.e.c-r.s.c+1);
	var out = new Array(r.e.r-r.s.r-offset+1);
	var outi = 0;
	for(C = r.s.c; C <= r.e.c; ++C) {
		cols[C] = encode_col(C);
		val = sheet[cols[C] + rr];
		switch(header) {
			case 1: hdr[C] = C; break;
			case 2: hdr[C] = cols[C]; break;
			case 3: hdr[C] = o.header[C - r.s.c]; break;
			default:
				if(val === undefined) continue;
				hdr[C] = format_cell(val);
		}
	}

	for (R = r.s.r + offset; R <= r.e.r; ++R) {
		rr = encode_row(R);
		isempty = true;
		if(header === 1) row = [];
		else {
			row = {};
			if(Object.defineProperty) Object.defineProperty(row, '__rowNum__', {value:R, enumerable:false});
			else row.__rowNum__ = R;
		}
		for (C = r.s.c; C <= r.e.c; ++C) {
			val = sheet[cols[C] + rr];
			if(val === undefined || val.t === undefined) {val = {t: "s", v: null, w: ""};}
			v = val.v;
			switch(val.t){
				case 'e': continue;
				case 's': break;
				case 'b': case 'n': break;
				default: throw 'unrecognized type ' + val.t;
			}
			if(v !== undefined) {
				row[hdr[C]] = raw ? v : format_cell(val,v);
				isempty = false;
			}
		}
		if(isempty === false || header === 1) out[outi++] = row;
		
	}
	out.length = outi;
	return out;
}`

**Comment by muscaiu** [comment]
@mjza that has no change for me. Still the empty fields are inexistant and imposible to detect.

**Comment by VectorM** [comment]
+1

**Comment by jiangtiteng** [comment]
@mjza  Thanks , It is work

**Comment by rashthedude** [comment]
Any updates on this matter?

**Comment by SheetJSDev** [comment]
I think this was resolved a long time ago, in version 0.8.0 the fix from https://github.com/SheetJS/js-xlsx/issues/139#issuecomment-60823125 was applied.  I just tested a file and see blank arrays generated when the option `{header:1}` is set.

As far as I can tell the crux of the matter (including empty rows) has been resolved.  If anyone can share a sample file with expected output I'll reopen the issue.

**Comment by vins13pattar** [comment]
sheet_to_json() with header option true yields empty column headers perfectly, But there is a bug and it won't echo null for last empty column data.  In attached screenshot, there are 11 header items. 2nd column is empty and it's coming null as expected. But it's not echoing null for 11th column which is last one.

![image](https://cloud.githubusercontent.com/assets/333259/24287386/7e416772-109f-11e7-97b8-fa64ed6848d5.png)

**Comment by SheetJSDev** [comment]
@vins13pattar do you have a file you can share? It should not be generating null in the first place -- those should be array holes (undefined)

I made a sample file to check what's going on: [t139.xlsx](https://github.com/SheetJS/js-xlsx/files/867886/t139.xlsx)

And this is what I see in node:

```js
> XLSX.version
'0.9.5'
> XLSX.utils.sheet_to_json(XLSX.readFile('t139.xlsx').Sheets.Sheet1, {header:1})
[ [ 'id',
    'id-job',
    'type',
    'name',
    'address',
    'latitude',
    'longitude',
    'service-duration',
    'start-time',
    'end-time',
    'quantity',
    'required-skills' ],
  [ 'Stop1', , , , , , , , , , '206' ] ]
```

**Comment by vins13pattar** [comment]
@SheetJSDev Thank you for the reply.
In the test file [t139](https://github.com/SheetJS/js-xlsx/files/867886/t139.xlsx) 'required-skills' is empty and it is generate data as

`  [ 'Stop1', , , , , , , , , , '206' ] `

Array holes is ok. But how do represent array hole after last column?
Like this?

`  [ 'Stop1', , , , , , , , , , '206', ] `

I faced this issue because I was parsing content without any header columns.
Anyway, I made it working. Thank you for the awesome package!!

**Comment by JOELJOSEPHCHALAKUDY** [comment]
I had a similar issue but was able to solve it like this by removing empty object in from an array , hope this helps someone.  Not an ideal solution but gets the job done

  ```
// code for the new excel reader
        $scope.do_file =  function(files)
        {
          $scope.fileContent  = [];
          var X = XLSX;
          var global_wb;
          var f = files[0];
          var reader = new FileReader();
          reader.onload = function(e)
          {
            var data = e.target.result;console.log(data);
            global_wb = X.read(data, {type: 'array'});
            var output = "";
            var result = {};
            global_wb.SheetNames.forEach(function(sheetName) {
              var roa = X.utils.sheet_to_json(global_wb.Sheets[sheetName], {header:1});
              if(roa.length) result[sheetName] = roa;
            });
          
            $scope.fileContent =  result["Sheet1"];
            if(!result["Sheet1"])
            {
               // If ES6  code 
              //$scope.fileContent =  result["contacts"].filter(value => Object.keys(value).length !== 0);   

              // If  ES5  code 
              $scope.fileContent =  result["contacts"].filter(function(el) { return typeof el != "object" || Array.isArray(el) || Object.keys(el).length > 0; });
            }

          
          };
          reader.readAsArrayBuffer(f);
        };
```

**Comment by EDUARDOMBRAGA** [comment]
I still have the problem today, I'm using version 0.12.13 and I still can not upload files that have null values ​​.. what's the solution? I already configured it as header: 1 also did not work.

**Comment by SheetJSDev** [comment]
Are you by any chance roundtripping through JSON by stringifying in one place and parsing elsewhere?  That would plug `null` into the array holes:

```js
> var arr = [1,,,,,2]
undefined
> arr
[ 1, <4 empty items>, 2 ]
> JSON.stringify(arr)
'[1,null,null,null,null,2]'
> JSON.parse(JSON.stringify(arr))
[ 1, null, null, null, null, 2 ]
```

**Comment by EDUARDOMBRAGA** [comment]
When I implement this code in my component.ts the worksheet contains null values ​​plus the sheet_to_json ignores the null values ​​and strips the entire column being able to set null and continue. Here's the snippet of my code, I'm using the most recent version of xlsx 0.12.13, it also follows a sample xlsx file I'm importing.



    var data = evt.target.files[0];
    const target: DataTransfer = <DataTransfer>(evt.target);
    if (target.files.length !== 1) throw new Error("Cannot use multiple files");
    const reader: FileReader = new FileReader();

    reader.onload = (e: any) => {

      /* read workbook */
      const bstr: string = e.target.result;
      const wb: XLSX.WorkBook = XLSX.read(bstr, {type: 'binary'});
      
      /* grab first sheet */
      const wsname: string = wb.SheetNames[0];
      const ws: XLSX.WorkSheet = wb.Sheets[wsname];
      
      /* data = meu array de objetos */
      data = <AOA>(XLSX.utils.sheet_to_json(ws, {header:1, raw: true})); // raw: true
 }  
reader.readAsBinaryString(target.files[0]);

file = [https://drive.google.com/file/d/1b9ql8LCHiDwRYNLyt_BjkCh9w908TbUT/view?usp=sharing](url)

**Comment by SheetJSDev** [comment]
@EDUARDOMBRAGA unable to download that file (you have to enable sharing).  Can you test with the [`t139.xlsx` file linked in a previous comment](https://github.com/SheetJS/js-xlsx/files/867886/t139.xlsx)

**Comment by EDUARDOMBRAGA** [comment]
@SheetJSDev  See if you can see now [https://drive.google.com/file/d/1b9ql8LCHiDwRYNLyt_BjkCh9w908TbUT/view?usp=sharing](url)

**Comment by SheetJSDev** [comment]
To test in the web browser, go to https://oss.sheetjs.com/js-xlsx/ and drag-drop the `Layout.xlsx` file into the box.  Once you see CSV content in the page, open up your browser console.  The loaded workbook object is stored in the `global_wb` variable which you can access.  Running `XLSX.utils.sheet_to_json(global_wb.Sheets.Plan1, {header:1, raw:true})[2]` in chrome console shows two array holes (not null):

<img width="512" alt="" src="https://user-images.githubusercontent.com/6070939/40325453-c600fca0-5d09-11e8-8c0e-0cb85db4d6a5.png">

The original worksheet had 13 columns, consistent with the actual data reported in chrome

**Comment by ryankall** [comment]
@EDUARDOMBRAGA @SheetJSDev 

I am using angular 6 and it will work on angular 5...
`package.json  "xlsx": "^0.12.13"`
in File
`import * as XLSX from 'xlsx';`

This will work on xlsx, Only one I used it on. 
`XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], {header: 1, defval: null});`

defval does the magic here, 'null' is what I want in place
if I wanted empty string in place of empty cell 
`XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], {header: 1, defval: ''});`

defval can be any value you set.

**Comment by EDUARDOMBRAGA** [comment]
@ryankall 

Uall, worked as I expected. Thank you very much for the help. 👍

**Comment by EDUARDOMBRAGA** [comment]
@ryankall Hello!

When I have null fields plus the same ones are of type string I can write as null and those that are of type binary send another value if it is null?

**Comment by clarkmu** [comment]
It's the defval param that fixed it for me:
var roa = XLS.utils.sheet_to_row_object_array(workbook.Sheets[sheetName], {defval: ''})

**Comment by aslam7** [comment]
Hi there,
We can achieve empty rows by doing in this way.

try this once.

const xlsx = require('xlsx');
const csvjson = require('json');

const workbook = xlsx.read(file.buffer, { type: 'buffer' });
const csvdata = xlsx.utils.sheet_to_csv(workbook.Sheets[workbook.SheetName[0]]);
const data = csvjson.toObject(csvdata);

**Comment by Nahuelgrc** [comment]
In my case I needed the header of a xlsx which could have empty rows above it.
What I needed to set was set the following values:
`const jsonSheet = XLSX.utils.sheet_to_json(ws, { header: 1, range: 0, defval: ""});`

The attribute **range: 0** is the essential thing. 
As I said, this was my case.

**Comment by SantoshKumar4547** [comment]
thanks, Nahuelgrc :) 👍

**Comment by dork1** [comment]
Setting {sheetStubs: true} allowed me to access all the json objects including the ones with empty values, without adding it my array would just end at the first empty element but at least now it just skips the empty cells and continues with the rest of the array. I need to update an 'empty' element now so I need to be able to fetch the empty cell 'values'. Another important part so far was using the !null in my filter function as referenced here github.com/SheetJS/js-xlsx/issues/139#issuecomment-390754486. My array is still returning with no values for the elements after the empty value. Hope that helps someone.

**Comment by MoH-AnA** [comment]
> Yeah. For me, I go thru the each row and each header to check for undefined values and put '' for empty field.
> 
> ```js
>  workbook.SheetNames.forEach(function (sheetName) {
>                 // Get headers.
>                 var headers = [];
>                 var sheet = workbook.Sheets[sheetName];
>                 var range = XLSX.utils.decode_range(sheet['!ref']);
>                 var C, R = range.s.r;
>                 /* start in the first row */
>                 /* walk every column in the range */
>                 for (C = range.s.c; C <= range.e.c; ++C) {
>                     var cell = sheet[XLSX.utils.encode_cell({c: C, r: R})];
>                     /* find the cell in the first row */
> 
>                     var hdr = "UNKNOWN " + C; // <-- replace with your desired default
>                     if (cell && cell.t) {
>                         hdr = XLSX.utils.format_cell(cell);
>                     }
>                     headers.push(hdr);
>                 }
>                 // For each sheets, convert to json.
>                 var roa = X.utils.sheet_to_json(workbook.Sheets[sheetName]);
>                 if (roa.length > 0) {
>                     roa.forEach(function (row) {
>                         // Set empty cell to ''.
>                         headers.forEach(function (hd) {
>                             if (row[hd] == undefined) {
>                                 row[hd] = '';
>                             }
>                         });
>                     });
>                 }
>             });
> ```

Fantastic, it helped a lot.

**Comment by awaisawanbscs** [comment]
> > Yeah. For me, I go thru the each row and each header to check for undefined values and put '' for empty field.
> > ```js
> >  workbook.SheetNames.forEach(function (sheetName) {
> >                 // Get headers.
> >                 var headers = [];
> >                 var sheet = workbook.Sheets[sheetName];
> >                 var range = XLSX.utils.decode_range(sheet['!ref']);
> >                 var C, R = range.s.r;
> >                 /* start in the first row */
> >                 /* walk every column in the range */
> >                 for (C = range.s.c; C <= range.e.c; ++C) {
> >                     var cell = sheet[XLSX.utils.encode_cell({c: C, r: R})];
> >                     /* find the cell in the first row */
> > 
> >                     var hdr = "UNKNOWN " + C; // <-- replace with your desired default
> >                     if (cell && cell.t) {
> >                         hdr = XLSX.utils.format_cell(cell);
> >                     }
> >                     headers.push(hdr);
> >                 }
> >                 // For each sheets, convert to json.
> >                 var roa = X.utils.sheet_to_json(workbook.Sheets[sheetName]);
> >                 if (roa.length > 0) {
> >                     roa.forEach(function (row) {
> >                         // Set empty cell to ''.
> >                         headers.forEach(function (hd) {
> >                             if (row[hd] == undefined) {
> >                                 row[hd] = '';
> >                             }
> >                         });
> >                     });
> >                 }
> >             });
> > ```
> 
> Fantastic, it helped a lot.

its not work

**Comment by LucasLpr** [comment]
Issue is still open ...

**Comment by gp187** [comment]
Issue still not resolved. Very frustrating

**Comment by Flickza** [comment]
> initial[name] = XLSX.utils.sheet_to_json(sheet,{defval:""})
> 
> ### {defval:""}
> This will work it automatically marks the empty cells as empty strings.

This works! Thanks.

**Comment by gonjavi** [comment]
const data = xlsx.utils.sheet_to_json(ws, { defval: '' }); is used, but it generates unwanted object key : **__EMPTY_**

![image](https://user-images.githubusercontent.com/49737160/233399725-472d2bc2-41bf-4118-9250-88bea3b69444.png)

**Comment by reuben-whammy681** [comment]
> sheet_to_json still not include empty cells





https://nodeer.space/questions/what-is-the-best-way-to-extract-data-from-a-specific-row-and-column-in-an-excel-sheet-and-convert-it-into-json-format-using-nodejs
