### ISSUE TITLE
Open Excel file not detecting any changes

### ISSUE THREAD

**Issue by johisco** [SheetJS/js-xlsx#1401]
Hi! Im working with SheetJS in an electron application.

In my app I allow the user to drag and drop an excel file into the program .... the application thereafter manipulates and saves the modified excel file with the same name. I want the user to be able to have the excel file open (in Excel) and see the changes appear.

As of now when the file is saved I have to close the Excel app and reopen it again to see my changes take effect.

Is this possible? 
Or ..
Is there any thing I could do from the Excel file like allowing background refresh or something similar?

**Comment by SheetJSDev** [comment]
Excel reads the file on load but doesn't poll the filesystem during use.  To verify this, try opening a file and clobbering by writing an empty file to the location.  If you are using a tool that polls the file, you will be notified that the file changed; Excel is blissfully unaware.

There may be a way to do it with VBA but that's far outside the scope of the library.
