### ISSUE TITLE
mime-type always coming as application/zip

### ISSUE THREAD

**Issue by siddarajusrikantaiah** [SheetJS/js-xlsx#1402]
Hi,

I am downloading the xlsx file with below code

                    var wbout = XLSX.write(wb, {bookType:'xlsx', bookSST:true, type: 'binary'});

                    function s2ab(s) {
                      var buf = new ArrayBuffer(s.length);
                      var view = new Uint8Array(buf);
                      for (var i=0; i!=s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
                      return buf;
                    }

                    var blob = new Blob([data], {
                      'type': 'application/vnd.ms-excel'
                    });
                   saveAs(blob, 'sample1.xlsx');

It is downloading the file, but the mime-type is always coming as application/zip even though I set it as 'application/vnd.ms-excel'. 

Please suggest how to get the mime-type which is passed in code in the downloaded file.

Thanks
Sid

**Comment by SheetJSDev** [comment]
XLSX files are really ZIP containers containing a series of XML files, so any tool or process that looks at the magic number of files will conclude that XLSX files are really `application/zip`.  It is out of the library's control.

FWIW: [the `XLSX.writeFile` helper function just sets `application/octet-stream`](https://github.com/SheetJS/js-xlsx/blob/master/bits/19_fsutils.js#L18)

**Comment by LrVch** [comment]
> XLSX files are really ZIP containers containing a series of XML files, so any tool or process that looks at the magic number of files will conclude that XLSX files are really `application/zip`. It is out of the library's control.
> 
> FWIW: [the `XLSX.writeFile` helper function just sets `application/octet-stream`](https://github.com/SheetJS/js-xlsx/blob/master/bits/19_fsutils.js#L18)

var blob = new Blob([blobify(data)], {type:"application/octet-stream"}); Seems it doesn't work, browser always sets mime type as application/zip, though you set it as "application/octet-stream".
