### ISSUE TITLE
Using ['!cols'][i].hidden anywhere results in all columns hidden for Windows users

### ISSUE THREAD

**Issue by atamon** [SheetJS/js-xlsx#1404]
Thanks for providing a great library for exporting data to Excel!

This minimal example reproduces an issue we've had with hidden columns:
```js
var XLSX = require('xlsx');

var ws = XLSX.utils.aoa_to_sheet([]);

const data = {
  "rows": [
    {
      'first_name': 'A',
      'last_name': 'A',
      'email': 'A',
    },
    {
      'first_name': 'B',
      'last_name': 'B',
      'email': 'B',
    },
    {
      'first_name': 'C',
      'last_name': 'C',
      'email': 'C',
    }
  ],
  "header": [
    'first_name',
    'last_name',
    'email'
  ]
}

XLSX.utils.sheet_add_json(ws, data.rows, { origin: 'A1', header: data.header });

ws['!cols'] = [
  {
    "hidden": false
  },
  {
    "hidden": true
  },
  {
    "hidden": false
  }
]

/* add to workbook */
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, 'Example Hidden');

/* generate an XLSX file */
XLSX.writeFile(wb, 'test-exports/hidden-example.xlsx');
```

Expected: column `last_name` is hidden when I open the document `test-exports/hidden-example.xlsx`, but `first_name` and `email` are both visible.

Actual: On Windows (both 7 and 10), using Microsoft Excel 16, all three columns are hidden

Produced file: [hidden-example.xlsx](https://github.com/SheetJS/js-xlsx/files/2755563/hidden-example.xlsx)

We found a workaround that works for us on both Mac and Windows:
```js
...
ws['!cols'] = [
  null,
  {
    "hidden": true
  },
  null
]
...
```

__Are we doing something weird with the construction of the sheet here?__

Thanks for your time!
Regards,
Anton

**Comment by atamon** [comment]
We also found that this workaround produces the expected behavior for both Mac and Windows:
```
...
ws['!cols'] = [
  { width: 5 },
  {
    "hidden": true
  },
  { width: 5 }
]
...
```

**Comment by SheetJSDev** [comment]
This is a deficiency in Excel.  Older versions of Excel treat `width: 0` as equivalent to hidden, and there is no way to specify column properties like hidden without specifying a width.  The best bet, as you discovered, is to manually set a width for each column that you are touching.

**Comment by atamon** [comment]
Thanks for the explanation!
