### ISSUE TITLE
Error on xlsx.readFile, Max call stack size exceeded.

### ISSUE THREAD

**Issue by hopemanryan** [SheetJS/js-xlsx#1405]
While using the readFile function I receive a RangeError: Maximum call stack size exceeded.

trying to parse a small excel file (12 rows). Parsing takes a long time and at the end I will get the error listed above. 

Is there a solution out there ? 

Thank you !

**Comment by SheetJSDev** [comment]
Can you share a file to reproduce this issue?

**Comment by SheetJSDev** [comment]
If you can share a file we'll reopen
