### ISSUE TITLE
xlsx.writeFile exports file without filename and extension

### ISSUE THREAD

**Issue by hallandsen** [SheetJS/js-xlsx#1415]
I try to create an xlsx file form json.

File is written to file system, but has strange random name and no file extension. If I change the filename and add .xls to it, I can open the file in excel and it has the correct content. So I must be exporting the file in a wrong way.

`const ws = xlsx.utils.json_to_sheet(data, { header: headers })`
`const wb = xlsx.utils.book_new()`
`xlsx.utils.book_append_sheet(wb, ws, 'Estimat')`
`xlsx.writeFile(wb, 'file', { type: 'xlsx' })`

Any help would be greatly appreaciated.

**Comment by SheetJSDev** [comment]
`bookType` controls the file type, so you should write

```js
xlsx.writeFile(wb, 'file', { bookType: 'xlsx' })
```

Should be noted that the recommended approach is to use the right extension and skip the `bookType` option entirely:

```js
xlsx.writeFile(wb, "out.xlsx")
```
