### ISSUE TITLE
Error on xlsx.readFile('xxx.xlsx'. options)，when the file is save by mac OS  System

### ISSUE THREAD

**Issue by CHJ1993** [SheetJS/js-xlsx#1419]
when I use js-xlsx to read a file  that save by mac OS System, I will get an error:

Uncaught Error: CLSID: Expected 00000000000000000000000000000000 saw 2008020000000000c000000000000046
    at Array.CheckField [as chk] (xlsx.js?1146:3318)
    at check_get_mver (xlsx.js?1146:1444)
    at parse (xlsx.js?1146:1355)
    at Object.read (xlsx.js?1146:1660)
    at Object.readSync [as read] (xlsx.js?1146:20309)

and than I  try to read the same file your websit demo, also I got the same error

**Comment by feralclaw** [comment]
wps？

**Comment by CHJ1993** [comment]
> wps？

yes

**Comment by nyj000** [comment]
after edited my file with WPS.
I got the same error in
XLSX.read(fs.readFileSync(file))
But I can read the original file

**Comment by billtsu** [comment]
xls edited with wps fail to parse
save as xlsx then success

**Comment by CHJ1993** [comment]
thanks, I try it.
 
------------------



陈杰
犀牛之星服务号


 联系我









 




------------------ 原始邮件 ------------------
发件人: "billtsu"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 下午3:13
收件人: "SheetJS/js-xlsx"<js-xlsx@noreply.github.com>; 
抄送: "1052957708"<1052957708@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [SheetJS/js-xlsx] Error on xlsx.readFile('xxx.xlsx'. options)，when the file is save by mac OS  System (#1419)




xls edited with wps fail to parse
 save as xlsx then success

**Comment by SheetJSDev** [comment]
@CHJ1993 @billtsu can you share an example file ?

**Comment by CHJ1993** [comment]
---------

------------------ 原始邮件 ------------------
发件人: "SheetJSDev"<notifications@github.com>;
发送时间: 2019年6月10日(星期一) 下午5:40
收件人: "SheetJS/js-xlsx"<js-xlsx@noreply.github.com>;
抄送: "1052957708"<1052957708@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [SheetJS/js-xlsx] Error on xlsx.readFile('xxx.xlsx'. options)，when the file is save by mac OS  System (#1419)




@CHJ1993 @billtsu can you share an example file ?

**Comment by xjnotxj** [comment]
Got the same problem... waiting to be solved!!!

**Comment by SheetJSDev** [comment]
@CHJ1993 @xjnotxj  you can't attach via email to github, send us a file directly dev@sheetjs.com

**Comment by CHJ1993** [comment]
I had send to you by email 
------------------



陈杰
犀牛之星服务号


 联系我









 




------------------ 原始邮件 ------------------
发件人: "SheetJSDev"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 下午5:56
收件人: "SheetJS/js-xlsx"<js-xlsx@noreply.github.com>; 
抄送: "1052957708"<1052957708@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [SheetJS/js-xlsx] Error on xlsx.readFile('xxx.xlsx'. options)，when the file is save by mac OS  System (#1419)




@CHJ1993 @xjnotxj  you can't attach via email to github, send us a file directly dev@sheetjs.com

**Comment by SheetJSDev** [comment]
Thank you @CHJ1993 I cannot reproduce the issue using the latest version on the website using Chrome / Safari .  Are you using the latest version in your deployment?  `console.log(XLSX.version)` it should be `0.14.3`

**Comment by SheetJSDev** [comment]
@xjnotxj thank you very much for sharing!

The first 32 bytes of the sample file are:

```
d0 cf 11 e0 a1 b1 1a e1
20 08 02 00 00 00 00 00
c0 00 00 00 00 00 00 46
3e 00 03 00 fe ff 09 00
```

[`MS-CFB 2.2`](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cfb/05060311-bfce-4b12-874d-71fd4ce63aea) states that the second and third lines are the "Header CLSID" and "MUST be set to all zeroes".  Clearly the file has nonzero data, which is why the library errors.  We will need to fix the dependency https://github.com/SheetJS/js-cfb first before updating here.

**Comment by xjnotxj** [comment]
@SheetJSDev Oh! So that explains it. wait for your development follow-up! thanks!

**Comment by SheetJSDev** [comment]
Commit 9aabf361422d3af0ae461d14708d8ccc74977016 should have referenced this issue, @xjnotxj it has been live since 0.14.4, please update and confirm.
