### ISSUE TITLE
incorrect sourceMappingURL

### ISSUE THREAD

**Issue by vinin3** [SheetJS/js-xlsx#142]
i'm including js-xls library using script tag with next src
"libs_path/js-xlsx/dist/xlsx.core.min.js"
after that my 38 google chrome tries to load source map for it using next path
libs_path/js-xlsx/dist/dist/xlsx.core.min.map
as you can see dist is repeated twice (.../dist/dist/......).
as i can see there is next line in xlsx.core.min.js - "//# sourceMappingURL=dist/xlsx.core.min.map"
to make chrome load .map file from correct path i changed it to "//# sourceMappingURL=xlsx.core.min.map" (without dist prefix)
i have surfed internet looking if this can be configured in some way, but i didn't find solution, help please

**Comment by tjhart** [comment]
This is also related to another issue I'm having. I'm using the bower package (0.7.11)

https://github.com/ember-cli/ember-cli/issues/2912

**Comment by reviewher** [comment]
All of the source map references are stripped.

@tjhart I was able to repeat the steps in https://github.com/ember-cli/ember-cli/issues/2912#issue-53562633 with no issue, so I assume the fixes in ember-cli/ember-cli#2912 resolved the issue.  Please raise a new issue if you still have problems.
