### ISSUE TITLE
TSV with empty first cell recognized wrong

### ISSUE THREAD

**Issue by bendlas** [SheetJS/js-xlsx#1421]
When trying to parse a tab-separated-value sheet, where the first cell is empty - that means that the first byte is a '\t' character - the parser jumps into the wrong file format here https://github.com/SheetJS/js-xlsx/blob/1eb1ec985a640b71c5b5bbe006e240f45cf239ab/xlsx.js#L20310

**Comment by Olko7** [comment]
Hello, 

got the same issue. 
Is there any workaround?

**Comment by SheetJSDev** [comment]
Thanks for reporting!

This particular decision is based on older file formats.  "BIFF2" / "BIFF3" / "BIFF4" (the "XLS" formats used in Excel prior to Excel '95) actually start with a tab character `0x09`.  The next character for the BIFF formats is `0x04` (corresponding to the BOF record).

Would it suffice to use plaintext parsing if the next character is not `0x04`?

**Comment by Ramzec** [comment]
any update?

**Comment by SheetJSDev** [comment]
This is an easy PR:

https://github.com/SheetJS/js-xlsx/blob/master/bits/87_read.js#L85

```diff
-		case 0x09: return parse_xlscfb(d, o);
+		case 0x09: if(n[1] <= 0x04) return parse_xlscfb(d, o); break;
```
