### ISSUE TITLE
Does SheetJS support text orientation?

### ISSUE THREAD

**Issue by m90** [SheetJS/js-xlsx#1428]
I would like to rotate the content of a cell by 90 degrees. In Excel I can do that by setting a value of for example 90 degrees when styling the cell:

![image](https://user-images.githubusercontent.com/1662740/52648202-6ac28700-2ee6-11e9-9631-56da1f97e07a.png)

I cannot find anything about this is the docs (both free and paid version which we use), so I would like to know if it is supported at all, or if there are any workarounds for achieving the same layout?

**Comment by SheetJSDev** [comment]
Text rotation and other styles are part of our Pro builds
