### ISSUE TITLE
Issue using ASP.NET MVC 2014

### ISSUE THREAD

**Issue by KarlesP** [SheetJS/js-xlsx#1429]
_Declaimer: For obvious reasons I won't post all of my code but the piece that won't work_

Right now I'm using MVC to develop a website. Right now I want to see a preview of my excel so that I'm 100% sure that it is what I want to upload. Problem is, that I the following lines won't work:

```
<input type="file" name="xlfile" id="xlf" />
```

```
<script src="dist/cpexcel.js"></script>
    <script src="shim.js"></script>
    <script src="jszip.js"></script>
    <script src="xlsx.js"></script>
    
    <script type="text/javascript">
        var X = XLSX = require('xlsx');
        var XW = {
            /* worker message */
            msg: 'xlsx',
            /* worker scripts */
            worker: './xlsxworker.js'
        };
```
specifically `XLSX` is undefined for some reason (and before you ask I'd like to say that every js file that is required is in the same folder)

So, can you explain to me how to fix it?

**Comment by SheetJSDev** [comment]
if you aren't using a bundler tool like webpack, get rid of the `= require('xlsx');` part.
