### ISSUE TITLE
Missing jszip in browserify bundle

### ISSUE THREAD

**Issue by SystemParadox** [SheetJS/js-xlsx#143]
The require call for jszip uses a concatenated string `require('js'+'zip')` which stops browserify from including it. The results in a runtime error `Cannot find module 'jszip'`.

This seems to be intentional (#76?), but I don't understand why because it just breaks the bundle. Is there a reason why jszip cannot be included and if so how can we build a browser bundle?

Thanks.

**Comment by cconrad** [comment]
I worked around this by adding explicit require statements for the two modules ('fs' and 'jszip') in my Browserify configuration:

```javascript
var b = browserify({
  /* ... other options, e.g. "debug:true" ... */
  require: [
    'fs',
    'jszip'
  ]
});
b.transform(/*...*/); b.bundle(); // etc.
```

Then it's just as easy as ```var xlsx = require('xlsx');```.

**Comment by hiattp** [comment]
Any movement on this? @SystemParadox's solution seems solid, there a fork or branch that implements it?

**Comment by SystemParadox** [comment]
A (possibly better) convention I have seen used in other packages is to have a second entry point for the 'extended' version:

```
// normal version (no optional deps)
var xlsx = require('xlsx');
// extended version with optional deps
var xlsx = require('xlsx/extra');
```

**Comment by barbalex** [comment]
I am using xlsx in another project now too (not a CouchApp), built with webpack. I am getting this message in devtools when webpack builds the project:

    ./~/xlsx/jszip.js
    Critical dependencies:
    12:436-443 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
     @ ./~/xlsx/jszip.js 12:436-443

I think it might be related to the above discussion so I added it here. But as I don't understand what is going on: please excuse if this should just be noise!

**Comment by devnieL** [comment]
I get an error when requiring xlsx in my browserify code :

    XLSX = require('xlsx')

Error : 

![image](https://cloud.githubusercontent.com/assets/1231888/10766203/62b45ac2-7ca4-11e5-883c-a69aaad92ad2.png)

Thanks

**Comment by chaluvadis** [comment]
I got the same error. 
I was loading the dependencies like below. 
var angular = require('angular');
var XLSX = require('xlsx');
I tried following ways to referrer jszip module in my code.
#### var jszip = require('jszip');
#### var jszip = require('./node_modules/xlsx/jszip.js');
both options giving the same error. 
<img width="339" alt="screen shot 2015-10-31 at 11 53 27 am" src="https://cloud.githubusercontent.com/assets/738511/10862554/1562c720-7fc6-11e5-800c-7dd3701d7e99.png">
any work around for this issue.

**Comment by chriddyp** [comment]
I've forked a version that fixes this issue: https://github.com/chriddyp/js-xlsx
```
$ npm install xlsx-browerify-shim
```

**Comment by diroru** [comment]
@chriddyp thanks a lot for the fix! It works great for me. You have a tiny typo in the install command though (an 's' is missing from 'browserify').

**Comment by chriddyp** [comment]
thanks @diroru ! Just updated :)

**Comment by TechBK** [comment]
this problem closed?

**Comment by SheetJSDev** [comment]
We un-broke all of the require statements in 0.8.7 and included samples with browserify/requirejs/webpack.  Please check against the latest version
