### ISSUE TITLE
Example code doesn't run

### ISSUE THREAD

**Issue by backstageent** [SheetJS/js-xlsx#1430]
When running the example code on apache server, this code 
 <script lang="javascript" src="xlsx.core.min.js"></script>

Gives this error in javaconsole:
Uncaught SyntaxError: Unexpected token <xlsx.core.min.js:7

What's the fix for this? Surely I'm not the only one who sees this error.

**Comment by SheetJSDev** [comment]
It looks like your browser is getting HTML, possibly a 404 error in disguise.  Are you sure the script is available?
