### ISSUE TITLE
discussion of the inconsistencies within worksheets?

### ISSUE THREAD

**Issue by apolishch** [SheetJS/js-xlsx#144]
I am considering using this library to parse data from Excel Spreadsheets and import data into my system. I would love to find out why some spreadsheets come in as objects with a .Sheet object and keys corresponding to columns, while specific values are represented as object where {v} represents a value, while others come in as layered arrays of rows, with values as string, so that I could set up requirements around spreadsheet creation.

Thanks,
Abe

**Comment by SheetJSDev** [comment]
@apolishch at this point every format parser should generate the same general structure (with a `.SheetNames` array of names, `.Sheets` object of worksheets, each worksheet having keys corresponding to A1 cell addresses, etc).  It is a bug if the same content saved in different formats gives you a different structure.  If you find specific inconsistencies please raise a new issue.
