### ISSUE TITLE
Working with templates

### ISSUE THREAD

**Issue by sonjadeissenboeck** [SheetJS/js-xlsx#1447]
Has anyone every worked with templates and SheetJS.
What I mean by this:
I want the users of my application to be able to preset templates, so that whenever they're downloading data to an excel file, the style/formats of that template is used. And when uploading an excel file again, the application know (based on the template) which columns/rows belong to the template and therefore don't contain relevant data.

Any ideas or advices that may help me?

Thanks!

**Comment by lwf804** [comment]
+1

**Comment by kevrat** [comment]
+1

**Comment by SheetJSDev** [comment]
Template data editing is offered in the Pro compendium (our paid offering). The Community version is primarily focused on data preservation.

https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021 is our general commentary.
