### ISSUE TITLE
Unmerge all cells

### ISSUE THREAD

**Issue by strdr4605** [SheetJS/js-xlsx#1448]
I have an xls file with a lot of merged cells. I need to parse the data by columns. 
How can I easily unmerge all cells only by columns (or at least unmerge all)?
I will send an example of the input file to sheetjs@gmail.com!

**Comment by danton721** [comment]
@strdr4605 I think I am having the same issue to convert to json the following structure, were you able to sort things out?

![image](https://user-images.githubusercontent.com/2263053/89483240-ef0b6880-d771-11ea-9183-56161dd37318.png)

**Comment by strdr4605** [comment]
@danton721 I ended up with copying value of the cell in the merged cells

```ts
  /**
   * Fill cell from a Worksheet that was merged
   * @param {WorkSheet} ws -Worksheet that will be filled
   */
  static fillMerges(ws: WorkSheet): void {
    const merges: Range[] = ws['!merges'];

    const mergesMap: IRangeMap[] = merges.map(merge => ({
      start: this.getCellNameFromCellAddress(merge.s),
      end: this.getCellNameFromCellAddress(merge.e),
    }));

    // console.log(JSON.stringify(mergesMap, undefined, 2));

    for (const merge of mergesMap) {
      const cells: string[] = this.getCellsForHorizontalRange(merge);
      if (ws[merge.start]) {
        const cellValue: CellObject = _.get(ws, merge.start);
        for (const newCell of cells) {
          ws[newCell] = cellValue;
        }
      }
    }
  }
```

[The code](https://github.com/strdr4605/OrarInCalendarAPI/blob/f486f4a45f2dcb65396a7d6dd30c2ba62408c5dd/src/modules/xlsx/XLSUtils.ts#L66).

**Comment by Samandar02** [comment]
i have use this code and it unmerge all merged cells :)
```
sheet['!merges'] = []
```
