### ISSUE TITLE
parse xls/xlsx to array of array

### ISSUE THREAD

**Issue by nakl3** [SheetJS/js-xlsx#1456]
I have some exel file 
![image](https://user-images.githubusercontent.com/47388240/54417767-2bb96880-4714-11e9-96c1-ddc96d2d8939.png)
I don't know name of keys, and bust all keys not comfortable to me
I try to get array of array of text 
[ [ key1 , key2 , .. , keyN ] ,
  [ someData ,someData , .. , someData ],
  [ .. ] , [ .. ] ]  
 but I did not find a realization of this.
It would be great to add this to the library.
P.S. sorry for my bad english

**Comment by SheetJSDev** [comment]
The `sheet_to_json` function takes an options argument, pass the option `header:1`.  See https://docs.sheetjs.com/#json for an explanation and example

**Comment by nakl3** [comment]
Thank you. It is work
