### ISSUE TITLE
encode/decode trouble cyrilic xls

### ISSUE THREAD

**Issue by nakl3** [SheetJS/js-xlsx#1460]
I have xls  [file](https://drive.google.com/open?id=12_xhf8wlj5YbCkQfhwj4uDzEfUh2ZM6p)
my code to parse it
 
```
function Make_list(){
    var reader = new FileReader();
    
  reader.onload = function(e) {
    var data = e.target.result;
     
     var workbook= XLSX.read(data, {type: 'binary'});    //use it because need parse xlsx and xls files
     workbook.SheetNames.forEach(function(sheetName) {
          var formulae = XLSX.utils.sheet_to_formulae(workbook.Sheets[sheetName]);
          console.log(formulae);
          Formulae_to_list(formulae)
        })
    };
  reader.readAsBinaryString(browse.files[0]);
}
```

output is : 
 ["A1='Êîä", "B1='name", "C1='EPOLID", "D1='Äàòà ïðèåìà", "E1='Äàòà óâîëüíåíèÿ", "F1='Äîëæíîñòü òåêóùàÿ", "G1='ÎêëàäÓÅ", "H1='Ïîäðàçäåëåíèå", "I1='ÐåæèìÐàáîòû", "J1='Ñóììà ïðåìèè", "B2='éöó", "C2='amak", "J2='500", "K2='asd", "B3='qwe", "C3='amak", "J3=500", "K3='asd", "B4='asd", "C4='amak", "J4=500", "K4='âôû", "B5='ôûâ", "C5='amak", "J5=500", "K5='asd"]

must be :
 ["A1='Код", "B1='name", "C1='EPOLID", "D1='Дата приема", "E1='Дата увольнения", "F1='Должность текущая", "G1='ОкладУЕ", "H1='Подразделение", "I1='РежимРаботы", "J1='Сумма премии", "B2='йцу", "C2='amak", "J2='500", "K2='asd", "B3='qwe", "C3='amak", "J3=500", "K3='asd", "B4='asd", "C4='amak", "J4=500", "K4='тест", "B5='фыв", "C5='amak", "J5=500", "K5='asd"]

**Comment by artitrue** [comment]
Hi! Have you tried to use modules for "international support" as described in this section https://github.com/SheetJS/js-xlsx#optional-modules ? I parsed your file with "full" version of library and it looks like encoding is handled correctly.

**Comment by nakl3** [comment]
> Have you tried to use modules for "international support" as described in this section https://github.com/SheetJS/js-xlsx#optional-modules ? I parsed your file with "full" version of library and it looks like encoding was handled correctly.

Hi. I added full wersion of liblrary and it worked. Thank you, for good idea)

**Comment by SheetJSDev** [comment]
Just to clarify, XLS predates unicode and therefore doesn't necessarily store data in a standard unicode encoding.  The "full" builds include the codepage library and necessary support, but given the size and the fact that it is only needed in XLS we don't include it in the core file.

**Comment by laizezhong** [comment]
can you tell me hao to resolve the problem，How to add full wersion of library,I use NodeJS

**Comment by SheetJSDev** [comment]
@laizezhong NodeJS should "just work" with `require`.  With `import`, you need to import the codepage dependency manually.  See https://docs.sheetjs.com/docs/installation/nodejs#usage for more info

@failvaliev If you are using the browser build, it is the `xlsx.full.min.js` file.  See https://docs.sheetjs.com/docs/installation/standalone for more info on `<script>` tag usage and https://docs.sheetjs.com/docs/installation/frameworks for bundler usage.

**Comment by failvaliev** [comment]
@SheetJSDev. i have same  encoding problem as the author with .xls file: "Äàòà óâîëüíåíèÿ". But there is no solution.

**Comment by failvaliev** [comment]
> @SheetJSDev. i have same encoding problem as the author with .xls file: "Äàòà óâîëüíåíèÿ". But there is no solution.

use: codepage: '1251'
XLSX.readFile(file, {codepage: '1251' });
