### ISSUE TITLE
Datetime is incorrectly represented in sheet_to_json

### ISSUE THREAD

**Issue by billyjacoby** [SheetJS/js-xlsx#1464]
So I'm using the `XLSX.utils.sheet_to_json` function and getting some really weird side effects using it...

I can't for the life of me figure out whats causing this.

I have date times stored in a CSV file, and for some reason I cannot get them parsed correctly at all.

A line in the CSV is as follows:

`3/22/2019  4:07:00 PM`

however my output without "raw" set to true is just the date like so:
`3/22/19`

When i set raw to true i get some weird number that I cannot for the life of me figure out where it comes from or represent:
`43546.67152777778` 

Where does this number come from and why?

**Comment by billyjacoby** [comment]
Sorry about this, I was adding the date formatting in the wrong function...

**Comment by jwhitmarsh** [comment]
@billyjacoby how did you resolve this?

**Comment by billyjacoby** [comment]
Sorry for the late response, I had to pass the date format that I wanted to use into the `XLSX.read()` function rather than the `XLSX.utils.sheet_to_json()` function.

Let me know if you have any questions or other issues and I'd be happy to help.

**Comment by bestkp** [comment]
by passing opts: `utils.sheet_to_json(ws, {raw: false})`
