### ISSUE TITLE
Incorrect mapping from sheet names to worksheet xml files in Macro-enabled spreadsheets

### ISSUE THREAD

**Issue by whileoneloop** [SheetJS/js-xlsx#1465]
When I try to use XLSX.read() with a Macro-enabled spreadsheet file `*.XLSM` that has a Macro1 sheet present `workbook.Sheets['Sheet1']` has data for the wrong sheet.

In `xl/_refs/workbook.xls.rels` for the problematic file, we notice the Relationship Id `rIdX` attribute value doesn't match the number in the Target attribute value `worksheets/sheetX.xml` .  Notice how rId2 doesn't match sheet1.xml:

```xml
<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
```

The following line may be responsible:

https://github.com/SheetJS/js-xlsx/blob/9866dfc010338394e4cfcd33a9fbc15dae017ee5/bits/85_parsezip.js#L148

To reproduce an XLSX file demonstrating the problem:

1. Save a macro-enabled XLSX file with a single Sheet1
2. Add a macrosheet by pressing `ctrl-f11` (or `cmd-f11` on macos) , you will see a new sheet appear to the left of Sheet1 called Macro1.  Save this file.
3. The XLSX library will return the wrong data in `workbook.Sheets['Sheet1']` .

The attached file is an `*.XLSM` file renamed to `*.ZIP` which demonstrates the problem.

[ExampleMacroEnabledSpreadsheet.xlsm.zip](https://github.com/SheetJS/js-xlsx/files/3007350/ExampleMacroEnabledSpreadsheet.xlsm.zip)

**Comment by SheetJSDev** [comment]
Are you possibly running a very old version?  That file is understood properly if you test with the node bin-script and if you test against https://oss.sheetjs.com/js-xlsx/ .  Keep in mind macro sheets aren't currently parsed out, so you will get an object `{ "!type": "macro" }`.  In NodeJS:

```
$ xlsx -l ExampleMacroEnabledSpreadsheet.xlsm
Macro1
Sheet1
Sheet2
Sheet3
$ for i in {0..3}; do xlsx -N $i ExampleMacroEnabledSpreadsheet.xlsm; done
Macro1
Sheet1
1
Sheet2
2
Sheet3
3
```

In the browser:

![GHissue1465](https://user-images.githubusercontent.com/6070939/54989402-cf194180-4f8e-11e9-8b45-5716dbd49d0b.png)

PS: that fallback is only used if the workbook relationships file does not link to any worksheet.  It is doubly important because older versions of iOS numbers actually defaulted the first worksheet to `sheet.xml` rather than `sheet1.xml`

**Comment by whileoneloop** [comment]
> Are you possibly running a very old version? That file is understood properly if you test with the node bin-script and if you test against https://oss.sheetjs.com/js-xlsx/ . Keep in mind macro sheets aren't currently parsed out, so you will get an object `{ "!type": "macro" }`. In NodeJS:
> 
> ```
> $ xlsx -l ExampleMacroEnabledSpreadsheet.xlsm
> Macro1
> Sheet1
> Sheet2
> Sheet3
> $ for i in {0..3}; do xlsx -N $i ExampleMacroEnabledSpreadsheet.xlsm; done
> Macro1
> Sheet1
> 1
> Sheet2
> 2
> Sheet3
> 3
> ```
> In the browser:
> 
> ![GHissue1465](https://user-images.githubusercontent.com/6070939/54989402-cf194180-4f8e-11e9-8b45-5716dbd49d0b.png)
> 
> PS: that fallback is only used if the workbook relationships file does not link to any worksheet. It is doubly important because older versions of iOS numbers actually defaulted the first worksheet to `sheet.xml` rather than `sheet1.xml`

Indeed it is, the failing file was 35MB, the repro I've supplied isn't sufficient, will create a new reproduction which demonstrates the problem in the live-demo interface.

**Comment by reviewher** [comment]
When you get a chance, please share the file and we can reopen the issue.
