### ISSUE TITLE
How to use xlsx-style in typescript?

### ISSUE THREAD

**Issue by Lilian1331** [SheetJS/js-xlsx#1466]
Hi,
I was using xlsx as my excel export. I am now trying to apply xlsx-style with cell style. However, it gives me the error.
![image](https://user-images.githubusercontent.com/23545532/54986821-4fbb5a80-4fee-11e9-8197-465a088bc619.png)

I only added one line of code as below:
`//import * as XLSX from 'xlsx';`
`import * as XLSX from 'xlsx-style';`

Thanks for any help.

**Comment by SheetJSDev** [comment]
`xlsx-style` is a different project
