### ISSUE TITLE
sheet_to_blob function

### ISSUE THREAD

**Issue by Danieleeee** [SheetJS/js-xlsx#1469]
Hi, 
it's possible to convert sheet to blob?
I need pass XLSX to DB in a common format and store it.

Thanks

**Comment by SheetJSDev** [comment]
You can either

- store the raw file as-is (doesn't involve the library)
- read the files and write to a standard format (`write` can generate an ArrayBuffer or binary string)
- store the JSON representation of the workbook as a string (store as string)

The actual details depend on the specific API and are outside of the scope of this library.

**Comment by Danieleeee** [comment]
Thanks for the answers.
I need to convert the xlsx to blob format because later I might have to write it from another program or insert it into a file.zip 
Surely, transforming it into json format does not allow me to insert it in a zip and find a file.xlsx in it.
Does one of the other two methods described allow me to do this?
For example how do I use:
`saveAs (blob, "file.xlsx");`
instead of using
`XLSX.writeFile(wb, "file.xlsx");`

**Comment by Danieleeee** [comment]
This is my code, I start from a json:
`  let ws = XLSX.utils.json_to_sheet(json); 
        let wb = XLSX.utils.book_new();
        let range = XLSX.utils.decode_range(ws['!ref']);
        let cell_ini:string = XLSX.utils.encode_cell({c:range.s.c, r:range.s.r});
        let cell_fin:string = XLSX.utils.encode_cell({c:range.e.c, r:range.s.r});
        
        ws['!autofilter'] = { ref: cell_ini+':'+cell_fin }
        wb.Props.CreatedDate = new Date();
        wb.Props.Version = "1.0";
        XLSX.utils.book_append_sheet(wb, ws, this.titolo.substring(1, 30));
        
        /* generate an XLSX file */
        XLSX.writeFile(wb, nome_file+".xlsx");`
