### ISSUE TITLE
excel read error when first row of a column is an empty cell.

### ISSUE THREAD

**Issue by kaustuv** [SheetJS/js-xlsx#147]
If excel data has a column whose value is an empty cell in the first row, then that column is not imported. This is possibly because utils.sheet_to_row_object_array() only has keys for non-empty cells.

This means that a simple example like this:

id col1 col2 col3
1 hello1        10
2 hello2 2 20
3 hello3 3 30

Only imports col1 and col3 correctly but not col2

**Comment by zachhale** [comment]
I think I may be experiencing a similar issue which I haven't fully diagnosed yet. I have a spreadsheet where the first row is headers but the next two rows are completely empty and I am running into an issue where a value way down the sheet in row 513 has it's last column incorrectly parsed. The file in the data is 36071161600 but I'm getting 367120000000 after running the file through `xlsx`. After deleting the empty rows, the value comes in correctly. I'm working on diagnosing this into a proper test case still.

**Comment by dominickp** [comment]
I'm also experiencing this issue. I can resolve it by adding data to the first couple of rows. Has anyone come up with a suitable workaround yet?
