### ISSUE TITLE
how to get text styles  for cell 

### ISSUE THREAD

**Issue by agiratech-nagarani** [SheetJS/js-xlsx#1478]
When I am trying to get html of cell and getting like this 

"<r><rPr><b val="true"/><sz val="12"/><color rgb="FFBF9000"/><rFont val="Calibri"/><family val="2"/><charset val="1"/></rPr><t xml:space="preserve"></t></r><r><rPr><sz val="12"/><color rgb="FFBF9000"/><rFont val="Calibri"/><family val="2"/><charset val="1"/></rPr><t xml:space="preserve"> </t></r>"

how can i get normal html format

**Comment by agiratech-nagarani** [comment]
```<r><rPr><b val="true"/><sz val="12"/><color rgb="FFBF9000"/><rFont val="Calibri"/><family val="2"/><charset val="1"/></rPr><t xml:space="preserve">Intercrop:</t></r><r><rPr><sz val="12"/><color rgb="FFBF9000"/><rFont val="Calibri"/><family val="2"/><charset val="1"/></rPr><t xml:space="preserve"> Onion, coriander and potato can grow as additional income.</t></r>`

**Comment by agiratech-nagarani** [comment]
``"<r><rPr><b val="true"/><sz val="12"/><color rgb="FFBF9000"/><rFont val="Calibri"/><family val="2"/><charset val="1"/></rPr><t xml:space="preserve">Intercrop:</t></r><r><rPr><sz val="12"/><color rgb="FFBF9000"/><rFont val="Calibri"/><family val="2"/><charset val="1"/></rPr><t xml:space="preserve"> Onion, coriander and potato can grow as additional income.</t></r>"

**Comment by Rajan-corient** [comment]
How did you solved this problem??
