### ISSUE TITLE
how to read other languages (ex. Korean) in CSV files

### ISSUE THREAD

**Issue by lonalee** [SheetJS/js-xlsx#1481]
I'm trying to read a CSV file including Korean.
Of course no problem with reading English, but it seems like Korean characters can't be read.
I think that Korean characters cant encoded(?) during XLSX.read() method. (not so sure..)

Can anyone help me out with this issue?
I've been looking up any options or ways and trying them for hours but useless.
(You can probably save my day! lol)
Thanks, in advance.

**Comment by SheetJSDev** [comment]
If it's encoded in UTF8, make sure that it starts with the UTF8 BOM.  If not, then pass the option `codepage: 65001` to the read function:

    XLSX.read(data, {type: ..., codepage: 65001});

If it's encoded in Unified Hangul, the codepage is 949 and you have to pass the argument `codepage: 949` directly.

If it's encoded in Johab, the codepage is 1361 and you have to pass the argument `codepage: 1361` directly.

There are other encodings too, go to https://github.com/sheetjs/js-codepage and search for "Korean" to find all of the possible values.
