### ISSUE TITLE
how to deal with an arrayBuffer, if file has no BOM

### ISSUE THREAD

**Issue by lonalee** [SheetJS/js-xlsx#1482]
Hello, thanks for the help with my question yesterday.
I have another issue here.
I have to deal with arrayBuffer which is created by users' uploaded files.
And let's say the uploaded file has no BOM(UTF-8), then what should I do?
Should I still add UTF-8 BOM in the arrayBuffer? If so, please let me know how to do that.
Thank you so much.

**Comment by SheetJSDev** [comment]
Glad to hear it was helpful!  If the BOM is missing and you know it is unicode, you can still pass the codepage argument to the read function, that will force override.  Use 65001 for UTF8 and 1200 for UTF-16 (little ending).
