### ISSUE TITLE
How to add class to html table generated by

### ISSUE THREAD

**Issue by gustawdaniel** [SheetJS/js-xlsx#1485]
Function `sheet_to_html` allows to generate raw html table. I want to add to them some classes or override their template in elastic way? How to do this using this function?

For example instead

```
<table>...</table>
```

I asking about: how to generate

```
<div class="table-responsive">
  <table class="table">
    ...
  </table>
</div>
```

to prevent table stick out frame. Example: Responsive tables:

> https://www.w3schools.com/bootstrap4/bootstrap_tables.asp

**Comment by gustawdaniel** [comment]
Now I have

HTML
```
<div id="out" class="table-responsive"></div>
```

JavaScript
```
const html = XLSX.utils.sheet_to_html(ws, {editable: true});
document.getElementById('out').innerHTML = html;
document.getElementById('out table').classList.add("table");
```

If it is best way please close this issue. It you know better, please comment.

**Comment by SheetJSDev** [comment]
This is a horrible hack and eventually will be fixed, but you could set the `id`:

```js
const html = XLSX.utils.sheet_to_html(ws, {editable: true, id: 'newid" class="newclass'});
```

The reason this hack works is because the function doesn't attr-escape the id: https://github.com/SheetJS/js-xlsx/blob/master/bits/79_html.js#L87
