### ISSUE TITLE
writeFile not working on ios/Safari

### ISSUE THREAD

**Issue by richpixel** [SheetJS/js-xlsx#1491]
When trying to save the workbook on iPhone/Safari:
> Error: cannot save file filename.xlsx

iOS 12.2

This code works fine on all desktop browsers.

`XLSX.writeFile(wb, filename);`

Thank you

**Comment by SheetJSDev** [comment]
Unfortunately none of the known techniques for forcing a download consistently work on iOS Safari.  There is a WebKit bug report https://bugs.webkit.org/show_bug.cgi?id=167341 but despite the fact that they report it as "fixed" it is not currently live on iOS yet.   There is nothing we can do :(
