### ISSUE TITLE
Issue while Reading Excel file with Image

### ISSUE THREAD

**Issue by sunilcet488** [SheetJS/js-xlsx#1495]
Not able to read image file in the excel file.

Reading Excel File having image.
<input type='file' onchange='openFile(event)'>

var openFile = function (event) {
    var input = event.target;
    var reader = new FileReader();
    reader.readAsBinaryString(input.files[0]);
    var data = reader.result;
    var workbook = XLSX.read(data, {
        type: 'binary'
    });
  // Doing Some modification in excel file then writing the same
    var wbout = XLSX.write(workbook, {
        bookType: 'xlsx',
        type: 'binary'
    });
 // Download the file
    function s2ab(s) {
        var buf = new ArrayBuffer(s.length);
        var view = new Uint8Array(buf);
        for (var i = 0; i < s.length; i++) view[i] = s.charCodeAt(i) & 0xFF;
        return buf;
    }
    saveAs(new Blob([s2ab(wbout)], {
        type: "application/octet-stream"
    }), 'test123.xlsx');
}

**Comment by qianyan123** [comment]
https://github.com/exceljs/exceljs  this project has already solved this problem,you can try this

**Comment by SheetJSDev** [comment]
Image support is offered in the Pro compendium (our paid offering). The Community version is primarily focused on data preservation.

https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021 is our general commentary.  See https://sheetjs.com/pro for more info
