### ISSUE TITLE
How to export data to a TSV file using SheetJS on the client?

### ISSUE THREAD

**Issue by savandriy** [SheetJS/js-xlsx#1497]
Going through the [SheetJS docs](https://github.com/SheetJS/js-xlsx), I noticed exporting to a csv file is supported. And I have the working code, to convert an array of objects into a file and start the download:

```javascript
let workSheet = XLSX.utils.json_to_sheet(rows);
let workBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workBook, workSheet);
XLSX.writeFile(workBook, 'export.csv');
```

But when it comes to tsv, there's only an [example to convert a sheet to text](https://github.com/SheetJS/js-xlsx#delimiter-separated-output):

```javascript
> console.log(XLSX.utils.sheet_to_csv(ws, {FS:"\t"}));
S	h	e	e	t	J	S
1	2	3	4	5	6	7
2	3	4	5	6	7	8
```

The question is, how to get this kind of output, but in a file?

**Comment by SheetJSDev** [comment]
It's not really documented well, but the options object is passed through to the helper functions.  You should be able to pass the FS option to `writeFile` directly:

```js
XLSX.writeFile(workBook, 'export.tsv', {bookType:"csv", FS:"\t"});
```
