### ISSUE TITLE
Can I write create an inifinite number of records ?

### ISSUE THREAD

**Issue by RichyNs** [SheetJS/js-xlsx#1498]
I am reading from an array of array with 800 000 recrods , i'm creating a ws and wb with the extension .csv ... the maximum number of records it was able to create was around 400 000 ... is there a way to increate that max ??

**Comment by SheetJSDev** [comment]
Excel 2019's max supported rows is `2**20 == 1048576`, there are other limitations too as described in ["Excel Specifications and Limits"](https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3)
