### ISSUE TITLE
How to delete last row of sheet?

### ISSUE THREAD

**Issue by Harrynho** [SheetJS/js-xlsx#1500]
I have this;

```
            $('.tablax').each(function () {
                var ws = XLSX.utils.table_to_sheet(document.getElementById(this.id), { raw: true });
                
                //ws['!deleteRows'] ={ } How to use this?

                XLSX.utils.book_append_sheet(wb, ws, "hoja" + i);
                i = i + 1;
            });
```

I need to delete the last row of every sheet, i have read that it might be a **delete_rows(ws, start_row, nrows)**  function. But i cant find any examples of that, and isn't available in XLSX.utils functions.

**Comment by SheetJSDev** [comment]
The code is in a comment https://github.com/SheetJS/js-xlsx/issues/352#issuecomment-456976898
