### ISSUE TITLE
Tree-shakable xlsx with angular 7

### ISSUE THREAD

**Issue by fahrulalwan** [SheetJS/js-xlsx#1502]
Hi,

I want to implement tree-shakable this library with angular 7, is there any possible way? since the cpexcel.js & xlsx.js is much larger than my app even with `ng build --prod`.

currently i had tried but it showing error "json_to_sheet" is undefined.

**Comment by spradlin-dev** [comment]
xlsx is by far the largest part of our vendors library, despite accounting for an extremely small portion of our functionality.
![image](https://user-images.githubusercontent.com/52361010/61975464-cf623180-afae-11e9-82e6-9c4fa3792c84.png)

**Comment by SheetJSDev** [comment]
0.15.0 ships with a mini build that is limited to XLSX operations (xlsx.mini.min.js).  It is 180K uncompressed / 57K compressed.

XLS support requires the huge codepage library, there isn't much room for reducing the bundle size.  If there is another specific slice that you need (say, just the read functionality), we can look into preparing another mini build.

**Comment by fchiumeo** [comment]
> 0.15.0 ships with a mini build that is limited to XLSX operations (xlsx.mini.min.js). It is 180K uncompressed / 57K compressed.
> 
> XLS support requires the huge codepage library, there isn't much room for reducing the bundle size. If there is another specific slice that you need (say, just the read functionality), we can look into preparing another mini build.

v0.15.0 xlsx.mini add cpexcel and dist/xlsx.mini.min throw error

```
ERROR in ./node_modules/xlsx/dist/xlsx.mini.min.js
Module not found: Error: Can't resolve './dist/cpexcel.js' in '\node_modules\xlsx\dist'
````

**Comment by SheetJSDev** [comment]
Thanks for looking into this!  We tested in a direct script tag injection (http://sheetjs.com/demos/tablemini) but not in a bundle setup :( it'll be corrected in the next release

**Comment by SheetJSDev** [comment]
0.15.1 removed that errant reference.  Tested against parcel.  Things should "just work", please test and confirm.

**Comment by Fratt** [comment]
How do I import the mini only in my angular app ?
Right now I'm running, on my page : import * as XLSX from 'xlsx';

**Comment by fchiumeo** [comment]
```ts
import * as XLSX from 'xlsx/dist/xlsx.mini.min';
```
