### ISSUE TITLE
iOS Nativescript: Cannot Access File.

### ISSUE THREAD

**Issue by pradumnk-mahanta** [SheetJS/js-xlsx#1503]
I am trying to use this in a nativescript application. The file is accessible to the application and can be read using file-system, the module provides an error that the file is not accessible. Am I doing something wrong? 

*Code*
<img width="700" alt="Screenshot 2019-05-13 at 3 15 01 PM" src="https://user-images.githubusercontent.com/18536894/57612218-0ae58600-7592-11e9-8b64-69cf08268e06.png">

*Error*
<img width="1690" alt="Screenshot 2019-05-13 at 3 12 24 PM" src="https://user-images.githubusercontent.com/18536894/57612207-04570e80-7592-11e9-98af-3b7dfe35ab7a.png">

**Comment by SheetJSDev** [comment]
`readFile` is shaped specifically for NodeJS and does not work with nativescript's incompatible interface.  Follow the example in https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2#nativescript -- you must read the data then call `XLSX.read`:

```js
/* read a workbook */
const bstr: string = await file.readText(textModule.encoding.ISO_8859_1);
const wb = XLSX.read(bstr, { type: "binary" });
```

Complete example app component code in https://github.com/SheetJS/js-xlsx/blob/master/demos/angular2/nscript.ts
