### ISSUE TITLE
xlsx.writeFile is creating the excel file but it's not downloading it.

### ISSUE THREAD

**Issue by RichyNs** [SheetJS/js-xlsx#1504]
In the documentation  xlsx.writeFile is supposed to also download the excel file through the browser but's it's not working so I am doing it using other code. Is this a bug or that's how it's supposed to work ?

**Comment by SheetJSDev** [comment]
Check your browser console -- is there an error?

**Comment by RichyNs** [comment]
that's how I'm using it :
const ws = xlsx.utils.aoa_to_sheet(transactions);
    console.log('created ws');
    const wb = xlsx.utils.book_new();
    console.log('created wb');
    xlsx.utils.book_append_sheet(wb, ws, 'SheetJS');
    await xlsx.writeFile(wb, 'Transactions.csv');

and yes not I just checked console is returning an error:

Failed to load resource: net::ERR_FAILED

Access to XMLHttpRequest at 'https://play.google.com/log?format=json&hasfast=true&authuser=0' from origin 'chrome-search://local-ntp' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://play.google.com' that is not equal to the supplied origin.

**Comment by RichyNs** [comment]
any Idea what this error is ?

**Comment by RichyNs** [comment]
Any Idea how to fix this error ? Or what is generating it ?
