### ISSUE TITLE
Support for RN Expo apps

### ISSUE THREAD

**Issue by maharjanaman** [SheetJS/js-xlsx#1506]
Do we have an example for expo apps?? Or is this supported on expo app??
I tried it with expo [FileSystem](https://docs.expo.io/versions/v32.0.0/sdk/filesystem/) and FileSystem can only read files as a string in either UTF8 or BASE64 encoding types. Can these encoding types be used in reading spreadsheet formats??
P.S. docs include an example in react-native which uses react-native-fs to read file is `ascii` encoding. Does the library support only `ascii` while reading?

**Comment by SheetJSDev** [comment]
Expo apparently supports base64 encoding, so you should be able to read the file with something like:

```js
FileSystem.readAsString(fileUri, {encoding: FileSystem.EncodingTypes.Base64}).then(b64 => {
  const wb = XLSX.read(b64, {type: "base64"});
}).then(wb => { /* process the workbook here */ });
```

If that works, please feel free to add a line in https://github.com/SheetJS/js-xlsx/blob/master/demos/react/README.md about it. 

PS: https://github.com/SheetJS/js-xlsx/blob/master/demos/react/react-native.js shows use in react native with both react-native-fs and with react-native-fetch-blob.  To see RNFB usage, comment out the 4 lines under "// react-native-fs" and uncomment the block after "// react-native-fetch-blob"
