### ISSUE TITLE
Confused about reading Excel file from React component

### ISSUE THREAD

**Issue by nathanmdaniel** [SheetJS/js-xlsx#1515]
I am very new to Javascript, React, and SheetJS so please excuse me if this is a basic misunderstanding! When I save this, localhost:3000 shows this error:

> TypeError: _fs.readFileSync is not a function

After looking online, some said this error occurs when this Javascript is executed in the browser, but my understanding was that React would do all this on the server side. Additionally, in another one of my classes, I use a Card that displays a picture using a filepath, so I don't think using a filepath should be an issue. I would prefer a solution where I could upload the Excel file from a path relative to the server location because I look to expand code to run on a network server. 

My code using XLSX is below. Thanks!

```
import React from 'react';
import XLSX from 'xlsx';
import Button from '@material-ui/core/Button';


function genButtons() {
	const XLSX = require('xlsx');
	var workbook = XLSX.readFile('./SampleInventory.xlsx');
        // ***JUST FILLER RETURN BELOW
	var arr = [];
	for (var i = 0; i < 10; ++i)
		arr.push(<Button> Button</Button>);
	return arr;
}

function ClothingButtons(props) {
	var buttArr=genButtons();
	return (
		<div>
			{buttArr}
		</div>
	);
}

export default ClothingButtons;
```

**Comment by SheetJSDev** [comment]
There's a comment but it's unfortunately hidden within the details/summary block for "nodejs read a file"

> readFile is only available in server environments. Browsers have no API for reading arbitrary files given a path, so another strategy must be used.

You have to use another technique, such as `fetch` to download from a public location, to get the data.

There are some demos for environments like [electron](https://github.com/SheetJS/js-xlsx/tree/master/demos/electron) and [react-native](https://github.com/SheetJS/js-xlsx/tree/master/demos/react) that show how to read / write files using alternative APIs.

**Comment by nathanmdaniel** [comment]
Hmm okay thank you for the quick response!
