### ISSUE TITLE
bug XLSX.utils.sheet_to_csv(sheet) got only 3 rows in large excel data

### ISSUE THREAD

**Issue by zlzdp** [SheetJS/js-xlsx#1519]
I found a bug, XLSX.utils.sheet_to_csv(sheet) got only 3 rows in large excel data,
but in MS Excel, I can see the large data in the table.

can you debug it?
I debug it, I can see large data in Strings property.
maybe sheet_to_csv() has bug.

version:
xlsx@0.14.3/dist/xlsx.full.min.js

**Comment by SheetJSDev** [comment]
Without seeing the sheet, the file is likely reporting the range to be something like `A1:J3` (only 3 rows).  Use the `update_sheet_range` function from https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions to recalculate the range and try again
