### ISSUE TITLE
Compression not working when writing xls files

### ISSUE THREAD

**Issue by pgomesdev** [SheetJS/js-xlsx#1520]
I'm using the xlsx library to generate a worksheet based on some data(an array of objects). When I generate a `.xlsx` file, the compression occurs, but when I try to use it with a `.xls`, there's no difference in use the `compression` option. I used both `write` and `writeFile` methods.

These are the results:

![](https://res.cloudinary.com/pgomesdev/image/upload/v1559136409/samples/sheets.png)

https://gist.github.com/pgomesdev/af57871f34e89332512223776b2f7a0a -This is the code I used to generate these files.

**Comment by SheetJSDev** [comment]
XLSX uses a ZIP container, which supports compression.  The default behavior is to use stored blocks and the `compression: true` setting forces DEFLATE compression.

The container format for XLS (so-called "CFB") does not support any sort of compression.  It's like a file-based FAT.  The compression setting noops for XLS.
