### ISSUE TITLE
Passing Workbook to React Component from Server

### ISSUE THREAD

**Issue by nathanmdaniel** [SheetJS/js-xlsx#1526]
I want to pass a workbook from my server.js file to my react components so that they can use the data from the workbook to display in themselves. I am not sure how to go about this. Ideally, I could just pass a prop into my outermost component. I explored the setInitialProps function and using fetch to retrieve the workbook. If that is the best method, would the url I am fetching from just be [server IP address : port number]? Also, how would I write the function in my server.js file to recieve that request and return the workbook? Please let me know if there is a simpler method!

I know that the workbook is being read in successfully in my server.js file right now.

I am using NextJS by the way. Also,  I am new to JavaScript, React, NodeJS, NextJS, and SheetJS, so any input is greatly appreciated!

Thanks

**Comment by SheetJSDev** [comment]
That's a question better directed towards a React support group, but I would expect it is easiest to have your front-end download the file (send as a Buffer from your nodejs server and fetch from your browser page).  There are some examples of [React / next.js](https://github.com/SheetJS/js-xlsx/blob/master/demos/react) and [Downloading files](https://github.com/SheetJS/js-xlsx/tree/master/demos/xhr) if you want inspiration
