### ISSUE TITLE
Generated worksheet not showing data

### ISSUE THREAD

**Issue by kthornsbury** [SheetJS/js-xlsx#1530]
I have the following code which outputs data for a new worksheet, but the existing and new tabs do not display any data when opened in Excel:

`let XLSX = require('xlsx');
let inquirer = require('inquirer');
let getType = require('pinyin-or-hanzi');
let pinyinify = require('hanzi-tools').pinyinify;

inquirer.prompt([{
        type: 'input',
        name: 'origFileLocation',
        message: 'What file do you want to translate?',
        default: './test.xlsx'
    },
    {
        type: 'input',
        name: 'newFileLocation',
        message: 'Where do you want to store the new file?',
        default: './newtest.xlsx'
    }
]).then(
    answers => {
        let workbook = XLSX.readFile(answers.origFileLocation);
        let firstSheetName = workbook.SheetNames[0];
        let worksheet = workbook.Sheets[firstSheetName];
        var range = XLSX.utils.decode_range(worksheet['!ref']);
        for (let rowNum = range.s.r; rowNum <= range.e.r; rowNum++) {
            for (let colNum = range.s.c; colNum <= range.e.c; colNum++) {
                let cellName = XLSX.utils.encode_cell({
                    r: rowNum,
                    c: colNum
                })
                let cellObject = worksheet[cellName];
                let status = cellObject ? getType(cellObject.v.toString()) : '';
                let retValue = status == 'other' ? cellObject.v : (cellObject !== undefined ? pinyinify(cellObject.v) : '');
                console.log(retValue);
                worksheet[cellName] = retValue;
            }
        }
        console.log(worksheet);
        console.log(workbook);
        XLSX.utils.book_append_sheet(workbook, worksheet, 'converted');
        console.log(workbook);
        XLSX.writeFile(workbook, answers.newFileLocation);
    }
)`

**Comment by kthornsbury** [comment]
test.xlsx is the original, which does display data, and newtest.xlsx is the generated file that shows nothing.

[newtest.xlsx](https://github.com/SheetJS/js-xlsx/files/3264215/newtest.xlsx)
[test.xlsx](https://github.com/SheetJS/js-xlsx/files/3264216/test.xlsx)

Thanks in advance for your help!

**Comment by SheetJSDev** [comment]
You are overwriting the original cell objects with a string value, you probably want to assign the `v` key of the object:

```js
// worksheet[cellName] = retValue; // this is wrong
worksheet[cellName].v = retValue; // this sets the value
```
