### ISSUE TITLE
r.forEach is not a function

### ISSUE THREAD

**Issue by bobjenkin** [SheetJS/js-xlsx#1531]
I am using FireFox 67.0.1 (64 bit).  This is my code

<script type="text/javascript" src="shim.min.js"></script>
<script lang="text/javascript" src="xlsx.full.min.js"></script>

	    var xmlhttp = new XMLHttpRequest();
	    xmlhttp.onreadystatechange = function() {
	        if (xmlhttp.readyState == 4 && xmlhttp.status == 200) {
	            try {
	                alert(xmlhttp.responseText);
	                var  ws = XLSX.WorkSheet = XLSX.utils.json_to_sheet(xmlhttp.responseText);
	        		var wb = XLSX.WorkBook = XLSX.utils.book_new();
	        		XLSX.utils.book_append_sheet(wb, ws, 'test');
	                XLSX.writeFile(ws, "export.xlsx");
	            } catch(err) {
	                console.log(err.message + " in " + xmlhttp.responseText);
	                return;
	            }
	        }
	    };
	 
	    xmlhttp.open("GET", "http://" + window.location.host + "/awsservers/rest/vms/" + session, true);
	    xmlhttp.send();		

I am able to obtain and load json from ajax call then the error happens.

**Comment by bobjenkin** [comment]
it was the \" in json data coming back from a service call that causes the r.foreach error.

**Comment by SheetJSDev** [comment]
You need to parse it first with `JSON.parse`:

```js
                var  ws = XLSX.utils.json_to_sheet(JSON.parse(xmlhttp.responseText));
```

**Comment by bfailing** [comment]
I'm seeing the same error in Firefox and Chrome on Windows 10.  Version 0.15.5 of xlsx.min.js.

```
<script type="text/javascript" src="xlsx.min.js"></script>

let json = {
    "first": 1,
    "second": 2
};

let wb = XLSX.utils.book_new();
let ws = XLSX.utils.json_to_sheet(json);
XLSX.utils.book_append_sheet(wb, ws, 'Test');
XLSX.writeFile(wb, 'workbook.xlsx');
```

**Comment by SheetJSDev** [comment]
Pass an array of objects:

```js
let ws = XLSX.utils.json_to_sheet([json]);
```

The generated worksheet will have two rows: a header row and a data row corresponding to the object.

**Comment by bfailing** [comment]
I tried that, but get a series of errors when opening the file in Excel.  First is "Excel found unreadable content in 'workbook.xlsx'. Do you want to recover the contents of this workbook? If you trust the source of this workbook, click Yes." After clicking "Yes," the next error is "Excel cannot open the file 'workbook.xlsx' because the file format or file extension is not valid. Verify that the file has not been corrupted and that the file extension matches the format of the file."
