### ISSUE TITLE
enable programmatic enum for default properties for sheet_to_json

### ISSUE THREAD

**Issue by michaelhyman** [SheetJS/js-xlsx#1536]
perhaps i haven't found the right thing to try, but i would like to be able to use default values for some of the properties in sheet_to_json. e.g. 

header | Description
-- | --
1 | Generate an array of arrays ("2D Array")
"A" | Row object keys are literal column labels
array of strings | Use specified strings as keys in row objects
(default) | Read and disambiguate first row as keys

I'd like to be able to pass the default -- read and disambiguate -- into the header property -- couldn't find a way to do so

**Comment by SheetJSDev** [comment]
The current implementation takes any other value as default, as represented in the test at https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L51-L53 .  The safest thing to do is to set it to `null`, and we'll make that the official case.  If you'd like to submit a PR, the fix would be adding a line just after line 53, something like

```js
	else if(o.header == null) header = 0;
```

**Comment by SheetJSDev** [comment]
fixed in ee862e3adfd927175a573ee9198eb395d0159cf2
