### ISSUE TITLE
Changing individual cell style

### ISSUE THREAD

**Issue by NhatL** [SheetJS/js-xlsx#154]
So right now I have my cell like this
var cell = { v: data[R][C] };

How can I add an option for it to the cell to be bolded/filled with a color/underlined/colored?

I tried 

cell = {
    v: data[R][C], 
    s: { "font-weight": 900 }
};

but it doesn't work :(

**Comment by gradualstudent** [comment]
Might there be any forks of the js-xlsx library that allow limited formatting?

**Comment by NhatL** [comment]
The closest thing I managed to figure out is to export it using the Office XML format. That allows full formatting of the cells

**Comment by SheetJSDev** [comment]
@NhatL to be clear, I don't expect that the object format with the named styles (backgroundColor etc) will be the final representation.  It's too tied to XLSX, and the other formats (like SpreadsheetML) use different names to reference the same concept.

**Comment by elad** [comment]
I should note that although in the past (issue #128) I objected to using CSS for this, I have since changed my mind. I now agree that if we're going to support multiple formats we might as well use an existing, familiar language to describe styles in the common representation.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
