### ISSUE TITLE
How to extract cell info with attached comment on sheet_to_json function

### ISSUE THREAD

**Issue by kpilkevich** [SheetJS/js-xlsx#1540]
Hello.
I need to extract google spreadsheet and some of cells has comments on it, and i need them in output object. I use sheet_to_json function. For example I have such small table with 2 cells (header and value):
```
{
    A1: { t: "s", v: "Name", r: "<t>Name</t>", h: "Name", w: "Name"},
    A2: {
        t: 's',
        v: 'Rudolf',
        r: '<t>Rudolf</t>',
        h: 'Rudolf',
        w: 'Rudolf',
        c: [{
            a: 'sheetjsghost', t: 'comment\n', r: '<t xml:space="preserve">commeent\n</t>', h: 'commeent<br/>'
        }]
    }
}
```
And I want to have the comment attached to the value. I don't know in what format it can be... May be some sort this:
```
{
    Name: { value: 'Rudolf', comment: 'comment'}
}
```
I haven't found any info about how it can be implemented. May be there is some another function to deal with this? Or the only way is to write own parse function?
Thank you!

**Comment by SheetJSDev** [comment]
It's pretty straightforward to make your own function.  The `sheet_to_json` function is implemented in https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L7-L88

Assuming you copied the functions elsewhere, the line https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L23 would be changed to `var v = { value: val.v, comment: (val.c||[]).map(cmnt => cmnt.t).join("") };`

**Comment by roy-lau** [comment]
How do the extracted comments be written into the sheet? How do I need to modify `json_to_sheet`?

**Comment by skobak** [comment]
@SheetJSDev maybe it would be good to add an Option flag, like { richValue : true }  and default false which return plain value ?
