### ISSUE TITLE
Cannot read propert 'String' of undefined

### ISSUE THREAD

**Issue by deedee1378** [SheetJS/js-xlsx#1542]
I am trying to create a excel workbook and download it. I am getting the above error while I do wb.download()
/* bookType can be any supported output type */
var wopts = { bookType:'xlsx', bookSST:false, type:'array' };

var wbout = XLSX.write(workbook,wopts);

/* the saveAs call downloads a file on the local machine */
saveAs(new Blob([wbout],{type:"application/octet-stream"}), "test.xlsx");

The error seems to happen in the jszip when the library tries to convert the input into TranformTo method.

I am using 0.12.13 version of xlsx

**Comment by SheetJSDev** [comment]
Please update to the latest version, if the error persists please reopen
