### ISSUE TITLE
Formatting cells to text size | excel size

### ISSUE THREAD

**Issue by stychu** [SheetJS/js-xlsx#1549]
Is there a way to adjust row cell size to the text length?
Whenever I generate a new Excel from json and I open it all cells are shrunk and file size is very large like 18mb. When I format the cells within created excel Format -> Automatically adjust row height -> Automatically adjust row width all text fits perfectly with cells and file size is REDUCED to 2mb...

**Comment by SheetJSDev** [comment]
File size can be reduced by passing the `compression: true` option when writing.
