### ISSUE TITLE
link 404

### ISSUE THREAD

**Issue by xiaoCong2014** [SheetJS/js-xlsx#1552]
I cannot visit "https://docs.sheetjs.com/demos/angular2/"

**Comment by reviewher** [comment]
Hmm it should be linking to the github page https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2 .  If you clone the repo, the path is `/demos/angular2/`

**Comment by xiaoCong2014** [comment]
1,Thank you for your reply.
2,When I read the document ( "https://docs.sheetjs.com/#installation" ), I found that I can not visit the link ( "https://docs.sheetjs.com/demos/angular2/" ) in this document.
So,who can solve this problem in this document?
