### ISSUE TITLE
jszip is not a constructor 

### ISSUE THREAD

**Issue by chenjiangyo** [SheetJS/js-xlsx#1554]
jszip is not a constructor

**Comment by kostasx** [comment]
Also, `ke is not a constructor` when using the minified version.

**Comment by chenjiangyo** [comment]
> Also, `ke is not a constructor` when using the minified version.

thanks,The problem has been solved.

**Comment by darrenrector91** [comment]
no it hasn't
```xlsx.js:2867 Uncaught TypeError: jszip is not a constructor
    at zip_new (xlsx.js:2867)
    at write_zip (xlsx.js:20216)
    at write_zip_type (xlsx.js:20446)
    at Object.writeSync [as write] (xlsx.js:20548)
    at TableExport.getRawData (tableexport.js:627)
    at TableExport.export2file (tableexport.js:584)
    at TableExport.downloadHandler (tableexport.js:548)```

**Comment by zhaoxiaofeng1995** [comment]
Can you tell me how to solve it?

**Comment by TexasSwede** [comment]
> > Also, `ke is not a constructor` when using the minified version.
> 
> thanks,The problem has been solved.

Please post the solution.

**Comment by madhumurugan89** [comment]
pls post solution

**Comment by matthewlamhk01** [comment]
I got the same error in reactjs if I directly import xlsx
`import * as XLSX from 'xlsx'`

I solved the issue by upgrading the xlsx version to 0.17, and update the import to
`import * as XLSX from 'xlsx/dist/xlsx'`

hope this can help if someone get the same issue
