### ISSUE TITLE
x.charCodeAt is not a function 

### ISSUE THREAD

**Issue by sheepfly** [SheetJS/js-xlsx#1555]
hello

### problem description
When i try to upload a file of .xlsx,the brower says:`TypeError: x.charCodeAt is not a function`.Then I open development tools of chrome to debug this error.And i found that this error caused in `node_modules/xlsx/xlsx.js:20252`.I find this in VS Code,when my mouse is on charCodeAt,vscode tell me the details of charCodeAt,This means charCodeAt is indeed a function.How do i deal with this problem?

### code in my antd pro project:
```javascript
import ExportJsonExcel from 'js-export-excel';

import XLSX from 'xlsx';

import {Upload, Tooltip } from 'antd';

// 定义upload的uploadprops
const uploadprops = {
  accept: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  name: 'file',
  headers: {
      authorization: 'authorization-text',
  },
  showUploadList: false,
  beforeUpload: (file, fileList) => {
    
    var rABS = true;
    const f = fileList[0];
    var reader = new FileReader();
    reader.onload = function (e) {
        var data = e.target.result;
        // if (!rABS) data = new Uint8Array(data);
        data = new Uint8Array(data);
        var workbook = XLSX.read(data, {
            type: rABS ? 'binary' : 'array'
        });
        var first_worksheet = workbook.Sheets[workbook.SheetNames[0]];
        var jsonArr = XLSX.utils.sheet_to_json(first_worksheet, {header:1});
    };
    if (rABS) reader.readAsBinaryString(f); else reader.readAsArrayBuffer(f);
    return false;
  }
```
### error screenshot:
![image](https://user-images.githubusercontent.com/39870481/60573411-30308c80-9daa-11e9-89f1-835695cda6ea.png)

### vscode screenshot
![image](https://user-images.githubusercontent.com/39870481/60573487-57875980-9daa-11e9-9f18-6b602452ccc5.png)

please help me to deal with this problem , thanks.

**Comment by reviewher** [comment]
remove the line

```js
        data = new Uint8Array(data);
```

**Comment by sheepfly** [comment]
Thank you,the problem solved.

**Comment by tongshan0** [comment]
i was run your code in my local,it's no problem,,,
sorry, my english is so bad,hhhh

**Comment by hmy4677** [comment]
哎呀，谢谢，我也成功了

**Comment by suryaSing65** [comment]
**twt**ert****
