### ISSUE TITLE
Incorrect !ref

### ISSUE THREAD

**Issue by jozefdzurenda** [SheetJS/js-xlsx#1557]
Hello,
I am having a problem with parsing following file:
[excel_data.xlsx](https://github.com/SheetJS/js-xlsx/files/3375947/excel_data.xlsx)

Code:
```html
<body>
	<input name="xlfile" id="xlf" type="file">

	<script>
		var xlf = document.getElementById('xlf');
		xlf.addEventListener('change', handleFile, false);
		
		function handleFile(e) {
			var f = e.target.files[0];
			console.log(f.name);
			var reader = new FileReader();
			reader.onload = function(e) {
				var data = e.target.result;
				data = new Uint8Array(data);
				var wb = XLSX.read(data, {type: 'array'});
				var sh = wb.Sheets["Data"];
			}
			reader.readAsArrayBuffer(f);
		}
	</script>
</body>
```
The problem is that the "Data" sheet is loaded with incorrect **!ref** (**A1:M12** in this case, when it really should be **A1:L1577**), which makes working with the sheet very difficult. Why M12? I have no clue.
When WTF is set to true in XLSX.read, it throws following exception:
> **bad second format: .**

It may be a problem with the source file, but I am unable to change the way it is generated. When I open that file in MS excel and just save it (without any editing), issue disappears.
Or can it be a problem in the library?
Can you please identify the problem cause here? Thank you!

J.

**Comment by SheetJSDev** [comment]
The file self-reports that the range of the first worksheet is A1:M12.  Excel is apparently ignoring the self-reported range.  To fix it, use the `update_sheet_range` function from https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions#updating-worksheet-range
