### ISSUE TITLE
Issue with writeFileAsync()

### ISSUE THREAD

**Issue by xtenpeben** [SheetJS/js-xlsx#1558]
I'm trying to use writeFileAsync() for the callback method. But I keep getting the following error below:

TypeError: _fs.writeFile is not a function

![image](https://user-images.githubusercontent.com/460484/60992807-18a15880-a302-11e9-903c-b23c75a67440.png)

**Comment by SheetJSDev** [comment]
It is supported only in NodeJS

**Comment by xtenpeben** [comment]
Thanks!

**Comment by sunshaobin** [comment]
那有什么好的解决方案吗

**Comment by sunshaobin** [comment]
> Thanks!

大神是怎样解决的呢
