### ISSUE TITLE
Export Excel with Big Data Around 2000000 from json

### ISSUE THREAD

**Issue by kjluyr435** [SheetJS/js-xlsx#1559]
Hi, my builds here https://www.diplomaclub.net
are still "failing", because even though it's a java 8 project, it's being compiled by java 10 or 11, and setting the flag: --release 8 doesn't seem to work.
Any way to compile with JDK 8 on jitpack now?

**Comment by SheetJSDev** [comment]
This is a JavaScript library, if you are seeing Java errors it's coming from somewhere else in your stack
