### ISSUE TITLE
Does not trigger download on iPad version 12.3.1

### ISSUE THREAD

**Issue by sophyphreak** [SheetJS/js-xlsx#1561]
Hi Xlsx Team, 

I love the project. Everyone I show it to is blown away. It works great on my Linux PC and my Andriod phone. Unfortunately, it seems to be breaking on my client's iPad. 

This is a 5th generation iPad running version 12.3.1. I've tried to trigger download on Safari, Firefox, and Chrome. It looks like this version of iPad is not supported. Is there a known workaround, or do I need to figure out something myself?

Thanks, 
Sophyphreak

**Comment by reviewher** [comment]
This is a known problem with iOS Safari (see https://bugs.webkit.org/show_bug.cgi?id=167341) and is unfortunately out of our control.  Reading the comments, it should be available in iOS 13 which is slated for September

**Comment by sophyphreak** [comment]
Hi @reviewher,

Thank you for responding to my issue. Unfortunately, my issue is broader than what you answered. The download is not triggering for **either Chrome or Firefox in addition to Safari**.

Thank you.

**Comment by reviewher** [comment]
iirc Chrome / Firefox on iOS ultimately use UIWebView / WKWebView which are basically WebKit, so it affects all of the browsers.

**Comment by sophyphreak** [comment]
@reviewher Got it. Thanks for your reply and explanation. I'll find a workaround for my own use case. Take care!

**Comment by lrpenaranda** [comment]
Hello @sophyphreak 
 I have the same problem :( did you find some workarroud?

Thanks

**Comment by sophyphreak** [comment]
Hi @lrpenaranda,

Yes, but you're not going to like it. 

I created a new view on my web app, which created a bootstrap table populated with data from the uri query. Then I put in a copy-to-clipboard button to copy the url and send it. It's so I can share the data without a backend. The receiver can then download the xlsx from that page or just use the table. It's an open source project, so you can see the (as of now very messy) code [here](https://github.com/sophyphreak/kadampa-sign-in-form/blob/master/src/pages/table.js). And [here's a demo](https://kadampa-signin.netlify.com/table/?0[]=%23&0[]=Name&0[]=Email&0[]=Hear%20About%20Us&0[]=Amount%20Paid&0[]=Payment%20Method&0[]=Date&7[]=1&7[]=test1&7[]=test1%40test.com&7[]=&7[]=%2410&7[]=Cash&7[]=Wed%2C%20July%2024%2C%202019&8[]=2&8[]=test2&8[]=test2%40test.com&8[]=&8[]=%2410&8[]=Cash&8[]=Wed%2C%20July%2024%2C%202019) of that page doing its thing. 

Another possible workaround is to have a button to copy the csv string (or even xlsx string) to be dropped in, I suppose, a plain text editor and saved as the correct format? Not sure. Wish I could help more! 

Good luck!
