### ISSUE TITLE
JS Array to Excel file

### ISSUE THREAD

**Issue by MikhailTatsky** [SheetJS/js-xlsx#157]
Please give me advice.
I need the smallest code to generate from JavaScript array Excel file.
As I see in code of SheetJS, it is about 200 kbs of min for that.

**Comment by SheetJSDev** [comment]
If you just need a file that can be processed by excel, you could generate a CSV.   There are plenty of javascript CSV encoders.  We probably could generate a specific build that only contains the write code.

**Comment by reviewher** [comment]
Closing as dup of https://github.com/SheetJS/js-xlsx/issues/243
