### ISSUE TITLE
Excel download not working on Lightning Experience

### ISSUE THREAD

**Issue by pessimca** [SheetJS/js-xlsx#1572]
I have implemented Excel Download functionality using JS XLSX library and my implementation is:
1. Aura Component has used library to donwload the file
2. VF page uses Lightning.Use to call Aura Component

This implementation is working great on Classic but it is failing when switch to Lightning Experience.

Getting below error: 
navEventManager.js:27 Not allowed to load local resource: blob:

Note: Excel downloading is working when i use Aura Component directly on Lightning Page.

Is there anything issue with Lightning Locker Service? Is this library compatible for Locker service? Please share your comments.

Appreciate your help on this issue.

**Comment by SheetJSDev** [comment]
This issue is better directed at SalesForce, as they likely have a workaround for generating a download. 
 If you need to get the result as a Base64 string, use `write`:

```js
var base64string = XLSX.write(wb, {bookType: 'xlsx', type: 'base64'});
```

Please reach out to them and let us know if you hear back.
