### ISSUE TITLE
Cannot find file in the device after export file using the example

### ISSUE THREAD

**Issue by Exeexe93** [SheetJS/js-xlsx#1573]
Hi,

I could not find any excel file in xlsx format in my device after I press the export data button using the example in [react-native.js](https://github.com/SheetJS/js-xlsx/blob/master/demos/react/react-native.js). Although it shows that it is being exported to /data/user/0/com.test/files/sheetjsw.xlsx in the alert after pressing the button.

Anyone can help with this issue? Thanks!

**Comment by SheetJSDev** [comment]
The demo uses [`react-native-fs`](https://github.com/itinance/react-native-fs/#usage-android) see the "Usage (Android)" section for more details on setting up the project.  You're probably running into an issue that is better resolved with that project;
