### ISSUE TITLE
Meteor server side empty import

### ISSUE THREAD

**Issue by tropa** [SheetJS/js-xlsx#1577]
Hello. When I try to do an example app for meteor, on server side I get empty object as a result of import xslx, but client side it works as expected.  Google cannot help.  Please, tell me what is wrong?

**Comment by SheetJSDev** [comment]
Did you try the demo at https://github.com/SheetJS/js-xlsx/tree/master/demos/meteor ? clone the repo, go to `/demos/meteor` and run `make init && make`.  That demo imports in both the browser and the server

**Comment by tropa** [comment]
I have resolved this issue, it was due to npm cache. I removed node_modules in project folder, then made npm cache clean --force and then npm install. All works as expected.
