### ISSUE TITLE
jszip is not a constructor

### ISSUE THREAD

**Issue by daviceitor** [SheetJS/js-xlsx#1578]
Hi!
I installed the library with `jspm install SheetJS/js-xlsx`

When I tried to write the file, I got the error jszip is not a constructor. 
Code attached below:

```
import * as XLSX from 'SheetJS/js-xlsx';

var workBook = XLSX.utils.book_new();
workBook.SheetNames.push('Sheet 1');
var workSheet = XLSX.utils.aoa_to_sheet(table.table);
workBook.Sheets['Sheet 1'] = workSheet;

XLSX.write(workBook, { bookType: 'xlsx',  type: 'binary' });
```
Seems like it's a problem with the loading of the jszip library. 
Any idea?

**Comment by SheetJSDev** [comment]
Was unable to get the install to work:

```
$ jspm install SheetJS/js-xlsx
err (jspm) No resolution found for npm:@github:SheetJS/js-xlsx.
```

However, using `xlsx` directly worked:

```
$ node `which jspm` install xlsx
```

To make everything else work, use the default import:

```js
import XLSX from 'xlsx';

var workBook = XLSX.utils.book_new();
workBook.SheetNames.push('Sheet 1');
var workSheet = XLSX.utils.aoa_to_sheet([[1,2,3],["a","b","c"]]);
workBook.Sheets['Sheet 1'] = workSheet;

XLSX.writeFile(workBook, "out.xlsx", { bookType: 'xlsx',  type: 'binary' });
```

You're likely stumbling upon a `jspm` bug, raise an issue with them at https://github.com/jspm/jspm-cli/issues
