### ISSUE TITLE
readFile get wrong formula (columns offset)

### ISSUE THREAD

**Issue by staperney** [SheetJS/js-xlsx#1579]
Hi,
I have a strange behavior when reading an excel file. 
When I open the file and save it with my version of Excel, the file is properly read with xlsx.
However, when I do not touch it and read it with xlsx, some formulas are offseted. 
Here is an example: I read my excel file and focus on cell O124.
Before opening it and saving it (without doing any modification), here is what I get in cell O124:

`{ t: 'n',
  v: 18202.970297029704,
  f: 'O124*(1+P144)*(1+P$146)',
  w: '18,203',`

Of course, there is here a circular reference (on O124). The P144 and P146 are also shifted.
However, when I open it and save it with Excel (I am using Excel 2019), I can see the formula is N124 and not O124 (so no circular reference). 
Here is he result:

`{ t: 'n',
  v: 18202.970297029704,
  f: 'N124*(1+O144)*(1+O$146)',
  w: '18,203',`

I have correctly the N124, O144 and O146.

I really do not understand why there is a shift when I do not "resave" my file first. 
Would you have any ideas?

Thanks a lot for your help!

**Comment by SheetJSDev** [comment]
Can you share the original file?  If you don't want to share publicly, feel free to send by email to dev@sheetjs.com

**Comment by staperney** [comment]
Hi, Unfortunately that is for my work so I cannot share the file event privately. How could I work on it to give you the maximum information?

**Comment by SheetJSDev** [comment]
XLSX files are ultimately ZIP files, so rename the file with a .zip extension, extract it, and share the `xl/worksheets/sheet##.xml` files.  If you take a look at the files directly, the numbers and formulae will be there but the text should not (those are generally stored in a `sharedStrings.xml` file and the worksheets merely reference the shared string table).  If you're concerned about leaking numbers as well, just do a string replace `str.replace(/<(?:\w*:)?v[^>]*>([\s\S]*?)<\/(?:\w+:)?v>/g, "")`

**Comment by BDLCapital** [comment]
Hi, I have sent you the xml via email.

**Comment by staperney** [comment]
Thanks a lot for your help. It works correctly with version 0.14.4 indeed.
For other people who read this, it is linked to shared formulae. It is solved using version 0.14.4 of the package.
