### ISSUE TITLE
EOMONTH function gives SH33TJSERRX(O8,12)

### ISSUE THREAD

**Issue by staperney** [SheetJS/js-xlsx#1581]
Hi,
I am reading an XLS file. On one cell, I have a end of month function. However, the .f value renders a SH33TJSERRX function instead of EOMONTH. 
If I open the file and save it in xlsx, it gives me correctly the EOMONTH.

Is there a way to correct that?

Thanks a lot!

**Comment by SheetJSDev** [comment]
Can you share that file?  https://portal.sheetjs.com/EOMONTH.xls was generated in Excel 2019 and the formula is correctly parsed
