### ISSUE TITLE
HTML table to xslx without spans

### ISSUE THREAD

**Issue by rthill** [SheetJS/js-xlsx#1584]
Is there a possibility to export HTML tables ignoring rowspan and colspan parameters?
I have some exportable tables which make use of rowspan and colspan for nicer presentation in the browser, but would love to export everything into the Excel file for further processing.

**Comment by SheetJSDev** [comment]
https://html.spec.whatwg.org/multipage/tables.html#the-td-element `colspan` is "Number of columns that the cell is to span".

https://support.office.com/en-us/article/merge-and-unmerge-cells-5cbd15d5-9375-4540-907f-c673a93fcedf "Merging combines two or more cells to create a new, larger cell. This is a great way to create a label that spans several columns."

They are the same concept, it's unclear why you would want to intentionally lose that metadata.  If you can give a concrete example we'll reconsider
