### ISSUE TITLE
How do I export excel and set up drop-down projects

### ISSUE THREAD

**Issue by bubinyang** [SheetJS/js-xlsx#1587]
How to export excel and set the drop-down items. For example, when the exported column is "male" and "female", there is a drop-down option when excel opens, and the values of the options are 1 and 2. In this case, only a new column can be created to store the male and female code, and the male and female code column can be manipulated to change the value of the male and female code column.For help

**Comment by SheetJSDev** [comment]
This is called "data validations" and is part of our Pro offering, see https://sheetjs.com/pro for more info

**Comment by bubinyang** [comment]
> 这称为“数据验证”，是我们Pro产品的一部分，有关详细信息，请参阅https://sheetjs.com/pro

Specific where can you see the relevant illustration case
