### ISSUE TITLE
Richt text in json

### ISSUE THREAD

**Issue by fridzema** [SheetJS/js-xlsx#1588]
Hello, 

I am trying to get richt text back from `XLSX.utils.sheet_to_json`

This works and shows words bold etc.
![Screenshot 2019-08-05 at 15 55 50](https://user-images.githubusercontent.com/8180660/62470076-e9172c00-b799-11e9-9376-b1ce837f9af9.png)

```js
          var htmlstr = XLSX.write(workbook, {
            sheet: sheet,
            type: 'string',
            bookType: 'html',
          });

          vm.$refs.spreadsheet.innerHTML += htmlstr;
```

This doesn't work and returns just the text without bold elements, playing with raw settings does not seem to help either.
![Screenshot 2019-08-05 at 15 56 04](https://user-images.githubusercontent.com/8180660/62470075-e9172c00-b799-11e9-96a4-35a867d6b367.png)

```js
        var result = {};
        workbook.SheetNames.forEach(function(sheetName) {
          result = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], {
            header: 1,
            raw: true,
          });

        });

        console.log(result);
```

**Comment by SheetJSDev** [comment]
This is part of our Pro offering, see https://sheetjs.com/pro for more info
