### ISSUE TITLE
0.15 changes / release notes?

### ISSUE THREAD

**Issue by avindra** [SheetJS/js-xlsx#1594]
The changes don't seem to be documented.... here is a link to a diff for anyone else who is looking

https://github.com/SheetJS/js-xlsx/compare/v0.14.0...4aeb0a786a6177cd5176dc08c7827a2cae4da3f6

**Comment by SheetJSDev** [comment]
We'll go back and repopulate the CHANGELOG, but the changes are listed in the actual git log.  The relevant code (excluding docs and demos) changes:

v0.14.1:
- raw cell objects can be passed to `sheet_add_aoa`
- `_FilterDatabase` fix for AutoFilter-related crashes (#1262)
- `stream.to_json` doesn't end up accidentally scanning to max row (#167)

v0.14.2:
- Proper encoding of comments (#1468)

v0.14.3:
- Issue with how shared formulae were shifted (#1388)

v0.14.4:
- Better treatment of `skipHidden` in CSV output (#1508)
- Ignore CLSID in XLS (#1419)
- SYLK ANSI encoding (#1544) 
- codepage integration for DBF and SYLK

v0.14.5:

- XLS PtgNameX record parse looks at XTI struct (#1581) 
- XLS always create stub cells for blank cells with comments (#1567)

v0.15.0:

- `dist/xlsx.mini.min.js` mini build with XLSX read/write and some utilities
- Removed some legacy conversion utility functions (this is why we bumped to 0.15.0)
