### ISSUE TITLE
Import only methods I need

### ISSUE THREAD

**Issue by dbaronov** [SheetJS/js-xlsx#1596]
Hello,

I am using this library and it is really good, but quite heavy indeed! The minified version is about a megabyte is size.

Is there any way to only import methods / objects I actually use?
Here is the list of what's in use from the whole library:

```
xlsx.read();
singleCountryChartXlsx2json.utils.sheet_to_json();
```

**Comment by SheetJSDev** [comment]
The largest component is a focused [`codepage` build](https://github.com/sheetjs/js-codepage), which is required for supporting XLS and other older formats.  XLS and many legacy formats are older than Unicode and possibly older than you, so correct support for reading those files requires a series of LUTs that we have to ship.  It's definitely possible to carve out smaller subsets for specific tasks

The mini build, added in 0.15.0, includes XLSX read/write support, HTML TABLE support, the utilities and a few other goodies.  Stripping out the support components for older formats lets us reduce the size to ~180KB minified, ~60KB gzipped.  You can add that in a direct script tag injection or require/import the script from the `dist` directory.

If you just needed to export from an HTML table to XLSX (HTML ingress and XLSX egress), then it would be possible to make a smaller build.  However, the `XLSX.read` entry point [must kno all of the supported file formats](https://github.com/SheetJS/js-xlsx/blob/master/bits/87_read.js#L83) and touches most of the code!

**Comment by dbaronov** [comment]
> The mini build, added in 0.15.0, includes XLSX read/write support, HTML TABLE support, the utilities and a few other goodies. Stripping out the support components for older formats lets us reduce the size to ~180KB minified, ~60KB gzipped. You can add that in a direct script tag injection or require/import the script from the `dist` directory.

I have followed your instructions and  required the core file like this: require('../../../node_modules/xlsx/dist/xlsx.core.min.js'); which resulted in an error in my console: 

```
site.js:1 Uncaught TypeError: a is not a constructor
    at e.initRadarChat (site.js:1)
    at e.prepareRadarData (site.js:1)
    at e.getLocalData (site.js:1)
    at e.handleDataSource (site.js:1)
    at new e (site.js:1)
    at site.js:1
    at Array.forEach (<anonymous>)
    at Object.70.../../../node_modules/xlsx/dist/xlsx.core.min.js (site.js:1)
    at c (site.js:1)
    at site.js:1
```

What am I doing wrong?
