### ISSUE TITLE
International characters broken in deployment

### ISSUE THREAD

**Issue by seantai** [SheetJS/js-xlsx#1597]
Is there a version of, say, xlsx.full.min.js, without international characters (Chinese, Japanese, Korean, etc.)? These are breaking my site when I deploy it in an environment that can't handle those characters. Thanks!

**Comment by SheetJSDev** [comment]
Can you share a file?

**Comment by seantai** [comment]
I was just using bower to depend on https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.full.min.js in my project; no special files were written. When that file got built into my webapp (we're using grunt) and deployed, the deployment environment our app is hosted in (I don't know the specifics of their system) served an invalid JS file to the browser. It's because of lines like
`case 'table': case '工作表': // 9.1.2 <table:table>`
that have international/non-unicode characters. For now, I've created my own version of the file with those characters removed and added that to our project, outside of bower. That fixed the issues. I added the license attribution to the new file, as well as a comment explaining what I changed in the file. Please let me know if there's anything else I should do with the file in terms of licensing.

**Comment by SheetJSDev** [comment]
That hosting environment is probably not handling JS properly, you are best off investigating why they aren't serving JS (there might be a simple setting)

**Comment by seantai** [comment]
Yep, I think that's definitely true. I'm working with the team in charge of the hosting environment to see if they can change things on their end. Thanks for the responses and for the cool library!
