### ISSUE TITLE
Chrome - strange file name with no file extension.

### ISSUE THREAD

**Issue by VMaklaud** [SheetJS/js-xlsx#1599]
Hi!
I'm new to SheetJS and finally I have it working with html table -> excel exporting, but my files have strange names and no 'xlsx' ext.

`
const workbook = XLSX.utils.table_to_book(table, { sheet: "regions" });
// Some data modifications here...

var options = {
	bookType: 'xlsx',
	bookSST: false,
	type: 'base64'
};

XLSX.writeFile(workbook, "file.xlsx", options);
XLSX.writeFile(workbook, "file.xlsx");
`

I try different writeFile versions - with and without options, with file name taken from <input type="file"/> and hardcoded "file.xlsx". After this code is done I have a file like "89eef6c4-3a5a-44f2-a512-61dad26bfdcf" in my Downloads folder (working on Ubuntu). If I rename it to "89eef6c4-3a5a-44f2-a512-61dad26bfdcf**.xlsx**" manually, I can open it via Excel or LibreOffice Calc and it contains my data. But I need it to take my file name and extension.
What's wrong in my code?

PS I saw this post https://github.com/SheetJS/js-xlsx/issues/1415, it doesn't help.

Thanks!

**Comment by VMaklaud** [comment]
Well, I solved the problem using write and saveAs. I didn't want to use them, but it seems I have to.

**Comment by reviewher** [comment]
What browser / OS are you using, and can you share a reproduction?

**Comment by VMaklaud** [comment]
Well, I already told it's Ubuntu and Chrome. And my code is above. Anyway, it doesn't matter now. Maybe the problem is in writeFile method - maybe it doesn't allow to choose a file name.

**Comment by aabuhijleh** [comment]
Facing the same issue @VMaklaud can you please share how you solved it exactly?

**Comment by SheetJSDev** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=373182 we might need to add a CORS workaround.  Is there a simple way to reproduce this issue?

**Comment by aabuhijleh** [comment]
@SheetJSDev The `writeFile` function was working in our case, then recently we started having this issue. Not sure why we _only recently_ started having it as I don't think we changed anything.

Anyway, if someone else is having this issue, this is working

```js
import FileSaver from 'file-saver'

const EXCEL_FILE_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8'

const excelBuffer = XLSX.write(workbook, {
  type: 'array',
  bookType: 'xlsx'
})
const fileData = new Blob([excelBuffer], { type: EXCEL_FILE_TYPE })
FileSaver.saveAs(fileData, fileName)
```

**Comment by SheetJSDev** [comment]
Can you test if https://jsfiddle.net/srqzu5v2/ generates a file named "issue1599.xlsx"?  It's a super simple export:

```js
XLSX.writeFile(XLSX.read("a,b,c\n1,2,3"), "issue1599.xlsx");
```

**Comment by aabuhijleh** [comment]
@SheetJSDev  Ok, I've discovered something strange

Using this line

```js
XLSX.writeFile(XLSX.read("a,b,c\n1,2,3"), "issue1599.xlsx");

```
In the project, it produces the same bug and downloads a file with a bad name/extension like this `5d5e2013-e701-44c1-938d-03bd05b2acae`

If I just add this import

```js
import FileSaver from 'file-saver'
```

Even without using `FileSaver` anywhere (just imported) the same `writeFile` line works and downloads a file named `issue1599.xlsx` correctly

file-saver just has to be imported 🤔 I'm thinking this package adds something to the global scope? Not sure what's happening 😅

**Comment by aabuhijleh** [comment]
So, `file-saver` adds a `saveAs` function to the global scope

and the `xlsx` package uses that function instead of creating an anchor tag, appending it to the body and triggering a click.

So, the `saveAs` function from `file-saver` is working well and that's the reason!

**Comment by SheetJSDev** [comment]
`saveAs` was originally part of the ["File API: Writer" proposed API for writing files in the web](https://dev.w3.org/2009/dap/file-system/file-writer.html).

Under the hood, [`writeFile` will use that API if available](https://git.sheetjs.com/sheetjs/sheetjs/src/branch/master/bits/19_fsutils.js#L32).

[FileSaver.js adds `saveAs` to the global scope, which is why the library seems to work if you just import the dependency](https://github.com/eligrey/FileSaver.js/blob/master/src/FileSaver.js#L168)

We're unable to reproduce the overall issue locally.  Any additional details (preferably a public demo) would help identify why it is not working in your deployment.

**Comment by aabuhijleh** [comment]
@SheetJSDev Thank you very much for the thorough explanation and your help 🙏. If I'm able to create a public demo which reproduces this issue, I will definitely share it.

**Comment by SheetJSDev** [comment]
Can you test if your FileSaver-based exports work if you change the mime type?  Under the hood, `writeFile` constructs a blob with [`"application/octet-stream"`](https://git.sheetjs.com/sheetjs/sheetjs/src/branch/master/bits/19_fsutils.js#L28).  Specifically, we're curious if the following types work:

A) `const EXCEL_FILE_TYPE = 'application/octet-stream'` (equivalent of what SheetJS does)

A) `const EXCEL_FILE_TYPE = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'` (no charset)

**Comment by aabuhijleh** [comment]
As long as I have `file-saver` imported, using any of those types works. Using `writeFile` without setting any type also works well.

BTW, Is it out of the question for you to rely on `file-saver` for downloading files instead of using your own implementation?

**Comment by SheetJSDev** [comment]
[Added a note in the docs.](https://docs.sheetjs.com/docs/miscellany/errors#strange-exported-file-names-in-the-web-browser)

With the state of ESM in 2022, there's no standard way for one module to depend on another module in a way that works in NodeJS ESM, in Deno Modules, in the web browser using `script type="module"`, and in tools like ViteJS and Webpack.  The only techniques that currently work everywhere are "dependency injection" (like how we recommend [loading the codepage tables](https://docs.sheetjs.com/docs/getting-started/installation/frameworks#encoding-support)) and "globals" (e.g. what `writeFile` currently does)
