### ISSUE TITLE
Unable to get cell data

### ISSUE THREAD

**Issue by C-G-Walsh** [SheetJS/js-xlsx#1600]
When i run the following code i cannot get any value for the cells. I get a error saying that the .v keyword is undefined

code snip
var range = XLSX.utils.decode_range('!ref');
var worksheet = workbook.Sheets[workbook.SheetNames[0]];
var cellrefStart = XLSX.utils.encode_cell({ c:range.s.c, r:range.s.r});
var cellrefEnd = XLSX.utils.encode_cell({ c:range.e.c, r:range.e.r});
var start = worksheet[cellrefStart].v;
console.log(start);
var end = worksheet[cellrefEnd].v;
console.log(end);

error
Uncaught TypeError: Cannot read property 'v' of undefined

**Comment by reviewher** [comment]
The cell object may not exist if it has no value.  To confirm, log `worksheet[cellrefStart]` and `worksheet[cellrefEnd]`.
