### ISSUE TITLE
write_xlscfb is not defined

### ISSUE THREAD

**Issue by cuneydayla** [SheetJS/js-xlsx#1606]
Hi,

I am getting the error below while I am using xlsx.mini.min.js

> ReferenceError: write_xlscfb is not defined
    at Qs (xlsx.mini.min.js:7)
    at al (xlsx.mini.min.js:7)
    at Object.il (xlsx.mini.min.js:7)

 My code here is and it is working fine with xlsx.min.js or xlsx.full.min.js.

`    export(datas: Array<Array<string>>, fileName?: string): void {
        /* generate worksheet */
        const ws = XLSX.utils.aoa_to_sheet(datas);

        /* generate workbook and add the worksheet */
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws);

        fileName = fileName ? fileName + '.xls' : 'mydata.xls';
        /* save to file */
        XLSX.writeFile(wb, fileName);
    }`

is this how xlsx.mini.min.js should work or am I doing something wrong or is it a bug?
thanks in advance

**Comment by reviewher** [comment]
The mini build strips out XLS read and write support.  It only supports XLSX and the utility functions.

The part of the code that supports XLS, along with the required codepage dependency, is the most significant contributor to the size of the library.
