### ISSUE TITLE
Corrupted file when uploading to S3

### ISSUE THREAD

**Issue by morganzysman** [SheetJS/js-xlsx#1610]
Hi, 

I have been working on a demo, and i'm stuck so far.

-  I want to download and excel file from my bucket s3, tranform it to json --> Ok 
- Modify my json and tranform it back to excel --> Ok
- Download the file to my local computer to double check that is worked --> Ok
- Upload the modified file to my bucket s3 --> HS

I always get a corrupted file when downloading it back from my bucket s3.

Bellow is the code I use to generate / uplaod the file. I have been playing around with type, ContentType etc, but never solved the issue.

Any tips, is more than welcome, as I can't find a work around.

Regards,

PS: If i do the upload with a csv format it does work
Morgan
```
      const workbook = XLSX.utils.book_new();
      const worksheet = XLSX.utils.json_to_sheet(this.data, {
        header: ["lastName", "firstName"]
      });
      XLSX.utils.book_append_sheet(workbook, worksheet, "feuille1");

      const file = XLSX.write(workbook, {
        type: "buffer",
        bookType: "xlsx",
        bookSST: false
      });

      aws.config.update({
        accessKeyId: "xxx",
        secretAccessKey: "xxx"
      });
      const s3 = new aws.S3();

      try {
        const data = await s3
          .putObject({
            Bucket: "xxx",
            Key: "dataSample.xlsx",
            ACL: "public-read",
            ContentType:
              "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            Body: file
          })
          .promise();
        console.log("data", data);
      } catch (error) {
        console.log("errir", error);
      }
    }
```

**Comment by SheetJSDev** [comment]
This is a question better raised with the AWS folks, since it's really about uploading a Buffer.  Based on a cursory glance of https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#putObject-property , you might be able to push a base64 string (`type: "base64"` when writing, `ContentEncoding: "base64"` in the putObject params).  Please follow-up with what worked.
