### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [SheetJS/js-xlsx#1611]
I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file for GitHub Sponsors. This would allow a canonical address to send funds to. For example, projects could parse out the address and provide donation capabilities to the user.

**Comment by SheetJSDev** [comment]
It would be nice, but unless some outside entity is handling the logistics of ETH-USD it's probably a bigger headache than it is worth
