### ISSUE TITLE
js-xlsx exported XLS BIFF8 and Apache-POI XLS reading function compatibility issue

### ISSUE THREAD

**Issue by cordovapolymer** [SheetJS/js-xlsx#1612]
Dear SheetJS developers,

js-xlsx is incompatible with Apache-POI XLS reading function.
Here is a sample maven project which can be complied to instantly reproduce the error:
[poirun.zip](https://github.com/SheetJS/js-xlsx/files/3557512/poirun.zip)
When opening js-xlsx generated document with Apache-POI library a following error occurs:

`Exception in thread "main" java.lang.RuntimeException: Found EOFRecord before WindowTwoRecord was encountered
        at org.apache.poi.hssf.model.RecordOrderer.isEndOfRowBlock(RecordOrderer.java:430)
        at org.apache.poi.hssf.model.RowBlocksReader.<init>(RowBlocksReader.java:58)
        at org.apache.poi.hssf.model.InternalSheet.<init>(InternalSheet.java:181)
        at org.apache.poi.hssf.model.InternalSheet.createSheet(InternalSheet.java:122)
        at org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:354)
        at org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:400)
        at org.apache.poi.hssf.usermodel.HSSFWorkbook.<init>(HSSFWorkbook.java:381)
        at poirun.ApachePOIExcelRead.main(ApachePOIExcelRead.java:21)`

I have tried generating the file with bookSST set as true and false, what did not help. Also the target application for which I am generating this file only supports reading XLS BIFF8 files via Apache-POI API.

**Comment by SheetJSDev** [comment]
Thanks for sharing!  That error message suggests POI requires a Window2 record (window properties for the given sheet).  This situation is unclear:

- Excel accepts files without Window2 records
- The [official Binary File Format Validator](https://www.microsoft.com/en-us/download/details.aspx?id=26794) accepts files without Window2 records
- The [official specification](https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/a1b3d8b4-7442-41fd-9c57-bbd2a6394082) claims it is required.

It would seem the spec might be in error and that the record is indeed optional.  We have raised an issue with POI (https://bz.apache.org/bugzilla/show_bug.cgi?id=63708) and it is better to continue the conversation there.

**Comment by cordovapolymer** [comment]
@sheetjsdev as official specification requires Window2 it makes sense to create it with SheetJS, and add a flag which would allow to enable or disable this behavior.
Sometimes Sheetjs generated files crash Excel, this might be one of the causes.
For Apache POI a compatible way of handling this situation would be accept files with both Window2 records and without, just like Excel does.
Could you point me on the part in SheetJS source code which can be modified to enable Window2 creation?

**Comment by SheetJSDev** [comment]
It's written only if you specify view options, to force it to generate Window2 records you need to make 2 changes:

1) https://github.com/SheetJS/js-xlsx/blob/master/bits/78_writebiff.js#L212 the if statement should be changed as follows:

```diff
-	if(b8 && _WB.Views) write_biff_rec(ba, "Window2", write_Window2(_WB.Views[0]));
+	if(b8) write_biff_rec(ba, "Window2", write_Window2(_WB.Views[0]));
```

2) check the write_Window2 function in https://github.com/SheetJS/js-xlsx/blob/master/bits/39_xlsbiff.js#L356 and see if any of the defaults need to be changed.

**Comment by cordovapolymer** [comment]
Thank you for you reply,
I have found the solution which can be added to the Docs: wb.Workbook = { Views: ['Window2'] };
Can be added before calling XLSX.write, then Window2 is created and the file is successfully opened by Apache POI.

**Comment by cordovapolymer** [comment]
@sheetjsdev
Furthermore, if you try to add a new sheet with Excel 2016 to SheetJSTableExport.xls, Excel crashes.
When the file is generated with Window2 it does not crash in this situation.

**Comment by SheetJSDev** [comment]
Can you share a sample file where excel is crashing?

**Comment by cordovapolymer** [comment]
@sheetjsdev

It's the SheetJSTableExport.xls from your demos page. (also included in poirun.zip xls directory)

**Comment by davidfaj** [comment]
> Thank you for you reply,
> I have found the solution which can be added to the Docs: wb.Workbook = { Views: ['Window2'] };
> Can be added before calling XLSX.write, then Window2 is created and the file is successfully opened by Apache POI.

This solution helped me too, thanks @cordovapolymer!

**Comment by SheetJSDev** [comment]
To be sure, you could also write:

```js
if(!wb.Workbook) wb.Workbook = {};
if(!wb.Workbook.Views) wb.Workbook.Views = [];
```

and that would trigger the Window2 generation.

Please direct further comments to the Apache POI project https://bz.apache.org/bugzilla/show_bug.cgi?id=63708 .

@cordovapolymer we'd accept a PR that makes the change in step 1 from https://github.com/SheetJS/sheetjs/issues/1612#issuecomment-526530072
