### ISSUE TITLE
Write or append data  to an Existing excel file say in assets folder of angular

### ISSUE THREAD

**Issue by manojkrsna** [SheetJS/js-xlsx#1615]
var Excel = require('exceljs');
var workbook = new Excel.Workbook();
let url = "/assets/resources/template.xlsx";
workbook.xlsx.readFile(url )
    .then(function() {
        var worksheet = workbook.getWorksheet(1);
        var row = worksheet.getRow(5);
        row.getCell(1).value = 5; // A5's value set to 5
        row.commit();
        return workbook.xlsx.writeFile(url);
    })

**Comment by SheetJSDev** [comment]
This is the repo for a different project, you probably meant to ask https://github.com/exceljs/exceljs/issues
