### ISSUE TITLE
How to load data excel file when click a button?

### ISSUE THREAD

**Issue by dacoten** [SheetJS/js-xlsx#1617]
Hey all,
I get an error when click button to load data from excel file. Error is:

> fs.readFileSync is not a function
>     at read_binary (xlsx.js?1146:2628)
>     at readSync (xlsx.js?1146:20402)
>     at Object.readFileSync (xlsx.js?1146:20430)
>     at VueComponent.mounted (CountryCard.vue?174c:32)

Vuejs code:
```
 import XLSX from 'xlsx';
 mounted: function(){
   var workbook = XLSX.readFile('./data.xlsx');
}
```
 Please help me. Thank you so much.

**Comment by SheetJSDev** [comment]
`readFile` is not supported in the browser due to security sandbox.  You have to use one of the approaches laid out in https://github.com/SheetJS/js-xlsx/blob/master/README.md#parsing-workbooks
