### ISSUE TITLE
workbook props are not read correctly - in particular: date1904

### ISSUE THREAD

**Issue by rpbouman** [SheetJS/js-xlsx#1619]
Hello, 

We noticed that we cannot pickup the date1904 workbook property. The value is always '0' whereas we are sure the workbook stores it as '1'. Sample workbook attached.

Most likeley reason is this line:

https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.js#L14614

`switch(strip_ns(y[0])) {`

Namespace information is stripped. I extracted the workbook, it turns out that my xl/workbook.xml contains two `<workbookPr>` elements, the first one is in the `http://schemas.openxmlformats.org/spreadsheetml/2006/main` namespace; the second is in the `http://schemas.microsoft.com/office/spreadsheetml/2010/11/main` namespace.

Initially the intended workbook properties are parsed correctly from the `<workbookPr>` in the `http://schemas.openxmlformats.org/spreadsheetml/2006/main` namespace, but then the occurrence of second `<workbookPr>` undoes all the previously collected properties.

The workbook was created with MS excel. Version info attached.
![image](https://user-images.githubusercontent.com/647315/64525444-2e7eca00-d301-11e9-892b-f6dce1cb24a8.png)
[test_1904.xlsx](https://github.com/SheetJS/js-xlsx/files/3590079/test_1904.xlsx)

**Comment by SheetJSDev** [comment]
To be clear, the assignment is defensive and the presence of the second tag does not affect the result.  Reproducing the code segment (starting line 14631):

```js
			/* 18.2.28 workbookPr CT_WorkbookPr ? */
			case '<workbookPr':
			case '<workbookPr/>':
				WBPropsDef.forEach(function(w) {
					if(y[w[0]] == null) return;
					switch(w[2]) {
						case "bool": wb.WBProps[w[0]] = parsexmlbool(y[w[0]]); break;
						case "int": wb.WBProps[w[0]] = parseInt(y[w[0]], 10); break;
						default: wb.WBProps[w[0]] = y[w[0]];
					}
				});
				if(y.codeName) wb.WBProps.CodeName = y.codeName;
				break;
			case '</workbookPr>': break;
```

The first tag is `<workbookPr date1904="1" defaultThemeVersion="166925"/>` and the second tag is `<x15:workbookPr chartTrackingRefBase="1"/>`.  Once the loop hits the expected `date1904` field, in the first tag it sees a value (`y[w[0]] == "1"`) and in the second tag it does not see a value (`y[w[0]] == void 0`) so the assignment will not be lost.

Are you possibly running an older version?  You can log `XLSX.version`, and should expect to see something like 0.15.1.  According to Excel, C2="1/2/22", C3="1/2/23 10:00", C4 = "3/1/04", exactly what you see if you click-drag the file into the demo https://oss.sheetjs.com/js-xlsx/ .  Furthermore, you can inspect the workbook object in the console (it's exposed as the variable `global_wb`) and verify that `global_wb.Workbook.WBProps.date1904` is indeed `true`

**Comment by rpbouman** [comment]
my bad, we are indeed using an older version. We will try to upgrade and see if that fixes the problem.

That said - discarding the namespace when parsing xml can't be a good idea, ever?

**Comment by SheetJSDev** [comment]
If you are still seeing this issue in the latest version, feel free to follow up and we'll reopen
