### ISSUE TITLE
Excel HTML files with tags inside cells results in extra white spaces

### ISSUE THREAD

**Issue by KurtMar** [SheetJS/js-xlsx#1622]
When parsing Excel HTML files, the _htmldecode_ function strips new lines from the beginning and end of the cell. If there are HTML elements like DIV or SPAN inside the cell, then new lines before and after the content will be transformed into whitespaces. Here is a jsbin example showing the problem and a possible solution:

https://jsbin.com/muzucuyigo/edit?js,console

The solution of checking for <\s and \s> is not optimal, but is in my opinion better than the current implementation.

**Comment by SheetJSDev** [comment]
#1650 closes this issue
