### ISSUE TITLE
React-Native example don't write file in directory

### ISSUE THREAD

**Issue by Gastonovich** [SheetJS/js-xlsx#1628]
RN version 0.60
while working, create new workbook, new sheet, convert to binary and using fs to write ascii in DocumentDirectoryPath xlsx file, but nothing is happen
trying official example https://github.com/SheetJS/js-xlsx/blob/master/demos/react/react-native.js, it says that file succ created, but it's not true

**Comment by SheetJSDev** [comment]
Thanks for reporting!  Likely you're seeing an issue with [`react-native-fs`](https://github.com/itinance/react-native-fs) .  Can you confirm whether their [write example](https://github.com/itinance/react-native-fs#file-creation) works?  If so, how are you testing (device or simulator, android or IOS)?

**Comment by Gastonovich** [comment]
Oh, writing example writing that successful but no files on directory still 
Testing on real device connected via usb 
install react-native-fs  via link and adding some strings in build.grandle and settings.grandle
