### ISSUE TITLE
XLSX saved as XLSB under the hood

### ISSUE THREAD

**Issue by Silon** [SheetJS/js-xlsx#1637]
**xlsx: 0.14.3**

After save xlsx file everything looks ok but after check exif data file has type xlxb:

**My code:**
`xlsx.writeFile(wb, `${filename}.xlsx`, { type: 'string', bookType: 'xlsx' });`

<img width="962" alt="Screenshot 2019-09-24 at 09 41 46" src="https://user-images.githubusercontent.com/3192612/65491964-5e58d080-deb0-11e9-9907-90ff1343864e.png">

Look that these three lines:
_File Type : XLSB
File Type Extension: xlsb
MIME Type: application/vnd.ms-excel.sheet.binary.macroEnabled_

Why my file is generated as xlsb type and how to change/solve it?

Thanks!

**Comment by SheetJSDev** [comment]
This is an issue with how `exiftool` resolves OPC files, so we [raised an issue with them](https://github.com/exiftool/exiftool/issues/27)
