### ISSUE TITLE
global leak detected: cptable

### ISSUE THREAD

**Issue by TarSzator** [SheetJS/js-xlsx#164]
Hello,

I just tried to use xlsx in a project of mine.
After trying to run my mocha test suite I got the error: "global leak detected: cptable" detected.
I found the source in the /xlsx.js file of this module. Line 9.

Can you please fix and release a new version.

Thanks.

**Comment by tuhoojabotti** [comment]
:+1: Found this error in our mocha tests, would be nice to avoid globals.

**Comment by reviewher** [comment]
This is intentional, see https://github.com/SheetJS/js-xlsx/issues/385#issuecomment-272660734
