### ISSUE TITLE
request for mini build

### ISSUE THREAD

**Issue by bagaskarala** [SheetJS/js-xlsx#1640]
Are this plugin available in separate module build or mini build? im just using this module to export to xlsx, but its size is huge so my app load slowly

**Comment by fchiumeo** [comment]
[Optinional modules](https://github.com/SheetJS/js-xlsx/tree/master/misc/docs#optional-modules) has a mini build version

**Comment by SheetJSDev** [comment]
It's included in the repo and the npm package.

CDN: https://unpkg.com/xlsx@0.15.1/dist/xlsx.mini.min.js

To use in a bundler, require `xlsx/dist/xlsx.mini.min` directly (the full build is still the default, you have to reference the mini script directly)

**Comment by bagaskarala** [comment]
thank youu
