### ISSUE TITLE
it is not writing more than 136 lines 

### ISSUE THREAD

**Issue by sibelius** [SheetJS/js-xlsx#1642]
```jsx
import * as XLSX from 'xlsx';

export type Sheets = {
  ws: XLSX.WorkSheet;
  name: string;
};
const buildXlsxFile = async (sheets: Sheets[]) => {
  const wb = XLSX.utils.book_new();

  for (const sheet of sheets) {
    XLSX.utils.book_append_sheet(wb, sheet.ws, sheet.name);
  }

  return await XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
};
```

I can see `A155` on `XLSX.WorkSheet`, but it only goes to `136` lines in the sheet

is there a better way to generate a `XLSX` to upload to s3?

**Comment by sibelius** [comment]
it looks like this is a bug on mac Numbers, it works well on Google Drive

**Comment by SheetJSDev** [comment]
Can you share the original file?  Likely the sheet is reporting a range of something like A1:B136

**Comment by sibelius** [comment]
I'm gonna share this, as I don't think as it works on excel and google sheets

maybe a Numbers problem

I can share later on, if this happens again

tks for this package

**Comment by SheetJSDev** [comment]
I'd definitely like to take a closer look (it might be indicative of another issue).  If you do feel like sharing but don't want to do it publicly, feel free to email us at oss@sheetjs.com
