### ISSUE TITLE
dates from date format always convert the text format

### ISSUE THREAD

**Issue by CNzxy0820** [SheetJS/js-xlsx#1645]
I want use datas of excel to generate a chart from echarts,but when I import the excel to echarts, the date data,such as "2019.9.22 16:22" was converted to "43730.682291666664".because my English is very poor ,if my description is not clear,could you please tell me your e-mail, I will send some picture to you , I want someone could help me or tell me some methods.Thanks!!!

**Comment by CNzxy0820** [comment]
ok,I have already solved my problem, this problem took my a week, just change this js release to "v0.11.5"

**Comment by SheetJSDev** [comment]
If you need the original date as a JS date object, pass the option `cellDates: true`.  If you need the original formatted string, it is attached to the `.w` field of the cell and you can get the string by passing the option `raw: false` to `sheet_to_json`.

**Comment by CNzxy0820** [comment]
Thanks for your answer,I am very excited!!!

**Comment by SheetJSDev** [comment]
The reason older versions seemed to "fix" the problem is the default for `raw`.  In older builds, `sheet_to_json` would use the text value.  We flipped it, so now default is the raw values and you need to pass `raw: false` to get the old behavior.  See https://docs.sheetjs.com/#json

**Comment by CNzxy0820** [comment]
ok,I will try what you said now.Thank you!
