### ISSUE TITLE
Formatting (using json_to_sheet)

### ISSUE THREAD

**Issue by dzimukairu** [SheetJS/js-xlsx#1648]
Hi. I would to ask is it possible empty rows then format it?

This is the sheet file that created by XLSX

![image](https://user-images.githubusercontent.com/27992091/66023509-f8112500-e523-11e9-92a4-d422dcf53e1b.png)

but i want it to be formatted like this. how to insert empty rows then insert something in the cells.

![image](https://user-images.githubusercontent.com/27992091/66023492-ec256300-e523-11e9-8043-00b668bff560.png)

**Comment by SheetJSDev** [comment]
At its infancy, SheetJS was envisioned as a solution to a specific problem involving reading data from various file formats. A bunch of default options are related to the fact that the original target was generating CSV (so by default, all values are processed by the number formatter).

We are unsure when the open source build will expand scope, but in the short term the main focus is data processing. We offer extended functionality (like the styling depicted in your screenshot) in a separate paid offering as described in https://sheetjs.com/pro

**Comment by dzimukairu** [comment]
i just want to ask how to insert empty rows. like i want to start at a selected cell (not A1 but but instead on A8 cell)

![image](https://user-images.githubusercontent.com/27992091/66090145-b67c8a80-e5b4-11e9-92cd-31f3b9f272fc.png)
