### ISSUE TITLE
We found a problem with some content in <filename.xslx> Office 365

### ISSUE THREAD

**Issue by LusiusDark** [SheetJS/js-xlsx#1652]
Copied your source code verbatim and am getting a message from Excel that there is a problem with the content. I have attached the log and the before file and after file (after fixing).

This is the code that ran:

function createSS(){
	
	var filename = "me.xlsx";
	var data = [[1,2,3],[true, false, null, "sheetjs"],["foo","bar",new Date("2014-02-19T14:30Z"), "0.3"], ["baz", null, "qux"]]
	var ws_name = "SheetJS";
	 
	if(typeof console !== 'undefined') console.log(new Date());
	var wb = XLSX.utils.book_new(), ws = XLSX.utils.aoa_to_sheet(data);
	 
	/* add worksheet to workbook */
	XLSX.utils.book_append_sheet(wb, ws, ws_name);

	/* write workbook */
	if(typeof console !== 'undefined') console.log(new Date());
	XLSX.writeFile(wb, filename);
	if(typeof console !== 'undefined') console.log(new Date());	
}

SPECIAL OBSERVATIONS: It worked before we installed Office 365. It doesn't appear to remove any data when repairing. Also, our server chokes on any file with individual lines over 3000 characters so I had to manually add carriage returns every 3000 characters or so to the xlsx,full.min.js file. Is there any way to get a minified version of the xlsx.full.min.js with breaks at ever 3000 characters? I can't find a minifier to do it.
[me.xlsx](https://github.com/SheetJS/js-xlsx/files/3698091/me.xlsx)
[me-fixed.xlsx](https://github.com/SheetJS/js-xlsx/files/3698095/me-fixed.xlsx)

![images and logs](https://user-images.githubusercontent.com/51424188/66324210-0760eb80-e8f3-11e9-8a0c-5b916bd64efc.png)

**Comment by SheetJSDev** [comment]
Your change must have corrupted the theme block.  The error is in the Theme XML.  Inspecting the theme file, there are many errors probably related to how your server is serving the script.

> Also, our server chokes on any file with individual lines over 3000 characters

Can you use a third party host?  The unpkg CDN hosts the script at  https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js and you should be able to reference it directly in a script tag
