### ISSUE TITLE
MS Office 365 Excel Version 1909 will not open exported files

### ISSUE THREAD

**Issue by escline** [SheetJS/js-xlsx#1661]
We started getting **`The file is corrupt and cannot be opened`** error when trying to open an exported xlsx file built using this library.

I also noticed the same error when exporting any file type from your demo page, https://sheetjs.com/demos/table.html

I get the error when using **Office 365 Excel version 1909 (Build 12026.20320)**, but my other PC that is still running **Version 1902 (Build 11328.20438)** works fine.

**Comment by SheetJSDev** [comment]
I just tried doing an update and the version updated to 1909 (Build 12026.20264) which doesn't show an error.  If you're on a beta channel, definitely report that to Microsoft

**Comment by escline** [comment]
Thanks for checking. The releases are managed by our corporate IT, so I doubt we are on a beta release, but stranger things have happened. I checked the Office 365 ProPlus releases and the Build 12026.20320 is the Oct 8th monthly channel build. But there are also 20334 (Oct 14th) and 20344 (Oct 22nd) releases. I have no idea how IT plans our releases. Maybe it's the ProPlus plan for why we have this different build. I also don't quite understand Microsoft's upgrade channels. It looks like 20320 is the build right after your 20264, though. So maybe keep an eye on this one in the next month.

My problem is I can't request IT to downgrade, so my only option at this point is to switch to a CSV export within our app until this gets sorted out. We've only had a few users bring the problem to our attention, but I figure it'll only get worse as this release gets pushed to more PCs.

If the next update happens to fix this issue, I'll be sure to update this issue, so you are aware.

**Comment by SheetJSDev** [comment]
Not sure why I can't pull that version yet, so your assistance would be appreciated :)

Does the same thing show up with the XLSB / XLS files in the web demo?  

To be sure it's not some weird browser issue, can you also test this file: [SheetJSTableExport (1).xlsx](https://github.com/SheetJS/js-xlsx/files/3787121/SheetJSTableExport.1.xlsx) -- 

Also, following https://support.office.com/en-us/article/Repair-a-corrupted-workbook-153A45F4-6CAB-44B1-93CA-801DDCD4EA53 , can you try to "open and repair" then save and share the file?

**Comment by escline** [comment]
Yes, I get the same error on every export option on that demo page.

I also get the same error when attempting to open your [SheetJSTableExport (1).xlsx](https://github.com/SheetJS/js-xlsx/files/3787121/SheetJSTableExport.1.xlsx) file.

I then tried to open it directly from Excel's open dialog. Same error. I tried the "Open and Repair" with both the "Repair" and then the "Extract Data" option, and they both get same error.

I jumped over to my other PC running version 1902 (Build 11328.20438), and opened your file. Since it came from the web, it opens in Protected View, which is normal. I enabled editing, and then **"saved as"** a new file. I was then able to open this new file on the newer version of Excel that would not open the original. I've emailed this file to sheetjs@gmail.com with the subject js-xlsx Issue #1661

**Comment by escline** [comment]
Shortly after submitting my reply, one of my team members seen my internal issue and tried to open the examples. He is running the very same version of Excel that gives me the error, but is able to open the exported files no problem.

I'm not sure what the issue is, now, but will keep looking. I would say at this time to hold off doing anything, as it looks to be an internal issue for us.

**Comment by escline** [comment]
I was curious and tested a Ruby on Rails backend built xlsx file and it also gives the error on opening, so going to close this issue. I believe it's an internal problem with some of the Office deployments within our company.
