### ISSUE TITLE
write million rows to xlsx from mysql db

### ISSUE THREAD

**Issue by abarik1981** [SheetJS/js-xlsx#168]
Hi there,
I would like to know if there is a fast way of writing 1 million rows to xlsx? Please take a look at http://stackoverflow.com/questions/28284205/node-js-dump-sql-as-xlsx-or-csv-fastest-possible-way

I am particularly using https://github.com/SheetJS/js-xlsx/blob/19c22fa34af4ec92f1984dae9fce8f749a39aac6/tests/write.js to write million rows

Thanks,
Amit

**Comment by SheetJSDev** [comment]
There are certainly ways to make it faster by adding constraints.  For example, if you knew that every cell would be written in the "General" format, the entire style logic could be bypassed.

Do you have a particular template or theme in mind, or do you just want to get data out in a plain xlsx?

**Comment by abarik1981** [comment]
thanks for replying, i just wanted to get all the data out in a plain xlsx and then style it later. thing is, i have all the data from mysql as nested array of arrays. 

but I guess found a easier way to do it simply using mysql export to csv. for now this works fine, but it will be good to know if xlsx can be made faster in such a case.
