### ISSUE TITLE
Anyway to tell sheet_to_json to output with the cell's value instead of text?

### ISSUE THREAD

**Issue by rdmurphy** [SheetJS/js-xlsx#169]
Hello!

Been using `XLSX.utils.sheet_to_json`, but hit a snag. The Excel workbook has a sheet with cells filled with integers. But when I run `sheet_to_json`, it spits them out as strings.

Using this as the example:
```js
A2: { t: 'n', v: 1995, w: '1995' },
B2: { t: 'n', v: 27, w: '27' },
C2: { t: 'n', v: 4, w: '4' },
```
I assume this is because it fills out object with the cell's text representation – `w` – instead of `v`. Is there anyway for me to tell it to use `v` instead?

I'm currently looping through the generated object to alter the keys I know should be numbers, but this tool would ideally not require the user to customize the converter per sheet. That could quickly get out of hand.

Thanks!

**Comment by rdmurphy** [comment]
Ha, went and poked on the code, and found it pretty quickly.

```js
XLSX.utils.sheet_to_json(worksheet, {raw: true});
```
It'd be good to document this!

**Comment by SheetJSDev** [comment]
@rdmurphy the default behavior is driven by the original problem, which was to produce a CSV identical to what you would get if you saved as CSV in Excel.  It might actually make sense to flip the default here.

**Comment by IgorShch** [comment]
Raw option is actually very good. It's a shame it's not documented.

**Comment by dinesh36** [comment]
Agreed with @IgorShch

**Comment by ghuroo** [comment]
Thank you very much sir! @rdmurphy

**Comment by sgibson21** [comment]
I had this problem only the other way around. sheet_to_json was giving me numbers when I wanted strings. Looks like the raw option defaulted to true for me. So I explicitly set it to false and now I get strings. :)

**Comment by ToanTNM** [comment]
Thanks **sgibson2**. It's seem raw is true by default in newest version. I've get datetime values with correct formatted text.

**Comment by cemremengu** [comment]
I was pulling my hair for the last two days when my unit tests started to blow up 😄

With `raw: true` I was getting incorrect date values like

```js
  O2: { t: 'd', v: 2016-03-31T20:59:04.000Z, w: '2016-04-01' },
  R2: { t: 'd', v: 2016-03-31T20:59:04.000Z, w: '2016-04-01' },
  S2: { t: 'd', v: 2017-10-30T20:59:04.000Z, w: '2017-10-31' },
```

The correct ones are the `w` ones so setting `raw: false` fixed it
