### ISSUE TITLE
XLS/XLML cell styles

### ISSUE THREAD

**Issue by SheetJSDev** [SheetJS/js-xlsx#172]
See https://github.com/SheetJS/js-xls/issues/51

**Comment by matteocontrini** [comment]
What is the progress of this? I'm not able to get a "normalized" style for some cells of an XLS file...

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
