### ISSUE TITLE
Trouble decoding file

### ISSUE THREAD

**Issue by shakhal** [SheetJS/js-xlsx#176]
Hello, 
I am having trouble parsing a Hebrew XLSX file
attached here: http://goo.gl/kPOfNr

Some of the cells data comes out empty.
For example for the first sheet: A1, A2, A3, A5, C6 etc..

Any help would be appreciated,
TIA,
Shakhal

**Comment by SheetJSDev** [comment]
I apparently already fixed it in my local copy, https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L2053 should read

```
			var o = parse_si(ss[i].trim(), opts);
```

Keeping open until next commit lands

**Comment by shakhal** [comment]
Awesome!
Thank you so much :)

**Comment by oising** [comment]
Any idea when the next commit lands? ;)

**Comment by shakhal** [comment]
+1 waiting for next realease, much appreciated! TIA!

**Comment by shakhal** [comment]
Hey, 
Thanks for your efforts on merging xls & xlsx,
Seems like this issue is back again...
