### ISSUE TITLE
Incorrect handling of table:number-columns-repeated in ODS

### ISSUE THREAD

**Issue by ziacik** [SheetJS/js-xlsx#177]
Hi. I think there may be incorrect handling of number-columns-repeated attribute in ODS files.

If I have a table where two adjacent cells have the same value, the second will not be present in Sheet object.

For example, having an ODS with `A1` cell set to "A" and `B1` cell set to "A" too,

`console.log(require('xlsx').readFile('./Test.ods').Sheets.Sheet1);`

outputs this:

`{ A1: { t: 's', v: 'A', w: 'A' }, '!ref': 'A1' }`

So B1 is missing there.

Version I tried this on is 0.7.12.

**Comment by SheetJSDev** [comment]
@ziacik do you have a sample file so I can take a look?

**Comment by ziacik** [comment]
@SheetJSDev Sample file is at this link http://www.koliksoftware.net/Stuff/Test.ods

**Comment by ziacik** [comment]
Merged cells are not handled well either as you can see from http://www.koliksoftware.net/Stuff/Test2.ods

**Comment by JavaScriptDude** [comment]
What is holding this back? This bug makes this toolset unusable for parsing ODS files. The patch works for me.

**Comment by Dineshagrawal85** [comment]
i'm facing same problem is there any solution for this?

**Comment by JavaScriptDude** [comment]
I had to fork this locally and apply ziacik's patch. Ugly but only way to get around this without involvement of owners.
