### ISSUE TITLE
Maintain Workbook Styling When Writing to New File

### ISSUE THREAD

**Issue by elimence** [SheetJS/js-xlsx#178]
I'm reading an excel file as follows
`var workbook = X.readFile("testSheet.xlsx", r_opts);`
using the following options object
`var r_opts = { bookType:'xlsx', cellStyles:true, sheetStubs: true };`

All this works just fine, but now I need a way to write a new file so that when I save, it has the same original formatting as the original file.

I can't find any way to do this, and when I write the file, it's just plain without any formatting.
I hope this can be achieved, and I'll stand by to hear from you guys.
Great work producing this library by the way :+1:

**Comment by pietersv** [comment]
In development, see issue #128 for current discussion.  There are two sides -- some but not all possible styles get read by `readFile()` into the workbook, and some but not all possible styles get written out.  The intersection set is what survives the the read-and-save path.  Working to expand both.

**Comment by elimence** [comment]
Ok thanks! I've gone through the discussion, looks promising. I'll find an alternative for now while I wait for the completion of this feature.
Thanks again :)

**Comment by pietersv** [comment]
One way to help is to try the dev version, either in Node.js (`npm install protobi/js-xlsx`) or in the browser 
(`<script type="text/javascript" src="https://rawgithub.com/protobi/js-xlsx/master/xlsx.js">`) and provide feedback that will improve it. This will preserve some but not all styles, so not a perfect round trip.

**Comment by elimence** [comment]
I'll be glad to help out in anyway that I can.
I'm gonna try out the Node.js version. I'll send any feedback I have after I do.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
