### ISSUE TITLE
Serialize Comments

### ISSUE THREAD

**Issue by aravindkoneru** [SheetJS/js-xlsx#183]
I'm running into a problem making a cell with a formula. As far as I know, the way that I'm defining the formula within the cell object is fine and the cell does write to the file when there is a v value. 

Here's my cell: 

>  var cell = {
>     v: 0,
>     f: 'A2*B2'
>     t: 'n'
>   };

Here's how I am printing out the data in the cells:

>  var book = xlsx.readFile("blah2.xlsx");
>   var sheet = book.Sheets["test"];
>   console.log(sheet);

Although the cell gets written to "test" locally before being written to the file, the cell simply disappears from the spreadsheet when it is written. If there is a v value for the cell, the cell appears, but the formula disappears. 

I also found that there is a similar problem with the c value in the cell, where the cell will disappear if not given a v value.  

So my question is: How do I write a formula or comment to a cell and not have it disappear?

**Comment by ryangallen** [comment]
Bumping this issue.

According to the docs: "The raw data is the only thing guaranteed to be saved. Formulae, formatting, and other niceties may not be serialized (pending CSF standardization)"

Is there any word on progress for this topic? Has anyone found a workaround?

**Comment by ryangallen** [comment]
Duplicate issue: https://github.com/SheetJS/js-xlsx/issues/152#issuecomment-87772442

**Comment by SheetJSDev** [comment]
The formulae should be written to XLSX as of 0.9.4, comments are not yet written to file.

**Comment by SheetJSDev** [comment]
@ryangallen we pushed the feature to the master branch and it will be in the next version cut (aiming for some time in the next 48 hours or so).

https://sheetjs.gitbooks.io/docs/#cell-comments is the relevant part of the docs (it's also in the README but I like the page with the sidebar).  As we settle on representations we will add more subsections to the README.
