### ISSUE TITLE
Issues when running under phantomjs

### ISSUE THREAD

**Issue by machinewu** [SheetJS/js-xlsx#184]
I wrote a simple test ir run by phantomjs (Ubuntu):
**test.js**

```
var fs = require('fs');
var xlsx = require('./xlsx');
var page = require('webpage').create();

page.open('http://www.google.com', function(status) {

  var data = fs.read('a.xlsx', {mode: 'rb', charset: 'utf8'});
  var workbook = xlsx.read(data, {type: 'binary'});
  data = xlsx.utils.sheet_to_csv(workbook.Sheets['Worksheet']);
  console.log("Data: " + data);

  phantom.exit();
});
```

Directory tree of phantomjs dir "phantomjs/bin":
- a.xlsx
- dist/cpexcel.js
- jszip.js
- phantomjs
- test.js
- xlsx.js

Run-time error occurred:
TypeError: 'undefined' is not a constructor (evaluating 'new jszip(d, { base64:false })')

for the reason, I found in **xlsx.js**:

```
if(typeof JSZip !== 'undefined') jszip = JSZip;
if (typeof exports !== 'undefined') {
    if (typeof module !== 'undefined' && module.exports) {
        if(has_buf && typeof jszip === 'undefined') jszip = require('js'+'zip');  // not go here, because has_buf is false
        if(typeof jszip === 'undefined') jszip = require('./js'+'zip').JSZip;  // go here, but require('./jszip').JSZip is a wrong require!!!  require('./jszip') is a correct require.
        _fs = require('f'+'s');
    }
}
```

**Comment by SheetJSDev** [comment]
@machinewu Let's keep all of the relevant phantomjs issues to this discussion (I closed the other issue)

Can you check if `require('./jszip').JSZip` is defined in test.js?  

Also, with regards to the other issue, do you happen to know what is the correct way to detect if the script is being run in a phantomjs context?  Clearly that part (fs detection and read/write semantics) needs to be reevaluated.

**Comment by machinewu** [comment]
I change the xlsx.js
```
if(typeof jszip === 'undefined') jszip = require('./js'+'zip').JSZip;
```

to 
```
if(typeof jszip === 'undefined') jszip = require('./js'+'zip');
```

and run script test.js in phantomjs, it work.

so, I write some console log in xlsx.js to trace the jszip where it define by require. I found in phantomjs, it should not require: **jszip = require('./js'+'zip').JSZip**, but **jszip = require('./js'+'zip')**

The trace code:
```
var _fs, jszip;
if(typeof JSZip !== 'undefined') { jszip = JSZip; console.log("Trace1:", typeof jszip);}
if (typeof exports !== 'undefined') {
	console.log("Trace2");
	if (typeof module !== 'undefined' && module.exports) {
		console.log("Trace3");
		if(has_buf && typeof jszip === 'undefined') {jszip = require('js'+'zip'); console.log("Trace4", typeof jszip);}
		if(typeof jszip === 'undefined') {jszip = require('./js'+'zip').JSZip; console.log("Trace5", typeof jszip);}
		_fs = require('f'+'s');
	}
	{console.log("Trace6", typeof jszip);}
}
```

result:
>Trace2
>Trace3
>Trace5 undefined
>Trace6 undefined
>TypeError: 'undefined' is not a constructor (evaluating 'new jszip(d, { base64:false })')

After change **jszip = require('./js'+'zip').JSZip** to **jszip = require('./js'+'zip')**:
The trace code:
```
var _fs, jszip;
if(typeof JSZip !== 'undefined') { jszip = JSZip; console.log("Trace1:", typeof jszip);}
if (typeof exports !== 'undefined') {
	console.log("Trace2");
	if (typeof module !== 'undefined' && module.exports) {
		console.log("Trace3");
		if(has_buf && typeof jszip === 'undefined') {jszip = require('js'+'zip'); console.log("Trace4", typeof jszip);}
		if(typeof jszip === 'undefined') {jszip = require('./js'+'zip'); console.log("Trace5", typeof jszip);}
		_fs = require('f'+'s');
	}
	{console.log("Trace6", typeof jszip);}
}
```

result:
>Trace2
>Trace3
>Trace5 function
>Trace6 function

**Comment by machinewu** [comment]
If I define JSZip at my code at first in phantomjs, It can work.
```
var fs = require('fs');
var JSZip = require('./jszip');
var xlsx = require('./xlsx');
var page = require('webpage').create();
```


But, If I use casperjs framework, it does not work whether I define **var JSZip = require('./jszip');**

**Comment by machinewu** [comment]
If I defined JSZip in a module but not global, it does not work.
test_module.js locate in the diretcory the same as test.js

Not work code:
**test.js**
```
var process = require('./test_module');
var page = require('webpage').create();

page.open('http://www.baidu.com', function(status) {
    process.run();
    phantom.exit();
});
```

**test_module.js**
```
var fs = require('fs');
var JSZip = require('./jszip');
var xlsx = require('./xlsx');

exports.run = function () {
    var data = fs.read('a.xlsx', {mode: 'rb', charset: 'utf8'});
    var workbook = xlsx.read(data, {type: 'binary'});
    data = xlsx.utils.sheet_to_csv(workbook.Sheets['Worksheet']);
    console.log("Status: " + data);
}
```


Work code:
**test.js**
```
var JSZip = require('./jszip');
var process = require('./test_module');
var page = require('webpage').create();

page.open('http://www.baidu.com', function(status) {
    process.run();

    phantom.exit();
});
```

**test_module.js**
```
var fs = require('fs');
var xlsx = require('./xlsx');

exports.run = function () {
    var data = fs.read('a.xlsx', {mode: 'rb', charset: 'utf8'});
    var workbook = xlsx.read(data, {type: 'binary'});
    data = xlsx.utils.sheet_to_csv(workbook.Sheets['Worksheet']);
    console.log("Status: " + data);
}
```

I think jszip should require more automatic, less manual require.

**Comment by SheetJSDev** [comment]
@machinewu last question: what happens if you use the xlsx.core.min.js file https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.core.min.js in place of xlsx.js?  When using this file, JSZip should not be pulled with `require` (it is defined so that entire code block is skipped)

**Comment by machinewu** [comment]
I change the name xlsx.core.min.js to xlsx.js, and replace the original xlsx.js. Remove jszip.js and dist/cpexcel.js. 

** test_module.js **
```
var fs = require('fs');
var xlsx = require('./xlsx');

exports.run = function () {
    console.log('=== xlsx:', typeof xlsx);
    var data = fs.read('a.xlsx', {mode: 'rb', charset: 'utf8'});
    var workbook = xlsx.read(data, {type: 'binary'});
    data = xlsx.utils.sheet_to_csv(workbook.Sheets['Worksheet']);
    console.log("Status: " + data);
}
```

Terminal display:
>SyntaxError: Parse error
>
>=== xlsx: object
>TypeError: 'undefined' is not a function (evaluating 'xlsx.read(data, {type: 'binary'})')

**Comment by SheetJSDev** [comment]
@machinewu thanks for looking into this!  You've exposed quite a few interesting issues.

That workaround is in the code because the jszip.js script uses a different version from the nodejs module (there were quite a few problems when they stopped using https://github.com/imaya/zlib.js for DEFLATE).  I will do some more tests in the browser with the latest version.  If it works out, we can update the browser dependency and simplify the require logic

**Comment by brunoshine** [comment]
Hi all,

I'm also experiencing some issues, but in my case the message is different:
*TypeError: undefined is not a constructor (evaluating '_fs.readFileSync(data)')*

I've installed xlsx via npm.

my code is:
```
var page = new WebPage(), testindex = 0, loadInProgress = false;
var fs = require('fs');
var XLSX = require('xlsx');

var workbook = XLSX.readFile('data.xlsx');
```

Any thoughts?

Thanks,
Bruno

**Comment by LinusU** [comment]
@brunoshine Phantom.js dosen't have an `fs` module and can't write to or read from disk.

**Comment by jonbonraki** [comment]
i am also having the same has there been a solution on this ?

**Comment by raiym** [comment]
The same thing: 
    var xlsx = require('./bower_components/js-xlsx/dist/xlsx.core.min.js');
    var workbook = xlsx.XLSX.read(bstr, {type:"binary"});
    first_sheet_name = workbook.SheetNames[0];

And response is: 
    TypeError: 'undefined' is not an object (evaluating 'xlsx.XLSX.read')

**Comment by sinjihn** [comment]
I was having this issue using vanilla JS, I fixed it by making sure I included the scripts in the same order as the example.

```
    <script src="js-xlsx-master/jszip.js"></script>
    <script src="js-xlsx-master/shim.js"></script>
    <script src="js-xlsx-master/xlsx.js"></script>
    <script src="js-xlsx-master/dist/ods.js"></script>

```

**Comment by TechBK** [comment]
How fix it on `react-native` context ?

**Comment by SheetJSDev** [comment]
We are including a phantomjs sample based on @machinewu initial code in the next commit, as this appears to work in `2.1.1`.  Please test and let us know if you have any other issues.

@TechBK please raise a new issue if you are talking about something other than `phantomjs`
