### ISSUE TITLE
Can not read or write file in phantomjs

### ISSUE THREAD

**Issue by machinewu** [SheetJS/js-xlsx#185]
In phantomjs, functions in module fs to read and write files are **read**(http://phantomjs.org/api/fs/method/read.html) and **write**(http://phantomjs.org/api/fs/method/read.html) but not like module fs in nodejs **readFileSync** and **writeFileSync**.

**Comment by SheetJSDev** [comment]
Going to combine this discussion with https://github.com/SheetJS/js-xlsx/issues/184
