### ISSUE TITLE
live demo not working

### ISSUE THREAD

**Issue by maheshp212** [SheetJS/js-xlsx#186]
http://oss.sheetjs.com/js-xlsx/

It is throwing some error please check and hlep me up
![screenshot from 2015-02-28 11 44 46](https://cloud.githubusercontent.com/assets/4687976/6425108/412746a8-bf3f-11e4-976d-433e1342d066.png)

**Comment by SheetJSDev** [comment]
It looks like you are using an XLS file (The name is "Manage Model Data.xls").  Can you test against http://oss.sheetjs.com/js-xls/ ?

**Comment by maheshp212** [comment]
i tested it again
![screenshot from 2015-02-28 12 33 45](https://cloud.githubusercontent.com/assets/4687976/6425221/13e6a740-bf46-11e4-8c88-2931b9762d34.png)

**Comment by maheshp212** [comment]
i tried with xlsx also
/home/newtel/Pictures/Screenshot from 2015-02-28 12:34:55.png

**Comment by maheshp212** [comment]
![screenshot from 2015-02-28 12 34 55](https://cloud.githubusercontent.com/assets/4687976/6425235/6b0ad456-bf46-11e4-8602-d91822b03152.png)

**Comment by maheshp212** [comment]
i m checking in ubuntu... and just now i tried in windows its working fine.. is there any OS dependent??

**Comment by SheetJSDev** [comment]
What version of Ubuntu and what version of chrome are you using?  There is no os-dependent behavior or detection.

**Comment by reviewher** [comment]
@maheshp212 please raise a new issue if you still have problems and include the browser info
