### ISSUE TITLE
IE9 issue

### ISSUE THREAD

**Issue by neirdahcier** [SheetJS/js-xlsx#187]
Hi, 
I like your script, it works fine with ie10+ chrome and firefox but i have problems with ie9.
the console give me an error: blob is undefined.
So i tried to include polyfill for blob and typedarray, it was better but i had still an error : object expected

Im doing an angular js app with also asasql:
ex: alasql('SELECT \* INTO XLSX("test.xlsx",{headers:true}) FROM ?',[$scope.displayedCollection]);

And I includes from you with script tag (I tried also the master tree):
/bower_components/js-xlsx/shim.js
/bower_components/js-xlsx/dist/xlsx.core.min.js

Any ideas ?

**Comment by SheetJSDev** [comment]
How are you pulling the source data?  Is it coming from an XHR or some other means?

@agershun any thoughts?

**Comment by neirdahcier** [comment]
I pulled with bower install js-xlsx

**Comment by SheetJSDev** [comment]
@neirdahcier IE9 and below are still able to use XHR.  Can you check if http://oss.sheetjs.com/js-xlsx/ajax.html works?  This page downloads http://oss.sheetjs.com/js-xlsx/test_files/formula_stress_test_ajax.xlsx with XMLHttpRequest and processes the data

**Comment by neirdahcier** [comment]
I tried your demo site.

I uploaded a simple xlsx file via http://oss.sheetjs.com/js-xlsx/ , works fine in ie10, but in ie9 i have javascript error in js-xlsx.js : for (i = 0, f = files[i]; i != files.length; ++i) { :'Unable to get property '0' of undefined or null

The http://oss.sheetjs.com/js-xlsx/ajax.html seems to work.
But in my app the data come from a json object and the library alasql use it to put it using XLSX.
I don't think it use XMLHttpRequest.

example from alasql doc inpired in my app :
http://jsfiddle.net/agershun/00nfeq12/

**Comment by wmfairuz** [comment]
I also have the same problem with IE9, uploaded a simple xlsx file and getting this error:

SCRIPT5007: Unable to get value of the property '0': object is null or undefined 
js-xlsx, line 218 character 2

**Comment by agershun** [comment]
The source of the problem is related with to FileSaver limitations (AlaSQL uses this library to save data as the file), unfortunately it does not support IE9. I have in very short plans in the very beginning of May to find a solution for IE9 (probably with ActiveX or other appropriate solution. Please, also use https://github.com/agershun/alasql/issues/73 for this issue. Sorry for a delay with with issue.

**Comment by agershun** [comment]
@SheetJSDev Is there way to save multisheet XLSX workbook as plain text (html) rather than binary (pkzipped) format? For example, it is possible to save data from Excel in XML format and then rename it to XLS extension. If so, users of IE9 can use something like:

    function isIE () {
         var myNav = navigator.userAgent.toLowerCase();
         return (myNav.indexOf('msie') != -1) ? parseInt(myNav.split('msie')[1]) : false;
     }

     function saveFile(data) {
        if(isIE() == 9) {
              var s = XLSX.generateXMLFromWorkbook(workbook);
	      var testlink = window.open("about:blank", "_blank");
	      testlink.document.write(data); 
	      testlink.document.close();
	      testlink.document.execCommand('SaveAs', false, path);
	      testlink.close();         		
        } else {
           // Save as usual binary file
        }
     }

Here, XLSX.generateXMLFromWorkbook() is a hypothetical function to generate XML from workbook.

**Comment by SheetJSDev** [comment]
@agershun there is no way using the excel html style, but it can be done with spreadsheetml (for example, https://github.com/SheetJS/test_files/blob/master/number_format.xls.xml)

**Comment by agershun** [comment]
You are right. XML format is better then HTML (at least we can create multiple sheets in the page).

I have created very simple function, which generates XML document from array (now it works with IE9) (http://jsfiddle.net/95j0txwx/7/). Hope, I can rewrite it to extract it from AlaSQL, so it will take data from ```js-xlsx``` workbook format. Thank you for the file with number formats and ```pb```.

**Comment by reviewher** [comment]
If this is still an issue, please raise an issue with https://github.com/agershun/alasql
