### ISSUE TITLE
Row limit of 65536 rows on import

### ISSUE THREAD

**Issue by grassick** [SheetJS/js-xlsx#189]
I imported a very large spreadsheet using `xlsx.utils.sheet_to_json` and only the first 65536 rows of 100000+ were imported. There was no error or any other indication of truncation. Is there a way to increase the limit Excel 2007+ support many more.

**Comment by SheetJSDev** [comment]
@grassick can you share a sample file that shows this problem?  If you can't share it, can you check the internal range of that sheet? (if `ws` is the worksheet, check the value of `ws['!ref']`)

FWIW I just checked on a 100K row file generated by Excel 2013 and there was no issue.

**Comment by grassick** [comment]
Aha! It's LibreOffice. The original Excel is `A1:AY111176` and LibreOffice resaves as `A1:AY65536`

Thanks for your prompt response!

**Comment by sunil-ideas2it** [comment]
@grassick  Can u please tell us how you solved this problem i am facing the same thing i have around 4 lakhs of records it is parsing only 65536

**Comment by reviewher** [comment]
@sunil-ideas2it you can manually change the worksheet `!ref` before using any of the utility functions.  It is described in the README:

> ws['!ref']: A-1 based range representing the worksheet range. Functions that work with sheets should use this parameter to determine the range. **Cells that are assigned outside of the range are not processed**. In particular, when writing a worksheet by hand, be sure to update the range. For a longer discussion, see http://git.io/KIaNKQ
