### ISSUE TITLE
insert comment to a cell

### ISSUE THREAD

**Issue by abarik1981** [SheetJS/js-xlsx#192]
When I try using the `cell.c = 'i-am-comment'`, does this insert a comment to a cell?

I am trying to insert a comment to a cell. How can I do it. I am using the latest js-xlsx. Also tried https://github.com/protobi/js-xlsx#cell-styles

**Comment by stla** [comment]
I'd like. I've just opened a question on SO: http://stackoverflow.com/questions/41526127/write-xlsx-file-with-comments-using-js-xlsx
