### ISSUE TITLE
Parsing 4 digit-Decimals after point from Excel gives back two point number

### ISSUE THREAD

**Issue by nottinhill** [SheetJS/js-xlsx#193]
I have such data in Excel:

```
1.2912
0.21312
```

Now when I parse this is what gets written out in my DB:

```
1.29
0.21
```

I am expecting to see 4-digit number to be written into DB, is there a parameter how to disable rounding? 

I want to debug and console.log in node.js and only see data _as such_:

```
{ s: 1, e: -2, c: [ 3 ] }
{ s: 1, e: 0, c: [ 0 ] }
```

**Comment by SheetJSDev** [comment]
@nottinhill Do you have a sample file that I could look at?

**Comment by reviewher** [comment]
It's most likely the case that you are reading the formatted data.  To get the raw data, look at the

**Comment by reviewher** [comment]
It's most likely the case that you are reading the formatted data.  To get the raw data, look at the `v` property of the cells.  The `XLSX.utils.sheet_to_json` converter takes an options argument, and setting `raw:true` will give you the original values.

Feel free to reopen the issue @nottinhill
