### ISSUE TITLE
Typo in bower.json

### ISSUE THREAD

**Issue by varblob** [SheetJS/js-xlsx#198]
{
  "name": "js-xlsx",
  "homepage": "https://github.com/SheetJS/js-xlsx",
  "main": "dist/xlsx.js",
  "version": "0.8.0",
  "ignore": [
    "bin",
    "bits",
    "misc",
    "**/.*"
  ],
  "keywords": [
    "excel",
    "xls",
    "xml",
    "xlsx",
    "xlsm",
    "xlsb",
    "ods",
    "js-xls" <-- missing comma
    "js-xlsx"
  ]
}

**Comment by SheetJSDev** [comment]
Thanks for pointing this out!  The build script now also checks bower.json and package.json to ensure they are valid JSON.  The v0.8.0 tag was also changed.  Please test it now (and please close the issue if it works)

**Comment by varblob** [comment]
Just tried installing 0.8 via bower looks good!
