### ISSUE TITLE
About ko-kr FormatCode incorrect Issue

### ISSUE THREAD

**Issue by JohnJeong123** [SheetJS/js-xlsx#200]
I'm a korean developer.

I am using xlsjs(v0.7.5).

I expected the correct formatcode about ("yyyy-mm-dd") date Format.

But always rendered data is mm/dd/yy that is formatcode 14...

In . ECMA-376 

ko-kr "yyyy-mm-dd" formatcode is 34, 35, 52, 53, 55, 56 

I want to get correct formatcode about "yyyy-mm-dd" ko-kr date Format.

Is there I missing step on locale setting at sheetjs??

I'm waiting your Response

**Comment by SheetJSDev** [comment]
This is the same problem encountered in https://github.com/SheetJS/js-xlsx/issues/181 -- basically, a few excel date formats are locale-specific.  You can see the difference if you change your system locale (in the Regional settings) and then open the file in Excel.

Right now, the formatter assumes the locale is en-US.  A temporary workaround is described in https://github.com/SheetJS/js-xlsx/issues/181#issuecomment-76733831 until we have a better solution.

**Comment by SheetJSDev** [comment]
We are pushing a change in 0.9.13 that allows you to specify a `dateNF` option to the parser to override the date format.  It will correctly write a file with the original format, but the JS API will use the specified format instead.
