### ISSUE TITLE
sometimes when header is having rowspan and colspan, the colspan doesn't get applied properly

### ISSUE THREAD

**Issue by ashwin-ragha1** [SheetJS/js-xlsx#201]
In ExportToExcel.js file, in the method generateArray(table)

var colspan = cell.getAttribute('colspan');
var rowspan = cell.getAttribute('rowspan');

both colspan and rowspan are strings...

so when an element is pushed into the "ranges" array, e.r and e.c is not proper and as a result, on the iteration for the next cell, the ranges for each loop doesn't run properly... and the header with colspan looks weird.

To fix it, we need to parse the attributes to int.

var colspan = parseInt(cell.getAttribute('colspan'));
var rowspan = parseInt(cell.getAttribute('rowspan'));

Also, cell.innerText property is not supported in FireFox... to solve this I checked the browser and used cell.textContent.
var isFirefox = typeof InstallTrigger !== 'undefined';
            var cellValue = isFirefox ? cell.textContent : cell.innerText;

In method export_table_to_excel(id), instead of hardcoding the worksheet name to SheetJS and file name to test.xlsx, we can accept sheetName and fileName as parameter and assign them respectively.

**Comment by Palakp41** [comment]
Thank you so much @ashwin-ragha1! This helped a lot!

**Comment by ashwin-ragha1** [comment]
Glad to be of help ☺️

**Comment by SheetJSDev** [comment]
We added `table_to_sheet` and `table_to_book` directly to the library that addresses the colspan/rowspan issue.

innerText is now supported in firefox

The `table_to_book` option takes an options argument, and the second argument's `sheet` key is the name of the worksheet in the workbook.

Usage is described in https://github.com/sheetjs/js-xlsx#html-table-input .  Summary:

```js
var tbl = document.getElementById('id_of_table');
var wb = XLSX.utils.table_to_book(tbl, {sheet:"nameofsheet"});
```
