### ISSUE TITLE
not reading formulas entered with Excel's fill / drag feature

### ISSUE THREAD

**Issue by vstegman** [SheetJS/js-xlsx#204]
I am reading excel files and would like to isolate values that were calculated vs. directly entered.  I have run into a bug where js-xlsx only recognizes formulas that were directly entered by the user in Excel or copied and pasted to a single cell.  If the Excel formulas are generated by the user using the drag to fill feature then js-xlsx does not provide an .f property.  

For example, in the files I am reading it would be common for a user to copy a formula like "=SUM(A1:F1)" down through many rows quickly by dragging.

Are formulas created in this manner stored elsewhere in the meta data?  Is there a workaround?

**Comment by matthewmueller** [comment]
+1 running into this myself.

**Comment by SheetJSDev** [comment]
I believe you are encountering shared formulae -- can you check against the latest version?

**Comment by SheetJSDev** [comment]
@vstegman @matthewmueller please reopen or comment here if you find this problem with the latest version.  I'm pretty sure it is a shared formula issue, which we recently addressed
