### ISSUE TITLE
Sheet missing from Sheets object but showing up in SheetNames array

### ISSUE THREAD

**Issue by jordanrogers** [SheetJS/js-xlsx#207]
I am experiencing the same symptom as issue #145, where I have what seems to be a valid xlsx, but when I parse it the SheetNames array contains the sheet name, but the Sheets object is empty. I am using v 0.8.0.

https://gist.github.com/jordanrogers/8b20c2b87118532f3add

If I open the file in excel and save it, it parses fine. I've tried hacking up the .xlsx to isolate the issue, without success.

**Comment by demiurga** [comment]
Got same issue there, open and save xlsx again can resolve it.

**Comment by quest** [comment]
+1

**Comment by SheetJSDev** [comment]
This file had the same problem as #508 -- unexpected namespaces in the XML.  This issue was fixed in 0.8.3 and it appears to work in http://oss.sheetjs.com/js-xlsx/ as well as in the node module.
