### ISSUE TITLE
excel sheet date field lost first 2 digit

### ISSUE THREAD

**Issue by jerryhe88** [SheetJS/js-xlsx#208]
In the excel sheet, let's say there is a column with values of date type. In the values of date type, let us say one value is '4/15/2015'. When  SheetJS gets the json data(use the api xlsxUtil.sheet_to_json(rosterFile.Sheets[rosterSheet])), the value '4/15/2015' is not there, but '4/15/15' is in the json. So it seems '2015' lost the first '20'. Is this a feature or bug?

Thanks
Jerry

**Comment by SheetJSDev** [comment]
@jerryhe88 I suspect this is the same as https://github.com/SheetJS/js-xlsx/issues/200 and https://github.com/SheetJS/js-xlsx/issues/181.  To be sure, if you manually change the format for code 14 (see https://github.com/SheetJS/js-xlsx/issues/181#issuecomment-76733831) to 'm/d/yyyy', do you see 2 or 4 digits?

**Comment by jerryhe88** [comment]
thanks for quick reply. Not sure what needs to do after reading  #200 and #181. 
The below is the file and code:
filePath.xlsx has data like '4/15/2015';
var fileContent = xlsx.readFile(filePath.xlsx);
var rowDatas = xlsxUtil.sheet_to_json(fileContent.Sheets['Template']);

after the above,
rowDatas has  '4/15/15'. Can you please provide sample codes or configs so that rowDatas can have '4/15/2015'?

thanks again

jerry

**Comment by SheetJSDev** [comment]
In 0.9.13 we're adding a `dateNF` option for the parsers to override the interpretation of the default dates:

```js
var fileContent = XLSX.readFile(filePath.xlsx, {dateNF:"mm/dd/yyyy"});
```
