### ISSUE TITLE
Carriage Returns '\r' in my parsed headers 

### ISSUE THREAD

**Issue by nottinhill** [SheetJS/js-xlsx#212]
I see this as headers when parsing my xlsx file on a Mac.

```
'Key\rChain'
```

Obviously somebody hit the Enter key in that excel headers.
Is there a way to only get: 

```
'KeyChain'
```

?

**Comment by SheetJSDev** [comment]
@nottinhill currently this can be done by dumping without headers and rebuilding the JS objects. If you run the sheet_to_json function with the option `{header:1}`, it will produce a straight array-of-arrays that you can work with.  Using https://github.com/SheetJS/test_files/blob/master/RkNumber.xlsx as an example, let's make all of the headers lowercase:

```
> var XLSX = require('xlsx')
> var wb = XLSX.readFile('RkNumber.xlsx')

> XLSX.utils.sheet_to_json(wb.Sheets.RkNumber)
[ { fX100: '0', fInt: '0', sample: '10000000' },
  { fX100: '0', fInt: '1', sample: '1200455' },
  { fX100: '1', fInt: '0', sample: '0.01' },
  { fX100: '1', fInt: '1', sample: '12004.55' } ]

> var aoa = XLSX.utils.sheet_to_json(wb.Sheets.RkNumber, {header:1}); aoa
[ [ 'fX100', 'fInt', 'sample' ],
  [ '0', '0', '10000000' ],
  [ '0', '1', '1200455' ],
  [ '1', '0', '0.01' ],
  [ '1', '1', '12004.55' ] ]

> function fix_header(header) { return header.toLowerCase(); }
> aoa.slice(1).map(function(x) { var o = {}; aoa[0].forEach(function(h, i) { o[fix_header(h)] = x[i]}); return o; })
[ { fx100: '0', fint: '0', sample: '10000000' },
  { fx100: '0', fint: '1', sample: '1200455' },
  { fx100: '1', fint: '0', sample: '0.01' },
  { fx100: '1', fint: '1', sample: '12004.55' } ]
```

@nottinhill i agree that we could do some sanitization within the util directly, although I'm not sure what other characters should be removed.  

@notatestuser @elad any thoughts?

**Comment by elad** [comment]
I'm not yet convinced this is functionality that belongs in the library, but maybe I'm missing something. What's wrong with the example you (@SheetJSDev) provided, where standard functions are used to process the data returned from `sheet_to_json`?

**Comment by nottinhill** [comment]
Thanks @SheetJSDev and @elad - I will be able to look into this in 1-2 weeks and provide you feedback as well as more pros and cons.
