### ISSUE TITLE
worksheet range not working

### ISSUE THREAD

**Issue by kalai7890** [SheetJS/js-xlsx#213]
i am newbie to js-xlsx
in my code i have something like this, workSheet["!range"].e.c
this works fine for .xls file by returning column count but not returning any values for .xlsx files. can anyone help me with this. i just opened the object and found that range is not coming as attribute for .xlsx files. is this a bug or any problem with me? i am using the most updated chrome browser and reading the file through FileReader API. 

Any helping hands will be appreciated much.
![capture](https://cloud.githubusercontent.com/assets/12132476/7343121/f08f2e30-ecda-11e4-93c9-d9488530f3be.JPG)

**Comment by SheetJSDev** [comment]
@kalai7890 The `!range` object should not be used (it is there for some XLS-specific parsing features that do not show up in XLSX or XLSB, and it will be removed in a future version).  Instead, use `!ref` (which stores a string reference) and use the utility `XLSX.utils.decode_range` to parse it:

    var range = XLSX.utils.decode_range(ws['!ref']);

Note that the XLS `!range` uses C-range semantics (so the end row/col indices are actually one element beyond the end), whereas the `!ref` stores the indices of the first and last entry, so any loops should be checked.

For example, using the test file https://github.com/SheetJS/test_files/blob/master/RkNumber.xls in nodejs:

```
> var XLSX = require("xlsx");
> var wb = XLSX.readFile("RkNumber.xls");
> var ws = wb.Sheets.RkNumber;
> ws['!range']
{ s: { r: 0, c: 0 }, e: { r: 5, c: 3 } }
> ws['!ref']
'A1:C5'
> XLSX.utils.decode_range(ws['!ref'])
{ s: { c: 0, r: 0 }, e: { c: 2, r: 4 } }
```

**Comment by kalai7890** [comment]
Wow great!. Thank you so much for your immediate solution to my problem. i am closing this case.
