### ISSUE TITLE
Corrupt XLSX file after downloading

### ISSUE THREAD

**Issue by nikolaifischer** [SheetJS/js-xlsx#217]
Hi,
I know there is already a very similar issue here but it does not provide a solution, because the author of this issue just uses a different approach to download the file in the end.
 https://github.com/SheetJS/js-xlsx/issues/122

I'm trying to download a file which is generated in the nodejs backend from the angular frontend, but when I try to open it, it's always corrupted. Of course I have seen the example in the readme of this project and tried it, but it also came out corrupted. I can write the output to a file and then point the browser to it by using window.location() and the file is fine. Sadly I could not get this approach working with my authorization code.
I read somewhere that it's better to send buffer objects when working with expressjs, so here is my code right now:
```javascript
// Backend
var wopts = { bookType:'xlsx', bookSST:false, type:'buffer' };
 
		var wbout = XLSX.write(workbook,wopts);

		res.writeHead(200, [['Content-Type',  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']]);
		res.end( wbout );
 
// Frontend
// This triggers the backend function:
 $http.get("/abrechnung/exportToExcel/" + JSON.stringify(pageAndFilter.filterByFields)).
             success(function(data, status, headers, config) {  
              // The data object is the buffer
        saveAs(new Blob([data],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}), "test.xlsx");
        }).
  error(function(data, status, headers, config) {
  });

```
Any help would be greatly appreciated!

**Comment by SheetJSDev** [comment]
@nikolaifischer Let's start by making sure the data on the backend is valid.  After generating the workbook, can you write to some file on the server side (for example, `fs.writeFileSync("test.xlsx", wbout)`), copy it to your client computer and open it in Excel?

**Comment by nikolaifischer** [comment]
No, it's not corrupted when writing it to a file on the server. Strange!

**Comment by remi-lebigre** [comment]
Hello,

I have the same corruption issue when writing my document.
I am editing the cells according to the documentation, and my Excel files output can be read, but I get almost every time the corrupt message error.
Here is what i found : if i console log wbout, i get wrong characters that may the cause of the corruption
<pre><code>
        var wopts = {bookType: 'xlsx', bookSST: true, type: 'binary', cellStyles: true};
        var wbout = XLSX.write(Email.workbook, wopts);
</code></pre>
<br/>
<pre>
<code>
&#60;PK T¥F^¡¾ÕYYdocProps/core.xml<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 &#60;cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">&#60;dcterms:created xsi:type="dcterms:W3CDTF">2015-04-27T09:18:16Z&#60;/dcterms:created>&#60;dcterms:modified xsi:type="dcterms:W3CDTF">2015-04-27T14:42:06Z&#60;/dcterms:modified>
...
</code></pre><pre>
<code>
...
&#60;a:font script="Jpan" typeface="ï¼­ï¼³ ï¼°ã´ã·ãã¯"/>
...
</code></pre>

**Comment by nikolaifischer** [comment]
I think the problem is not the actual writing of the file but the sending to the client. When I open the downloaded file in a texteditor and compare it to the written on the server, I can see that they have different hex codes. 
So, after all this might not be an Issue with js-xlsx but with expressjs or what ever. I read alot about disabeling the live-reload component but that did not do the trick for me. 
Still, I would be very thankful for any help on this matter!

**Comment by nikolaifischer** [comment]
Ok. Sorry for the monologue but I solved it: In the frontend when making the GET Request, the Response Type has to be set to arraybuffer like this:
```javascript
$http({method: 'GET', url: "/abrechnung/exportToExcel/" + JSON.stringify(pageAndFilter.filterByFields) ,
        headers: {'Content-Type': "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}, responseType: "arraybuffer"}).             
             success(function(data, status, headers, config) {  
             // continue like before...
```
I think this is actually an issue in angularJS and has nothing to do with this project. Thank you anyways!

**Comment by SheetJSDev** [comment]
@nikolaifischer thanks for looking into this further!  Similar issues have come up before.  If you don't mind, can you put together a very short and simple example using Angular that we can reference later?

**Comment by nikolaifischer** [comment]
I hope this helps!
Feel free to use or edit it as you wish
```javascript
// Backend:
// Be sure to write the workbook in the type:'buffer'
var wopts = { bookType:'xlsx', bookSST:false, type:'buffer' };
var wbout = XLSX.write(workbook,wopts);		
// Send the buffer:
res.end( wbout );

// AngularJS Frontend:
exportToExcel: function() {

	// You have to use http GET, otherwise browsers will not download the excel
    $http({method: 'GET', url: "/yourAPI/exportToExcel/",
    	// This is important! Tell it to expect an arraybuffer
    	responseType: "arraybuffer"}).             
        success(function(data, status, headers, config) {  
        	// use the saveAs library to save the buffer as a blob on the user's machine. Use the correct MIME type!
            saveAs(new Blob([data],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}), "excel.xlsx");
        }).
        error(function(data, status, headers, config) {

        });  
}
```

**Comment by solidevolution** [comment]
Big thx for the responseType hint!

My long debug line ends in google. now I know much more about http ;)

**Comment by abhinavnigam2207** [comment]
keep the responseType as 'arraybuffer'
$http({
                url: 'www.example-api-url.com/download',
                method: "GET",
                headers: {'Content-type': 'application/json'},
                data: {a:1,b:2},
                responseType: 'arraybuffer'
            });

**Comment by unseen1980** [comment]
@nikolaifischer Thanks for posting the code snippet. Really helped me today 👍

**Comment by priyadarshini2111** [comment]
responseType: "arraybuffer" works...

**Comment by pablosistemas** [comment]
Working fine with ResponseType as arraybuffer in Angular 5 for a xlsx file. My final code:
`return this.httpClient
      .get(environment.apiUrl + 'Agenda/ObterPlanilhaExcel', {
        params: params,
        headers: new HttpHeaders()
          .set('Content-type', 'application/json')
          .set('Accept-Language', 'pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3')
          .set('Accept-Encoding', 'gzip, deflate'),
        responseType: 'arraybuffer'
      }).subscribe(
      retorno => {
        const blob = new Blob([retorno], {type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
        const urlPlanilha = window.URL.createObjectURL(blob);
        this.urlPlanilha = this.sanitizer.bypassSecurityTrustResourceUrl(urlPlanilha);
      },
      erro => this.errorHandler(erro)
    );`

**Comment by reviewher** [comment]
The [angular 1.x](https://github.com/SheetJS/js-xlsx/tree/master/demos/angular) and [angular 2+](https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2) demos specifically show client-side workflows: FileReader to read data + client side export.  Is a http client example necessary or is the info in this issue sufficient?

**Comment by dfloresgonz** [comment]
@pablosistemas What is this.sanitizer? and how does the file gets downloaded?

**Comment by reviewher** [comment]
@dfloresgonz it's using the Angular 2+ `DomSanitizer` service: https://angular.io/api/platform-browser/DomSanitizer

**Comment by damaimrs** [comment]
@nikolaifischer thanks for ur solution. it works for me! 👍

**Comment by vahniteja** [comment]
@nikolaifischer it's  not working, i'm using angularJS  can you help me out 
this is code  written
$http({
method: 'GET',
 url: 'jobOrder/downloadJobOrdersTemplate',
responseType: 'arraybuffer'
}).success(function (data, status, headers) {
 var blob = new Blob([data], {
type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
});
 saveAs(blob, "excel.xlsx");
})
.error(function(data, status, headers, config){
if(status == constants.FORBIDDEN){
location.href = 'login.html';
}else{  			  
$state.transitionTo("ErrorPage",{statusvalue  : status});
}
});

**Comment by indiarocks** [comment]
Hi Nikolaifischer,
This is not working for me. I am still getting a corrupted file.  I am using reactjs and below is the piece of code : 
server.js : 
var wb = XLSX.utils.book_new();
    wb.Props = {
        Tittle : "SheetJs Tutorial",
        Subject : "Test file",
        Author : "Arvind Nagar"
    };
    wb.SheetNames.push("Test-Sheet");
    var ws_data = [["hello", "world"]];
    var ws = XLSX.utils.aoa_to_sheet(ws_data);
    wb.Sheets["Test Sheet"] = ws;

    var wbout = XLSX.write(wb, {bookType:'xlsx', type:'binary'});// if using  buffer, able to downlaod the file but no data. // rather than binary
    console.log('wbout : ', wbout);
    fs.writeFileSync("test.xlsx", wbout);
    res.send(wbout);

client.jsx
axios({
            method: 'get',
            url: `${this.state.url}/exportAll`,
            headers: {'Content-Type': "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
            responseType: "arraybuffer"
        }).then((response) => {
            var blob = new Blob([convetBinaryIntoOctet(response.data)], {type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});
            filesaver.saveAs(blob, "excel.xlsx");

        }).catch((response) => {
            console.error("CheckStatus handleSubmit() :: Error : ", response);
        })

function convetBinaryIntoOctet(data){
      console.log('data : ', data);
      var buf = new ArrayBuffer(data.length); //convert s to arrayBuffer
      var view = new Uint8Array(buf);  //create uint8array as viewer
      for (var i=0; i<data.length; i++) {
        console.log('inserting : ', data[i]);
        view[i] = data.charCodeAt(i) & 0xFF; //convert to octet
      }
    return buf;  
  }
, 
I have tried with both ways by passing binary and buffer as type in server.js, but no luck.


![response](https://user-images.githubusercontent.com/13284027/50580914-83894880-0e22-11e9-92a7-7b4edd201944.JPG)

Any help would be appreciated... thanks.

**Comment by pablosistemas** [comment]
We've faced an issue that looks like the one you are fighting now. I
couldn't explain why this worked exactly, but in backend (.NETCore) we send
an FIleResultContent with the byte array from excel sheet and two
additional headers:

       HttpContext.Response.Headers.Add("Set-Cookie", "fileDownload=true;
path=/");
       HttpContext.Response.Headers.Add("Cache-Control", "no-cache,
no-store, must-revalidate");
       return File(excelbytearray, "application/vnd.ms-excel;",
"excelsheet.xlsx");

In the frontend (Angular 5), we received the HTTP response like this:
return this.httpClient
.get(environment.apiUrl + route, {
params: params,
headers: headers,
responseType: 'arraybuffer'
})
.map(responseObj => {
const blob = new Blob([responseObj], { type:
'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
const urlExcelSheet = window.URL.createObjectURL(blob);
return this.sanitizer.bypassSecurityTrustResourceUrl(urlExcelSheet);
});
I hope it could help you!


Pablo Goulart Silva
Engenharia de Sistemas - Universidade Federal de Minas Gerais


Em qua, 2 de jan de 2019 às 03:08, indiarocks <notifications@github.com>
escreveu:

**Comment by pablosistemas** [comment]
Cheers, man!

Pablo Goulart Silva
Engenharia de Sistemas - Universidade Federal de Minas Gerais


Em ter, 15 de jan de 2019 às 13:56, Tarik Lefi <notifications@github.com>
escreveu:

**Comment by mytrytest** [comment]
I am also getting a corrupted excel file. I am using the express JS server and trying to get from AWS MWS. API will return excel but I am not able to get a proper Excel file. Anyone can help me?

```
const XLSX = require('xlsx');
var ws = XLSX.utils.json_to_sheet(response.data);
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws);

var buf = XLSX.write(wb, {bookType:'xlsx', type:'buffer'}); // generate a nodejs buffer
var str = XLSX.write(wb, {bookType:'xlsx', type:'binary'});
    
XLSX.writeFile(wb, "sheetjs.xlsx");
```

**Comment by GusMartins499** [comment]
> I am also getting a corrupted excel file. I am using the express JS server and trying to get from AWS MWS. API will return excel but I am not able to get a proper Excel file. Anyone can help me?
> 
> ```
> const XLSX = require('xlsx');
> var ws = XLSX.utils.json_to_sheet(response.data);
> var wb = XLSX.utils.book_new();
> XLSX.utils.book_append_sheet(wb, ws);
> 
> var buf = XLSX.write(wb, {bookType:'xlsx', type:'buffer'}); // generate a nodejs buffer
> var str = XLSX.write(wb, {bookType:'xlsx', type:'binary'});
>     
> XLSX.writeFile(wb, "sheetjs.xlsx");
> ```

same issue

**Comment by mytrytest** [comment]
I got the solution and I put updated code in below link.
https://stackoverflow.com/questions/67786734/how-to-download-xlsx-file-from-aws-mws-api-json-response/67965440#67965440

**Comment by SheetJSDev** [comment]
@mytrytest @GusMartins499 When looking into AWS Lambda, a backend change was needed: https://github.com/SheetJS/sheetjs/tree/master/demos/function#aws-lambda

> When reading form data, be sure to include the necessary binary types on the AWS API Gateway console. To do this, navigate to the "Binary Media Types" section in the settings tab of the console. For reading a file, you may need to add "multipart/form-data". For downloading a file, you may need to add "application/vnd.ms-excel".

Does that approach resolve the issue with MWS?

**Comment by klinsc** [comment]
> I hope this helps! Feel free to use or edit it as you wish
> 
> ```js
> // Backend:
> // Be sure to write the workbook in the type:'buffer'
> var wopts = { bookType:'xlsx', bookSST:false, type:'buffer' };
> var wbout = XLSX.write(workbook,wopts);     
> // Send the buffer:
> res.end( wbout );
> 
> // AngularJS Frontend:
> exportToExcel: function() {
> 
>     // You have to use http GET, otherwise browsers will not download the excel
>     $http({method: 'GET', url: "/yourAPI/exportToExcel/",
>         // This is important! Tell it to expect an arraybuffer
>         responseType: "arraybuffer"}).             
>         success(function(data, status, headers, config) {  
>             // use the saveAs library to save the buffer as a blob on the user's machine. Use the correct MIME type!
>             saveAs(new Blob([data],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}), "excel.xlsx");
>         }).
>         error(function(data, status, headers, config) {
> 
>         });  
> }
> ```

For future readers, this is still a valid answer in NextJS@13.

**Comment by SheetJSDev** [comment]
@klinsc The NextJS 13 issue is a bug in NextJS / SWC, see https://github.com/vercel/next.js/discussions/30237?sort=old#discussioncomment-3839045 for more info.  Try setting `swcMinify: false` and raise a new issue if it persists
