### ISSUE TITLE
Excel sheet corrupted on opening, after writing a workbook and sending its output on base64 by mail

### ISSUE THREAD

**Issue by remi-lebigre** [SheetJS/js-xlsx#221]
Hello,

I'm trying fetch a table from my Cordova application, parse its content to a workbook using SheetJS, then sending it via my email plugin.

The parsing and coding in my workbook goes right, i used the whole documentation and posts in issues to try to produce something clean (see code below).

I then try to write it down like so:
<pre><code> var wopts_64 = {bookType: 'xlsx', bookSST: false, type: 'base64', cellStyles: true};
    var wbout = XLSX.write(Email.workbook, wopts_64);
</code></pre>

Here is a part of the console.log of my wbout when i perform a atob() to reverse it from base64 format:
![capture d ecran 2015-05-05 a 10 32 15](https://cloud.githubusercontent.com/assets/7973123/7473256/29cad50e-f33a-11e4-9481-283823e7dfd3.png)

Then I send it by mail with a plugin that creates a file from base64 data, I name it test.xlsx for example.

When I try to open it with Excel on Max, if have the error that asks me to repair the file, though nothing has changed when to sheet opens after repair.

Here is how I write my sheet :
For strings: 
A1.v = 'my sttring with accents été être ça sera';
A1.t = 's';
A1.z = 'General';
For numbers:
A1.v= 0.45
A1.t = 'n'
A1.z ='0.0 €', or '0', depending on my needs

I set the [!ref] with a range from A1 to last bottom right cell + 1 row, never exceeding a hundreds of rows.
Then I loop in all cells to apply:
<pre><code>delete myCell.w
XLSX.utils.format_cell(myCell);
</code></pre>

I double check that the w are written correctly

Do you have any idea where the corrupt error might come from ? Or a way for me to get logs from this 'repair' action ?

**Comment by remi-lebigre** [comment]
Here is the error message, saying:
"Part of the content is unreadable. Do you want to open and repair this workbook?"
![capture d ecran 2015-05-05 a 15 37 27](https://cloud.githubusercontent.com/assets/7973123/7473612/c420a460-f33c-11e4-9729-3cf6fcf83655.png)

**Comment by SheetJSDev** [comment]
@remi-lebigre my initial guess is that there's an encoding problem with the euro symbol in the number format.  Can you try without the euro in the number format and see if the file is valid?

**Comment by remi-lebigre** [comment]
Hello, thanks for the quick reply
I changed the format to z: "0.00" for every number type cell, instead of "0.00 €" as before, but this is not the cause of the issue. (also, the € symbol is correctly set when I open the sheet).

I use xlsmain.js, and I get the same error with the files from this fork (i need to add style to my cells):
https://github.com/protobi/js-xlsx

In my issue, I also removed .s style for each cell. In the end they only contain .t, .v, .z, .w.

Do you know why my "wbout" output console log has these strange encoding symbols instead of tags or other names ?
Also, I found in the same log that my accents è é à ù had a wrong encoding, showing Ã©,Ã§,Ã, as if UTF-8 encoding was missing. Maybe because the first tag where encoding="UTF-8" is broken?

**Comment by SheetJSDev** [comment]
@remi-lebigre can you share a bad file so I can take a look?

**Comment by remi-lebigre** [comment]
I hosted some there:
https://github.com/remi-lebigre/share_files
You have two failing examples, + a successful export. Note that both small sheets are the same, the corruption has a random factor.

**Comment by remi-lebigre** [comment]
I just found out what my problem was: it was the way I attached the output to my email
So there is nothing wrong with SheetJS
At least I went deep in how your system works!
I apologize for the trouble

**Comment by morganzysman** [comment]
Hi Remi,

I have the same issue, the file is uploaded to my bucketS3, but is corrupted. Can you give me more info on how you have solved it ? 

Regards
