### ISSUE TITLE
wrong number parsing 6377,9972

### ISSUE THREAD

**Issue by sysarchitect** [SheetJS/js-xlsx#222]
Hello,

Numbers like 6377,9972 (rounded and shown as 6378,00 in cell) parses as 6,377.10 in js-xlsx.
If value is not rounded in cell and shown as is - parsing is OK.
Could you please fix? Thank you.

Ilya

**Comment by sysarchitect** [comment]
We have fixed it:

In row

return val < 0 ? "-" + write_num_flt(type, fmt, -val) : commaify(""+(Math.floor(val))) + "." + pad0(dec(val, r[1].length),r[1].length);

"dec" function should not be used in its current logic after "." because it rounds .9999 to .1.

**Comment by SheetJSDev** [comment]
I'm reasonably confident we fixed the issue.  You can test against http://oss.sheetjs.com/js-xlsx with a test file
[issue222.xlsx](https://github.com/SheetJS/js-xlsx/files/1069109/issue222.xlsx) :

<img width="201" alt="screen shot 2017-06-12 at 14 16 12" src="https://user-images.githubusercontent.com/6070939/27048426-c5e8552c-4f79-11e7-93d8-9320551af70f.png">
