### ISSUE TITLE
How do I set column width when using alasql?

### ISSUE THREAD

**Issue by MaxNoack** [SheetJS/js-xlsx#224]
How can I set my output column width on my xlsx file to be as wide as the text in every column? I use the following code in my AngularJS controller:

angular.module('myApp').controller("myController", function ($scope){
...
$scope.mydata = (some table data);

$scope.exportData = function () {
        alasql('SELECT \* INTO XLSX("Report.xlsx",{headers:true}) FROM ?',[$scope.mydata]);
       }

};

**Comment by agershun** [comment]
This is rather AlaSQL question, than js-xlsx. Please see the answer here https://github.com/agershun/alasql/issues/181. 
I will implement the similar functionality for js-xlsx version of the export function soon.
