### ISSUE TITLE
Anyway to iterate through single column based on header value

### ISSUE THREAD

**Issue by omnivl** [SheetJS/js-xlsx#226]
is there anyway to interate through non empty cells based on column header value?
have been digging around but cannot get an answer

**Comment by SheetJSDev** [comment]
@omnivl I'm not sure I fully understand the question, so let's look at an example table:

A | B | C | D | E | F
------ | ------ | ------ | ------ | ------ | ------ 
headerA | headerB | headerC | headerD |  | headerF
A1 | B1 | C1 | D1 | E1 | F1
A2 | B2 | C2 | D2 | E2 |
A3 | B3 | C3 | D3 |  | F3
A4 | B4 | C4 | | E4 | F4
A5 | B5 | | D5 | E5 | F5
A6 | | C6 | D6 | E6 | F6
| B7 | C7 | D7 | E7 | F7

In this example, we have a column with a missing header (E) and each row after the first has a missing column (the sixth row, for example, is missing column B).  What is the desired iteration order?

**Comment by reviewher** [comment]
Question unclear, closing
