### ISSUE TITLE
writing back to cells

### ISSUE THREAD

**Issue by jack-sub** [SheetJS/js-xlsx#229]
Ive been using your example you provided, im loading an excel spreadsheet with the following data
Column A - "Address", Column B "Image", Column C "Road"

```
 A                                              B                                    C
```

1   Address------------------------- Image   --------------------Road
2   29 Pitt Street, New York--------Yes--------------------------1
3   50  Pitt Street, New York-------- No------------------------- 2

I then put the following function in to geocode the address in Column A

function codeAddress(callback) {   

  var address = eAdd;
  geocoder = new google.maps.Geocoder();
  geocoder.geocode( { 'address': address, 'region': 'AU'}, function(results, status) {
    if (status == google.maps.GeocoderStatus.OK) {
    souradnice = [results[0].geometry.location.lat(),results[0].geometry.location.lng()];
    callback(souradnice);
  } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });  
}

I then was messing around in the JSON output function and captured each address and geocoded location (in an ideal world instead of using IndexOf i would love to just find the "Address" header)

function to_json(workbook) {

```
var result = {};
var sheet_name_list = workbook.SheetNames;
    sheet_name_list.forEach(function(y) { /* iterate through sheets */
var worksheet = workbook.Sheets[y];

    for (z in worksheet) {
    /* all keys that do not begin with "!" correspond to cell addresses */
      if(z[0] === '!') continue;
      if(z[0].indexOf("B") >= 0) continue;
          eAdd = JSON.stringify(worksheet[z].v);
          codeAddress(function(num) {
          alert(num);
```

});

console.log(y + "!" + z + "=" + JSON.stringify(worksheet[z].v));
  }

My question is how do i get the longtitude and lattitude into the JSON output file like so

{
  "Sheet1": [
    {
      "Address": "29 Pitt Street, New York",
      "Image": "Yes",
      "Road": "1"
      "geometry": { "type": "Point", "coordinates": [ -73.9824935, 40.7175793 ] }
    },
    {
      "Address": "50 Pitt Street, New York",
      "Image": "No",
      "Road": "2"
      "geometry": { "type": "Point", "coordinates": [ -73.9824935, 40.7175793 ] }
    }
  ]
}

Im happy to paypal some beer money! to whoeever has the time to help me out
as my head is spent :)

**Comment by jack-sub** [comment]
Id also be happy to paypal some cash if someone wanted to convert the JSON to GeoJSON file structure as an added output

**Comment by reviewher** [comment]
If you can give an example input file I'm sure someone can whip up a special parse function for you :)
