### ISSUE TITLE
why not write comments in .xlsx file?

### ISSUE THREAD

**Issue by hanxi** [SheetJS/js-xlsx#233]
I think write comments in `.xlsx` file is very useful.

https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L11280-L11358

**Comment by osecki** [comment]
Is there a way to do comments/tooltips with the xlsx package?

**Comment by hanxi** [comment]
Sorry. I have no idea. I just want this feature can be realized. I think it will like this : https://github.com/jmcnamara/XlsxWriter/blob/master/xlsxwriter/comments.py
