### ISSUE TITLE
How to define a cell range

### ISSUE THREAD

**Issue by robgwheeler** [SheetJS/js-xlsx#235]
First off, great tool. I've been playing around with it any i'm struggling with the following:

I'm able to get a cell value from a workbook sheet using the following code

```
if(typeof require !== 'undefined') XLSX = require('xlsx');
var workbook = XLSX.readFile('test.xls');
var sheet_name_list = workbook.SheetNames;
var sheet = sheet_name_list.indexOf('sheet_name');
var sheetF48 = workbook.Sheets[sheet_name_list[sheet]]['F48'].v;
```

What I would like to do next is define a cell range so only those cell values are returned. I have figured out to get a sheet's ref by:

```
var sheet1 = workbook.Sheets[sheet_name_list[sheet_name]]
var range = XLSX.utils.decode_range(sheet1['!ref']);
```

Is it possible to define a cell range by providing the cell references, so only those cell values are returned as an array?

**Comment by SheetJSDev** [comment]
All of the utility functions use the `!ref` key to determine the sheet range.  The sheet_to_json function can give you an array of arrays (if you pass the options argument `header:1`).  For example, using the [RkNumber test file](https://github.com/SheetJS/test_files/blob/master/RkNumber.xlsx):

```
> var XLSX = require("xlsx")
> var wb = XLSX.readFile("RkNumber.xlsx")
> var ws = wb.Sheets.RkNumber;
> XLSX.utils.sheet_to_json(ws, {header:1}) // this is the full sheet
[ [ 'fX100', 'fInt', 'sample' ],
  [ '0', '0', '10000000' ],
  [ '0', '1', '1200455' ],
  [ '1', '0', '0.01' ],
  [ '1', '1', '12004.55' ] ]
> ws['!ref'] = "A2:B4" // change the sheet range to A2:B4
> XLSX.utils.sheet_to_json(ws, {header:1}) // will only use cells within the new range
[ [ '0', '0' ],
  [ '0', '1' ],
  [ '1', '0' ] ]
```

**Comment by reviewher** [comment]
I think you were looking for `sheet_to_json` as explained by @SheetJSDev.  If you can present an example file with your expected input and output, we can whip up a special function
