### ISSUE TITLE
Some formulae dont work when I parse the given Excel

### ISSUE THREAD

**Issue by yagnesh-d-bhat** [SheetJS/js-xlsx#236]
I downloaded this Excel sheet from here and unzipped the file : http://www.contextures.com/SampleData.zip

Then I parsed the Excel file  in here : http://oss.sheetjs.com/js-xlsx/, by uploading it

and then viewing the output as formulae. 

Particularly compare the value at cell number G2 in the Excel and the formulae output.

In the Excel sheet, its F2*E2.

In the formulae output , its G2==1,6

This causes issues when I try to import an Excel sheet into an html table

Now if I go ahead and save the cell G2 specifically in the Excel sheet and then upload the Excel sheet again to the link above, it works well, but now G3 gets affected and so on !!!!

Not sure whats causing this issue. 

I am trying this out in Windows 8 environment and chrome browser.

Any help would be appreciated.

UPDATE : 

I am currently digging into the library and found that this issue is occuring mostly because the value of variable x.f is getting messed up somehow in the method sheet_to_formulae in file xlsx.js that is causing the above issue. Note I inserted the console.log statements myself, to debug the issue, but thats pretty much it, all other code is same as in the repository.

function sheet_to_formulae(sheet) {
    var cmds, y = "", x, val="";
    if(sheet == null || sheet["!ref"] == null) return "";
    var r = safe_decode_range(sheet['!ref']), rr = "", cols = [], C;
    cmds = new Array((r.e.r-r.s.r+1)*(r.e.c-r.s.c+1));
    var i = 0;
    for(C = r.s.c; C <= r.e.c; ++C) cols[C] = encode_col(C);
    for(var R = r.s.r; R <= r.e.r; ++R) {
        console.log("IN R FOR LOOP");
        rr = encode_row(R);
        for(C = r.s.c; C <= r.e.c; ++C) {
            y = cols[C] + rr;
            x = sheet[y];
            val = "";
            if(x === undefined) continue;
            if(x.f != null) val = x.f;
            else if(x.w !== undefined) val = "'" + x.w;
            else if(x.v === undefined) continue;
            else val = ""+x.v;
            console.log("X.V IS " + x.v);
            console.log("X.F IS " + x.f);
            console.log("X.W IS " + x.w);
            console.log("VAL IS " + val);
            console.log("Y IS " + y);
            cmds[i++] = y + "=" + val;
            console.log("CMDS " + cmds[i]);
        }
    }
    cmds.length = i;
    return cmds;
}

Any feedback as to how to proceed?

**Comment by yagnesh-d-bhat** [comment]
Any updates on this? The problem I am currently facing is that the variable x.f has like 50+ implementations - its really hard to figure out which x.f is called

**Comment by reviewher** [comment]
As you probably saw, this was a shared formula issue.  Checking against the site now, the right formula is displayed for the given cell.
