### ISSUE TITLE
It doesn't working with base64 string

### ISSUE THREAD

**Issue by zxy900213** [SheetJS/js-xlsx#238]
var base64 = "the base64 string convert from a xlsx(excel 2007) file.";
var workbook = XLSX.read(base64, { type: "base64" });

the base64 string is from a xls file, it will be ok, but if the base64 string is from a xlsx file, it doesn't working.

Do you know what I mean? my english is very poor. so, if you don't, please forgive me.

**Comment by SheetJSDev** [comment]
Can you share the base64 string and the XLSX file?

**Comment by zxy900213** [comment]
Sorry,I have deleted the excel file. 
I tried to create the same file, but i can't make this problem reappear.
