### ISSUE TITLE
(ver 0.7.9) XLSX.load Function Doesn't work.. : ( 

### ISSUE THREAD

**Issue by JohnJeong123** [SheetJS/js-xlsx#239]
I use XLS, XLSX, node module.

I had to change SSF table_fmt's value ('14' : yyyy-mm-dd')

When I use XLS.SSF.load function (XLS.load('yyyy-mm-dd', 14), It work well.
But At XLSX module, XLSX.SSF.load('yyyy-mm-dd', 14) doesn't work.

below get_table function's result after Calling XLSX.SSF.load('yyyy-mm-dd')

{ '0': 'General',
  '1': '0',
  '2': '0.00',
  '3': '#,##0',
  '4': '#,##0.00',
  '9': '0%',
  '10': '0.00%',
  '11': '0.00E+00',
  '12': '# ?/?',
  '13': '# ??/??',
  '14': 'm/d/yy',
  '15': 'd-mmm-yy',
  '16': 'd-mmm',
  '17': 'mmm-yy',
  '18': 'h:mm AM/PM',
  '19': 'h:mm:ss AM/PM',
  '20': 'h:mm',
  '21': 'h:mm:ss',
  '22': 'm/d/yy h:mm',
  '37': '#,##0 ;(#,##0)',
  '38': '#,##0 ;[Red](#,##0)',
  '39': '#,##0.00;(#,##0.00)',
  '40': '#,##0.00;[Red](#,##0.00)',
  '45': 'mm:ss',
  '46': '[h]:mm:ss',
  '47': 'mmss.0',
  '48': '##0.0E+0',
  '49': '@',
  '56': '"上午/下午 "hh"時"mm"分"ss"秒 "',
  '65535': 'General' }

table '14' is not applied...

**Comment by SheetJSDev** [comment]
We added a [`dateNF` option](https://github.com/sheetjs/js-xlsx#parsing-options) to the parser to override date code 14.  For example, using the [`sheetjs.xlsx`](https://github.com/SheetJS/js-xlsx/files/991287/sheetjs.xlsx) sample from the write test:

```js
> require('xlsx').readFile('sheetjs.xlsx').Sheets.SheetJS.C3
{ t: 'n', v: 41689.604166666664, w: '2/19/14' }
> require('xlsx').readFile('sheetjs.xlsx', {dateNF:'yyyy-mm-dd'}).Sheets.SheetJS.C3
{ t: 'n', v: 41689.604166666664, w: '2014-02-19' }
```
