### ISSUE TITLE
Writing Style Information to the worksheet

### ISSUE THREAD

**Issue by Warun26** [SheetJS/js-xlsx#241]
Hi,

I have data in JSON format which I have written to an excel Workbook using js-xlsx. I wanted to put in font-color for a few cells. Please let me know how I could include that. Here are parts of my code.

 var wbout = XLSX.write(wb, {bookType:'xlsx', bookSST:false, type: 'binary', cellStyles:true});
 saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), "My Excel Worksheet");

I manipulate data in my cells here: Consider data to be an array

var ws = {};
var range = {s: {c:10000000, r:10000000}, e: {c:0, r:0 }};
for(var R = 0; R != data.length; ++R) {
	for(var C = 0; C != data[R].length; ++C) {
		if(range.s.r > R) range.s.r = R;
		if(range.s.c > C) range.s.c = C;
		if(range.e.r < R) range.e.r = R;
		if(range.e.c < C) range.e.c = C;
		var cell = {v: data[R][C], "s": {font: {name: "Arial", sz: 24, color: {rgb: "FFFF0000"}}} };
		if(cell.v == null) continue;
		var cell_ref = XLSX.utils.encode_cell({c:C,r:R});	
		if(typeof cell.v === 'number') cell.t = 'n';
		else if(typeof cell.v === 'boolean') cell.t = 'b';
		else if(cell.v instanceof Date) {
			cell.t = 'n'; cell.z = XLSX.SSF._table[14];
			cell.v = datenum(cell.v);
		}
		else cell.t = 's';
               ws[cell_ref] = cell;
	}
}

Is there any documentation that I can refer to include font-color for few cells in my worksheet? The above code is not adding any foreground color. Could you please tell me where I am going wrong?

**Comment by remi-lebigre** [comment]
I needed to style my cells as you are a few weeks ago, here is what I found:
https://github.com/protobi/js-xlsx#cell-styles
This fork enables cell styles. The one you're posting in does not yet, as far as I understood. So checkout this documentation, and use the new lib files

**Comment by Warun26** [comment]
Thanks for the reply @remi-lebigre . I will try out the other repository.

**Comment by harshdeepHD** [comment]
i have no idea to  use https://github.com/protobi/js-xlsx#cell-styles  please replay
