### ISSUE TITLE
How to set format cell to "Monetary"?

### ISSUE THREAD

**Issue by remi-lebigre** [SheetJS/js-xlsx#242]
Hello,

I use the write function to export an Excel sheet.
I need to format my cells as "Monetary", not "Number".
I use z:"0.00 €", it works but on Excel it not accounted as Monetary, but as a Number.

Is there any way to get set it to a Monetary value?

Thanks in advance

![screencap](https://cloud.githubusercontent.com/assets/7973123/7933796/0cdd5644-0922-11e5-8c0a-00acb0fa825f.png)

**Comment by SheetJSDev** [comment]
There is no special currency format like Date format 14.  Assuming you are using French (France) locale, the format to use is `z:'#,##0.00\\ "€"'`.  To discover this, save a file with the formatting, unzip, and inspect the xl/styles.xml subfile.  You will see a line like this:

```xml
    <numFmt numFmtId="165" formatCode="#,##0.00\ &quot;€&quot;"/>
```

That's the format.  The XML string is `#,##0.00\ &quot;€&quot;`.  Replacing `&quot;` with the literal double-quote and replacing the literal slash with an escaped slash yields `'#,##0.00\\ "€"'`
