### ISSUE TITLE
Demo not working in IE10

### ISSUE THREAD

**Issue by pjlasl** [SheetJS/js-xlsx#244]
To use this library, my company has a requirement that it work with IE 10 and above. I ran the demo to see how it works in IE10 and nothing happens after you browse tot he file.

The console throws this message

> Object doesn't support property or method 'slice' 

``` javascript
function fixdata(data) {
    var o = "", l = 0, w = 10240;
    for(; l<data.byteLength/w; ++l) o+=String.fromCharCode.apply(null,new Uint8Array(data.slice(l*w,l*w+w)));
    o+=String.fromCharCode.apply(null, new Uint8Array(data.slice(l*w)));
    return o;
}
```

It works great in Chrome though.

Any suggestions?

**Comment by newnok6** [comment]
You have to add https://github.com/SheetJS/js-xlsx/blob/master/shim.js in your project

**Comment by pjlasl** [comment]
Thank you! That worked perfectly!

**Comment by reviewher** [comment]
Added a note in the wiki: https://github.com/SheetJS/js-xlsx/wiki/Browser-Errors#ie-object-doesnt-support-property-or-method-slice
