### ISSUE TITLE
Need explanation on how to work with web workers

### ISSUE THREAD

**Issue by pjlasl** [SheetJS/js-xlsx#245]
If I try to use the webworkers (xlsxworker2,xlsxworker1,xlsxworker) option from the demo I get the following message in my console:

GET http://localhost:8383/HTML5Application/xlsxworker2.js net::ERR_EMPTY_RESPONSE

If I perform the read without webworkers it works great! 

My question is: Do I need these webworkers? If so, how do I use them so I don't get an error as shown above?

**Comment by reviewher** [comment]
@pjlasl You don't need web workers, and the browser demo has a fall back in case they are not available (or if you uncheck the web workers box).  The main reason for having them is reading without blocking the browser.  http://oss.sheetjs.com/ uses them to show a spinner while processing a file.

If you don't want to use web workers, follow the [readAsBinaryString / readAsArrayBuffer example in the README](https://github.com/SheetJS/js-xlsx#parsing-workbooks)
