### ISSUE TITLE
How to run from the command line

### ISSUE THREAD

**Issue by ob7** [SheetJS/js-xlsx#246]
Where would I start to get this thing running from my linux command line.  I want to tie it into a script that will output whichever format (csv, json, etc..) to a text file.

**Comment by harbhub** [comment]
There is a module created by SheetJS called "j" which has a Command-Line Interface.

>  npm install -g j
This should install the "j" module globally on your Linux machine.

>  j --help
Use the --help (or -h) flag to see a list of possible flags.

>  j --json <file>
In this example you will convert an excel file into the JSON output using the --json (or -j) flag.  Note that <file> represents the path to the excel file that you want process.

>  j --json ./Downloads/test_file.xlsx
Your final command should look something like this.  The console should display the output.

If you have any further questions about the "j" module then you can check it out here:
https://github.com/SheetJS/j

Does the "j" module solve your problem?

**Comment by harbhub** [comment]
You can put the commands in your shell script just like you would any normal command.

**Comment by ob7** [comment]
You are very helpful thank you.

**Comment by harbhub** [comment]
Glad I could help.

**Comment by ob7** [comment]
How do I emet csv output?

**Comment by ob7** [comment]
I figured it out, you don't use an operator:

j input.xlsx -o input.csv
