### ISSUE TITLE
xlxb to csv with negative number

### ISSUE THREAD

**Issue by bertrand-sifre** [SheetJS/js-xlsx#248]
I try to convert a xlsb to csv. The xls contains one cell with color red and a negative number, after the conversion the cell is "--1485.85 ". There is two minus symbols.

The file is here => http://www.filedropper.com/rednegnumber

My code for the convertion :

``` javascript
var f = document.getElementById('input').files[0];
var reader = new FileReader();
var name = f.name;
reader.onload = function(e) {
  var data = e.target.result;

  var workbook = XLSX.read(data, {type: 'binary'});

  var sheet1 = workbook.Sheets[workbook.SheetNames[0]];
  console.debug(XLSX.utils.sheet_to_csv(sheet1,{"FS":";"}));
};
reader.readAsBinaryString(f);
```

So It's a bug ?

**Comment by bertrand-sifre** [comment]
The positive numbers are black and the negative numbers are red (in excel).
The format code of the cell is : # ##0,00;[RED]-# ##0,00

Function eval_fmt(fmt, v, opts, flen) is called with parameters : 
 - fmt = "[RED]\-# ##0,00"
 - v = -3419.19

This function return -TheNumber, so --3419.19

I update the case "[" 
```javascript
case "[":
                    o = c;
                    while (fmt[i++] !== "]" && i < fmt.length)
                        o += fmt[i];
                    if (o.substr(-1) !== "]")
                        throw 'unterminated "[" block: |' + o + "|";
                    if (fmt[i] === "\\" && fmt[i+1] === "-") {
                        o += fmt[i];
                        o += fmt[i++];
                        i++;
                    }
                    if (o.match(abstime)) {
                        if (dt == null) {
                            dt = parse_date_code(v, opts);
                            if (dt == null)
                                return ""
                        }
                        out[out.length] = {
                            t : "Z",
                            v : o.toLowerCase()
                        }
                    } else {
                        o = ""
                    }
                    break;
```
And it's work, but I don't know if it's correct, it's maybe before the function eval_fmt that the fixed must be applied.

**Comment by SheetJSDev** [comment]
@bertrand-sifre We addressed the negative value in an earlier commit.  The correct format based on our efforts to reproduce is

```
#,##0.00;[RED]-#,##0.00
```

Excel generally generates the file with the US delimiters (comma for thousands, period for decimal) and uses locale settings to determine the separators.  Can you share a file with that specific format?

**Comment by bertrand-sifre** [comment]
Ok. It was two years ago, I don't have the file with the probleme, sorry.

**Comment by SheetJSDev** [comment]
No worries, I think the confusion probably stemmed fro a difference between the excel interface and the actual number format (it will show one thing but actually store something different in the file)
