### ISSUE TITLE
Filter worksheet data based on column option

### ISSUE THREAD

**Issue by Deborah-RP** [SheetJS/js-xlsx#249]
Hi,

I have a case in which I just need to read some of the columns from the worksheet. Is there a way that I can pass in the options to sheet_to_json() function to do this?

My filter object looks like this {postal: "16", fleet: "7", date: "6", starttm: "10"}, keys such as "postal", "fleet" are the name that I would like to use to replace the original header, value represents the column number. 

I'd like to do the following:
1. Only read the selective columns such as 16, 7, 6 and 10. (Important).
2. At the same time, replace the original column header with my own header such as "postal", "fleet"... (Not so important, but nice to have).

Please advise what is the best way to achieve these using js-xlsx.

Thanks,
DZ

**Comment by SheetJSDev** [comment]
`sheet_to_json` takes an options argument.  Set the header field to an array if you want to override the headers.  Here's a sample:

```js
function process_wb(wb, headers) {
	var sheet = wb.Sheets[wb.SheetNames[0]];
	var H = []; // we need to convert the headers object into an array
	Object.keys(headers).forEach(function(h) {
		if(!headers.hasOwnProperty(h)) return;
		H[+headers[h]-1] = h; // the array is zero-indexed
	});
	var s2jopts = {
		range:1, // skip the first row -- remove this line if the first row in your worksheet is data
		header:H
	};
	var json = XLSX.utils.sheet_to_json(sheet, s2jopts);
	json.forEach(function(j) { delete j["undefined"]; }); // this will be unnecessary soon
	return json;
}

/* read the file -- this is how you do it in node */ 
var XLSX = require('xlsx');
var wb = XLSX.readFile('issue_249.xlsx');

var json = process_wb(wb, {postal:16, fleet:7, date:7, starttm:10});
console.log(json);
```

Here is a sample:

![v90nfal](https://cloud.githubusercontent.com/assets/6070939/24162131/f154a734-0e3c-11e7-8f6a-cbfc94cd629b.png)

[issue_249.xlsx](https://github.com/SheetJS/js-xlsx/files/859146/issue_249.xlsx)

The output :

```js
$ node t.js
[ { date: '6', fleet: '7', starttm: '10', postal: '16' },
  { date: '7', fleet: '8', starttm: '11', postal: '17' },
  { date: '8', fleet: '9', starttm: '12', postal: '18' },
  { date: '9', fleet: '10', starttm: '13', postal: '19' },
  { date: '10', fleet: '11', starttm: '14', postal: '20' } ]
```
