### ISSUE TITLE
Error when opening converted file in Excel

### ISSUE THREAD

**Issue by nicholasblexrud** [SheetJS/js-xlsx#250]
I was able to convert .xlsx to .csv using the code below, but when I attempt to open the new file in excel, it's giving me an error: _"The file format and extension of 'data2.csv' don't match. The file could be corrupt or unsafe. Unless you trust its source, don't open it. Do you want to open it anyway?"_

Am I doing something incorrectly?

```
var xlsx = require('xlsx');

// read file
var wb = xlsx.readFile('data.xlsx');

// convert file
var csv = xlsx.utils.sheet_to_csv(wb.Sheets['workbook1']);

// write file
xlsx.writeFile(wb, 'data2.csv');
```

**Comment by SheetJSDev** [comment]
@nicholasblexrud you probably meant to write the CSV, not the workbook object:

```
xlsx.writeFile(csv, 'data2.csv');
```

**Comment by nicholasblexrud** [comment]
@SheetJSDev, thanks for quick response. Upon changing it from ```wb``` to ```csv```, it's now throwing this error:

     ...\node_modules_xlsx\xlsx\xlsx.js:11308 wb.Props.SheetsNames = wb.SheetNames; TypeError: Cannot set property 'SheetNames' of undefined.

**Comment by SheetJSDev** [comment]
CSV was added as a supported write format in `writeFile` so this should just work now.  Please test and reopen if there are any issues
