### ISSUE TITLE
IE 9 support

### ISSUE THREAD

**Issue by neridaj** [SheetJS/js-xlsx#251]
I can't get this working in IE 9 with .xlsx or .xls files. I tried adding the shim but it didn't change the error in IE 9: SCRIPT5007: Unable to get value of the property '0': object is null or undefined. This happens on the demo page, as well: http://oss.sheetjs.com/js-xlsx/. Works great with Chrome and FF, what versions of IE are supported?

Thanks!

**Comment by SheetJSDev** [comment]
@neridaj can you test against the latest version, and do you have an example file?

**Comment by reviewher** [comment]
If you can share a file, please reopen and we can take a look.
