### ISSUE TITLE
writing Xls file 

### ISSUE THREAD

**Issue by ranoy** [SheetJS/js-xlsx#257]
Hi, 
I have just started with this library , seems a great library(except the IE9 issue ,which is known).
Is there any way to write xls files with this library . I have the requirement for xls.

**Comment by terrybu** [comment]
from personal research, XLS seems rarely supported by current JS libraries compared to XLSX that uses XML

**Comment by SheetJSDev** [comment]
We folded XLS into XLSX and added BIFF2 XLS writing.  We will eventually add BIFF8, but for now BIFF2 works all the way back to Excel 2.0
