### ISSUE TITLE
Fil not found error in Node project

### ISSUE THREAD

**Issue by jacka92** [SheetJS/js-xlsx#259]
Get the following error:

fs.js:439  
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);  
                 ^  
Error: ENOENT, no such file or directory 'test_spurs_data.xlsx'  
    at Object.fs.openSync (fs.js:439:18)  
    at Object.fs.readFileSync (fs.js:290:15)  
    at readSync (/home/ubuntu/workspace/node_modules/xlsx/xlsx.js:11387:67)  
    at Object.readFileSync (/home/ubuntu/workspace/node_modules/xlsx/xlsx.js:11403:9)                

when I require the module that uses xlsx. Lots of other people seem to be having this issue but I can't find a solution anywhere. Any help appreciated.

**Comment by SheetJSDev** [comment]
That error is telling you that XLSX is looking at the wrong place.  If you want to see which directory the library is attempting to read from, try writing a test file using fs.writeFileSync just before the XLSX readFile function and see where that test file appears.  I'm guessing it won't be in the directory with your desired file.

**Comment by hhsadiq** [comment]
@jacka92 how you solved this issue. I am having same thing.

**Comment by hhsadiq** [comment]
Sorry, used the awesome answer by @SheetJSDev and it fixed the issue. Thanks guys

**Comment by rakeshlahre** [comment]
Try this
XLSX.readFile(path.join(__dirname, 'test_spurs_data.xlsx'));
