### ISSUE TITLE
This is bug? XLSX.load func don't work.

### ISSUE THREAD

**Issue by JohnJeong123** [SheetJS/js-xlsx#262]
My Node.js application use your XLSX module by overriding.
And I have to local format setting by using SSF.load('yyyy-mm-dd', 14)  function call..

But I faced problem...
When I set XLS.SSF.load('yyyy-mm-dd',14), table_fmt is correctly work.
But When I set XLSX.SSF.load('yyyy-mm-dd', 14), table_fmt is not work. 
and get_table() functions return is not my custom table_fmt setting.

I use version XLSX - 0.7.9

Waiting your response..
please feedback about this problem : (

**Comment by SheetJSDev** [comment]
We're standardizing overriding the date format 14 with a special `dateNF` option.  In retrospect, the problem with manually overriding the table is that technically the old value is correct (the issue lies in the user display, not in the underlying style)
