### ISSUE TITLE
SSF Instace Is not shared?

### ISSUE THREAD

**Issue by JohnJeong123** [SheetJS/js-xlsx#264]
XLSX (v.0.7.9)'s SSF Instacne is not shared?
When I use read(data, option) function, In the callback area, XLSX.SSF's instance is not same.

I suppose that xlsxworker make different instance.
This is bug? or not? 
I want to response.

**Comment by SheetJSDev** [comment]
Across the web worker the instances are different, but the parsers store the table in the workbook object (`wb.SSF`), so it should work across the webworker divide
