### ISSUE TITLE
Saving it for IE9

### ISSUE THREAD

**Issue by ranoy** [SheetJS/js-xlsx#265]
for saving it in IE9 , I am sending the ouptput of XLSX.write fn to my backend which will return the content as it is with the download prompt. I am creating a form on the fly and submitting it.
This method is working for csv (just for testing) but it is not working for this library output. Should I do some encoding or decoding of the output before sending it to my backend.

**Comment by SheetJSDev** [comment]
http://sheetjs.com/demos/table.html uses https://github.com/dcneiner/downloadify as a fallback for IE.  It can generate valid files in IE6:

<img width="884" alt="screen shot 2017-03-21 at 14 18 06" src="https://cloud.githubusercontent.com/assets/6070939/24163538/4017b092-0e41-11e7-9f24-5d246b15fa6e.png">

This is probably an issue with sending binary results back to your server.  I would recommend encoding in base64 (set `type:"base64"` in the write options, then decode on the server end) as an alternative
