### ISSUE TITLE
currency formatting does not work

### ISSUE THREAD

**Issue by Fangmingdu** [SheetJS/js-xlsx#267]
I have cell configured as below
{v:1222.34, z: '$#,##0'}

And I used the write function to xlsx file.
It does not do any formatting. But it works fine for {v:12.34, z:'0.00%'}, with percentage.

I'm referring the library this way. http://oss.sheetjs.com/js-xlsx/xlsx.core.min.js

**Comment by surjikal** [comment]
This is a problem for me as well. Really need this!

**Comment by AllenHW** [comment]
Agreed! Would really love to see this :+1:

**Comment by Gargamil** [comment]
+1

**Comment by thiagoalvernaz** [comment]
I had this same problem, you can solve with parseFloat
cell.t = 'n'; 
cell.z = XLSX.SSF._table[4];
cell.v = parseFloat('2054.78');

**Comment by SheetJSDev** [comment]
There is no need to manually add to the string table anymore.  Just assigning the `z` property to the number format is sufficient -- the writers will automatically build the table for you.

**Comment by ConAntonakos** [comment]
I apologize for the bump and perhaps even tangent, but is it possible to combine the Intl object's properties to dynamically format currency based on locale and currency codes?

I've tried to write to a some of the properties of the `cell` but to no avail. Thanks!

**Comment by SheetJSDev** [comment]
@ConAntonakos your question is unrelated to this issue, and is discussed a bit in [the docs](https://docs.sheetjs.com/#number-formats) but I'll give a quick summary here:

The format code mirrors Excel's treatment of number formats.  There are some built-in formats but it also has its [own custom number format processor](https://support.office.com/en-us/article/Create-or-delete-a-custom-number-format-78f2a361-936b-4c03-8772-09fab54be7f4?ui=en-US&rs=en-US&ad=US).  The core processing logic is housed in [the SSF object, which is added to the library](https://github.com/sheetjs/ssf).  

The primary confusion is that no matter which locale you use, the format codes are stored as if they were the English (US) equivalents: the thousands separator is always stored as a comma, decimal point is always a period, etc.  Unfortunately Excel doesn't even store the locale of the last user who saved the file, so there is no way to figure out exactly what was shown!  

In theory, we could use the `Intl.NumberFormat().format` function to get the string value and try to massage the string to match the requested format, but that has its own challenges.
