### ISSUE TITLE
IE8 binary read fault

### ISSUE THREAD

**Issue by C0d3ine** [SheetJS/js-xlsx#268]
I am trying to parse data from an excel spreadsheet.  it is XLSX.  I am working with IE8, running server-side Javascript.

while pulling data from the excel sheet though, it seems to be missing the first column data completely. I thought it was just for me and cross checked it with the ajax example. Turns out it shares the error as well. Considering this is on IE8 i guess not much importance is given to it. I needed legacy support though.

Thanks for any help!

Here is screenshot, which is really your code-

![image](https://cloud.githubusercontent.com/assets/11499852/8486905/d6e0ca6e-2125-11e5-9296-b8c070601318.png)

**Comment by SheetJSDev** [comment]
This is fixed in 0.8.5.  We are able to run the ajax demo and test against files of all of the supported file formats in IE6!
