### ISSUE TITLE
Auto format date value problem

### ISSUE THREAD

**Issue by calebeaires** [SheetJS/js-xlsx#269]
On XLSX cell date format, when we use date from Brazil. It change the "correctly place" from numbers

On Brazil: 01/03/2015 = Day/Month/Year
On XLSX.read(): 03/01/2015 = Month/Day/Year

Is there some config option, so we can customize it. I do not want to change the CORE javascript. I notice this change must be made on `table_fmt[14]`

**Comment by MrHubble** [comment]
@calebeaires did you find a solution to your problem. I also would like to avoid changing `table_fmt[14]` but it seems to be the cleanest solution I can find right now.

**Comment by reviewher** [comment]
@calebeaires @MrHubble technically format code 14 (`mm/dd/yy`) is supposed to apply locale-specific formatting.  This part is not documented, so to fix this we need to blast through a bunch of locales, figure out the formats used in each locale, then devise a way to specify locale to the formatting library.  @MrHubble what is your current locale and what format does Excel use in your computer?

**Comment by MrHubble** [comment]
@reviewher 

Locale:
````
LANG="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_CTYPE="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_ALL=
````

Excel uses Australia (English), defaults to dd/mm/yy
