### ISSUE TITLE
Looping through rows and columns

### ISSUE THREAD

**Issue by mazing** [SheetJS/js-xlsx#270]
How do I loop through rows and columns without converting the worksheet to csv or json before doing so?

Is it not possible to do something like

```
var worksheet = workbook.Sheets['Sheet1'];

for (var row in worksheet) {
  for (var col in row) {
    console.log(worksheet[row][col]);
  }
}
```

**Comment by Mithgol** [comment]
Convert to an array:

```js
var sheet2arr = function(sheet){
   var result = [];
   var row;
   var rowNum;
   var colNum;
   for(rowNum = sheet['!range'].s.r; rowNum <= sheet['!range'].e.r; rowNum++){
      row = [];
	   for(colNum=sheet['!range'].s.c; colNum<=sheet['!range'].e.c; colNum++){
	      var nextCell = sheet[
	         xlsx.utils.encode_cell({r: rowNum, c: colNum})
	      ];
	      if( typeof nextCell === 'undefined' ){
	         row.push(void 0);
	      } else row.push(nextCell.w);
	   }
	   result.push(row);
   }
   return result;
};
```

Then loop through that array.

**Comment by gregpinero** [comment]
@Mithgol, I seem to not have sheet['!range'].  Is there a new way to get the ranges?

**Comment by reviewher** [comment]
@gregpinero @Mithgol the `!ref` key is exposed by every format.  `!range` was used in XLS but it was ultimately confusing to store the same information in 2 different ways.  Decoding using `decode_range` gives you the range object.  So @Mithgol 's code sample would look like

```js
var sheet2arr = function(sheet){
   var result = [];
   var row;
   var rowNum;
   var colNum;
   var range = XLSX.utils.decode_range(sheet['!ref']);
   for(rowNum = range.s.r; rowNum <= range.e.r; rowNum++){
      row = [];
       for(colNum=range.s.c; colNum<=range.e.c; colNum++){
          var nextCell = sheet[
             XLSX.utils.encode_cell({r: rowNum, c: colNum})
          ];
          if( typeof nextCell === 'undefined' ){
             row.push(void 0);
          } else row.push(nextCell.w);
       }
       result.push(row);
   }
   return result;
};
```

Is it worth adding an "iterator" to the utils? Basically it would take a worksheet and a callback function and repeatedly call it for every cell in the workbook, with an option to include or omit empty cells

**Comment by gregpinero** [comment]
Thanks.  That does work.

I would like something just like sheet2arr above in the utils.  That what I thought XLSX.utils.sheet_to_row_object_array would do but it seemed to give me strange results missing most of the data.

**Comment by reviewher** [comment]
@gregpinero the JSON conversion has a little bit of "intelligence" and is poorly documented :/

For example consider this worksheet:

```
|foo|bar|baz|
| 1 | 2 | 3 |
| 4 | 5 | 6 |
```

Let's say we are in node (the relevant parts work the same way in browser).  Read the workbook:

```js
var XLSX = require('xlsx');
var wb = XLSX.readFile('Workbook4.xlsx');
var ws = wb.Sheets.Sheet1;
```

So by default, the conversion will read the first row and use them as keys in the row object:

```
> XLSX.utils.sheet_to_json(wb.Sheets.Sheet1)
[ { foo: '1', bar: '2', baz: '3' },
  { foo: '4', bar: '5', baz: '6' } ]
```

If a field is missing, the data won't show up.  If there's data in a cell with no header (say, data in cell D2 but not D1), data won't show up.

passing an options argument with `header` controls the output:

Setting header to `1` will generate arrays:

```
> XLSX.utils.sheet_to_json(wb.Sheets.Sheet1, {header:1})
[ [ 'foo', 'bar', 'baz' ], [ '1', '2', '3' ], [ '4', '5', '6' ] ]
```

Setting header to `A` will use the column names:

```
> XLSX.utils.sheet_to_json(wb.Sheets.Sheet1, {header:'A'})
[ { A: 'foo', B: 'bar', C: 'baz' },
  { A: '1', B: '2', C: '3' },
  { A: '4', B: '5', C: '6' } ]
```

You can even give custom labels by passing an array:

```
> XLSX.utils.sheet_to_json(wb.Sheets.Sheet1, {header:["what", "the", "flip"]})
[ { what: 'foo', the: 'bar', flip: 'baz' },
  { what: '1', the: '2', flip: '3' },
  { what: '4', the: '5', flip: '6' } ]
```

The easiest way to control the range is to change the `!ref` value on the sheet.  It's expected to be an A1-style range like "A1:C4".  Changing the value will change the range that the utils look at:

```
> wb.Sheets.Sheet1['!ref']
'A1:C3'
> XLSX.utils.sheet_to_json(wb.Sheets.Sheet1)
[ { foo: '1', bar: '2', baz: '3' },
  { foo: '4', bar: '5', baz: '6' } ]

// now change to A1:A3
> wb.Sheets.Sheet1['!ref'] = 'A1:A3';
'A1:A3'
// the output will change
> XLSX.utils.sheet_to_json(wb.Sheets.Sheet1)
[ { foo: '1' }, { foo: '4' } ]
```

The same parameter also affects writing workbooks -- cells outside of that range are not included:

```
> wb.Sheets.Sheet1['!ref'] = 'A1:C3';
'A1:C3'
> XLSX.read(XLSX.write(wb, {type:'binary'}), {type:'binary'}).Sheets.Sheet1
{ '!ref': 'A1:C3',
  A1: { t: 's', v: 'foo', h: 'foo', w: 'foo' },
  B1: { t: 's', v: 'bar', h: 'bar', w: 'bar' },
  C1: { t: 's', v: 'baz', h: 'baz', w: 'baz' },
  A2: { t: 'n', v: 1, w: '1' },
  B2: { t: 'n', v: 2, w: '2' },
  C2: { t: 'n', v: 3, w: '3' },
  A3: { t: 'n', v: 4, w: '4' },
  B3: { t: 'n', v: 5, w: '5' },
  C3: { t: 'n', v: 6, w: '6' } }
> wb.Sheets.Sheet1['!ref'] = 'A1:A3';
'A1:A3'
> XLSX.read(XLSX.write(wb, {type:'binary'}), {type:'binary'}).Sheets.Sheet1
{ '!ref': 'A1:A3',
  A1: { t: 's', v: 'foo', h: 'foo', w: 'foo' },
  A2: { t: 'n', v: 1, w: '1' },
  A3: { t: 'n', v: 4, w: '4' } }
```

**Comment by gregpinero** [comment]
Thanks, that makes a lot more sense now.  My case was weird because I have the data I want starting at row 5.  But I guess I could have manually given it a header and ignore data before row 4.  I'll give that a try new time.

**Comment by reviewher** [comment]
@gregpinero @mazing @Mithgol we improved the README a bit: https://github.com/SheetJS/js-xlsx#json -- can you take a look when you get a chance?

**Comment by reviewher** [comment]
Closing for now, please follow up with some feedback on the relevant documentation if you get a chance :D

**Comment by Anujmoglix** [comment]
HI My requirement is like this ,how can i achieve this?
![selection_106](https://user-images.githubusercontent.com/26056096/38663051-5b042d02-3e53-11e8-9a45-3c0a8dd5abda.png)

**Comment by sunilbtech9** [comment]
I dnt know

**Comment by rohitmore1995** [comment]
Hello...I have one query ..actually I want to display excel file in select box in html and I'm done with this but after that,when we select option from select box that time i wan to display other information from that excel file..how can I do this...

**Comment by gitBrij** [comment]
> HI My requirement is like this ,how can i achieve this?
> ![selection_106](https://user-images.githubusercontent.com/26056096/38663051-5b042d02-3e53-11e8-9a45-3c0a8dd5abda.png)

I know I'm late but it might help other having same requirement.
You can do that by specifying range attribute like this

`var sheetName = workbook.SheetNames[0];
                    var d = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], { range: 5 });`

And it will return data for the table in d after row 5.
Thanks

**Comment by DivyaArun1985** [comment]
Hi,

I have exported json to excel using XLSX.utils.sheet_to_json and the output looks like below. I would like to display 'Total' and its contents as the last column. How can I achieve that?

![image](https://user-images.githubusercontent.com/49437516/55794170-392efc00-5ae2-11e9-8713-62067a0c67ce.png)

**Comment by gitBrij** [comment]
Try this code, read the properties of first object in json array and create add it into headerInfo array and lastly add Total.

`var headerInfo = ['Event Type', 'Start Date', 'End Date', 'Duration Name'];
for (var key in json[0]) {
    if (headerInfo.indexOf(key) == -1 && key !='Total')
        headerInfo.push(key);
}
headerInfo.push('Total');
const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json, { header: headerInfo });`

**Comment by khaileshkhatri** [comment]
vcvcvc

**Comment by carcigenicate** [comment]
Here's a little helper based on the above corrected code from 9 years ago:
```javascript
/**
 * Adapted from: https://github.com/SheetJS/sheetjs/issues/270#issuecomment-283992162
 * f will be called with each cell, as well as the cell identifier in A1 notation and a tuple of the cell indices (0-based).
 * The passed 'cell' may be undefined if that cell was merged with another cell.
 *
 * Note that this will only iterate cells that are in the range of populated cells, so this should be used after populating the sheet.
 *
 * @param {xlsx.WorkSheet} sheet
 * @param {(cell: xlsx.CellObject | undefined, a1CellId: string, rowColIndices: [number, number]) => void} f
 */
exports.forEachExistingCell = (sheet, f) => {
  const range = xlsx.utils.decode_range(sheet['!ref']);

  for (let row = range.s.r; row <= range.e.r; row++) {
    for (let col = range.s.c; col <= range.e.c; col++) {
      const a1CellId = xlsx.utils.encode_cell({ c: col, r: row });
      const cell = sheet[a1CellId];
      f(cell, a1CellId, [row, col]);
    }
  }
}
```
Example:
Set every cell to the same text:
```javascript
forEachExistingCell(sheet, (cell, a1, indices) => {
  if (cell) {
    cell.v = 'Filled!';
  }
});
```
