### ISSUE TITLE
Get Highest Row

### ISSUE THREAD

**Issue by christopherfeyerabend** [SheetJS/js-xlsx#272]
Is there a function or a call to determine how many rows are in a sheet?

**Comment by robksawyer** [comment]
Here's what I've been doing with EJS.

```
<% indexes = csfData['!ref'].split(':') %>
<% merges = csfData['!merges'] %>
<% firstIndex = indexes[0] %>
<% lastIndex = indexes[1] %>
<% firstRow = parseInt(indexes[0].replace(/[A-Za-z]*/gi,'')) %>
<% lastRow = parseInt(indexes[1].replace(/[A-Za-z]*/gi,'')) %>
<% firstCol = indexes[0].replace(/[0-9]*/gi,'') %>
<% lastCol = indexes[1].replace(/[0-9]*/gi,'') %>
```

**Comment by SheetJSDev** [comment]
Each worksheet has a `!ref` key which encodes a range.  use `decode_range` to parse it:

```js
// assume ws is your worksheet
var range = XLSX.utils.decode_range(ws['!ref']);
var num_rows = range.e.r - range.s.r + 1
var num_cols = range.e.r - range.s.r + 1
```

The `decode_range` utility takes a string like "A2:C4" and returns a [range object](https://github.com/sheetjs/js-xlsx#general-structures)

**Comment by deksden** [comment]
@SheetJSDev 

Small typo in code: 
> ```js
> var num_cols = range.e.r - range.s.r + 1
> ```

I think '.r' needed to be replaced by '.c' to calculate columns instead rows! This thread is still actual to get code snippet via googling
