### ISSUE TITLE
Same data on the subsequent row gets ignored

### ISSUE THREAD

**Issue by Jawad-LiftOff** [SheetJS/js-xlsx#273]
If I have the same data on the subsequent row it gets ignored and I end up in a cell lesser than what actually is. For Example if I have the data like in below grid it just returns me [[a,b,c,d]] instead of [[a,b,c,c,e]]

![image](https://cloud.githubusercontent.com/assets/12030499/8633319/a6d2defa-27df-11e5-9c6b-2439f69d24ca.png)

**Comment by sick** [comment]
+1

**Comment by think01** [comment]
I'm observing something similar: I cannot read repeated values on the same row.
For example, the row:

![image](https://cloud.githubusercontent.com/assets/475965/11446200/f613c1ac-9533-11e5-8b42-337daebc5695.png)

is being read as: `["latest", 3, undefined, undefined]` (and not `["latest", 3, 3, 3]` as expected).

**Comment by SheetJSDev** [comment]
@Jawad-LiftOff @think01 do you have a file that demonstrates the issue? I know we had an issue with ODS repeat cells in the past (which we have since fixed), but if it's XLS or XLSX it should generate every cell

**Comment by think01** [comment]
I use ODS and I workarounded it. Anyway you should be able to reproduce it with a single line like the one I reported above (actually taken from my sheet).

**Comment by SheetJSDev** [comment]
@Jawad-LiftOff If it is only ODS we resolved it in 0.8.2 as per https://github.com/SheetJS/js-xlsx/issues/328.  If it's some other format I'd like to take a look at the affected file.
