### ISSUE TITLE
Unclear how to use wb.Props

### ISSUE THREAD

**Issue by michahell** [SheetJS/js-xlsx#274]
i.e what properties exist? how does the data structure look like? I tried to find documentation on this in the readme (not found, wb.Props occurs once. 'Props' occurs 4 times in total) and on the sheetjs.com website (currently down for me?) Please advise! I'm looking for a way to protect an entire sheet, maybe I am approaching this the wrong way?

**Comment by reviewher** [comment]
Part of the ambiguity is the fact that different formats handle `Props` differently, we will try to sort out the cross-format parts and update the docs soon
