### ISSUE TITLE
Need to load xlsx.js and jszip.js separately for Netsuite suite script

### ISSUE THREAD

**Issue by jimijon** [SheetJS/js-xlsx#275]
I am using Netsuite on the server. When I add xlsx.js it doesn't load or see jszip. The same problem occurs even if I do also load jszip via Netsuite's method.

Is there something obvious I am missing that won't allow me to load jszip sepately?

thanks

**Comment by reviewher** [comment]
The minified builds [`dist/xlsx.core.min.js`](https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.core.min.js) and [`dist/xlsx.full.min.js`](https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.full.min.js) bundle JSZip, so there should be no need to load multiple scripts.  Please test and comment if it does not work
