### ISSUE TITLE
why my file have ref from B1:C6 in sheet 1  not A1:B6

### ISSUE THREAD

**Issue by webinopoly** [SheetJS/js-xlsx#287]
Hello tow day i have issue with pasre js-xlsx
Why my excel  have !ref is B1:C6 not  A1:B6
Please view image

http://prntscr.com/84fe9q

**Comment by reviewher** [comment]
@webinopoly can you share a file?

**Comment by reviewher** [comment]
Please test against http://oss.sheetjs.com/js-xlsx and reopen if the issue persists.
