### ISSUE TITLE
Segfault on node server running on linux with a particular xls file

### ISSUE THREAD

**Issue by Sankluj** [SheetJS/js-xlsx#288]
Hi,

I got a  **Segmentation fault (core dumped)** while trying to execute the **readFile** method on the following xls file. It's only happening while the node server is running on a linux machine. Works fine on windows. 
Something to do with the compiler maybe? I'm using gcc 4.9.2 if that can help.

[The incriminated file!](http://www.filedropper.com/5cqlbs2014bpm1turnoveroflondonbusinesses)

Thanks.

**Comment by reviewher** [comment]
It is possible you ran into a node bug like https://github.com/nodejs/node-v0.x-archive/issues/8208 , especially if it worked on windows and not in linux.

For future reference: the original link 404s, based on the URL my best guess is https://files.datapress.com/london/dataset/london-business-survey-2014-business-performance-and-outlook/LBS%202014%20BPM1%20Turnover%20of%20London%20businesses.xls and this file works in the browser and in node
