### ISSUE TITLE
[Help] Open file using source path, do not using input file

### ISSUE THREAD

**Issue by mrdance92** [SheetJS/js-xlsx#289]
I want to open file xlsx using source path, do not using input file. Please help me!

**Comment by mtada** [comment]
use XMLHttpRequest !
--------------------------------------
    var filePath = 'C:\your\local\path\filename.xlsx';
    var xhr = new XMLHttpRequest();
    xhr.open("GET", filePath, true);
    xhr.overrideMimeType('text\/plain; charset=x-user-defined');
    xhr.onload = function(e) {
        var data = xhr.responseText;
        // dummyObject
        var f = new File([], 'sample.xlsx', {type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});

        var reader = new FileReader();
        reader.onload = function(e) {
            var projectTime = {};
            var wb;
            wb = XLSX.read(data, {type: 'binary'});
            // do something
        };
        reader.readAsBinaryString(f);
    };
    xhr.send(null);

**Comment by Inateno** [comment]
This is old but maybe it'll help someone.
I do this with my nw app:
````
this.workbook = xlsx.readFile( path.join( url, "" ) );
````

**Comment by mtada** [comment]
i did this in making chrome addon.

**Comment by SheetJSDev** [comment]
@mrdance92 if you can follow up with some more details we can figure out what's going on

@Inateno if you have a small NW sample we can link to it in the wiki!

**Comment by Inateno** [comment]
Sorry unfortunately it was a project in a previous company and I can't share anything from it.
I'll try to do a sample if I have some time this week.
