### ISSUE TITLE
[SOLVED] making bold cells, align text to the right

### ISSUE THREAD

**Issue by smalljam** [SheetJS/js-xlsx#290]
Hey guys, thank you for amazing work you are doing.
From what I see bold cell is most requested feature and I needed ability to align text to the right, so made a quick and dirty patch — https://gist.github.com/smalljam/b0e8b7a7e5a218b58e62#file-xlsx-patch
there is also `test.js` example with data structure, where you can use `bold: true` and 'alignRight: true'
Maybe someone will find this usable.
Thanks.
Anton.

**Comment by Suncatcher** [comment]
So how to apply this patch to existing js-xlsx?

**Comment by smalljam** [comment]
I'm not sure it's still relevant for up-to-date version of js-xlsx, I've used "custom" version with patch from above applied by hands :)

**Comment by smalljam** [comment]
please let me know if you will be able to apply it to current version, good luck!

**Comment by pankajnagarsekar** [comment]
@smalljam ur solution works for me.. thanks a tonn 👍

**Comment by Krishnakanth94** [comment]
@pankajnagarsekar  How you appled patch let me know

**Comment by pankajnagarsekar** [comment]
@krishnakanth94 I replaced the code in min.js. that's it

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by paigeflourin** [comment]
hi @smalljam ,

may i get help in applyin it to my application? i need to set the cell values for the specific column but my code looks like this;

```
 let excelCols = rowData;
      /* cell width */
      var wscols = [];
      let cell;
      for (let i = 0; i < excelCols.length; i++) {
        wscols.push({ wch: 20 });  // wch = character
        
      }

      /* convert state to workbook */
      const ws = XLSX.utils.aoa_to_sheet(xlsData);
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "SheetJS");
      ws['!cols'] = wscols;
       

      /* generate XLSX file */
      const wbout = XLSX.write(wb, { type: "array", bookType: "xlsx" });
      /* send to client */
      let fileName = "Report" + moment().format('YYYYMMDDhhmmss') + ".xlsx";
      saveAs(new Blob([wbout], { type: "application/octet-stream" }), fileName);
```


and i need to set these columns under (header 9-15) bold

![image](https://user-images.githubusercontent.com/6951524/55128056-30870f00-514d-11e9-9c17-21c5061aabd1.png)

**Comment by samgodar64** [comment]
facing same issue

**Comment by samgodar64** [comment]
> hi @smalljam ,
> 
> may i get help in applyin it to my application? i need to set the cell values for the specific column but my code looks like this;
> 
> ```
>  let excelCols = rowData;
>       /* cell width */
>       var wscols = [];
>       let cell;
>       for (let i = 0; i < excelCols.length; i++) {
>         wscols.push({ wch: 20 });  // wch = character
>         
>       }
> 
>       /* convert state to workbook */
>       const ws = XLSX.utils.aoa_to_sheet(xlsData);
>       const wb = XLSX.utils.book_new();
>       XLSX.utils.book_append_sheet(wb, ws, "SheetJS");
>       ws['!cols'] = wscols;
>        
> 
>       /* generate XLSX file */
>       const wbout = XLSX.write(wb, { type: "array", bookType: "xlsx" });
>       /* send to client */
>       let fileName = "Report" + moment().format('YYYYMMDDhhmmss') + ".xlsx";
>       saveAs(new Blob([wbout], { type: "application/octet-stream" }), fileName);
> ```
> and i need to set these columns under (header 9-15) bold
> 
> ![image](https://user-images.githubusercontent.com/6951524/55128056-30870f00-514d-11e9-9c17-21c5061aabd1.png)

if anyone find the solution let us know ,i am also facing same issue
