### ISSUE TITLE
Append to an existing file, or create a new one

### ISSUE THREAD

**Issue by anjali-chadha** [SheetJS/js-xlsx#291]
Hi,

I am trying to export my data to xlsx sheet. Also, if some data already exists in the sheet, I should be able to append it to the same sheet.

Any leads on how to append?

Thanks

**Comment by abhishek1191** [comment]
Hi @gracehopper17 ,

Were you able to find any solution ?

I can think of a possible workaround here. We may read the sheet if it is present, then append new data to its contents and then write back the contents to the sheet.

Not sure if above will work, but in my case the sheet size may be large sometimes. So above operation would be heavy and might hamper the performance as well. If there is any in built way, it would be great.

Thanks

**Comment by SheetJSDev** [comment]
Exporting arrays of data is supported through [`aoa_to_sheet`](https://github.com/sheetjs/js-xlsx#array-of-arrays-input) and [`json_to_sheet`](https://github.com/sheetjs/js-xlsx#array-of-objects-input).  Appending data to existing worksheets is supported with `sheet_add_aoa` and `sheet_add_json`

**Comment by Noitidart** [comment]
@SheetJSDev is the append method memory friendly? As in, it won't open up the whole file into memory to append one line?

**Comment by doctorallen** [comment]
I'm curious about this too @Noitidart, did you ever learn if it is memory friendly?
