### ISSUE TITLE
Blank sheets not included in SheetNames

### ISSUE THREAD

**Issue by GenoD** [SheetJS/js-xlsx#292]
I have an Excel file where the first Sheet is simply an image.

![excel sample](https://cloud.githubusercontent.com/assets/5068500/9450490/b7598a12-4a5d-11e5-9a67-1d03331af0e7.png)

Now calling:
console.log(Workbook.SheetNames) 

Prints:
"INPUT DATA", "BURST PRESSURE RESULTS", "PASSIVE PHASE", "PASSIVE IMPEDANCE", "CHART COMPARISON", "OTHER RESULTS", "Calculations and Tables", "Shape Statistics Setup A", "Shape Statistics Setup B", "Sheet1"

My assumption is that Seal Summary is left out because it contains no cells. This would be fine, however when looping through SheetNames for 'INPUT DATA' I get the incorrect index.

![code sample](https://cloud.githubusercontent.com/assets/5068500/9450702/07e95c86-4a5f-11e5-8667-d12663f829f0.png)

This code gives me an index of '0' which follows the console printout above. Using that index via SheetNames[sheetNumber] accesses "Seal Summary". In my code above I have to increment my sheet_name in order to access the correct sheet.

It seems that there is an inconsistency between SheetNames and Sheets. Therefore when parsing SheetNames for a specific name will potentially lead to me accessing the wrong Sheet. Is there currently any workaround for this?

**Comment by SheetJSDev** [comment]
We pushed a change that now reads the underlying chartsheet data as worksheets with a special flag `!type` set to `"charts"`.  It should resolve the aforementioned issue, but we also need to support dialogsheet and macrosheet (Excel 4 Macros), so will keep issue open
