### ISSUE TITLE
Question on the generation of cells with data validation

### ISSUE THREAD

**Issue by anthun** [SheetJS/js-xlsx#293]
From the documentation it isn't clear to me whether it is possible to define any data validation on a cell in a generated xlsx file. I would for example define that a value in a cell can only be chosen from a list such as Green,Blue,Red. 
![2015-08-26_10h25_51](https://cloud.githubusercontent.com/assets/13977581/9488828/d76bdf64-4bdc-11e5-90ea-efc99809f86b.png)
![2015-08-26_10h26_10](https://cloud.githubusercontent.com/assets/13977581/9488835/e27bbbb8-4bdc-11e5-9d1c-276a6c7cfb13.png)

**Comment by aturkelson** [comment]
Any update on this?  I'm also interested....

**Comment by tnrich** [comment]
+1

**Comment by shahbhaveshp** [comment]
Even am looking forward to this feature. Is it implemented/available?

**Comment by kiranaghor** [comment]
+1

**Comment by huoyixin** [comment]
+1

**Comment by nic** [comment]
+1

**Comment by magnifi** [comment]
+1
I would be happy to work on this issue if no one is assigned to it.
This is the workaround that I have used for basic fixed list validation.

https://gist.github.com/magnifi/e020425cf2711ea24d3bec2b782b1e68

**Comment by dbgtx** [comment]
@magnifi  Tried it & doesn't seem to work.
**Can you be so kind to post a working (browser only write) example??**

**Comment by magnifi** [comment]
@dbgtx I have updated the gist and added a working example.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
