### ISSUE TITLE
Failed: Cannot read property 'D1' of undefined

### ISSUE THREAD

**Issue by tansu925098** [SheetJS/js-xlsx#295]
var filepath = '../resource/users.xlsx',
absolutePath = path.resolve(__dirname, filepath);
console.log(absolutePath);
var workbook = XLSX.readFile(absolutePath);
var first_sheet_name = workbook.SheetNames[0];
var worksheet = workbook.Sheets[first_sheet_name];
console.log(worksheet);
for(...){
var cell_address = 'D'+i;
console.log('cell_address:'+cell_address);
var cell = worksheet[cell_address];
console.log('cell:'+cell);
...
}  
Printout shows
C:\Users...\workspace\pro-test\resource\users.xlsx
undefined
total:6
curr:1
cell_address:D1

Message:
    Failed: Cannot read property 'D1' of undefined

**Comment by reviewher** [comment]
@tansu925098 without a file we can't say what's going on.  Can you share that users.xlsx file?

**Comment by SheetJSDev** [comment]
Unfortunately we need to see the file to figure out what's going on.  Closing the issue for now, but please reopen if you can share an offending file!
