### ISSUE TITLE
xlsx.js does not work but xlsx.full.min.js does

### ISSUE THREAD

**Issue by ahmadferdous** [SheetJS/js-xlsx#299]
I tried to use js-xlsx to parse xlsx file on Chrome browser. I first included `xlsx.js` (script tag in HTML file) and saw the following error on console:

```
Uncaught TypeError: undefined is not a function
    read_zip @ xlsx.js:11375
    readSync @ xlsx.js:11396
```

The error occurred on line 11375 in `xlsx.js` file.

```
case "binary": case "array": zip = new jszip(d, { base64:false }); break;
```

When I included `xlsx.full.min.js` instead of `xlsx.js`, it worked. It seems that `jszip` is defined in full version but not done in the other.

Do you think it might be some other issue?

**Comment by stesix** [comment]
I was having the same issue and I solved it by importing jszip (using bower) and making sure that JSZip was getting loaded before XSLX.

The problem is in line 1335: if(typeof JSZip !== 'undefined') jszip = JSZip; and it makes the loading order important for the proper functioning of the library.

**Comment by reviewher** [comment]
`xlsx.core.min.js` and `xlsx.full.min.js` both embed the jszip dependency but `xlsx.min.js` does not -- you have to also include `jszip.js`.  We are going to clarify this in the documentation

**Comment by vsssunder** [comment]
facing the same issue in angular cli project.
How to use xlsx.core.min.js, as in node modules xlsx.js is loaded.
