### ISSUE TITLE
Keep formula inside a cell from the input excel file after genarte the output xls file

### ISSUE THREAD

**Issue by wawanopoulos** [SheetJS/js-xlsx#300]
Hi,

My input xls file contain a formula inside the D1 cell. (SUM of B1 and C1).
After generate the output xls file with js-xlsx  library, my formula is lost.

Is there a way to keep my formul ?

Thanks a lot for your help.

**Comment by fabiooshiro** [comment]
+1

**Comment by AniLau** [comment]
Same issue here

**Comment by AniLau** [comment]
This works for me mcsf@d439645

**Comment by evk0** [comment]
+1

**Comment by SheetJSDev** [comment]
We updated the [write test](https://github.com/SheetJS/js-xlsx/blob/master/tests/write.js#L82-L93) with an example
