### ISSUE TITLE
Inserting Rows

### ISSUE THREAD

**Issue by acgentry** [SheetJS/js-xlsx#301]
I believe this is a big ask, but I am wondering if in the utilities or cell objects there is a way to insert a row into a worksheet and have all corresponding formulas and current cells be updated for their coordinates?

Apologies in advance for a stupid question.

**Comment by jabooth** [comment]
This feature would be so useful. Likewise, I'm new to the project, and not sure if this request is considered too high level for what you are trying to achieve, but surely it would be a feature that would be useful for many many people.

**Comment by mrodal** [comment]
This is basic spreadsheet handling, it's a must! 
Great work by the way

**Comment by SheetJSDev** [comment]
The new `sheet_add_json` and `sheet_add_aoa` helper functions can modify existing worksheet objects.  You can control what data is being added and where it will be added in the worksheet.  See #947 for an example.
