### ISSUE TITLE
Support for reading protected sheets without password

### ISSUE THREAD

**Issue by Mior** [SheetJS/js-xlsx#302]
Hello
We have challenge to read protected XLS file which have some protected but visible and others protected invisible sheets. I don't know password for protection but as it is possible to read those files in MS Excel and also in Apache POI I suspected it should be possible.
However I was not able to find any demo or documentation regarding this and if I read file according to demo it always fails to "File is password-protected" exception.
Is it possible to specify sheets to read only? Or any other way to do so?

Thanks for any advice.

By the way Is project live?

**Comment by reviewher** [comment]
Read-only files are actually stored as a password-protected file with standard password `VelvetSweatshop` .  Best guess: that password is referencing [a Seattle Times article about Microsoft](https://archive.is/20120629191556/http://www.krsaborio.net/research/1980s/89/890423.htm)

Closing in favor of #774
