### ISSUE TITLE
when converts xlsx file have occured undefined 

### ISSUE THREAD

**Issue by guoxunbo** [SheetJS/js-xlsx#303]
I Use the xlsx.js from the version of 0.8.But I found if I chose a file with suffix of xlsx.it will be occured a problem.undefined is not a function.I have see the demo.but the demo do not have this problem.Do I have download wrong js? or what should I do to solve this problem. if the wrong js,could you send the right js to me? my email address is 11603652@qq.com.Thank you

**Comment by guoxunbo** [comment]
function read_zip(data, opts) {
	debugger;
	var zip, d = data;
	var o = opts||{};
	if(!o.type) o.type = (has_buf && Buffer.isBuffer(data)) ? "buffer" : "base64";
	switch(o.type) {
		case "base64": zip = new jszip(d, { base64:true }); break;
		case "binary": case "array": zip = new jszip(d, { base64:false }); break;
		case "buffer": zip = new jszip(d); break;
		case "file": zip=new jszip(d=_fs.readFileSync(data)); break;
		default: throw new Error("Unrecognized type " + o.type);
	}
	return parse_zip(zip, o);
}
the o.type is binary.

**Comment by SheetJSDev** [comment]
Please test against the latest version and re-open if the problem persists.
