### ISSUE TITLE
How to empty a cell ?

### ISSUE THREAD

**Issue by HugoCornu** [SheetJS/js-xlsx#305]
Hi 

I use this to fill a cell : 
     workbook.Sheets['Sample']['C2'] = {v: string, t:'s'}
How do I properly empty a cell ?

**Comment by akaustel** [comment]
Have you tried this?
```js
delete workbook.Sheets['Sample']['C2']
```

**Comment by HugoCornu** [comment]
Thank you

**Comment by huangyifu** [comment]
`function delete_row(sheet,row){//row:int
	var range =XLSX.utils.decode_range(sheet["!ref"]);
	console.log(JSON.stringify(range));
	for(var r=row;r<range.e.r;r++){
		var rowname=XLSX.utils.encode_row(r);
		var nextrowname=XLSX.utils.encode_row(r+1);
		for(var c=0;c<=range.e.c;c++){
			var colname=XLSX.utils.encode_col(c);
			console.log(colname+rowname+" = "+colname+nextrowname);
			sheet[colname+rowname]=sheet[colname+nextrowname];
		}
	}
	var lastrowname=XLSX.utils.encode_row(range.e.r);
	for(var c=0;c<=range.e.c;c++){//delete the last row
		var colname=XLSX.utils.encode_col(c);
		console.log("delete the cell of last row: "+colname+lastrowname);
		delete sheet[colname+lastrowname];		
	}
	//update "!ref"
	range.e.r--;
	sheet["!ref"]=XLSX.utils.encode_range(range);
}

function insert_row(sheet,row,data){
	var range =XLSX.utils.decode_range(sheet["!ref"]);
	console.log(JSON.stringify(range));
	for(var r=range.e.r+1;r>row;r--){
		var rowname=XLSX.utils.encode_row(r);
		var prerowname=XLSX.utils.encode_row(r-1);
		for(var c=0;c<=range.e.c;c++){
			var colname=XLSX.utils.encode_col(c);
			console.log(colname+rowname+" = "+colname+prerowname);
			sheet[colname+rowname]=sheet[colname+prerowname];
		}
	}
	var currowname=XLSX.utils.encode_row(row);
	for(var c=0;c<=Math.max(range.e.c,data.length-1);c++){
		var colname=XLSX.utils.encode_col(c);
		console.log("update the cell of new row: "+colname+currowname+"=="+data[c]);
		if(data[c]){
			sheet[colname+currowname]={v:data[c],t:"s"};
		}else{
			delete sheet[colname+currowname];
		}
		
	}
	//update "!ref"
	range.e.c=Math.max(range.e.c,data.length);
	range.e.r++;
	sheet["!ref"]=XLSX.utils.encode_range(range);
}`
