### ISSUE TITLE
Suggested solution for automatically calculating formulas

### ISSUE THREAD

**Issue by akaustel** [SheetJS/js-xlsx#306]
I would like to add some formulas to my generated spreadsheet, like `SUM(B4:B34)`, however it does not work as one would expect. When opened in a spreadsheet application the value is not calculated automatically, and is shown as empty or whatever was put into the `v`-value.

However, when looking into the problem of recalculating formulas I found and article on http://stackoverflow.com/questions/18355691/set-xlsx-to-recalculate-formulae-on-open, which suggests simply adding a  tag `<calcPr fullCalcOnLoad="1"/>` would resolve the whole issue when opening the document in MS Office, OpenOffice, Google spreadsheet etc.

Anyone who understands the inner workings of js-xlsx might be able to test this. This might be an significantly easier way of solving the issue discussed #105, and maybe some other issues around formulas as well.

**Comment by mdumouchel** [comment]
you might want to look at this issue
https://github.com/SheetJS/js-xlsx/issues/152#issuecomment-145090110

There is a fork that has added support for formulas.

**Comment by akaustel** [comment]
Thanks @mdumouchel! I do, however, believe that #152 does not solve the issue at hand. My issue being that when I have generated a spreadsheet with formulas the resulting values are not calculated when opened in editor of choice. The formulas are present, but not calculated.

**Comment by mdumouchel** [comment]
Would you mind posting some sample code of the problem?

**Comment by SheetJSDev** [comment]
We updated the [write test](https://github.com/SheetJS/js-xlsx/blob/master/tests/write.js#L82-L93) with an example
