### ISSUE TITLE
Create Worksheet

### ISSUE THREAD

**Issue by fonzy2013** [SheetJS/js-xlsx#314]
I see that it is possible to create a sheet/book but I am hoping that it doesn't mean that I need to use the many conversions needed with c: and r: but instead use something like an opposite of the xls.utils.sheet_to_json. 
Could someone please help me with the easist way there is to create a book (no formatting required)?

**Comment by rvdwijngaard** [comment]
hi @fonzy2013  do you already have a solution for this?

**Comment by SheetJSDev** [comment]
The inverse of the `XLSX.utils.sheet_to_json` function where `header:1` is set (so we are dealing with arrays-of-arrays) is in the test suite:

https://github.com/SheetJS/js-xlsx/blob/master/test.js#L1044-L1069

https://github.com/SheetJS/js-xlsx/blob/master/tests/write.js#L46-L70

We will be adding a function like this, named `XLSX.utils.aoa_to_sheet`,  for the 0.9.5 release
