### ISSUE TITLE
and without node.js

### ISSUE THREAD

**Issue by JulienLL** [SheetJS/js-xlsx#318]
Hello,
Is it possible to do the same without the node.js server? I just wish retrieve the values and formulas cells in a js variable to send them to the server.
Thank you in advance for your reply.

**Comment by Sevensnake** [comment]
I agree.

**Comment by reviewher** [comment]
You do not need nodejs at all.  The browser demos like http://oss.sheetjs.com/js-xlsx/ are all static pages and processing happens in the browser.  Nothing touches a server.  See the [gh-pages branch](https://github.com/SheetJS/js-xlsx/tree/gh-pages)
