### ISSUE TITLE
writing sheet with direction RTL (Right-To-Left)  property

### ISSUE THREAD

**Issue by varzager** [SheetJS/js-xlsx#322]
i am trying to create a new file, and applying RTL property on the document.
i couldn't find how i can manipulate sheet styling, and 'direction - RTL' property in particular.

i couldnt find any documentation of how i set styling for sheets or cells.

i would like aswell to set a cell's bgColor and borders.

An answer for the direct question of RTL would be great.
and a reference for a full documentation of all of this package would be perfect.

**Comment by reviewher** [comment]
See https://github.com/SheetJS/js-xlsx/issues/927
