### ISSUE TITLE
[HELP]How to pipe uploaded xlsx file's data to an js object in mem instead of to file on disk?

### ISSUE THREAD

**Issue by morfies** [SheetJS/js-xlsx#323]
Hi, my usecase is supporting import&export for certain search page.
As for export:
Currently I am able to retrieve query result, form the data into a workbook object and then use XLSX to writeFile to a xlsx file on server and then send this file back to browse for user to download.(This works, but I donot want to generate a file on server);
As for import: 
Browser upload the xlsx file through fileupload, and node server receive the file by busboy middleware, but again, how can I just pipe the file data to XLSX directly and then I can parse this data into json, eventually put the uploaded data to mysql?
Thanks very much if you can give me some advice on this.

**Comment by whytheday** [comment]
Looks like there is an example in the readme: https://github.com/SheetJS/js-xlsx#writing-workbooks

**Comment by reviewher** [comment]
Related: https://github.com/SheetJS/js-xlsx/issues/604 It sounds like you are facing a similar issue.
