### ISSUE TITLE
Save File in IE9

### ISSUE THREAD

**Issue by jamessimo** [SheetJS/js-xlsx#329]
Hey guys, I love this library, has been amazing to work with. 

I noticed that the FileSaver.js doesn't support IE 9 and below because IE9 can't make blobs. 

Is there a way to use the Base64 that XLSX.write() returns and create a .xlsx file to upload to a server without using blobs or TypeArrays? Or does it have to be parsed in s2ab().

Thanks

**Comment by reviewher** [comment]
@jamessimo XLSX.write can generate base64 by setting `type:'base64'` in the options argument.

There are two ways to send the data if you don't want to generate a blob:

1) If you can modify the server process, you can then upload the base64 directly to a server and have it converted on the server side.

2) If you can't change the server, you can recover the binary string with `atob` or use a Base64 library to decode.  Then you can send the binary string via XHR
