### ISSUE TITLE
TypeError: _fs is undefined [Tried xlsx.js, xlsx.full.min.js, xlsx.core.min.js]

### ISSUE THREAD

**Issue by SentientBits** [SheetJS/js-xlsx#330]
I have tried every combination I can think of yet I still get _TypeError: _fs is undefined_. Attached is the HTML file with embedded script. 

Am I missing something??

[index.txt](https://github.com/SheetJS/js-xlsx/files/50278/index.txt)

**Full Stack Trace**
TypeError: _fs is undefined
readSync()xlsx.full.min.js (line 18)
readFileSync()xlsx.full.min.js (line 18)
index.html()index.html (line 24)
n.event.dispatch()jquery.min.js (line 3)
n.event.add/r.handle()jquery.min.js (line 3)

**Comment by piotrblasiak** [comment]
I get this as well - any news on this?

**Comment by garrett92895** [comment]
I'm having issues with this as well. Looking through the code, it appears that js-xlsx relies on Node's fs module. I'm not sure how that works (I'm fairly new to all of this), but I'm working on figuring out how to either pull in the fs module as a dependency or create my own wrapper that uses javascript's FileReader underneath (worst case scenario)

**Comment by jacaseyclyde** [comment]
Also running into issues with this. If anyone figures out a good workaround, I'd love to know (and will likewise comment here I figure something out)

**Comment by oscarfonts** [comment]
Look at #285

**Comment by SheetJSDev** [comment]
You can't use `fs` or `XLSX.readFile` in the browser.  Use `XLSX.read`.  If you need specific examples, the demo http://oss.sheetjs.com/js-xlsx/ source is in the [gh-pages branch](https://github.com/SheetJS/js-xlsx/tree/gh-pages) of the repo.  `index.html` uses HTML5 File API and `ajax.html` uses XMLHttpRequest

**Comment by sangeethaharidass** [comment]
I am upload chinese file to upload but i am getting character in wrong format while i am using uploaded file  as csv file.please any one to help me.
[Upload Template_Planner问卷申请模板.xlsx](https://github.com/SheetJS/js-xlsx/files/1867322/Upload.Template_Planner.xlsx)
