### ISSUE TITLE
readFile('filename.xlsx')

### ISSUE THREAD

**Issue by gen1n** [SheetJS/js-xlsx#334]
Hi,
I loaded the xlsx.full.min.js script,
Started as per example,
_if (typeof require !== 'undefined') XLSX = require('xlsx');
var workbook = XLSX.readFile('sample.xlsx');_

But the output gives error:
<i>Javascript error in event handler! Event Type = element</i>

Any suggestions?

**Comment by SheetJSDev** [comment]
I am not familiar with that specific error, but my guess is that you are running in something other than node.  `readFile` does not work in the browser.  You need to get the file data somehow (like an XMLHttpRequest) and call `read`.

If you can share a small project we can take a deeper look.
