### ISSUE TITLE
Parse by columns instead of rows

### ISSUE THREAD

**Issue by DaAwesomeP** [SheetJS/js-xlsx#335]
Hi,
I have a spreadsheet in which the headers are in the left-most column and the data following it to the right. Is there a way to have it format this way? I also could have it move each cell, but I don't think that that's practical.

**Comment by SheetJSDev** [comment]
If you know that in advance, you can copy one of the utility functions like `sheet_to_json` and flip the order of the loops.  The underlying files are always stored in row-major order so the best bet is to read the file normally and change the utility functions to be column-major.  For example, in https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L68 just change the column loops to row loops and vice versa.
