### ISSUE TITLE
Undefined formulas

### ISSUE THREAD

**Issue by hculap** [SheetJS/js-xlsx#338]
Hi,

I have a little problem with reading my xlsx file. After importing file some cells contains only .v and .w but .f property is undefined. It is weird because in Excel all those cells has formulas defined. 

I also found that it happens in cells that has formula copied(by drag and drop action) from other cell. After removing formula and typing it again (not coping) it stats to read it. 

Can you help my? I have big workbook and changing manually all broken cells would by bad idea.

**Comment by darrinholst** [comment]
@hculap did you ever figure this out?

**Comment by hculap** [comment]
It's hard question, because I figured out that that repairing manualy all cells was the only idea, you cand drag and drop formula to copy it you must type it explicit to cell. I think it is bad example of performance optimization which is not implemented in this package.

**Comment by SheetJSDev** [comment]
@hculap It sounds like a shared formula issue.  Can you check against the latest version and see if it persists?

**Comment by SheetJSDev** [comment]
This sounds like a shared formula issue.  Please try against a version >= 0.8.4 and comment if still misses the formula.
