### ISSUE TITLE
require with angular and browserify

### ISSUE THREAD

**Issue by pietersv** [SheetJS/js-xlsx#339]
Received two issue reports related to the `require` calls:
- https://github.com/protobi/js-xlsx/issues/17 
- https://github.com/protobi/js-xlsx/issues/18

The first recommends getting rid of the string concatenations, e.g. `jszip = require('js'+'zip');`
The seconds adds `jszip = require('js'+'zip');` in the case where `typeof exports === undefined`.

These changes make sense to me.  But these  relate to core code inherited from the main https://github.com/SheetJS/js-xlsx branch, and go beyond styling which was the intent of the  https://github.com/protobi/js-xlsx fork.
- **Q1**  Should these changes be made in the main https://github.com/SheetJS/js-xlsx branch?
- **Q2**   Why `require('js' + 'zip')` rather than `require('jszip')`?
- **Q3**  Why not call `require('jszip')` when `exports` is undefined?

**Comment by tkhyn** [comment]
Hello, same concern here. I have errors when importing xslx with [jspm's SystemJS](https://github.com/systemjs/) browser side.

The issue I have is similar to https://github.com/systemjs/builder/issues/45 (I get ``Module jszip not declared as a dependency``)

This could be solved by replacing the dynamic ``require('js' + 'zip')`` by ``require('jszip')``. I second @pietersv's 2nd question!

**Comment by csvan** [comment]
+1

**Comment by SheetJSDev** [comment]
We un-broke all of the require statements in 0.8.7 and included samples with browserify/requirejs/webpack.  Please check against the latest version.

@pietersv if you have a very small angularjs project, we can add to the main repo to make sure we don't break compatibility in future versions

**Comment by SheetJSDev** [comment]
At this point I think we resolved the browserify/angular problems.  @tkhyn I am not familiar with SystemJS, but please test against the latest version and raise a new issue if it is still failing.
