### ISSUE TITLE
Dense Worksheet Representation

### ISSUE THREAD

**Issue by schleumer** [SheetJS/js-xlsx#34]
You guys can make a option to choose range type, `A-1` notation or `[Sheet][Line][Column]`, it would be nice :+1:

**Comment by SheetJSDev** [comment]
@schleumer we didn't flip the default, but if you pass `dense:true` as an option to the various read functions (`XLSX.read`, `XLSX.readFile`, or any of the utilities that generate a worksheet or workbook) the generated worksheets are arrays.  The writers and various utils have been updated to handle both types of worksheets.  We were surprised by the performance difference but are hesitant to change the default until we are sure it won't break older browser versions.
