### ISSUE TITLE
HYPERLINK cell

### ISSUE THREAD

**Issue by slonoed** [SheetJS/js-xlsx#344]
Could I create link cell when creating sheet?

**Comment by rylyade1** [comment]
I have the same problem. Could someone help us out.

**Comment by rdeforest** [comment]
I just ran into this myself. As far as I can tell there's no support for writing formuae in bits/67_wsxml.js.

**Comment by rdeforest** [comment]
Just noticed this is a dupe of #156.

**Comment by Kalo7o** [comment]
Same Problem.
