### ISSUE TITLE
Not refreshed when same file uploaded

### ISSUE THREAD

**Issue by hwanginyeop** [SheetJS/js-xlsx#345]
(This problem also occurs in demo site)
After upload xlsx file first, we need to modify the xlsx file.
And we try to upload and wait for result, but no respond.

How can I solve this problem?
Please give me an advise about this.

Thank you.

**Comment by dafegima** [comment]
I found a solution for this issue. i dont know speak english but i try to explain 
in the line when you set the evenlistener for "change" event
          
**`if (xlf != null) {`
                 `if (xlf.addEventListener) xlf.addEventListener('change', handleFile, false);`
            `}`**

i add another listener for the "click" event

**`if (xlf.addEventListener) xlf.addEventListener('click', fileUploadClick, false);`**

in the **fileUploadClick** function clear the input 

**`function fileUploadClick(e) {`
                `xlf.value = '';`
            `}`**

Full code:

**`function fileUploadClick(e) {`
                `xlf.value = '';`
            `}`**

**`if (xlf != null) {`
                `if (xlf.addEventListener) xlf.addEventListener('change', handleFile, false);`
                `if (xlf.addEventListener) xlf.addEventListener('click', fileUploadClick, false);`
            `}`**

This solution solve this issue for me.
