### ISSUE TITLE
Need to remove an entire row from a worksheet.

### ISSUE THREAD

**Issue by ksumrall** [SheetJS/js-xlsx#352]
I am using this library to make modifications to existing files. I have recently figured out how to find cells and manipulate their values.
The next quest is to **remove a whole row in the worksheet.**
I have reviewed the issues and code and was not able to spot an obvious solution. I'm thinking I can delete the worksheet[cell] values in the row, but the worksheet['!ref'] value will probably need to be changed as well. I'm sure there are other dependencies as well. How should this be done?

**Comment by ksumrall** [comment]
I've come up with the following code and it seems to be working...

```javascript
const ec = (r, c) => {
    return XLSX.utils.encode_cell({r:r,c:c})
}

const delete_row = (ws, row_index) => {
    let range = XLSX.utils.decode_range(ws["!ref"])
    for(var R = row_index; R < range.e.r; ++R){
        for(var C = range.s.c; C <= range.e.c; ++C){
            ws[ec(R, C)] = ws[ec(R+1, C)]
        }
    }
    range.e.r--
    ws['!ref'] = XLSX.utils.encode_range(range.s, range.e)
}

// testing the delete row functionality
let filename = 'C:\\temp\\animals-template.xlsx'
let workbook = XLSX.readFile(filename)
let worksheet = workbook.Sheets[workbook.SheetNames[0]]
delete_row(worksheet, 4)
XLSX.writeFile(workbook, filename)
```

Are there any issues I need to be aware of with this code?

**Comment by edohkodjo** [comment]
It is working pretty fine. But i changed some instructions to have it worked. Here is my code.
```javascript
function ec(r, c){
  return XLSX.utils.encode_cell({r:r,c:c});
}
function delete_row(ws, row_index){
  var variable = XLSX.utils.decode_range(ws["!ref"])
  for(var R = row_index; R < variable.e.r; ++R){
    for(var C = variable.s.c; C <= variable.e.c; ++C){
      ws[ec(R,C)] = ws[ec(R+1,C)];
    }
  }
  variable.e.r--
  ws['!ref'] = XLSX.utils.encode_range(variable.s, variable.e);
}
```
Instead of `let`, i used `var` ; like this
```javascript
var filename = 'C:\\temp\\animals-template.xlsx'
var workbook = XLSX.readFile(filename)
var worksheet = workbook.Sheets[workbook.SheetNames[0]]
delete_row(worksheet, 4)
XLSX.writeFile(workbook, filename)
```

**Comment by reviewher** [comment]
@ksumrall @edohkodjo decent first cut 👍 but there are many features that need to be adjusted when you make a transform like this.

Small bug: what happens if you try to delete a row outside of the current range? No cell is removed but the range is erroneously changed.

Here are a few questions to consider:

1) how should formulae change as a result?  As a dumb example, let's say the formula for cell A2 is `=A1`.  What happens when you delete the first row? The cell that was in A2 is now in A1, and the formula is now circular

2) What happens if you remove a row through a merge?  Say cells B2:D4 are merged, what should happen when row 3 is removed?

3) What happens if you delete the only row in the workbook? Say the only cell with content is A1 and you remove the first row.

**Comment by samufort** [comment]
The solutions proposed above are not deleting the last row of the file.
When you use the `table_to_sheet` function, it renders the last row of the table at the end of file.

Here's the fix 
``` 
const ec = (r, c) => {
    return XLSX.utils.encode_cell({r:r,c:c})
}

const delete_row = (ws, row_index) => {
    let range = XLSX.utils.decode_range(ws["!ref"])
    for(var R = row_index; R <**=** range.e.r; ++R){
        for(var C = range.s.c; C <= range.e.c; ++C){
            ws[ec(R, C)] = ws[ec(R+1, C)]
        }
    }
    range.e.r--
    ws['!ref'] = XLSX.utils.encode_range(range.s, range.e)
}
```

**Comment by SheetJSDev** [comment]
This is a good starting point:

```js
function clamp_range(range) {
	if(range.e.r >= (1<<20)) range.e.r = (1<<20)-1;
	if(range.e.c >= (1<<14)) range.e.c = (1<<14)-1;
	return range;
}

var crefregex = /(^|[^._A-Z0-9])([$]?)([A-Z]{1,2}|[A-W][A-Z]{2}|X[A-E][A-Z]|XF[A-D])([$]?)([1-9]\d{0,5}|10[0-3]\d{4}|104[0-7]\d{3}|1048[0-4]\d{2}|10485[0-6]\d|104857[0-6])(?![_.\(A-Za-z0-9])/g;

/*
	deletes `nrows` rows STARTING WITH `start_row`
	- ws         = worksheet object
	- start_row  = starting row (0-indexed) | default 0
	- nrows      = number of rows to delete | default 1
*/

function delete_rows(ws, start_row, nrows) {
	if(!ws) throw new Error("operation expects a worksheet");
	var dense = Array.isArray(ws);
	if(!nrows) nrows = 1;
	if(!start_row) start_row = 0;

	/* extract original range */
	var range = XLSX.utils.decode_range(ws["!ref"]);
	var R = 0, C = 0;

	var formula_cb = function($0, $1, $2, $3, $4, $5) {
		var _R = XLSX.utils.decode_row($5), _C = XLSX.utils.decode_col($3);
		if(_R >= start_row) {
			_R -= nrows;
			if(_R < start_row) return "#REF!";
		}
		return $1+($2=="$" ? $2+$3 : XLSX.utils.encode_col(_C))+($4=="$" ? $4+$5 : XLSX.utils.encode_row(_R));
	};

	var addr, naddr;
	/* move cells and update formulae */
	if(dense) {
		for(R = start_row + nrows; R <= range.e.r; ++R) {
			if(ws[R]) ws[R].forEach(function(cell) { cell.f = cell.f.replace(crefregex, formula_cb); });
			ws[R-nrows] = ws[R];
		}
		ws.length -= nrows;
		for(R = 0; R < start_row; ++R) {
			if(ws[R]) ws[R].forEach(function(cell) { cell.f = cell.f.replace(crefregex, formula_cb); });
		}
	} else {
		for(R = start_row + nrows; R <= range.e.r; ++R) {
			for(C = range.s.c; C <= range.e.c; ++C) {
				addr = XLSX.utils.encode_cell({r:R, c:C});
				naddr = XLSX.utils.encode_cell({r:R-nrows, c:C});
				if(!ws[addr]) { delete ws[naddr]; continue; }
				if(ws[addr].f) ws[addr].f = ws[addr].f.replace(crefregex, formula_cb);
				ws[naddr] = ws[addr];
			}
		}
		for(R = range.e.r; R > range.e.r - nrows; --R) {
			for(C = range.s.c; C <= range.e.c; ++C) {
				addr = XLSX.utils.encode_cell({r:R, c:C});
				delete ws[addr];
			}
		}
		for(R = 0; R < start_row; ++R) {
			for(C = range.s.c; C <= range.e.c; ++C) {
				addr = XLSX.utils.encode_cell({r:R, c:C});
				if(ws[addr] && ws[addr].f) ws[addr].f = ws[addr].f.replace(crefregex, formula_cb);
			}
		}
	}

	/* write new range */
	range.e.r -= nrows;
	if(range.e.r < range.s.r) range.e.r = range.s.r;
	ws["!ref"] = XLSX.utils.encode_range(clamp_range(range));

	/* merge cells */
	if(ws["!merges"]) ws["!merges"].forEach(function(merge, idx) {
		var mergerange;
		switch(typeof merge) {
			case 'string': mergerange = XLSX.utils.decode_range(merge); break;
			case 'object': mergerange = merge; break;
			default: throw new Error("Unexpected merge ref " + merge);
		}
		if(mergerange.s.r >= start_row) {
			mergerange.s.r = Math.max(mergerange.s.r - nrows, start_row);
			if(mergerange.e.r < start_row + nrows) { delete ws["!merges"][idx]; return; }
		} else if(mergerange.e.r >= start_row) mergerange.e.r = Math.max(mergerange.e.r - nrows, start_row);
		clamp_range(mergerange);
		ws["!merges"][idx] = mergerange;
	});
	if(ws["!merges"]) ws["!merges"] = ws["!merges"].filter(function(x) { return !!x; });

	/* rows */
	if(ws["!rows"]) ws["!rows"].splice(start_row, nrows);
}
```

**Comment by miroslavlison** [comment]
> The solutions proposed above are not deleting the last row of the file.
> When you use the `table_to_sheet` function, it renders the last row of the table at the end of file.
> 
> Here's the fix
> 
> ```
> const ec = (r, c) => {
>     return XLSX.utils.encode_cell({r:r,c:c})
> }
> 
> const delete_row = (ws, row_index) => {
>     let range = XLSX.utils.decode_range(ws["!ref"])
>     for(var R = row_index; R <= range.e.r; ++R){
>         for(var C = range.s.c; C <= range.e.c; ++C){
>             ws[ec(R, C)] = ws[ec(R+1, C)]
>         }
>     }
>     range.e.r--
>     ws['!ref'] = XLSX.utils.encode_range(range.s, range.e)
> }
> ```

const delete_row = (ws, row_index) => {
    let range = XLSX.utils.decode_range(ws["!ref"])
    console.log("range"+ ws['!ref'])
    for(var R = row_index; R <= range.e.r; ++R){
        for(var C = range.s.c; C <= range.e.c; ++C){
            ws[ec(R, C)] = ws[ec(R+1, C)]
        }
    }
    //range.e.r--
    ws['!ref'] = XLSX.utils.encode_range(range.s, range.e)
}

Commenting out range.e.r-- . Fixed removing last row in the table for me.

**Comment by temacoder** [comment]
This removes the contents of the row, but unfortunately does not remove the row itself. If you delete the content of one row, the content of the next row goes up. This interferes if the cells of that row have been merged in a certain way.

**Comment by tsensei** [comment]
@temacoder 

Did you find any solution for deleting row while maintaing merge + styles of subsequent rows ?
