### ISSUE TITLE
Cannot find Workbook stream

### ISSUE THREAD

**Issue by amorimfilip** [SheetJS/js-xlsx#355]
I tried to parse an xlsx file in node but gives the error Cannot find Workbook stream. Then i tried to open in http://sheetjs.com/sexql/ and gives the same error.

The file hasnt password and i can open in ms excel.

Whats the possible problem ?

**Comment by medaamarnadh** [comment]
I also have same issue .

**Comment by SheetJSDev** [comment]
@filipeamorim @medaamarnadh can you share a sample file showing this problem?  Do you also see the problem in http://oss.sheetjs.com/js-xlsx/ ?

**Comment by filipeamorim** [comment]
@SheetJSDev in my case, it was due encryption. 

The content of the xlsx is
![image](https://cloud.githubusercontent.com/assets/7718612/24365163/e6fb5c0e-130c-11e7-865a-556594751b3b.png)

I have the same problem in  http://oss.sheetjs.com/js-xlsx/

**Comment by SheetJSDev** [comment]
Thanks for following up @amorimfilip we will update when we have address encryption

**Comment by amorimfilip** [comment]
@SheetJSDev Forgot to tell you that the file doesn't have any password.  MS Excel opens without asking for a pass.

**Comment by SheetJSDev** [comment]
@amorimfilip if you can share a file, we would love to take a look! dev at sheetjs com

**Comment by reviewher** [comment]
It's likely a read-only file, which is stored as a password-protected file with standard password `VelvetSweatshop`.

Closing in favor of #774
