### ISSUE TITLE
instanceof object that represent sheet. 

### ISSUE THREAD

**Issue by gnachao** [SheetJS/js-xlsx#356]
This might be very stupid question but I really wonder if there is a way to check instance of `sheet` object. 

``` JavaScript

fn(aSheet){
   if(aSheet instanceof Sheet){
      // do work if the parameter is an instance of the object that represent a sheet.
  }

  // as of now, I check like the following
  if(typeof aSheet['!ref'] !== 'undefined'){
    // it's a sheet, do the work.
  }
}
```

Thank you!

**Comment by Chima1707** [comment]
Don't think there is a way, Sheet objects a just arbitrary hash maps which there value adhere to certain, conventions

**Comment by reviewher** [comment]
@gnachao good question :) There's no `instanceof` mantra you can use, and your check is exactly what I would do.

@Chima1707 is correct in saying that it is essentially an object.  There's a reason for that: you can use `JSON.stringify / JSON.parse` on the workbook.  Web workers, featured in the [web demo](http://oss.sheetjs.com/js-xlsx/), used to only allow simple data like strings to be passed back and forth.  You couldn't pass actual objects, so a common technique involves stringifying from the web worker and parsing in the main browser thread.  It is much easier to do that with simple objects.
