### ISSUE TITLE
sheet_to_json

### ISSUE THREAD

**Issue by jfoxworth** [SheetJS/js-xlsx#357]
I was under the impression that this utility function would read in a sheet and return a JSON object. However, it is returning an object with one entry that appears to hold the final value in the sheet. Sheet_to_csv produced the proper results, so I am reasonably sure of the usage.  Thanks

**Comment by gnachao** [comment]
Let `sheet` be the following table,

| City | Population | Rain | Echo |
|------|-----------------|-------|---------|
| Moscow | 11500000 |  |  |    
| Minsk | 2500000 |  |   100 |
| Kyoto | 3000000 | | |   
| Tokyo | 7000000 | 0.34 |  
| Mexico |  12000000 | | 200 |
| Sheet1_Sheet | | | |  

**Ouput of JSON using `XLSX.utils.sheet_to_json`**
```JavaScript
[{"City":"Moscow","Population":"11500000"},  
{"City":"Minsk","Population":"2500000","Echo":"100"},  
{"City":"Kyoto","Population":"3000000"},  
{"City":"Tokyo","Population":"7000000","Rain":"0.34"},  
{"City":"Mexico","Population":"12000000","Echo":"200"},  
{"City":"Sheet1_Sheet"}]
```
I am not sure if this help.

**Comment by jfoxworth** [comment]
I understand that this is the intended result, but the object returned to me when I use the utility has only one entry and it is the last line on the worksheet.

**Comment by reviewher** [comment]
Great example @gnachao +1 

@jfoxworth can you share an example file?

**Comment by gnachao** [comment]
@reviewher Thank you!
@jfoxworth http://gnachao.github.io/demos/demo_sheet_to_json.html It works on my demo so does your object.

**Comment by SheetJSDev** [comment]
@jfoxworth I think you are seeing the same thing as in https://github.com/SheetJS/js-xlsx/issues/280

Long story short: `sheet_to_json` will read the first row to determine row headers.  If the first row happens to have one entry, the exporter will only display that column.

@reviewher gave one solution: https://github.com/SheetJS/js-xlsx/issues/280#issuecomment-286004644 if your actual header row is the second row, set `{range:1}` in the options object.  Another approach is to set `{header:1}` -- it will give you an array of arrays that you can directly address.
