### ISSUE TITLE
Is the sheet_to_json XSS attack safe?

### ISSUE THREAD

**Issue by YueZhaoDreams** [SheetJS/js-xlsx#358]
I read through the code about `sheet_to_json`. I see there is a `safe_format_cell`. Can you confirm that the code is designed for XSS attack. You know the user can enter anything in the excel. We can't trust their input.

**Comment by joepie91** [comment]
XSS isn't really something that should be solved at the data layer; it's specifically about injecting HTML where plaintext is expected (that is later rendered into a HTML page).

This means that in a JSON string, there's not really such a thing as "XSS" - after all, HTML has no special meaning in the context of a JSON string, and it's just bytes. It would make no sense to assume that it's going to be used in HTML somewhere.

The problem of XSS should therefore be solved at the *display* layer - for example, if you render JSON into a HTML page, then *the code that does the rendering* should be escaping values (or, ideally, use a library or function that does it for you, such as React or jQuery's `.text`). The data in the JSON should remain untouched and unescaped.

**Comment by SheetJSDev** [comment]
`safe` refers to the fact that `decode_range` assumes a bounded range like `A1:C3`.  It does not handle the more general case of ranges like `A:C` or `1:3`.   Ultimately, a more robust implementation of the character approach will replace `decode_range` and `safe_decode_range` will be eliminated.
