### ISSUE TITLE
How can i set a formula into a ceil wich works on every lang ? (SUM, ROUND..)

### ISSUE THREAD

**Issue by wawanopoulos** [SheetJS/js-xlsx#359]
I search a way to add into a ceil a formula like : ROUND((A1*B1);2)
If i put this line it will works fine if Excell is in English. But how can i do to modify this formula to be able to make this ROUND function for all Excell languages ?

**Comment by SheetJSDev** [comment]
You have to write the formula in the "English" style, with English names (e.g. ROUND) and commas to separate arguments.  The correct formula in this case is:

```
ROUND((A1*B1), 2)
```

And this should do the right thing in other languages.
