### ISSUE TITLE
xlsx.core.min.js:13 Uncaught Error: Unsupported file NaN

### ISSUE THREAD

**Issue by umimeher** [SheetJS/js-xlsx#367]
hi there.. 
i am using js xlsx to access xlxs file in jquery array to use it..
first, all ok data is fetching from file successfully but
than this error come ...
i dont know from where this error come because i did not edit or even touch the code..
please say something on this issue..

dont mind .. i know my English is poor.. 
ignore it please.
Thanks.. good job.

**Comment by umimeher** [comment]
`alasql.promise('SELECT * FROM XLS("'+filename+'")')
					      .then(function(res){
					      	
						    $("input[name=f_firstname]").val(res[i].A);
				            $("input[name=f_lastname]").val(res[i].B);
				            $("input[name=f_email]").val(res[i].C);
				            $("input[name=f_phone]").val(res[i].D);
				            $("input[name='custom_field_answer[cf_65043]']").val(res[i].E);
`}

**Comment by reviewher** [comment]
This looks like an integration error with alasql, it is better to report the issue there.
