### ISSUE TITLE
sheet_to_json: cannot specify offset if passing an array of headers in options

### ISSUE THREAD

**Issue by hstonge** [SheetJS/js-xlsx#371]
The code of `XLSX.utils.sheet_to_json` allows passing an array for the _header_ property in its options object, but doing so automatically sets the _offset_ variable to 0 and cannot be overridden by an options property.

This is problematic in the case you have an Excel file which includes headers, but do not want to use those same headers in the resulting collection generated by `sheet_to_json`; something that may happen in the case of client/third party files for which you do not want to always trust its header names.

**Comment by hstonge** [comment]
Any updates ?

**Comment by reviewher** [comment]
If you just want to skip the first row, set the option `range:1`.  We've updated the documentation recently to explain this: https://github.com/SheetJS/js-xlsx#json

Here's a simple example:

```js
> var ws = XLSX.utils.aoa_to_sheet([[1,2,3],[4,5,6],[7,8,9]]);
> XLSX.utils.sheet_to_json(ws, {header:1})
[ [ '1', '2', '3' ], [ '4', '5', '6' ], [ '7', '8', '9' ] ] // <-- this still has the first row
> XLSX.utils.sheet_to_json(ws, {header:1, range:1})
[ [ '4', '5', '6' ], [ '7', '8', '9' ] ] // <-- when you set range:1 it skips the first row
```

**Comment by ganesh283** [comment]
I just tried the option of using XLSX.utils.sheet_to_json(ws, {header:1, range:1}) on our application, but it always picks the 1st row. Please help.
