### ISSUE TITLE
Possible to add a worksheet with a name Excel doesn't like

### ISSUE THREAD

**Issue by pietersv** [SheetJS/js-xlsx#376]
This isn't a bug, more of a safety guard that's absent and thus a caution for API users.  It is possible to create a workbook with a seemingly-valid sheet name that Excel cannot open.  

 According to [this source](http://www.accountingweb.com/technology/excel/seven-characters-you-cant-use-in-worksheet-names) there are seven characters not allowable as tab names: `\ / * [ ] : ?` whereas ampersands `&` should be allowable.

However, if a sheet name contains an ampersand, the workbook generates an error on opening.  

`Excel could not open wb.xlsx because some content is unreadable.   Do you want to open and repair this workbook?`
![image](https://cloud.githubusercontent.com/assets/10464727/13428960/ce267e12-df8b-11e5-9044-2fb42431b654.png)

Internally, Excel expects the character `&` to be escaped as `&amp.`   So right now it's up to the API user to escape special characters in worksheet names.

```
 <sheet name="Overal &amp; Total" sheetId="1" r:id="rId1"/>
```

``` js
workbook = {
  "SheetNames": [
    "Plough &amp; Stars"
  ],
  "Sheets": {
    "Plough &amp; Stars": {
      "A1": {  "v": "hello" }
    },
    "!ref": "A1:A1"
}
```

**Comment by mattbasta** [comment]
I ran into this in production yesterday, so this isn't an unusual edge case.

**Comment by iantocristian** [comment]
It looks like a bug to me, the library should properly escape the worksheet names before writing them to workbook.xml (ampersand and other characters that require escaping in xml).

**Comment by nickpalmer** [comment]
Excel has a whole host of issues with sheet names. It cannot handle & : [ ] \ / and has a maximum length of 31 characters.

**Comment by SheetJSDev** [comment]
Here are the "rules":

- bad characters: `: \ / ? * [ ]`
- length: `0 < length < 32`
- Characters apparently can be encoded with the `_xHHHH_` form, so it's possible to make a sheet with a newline character!  However, the length only applies to the decoded characters, so a name like

```
1234567890
1234567890
123456789
```

can be encoded as `1234567890_x000d_1234567890_x000d_123456789`

So definitely js-xlsx should do something.  It's unclear to me how far it should go.

js-xlsx definitely should encode/decode the tab names, so the JS interface works with JS strings and the XLSX writer/reader interface with the encoded values.

I am not sure how js-xlsx should handle invalid names.  Should it

A) throw an error (something about an invalid sheet name)

B) try to "fix" the name by replacing bad characters

Related to this is duplicated SheetNames entries.  If a name shows up twice in the `SheetNames` array (like `["Sheet1", "Sheet2", "Sheet2"]`) how should it be handled?

**Comment by SheetJSDev** [comment]
We started the process by adding a function [`check_wb`](https://github.com/SheetJS/js-xlsx/blob/master/bits/71_wbcommon.js#L102) that is called at the start of the `write` function.  We will slowly add the recommendations here.  Currently it throws an error, but that can change if you think we should pass errors in a different way
