### ISSUE TITLE
Error parsing formula

### ISSUE THREAD

**Issue by oepdtt** [SheetJS/js-xlsx#377]
For the attach xls file and I tried with http://oss.sheetjs.com/js-xlsx/, the formula for C1 is wrong (it should be "A1+B1" while the program returns "0,2"
[Book1.zip](https://github.com/SheetJS/js-xlsx/files/160941/Book1.zip)

**Comment by reviewher** [comment]
@oepdtt Formula parsing was overhauled in `0.8.4`.  This appears to be a case of a shared formula and it works in the current version.
