### ISSUE TITLE
All the line breaks are shown

### ISSUE THREAD

**Issue by Jeff406** [SheetJS/js-xlsx#378]
When I convert a .xlsx file to .json file format (by xlsx.njs bin in bash shell), I notice that all the value includes line breaks are shown with `&#10`. How to not include it in the json ? Please help me to find the solution for this.

Note: I downloaded the original .xlsx from Google spreadsheets, after editing some fields by LibreOffice, this appears.
Example: In a cell, a value like this: 
[id
code
name
type
account_id
created_at]

will become : `"id&#10;code&#10;name&#10;type&#10;account_id&#10;created_at&#10"`

**Comment by reviewher** [comment]
Cannot reproduce in the current version, please test and reopen if the issue persists.
