### ISSUE TITLE
Problems with cells containing unicode characters

### ISSUE THREAD

**Issue by rodryquintero** [SheetJS/js-xlsx#380]
I am trying to extract the first row of an excel sheet to pull the column headers. However, I noticed that for a header called **DÍA** it is completely ignored. Here is the code.

```
var _ = require('lodash');
var XLSX = require('xlsx');

var workbook = XLSX.readFile('test.xlsx');
_.each(workbook.Sheets['SEPTIEMBRE 2015'], function(cellValue, cell) {
    var column = cell.replace(/[0-9]/g, '');
    var row = cell.replace(/[A-Z]/g, '');

    if (row == "1") {
        console.log(column, "...",cellValue.v);
    }
});
```

Here is the result. In bold is the data ignored by js-xsls. 

**A ... DÍA**
B ... MES
C ... ANYO
D ... FECHA DE TOMA
E ... RESPONSABLE
F ... PROCEDENCIA
G ... NOMBRE
H ... APELLIDO
I ... CEDULA
J ... # DE LA UNIDAD
K ... RESULTADO 
L ... RESULTADO 
M ... RESULTADO 
N ... HBSAG
O ... xxx
P ... xxx
Q ... CORE
R ... PLACA DE ARCHIVO

The weird thing is, this just happend when the word **DÍA** is processed. If I put a tilde in any other string it does not ignore it. So, for example, if the cell contained the word **PASTELERíA** it will ignore it.

Please help.

**Comment by SheetJSDev** [comment]
Can you share an offending file?  I tried to manually generate a file with the text you provided in Excel 2016 and I see the correct results.  The XML shared string table shows:

```
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="2" uniqueCount="2"><si><t>DÍA</t></si><si><t>PASTELERíA</t></si></sst>
```

and reading with XLSX shows the same result:

```js
> require('xlsx').readFile('DIA.xlsx').Sheets.Sheet1
{ '!ref': 'A1:A2',
  A1: { t: 's', v: 'DÍA', r: '<t>DÍA</t>', h: 'DÍA', w: 'DÍA' },
  A2:
   { t: 's',
     v: 'PASTELERíA',
     r: '<t>PASTELERíA</t>',
     h: 'PASTELERíA',
     w: 'PASTELERíA' } }
```

**Comment by reviewher** [comment]
Without seeing the `test.xlsx` file it's hard to say what's going on.  Please update to the latest version and test again.  If the problem persists, reopen when you get a chance and attach a sample file so we can take a look
