### ISSUE TITLE
Decimal places when number format

### ISSUE THREAD

**Issue by karaxuna** [SheetJS/js-xlsx#391]
Default decimal place is 2, I want to change it depending on variable, is it possible?

``` javascript
cell.v = parseFloat(cell.v),
cell.t = 'n';
cell.z = XLSX.SSF._table[2]; // 0.00
```

**Comment by reviewher** [comment]
@karaxuna if you want to override a specific format, you can make your own:

```js
delete cell.w;
cell.z = "0.0000";
//XLSX.utils.format_cell(cell); // uncomment if you want to see the value.
```

Test this out and please reopen the issue if you have any problems

**Comment by jalagar** [comment]
I'm using utils.aoa_to_sheet and having trouble overriding the default setting. @reviewher any help? I don't seem to have access to the actual cells themselves.
