### ISSUE TITLE
Read cell which is date type error

### ISSUE THREAD

**Issue by FourLeafClover** [SheetJS/js-xlsx#392]
```
In my excel. the type of cell is date.  the value is 2015/12/30. but when i read the excel the value change to 12/30/15, How can i get the value  the same as '2015/12/30'
```

**Comment by shikelong** [comment]
+1

**Comment by reviewher** [comment]
@FourLeafClover @shikelong What is your current system locale?  This is probably a locale issue, the file itself stores the default date in a specific format (mm/dd/yy) but is supposed to read the system locale.  Related: #269
