### ISSUE TITLE
when using XLSX.read(),there is an error "Uncaught TypeError: Cannot read property 'read' of undefined",need help

### ISSUE THREAD

**Issue by tomfred23** [SheetJS/js-xlsx#393]
when using XLSX.read(),there is an error "Uncaught TypeError: Cannot read property 'read' of undefined", the code is below ,and i use meteor to develop

Template.codein.events({
        'click #stock_save_id':function(){
        var filelist = document.getElementById("stockfile_id"); 
    //if(typeof require !== 'undefined') XLSX = require('xlsx');
        if (filelist.files.length > 0) { 
               for (i=0;i<filelist.files.length;i++)
                 {
                    var reader = new FileReader(); 

```
              reader.onload = function(e) { 
                // 这个事件在读取成功结束后触发
                if (e.error)
                {
                    swal("error is "+e.error);
                }
                else
                { 
                         var xlsrow = e.target.result;
                         alert(xlsrow);
                         var workbook = XLSX.read(xlsrow, {type: 'binary'});
                         //var workbook = XLSX.read(xlsrow);
                         alert("over");


                }

             };

            reader.readAsBinaryString(filelist.files[i]); 
            //reader.readAsDataURL(filelist.files[i]);    
          }
      }
      },
```

**Comment by digelim** [comment]
Try replacing this line:
 //if(typeof require !== 'undefined') XLSX = require('xlsx');
to this:
XLSX = require('xlsx');

**Comment by SheetJSDev** [comment]
@tomfred23 This is happening because `XLSX` is not present.

In nodejs, you need to require the `xlsx` module using a line like @digelim 's comment

In the browser you have to make sure that the source is loaded.  Normally you put a script tag like `<script src="xlsx.js">` in the source.

If the console shows an execution error pertaining to xlsx.js, that is a bug and should be reported.

**Comment by pferreirafabricio** [comment]
I had a similar issue with the XLSX on Vue.js.

I was importing the lib on a component with `import XLSX from 'xlsx'` and getting this error on the console:

    [Vue warn]: Error in v-on handler: "TypeError: Cannot read properties of undefined (reading 'utils')"

And then I noticed on the terminal (which was running the vue.js app) the message: `"export 'default' (imported as 'XLSX') was not found in 'xlsx'`

So I've resolved it by changing the import to: `import * as XLSX from 'xlsx'`

**Comment by rmnlpz** [comment]
@pferreirafabricio brabo! thx bro.

**Comment by pferreirafabricio** [comment]
> @pferreirafabricio brabo! thx bro.

You're welcome, amigo.

**Comment by Eli250** [comment]
@pferreirafabricio Thank you for your suggestion.

I had the same issue in the Next.js project and I did exactly as you mentioned and then it fixed my issue.

**Comment by SheetJSDev** [comment]
Older releases used the CJS library, and bundlers would typically expose those through the default import (`import XLSX from "xlsx"` would be the equivalent of `const XLSX = require("xlsx");`).

0.18.1 enabled ESM when using webpack and 0.18.10 fixed issues with vitejs.  The current documentation is written around the latest version.

The options are to upgrade to the latest version or use the default import.
