### ISSUE TITLE
Reading from binary string Error: End of data reached (data length = 11665014, asked index = 11665015). Corrupted zip ?

### ISSUE THREAD

**Issue by keyscores** [SheetJS/js-xlsx#394]
Hello, this is a great package. It seems like I've come across an edge case that is not handled directly by xslx.

I've been experimenting with creating a buffer from a stream, but I seem to keep getting an 'off-by-one' error.  However it doesn't seem that xslx is catching the error, instead it's in a dependency. 

~/.meteor/packages/netanelgilad_excel/.0.2.6.1re0rnm++os+web.browser+web.cordova/npm/node_modules/xlsx/node_modules/jszip/lib/dataReader.js:25
W20160411-22:27:56.228(-4)? (STDERR)             throw new Error("End of data reached (data length = " + this.lengt
W20160411-22:27:56.228(-4)? (STDERR)                   ^
W20160411-22:27:56.234(-4)? (STDERR) Error: End of data reached (data length = 11665014, asked index = 11665015). Corrupted zip ?

```
    var excelDataBuffer
    var bufs = [];
    stream.on('data', function(d){
         bufs.push(d);
     });
    stream.on('end', function(){
      excelDataBuffer = Buffer.concat(bufs);

      var workbook = excel.read(excelDataBuffer, {type:"binary"});
    });
```

**Comment by keyscores** [comment]
Also posted here: http://stackoverflow.com/questions/36576656/node-trying-to-stream-an-excel-file-and-pass-the-buffer-to-xslx-library

**Comment by banzai-samurai** [comment]
Had the same issue. Try the example below, it helped me:

` 
var excelDataBuffer
var bufs = [];
stream.on('data', function (d){
        let data = new Uint8Array(d);
        let arr = [];
        for(let i = 0, i < data.length; ++i) { arr.push(String.fromCharCode(data[i]))   }
       bufs.push(arr.join(''))
 });
stream.on('end', function(){
      var workbook = excel.read(bufs.join(''), {type:"binary"});
});`

**Comment by keyscores** [comment]
Thanks, yes that did the trick!  Tested with local FS and with GridFS

@SheetJSDev can we update the docs? 

For future readers:


`````

 var excelDataBuffer
    var bufs = [];
    stream.on('data', function(d){
         bufs.push(d);
     });
        stream.on('end', function(){
         excelDataBuffer = Buffer.concat(bufs);

      var workbook = excel.read( excelDataBuffer );
    });
`````

**Comment by SheetJSDev** [comment]
@keyscores we explained the input `type` option in https://github.com/SheetJS/js-xlsx#input-type .

I think there are modules like `concat-stream` that will do the buffer concat logic for you, but that's for another day.
