### ISSUE TITLE
When writing file the date cell text(w) changed to epoch(v)

### ISSUE THREAD

**Issue by lavkesh1608** [SheetJS/js-xlsx#395]
Hi, When i am reading file i have cell values like :
 A34: { t: 'n', v: 42626, w: '9/13/16' },
and after some edition to workbook when i write back to  file it convert cell  like
 A34: { t: 'n', v: 42626, w: '42626' },

The cell.w get replaced with cell.v , why? 
I want back cell values like same as when reading after write.

Please help thanks.

**Comment by reviewher** [comment]
When you read a file, it doesn't store the cell formats by default.  You have to set the option `cellNF:true` in the read call.  For example, in nodejs using XLSX.readFile:

```js
var wb = XLSX.readFile(name_of_file, {cellNF:true});
```

Every cell will have a `z` field with the number format, and then you will see saving the file works.
