### ISSUE TITLE
callback for writeFile?

### ISSUE THREAD

**Issue by barbalex** [SheetJS/js-xlsx#396]
First of all: thanks for this great tool!

`XLSX.writeFile` can take quite some time to finish. And of course an error could occur.

In either case the user should be informed about the outcome. Or maybe the created file should then be opened.

I must be missing something extremely obvious, but I can't find a way to pass a callback and receive error and result.

I have tried adding a callback as fourth parameter. But it seems like this is ignored.

(How) can this be done?

**Comment by lucdetellis** [comment]
+1
This is a JavaScript module. Callbacks are a standard these days (especially with Node.js).

**Comment by mrwhite1** [comment]
Is there any progress on this issue? @barbalex  @lucdetellis  were you guys able use callback? please help if you have any information.

**Comment by barbalex** [comment]
I changed to using https://github.com/guyonroche/exceljs.
With this I can use promises. And format the data in the excel file...

**Comment by SheetJSDev** [comment]
@barbalex @lucdetellis @mrwhite1 you can just wrap `XLSX.write`.

`XLSX.writeFile(wb, filename, opts)` basically

- sets  `opts.bookType` to the appropriate output type based on the file name (so if the filename ends in `.xlsx` then `opts.bookType = "xlsx"`

- sets `opts.type` to buffer and calls `XLSX.write(wb, opts)`

- calls `fs.writeFileSync` on the output of the write.

So it should be straightforward to write something similar: (warning: untested)

```js
function writeFileAsync(wb, filename, opts, cb) {
    	// set up bookType and type options
    	var o = opts||{}; o.type = 'buffer';
	if(!o.bookType) switch(filename.substr(-5).toLowerCase()) {
		case '.xlsx': o.bookType = 'xlsx'; break;
		case '.xlsm': o.bookType = 'xlsm'; break;
		case '.xlsb': o.bookType = 'xlsb'; break;
	default: switch(filename.substr(-4).toLowerCase()) {
		case '.xls': o.bookType = 'biff2'; break;
		case '.ods': o.bookType = 'ods'; break;
	}}
    	// generate output data
	var out;
	try {
		out = XLSX.write(wb, o);
	} catch(e) {
    	    	// call the callback if there's an error
		return cb(e, null);
	}
    	// success! now just write the file asynchronously
	fs.writeFile(filename, out, cb);
}
```
