### ISSUE TITLE
What is the best way to read an excel file in the browser?

### ISSUE THREAD

**Issue by DavidGrinberg** [SheetJS/js-xlsx#398]
Looking at the demos and examples, `readAsBinaryString()` is used to read file data on the browser. However, according to the [documentation ](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsBinaryString) this function is non-standard and seems to be deprecated.

Are there any other preferred ways of reading the file data in the browser?

I should also add that I'm using Dropzone to pull my excel files in, and dropzone gives me a [`File`](https://developer.mozilla.org/en-US/docs/Web/API/File) object to work with

**Comment by barbalex** [comment]
have you tried this?: http://stackoverflow.com/a/18582809/712005

**Comment by DavidGrinberg** [comment]
@barbalex I took another read through the demo code again today and I noticed that they had some alternative ways of reading the file (using readArrayAsBuffer)
