### ISSUE TITLE
Not working with Ajax uploader

### ISSUE THREAD

**Issue by Sevensnake** [SheetJS/js-xlsx#400]
Is there a way to keep the EventListener from not working when you are using a ajax upload control like kendo async. What happens you can add a file once but you cannot add it after that.  What I was trying to do is save the file also. But cannot seem to do that. Any fixes for this.

`<input type="file" name="xlfile" id="xlf"  class="btn btn-primary" kendo-upload
                                               k-async="{ saveUrl: '/File/save', removeUrl: '/Filed/Remove', autoUpload: False}"`

**Comment by Sevensnake** [comment]
Here is what is going on.
[https://www.experts-exchange.com/questions/28939900/File-upload-Telerik-and-sheetJS.html?anchor=a41554203](url)

**Comment by SheetJSDev** [comment]
It looks like that was a kendo issue and it was resolved.  If you can add a note in the project wiki, I'm sure other people will find it helpful!
