### ISSUE TITLE
How to use read from custom column or row?

### ISSUE THREAD

**Issue by alvin992** [SheetJS/js-xlsx#401]
Hi, I'm Alvin. I'm totaly newbie on using javascript. i need complete example of reading custom data on a cell for example (B5) or (A8).

**Comment by lonelydatum** [comment]
This is taken from the example that is already provided from the author.

var XLS = require('xlsx');
var workbook = XLS.readFile('test.xlsx');
var first_sheet_name = workbook.SheetNames[0];
var address_of_cell = 'A8';
var desired_cell = worksheet[address_of_cell];
var desired_value = desired_cell.v;

console.log(desired_value)

**Comment by alvin992** [comment]
Thank you for response mr @lonelydatum , i give a try but yeah stil not understand how to use. . 
there my complete html.
`<!DOCTYPE html>


<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>JS-XLSX Live Demo</title>


<br />

<script src="shim.js"></script>
<script src="jszip.js"></script>
<script src="xlsx.js"></script>

<script src="dist/ods.js"></script>
<script>
var XLS = require('xlsx');
var workbook = XLS.readFile('test.xlsx');
var first_sheet_name = workbook.SheetNames[0];
var address_of_cell = 'A8';
var desired_cell = worksheet[address_of_cell];
var desired_value = desired_cell.v;
console.log(desired_value)
document.getElementById('test');
</script>
value is : <div id="test"></div>
</body>
</html>
`

**Comment by lonelydatum** [comment]
I'm using node to do it instead of HTML. I made a repo that might help you.
https://github.com/lonelydatum/xlsx-demo

Let me know if that does the trick.

**Comment by alvin992** [comment]
Glad to have good response, i'm building HTML website, and im not sure if node can be apply at HTML. i will give a try and read first. :smile:
