### ISSUE TITLE
Sheets not being read in xlsm file but is read if saved as an xlsx

### ISSUE THREAD

**Issue by jeffreytu** [SheetJS/js-xlsx#405]
I have an xlsm file where only one sheet is being read and parsed through js-xlsx. If I save this xlsm file as an xlsx and run it through js-xlsx, it will parse all the sheets. I do not want the extra step of externally saving the file as an xlsx. What can be causing the xlsm file to not parse all the sheets? 

I'm thinking it's the VBA macros causing this since saving it as an xlsx strips the macro. Anyone have ideas around this? Thanks.

**Comment by reviewher** [comment]
@jeffreytu Do you have an example XLSM file?

**Comment by reviewher** [comment]
@jeffreytu  If you can share an example file, please share and reopen the issue.  There are many reasons why the original file would fail but reserving as XLSX would work.  Many writers in the wild do strange things :(
