### ISSUE TITLE
i can read a dbf file?

### ISSUE THREAD

**Issue by joefreire** [SheetJS/js-xlsx#407]
there a way to read a dbf file with js-xlsx?

**Comment by vanchisel** [comment]
Hello @joefreire, 

It doesn't appear that `js-xlsx` cannot read .dbf. I would recommend trying js-harb: http://sheetjs.com/status/ and/or [node-dbf](https://github.com/abstractvector/node-dbf). With `node-dbf` you can parse to csv, etc and then with js-xlsx. I would love to see your results as I'm a Foxpro programmer.

**Comment by SheetJSDev** [comment]
@joefreire @vanchisel [js-harb](https://github.com/SheetJS/js-harb) currently has basic support for DBF.  Ultimately that will be merged into js-xlsx, not sure about the timeframe.

If you are in node, the [j cli command](https://www.npmjs.com/package/j) combines js-xlsx and js-harb in one interface.  You can read in a dbf file and convert to CSV or XLSX or other formats.
