### ISSUE TITLE
I can't upgrade JSZip to ^3.0.0

### ISSUE THREAD

**Issue by limouri** [SheetJS/js-xlsx#408]
I can' t use the current version of **JSZip ^3.0.0**, i get the following log while i try to read an .xlsx file:   '**Error: The constructor with parameters has been removed in JSZip 3.0, please check the upgrade guide.(…)**'

**Comment by jacobmischka** [comment]
JSZip 3.0.0 changed its api to make calls asynchronous. It would be impossible to use JSZip 3.0.0 in this package without essentially rewriting everything to use Promises. Not worth it.

**Comment by SheetJSDev** [comment]
JSZip API changed and they completely removed the sync interface.  It looks like [jszip-sync](https://www.npmjs.com/package/jszip-sync) [source](https://github.com/ericvergnaud/jszip) supports sync, so that is definitely an option moving forward

**Comment by SheetJSDev** [comment]
@limouri @jacobmischka for now to avoid problems, the jszip external dependency was removed and replaced with a local copy.  The bower points to a script that combines the jszip dependency and the core library, so there should be no need to use the external dependency.

**Comment by dustincjensen** [comment]
I would vote for this to be re-opened.

This is, in my opinion a pretty massive flaw. If anyone does what I did and implement JSZip 3.0 to make a zip of images, then bring in js-xlsx, then their JSZip stops working.

It should be at least mentioned as incompatible in the readme, so people know they can or cannot use js-xlsx before spending time implementing it.

**Comment by lyatziv** [comment]
I agree with @dustincjensen this is an issue that needs to be resolved. js-xlsx should either adopt a dependency that supports sync or just include it in the main source and not flag it as a dependency.
That would introduce bloat to users of the JSZip but ... ¯\_(ツ)_/¯ 
The other option is to re-write to support promises.
