### ISSUE TITLE
Merged cell handling

### ISSUE THREAD

**Issue by clayzermk1** [SheetJS/js-xlsx#41]
First, thank you for this library. Second, if I'm in the wrong place to be asking questions, I apologize.

I'm working with documents that contain merged cells. I'd like to iterate over rows and for a particular cell grab the value in a column header above it. The column headers are in merged cells.

Based on the demo, the `sheet.xml` files, and relevant sections of the spec (29500-1 SS 18.3.1.55 and A.2 ln. 2293 through ln. 2298), it seems the merge cell value is always in the top left cell and subsequent cells in the merge range are `undefined`.

Are there any helper attributes on the JS object of a merged cell (`obj.mergeValue` or `obj.isMergeCell`) or is that something I'll have to handle myself?

Cheers and thank you for your time! :beers:

**Comment by vjpr** [comment]
+1 It would be great to have `isMergeCell`.

**Comment by clayzermk1** [comment]
@vjpr I think you should probably turn that into its own issue so it gets the appropriate attention.

@SheetJSDev since it looks like you added this functionality, I think this issue can be safely closed. Thank you for the work!

**Comment by mpolutta** [comment]
Example for write:
```
var merges = wb.sheets["mysheetId"]['!merges'] = [];
//then push merges into array
merges.push( { s: 'A1', e: 'F1' } );
```

**Comment by polarBearGit** [comment]
can you tell me how to set the alignment property of merge cell?

**Comment by ashish-agarwal24** [comment]
can someone tell me how to write in the merged cell?

**Comment by Krishnakanth94** [comment]
https://github.com/Krishnakanth94/Xlsx-styles-working-code
the above code shows merge cells


alignment should be given to starting cell to merge it will we done!
