### ISSUE TITLE
error  import XLSX from 'xlsx'

### ISSUE THREAD

**Issue by lz19870108lz** [SheetJS/js-xlsx#415]
webpack building...
WARNING in ./~/xlsx/jszip.js
Critical dependencies:
12:436-443 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/xlsx/jszip.js 12:436-443

ERROR in ./~/xlsx/dist/cptable.js
Module build failed: Error: ENOENT: no such file or directory, open 'E:\workproject\anXinBaoXian\axplatform_web\node_modules\xlsx\dist\cptable.js'
    at Error (native)
 @ ./~/xlsx/dist/cpexcel.js 807:16-41

**Comment by akhnaeton** [comment]
Have you read issue #285 ?

**Comment by reviewher** [comment]
We have reworked the library to play nice with webpack.  [The web pack demo](https://github.com/SheetJS/js-xlsx/blob/master/demos/webpack/) uses the following config to address the issues:

```js
{
	module: {
		noParse: [/jszip.js$/]
	},
	node: {
		fs: false,
		Buffer: false
	}
}
```

@ArnieGA `XLSX.readFile` and `XLSX.writeFile` are node-only and should not be used in the browser.  `XLSX.read` and `XLSX.write` work with data that you would obtain from a FileReader or XMLHttpRequest.
