### ISSUE TITLE
How to add filter in excel

### ISSUE THREAD

**Issue by shrikantpatwari** [SheetJS/js-xlsx#421]
Hi,

I want to add filters on column which is generated using js-xlsx but I didn't find any documentation regarding that so Is there any functionality written for same

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/#worksheet-object The basic autofilter structure is exposed in the worksheet `!autofilter` key.


https://jsfiddle.net/kwxwg91j/ is a small example

<details>
    <summary>Click to show fiddle code</summary>

```js
/* new workbook with one worksheet */
var wb = XLSX.utils.book_new();
var ws = XLSX.utils.aoa_to_sheet([
["Foo", "Bar", "Baz", "Qux"],
  [1,2,3,4],
  [2,3,4,5],
  [3,4,5,6]
]);
XLSX.utils.book_append_sheet(wb, ws, "Sheet1");

/* set AutoFilter range */
ws['!autofilter'] = { ref:"A1:D4" };

/* ... export file ... */
```
</details>

**Comment by shrikantpatwari** [comment]
@SheetJSDev Thank you very much for adding this feature.
