### ISSUE TITLE
Unable to parse .xlsx file. //11400 Uncaught Error: Unsupported file P

### ISSUE THREAD

**Issue by testcase117** [SheetJS/js-xlsx#425]
I am trying to create a code from scratch to read the contents of a normal excel file but am unable to even read it. I've used the readme for xlsx.js available for github to guide myself and come up with the following code. 

[my_code.txt](https://github.com/SheetJS/js-xlsx/files/308396/my_code.txt)

The error lies in the 46th line as pointed out by the comment in that line, where I've tried to read the excel file as instructed in the readme section. 

Following is a quick-link for xlsx.js src. The error comes out from the exception mentioned in the line 11400 of it.

http://oss.sheetjs.com/js-xlsx/xlsx.js 

Can somebody please help me with this

**Comment by SheetJSDev** [comment]
If you are using `readAsBinaryString` to get the data, you need to set the type to `binary`.  The relevant segment from the demo is https://github.com/SheetJS/js-xlsx/blob/gh-pages/index.html#L265-L282 -- when you assume `rABS`is true and not using web workers, the code is basically:

```
	reader.onload = function(e) {
		var data = e.target.result;
		var wb;
		wb = XLSX.read(data, {type: 'binary'});
		process_wb(wb);
	};
	reader.readAsBinaryString(f);
```
