### ISSUE TITLE
Writing option "type" not documented

### ISSUE THREAD

**Issue by tomkel** [SheetJS/js-xlsx#432]
One of the options that is necessary when using `xslx.write` is the `type` option. According to the function `write_zip_type`, it must be set to `base64`, `binary`, `buffer`, or `file`, or else an error is thrown.

**Comment by reviewher** [comment]
@tomkel you're right, it should be included in https://github.com/SheetJS/js-xlsx/#writing-options.  The possible values mirror the read functions and are listed in another issue: https://github.com/SheetJS/js-xlsx/issues/337#issuecomment-281284479

| `type`     | expected input                                                           |
|------------|--------------------------------------------------------------------------|
| `"base64"` | string: base64 encoding of the file                                      |
| `"binary"` | string:  binary encoded string (the `n`-th byte is `data.charCodeAt(n)`) |
| `"buffer"` | nodejs Buffer                                                            |
| `"file"`   | string: filename that will be written and processed (nodejs only)           |

@SheetJSDev that table should be copied into the README
