### ISSUE TITLE
Clean build failing due to missing npm codepage 1.3.8 module

### ISSUE THREAD

**Issue by mbeynon** [SheetJS/js-xlsx#434]
xlsx 0.8.0 depends on codepage "~1.3.6".  The npm logic finds 1.3.8 and tries to pull that, but is failing with the following output on our jenkins server:

npm  ERR!  fetch failed  https://registry.npmjs.org/codepage/-/codepage-1.3.8.tgz
npm  WARN  will retry, error on last attempt: Error: fetch failed with status code 502

Manually pulling this URL fails with 502 also.  Did something break with the published npm packages for codepage?

**Comment by reviewher** [comment]
@mbeynon what version of node / npm are you using? Also, can you check if the same problem shows up with xlsx `0.8.1`?
