### ISSUE TITLE
Error mappings in currency cells

### ISSUE THREAD

**Issue by mcaballeroh** [SheetJS/js-xlsx#435]
Error detected in sheet_to_csv and sheet_to_json methods when cells have currency values.
Cells with values like $3.0 are mapped to $2.10 in output of sheet_to_csv and sheet_to_json methods

Attaching test project to reply bug.
[currency-problem.zip](https://github.com/SheetJS/js-xlsx/files/351001/currency-problem.zip)

**Comment by SheetJSDev** [comment]
I believe that we addressed the problem at some point, the file appears to be properly processed in the web browser and the node script:

<img width="324" alt="screen shot 2017-05-16 at 14 46 38" src="https://cloud.githubusercontent.com/assets/6070939/26122739/7f738078-3a46-11e7-8192-3edfcfb32f3d.png">
