### ISSUE TITLE
Integration with almond vs require

### ISSUE THREAD

**Issue by scottnc27603** [SheetJS/js-xlsx#436]
This really isn't an issue, but I wanted to post here to see if I could get some help.  I really need to integrate js-xlsx into our project.  The issue that I'm running into is that we are using almond due to the fact that we are using cesium.  Our underlying project, doesn't use AMD so we really haven't had any conflicts with this issue so far.  Since almond(https://github.com/requirejs/almond), a lightweight version of require, the lib defines 'define' a little differently.  I'm having issues getting jszip and js-xlxs to load properly.  I'm trying to work through the issues with cesium to use the non almond version, but that is a pretty big change.  So far, I haven't had any luck.  I did find the amdclean(https://github.com/gfranko/amdclean) project as well which turns AMD code into pure Javascript.  If anyone has any suggestions, or there's a way to build this library in away that will load in almond, please let me know.  
TIA,
Scott

**Comment by SheetJSDev** [comment]
@scottnc27603 please check against the latest version.  We included a [require.js demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/requirejs)
