### ISSUE TITLE
Remove cpexcel.js in webpack

### ISSUE THREAD

**Issue by rusty1s** [SheetJS/js-xlsx#438]
When I build my project with this module via webpack and the following configuration:

``` js
node: {
    fs: 'empty',
  },
  externals: [
    { './jszip': 'jszip' },
    { './cptable': 'var cptable' },
  ],
```

it gets really large. I noticed that rows like

``` js
D[152] = "�����������������������������������������������������������������쁀쁁쁂쁃쁄쁅쁆쁇쁈쁉쁊쁋
```

are also included in my bundle file. How can i remove `cpexcel.js`, so that it gets no longer included?

Thanks.

**Comment by SheetJSDev** [comment]
@rusty1s those are coming from [the codepage library](https://github.com/sheetjs/js-codepage), which is needed for XLS files and some other corner cases.  If you don't expect to have to deal with XLS files (say, if you know the source is always producing XLSX or XLSB files), then you can safely suppress it by using webpack resolve:

```js
	resolve: {
		alias: { "./dist/cpexcel.js": "" }
	}
```

This will be added to the README
