### ISSUE TITLE
Demo / Base64 not working?

### ISSUE THREAD

**Issue by jhiver** [SheetJS/js-xlsx#441]
Hello, I have trouble parsing Base64 data uploaded from disk with this library. I tried the demo page and it doesn't seem to be working either.

You can try pasting this Base64 CSV data:

[test.txt](https://github.com/SheetJS/js-xlsx/files/365586/test.txt)

Here:

https://www.base64decode.org/

And it decodes fine.

However trying the same thing on the demo gives "xlsx.js:11397 Uncaught Error: Unsupported file 109" on the console.

Any ideas?

**Comment by reviewher** [comment]
The library does not currently support CSV reading at the moment.  Most CSV readers follow the RFC 4180, but Excel follows a different set of rules.  We are working on a new Excel-compatible CSV parser.
