### ISSUE TITLE
Compiling typescript is throwing exceptions

### ISSUE THREAD

**Issue by OzgurDogan** [SheetJS/js-xlsx#442]
jspm_packages\github\SheetJS\js-xlsx@0.8.0\misc\xl.d.ts(31,3): error TS2411: Property ''!range'' of type 'CellRange' is not assignable to string index type 'Cell'.

jspm_packages\github\SheetJS\js-xlsx@0.8.0\misc\xl.d.ts(31,3): error TS2411: Property ''!ref'' of type 'string' is not assignable to string index type 'Cell'.

**Comment by johnjuuljensen** [comment]
In TS 2.0 the fix seems to be:
[key: string]: Cell | string | CellRange;

**Comment by SheetJSDev** [comment]
We will be removing the old typescript definitions files.  Type metadata is included as flow comments.
