### ISSUE TITLE
Trim values

### ISSUE THREAD

**Issue by miguelschwindt** [SheetJS/js-xlsx#443]
How to trim values on a cell when reading? I'm experiencing a problem with white spaces

**Comment by lakhorerakesh** [comment]
Same issue here

**Comment by reviewher** [comment]
@miguelschwindt @lakhorerakesh can you share a file that has extra whitespace?  Confirm that the original file doesn't have extra whitespace first.

**Comment by lakhorerakesh** [comment]
@reviewher  suppose first column "Name" and value is  "   Test    " 

How to trim value on a cell when reading? 

 Thanks!

**Comment by reviewher** [comment]
I don't think the library should do this automagically, since the whitespace may be intentional.  The easiest thing to do is to loop through the cells.  Something like this (warning: untested)

```js
// assume ws is the worksheet you want to clean up
var range = XLSX.utils.decode_range(ws['!ref']);
for(var R = range.s.r; R <= range.e.r; ++R){
  for(var C = range.s.c; C <= range.e.c; ++C) {
    var coord = XLSX.utils.encode_cell({r:R, c:C}), cell = ws[coord];
    if(!cell || !cell.v) continue;
    // clean up raw value of string cells
    if(cell.t == 's') cell.v = cell.v.trim();
    // clean up formatted text
    if(cell.w) cell.w = cell.w.trim();
  }
}
```

If this works, please add to the project wiki

**Comment by reviewher** [comment]
@lakhorerakesh @miguelschwindt please try the code and let us know if it works.  If you are still having problems feel free to reopen or comment here

**Comment by ATMarcks** [comment]
@reviewher thanks, it works

**Comment by Rach81** [comment]
I also tried this code. It removed an entire column of data and when I took out the code and reran my lambda function to convert an xlsl into json, the column still isn't there. Does anyone know why this might be happening?
