### ISSUE TITLE
How to retrieve the Worksheet and modify it ?

### ISSUE THREAD

**Issue by Makizar** [SheetJS/js-xlsx#448]
Hello everyone,

I am very new to programming and I try to use the XLSX script. It's working great and I can display my files as in the demo.

Nevertheless I would like to manipulate the Worksheet to apply some modifications to it. How can I do ? What is the final object containing the Worksheet ? I look very carefully at the read-me but couldn't find where I can modify the Worksheet and display it to another webpage.

I am trying to retrieve it inside this part of the code but couldn't do anything : 

```js
function handleFile(e) {
    rABS = document.getElementsByName("userabs")[0].checked;
    use_worker = document.getElementsByName("useworker")[0].checked;
    var files = e.target.files;
    var f = files[0];
    {
        var reader = new FileReader();
        var name = f.name;
        reader.onload = function(e) {
            if(typeof console !== 'undefined') console.log("onload", new Date(), rABS, use_worker);
            var data = e.target.result;
            if(use_worker) {
                xw(data, process_wb);
            } else {
                var wb;
                if(rABS) {
                    wb = X.read(data, {type: 'binary'});
                } else {
                var arr = fixdata(data);
                    wb = X.read(btoa(arr), {type: 'base64'});
                }
                process_wb(wb);
            }
        };
        if(rABS) reader.readAsBinaryString(f);
        else reader.readAsArrayBuffer(f);
    }
}
```

Thanks a lot in advance,

Makizar

NOTE: edited by @reviewher to put the code in fenced code block

**Comment by reviewher** [comment]
In your process_wb function you make the changes.  If you can describe what you want to change, we can give some guidance.  The format is described in the README
