### ISSUE TITLE
Will not import value if numeric format = "Rs."#,###.00

### ISSUE THREAD

**Issue by dougschiller** [SheetJS/js-xlsx#449]
For some reason, if number formatted "Rs."#,###.00, the numeric value will not be properly be converted.   See attached.   -Rs.51,968,287.00  imports as "Rs.00"    .. it should be 51,968,287.00

[testrs.xlsx](https://github.com/SheetJS/js-xlsx/files/392443/testrs.xlsx)

**Comment by SheetJSDev** [comment]
@dougschiller The parser was tripped up by the presence of the `.` in the text.  That was resolved in SSF 0.9.1 and will be pushed here as XLSX version 0.9.13.
