### ISSUE TITLE
Wrong parse date in Firefox and EDGE 

### ISSUE THREAD

**Issue by ignacio-chiazzo** [SheetJS/js-xlsx#456]
When I parse a date the year is wrong, it's 100 years less than the real date.

For example if my cell is _8/31/2016  12:00:00 AM_ the year will be 1906 instead of 2016.

The Problem is related to the date retrieved, If the cell is _8/31/2016  12:00:00 AM_ the date retrieved will be the string "8/31/16 12:00 AM", note the year is 16 instead of 2016

NOTE: The issue only happens with edge and firefox, it's working fine in Chrome and Safari

**Comment by shikelong** [comment]
In chrome 52. The date cell  '8/14/2016' will be parsed to `8/14/16`

**Comment by reviewher** [comment]
@ignacio-chiazzo @shikelong can you share an offending file?  Also, can you check if the issue occurs in IE10/11?

**Comment by SheetJSDev** [comment]
We were able to reproduce.  Here's the story: if you are dealing with a file that stores a date in string form like `"2/19/17"`, IE defaults to `1917` while Chrome defaults to `2017`.  To determine whether the correction is needed, we now proactively try to convert a date and see if we get `2017` or `1917` and apply the 100-year adjustment accordingly.

If possible, can you check against the latest version?

**Comment by ignacio-chiazzo** [comment]
@SheetJSDev I am 100% that that's the problem. We have to take into account that.  I cannot check the version now, but it was edge 10.x.

**Comment by SheetJSDev** [comment]
If that's the issue, I believe we applied the appropriate fix.  Closing, please reopen if this shows up in the future.

**Comment by ignacio-chiazzo** [comment]
ok, I cannot check it now. Thanks for the response!
