### ISSUE TITLE
How to skip first row of the excel

### ISSUE THREAD

**Issue by satishmadugundu** [SheetJS/js-xlsx#463]
How to skip the first row of the excel while parsing (in my excel first row contains some static text, header starts from second row), I have tried with option "sheetRows: 1" which is not working. is there any other alternate.

**Comment by killtheliterate** [comment]
`sheetRows` seems to be the number of rows you would like to parse, not an offset.

**Comment by satishmadugundu** [comment]
In that case, how to skip first row of the excel sheet.

**Comment by SheetJSDev** [comment]
All of the utilities respect the `!ref` key as the range of the worksheet.  You can directly manipulate it to control the sheet range.

For example, to skip the first row of a worksheet:

```js
var range = XLSX.utils.decode_range(worksheet['!ref']);
range.s.r = 1; // <-- zero-indexed, so setting to 1 will skip row 0
worksheet['!ref'] = XLSX.utils.encode_range(range);
```

This range is respected by the various utility functions and exporters, as they all decode and work with the reported range.

Here's a live example: https://runkit.com/sheetjs/58f0158b09f0c50012171569
