### ISSUE TITLE
Using xlsx with Webpack on the browser.

### ISSUE THREAD

**Issue by vijayst** [SheetJS/js-xlsx#467]
I am using xlsx with Webpack on the browser.

`import XSLX from "xslx";`

Importing XSLX is throwing an error in Webpack compilation that fs module could not be found. 
![screen shot 2016-09-08 at 2 21 11 pm](https://cloud.githubusercontent.com/assets/3457565/18343113/9f56f938-75cf-11e6-99d0-007beee5a0a5.png)

**Comment by jmcenteno** [comment]
Having the same issue here. Any ideas on how to solve it?

**Comment by vijayst** [comment]
I found this answer on another thread. Add the below configuration to the webpack.config file.
```
// required for xlsx to work with webpack
  node: {
    fs: 'empty'
  },

  externals: [
    {
      './cptable': 'var cptable'
    },
    {
      './jszip': 'jszip'
    }
  ],
```

**Comment by jmcenteno** [comment]
@vijayst Thank you for sharing your solution. Works like a charm.

**Comment by dineshjain1992** [comment]
also getting errors when integrating xlsx.core.min.js in webpack
ERROR in ./public/asset/libs/js/xlsx.core.min.js
Module not found: Error: Can't resolve './dist/cpexcel' in '/home/dinesh/Paxcom/kinator/public/asset/libs/js'
 @ ./public/asset/libs/js/xlsx.core.min.js 5:15462-15487
 @ ./webpackJQ.js

ERROR in ./public/asset/libs/js/xlsx.core.min.js
Module not found: Error: Can't resolve './dist/ods' in '/home/dinesh/Paxcom/kinator/public/asset/libs/js'
 @ ./public/asset/libs/js/xlsx.core.min.js 9:159-183
 @ ./webpackJQ.js

**Comment by reviewher** [comment]
@dineshjain1992 you are using a very old version.  The relevant issue has been resolved in later versions

**Comment by dineshjain1992** [comment]
I am using webpack": "^3.8.1" version

**Comment by dineshjain1992** [comment]
Here is my webpack.config file 
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
var IgnorePlugin = require('watch-ignore-webpack-plugin')
var jquery = require('jquery');
var underscore = require('underscore');
var moment = require('moment');
const rules = [
    {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
            fallback: "style-loader",
            use: ["css-loader"]
        })
    }
    ,{
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,    //to support @font-face rule 
        loader: "url-loader",
        query:{
          limit:'10000',
          name:'font.css',
          outputPath:'fonts/'
          //the fonts will be emmited to public/assets/fonts/ folder 
          //the fonts will be put in the DOM <style> tag as eg. @font-face{ src:url(assets/fonts/font.ttf); }  
        }
      },
];
const plugins = []

module.exports = {
    context: __dirname + '',
    entry: {
        app: './webpackApp.js'
        , vendor: './webpackJQ.js'
        // , bundlejs: './webpackJQ.js'
    },
    output: {
        path: __dirname + '/public/webpack-min',
        filename: 'bundle.js'
    }
    , plugins: 
    [
        new webpack.ProvidePlugin({
            '$': "jquery",
            'jQuery': "jquery",
            'jquery': "jquery",
            'window.$': "jquery",
            'window.jQuery': "jquery",
            "window.moment": "moment",
            "moment": "moment",
            '_':'underscore',
            "underscore": "underscore", 
        })

        ,new webpack.optimize.CommonsChunkPlugin({ name: 'vendor', filename: 'vendor.js',Infinity })
        ,new ExtractTextPlugin({ filename: "style.css" }),
    ]
    
    ,externals: [
		{
            'sampleApp': '',
			'./cptable': 'var cptable',
			'./jszip': 'jszip'
		}
	]
    ,module: {
        rules
    }
    ,node: {
        fs: 'empty'
      },
};




from my webpackJQ.js file I am using
require('./public/asset/libs/js/xlsx.core.min.js'); 

Did I miss something ?
