### ISSUE TITLE
decryption

### ISSUE THREAD

**Issue by surjikal** [SheetJS/js-xlsx#47]
I don't see support for decrypting password-protected spreadsheets. Is this feature beyond the scope of this library?

Is there a way to programmatically decrypt spreadsheets? Doesn't need to be JS.

**Comment by sgilroy** [comment]
@surjikal Any progress on this? Being able to read a password protected xlsx file would be very useful for me. Did the commit above by @clarketm that links to this issue actually impact password/decryption support?

**Comment by surjikal** [comment]
@sgilroy Sorry, I have not looked at the patch above. I posted this issue almost 3 years ago! Thanks for bringing it to my attention though, might be useful someday.

**Comment by sgilroy** [comment]
@SheetJSDev Is the patch you referred to back in 2014 https://github.com/SheetJS/js-xlsx/issues/47#issuecomment-35060977 available on a branch or fork somewhere? I'm using js-xlsx in nodejs, so a Firefox memory error would not affect me.

**Comment by reviewher** [comment]
Closing in favor of #774
