### ISSUE TITLE
Is it possible to define automatic column filters?

### ISSUE THREAD

**Issue by yonatannn** [SheetJS/js-xlsx#478]
Hi,

Thanks for the great work.

Question: is it possible to define per-sheet an automatic filter for all/some columns? in other words, when the user will open the sheet, automatically Excel will display filters on the column headers

thanks,
Yoni Goldberg

**Comment by zuk38** [comment]
+1

**Comment by zuk38** [comment]
I found solution here: https://github.com/SheetJS/js-xlsx/issues/472

**Comment by yonatannn** [comment]
@zuk38 thanks a bunch!

Should I edit the source code to allow "writextag" or is part of the API and I can just add the autofilter tag?

**Comment by SheetJSDev** [comment]
We're pushing a change to add autofilter metadata in the worksheet `!autofilter` key.  For now it just supports a reference, but later we will add more.

usage:

```js
worksheet['!autofilter'] = { ref: "A1:C20" };
```
