### ISSUE TITLE
Excel fields not refreshed post an update using js-xlsx

### ISSUE THREAD

**Issue by rs2275** [SheetJS/js-xlsx#481]
I have this requirement to reuse an excel [xlxb format] for calculations, in a Webapp. This four sheet excel is self-contained with all the rates, and logic needed for the calculation. I input fields on sheet1 which refreshes a table in the same sheet with the calculated values - which is the required output, which I am to read and use in the parent code.

The issue I am facing is that the output fields do not get refreshed, upon setting the input fields.

I tried processing the excel with js-xlsx-0.8.0. The code snippet is as shown below

 var base64Value = "...."; -> the excel file in base64
 var wb = XLSX.read(base64Value, {type: 'base64',WTF:false});
 var first_sheet_name = wb.SheetNames[0];

 var worksheet = wb.Sheets[first_sheet_name];

  var cell = { v: 5000000 };
  var cell_ref = XLSX.utils.encode_cell({c:2,r:3});
  worksheet[cell_ref] = cell;

  var cell = { v: 25 };
  var cell_ref = XLSX.utils.encode_cell({c:2,r:4});
  worksheet[cell_ref] = cell;

  var cell = { v: 'M' };
  var cell_ref = XLSX.utils.encode_cell({c:2,r:6});
  worksheet[cell_ref] = cell;

....a few more fields entered in a similar fashion

console.log('D22 value - ' + worksheet['D23'].v ); -> This should return the newly calculated value [ouput] but returns an existing value.
I am new to sheetjs, so I may be missing something. Can someone kindly help me with the following 
1) Am I setting the fields right, with regard to the code snippet above. 
2) Is there any setting I am missing. 
3) The input excel contains a drop down list. eg. var cell = { v: 'M' }; -> is a drop down list for gender. I use the same technique to set this field. Is that correct??

**Comment by reviewher** [comment]
This library does not automatically recalculate formulae.  You need something like https://github.com/fabiooshiro/xlsx-calc.
