### ISSUE TITLE
isregex fails

### ISSUE THREAD

**Issue by ljani** [SheetJS/js-xlsx#484]
I have an xlsx file with following simplified data (`sheet3.xml`):

```
<?xml version="1.0" encoding="utf-8"?>
<x:worksheet xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" xmlns:x="http://schemas.openxmlformats.org/spreadsheetml/2006/main" mc:Ignorable="x14ac">
  <x:sheetData>
    <x:row r="1">
      <x:c r="A1" s="0" t="inlineStr">
        <x:is>
          <x:t>Test</x:t>
        </x:is>
      </x:c>
   </x:row>
  </x:sheetData>
</x:worksheet>
```

[`isregex`](https://github.com/SheetJS/js-xlsx/blob/53f7f6d9446ccd680c9b13992d6dcdccde49a8f6/bits/67_wsxml.js#L168) does not seem to match this, because of the `x` namespace. If I correct the regex, parsing fails with `Cannot read property 'replace' of undefined`.

Unfortunately I cannot share the original file, but this is the part I've identified to be problematic.

Thanks for the wonderful library!

**Comment by reviewher** [comment]
@ljani the namespace should have been fixed, please update and test against the latest version.  If the error persists raise a new issue

**Comment by ljani** [comment]
Seems to be fine now, thanks.
