### ISSUE TITLE
Missing documentation for WTF mode

### ISSUE THREAD

**Issue by livesoftware** [SheetJS/js-xlsx#487]

**Comment by SheetJSDev** [comment]
`WTF:true` exposes all of the sheet-level errors (by default they are caught and suppressed).  It also adds a whole host of new errors pertaining to file features that are not recognized by the parser.

It is mainly useful for development, as the errors usually represent "we don't know what that thing is" and the default behavior is "just ignore the odd things".

A note will be added to the README.
