### ISSUE TITLE
Unsupported File: XLSX (First bytes: 50 4b)

### ISSUE THREAD

**Issue by gavinrobertszeco** [SheetJS/js-xlsx#488]
Hi there,

I'm using JS-XSLX within Node to convert XLS/XLSX files to CSV files and I've come across a problem which fails in both my code and the online demo.

[Test.xlsx](https://github.com/SheetJS/js-xlsx/files/550268/Test.xlsx)

When uploading the above file, with all check boxes ticked, I get:

![image](https://cloud.githubusercontent.com/assets/20720865/19681671/46421542-9aa2-11e6-8df8-8264442fbfb1.png)

However if I use the same file without any check boxes ticked, I replicate my error:

![image](https://cloud.githubusercontent.com/assets/20720865/19681715/7a7f03d8-9aa2-11e6-9b45-ec1317635107.png)

When debugging, it appears that my XLSX has a header starting with 504b, which fails to match any of the signatures configured within `xlsread` and `readfile`.

Any suggestions on what the cause could be?

**Comment by reviewher** [comment]
It looks like you are using js-xls.  The 504b signature corresponds to XLSX and XLSB files.  You should switch to using js-xlsx, which now includes the XLS logic as well as XLSX.
