### ISSUE TITLE
I want export excel by chinese name, but i got the error 'The header content contains invalid characters',what should i do?

### ISSUE THREAD

**Issue by FlyingSailor** [SheetJS/js-xlsx#492]
I want export excel by chinese name, but i got the error 'The header content contains invalid characters',what should i do?

thanks for first!

**Comment by pythonsoft** [comment]
I meet this problem too,You can use another package export-excel,simple-easy use.

**Comment by reviewher** [comment]
Can you share some sample code and test against the latest version?  We were able to generate some files with Chinese characters: https://gist.github.com/SheetJSDev/03b0717087c9e2c088b593019367fcd9

**Comment by simonchan2013** [comment]
@reviewher yep, it works well when export xlsx file, but when I export xls file, the Chinese will be wrong

**Comment by SheetJSDev** [comment]
The new default XLS export is BIFF8 (97-2004) which does support Chinese characters!
