### ISSUE TITLE
DeprecationWarning in node.js v7.0.0

### ISSUE THREAD

**Issue by c941010623** [SheetJS/js-xlsx#493]
when i use nodejs v7.0.0 and use this package and i use session store
i get the error:

DeprecationWarning: Using Buffer without new will soon stop working. Use new Buffer(), or preferably Buffer.from(), Buffer.allocUnsafe() or Buffer.alloc() instead.

how fix ??

**Comment by c941010623** [comment]
when i use nodejs v7.0.0 and use this package and i use session store
i get the error:

DeprecationWarning: Using Buffer without new will soon stop working. Use new Buffer(), or preferably Buffer.from(), Buffer.allocUnsafe() or Buffer.alloc() instead.

how fix ??

**Comment by spelunk** [comment]
Unfortunately node isn't going back, so I think this needs to be fixed.  browserify is seeing the same problem

**Comment by semiphore** [comment]
This isn't an error, but it's really annoying to see the message show up on stderr :/

**Comment by SheetJSDev** [comment]
AFAICT it was fixed in node 7.3.0.  See https://github.com/nodejs/node/pull/9529
