### ISSUE TITLE
FOR SOME REASON IT DOESNT PICKUP THE VALUES UNDER THE CALL_PRIORITY  COLUMN. CAN YOU PLEASE CHECK ?

### ISSUE THREAD

**Issue by jpca999** [SheetJS/js-xlsx#494]

**Comment by jpca999** [comment]
https://www.dropbox.com/s/zdf9w2ji438arq1/WORKING.xls?dl=0

**Comment by reviewher** [comment]
This file actually has 2 columns named `call_priority`.  

<img width="232" alt="screen shot 2017-03-12 at 22 39 42" src="https://cloud.githubusercontent.com/assets/24845478/23839487/d28fe666-0774-11e7-8351-b79f6d433779.png">

We recently changed the JSON output to disambiguate the names, so it should work in the latest version. The first `call_priority` column retains the name while the second one is stored in `call_priority_1`

**Comment by jpca999** [comment]
ok got it, but how do i convert an excel file into json, sorry i dont understnd the documentation....

**Comment by SheetJSDev** [comment]
Are you running in nodejs or in the web browser?  How do you plan on supplying the file?

Here's a node example:

```js
var XLSX = require('xlsx');
var wb = XLSX.readFile('WORKING.xls');
var sheetname = 'Worksheet'; // if the sheet name is different ,use wb.SheetNames[0] to get the first sheet
var json = XLSX.utils.sheet_to_json(wb.Sheets[sheetname]);
```

**Comment by jpca999** [comment]
nope via node.  not on browser. 
Let me try this.

**Comment by SheetJSDev** [comment]
@jpca999 if you are looking for output, you need something like `console.log(json)` after that line

**Comment by jpca999** [comment]
Holy shit, it works, ive beeen trying to get this work for last 6mos, soemthing this error, sometime that error . Thanks  @SheetJSDev

**Comment by jpca999** [comment]
@SheetJSDev 

quick question now im trying to write the ouput on file, im gettin this weird error again 


var fs=require('fs');

var XLSX = require('xlsx');
var wb = XLSX.readFile('working.xls');
var sheetname = 'Worksheet'; // if the sheet name is different ,use wb.SheetNames[0] to get the first sheet
var jso = XLSX.utils.sheet_to_json(wb.Sheets[sheetname]);
console.log( ' json = ', jso);
fs.write('data.json',jso,'w');


![image](https://cloud.githubusercontent.com/assets/1026325/24083656/91f7db1c-0cb1-11e7-84d9-dade0d2078cb.png)

**Comment by SheetJSDev** [comment]
@jpca999 you probably meant to use [`writeFileSync`](https://nodejs.org/api/fs.html#fs_fs_writefilesync_file_data_options).  Try

```js
var jso = XLSX.utils.sheet_to_json(wb.Sheets[sheetname]);
var jsonstr = JSON.stringify(jso); // generate JSON string
fs.writeFileSync('data.json',jsonstr,{flag:'w'}); // write file
```

That should generate a data.json file

**Comment by jpca999** [comment]
lol - your right but the output that i get isn't real juicy data, but 
[object Object],[object Object]

![image](https://cloud.githubusercontent.com/assets/1026325/24083702/9b82a314-0cb2-11e7-8058-537340c745b3.png)


var fs=require('fs');
var XLSX = require('xlsx');
var wb = XLSX.readFile('working.xls');
var sheetname = 'Worksheet'; // if the sheet name is different ,use wb.SheetNames[0] to get the first sheet
var jsonOut = XLSX.utils.sheet_to_json(wb.Sheets[sheetname]);
console.log( ' jsonOut= ', jsonOut);
// fs.write('data.json',jso,'w');
fs.writeFileSync('data.json',jsonOut,{flag:'w'});

**Comment by SheetJSDev** [comment]
@jpca999 you need to convert `jsonOut` to a string first.  Try this:

```js
var fs = require('fs');
var XLSX = require('xlsx');
var wb = XLSX.readFile('WORKING.xls'); // read file
var sheetname = 'Worksheet'; // if the sheet name is different ,use wb.SheetNames[0] to get the first sheet
var jso = XLSX.utils.sheet_to_json(wb.Sheets[sheetname]); // get row objects
console.log( ' jsonOut= ', jso);
var jsonstr = JSON.stringify(jso); // generate JSON string
fs.writeFileSync('data.json',jsonstr,{flag:'w'}); // write file
```

**Comment by jpca999** [comment]
@sheetjsdev   perfect!  thanks a bunch!
