### ISSUE TITLE
Don't encourage binary string use

### ISSUE THREAD

**Issue by jimmywarting** [SheetJS/js-xlsx#496]
as stated: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsBinaryString
> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future. 
> 
> This method has been removed from the FileAPI standard. FileReader.readAsArrayBuffer() should be used instead.

It's not even supported in IE10

Javascript is bad at handling binary strings. One character is a 16-bit so it means a binary string can take up to 2x more memory since it's not in utf-8

What you should do in the readme is changing the examples to use arrayBuffer/typed arrays or just accept plain blob objects

**Comment by miclill** [comment]
This [readAsBinaryString] method has been removed from the FileAPI standard. FileReader.readAsArrayBuffer() should be used instead.
Source: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsBinaryString

**Comment by reviewher** [comment]
@jimmywarting @miclill there was probably a reason for preferring readAsBinaryString, most likely performance.  The demo supports both modes.

> One character is a 16-bit so it means a binary string can take up to 2x more memory since it's not in utf-8

The binary string is a direct mapping of bytes (if `s` is the string, `s.charCodeAt(i)` is the `i`-th byte), so UTF8 conversion is not involved.  The string length will be the exact byte size of the uploaded file.

> What you should do in the readme is changing the examples to use arrayBuffer/typed arrays or just accept plain blob objects

I agree that it would be helpful to add more examples like the readAsArrayBuffer form.

**Comment by SheetJSDev** [comment]
I have [a 2010 tutorial that used readAsBinaryString](https://www.html5rocks.com/en/tutorials/file/dndfiles/) in my bookmarks.  When we added readAsArrayBuffer support, rABS was noticeably faster.
