### ISSUE TITLE
Please allow the community to help

### ISSUE THREAD

**Issue by tarwich** [SheetJS/js-xlsx#497]
I've made a fork: https://github.com/tarwich/js-xlsx

I'm not trying to take over or run away with this project. My goal is to help carry some of the weight of merging PRs and incorporating simple fixes. If you like, you can add me as a contributor and I'll delete my fork. If you have any issues with my fork, please let me know and I'll get rid of it.

Until then, I'm going to encourage people to contribute to my fork for the purpose of updates. Once again, not trying to steal any light from the amazing work you've done here. Just trying to help.

**Comment by csvan** [comment]
This is a great initiative, thanks!

**Comment by tarwich** [comment]
So... someone told me (https://github.com/SheetJS/js-xlsx/issues/513#issuecomment-267741561) that you guys are indeed active, but you take pull requests very seriously on account that you'd like to ensure quality on a broad spectrum of versions.  

Hat's off 🎩 to you guys for maintaining a quality product. I can say that I've always been impressed that what I write with this just works in Excel and Numbers.

I'll still maintain the fork and perhaps it will offload some pressure from you guys. If you don't like it, just let me know and I'll kill the fork.

**Comment by st-sloth** [comment]
And what about https://github.com/protobi/js-xlsx?
There is a lot of great new styling features in that fork and they too wish to merge back with the main project. But for over than a year this process didn't seem to move (see the last messages in #128, #263) and doesn't seem to be starting any time soon.
SheetJS/js-xlsx is awesome, but, sadly, it looks like this project is going to be very fragmented into many different incompatible forks that solve different and sometimes the same problems and don't get merged back...

**Comment by SheetJSDev** [comment]
@st-sloth we're working on it
