### ISSUE TITLE
cannot read xlsx file exported by java jasper

### ISSUE THREAD

**Issue by chuong2v** [SheetJS/js-xlsx#499]
Hi there, 
I can't read xlsx file which exported by java jasper while I can open it by Microsoft Excel.
Can anyone help me? It took whole day from me. Thanks

**Comment by spelunk** [comment]
@chuong2v can you upload a file and show the error?

**Comment by chuong2v** [comment]
@spelunk There's not any error, but the result of readFile function is an empty array. 
Here the example file: 
[Corporate5726486890413714895.xlsx](https://github.com/SheetJS/js-xlsx/files/588397/Corporate5726486890413714895.xlsx)

**Comment by asksahil** [comment]
I am facing the same issue. Did you find a fix?

**Comment by SheetJSDev** [comment]
This appears to work in 0.9.4 -- can you check against the latest version and confirm?
