### ISSUE TITLE
Umlauts in cell HTML

### ISSUE THREAD

**Issue by fuchsc** [SheetJS/js-xlsx#505]
Hi,

I'm having an issue with HTML formatted text containing umlauts. My xlsx worksheet has cells containing umlauts. The raw value (cell.v) looks good, but I'd like to preserve the cell formatting and therefore I use cell.h to get the HTML formatted text. Regarding formatting the value looks good but the umlauts (ö, ü, ä) are not converted correctly.

Is there anything I can do to get correct encoded HTML?

thx in advance!

**Comment by qqilihq** [comment]
FYI: I'm having the same issue. I just sent a detailed description with a test case and data to sheetjs@gmail.com.

**Comment by SheetJSDev** [comment]
Thanks @fuchsc @qqilihq I looked at the file, the fix for the HTML is to do a utf8 conversion first:

https://github.com/SheetJS/js-xlsx/blob/master/bits/42_sstxml.js#L152-L154 should be

```js
		z.r = utf8read(x);
		z.t = utf8read(unescapexml((x.match(sitregex)||[]).join("").replace(tagregex,"")));
		if(html) z.h = parse_rs(z.r);
```
