### ISSUE TITLE
.xlsx file that opens w/ other applications is silently imported without content

### ISSUE THREAD

**Issue by rahulsindc** [SheetJS/js-xlsx#510]
Hi there,

What reasons would there be for an excel file that (say) Apple Numbers can import without issue, failing silently with js-xlsx? By failing I mean no sheets are recorded, and the non-existent sheets are then not populated with data (obviously). No errors are sent to console.
[test.xlsx](https://github.com/SheetJS/js-xlsx/files/622118/test.xlsx)

Thanks!

**Comment by SheetJSDev** [comment]
In general it tries not to blow up if certain things look weird.  Passing the option `WTF:1` to read or readFile will suppress that behavior.  In the node command that's the `--dev` option.

In this file, there were a few XML inconsistencies.  For certain tags like `numFmt`, the spec asserts that the content must be empty.  Excel and Numbers usually write these cells with an empty body but this file has a zero-length string body.

For example, here's the first number format (rename the XLSX file with a .zip extension, extract, and look at `xl/styles.xml`):

```xml
<numFmt numFmtId="82" formatCode="[$-010409]m/d/yyyy"></numFmt>
```

The expected form is

```xml
<numFmt numFmtId="82" formatCode="[$-010409]m/d/yyyy"/>
```

We will roll out a fix soon.
