### ISSUE TITLE
formula write fix - please pull

### ISSUE THREAD

**Issue by eddyparkinson** [SheetJS/js-xlsx#512]
https://github.com/mcsf/js-xlsx/commit/d439645

I tested the above and agree it fixes the formula write problem, please pull.

several people (at least 6) would like to see these few lines of code added.

**Comment by csvan** [comment]
Is this even being maintained anymore?

**Comment by eddyparkinson** [comment]
@csvan
Looks to be active every few months https://github.com/SheetJSDev
Failing that,  if I create an Organization account https://github.com/blog/674-introducing-organizations  Do you want to be an admin/have & pull rights.

**Comment by tarwich** [comment]
@eddyparkinson I have [reached out] to try to help. I've created a fork and I am taking PRs. If you made an organization that would meet the same goal. If you go down that path, please let me know so I can kill my repo.

My fork: https://github.com/tarwich/js-xlsx

[reached out]: https://github.com/SheetJS/js-xlsx/issues/497

**Comment by eddyparkinson** [comment]
@tarwich suggest you read
https://github.com/protobi/js-xlsx/issues/21

Organization account - Please create one and add me if you have time, or I will do it when I set up an npm.

**Comment by tarwich** [comment]
@eddyparkinson `node-xlsx` is available as an organization name. If you like it, give me a 👍 and I'll invite you. We can change the organization name at any time, but links made to the old name obviously won't update.

**Comment by eddyparkinson** [comment]
I plan to change  sheetjs/j, sheetjs/xlsx and sheetjs/harb
