### ISSUE TITLE
Check if excel file has any macro

### ISSUE THREAD

**Issue by kamranwali** [SheetJS/js-xlsx#514]
Hi,

This is not an issue, I just want to know is there a way to find out if the excel file has any macro using this library.

**Comment by wildeyes** [comment]
xlsm files are the only ones allowed to have macros, maybe check the file extension?

**Comment by reviewher** [comment]
@wildeyes xls and xlsb are also permitted to have records.

For VBA macros, passing the option `bookVBA:true` to the read functions will set the `vbaraw` property of the workbook to the VBA storage if it is available.

Pre-95 Macrosheets are currently not persisted.

**Comment by SheetJSDev** [comment]
Reading the file with the option `bookVBA:true` will create a key `vbaraw` if VBA is in the workbook.  To find macrosheets, check the worksheet `!type` key.  The full test is:

```js
const wb_has_macro = (wb) => !!wb.vbaraw || wb.SheetNames.map(n => wb.Sheets[n]).some(ws => ws && ws['!type'] == 'macro');
```
