### ISSUE TITLE
generate SQL statements from an excel sheet

### ISSUE THREAD

**Issue by sumtingwon** [SheetJS/js-xlsx#517]
have excel table, need sql insert statements just like the data

**Comment by eddyparkinson** [comment]
**Insert row/col** 
ethercalc has formulas for *inserting/updating/gui*

Look at the insert example 
 http://sheet.cellmaster.com.au/examples
 http://sheet.cellmaster.com.au/examples_insert

**Comment by tommytian770401** [comment]
Maybe, you can try the alasql, this module also use js-xlsx as excel parser.
[https://github.com/agershun/alasql](https://github.com/agershun/alasql)

**Comment by sumtingwon** [comment]
@tommytian770401 I found alasql a few days ago and it solved my problem!
