### ISSUE TITLE
Helper functions for parsing tables with named columns.

### ISSUE THREAD

**Issue by optilude** [SheetJS/js-xlsx#521]
Please close if you don't want this in your issue tracker, but I thought maybe people might search here and find this helpful:

https://gist.github.com/optilude/2aa1d1ccb8c3398eb0afce32226ac8eb

This is a set of functions that make it easy to parse sheets containing tables with named columns.

Ideally I'd like to use Excel named tables for this, but I don't think JS-XLSX supports those yet.

**Comment by reviewher** [comment]
Hello @optilude

Thanks for the snippets!  Does it make sense to also include them in the wiki?  I'm not too familiar with the wiki feature but can you edit it directly or do we have to approve changes?

**Comment by optilude** [comment]
Done: https://github.com/SheetJS/js-xlsx/wiki/Helper-functions-to-parse-tables-in-sheets
