### ISSUE TITLE
Skookum JS errors

### ISSUE THREAD

**Issue by animetronix** [SheetJS/js-xlsx#523]
xlsx works well in nodejs but fails when embedding using sjs. The error message is pretty useless, can someone take a look at why it is failing?

**Comment by reviewher** [comment]
Hello @animetronix, I have not used `sjs`, do you have a sample procedure to reproduce the problem?

**Comment by reviewher** [comment]
We have made changes to the `require` usage and other patterns, please test and let us know if you have any issues
