### ISSUE TITLE
How to work with SHeetJs for reading xls/xlsx in IE?

### ISSUE THREAD

**Issue by Kishoreocr** [SheetJS/js-xlsx#528]

**Comment by Kishoreocr** [comment]
My requirement is to read the xls/xlsx file in client side, show the details in some textarea.Plugin is working in chrome but not working in IE.To work in IE, we need to convert file to base64 and pass to the plugin.But am unable to crack it..Could you please provide me the code snippet to work th excel reading in IE

**Comment by reviewher** [comment]
Older versions of IE do not support HTML5 features like the FileReader interface and drag-and-drop.  You have to pass in data another way.  Using a base64 string is one option, and the demo page http://oss.sheetjs.com/js-xlsx/ has a box for that purpose.  Another option if you just want to do the processing on the client side is to use AJAX, see http://oss.sheetjs.com/js-xlsx/ajax.html for an example.
