### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by aseem2625** [SheetJS/js-xlsx#529]
**Environment:**
Isomorphic, React, webpack
I've already set  ```patch_require: true```

I'm not able to move ahead of this following error. Sometimes, ``cpexcel`` and other times ``cptable`` doesn't seem to exist. I tried browser way of including with script tag but that also failed.

**2 ISSUES:**
1st..
```
0] ./~/xlsx/dist/xlsx.core.min.js
[0] Module not found: Error: Cannot resolve 'file' or 'directory' ./dist/cpexcel in /Users/myUser/Documents/projectName/node_modules/xlsx/dist
```
It is trying to find out dist inside dist.

![image](https://cloud.githubusercontent.com/assets/6055628/21922487/d8807404-d994-11e6-938a-f7eb0b6d5241.png)

2nd..
```
[0]  @ ./~/xlsx/dist/xlsx.core.min.js 5:15471-15496
[0] ./~/xlsx/dist/xlsx.core.min.js
[0] Module not found: Error: Cannot resolve 'file' or 'directory' ./empty_shim.js in /Users/myUser/Documents/projectName/node_modules/xlsx/dist
[0] resolve file
```

Hey @SheetJSDev  can you please check this above issue?

**Library seems to be wonderful but it's said that it's hard to get past the setting it up using node!** And I wonder if these issues started happening with  people recently bcoz this repo has whopping 4329 stars!

**Comment by SheetJSDev** [comment]
Hello @aseem2625 !

There were 2 deployment scenarios initially envisioned: direct script tag references as in [the demo](http://oss.sheetjs.com/js-xlsx) and nodejs.  webpack was not really popular at the beginning.  

cpexcel provides codepage support, basically a big table of mappings between numbers and characters (Excel predates the Unicode standard, so this is not obstinance).  cpexcel.js is a pretty big library and is used for compatibility with files generated by older versions of Excel.  If you are using Excel 2016 to generate files, it is strictly unnecessary.

The goal is for the library to be an optional dependency.  In the aforementioned deployment scenarios this was not an issue:

- in node, the extra file size wasn't a show stopper, so we always require it
- in the browser, global variables and feature tests enable "optional" dependencies -- just add a script tag reference before the xlsx.js script tag reference.

If there's a simple way to do it without breaking ES5 compatibility, we can make a push.

**Comment by SheetJSDev** [comment]
@aseem2625 we bit the bullet and un-broke all of the require statements in 0.8.7 and included samples with browserify/requirejs/webpack. Please check against the latest version

**Comment by SheetJSDev** [comment]
If you are using webpack, using `require('xlsx')` should do the right thing now.  Please test and raise a new issue if there are any issues with the newest version
