### ISSUE TITLE
Is there a way to read in original numbers?

### ISSUE THREAD

**Issue by seong007** [SheetJS/js-xlsx#531]
The numbers in the Excel file are too large. So it is showed like a 3.31928E+11
Is there a way to read in original numbers?

**Comment by reviewher** [comment]
@seong007 You should be able to inspect the value field of each cell to see the original stored value.  The display text replicates the Excel General format, which tries to limit the output to 11 characters.  The raw number is more than 11 characters in standard form so Excel and this library would default to formatting the number as exponential.

As an example, suppose you set Cell `A1` of Sheet `"Sheet1"` to the value `331928000000`.  Then you can find the raw value as follows:

```
> var XLSX = require('xlsx'); XLSX.readFile('test.xlsx').Sheets.Sheet1.A12
{ t: 'n', v: 331928000000, w: '3.31928E+11' }
```

The `v` field shows the numeric value and `w` stores the formatted text.

If you are using an output function like sheet_to_json there are options to display the raw value.

**Comment by leodutra** [comment]
This should be better described in the README. Almost felt in the same rabbit hole.

**Comment by reviewher** [comment]
@leodutra It's mentioned in https://github.com/SheetJS/js-xlsx#cell-object but should be spelled out more clearly.  The `v` field should mirror what is stored in an XLSX/XLS/XLSB file and the `w` field should give you the text you would see if you open the file in Excel.  

One of the main reasons for storing the raw value separately from the formatted text is date handling: Excel natively stores dates as numeric codes.  For example, I set `A1` to the formula `=TODAY()` and `A2` to the date `2/19/17` and saved as XLSX.  The following lines from the worksheet XML correspond to the cells:

```xml
      <c r="A1" s="1">
        <f ca="1">TODAY()</f>
        <v>42787</v>
      </c>
...
      <c r="A2" s="1">
        <v>42785</v>
      </c>
```

You can see that the actual values stored are numeric.  The xlsx library looks at the cell style and process the format to give you the dates, but it still stores the original values:

```
  A1: { t: 'n', v: 42787, f: 'TODAY()', w: '2/21/17' },
  A2: { t: 'n', v: 42785, w: '2/19/17' } }
```

The [leap year bug](https://en.wikipedia.org/wiki/Leap_year_bug) is the main reason for not automatically trying to convert those cells to date type: Excel, in replicating a Lotus bug, treats 1900 as a leap year even though it wasn't (years that are multiple of 100 but not a multiple of 400 are not leap years), so it's not clear how you would handle dates in that day and arithmetic that straddles the day.

**Comment by leodutra** [comment]
@reviewher thank you for the explanation, good to know about the date.

I were talking specifically about that utils function sheets_to_json or something like that.

I don't know if it is intended for public usage but I found it in your demo page and found it the easier and cleaner way to produce a JSON from my sheets... but I found no clear explanation about this useful method or its "raw" optional.

I know the project is not v1.0, but there's a huge amount of stars, downloads and I think a relevant maturity.

Maybe we should produce more examples or produce a more detailed documentation. I'm willing to help.

**Comment by SheetJSDev** [comment]
@leodutra we expanded that part: https://github.com/SheetJS/js-xlsx#json please take a quick look and let us know how to improve it

**Comment by SheetJSDev** [comment]
We changed how dates are handled in `0.9.5`:  Passing `cellDates:true` to the `readFile` function will generate raw dates when the format is a date, and passing `raw:true` will ensure that you get a real date object.

**Comment by leodutra** [comment]
Well done and thanks. This is very straightforward.

**Comment by shanthakumarf22** [comment]
I get the same for mobile numbers `"9.18149E+11"`  using `XLSX.utils.sheet_to_csv`

**Comment by rodsouto** [comment]
@shanthakumarf22 I'm not sure if this is the best solution, but this worked for me

```javascript
Object.keys(ws).forEach(function(s) {
    if(ws[s].t === 'n') {
        ws[s].z = '0';
        ws[s].t = 's';
    }
});
```

**Comment by SavyasachiInfotech** [comment]
**By default `sheet_to_csv` take the formatted numbers.**

**- To avoid the formatted value and to take raw inputs (original values) you have to add parameter in `sheet_to_csv` method you have to set `rawNumbers` to `true`**


**Try this code**
```js
var csvFile = XLSX.utils.sheet_to_csv({ rawNumbers: true });
```
