### ISSUE TITLE
buffer interface deprecation

### ISSUE THREAD

**Issue by nahidakbar** [SheetJS/js-xlsx#533]
line 1443 in xlsx.js

	var utf8readc = function utf8readc(data) { return Buffer(data, 'binary').toString('utf8'); };

needs to become 

	var utf8readc = function utf8readc(data) { return (new Buffer(data, 'binary')).toString('utf8'); };

for newer versions of nodejs

**Comment by bbatliner** [comment]
Made a PR for this small change. Thanks for bringing it up!

**Comment by reviewher** [comment]
@bbatliner @nahidakbar can you check if the same warning shows up using node 7.3.0? Supposedly they rolled back this particular deprecation warning.

**Comment by bbatliner** [comment]
@reviewher Just tested 7.3.0, did not receive that deprecation notice. Closing the PR now, thanks.

**Comment by reviewher** [comment]
@nahidakbar @bbatliner the nodejs team decision to add that warning was unfortunate but they did roll it back.
