### ISSUE TITLE
[HELP]Uncaught Error: Unsupported file 100

### ISSUE THREAD

**Issue by shen5455** [SheetJS/js-xlsx#535]
<script lang="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.1/xlsx.core.min.js"></script>
<script lang="javascript" src="./../app/utils/shim.js"></script>

<body style="font-family: awesome;min-width: 1280px;">
    <input type="file" id="fileElem" onchange="handleFiles(this.files)">
    <span href="#" id="fileSelect">Select some files</span>
    <div id="app"></div>
    <script>
    var fileSelect = document.getElementById("fileSelect"),
        fileElem = document.getElementById("fileElem");

    fileSelect.addEventListener("click", function(e) {
        if (fileElem) {
            fileElem.click();
        }
        e.preventDefault(); // prevent navigation to "#"
    }, false);
    var handleFiles = function(v) {
        var fileReader = new FileReader();
        fileReader.readAsDataURL(v[0]);
        fileReader.onload = function(ev) {
            var data = ev.target.result,
                workbook = XLSX.read(data, {
                    type: 'binary'
                });
        }
    }
    </script>
</body>
///////////////////////
Uncaught Error: Unsupported file 100
    at Object.readSync [as read] (app.js:52268)
    at FileReader.fileReader.onload ((index):45)
//////////////////////
function readSync(data, opts) {
		var zip, d = data, isfile = false, n;
		var o = opts||{};
		if(!o.type) o.type = (has_buf && Buffer.isBuffer(data)) ? "buffer" : "base64";
		if(o.type == "file") { isfile = true; o.type = "buffer"; d = _fs.readFileSync(data); }
		switch((n = firstbyte(d, o))) {
			case 0xD0:
				if(isfile) o.type = "file";
				return parse_xlscfb(CFB.read(data, o), o);
			case 0x09: return parse_xlscfb(s2a(o.type === 'base64' ? Base64.decode(data) : data), o);
			case 0x3C: return parse_xlml(d, o);
			case 0x50:
				if(isfile) o.type = "file";
				return read_zip(data, opts);
			default: throw new Error("Unsupported file " + n);   <---------------error
		}
	}

**Comment by reviewher** [comment]
The `binary` type refers to a binary string like the type you get from `readAsBinaryString`.  `readAsDataURL` returns a [data URL](https://en.wikipedia.org/wiki/Data_URI_scheme) which you would need to parse.  To use `readAsDataURL` I think you can do something like this in the onload callback:

```js
        var data = ev.target.result;
        var _comma = data.indexOf(","), _b64 = data.substr(0, _comma).indexOf("base64") > -1;
        workbook = XLSX.read(data.substr(_comma + 1), {type: _b64 ? 'base64' : 'binary'});
```

**Comment by reviewher** [comment]
@shen5455 the recommendation is to switch to `readAsBinaryString` or `readAsArrayBuffer`.  There are a few code samples and links to demos in the README: https://github.com/SheetJS/js-xlsx#parsing-workbooks
