### ISSUE TITLE
"file" type is hardcoded in readFileSync function in xlsx.js file

### ISSUE THREAD

**Issue by motomohg** [SheetJS/js-xlsx#536]
function readFileSync(data, opts) {
	var o = opts||{}; o.type = 'file';//hardcoded here
	return readSync(data, o);
}
since type is hardcoded, im not able to send buffer here

**Comment by motomohg** [comment]
i made change in this module and published it as xlsx_buffer.

**Comment by reviewher** [comment]
@motomohg instead of calling readFile you should just call read:

```js
var XLSX = require('xlsx');
var xlsx = XLSX.read(fs.readFileSync('test.xlsx'), {type:'buffer'});
```

XLSX.readFile is a light wrapper of XLSX.read

**Comment by motomohg** [comment]
@reviewher  of... actually this module is being used in another module where readFile function is getting called. I will change that module to call read function. Thanks for the help.
