### ISSUE TITLE
Empty sheets after using writeFile

### ISSUE THREAD

**Issue by andrewdsilva** [SheetJS/js-xlsx#537]
Hi,

I'm using the XLSX module to open a XLSX file with empty sheets and fill them.

This is an extract of our code :

```
var myXlsx  = XLSX.readFile( filePath );

myXlsx.Sheets[ 'existingSheet' ][ 'F3' ] = {"v":"TEST","t":"s","r":"<t>TEST</t>","h":"TEST"};

XLSX.writeFile(
    myXlsx,
    filePath
);
```

If i execute the same code with an existing XLSX with non empty sheets it works. But when i try to modify an empty cell it does not work!

Thanks in advance for your time

**Comment by Zibaire** [comment]
Hi, 

I've the same problem today, did you find a solution for this issue ?

**Comment by andrewdsilva** [comment]
Hi,
Our dirty solution is to fill the existing file (the one we open) with random values. In fact i think you can only replace non-empty cell with this library... It's weird.

Somebody find a real solution?

Kiss from France ;)

**Comment by reviewher** [comment]
@andrewdsilva The exporters don't automatically expand the range of the worksheet, so if the original range is A1:B2 and you try to write to cell C3 it will not show up.  To check this, can you try a file with a sheet like

```
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
| 4 |   | 6 |
+---+---+---+
| 7 | 8 | 9 |
+---+---+---+
``` 

and try assigning to cell B2?  This way, you are assigning to a cell within the range of the worksheet

**Comment by andrewdsilva** [comment]
@reviewher yes we have had the same idea !

This works :
```
+---+---+---+
| 1 |   |   |
+---+---+---+
|   |   |   |
+---+---+---+
|   |   | 9 |
+---+---+---+
```

This does not work :
```
+---+---+---+
|   |   |   |
+---+---+---+
|   |   |   |
+---+---+---+
|   |   | 9 |
+---+---+---+
```

But anyway the problem is, with this solution we need to know in advance what is the size of the future sheet.

**Comment by andrewdsilva** [comment]
Nice ! Thank you very much :)

**Comment by SheetJSDev** [comment]
We're thinking of adding something like this to the utilities:

```js
function range_add_cell(range, cell) {
	var rng = XLSX.utils.decode_range(range);
	var c = typeof cell == 'string' ? XLSX.utils.decode_cell(cell) : cell;
	console.log(rng, c);
	if(rng.s.r > c.r) rng.s.r = c.r;
	if(rng.s.c > c.c) rng.s.c = c.c;

	if(rng.e.r < c.r) rng.e.r = c.r;
	if(rng.e.c < c.c) rng.e.c = c.c;
	return XLSX.utils.encode_range(rng);
}

function add_to_sheet(sheet, cell) {
	sheet['!ref'] = range_add_cell(sheet['!ref'], range);
}
```

For now it is in the wiki: https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions#adding-a-cell-to-a-range
