### ISSUE TITLE
Cannot Find the Way to Use SheetJS in AngularJS 1 angularjs ui-grid SheetJS dependency injection error occurs

### ISSUE THREAD

**Issue by hsbilgen** [SheetJS/js-xlsx#538]
I cannot find anyone install the SheetJS to their AngularJS app with dependency injection.

I just found the guy without dependency injection and as a plunker [here](http://plnkr.co/edit/GCjZKb?p=preview). But how to import library into AngularJS 1 app is cannot findable no documents related to AngularJS or any example on angularJS

here is dependecy injection with 'ui.grid' example: Can anyone help me on this to inject and work with SheetJS dependencies?? Emergency please

`angular.module('multipleInvoiceUpload', [	'ui.grid', 'ui.grid.resizeColumns', 'ui.grid.pagination', 'ui.grid.selection', 'ui.grid.exporter', 'ui.grid.moveColumns', 'ui.grid.pinning'])
	.controller('MultipleInvoiceUploadCtrl', [
		'$scope', '$state', '$stateParams', 'uiGridConstants', '$localStorage',
		function ($scope, $state, $stateParams, uiGridConstants, $localStorage) `

@SheetJSDev @noodles @kawanet @session @hmalphettes @Sebmaster

**Comment by SheetJSDev** [comment]
We have included an angular JS sample based on https://github.com/brexis/angular-js-xlsx -- please test and let us know if you have any issues
