### ISSUE TITLE
Excel 2010 Support

### ISSUE THREAD

**Issue by mmumshad** [SheetJS/js-xlsx#542]
Hi, any information on Excel 2010/2013 Support?

Thanks

**Comment by reviewher** [comment]
@mmumshad Your question is unclear.  This is not an API for Office but rather a standalone JS library that interacts with data files directly.  In theory it should be able to read and write files that work with Excel 2010 and with Excel 2013, but if you have an example of a problem please share a file.

**Comment by mmumshad** [comment]
It works thanks!!
