### ISSUE TITLE
xlsx : cannot see data in cells

### ISSUE THREAD

**Issue by Zibaire** [SheetJS/js-xlsx#544]
Hello everyone, I trying to make an excel with the code below, the file is create, with two different sheets but I can't see any data into the cells, please could you help me to understand if I made a mistake...

(I use this lib to make a project with TS)

` var data = [["toto"], ["titi"],["tete"], ["tutu"],["otot"], ["itit"],["etet"]];`

`export function GenData(data) {`
`    var tabXL = []`
   ` LogService.GetInstance().info("GENDATA");`
   ` tabXL.push(data);`
 `   Create(tabXL);`
`}`

`function datenum(v, date1904) {`
   ` if (date1904) v += 1462;`
   ` var epoch: any;`
   ` epoch = Date.parse(v);`
   ` var date: any;`
  `  date = new Date(Date.UTC(1899, 11, 30));`
 `   return (epoch - date / (24 * 60 * 60 * 1000));`
`}`

`function sheet_from_array_of_arrays(data) {`
 `   var ws = {};`
  `  var range : any;`
   ` range = { s: { c: 10000000, r: 10000000 }, e: { c: 0, r: 0 } };`
    `for (var R = 0; R != data.length; ++R) {`
     `   for (var C = 0; C != data[R].length; ++C) {`
      `      if (range.s.r > R) range.s.r = R;`
       `     if (range.s.c > C) range.s.c = C;`
        `    if (range.e.r < R) range.e.r = R;`
         `   `if (range.e.c < C) range.e.c = C;`
            `var cell: any`
           ` cell = { v: data[R][C] };`
          `  if (cell.v == null) continue;`
         `   var cell_ref = xlsx.utils.encode_cell({ c: C, r: R });`
        `    if (typeof cell.v === 'number') cell.t = 'n';`
       `     else if (typeof cell.v === 'boolean') cell.t = 'b';`
      `      else cell.t = 's';`
     `       ws[cell_ref] = cell;`
    `    }`
   ` }`
  `  if (range.s.c < 10000000) ws['!ref'] = xlsx.utils.encode_range(range);`
 `   return ws;`
`}`

`function Workbook() : void {`
 `   if (!(this instanceof Workbook)) return new Workbook();`
  `  this.SheetNames = [];`
   ` this.Sheets = {};`
`}`

`function Create(name) {`
`    console.log(name);`
 `   console.log("create entry point");`
`    var wb : any;`
 `   wb  = new Workbook();`
`    var ws_name : String = "Sheet1";`
 `   var wc_name : String= "Sheet2";`
`    var ws = sheet_from_array_of_arrays(name);`
 `   var wc = sheet_from_array_of_arrays(name);`
`    console.log(ws);`
 `   console.log(wc);`
`    wb.SheetNames[0]=ws_name;`
 `   wb.SheetNames[1]=wc_name;`
`    console.log("name");`
`    wb.Sheets[0] = ws;`
  `  wb.Sheets[1] = wc;`
`    xlsx.writeFile(wb, config.get("Export.path"));`
`    LogService.GetInstance().debug("WRITE IS OK");`
`}`

**Comment by reviewher** [comment]
@Zibaire I am not in front of a computer so I cannot test, but I think the problem is in the Sheets assignments.  `Sheets` is an object where the keys are the actual sheet names, not indices, so those assignments should be:

```
wb.Sheets[ws_name] = ws;
wb.Sheets[wc_name] = wc;
```

**Comment by Zibaire** [comment]
@reviewher Thank you so much, It's works! I didn't think about this.
