### ISSUE TITLE
Write XLS with Chinese Characters

### ISSUE THREAD

**Issue by keyiis** [SheetJS/js-xlsx#553]
I want convert below data to xls,Has a simple way write it to xls by sheetjs?
#source data
**head row**
[‘名称’,'价格','数量']
**data rows**
[['衣服',10,100],['帽子',10,100]]

**Comment by SheetJSDev** [comment]
@keyiis check the sample file tests/write.js for how to generate a file from an array of arrays of content in nodejs.

You should only have to change the data object:

```js
var data = [
	['名称','价格','数量'], // <-- header row
	['衣服',10,100], // <-- data row
	['帽子',10,100] // <-- data row
];
```

I am not entirely sure if BIFF2 (excel 2.0) supports chinese characters, but the other formats should be correct.

These are my results: https://gist.github.com/SheetJSDev/03b0717087c9e2c088b593019367fcd9

**Comment by SheetJSDev** [comment]
The new default XLS export is BIFF8 (97-2004) which does support Chinese characters!
