### ISSUE TITLE
nodebuffer is not supported by this browser

### ISSUE THREAD

**Issue by mattburrell** [SheetJS/js-xlsx#556]
I'm now getting the following exception when uploading an .xlsx file. .xls works fine.

.xlsx files were working fine previously so not sure whether a browser update has broken something. I'm using Chrome Version 56.0.2924.87 (64-bit).

```
jszip.min.js:12 Uncaught Error: nodebuffer is not supported by this browser
    at Object.c.checkSupport (jszip.min.js:12)
    at Object.c.transformTo (jszip.min.js:12)
    at r.asNodeBuffer (jszip.min.js:12)
    at getdata (main-client.js:17920)
    at getzipdata (main-client.js:17941)
    at parse_zip (main-client.js:27869)
    at read_zip (main-client.js:28095)
    at Object.readSync [as read] (main-client.js:28111)
    at FileReader.reader.onload (main-client.js:39880)
```

Someone else has reported this issue too on [StackOverflow](http://stackoverflow.com/questions/41997027/uncaught-error-nodebuffer-is-not-supported-by-this-browser).

Any help would be most appreciated.

**Comment by SheetJSDev** [comment]
@mattburrell do you see the same problem in http://oss.sheetjs.com/js-xlsx/ ?  I can't seem to reproduce when using the same chrome version.

Is it possible that you recently made some change that adds a Buffer shim somewhere in your stack?  That particular error can only arise if you are using the script in the browser and shimming Buffer.  Currently the node buffer is tested by checking `typeof Buffer != 'undefined'`.

**Comment by mattburrell** [comment]
@SheetJSDev ah yes. I recently added jsZip and when I remove it the xlsx upload works again!

Thank you very much for your help! Will close the issue.

**Comment by jayabhar** [comment]
Hi,

I am still facing this issue. When I try to print: typeof Buffer != 'undefined', it says true. Can you please suggest a fix?

Thanks,

**Comment by SheetJSDev** [comment]
@jayabhar somewhere in your stack, you are pulling in a buffer shim.  If you are using webpack, you can suppress the behavior with something like:

```js
	node: {
		fs: false,
		Buffer: false
	}
```

That's what we use in the [webpack demo](https://github.com/SheetJS/js-xlsx/blob/master/demos/webpack/webpack.config.js#L9-L12)

**Comment by jayabhar** [comment]
Thank you !!! It worked for me.

**Comment by Syncthreads-unnati** [comment]
i'm getting same error but when i m try to read shp file in zip format inside functional component in reactjs But when same thing we r doing class component is working fine

**Comment by Syncthreads-unnati** [comment]
can u please ell where to find this pollyfill.ts file in my node modules i m unable to find

**Comment by SheetJSDev** [comment]
Upgrading to the latest version should avoid this issue entirely. [Instructions](https://docs.sheetjs.com/docs/getting-started/#installation)

`polyfills.ts` is a typical feature of Angular projects.  If you are seeing this issue in a Create React App project, there is an outstanding issue on polyfills for Buffer and other modules: https://github.com/facebook/create-react-app/issues/11756 .
