### ISSUE TITLE
Getting "#NAME?" as value for some of the formula cell

### ISSUE THREAD

**Issue by vppravi93** [SheetJS/js-xlsx#558]
We have few formula cells which bring data from another sheet. We noticed that Parser fails to calculate some of the formula cells. Interesting fact is that the all the cell fomula point to the same sheet but different cells, but only a few are properly evaluated.

Please see the screenshot which shows two formulas whether one is evaluated and other is not.

![cell_error_001](https://cloud.githubusercontent.com/assets/13347428/22938195/080ef72e-f301-11e6-8bd5-929e06c729e2.png)

**Comment by reviewher** [comment]
@vppravi93 we do not re-evaluate formulae, so the values and formulae you see are the ones that were stored in the file.  My guess is that the file itself stored an error in cell N6.  If the formula is actually valid, then Excel will correct the value when you open the file there.

Here's an example XML Spreadsheet (Excel 2003) file: https://gist.githubusercontent.com/anonymous/fb0918dee93cf0c0a426aa2ca4481b5e/raw/fa843b4f397db7545c24a4d84b1ce93ae339068f/file.xml save it as test.xml and open it in Excel and drag-drop in http://oss.sheetjs.com/js-xlsx/

The cell C6 is encoded as follows:

```xml
    <Cell ss:Formula="=1+1"><Data ss:Type="Error">#VALUE!</Data></Cell>
```

Note that the actual value is stored as an error, but the formula is valid and should be `2`.

The library will read exactly what the file records, so it will give you the `#VALUE!` error.  

Using http://oss.sheetjs.com/js-xlsx/ :

<img width="179" alt="screen shot 2017-02-14 at 09 05 25" src="https://cloud.githubusercontent.com/assets/24845478/22939815/c50ca4ba-f294-11e6-869a-f0b56e8c5026.png">

Using the `xlsx` command in the node package:

```
$ xlsx test.xml 
Sheet1
1,1,1,1
2,2,2,2
3,3,3,3
4,4,4,4
5,5,5,5
#VALUE!,55,#VALUE!,55
```

If you open the file in Excel normally, it will automatically recalculate formulae so you will see that C6 has the correct value `2`:

<img width="288" alt="screen shot 2017-02-14 at 09 07 45" src="https://cloud.githubusercontent.com/assets/24845478/22939915/15354f6e-f295-11e6-809a-c25e2dacd44a.png">

If you change the calculation mode to Manual (follow the instructions in http://stackoverflow.com/a/20597866 ) then Excel will not recalculate and you will see the error:

<img width="285" alt="screen shot 2017-02-14 at 09 08 48" src="https://cloud.githubusercontent.com/assets/24845478/22939971/3c92235c-f295-11e6-99cd-5409530860d6.png">

Can you repeat the steps above with your file and confirm that the error shows up if you set the calculation mode to Manual in Excel?

**Comment by vppravi93** [comment]
@reviewher Thank you for taking time to respond to the issue. Actually the excel file is .xlsm format, it work the way you described for the above test.xml file but despite setting the Formula -> Calculation Option-> Manual, the problematic formula cells were not properly showing the values the .xlsm file i'm dealing with. Fortunately, the Parser returned the proper cell values for the new version of the file client sent to us. So I am good now, please feel free to close the issue.
