### ISSUE TITLE
Load a file, Add one column (or row) and write a value in, how to do?

### ISSUE THREAD

**Issue by Ideandro** [SheetJS/js-xlsx#561]
I can not figure out how to do it:

- Load a .xlsx file (done!)
- Add a column (or row) (???)
- Write a value in (???)

It's possible to do it?
It's possible write a value out of ws['!ref']?
How to update this value (!ref)?
It's possible to see an example?
Thanks!

**Comment by SheetJSDev** [comment]
There's a wildly destructive way to do this:

- convert worksheet to an array of arrays (`sheet_to_json` with `{raw:true, header:1}`)
- manipulate the array of arrays:
-- insert your row by splicing the outer array with a empty row
-- insert your column by iterating through every row
- convert array of arrays back to a worksheet (`aoa_to_sheet`)

The hard part of manipulating the raw object representation is making sure everything else is consistent.  Take formulae.  How do you ensure that you update formula references when you insert or delete rows or columns?  You need to walk every formula and fix them.

**Comment by SheetJSDev** [comment]
We added a `sheet_add_aoa` helper function that can modify an existing worksheet with data specified in an array of arrays.  `sheet_add_json` takes an array of JS objects.  See #947 for a complete example.
