### ISSUE TITLE
Calculate Formula Results

### ISSUE THREAD

**Issue by boxpear** [SheetJS/js-xlsx#564]
Feel free to delete if off-topic.

We have a tool that exports data from an internal data store.  It has formulas at the last row to calculate averages and other stuff.  js-xlsx reads the formulas but the values are `0`.  Can js-xlsx calculate the results?

**Comment by reviewher** [comment]
This library does not automatically recalculate formulae. You need something like https://github.com/fabiooshiro/xlsx-calc.

Duplicate of https://github.com/SheetJS/js-xlsx/issues/481
