### ISSUE TITLE
in amcharts use your library sheetjs and working fine in chrome but in IE11 second download stop on resuming

### ISSUE THREAD

**Issue by saber13812002** [SheetJS/js-xlsx#566]
AMcharts using sheetjs for export to xslx and working fine in chrome

in IE11 when click download for the first time this works fine

but in second try (this AMchart or every others) [resuming...] prompt in downloads shows and pause and never stop

when clear download lists then restart ie ,problem still there in download lists  and [resuming...] appears and export2 excel doesnt work. but prompt for starting download appears, after click on save or open nothing happen except errors.

it seems about download resuming algorithm bug in IE . that try to resume completed download! and cant !!! 

![image](https://cloud.githubusercontent.com/assets/3294604/23208364/ee8984b8-f909-11e6-867f-ac704d32815d.png)

**Comment by reviewher** [comment]
This sounds like an issue with the code that actually sends the file to the client.  Have you asked the AMcharts people?

**Comment by SheetJSDev** [comment]
This sounds like something coming from AMcharts, I'd raise the issue with them first
