### ISSUE TITLE
Creating LARGE files that are not that big

### ISSUE THREAD

**Issue by thiagohagy** [SheetJS/js-xlsx#568]
When I write some files ( more or less 200K lines) , they are created with +- 100MB, but if I open those files on LibreOffice and then only edit  any cell and save again, the file is saved with just 7Mb. Exist any config to decrease the files size that I am not using?

**Comment by reviewher** [comment]
@thiagohagy for performance and compatibility reasons, the default options sacrifice file size.  But it is straightforward to decrease the file size:

1) pass the option `compression:true` to the write function.  XLSX is a ZIP-based format and the default is no compression.  You can enable compression to generate a smaller file but it may take much longer to generate the file.

2) if many of your cells are text and some text values are repeated many times, pass the option `bookSST:true`. This reduces file size by but iOS Numbers in particular chokes on files using the shared string table

**Comment by SheetJSDev** [comment]
@thiagohagy Can you check the following option sets and report on the file sizes:

A) `var opts = {bookType: 'xlsx'};`

B) `var opts = {bookType: 'xlsb'};`

C) `var opts = {compression:true, bookType: 'xlsx'};`

D) `var opts = {compression:true, bookType: 'xlsb'};`

E) `var opts = {bookSST:true, bookType: 'xlsx'};`

F) `var opts = {bookSST:true, bookType: 'xlsb'};`

G) `var opts = {bookSST:true, compression:true, bookType: 'xlsx'};`

H) `var opts = {bookSST:true, compression:true, bookType: 'xlsb'};`

I) `var opts = {bookType: 'biff2'};`

J) `var opts = {bookSST:true, bookType: 'biff2'};`

**Comment by thiagohagy** [comment]
whit the options :
{ bookSST: true, bookType: 'xlsx' }, 
{ bookSST: true, bookType: 'xlsb' }, 
{ bookSST: true, compression: true, bookType: 'xlsx' }, 
{ bookSST: true, compression: true, bookType: 'xlsb' }, 
The size of the files are considerably decreased, but as you said, the time to generate the files take much longer for big files.So I'm  going to use this options for smaller files and keep the big files as they are.
thanks a lot for the atention and the help
Congrats for the project

**Comment by SheetJSDev** [comment]
@thiagohagy it's unfair that Excel and LibreOffice can use highly optimized compiled code while we have to run everything in the browser!  At some point we hope to revisit the ZIP situation
