### ISSUE TITLE
How can I create an xlsm file ?

### ISSUE THREAD

**Issue by mca22120** [SheetJS/js-xlsx#577]
Hello, I'm a beginner and I don't understand how can I create an xlsm file with this code. I try to change this line : XLSX.writeFile(wb, 'test.xlsx')     by this one    :   XLSX.writeFile(wb, 'test.xlsm')   but it doesn't work. 

Could you help me ?
Thanks !

`var XLSX = require('XLSX')

/*function datenum(v, date1904) {
	if(date1904) v+=1462;
	var epoch = Date.parse(v);
	return (epoch - new Date(Date.UTC(1899, 11, 30))) / (24 * 60 * 60 * 1000);
}*/

function sheet_from_array_of_arrays(data, opts) {
	var ws = {};
	var range = {s: {c:1, r:1}, e: {c:0, r:0 }};
	for(var R = 0; R != data.length; ++R) {
		for(var C = 0; C != data[R].length; ++C) {
			if(range.s.r > R) range.s.r = R;
			if(range.s.c > C) range.s.c = C;
			if(range.e.r < R) range.e.r = R;
			if(range.e.c < C) range.e.c = C;
			var cell = {v: data[R][C] };
			if(cell.v == null) continue;
			var cell_ref = XLSX.utils.encode_cell({c:C,r:R});
			
			if(typeof cell.v === 'number') cell.t = 'n';
			/*else if(typeof cell.v === 'boolean') cell.t = 'b';
			else if(cell.v instanceof Date) {
				cell.t = 'n'; cell.z = XLSX.SSF._table[14];
				cell.v = datenum(cell.v);
			}
			else cell.t = 's';*/
			
			ws[cell_ref] = cell;
		}
	}
	if(range.s.c < 1) ws['!ref'] = XLSX.utils.encode_range(range);
	return ws;
}

/* original data */
var data = [[1,2,3]]
var ws_name = "SheetJS";

function Workbook() {
	if(!(this instanceof Workbook)) return new Workbook();
	this.SheetNames = [];
	this.Sheets = {};
}

var wb = new Workbook(), ws = sheet_from_array_of_arrays(data);

/* add worksheet to workbook */
wb.SheetNames.push(ws_name);
wb.Sheets[ws_name] = ws;

/* write file */
XLSX.writeFile(wb, 'test.xlsx'); `

**Comment by reviewher** [comment]
Suppose you had your data:

```js
var data = [
  ["col A", "col B", "col C"],
  [1,2,3],
  ["foo", "bar", "baz"]
]
```

Then the following will generate an XLSM workbook:

```js
// var XLSX = require('xlsx'); // <-- uncomment this in node
var wb = {SheetNames:["Sheet1"], Sheets:{Sheet1:XLSX.utils.aoa_to_sheet(data)}};
```

To actually distribute the file, use one of the techniques outlined [in the README](https://github.com/SheetJS/js-xlsx#writing-workbooks).  For example, you can use `writeFile` in node:

```js
XLSX.writeFile(wb, 'test.xlsm');
```

Please follow up if you have any other questions.
