### ISSUE TITLE
Problem of style is finally resolved

### ISSUE THREAD

**Issue by ismailkomay** [SheetJS/js-xlsx#580]
[full.zip](https://github.com/SheetJS/js-xlsx/files/817251/full.zip)

I prepare a one js file (zipped) including a style 

Unzip the file.then include it + include filesaver.js

Then use it as an example above (i only mention  the script part) : 
index.html : 

```html
<!-- header -->
<script src="http://cdn.jsdelivr.net/g/filesaver.js" type="text/javascript"></script>
<script src="full.js" type="text/javascript"></script>


<!-- script -->
<script>
var wb = new Workbook();
var ws = {};
var defaultStyles = {
    font: {
        name: "Arial",
        sz: 11,
        bold: false,
        underline: true,
        color: {rgb: "FF000000"}
    }
};
var headerStyles = {
    font: {
        name: "Arial",
        sz: 15,
        bold: true,
        underline: false,
        color: {rgb: "FF0000FF"}},
    fill: { fgColor: { rgb: "FFFFA500"}},
    border: {
        top: {style: 'medium',
            color: {rgb: "FFFFAA00"}},
        left: {style: 'medium', color: {rgb: "FFFFAA00"}}
    }
};

var sheetName = "Onglet";
var wscols=[];
wscols = [{wch: 20},{wch: 30},{wch: 40},{wch: 50}];
setColsWithToSheet(ws,wscols);
setColWithToSheet(ws,wscols,0,150);
fillCelluleByAddress(wb,ws, sheetName, null, createObjetRowCol(1,1), headerStyles);
fillCelluleByAddress(wb,ws, sheetName, '2', createObjetRowCol(1,2), headerStyles);
fillCelluleByAddress(wb,ws, sheetName, "data", createObjetRowCol(1,3), defaultStyles);
fillCelluleByAddress(wb,ws, sheetName, new Date("2014-02-19T14:30Z"), createObjetRowCol(1,4), defaultStyles);
fillCelluleByAddress(wb,ws, sheetName, '0.5', createObjetRowCol(1,5), defaultStyles);
fillCelluleByAddress(wb,ws, sheetName, new Date("2014-02-19T14:30Z"), createObjetRowCol(1,6), defaultStyles,'DatewithTime');
fillCelluleByAddress(wb,ws, sheetName, 0.5, createObjetRowCol(1,7), defaultStyles,'percent');
setColWithToSheet(ws,wscols,0,10);
setColWithToSheet(ws,wscols,5,40);
var wopts = setWopts();
saveFile(wb,wopts,'Komay.xlsx');
</script>
```

**Comment by Aymkdn** [comment]
Hi,

Your file works. But could you explain which changes you have done on js-xlsx to make it work please?

**Comment by mattbalza** [comment]
Hi,
This code works super well :)
Could you please help us understand what you changed exactly? I see that a lot of the original js-xlsx code has been changed.

Thanks!

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by bismoy2013** [comment]
@SheetJSDev please stop commenting same line everywhere :)

**Comment by conceptualspace** [comment]
it would be less sickening if it were an honest comment, such as, "styling is available as a paid feature to continue to support the project", or, "that is in the commercial version of the software", instead of appealing to a false notion of "fairness". how many devs in the github would would read, "turned around and made it open source" as a negative thing lol

**Comment by bismoy2013** [comment]
hehe @conceptualspace

**Comment by KrPawan** [comment]
> [full.zip](https://github.com/SheetJS/js-xlsx/files/817251/full.zip)
> 
> I prepare a one js file (zipped) including a style
> 
> Unzip the file.then include it + include filesaver.js
> 
> Then use it as an example above (i only mention the script part) : index.html :
> 
> ```
> 
> <script src="http://cdn.jsdelivr.net/g/filesaver.js" type="text/javascript"></script>
> <script src="full.js" type="text/javascript"></script>
> 
> 
> 
> <script>
> var wb = new Workbook();
> var ws = {};
> var defaultStyles = {
>     font: {
>         name: "Arial",
>         sz: 11,
>         bold: false,
>         underline: true,
>         color: {rgb: "FF000000"}
>     }
> };
> var headerStyles = {
>     font: {
>         name: "Arial",
>         sz: 15,
>         bold: true,
>         underline: false,
>         color: {rgb: "FF0000FF"}},
>     fill: { fgColor: { rgb: "FFFFA500"}},
>     border: {
>         top: {style: 'medium',
>             color: {rgb: "FFFFAA00"}},
>         left: {style: 'medium', color: {rgb: "FFFFAA00"}}
>     }
> };
> 
> var sheetName = "Onglet";
> var wscols=[];
> wscols = [{wch: 20},{wch: 30},{wch: 40},{wch: 50}];
> setColsWithToSheet(ws,wscols);
> setColWithToSheet(ws,wscols,0,150);
> fillCelluleByAddress(wb,ws, sheetName, null, createObjetRowCol(1,1), headerStyles);
> fillCelluleByAddress(wb,ws, sheetName, '2', createObjetRowCol(1,2), headerStyles);
> fillCelluleByAddress(wb,ws, sheetName, "data", createObjetRowCol(1,3), defaultStyles);
> fillCelluleByAddress(wb,ws, sheetName, new Date("2014-02-19T14:30Z"), createObjetRowCol(1,4), defaultStyles);
> fillCelluleByAddress(wb,ws, sheetName, '0.5', createObjetRowCol(1,5), defaultStyles);
> fillCelluleByAddress(wb,ws, sheetName, new Date("2014-02-19T14:30Z"), createObjetRowCol(1,6), defaultStyles,'DatewithTime');
> fillCelluleByAddress(wb,ws, sheetName, 0.5, createObjetRowCol(1,7), defaultStyles,'percent');
> setColWithToSheet(ws,wscols,0,10);
> setColWithToSheet(ws,wscols,5,40);
> var wopts = setWopts();
> saveFile(wb,wopts,'Komay.xlsx');
> </script>
> ```

Thank You . This is working Fine.
