### ISSUE TITLE
Doesn't work in webpack: Can't resolve '../xlsx.js' 

### ISSUE THREAD

**Issue by gongph** [SheetJS/js-xlsx#585]
look this: 
```
WARNING in ./~/xlsx/ods.js
Module not found: Error: Can't resolve '../xlsx.js' in 'F:\gittest\js-office-demo\node_modules\xlsx'

 @ ./~/xlsx/ods.js 10:9-30
 @ ./~/xlsx/xlsx.js
 @ ./src/index.js

ERROR in ./~/xlsx/dist/cpexcel.js
Module not found: Error: Can't resolve './cptable' in 'F:\gittest\js-office-demo\node_modules\xlsx\d
ist'
 @ ./~/xlsx/dist/cpexcel.js 808:16-41
 @ ./~/xlsx/xlsx.js
 @ ./src/index.js
```

**Comment by SheetJSDev** [comment]
right now, you can suppress those in the webpack config.  The webpack demo (in the demos/webpack subdirectory of the git repo) has the following

```js
	externals: [
		{
			'./cptable': 'var cptable',
			'../xlsx.js': 'var _XLSX'
		}
	]
```

Soon we will rework the codepage library to omit the require statement and fold the ODS code into the main script.  Keep the issue open until then.

**Comment by gongph** [comment]
Dear, thank you very much. The problem has been solved! @SheetJSDev

**Comment by SheetJSDev** [comment]
https://github.com/SheetJS/js-xlsx/issues/285 is also tracking the issue

**Comment by pranaydp** [comment]
Failed to compile.

./node_modules/tempa-xlsx/ods.js
Module not found: Can't resolve 'xlsx' in 'D:\OFFICE\workspace\geo\node_modules\tempa-xlsx'


please can solve this issue I am not getting what to do?????

**Comment by maheshitechnotion** [comment]
Hi Pranaydp 
install this package  npm install xlsx  it's working

**Comment by maheshitechnotion** [comment]
> Failed to compile.
> 
> ./node_modules/tempa-xlsx/ods.js
> Module not found: Can't resolve 'xlsx' in 'D:\OFFICE\workspace\geo\node_modules\tempa-xlsx'
> 
> please can solve this issue I am not getting what to do?????

install this package npm install xlsx it's working

**Comment by Shtokins** [comment]
I've read tons of related topics and tried everything. But in my case this helped: 
In webpack config in `externals` replace  `{ "../xlsx.js": "var _XLSX" }` with `{ "../xlsx": "var _XLSX" } `
