### ISSUE TITLE
Disabling optional modules using Webpack is not working

### ISSUE THREAD

**Issue by petergombos** [SheetJS/js-xlsx#590]
Hi there, trying not to include the optional packages using 0.9.2, here is my resolve code:

```
resolve : {
    root       : paths.client(),
    extensions : ['', '.js', '.jsx', '.json'],
    alias: {
      './dist/cpexcel.js': '',
      './dist/jszip.js': ''
    }
  },
```

Unfortunately it does not have any impact, my build file size stays the exact same with or without of these in my config file.

Anything I'm missing?

Thanks!
P

**Comment by SheetJSDev** [comment]
We have a webpack demo in `demos/webpack` directory of the repo: https://github.com/SheetJS/js-xlsx/tree/master/demos/webpack  I copied that directory to a new location and installed a copy of `xlsx` from npm. 

The main.js is very simple, the only purpose is to expose the XLSX variable:

```js
var XLSX = require('xlsx');
console.log("it works!");
module.exports = XLSX;
```

The webpack config file is:

```js
module.exports = {
	output: {
		libraryTarget: 'var',
		library: 'XLSX'
	},
	module: {
		noParse: [/jszip.js$/]
	},
	node: {
		fs: false,
		Buffer: false
	},
//	resolve: {
//		alias: { "./dist/cpexcel.js": "" }
//	}
}
```

And the command is:

```bash
$ webpack main.js --output-filename webpack.js --display-modules --profile
```

If I run with those 3 lines commented out (so the build includes the cpexcel library), the file is included:

```
     Asset    Size  Chunks                    Chunk Names
webpack.js  933 kB       0  [emitted]  [big]  main
   [1] ../~/xlsx/xlsx.js 454 kB {0} [built]
       [] -> factory:5ms building:399ms = 404ms
   [2] ../~/xlsx/dist/cpexcel.js 188 kB {0} [built]
       [] -> factory:3ms building:145ms = 148ms
   [3] ../~/xlsx/jszip.js 287 kB {0} [built]
       [] -> factory:3ms building:4ms = 7ms
   [5] ./main.js 77 bytes {0} [built]
        factory:21ms building:16ms = 37ms
    + 2 hidden modules
```

If I uncomment those 3 lines, webpack skips the file

```
webpack.js  745 kB       0  [emitted]  [big]  main
   [0] ../~/xlsx/xlsx.js 454 kB {0} [built]
       [] -> factory:5ms building:396ms dependencies:3ms = 404ms
   [2] ../~/xlsx/jszip.js 287 kB {0} [built]
       [] -> factory:4ms building:4ms = 8ms
   [4] ./main.js 77 bytes {0} [built]
        factory:21ms building:15ms = 36ms
    + 2 hidden modules
```

I am not that familiar with webpack, based on the file sizes there's a significant difference between the two.  If you can share a small example where this breaks down, I can take a look

**Comment by slinhart** [comment]
This worked for me @SheetJSDev. Thanks for providing detailed sample. :1st_place_medal:

**Comment by SheetJSDev** [comment]
@petergombos I believe that the aforementioned fix resolves the issue.  Please reopen the issue if it doesn't work
