### ISSUE TITLE
XLS column widths

### ISSUE THREAD

**Issue by sheeeeep** [SheetJS/js-xlsx#591]
there is no ['!col'] in my worksheet.

`
var workbook = XLSX.readFile('inputFiles/data.xls');
const worksheet = workbook.Sheets.Sheet1;
`

**Comment by SheetJSDev** [comment]
Column widths are currently calculated only for XLSX and they are available at the key `'!cols'`.

**Comment by sheeeeep** [comment]
Thanks.
After save to XLSX, still no  ['!cols'] in my worksheet.
![image](https://cloud.githubusercontent.com/assets/16912701/24347445/f0fd565a-130a-11e7-9b69-ecf1b45ce4d5.png)

**Comment by SheetJSDev** [comment]
@sheeeeep can you change the read line to:

```js
var workbook = XLSX.readFile('inputFiles/data.xlsx', {cellStyles:true});
```

**Comment by sheeeeep** [comment]
It's ok, thank you very much.
