### ISSUE TITLE
Non removal of empty columns

### ISSUE THREAD

**Issue by rashthedude** [SheetJS/js-xlsx#592]
I'm currently using this library and empty columns/cells are removed when parsed, is there an option to keep them somehow?

**Comment by rashthedude** [comment]
This is what I'm doing more or less:

var sheet_name_list = workbook.SheetNames;
sheet_name_list.forEach(function(y) { /* iterate through sheets */
  var worksheet = workbook.Sheets[y];
  for (var z in worksheet) {
    /* all keys that do not begin with "!" correspond to cell addresses */
    if(z[0] === '!') continue;
    console.log(y + "!" + z + "=" + JSON.stringify(worksheet[z].v));
  }
});

It loops through every nonempty sheet. But my question is how can I maintain/keep the empty sheets?

**Comment by SheetJSDev** [comment]
@rashthedude I assume you mean empty cell.

README: https://github.com/SheetJS/js-xlsx#worksheet-object

Each worksheet stores its range in a key `!ref`.  If `worksheet` is the your sheet, then `worksheet['!ref']` is the range.  Using the `XLSX.utils.decode_range` function, you can get the full extent of the worksheet.  Then you can loop across the sheet by looping across all rows and columns in the range:

```js
var range = XLSX.utils.decode_range(worksheet['!ref']);
for(var R = range.s.r; R <= range.e.r; ++R) {
  for(var C = range.s.c; C <= range.e.c; ++C) {
    var coord = XLSX.utils.encode_cell({r:R,c:C});
    if(!worksheet[coord]) {
      /* The cell is not specified in the worksheet */
    } else {
      /* worksheet[coord] is a valid cell */
    }
  }
}
```

The utilities functions skip the `encode_cell` calls by pre-computing the column names.  For example, [`sheet_to_csv`](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L152-L164) essentially does:

```js
var range = XLSX.utils.decode_range(sheet["!ref"]);
var rowlabel = "";
var cols = [];
var R = 0, C = 0;

/* precompute column labels */
for(C = range.s.c; C <= range.e.c; ++C) cols[C] = encode_col(C);

for(R = range.s.r; R <= range.e.r; ++R) {
  /* precompute row label */
  rowlabel = encode_row(R);
  for(C = range.s.c; C <= range.e.c; ++C) {
    /* a cell reference is merely a column label concatenated with a row label*/
    val = sheet[cols[C] + rowlabel];
    /* do something */
  }
}
```

**Comment by rashthedude** [comment]
Hi there, 

Thanks for the swift reply but I'm a little confused. To give you a clear idea of what I'm doing:

workbook - xlsx.readFile(file)
sheet_name_list = workbook.SheetNames

sheet_name_list.forEach( (y)   ->
   worksheet = workbook.Sheets[y]
   for m, n of worksheet
      // do something here

So where exactly do I make use of "decode_range"?

**Comment by SheetJSDev** [comment]
@rashthedude The worksheets are objects whose keys are cell addresses (like `B3`) and whose values are cell objects.  The code you presented will iterate across the cells.  In retrospect that's not a great pattern and we will remove it from the README.

What exactly are you trying to do?  For example, if you just want to get the content as an array of arrays, the `sheet_to_json` utility function will do that.

**Comment by rashthedude** [comment]
@SheetJSDev Yes I'm trying to fetch the content as an array and iterate over it.

**Comment by rashthedude** [comment]
Managed to get it to work at last. Thanks again @SheetJSDev.

**Comment by SheetJSDev** [comment]
@rashthedude sheet_to_json, as the name indicates, takes a worksheet :D Feel free to raise another issue if you encounter more issues.

**Comment by yash2503** [comment]
@rashthedude could you please share how did you resolve the issue, I am facing the same issue right now.

**Comment by Reejesh-PK** [comment]
Make sure you are using the latest version of js from https://cdn.sheetjs.com/ (Read "how to use") and you can refer this https://github.com/SheetJS/sheetjs/issues/159#issuecomment-403228877
