### ISSUE TITLE
Improve doc for optional module

### ISSUE THREAD

**Issue by ScreamZ** [SheetJS/js-xlsx#596]
Hello, first I want to thank you for this great tool !

Just wanted to know the difference between
https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.core.min.js
AND
https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.min.js

I'm using in browser with a good old Symfony app

Best regards

**Comment by reviewher** [comment]
There are 3 minified source files:

- `xlsx.min.js` is the minified version of this library.
- `xlsx.core.min.js` includes dependencies .
- `xlsx.full.min.js` also includes optional modules.

XLSX, XLSB and ODS support requires a zip reader/writer.  The default `xlsx.min.js` does not include it, so you have to include [jszip.js](https://github.com/SheetJS/js-xlsx/blob/master/dist/jszip.js) before `xlsx.min.js`.  However, both `xlsx.core.min.js` and `xlsx.full.min.js` embed the zip library in the source, so you can use one of those as your only include.

The `full` file also includes a codepage library that allows you to read international files generated by older versions of Excel as well as some third party libraries.  It is a pretty hefty dependency and isn't necessary for a strictly English US based audience, so it's not included in the core distribution.

**Comment by ScreamZ** [comment]
@reviewher Awesome thanks.

Maybe add a section in the readme about that ? 

Regards.
