### ISSUE TITLE
How to add information on an existing workbook

### ISSUE THREAD

**Issue by thiagohagy** [SheetJS/js-xlsx#598]
I want to create a file and save it into a folder, then I want to open this file and add some content several times.Can I do this?

**Comment by manikmi** [comment]
I too have a similar requirement. I want to keep the excel file (with formulae and charts, which get data from named ranges) stored on the server as a template, load the excel into memory, push the data from the DB to the named ranges and download updated file to client.

Is it possible using xlsx?

**Comment by SheetJSDev** [comment]
Template data editing is offered in the Pro compendium (our paid offering). The Community version is primarily focused on data preservation.

https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021 is our general commentary.
