### ISSUE TITLE
Set cell style when creating new .xlsx

### ISSUE THREAD

**Issue by Matas555** [SheetJS/js-xlsx#609]
Is it possible to set cell style? if, yes how? When trying to parse it clearly returns it:
`  A1:
   { t: 'n',
     v: 1,
     w: '1',
     s:
      { patternType: 'solid',
        fgColor: { rgb: 'FFFF00' },
        bgColor: { indexed: 64 } } } }
`

But what about setting it?

**Comment by SheetJSDev** [comment]
Writing styles is currently not supported, and we will be changing the style representation soon.  Stay tuned.

**Comment by sebius8780** [comment]
The only question that remains : when ?? I'd love to do my part in this if you need !

**Comment by shoshannamb** [comment]
@SheetJSDev Any ideas on when that would land? It would be really awesome to incorporate into my current project. We're looking into some pretty ugly workarounds right now and a supported solution would obviously be way better.

**Comment by xSirrioNx** [comment]
@Matas555 , @shoshannamb , i just make a fork, where try to implement styles and images from another forks to current version in main project (0.10.2)
https://github.com/xSirrioNx/js-xlsx

**Comment by Albion87** [comment]
@SheetJSDev  : is it possible to format XLSX document before export from the html

**Comment by vinhboy** [comment]
@xSirrioNx -- I tried your branch with the following configs, and it did not work. Any suggestions?

```
    let wb = XLSX.utils.table_to_book(tbl);
    wb.Sheets.Sheet1.A1.s = { fill: {patternType: "none",fgColor: {rgb: "FF000000"},bgColor: {rgb: "00000000"}} }
```

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
