### ISSUE TITLE
Writing cell size in pixels not working

### ISSUE THREAD

**Issue by paulck** [SheetJS/js-xlsx#611]
Hi all,

if i simply switch the width from wch:20 to wpx:200 (in the columns property), that doesn't work.

**Comment by reviewher** [comment]
Are you running in node or the browser?  Can you share what the workbook object looks like before writing (`console.log(workbook)`)? 

See [`tests/write.js`](https://github.com/SheetJS/js-xlsx/blob/master/tests/write.js#L14) -- it tests both character and pixel specifications

**Comment by SheetJSDev** [comment]
I started from the write demo that @reviewher referenced, and changed the columns array to

```js
var wscols = [
	{wch:6},
	{wpx:50},
	{wch:10},
	{wpx:200} // <-- here's your 200 px
];
```

The worksheet (verify from the console) should have the following col spec:

```
  '!cols': [ { wch: 6 }, { wpx: 50 }, { wch: 10 }, { wpx: 200 } ]
```

Here's the file it generated: [sheetjs.xlsx](https://github.com/SheetJS/js-xlsx/files/882920/sheetjs.xlsx) -- you'll see the D column is 200 px.

Please test and let us know if it works.  If it does not, please reopen and share some code that fails.

**Comment by ob-sc** [comment]
I have the same Issue, my cols should be 64 and 128 px but they are 85 and 171 px when I open the worksheet in excel.

This is a sheet from the workbook in console:

`Sheets:
10 Hamburg-Jenfeld:
A1: {v: "PN", t: "s"}
B1: {v: "Nachname", t: "s"}
C1: {v: "Vorname", t: "s"}
D1: {v: "AZ", t: "s"}
E1: {v: "Gehalt", t: "s"}
F1: {v: "Tage", t: "s"}
G1: {v: "Urlaub", t: "s"}
H1: {v: "Status", t: "s"}
!ref: "A1:H1"
!cols: Array(8)
0: {wpx: 64}
1: {wpx: 128}
2: {wpx: 128}
3: {wpx: 64}
4: {wpx: 64}
5: {wpx: 64}
6: {wpx: 64}
7: {wpx: 64}
length: 8
__proto__: Array(0)
__proto__: Object`
