### ISSUE TITLE
Can you define multiple ranges in the utility functions?

### ISSUE THREAD

**Issue by nickfogler** [SheetJS/js-xlsx#616]
For example: `ws['!ref'] = "D1:E5,B12:D18"`

**Comment by SheetJSDev** [comment]
You can't specify "multiple ranges" because the operations aren't really well-defined on disjoint ranges.  There are two ways to proceed, depending on what you want:

- If you need a unified output, combine the ranges into a larger range that includes the ranges you want to cover.  For example, `D1:E5` and `B2:D18` are subranges of `B1:E18`.

- If you need separate outputs for each range, you can directly change the `!ref`:

```js
ws['!ref'] = "D1:E5";
XLSX.utils.sheet_to_csv(ws); // CSV output for the range D1:E5
ws['!ref'] = "B12:D18";
XLSX.utils.sheet_to_csv(ws); // CSV output for the range B12:D18
```

Changing the `!ref` won't automatically change the rest of the worksheet, so it's a lightweight way of controlling the output functions.  FWIW It's also used in the workbook writing functions.

**Comment by reviewher** [comment]
@nickfogler like @SheetJSDev said it makes no sense to use disjoint ranges.  Try this to combine the ranges:

```js
function combine_ranges(str/*:String*/)/*:Range*/ {
	var o = {s:{c:2000000, r:2000000},e:{c:0,r:0}}
	str.split(",").map(function(s) {
		return XLSX.utils.decode_range(s);
	}).forEach(function(r){
		if(o.s.c > r.s.c) o.s.c = r.s.c;
		if(o.s.r > r.s.r) o.s.r = r.s.r;
		if(o.e.c < r.e.c) o.e.c = r.e.c;
		if(o.e.r < r.e.r) o.e.r = r.e.r;
	});
	return XLSX.utils.encode_range(o);
}
```

For your example, `combine_ranges("D1:E5,B12:D18")` gives `'B1:E18'`

If you can be more specific regarding what you expect, we can find a way to do it.

**Comment by nickfogler** [comment]
Thanks for your responses.  In my case, the combined range of B1:E18 is not what I'm looking for.  In the attached excel file, you can see the two different sections of the document I want to parse out.  The expected JSON returned would be:
```[ 
  { 'TOP Code(s)': '61220', 'Program Title': 'Film Production' },
  { 'TOP Code(s)': '614', 'Program Title': 'Graphics and Digital Imagry' } 
  { 'SOC Code': '274011','Occupational Title': 'Audio/Video Equipment Technicians','Annual Openings': '914' },
  { 'SOC Code': '499096','Occupational Title': 'Riggers','Annual Openings': '67' },
  { 'SOC Code': '393092','Occupational Title': 'Costume Attendants','Annual Openings': '218' },
  { 'SOC Code': '274032','Occupational Title': 'Film and Video Edior','Annual Openings': '910' },
  { 'SOC Code': '271027','Occupational Title': 'Set and Exhibit Designers','Annual Openings': '222' },
  { 'SOC Code': '472141','Occupational Title': 'Painters, Construction, Matinenance','Annual Openings': '1658' } 
  ]```
[WLAC-CurricStrengthening-Film.xlsx](https://github.com/SheetJS/js-xlsx/files/883735/WLAC-CurricStrengthening-Film.xlsx)

**Comment by nickfogler** [comment]
[WLAC-CurricStrengthening-Film.xlsx](https://github.com/SheetJS/js-xlsx/files/883737/WLAC-CurricStrengthening-Film.xlsx)

**Comment by nickfogler** [comment]
It sounds like I can use @reviewher's first suggestion to get the individual JSON blobs and then join them.  My follow up question would be this:  The starting row of the second range is variable (based on the number of rows preceding it). Is there a utility in the library that can search the document for a reference value in the sheet which I can use to determine the starting row of a range?

**Comment by SheetJSDev** [comment]
You want the second approach:

```js
var XLSX = require('xlsx');
var wb = XLSX.readFile('WLAC-CurricStrengthening-Film.xlsx');
var ws = wb.Sheets['Local Share LMI'];

/* first part */
ws['!ref'] = "D1:E5"; // change the range to the first block
var o1 = XLSX.utils.sheet_to_json(ws);

/* second part */
ws['!ref'] = "B12:D18"; // change the range to the second block
var o2 = XLSX.utils.sheet_to_json(ws);

var output = o1.concat(o2);
```

And output is:

```
[
  { 'TOP Code(s)': '61220', 'Program Title': 'Film Production' },
  { 'TOP Code(s)': '614', 'Program Title': 'Graphics and Digital Imagry' },
  { 'SOC Code': '274011', 'Occupational Title': 'Audio/Video Equipment Technicians', 'Annual Openings': '914' },
  { 'SOC Code': '499096', 'Occupational Title': 'Riggers', 'Annual Openings': '67' },
  { 'SOC Code': '393092', 'Occupational Title': 'Costume Attendants', 'Annual Openings': '218' },
  { 'SOC Code': '274032', 'Occupational Title': 'Film and Video Edior', 'Annual Openings': '910' },
  { 'SOC Code': '271027', 'Occupational Title': 'Set and Exhibit Designers', 'Annual Openings': '222' },
  { 'SOC Code': '472141', 'Occupational Title': 'Painters, Construction, Matinenance', 'Annual Openings': '1658' }
]
```

**Comment by nickfogler** [comment]
@SheetJSDev Thanks so much!  I think we posted at the same time. Did you see my question above?

**Comment by SheetJSDev** [comment]
> Is there a utility in the library that can search the document for a reference value in the sheet which I can use to determine the starting row of the second range?

@nickfogler No utility yet, but it's not particularly hard to write.  You can loop across the sheet:

```js
var range = XLSX.utils.decode_range(ws['!ref']);
for(var R = range.s.r; R <= range.e.r; ++R) {
  for(var C = range.s.c; C <= range.e.c; ++C) {
    var cell_address = {c:C, r:R};
    var cell = ws[cell_address];
    if(!cell) continue; // <-- if the cell is not specified
    // the cell `t` key tells you the type and the `v` key is the stored value
  }
}
```

Also take a look at the sheet_to_csv function: https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L165-L171 is the part that walks the sheet and checks every cell.

The README describes the [object model](https://github.com/sheetjs/js-xlsx#workbook--worksheet--cell-object-description) -- let us know how we can improve it!

**Comment by nickfogler** [comment]
Awesome, thank you!!
