### ISSUE TITLE
Unsupported file 115|104|105|112

### ISSUE THREAD

**Issue by ayush000** [SheetJS/js-xlsx#617]
Hi,

It's an xls file (I think in 97 -2004 format). It's being uploaded and sent to the server and read from file.buffer. Also, uploading it to online demo doesn't give any output.
[abc.xls.zip](https://github.com/SheetJS/js-xlsx/files/885017/abc.xls.zip)

**Comment by SheetJSDev** [comment]
This is actually a tab-separated-values file (open the file in notepad or vim or your favorite text editor and you will see text).  

We're aiming to add csv/txt support soon

**Comment by ayush000** [comment]
Thanks for the information.
