### ISSUE TITLE
Negative Percent on cell

### ISSUE THREAD

**Issue by firas3d** [SheetJS/js-xlsx#619]
Hello,
The Excel table has a cell with value : -5%
The `XLSX.utils.sheet_to_json` return : -0

Positive value works perfectly,
only Negative value do not.

Is there something i need change in reading?
`var data = XLSX.utils.sheet_to_json(first_worksheet, {header:1});`

![image](https://cloud.githubusercontent.com/assets/17760039/24651942/c0fd2426-1940-11e7-84ea-bc9278c0ad93.png)

The Excel file : 
![image](https://cloud.githubusercontent.com/assets/17760039/24651513/1de56a7e-193f-11e7-9e1d-771075215e53.png)

Note : I am using the the js-xlsx insude adobe extendscript

Appreciate your help,
Firas.

**Comment by SheetJSDev** [comment]
I think that's an extendscript issue.  You can test against the web demo: http://oss.sheetjs.com/js-xlsx/

I put together a small test file: [pct.xlsx](https://github.com/SheetJS/js-xlsx/files/893381/pct.xlsx) and in the web demo I see:
<img width="110" alt="pct" src="https://cloud.githubusercontent.com/assets/6070939/24661037/3bd83ae0-191f-11e7-83c5-7ef8063c6d36.png">

In any case, we're rewriting the formatting piece.  Stay tuned.

**Comment by firas3d** [comment]
Thank you,

I am interested in the value, not its (%) format > aim to read **-0.05**
(on positive 80%, it return value **0.8**, which is super usefull)

Is it possible ?
if not, i'll try to find the how the web demo is different than the extendscript.

**Comment by firas3d** [comment]
Looks like web demo returns the **formatted string**
Extendscript lib, returns correct positive **value**.

**Comment by SheetJSDev** [comment]
If you pass `{raw:true}` to the sheet_to_json function it should give you the number!

For example, with that pct.xlsx file from earlier:

```js
// normal behavior
XLSX.utils.sheet_to_json(wb.Sheets.Sheet1,{header:1})
[
  [ '0.8', '-0.05' ], 
  [ '80%', '-5%' ]
]


// if you add raw:true to the options, it will give you the number
XLSX.utils.sheet_to_json(wb.Sheets.Sheet1,{header:1,raw:true})
[
  [ 0.8, -0.05 ],
  [ 0.8, -0.05 ]
]
```

**Comment by firas3d** [comment]
SUPER, its working.

**Comment by reviewher** [comment]
#608 covers the general issue of the formatting in ExtendScript, so I think we're done here
