### ISSUE TITLE
Input language changing according to browser language

### ISSUE THREAD

**Issue by mesosteros** [SheetJS/js-xlsx#621]
We are using the library within an angularJS project but we can't seem to implement angular-translate so that we can change the input's language to match what the user has selected as his language.
How can we add the translate filter to the js-xls input (and change the layout for the button to be a bootstrap button for that matter)?
`<js-xls id="batchUpload" onread="readxls" onerror="errorxls" accept=".xls,.xlsx"></js-xls>`

**Comment by SheetJSDev** [comment]
I'm not familiar with angular-translate -- did you figure out a resolution?

**Comment by mesosteros** [comment]
Yes @SheetJSDev , had nothing to do with angular. It was the input itself. All I had to do was wrap it in a label, add the `{{ 'keytotranslate' | translate}}` inside it and finally put a display:none in the input itself so it could the appearance of a normal button and the translated text. ;)

**Comment by SheetJSDev** [comment]
@mesosteros if you can share some code we can add it to the wiki or change the angular demo :D
