### ISSUE TITLE
demo for the angular 4 

### ISSUE THREAD

**Issue by AnupojuVenkatNaveen** [SheetJS/js-xlsx#622]
Hello Team,

If you can provide the demo for the angular 4 it will be helpful for so many guys.

- this is one of the basic feature for so many sites to upload the data.
- Help the community with your demo

Hoping for the demo for Angular 4 soon :+1:

**Comment by AnupojuVenkatNaveen** [comment]
@ #

- [ ] [](url)

**Comment by maheshp212** [comment]
yes team,

I am also searching for this demo, please help us

**Comment by negberts** [comment]
There is an example here: https://github.com/florianschwanz/xlsx-drop-parse-demo

**Comment by SheetJSDev** [comment]
@negberts please add your link to https://github.com/SheetJS/js-xlsx/wiki/Examples with a short comment (e.g. what version of angular, what directive etc)

**Comment by negberts** [comment]
Done! It's not my example, but we used it as a base for our needs.

**Comment by bogdancar** [comment]
I added an example on exporting a xlsx file from an array of jsons on Angular2/4:

[https://github.com/bogdancar/xlsx-json-to-xlsx-demo-Angular2](url)

**Comment by SheetJSDev** [comment]
@AnupojuVenkatNaveen we added a proper example to the repo at [`demos/angular2`](https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2) -- it shows a simple component with a data-driven table.  A file input control is provided for data import and an export button is provided for data export.

@bogdancar we added your example to [the wiki!](https://github.com/SheetJS/js-xlsx/wiki/Examples)
