### ISSUE TITLE
Unexpected BrtBigName encountered

### ISSUE THREAD

**Issue by pgeeh** [SheetJS/js-xlsx#624]
Hi,

Ran into an issue where the record type 'BrtBigName' was encountered in 

`parse_ws_bin > ws_parse`

It appears that 'BrtBigName' is defined in XLSBRecordEnum and then is mentioned in a comment in 'write_ws_bin', but is not called out in any of the reader's methods. This throws the "Unexpected record" error in the ws_parse function.

It appears that 'BrtBigName' should be added to the list of case statements in the above method, even if it is not operated on yet.

**Comment by SheetJSDev** [comment]
@pgeeh the list in parse_ws_bin is based on records we've seen in the wild.  Clearly we haven't encountered a file with a BrtBigName record! Can you possibly share a file? (if you don't want to make it public, just email us at dev at sheetjs dot com).

We'll make a release later today and try to cover more cases that the spec permits but we haven't seen yet.

**Comment by pgeeh** [comment]
@SheetJSDev unfortunately, I cannot share my workbook at this time.

https://msdn.microsoft.com/en-us/dd926172

Based on the documentation above, BrtBigName could be in the sequence of a Worksheet. It appears that is already noted in a comment in the write function 'write_ws_bin'.
