### ISSUE TITLE
How do I read a Base64 Url encoded string to excel?

### ISSUE THREAD

**Issue by magician11** [SheetJS/js-xlsx#625]
I'm getting a xlsx attachment using the Gmail API https://developers.google.com/gmail/api/v1/reference/users/messages/attachments#resource

It returns it as a "The body data of a MIME message part as a base64url encoded string."

I'm not sure how to read it?

`XLSX.read(attachment, {type: 'base64'});`

I get

> TypeError: f.substr is not a function

How I do read this? Ultimately I want to convert that base64 format from Gmail to a JSON object.

Thanks.

**Comment by SheetJSDev** [comment]
@magician11 the linked doc suggests the encoding is base64url:

> The body data of a MIME message part as a base64url encoded string. 

Can you try:

```js
XLSX.read(attachment.replace(/\//g, "_").replace(/\+/g, "-"), {type:'base64'})
```

**Comment by magician11** [comment]
Ah ok. Convert it to Base64 from base64url.

I tried your code and got
> Error: Corrupted zip : can't find end of central directory

I think we also need to pad the end of the string with '=' a few times.

Something like

`var workbook = XLSX.read(attachment.replace(/\//g, "_").replace(/\+/g, "-").concat('=', (4 - ( attachment.length % 4 ))), {type:'base64'})`

?

Unfortunately I got the same error message as above.

I've been looking around for libraries for this. It seems it would be pretty common, but haven't found anything solid yet. Do you know of one?

**Comment by SheetJSDev** [comment]
@magician11 I haven't tested anything yet.  Can you try the other direction?

```js
XLSX.read(attachment.replace(/_/g, "/").replace(/-/g, "+"), {type:'base64'})
```

It's really confusing because there are multiple base64 standards https://en.wikipedia.org/wiki/Base64#Variants_summary_table

**Comment by magician11** [comment]
That worked!

Thank you :)

**Comment by SheetJSDev** [comment]
@magician11 added a note to the wiki: https://github.com/SheetJS/js-xlsx/wiki/Browser-Errors#gmail-api-typeerror-fsubstr-is-not-a-function feel free to embellish or add any other feedback

**Comment by Mujtaba4ahmed** [comment]
I have an XLSX file on the server which I am trying to download. When I hit that url with axios call, I get very diff, random data as response. How do I convert it to normal xlsx data? 

data : 
&��\���ad,��J������]bl��sM�E@�&ŵ�ͧ 0��
b�TC%̔Jba���4���8'��8oA��YR*i
ڨV�ߌ�,1/hK8�� K6�+�,�!��D���p�k�%���:v
��h'�T�)�!���c�*O�j|�G�Q\{����U�pb�n'(��!�R-W0@����W��0��u�I��;�YᲨ�ok>N0YЎ)����=��
Ç��W��/X�\�ZtZ�O�,ᴴ�YU��U����U���JI�]���'�M�b[���	i�Od

Data from response looks like this.

**Comment by louckousse** [comment]
I had this problem and what I did was:
```
const buf = Buffer.from(attachment, 'base64')
const sheet = xlsx.read(buf, { type: 'buffer' })
```
I get the same result that with the replace but I find it cleaner for reading.

**Comment by kantmani4** [comment]
I am new to react , I have a small problem.

I have a below method and "TestExcel.xlsx"  is in my root folder where my package.json file there
uploadFileAction() {
        const workbook = XLSX.readFile('TestExcel.xlsx', 'file');
        console.log(workbook)
      }

I am getting the below error.
default: throw new Error("Unrecognized type " + opts.type);.

In the document it says **node.js** only for file type:

type | expected input
-- | --
"base64" | string: Base64 encoding of the file
"binary" | string: binary string (byte n is data.charCodeAt(n))
"string" | string: JS string (characters interpreted as UTF8)
"buffer" | nodejs Buffer
"array" | array: array of 8-bit unsigned int (byte n is data[n])
"file" | string: path of file that will be read (nodejs only)

Can someone provide me the code how to do that via node.js or can some one help me how to convert my "TestExcel.xlsx" from my root folder to base64string. .

I have searched but there is no proper info provided.  can some one help me with that.

In react when I browse and upload the excel , how to convert the excel into object using
import XLSX from 'xlsx';  component.

Thanks

**Comment by SheetJSDev** [comment]
`readFile` is specific to nodejs (under the hood, it uses `fs.readFileSync`, something that has no equivalent in the browser).  If you are trying to read in react, place the file in the `public` folder (so that users can download it) and use the `fetch` api to download the file, then read the file with `FileReader` and call XLSX.read with `{type:"array"}`

**Comment by JosielFaleiros** [comment]
@kantmani4 
```
uploadFileAction() {
    const workbook = XLSX.read('TestExcel.xlsx', { type: 'file' });
    console.log(workbook)
}
```
