### ISSUE TITLE
Unreachable code 

### ISSUE THREAD

**Issue by negberts** [SheetJS/js-xlsx#628]
I'm trying to get my Angular2 rollup build working but it fails on the ReadShift function on the default case because of unreachable code:

```
switch(size) {
			case 1: oI = __readUInt8(this, this.l); this.l++; return oI;
			case 2: oI = (t === 'i' ? __readInt16LE : __readUInt16LE)(this, this.l); this.l += 2; return oI;
			case 4:
				if(t === 'i' || (this[this.l+3] & 0x80)===0) { oI = __readInt32LE(this, this.l); this.l += 4; return oI; }
				else { oR = __readUInt32LE(this, this.l); this.l += 4; return oR; } break;
			case 8: if(t === 'f') { oR = __double(this, this.l); this.l += 8; return oR; }
			/* falls through */
			case 16: o = __hexlify(this, this.l, size); break;
		}}
```

Because both the if and else of case 4 return a value, the break is never reached.

**Comment by SheetJSDev** [comment]
You are correct in deducing that the break is unreachable.  It exists because of a linter bug: https://github.com/jshint/jshint/issues/3108

If you submit a PR that removes it and similar unreachable break statements, we'll accept it.

**Comment by negberts** [comment]
I've created a gulp task to replace the break statement during build, so for now I'm fine. Removing the break statement would apparantly reintroduce the jshint bug.

**Comment by SheetJSDev** [comment]
It's pretty silly to add an unreachable statement just to satisfy the linter, and hopefully they will fix it at some point.  Are there any other weird cases you have to work around that we can fix?  As stated earlier, we'll accept a PR that removes that break statement.

**Comment by negberts** [comment]
No, that was the only one :) I will look into creating a PR. Have not done it on Github before :)

**Comment by negberts** [comment]
I guess someone was ahead of me. Thanks!

**Comment by SheetJSDev** [comment]
I remember that code from an older version of the module specifically because it was something that we had to add to work around jshint.  We made a push about a month ago to get flow to pass 100%, and it was at that time we worked around the issue: see commit 8cd9e81

We finally moved off jshint/jscs entirely, as eslint actually supports both types of checks in the same tool.
