### ISSUE TITLE
How to catch Unsupported file Errors?

### ISSUE THREAD

**Issue by gregpinero** [SheetJS/js-xlsx#631]
Is there a way I can catch the Unsupported file 105 error (or all unsupported file errors) so I can display a message to the user?

**Comment by gregpinero** [comment]
Nevermind, it's just normal error handling:
```

                try {
                    var workbook = XLSX.read(data, {type: 'binary'});
                }
                catch (err) {...
```

**Comment by SheetJSDev** [comment]
`105` is the letter `i` suggesting you may have a CSV or TXT file.  Based on the error message I'm guessing you are using an older version (newer versions peek at the first 4 bytes so you get an error message like `Unsupported file 115|104|105|112` ) We've added some plaintext format processing so try using the latest version.
