### ISSUE TITLE
Read data vertically instead of horizontally

### ISSUE THREAD

**Issue by newkillerbeast2017** [SheetJS/js-xlsx#633]
I am converting a workbook data into json object using the following code:

```
var o = { };
workbook.SheetNames.forEach(function(name) {
    o[name] = XLSX.utils.sheet_to_json(workbook.Sheets[name]);
});
```

Now, the data is read horizontally instead of vertically. For explanation, below is my json object
```
    { 
        'testsheet1': [{
             'test1': 'testvalue1',
             'test2': 'testvalue2'
         }],
        'testsheet2': [{
             'test3': 'testvalue3',
             'test4': 'testvalue4'
         }]
    }
```

Here, `test1` is taken from A1. `testvalue1` is taken from A2. But I would like the value of `testvalue1` to be taken from B1 instead of A2. Is this possible?

**Comment by newkillerbeast2017** [comment]
Wrong issue from my end. Found the solution, closing the issue.

**Comment by medha-patki** [comment]
what is the solution?
