### ISSUE TITLE
Creating formula or macros in excel

### ISSUE THREAD

**Issue by hawasthi02** [SheetJS/js-xlsx#634]
I have an array of 6 objects in json.
/* original data */
var data = [{ "monoTotalMonthly" : 490,
    "colorTotalMonthly" : 0,
    "lifeTotalMonthly" : 490,
    "colorA3Monthly" : 0,
    "monoA3Monthly" : 0,
    "copyTotalMonthly" : 0,},{ "monoTotalMonthly" : 490,
    "colorTotalMonthly" : 0,
    "lifeTotalMonthly" : 490,
    "colorA3Monthly" : 0,
    "monoA3Monthly" : 0,
    "copyTotalMonthly" : 0,},{ "monoTotalMonthly" : 490,
    "colorTotalMonthly" : 0,
    "lifeTotalMonthly" : 490,
    "colorA3Monthly" : 0,
    "monoA3Monthly" : 0,
    "copyTotalMonthly" : 0,}{ "monoTotalMonthly" : 490,
    "colorTotalMonthly" : 0,
    "lifeTotalMonthly" : 490,
    "colorA3Monthly" : 0,
    "monoA3Monthly" : 0,
    "copyTotalMonthly" : 0,}{ "monoTotalMonthly" : 490,
    "colorTotalMonthly" : 0,
    "lifeTotalMonthly" : 490,
    "colorA3Monthly" : 0,
    "monoA3Monthly" : 0,
    "copyTotalMonthly" : 0,}{ "monoTotalMonthly" : 490,
    "colorTotalMonthly" : 0,
    "lifeTotalMonthly" : 490,
    "colorA3Monthly" : 0,
    "monoA3Monthly" : 0,
    "copyTotalMonthly" : 0,}]

While converting it to excel the 3rd column contains the sum of first two fields , 6th column contains the sum of 4th and 5th column in excel and 9th column contains the sum of 7th and 8th column.
How I can make the formula for it such that 3rd 6th and 9th field gets auto populated in excel for every row.

**Comment by SheetJSDev** [comment]
You can manually build up the worksheet:

```js
var worksheet = {};
var range = {s:{r:0,c:0},e:{r:0,c:8}};
data.forEach(function(row, n) {
    range.e.r = n;
    /* data cells, I just took the order from your example
       but you can change the `row["..."]` part to reorder the cols */
    worksheet['A' + (n+1)] = {t:'n', v:row["monoTotalMonthly"]};
    worksheet['B' + (n+1)] = {t:'n', v:row["colorTotalMonthly"]};
    worksheet['D' + (n+1)] = {t:'n', v:row["lifeTotalMonthly"]};
    worksheet['E' + (n+1)] = {t:'n', v:row["colorA3Monthly"]};
    worksheet['G' + (n+1)] = {t:'n', v:row["monoA3Monthly"]};
    worksheet['H' + (n+1)] = {t:'n', v:row["copyTotalMonthly"]};
    /* column C is going to be the sum from A and B */
    worksheet['C' + (n+1)] = {t:'n', v:worksheet['A' + (n+1)].v + worksheet['B' + (n+1)].v, f:'A' + (n+1)+'+'+'B'+(n+1)};
    /* column F is going to be the sum from D and E */
    worksheet['F' + (n+1)] = {t:'n', v:worksheet['D' + (n+1)].v + worksheet['E' + (n+1)].v, f:'D' + (n+1)+'+'+'E'+(n+1)};
    /* column I is going to be the sum from G and H */
    worksheet['I' + (n+1)] = {t:'n', v:worksheet['G' + (n+1)].v + worksheet['H' + (n+1)].v, f:'G' + (n+1)+'+'+'H'+(n+1)};
});
worksheet['!ref'] = XLSX.utils.encode_range(range);
```

And if you want to make a full file:

```js
var wb = {SheetNames:["Sheet1"], Sheets:{Sheet1:worksheet}};
XLSX.writeFile(wb, "test634.xlsx");
```

I just tested with https://runkit.com/sheetjs/58f5c48e958121001283c8fe and the result is 

[output634.xlsx](https://github.com/SheetJS/js-xlsx/files/932004/output634.xlsx)

**Comment by hawasthi02** [comment]
Its Great!!!!!!!!!
Many Thanks....
willl Come back to you for more Queries...

**Comment by hawasthi02** [comment]
Formula is not getting applied in the xlsx sheet but the values are getting added
the commands I used is
   cell = {t:'n' , v: workSheet['A' + (row+1)].v + workSheet['B' + (row+1)].v , f:'A' + (row+1)+'+'+'B'+(row+1)};
   cellRef = xlsx.utils.encode_cell({
                    c: column,
                    r: row
                });
           workSheet[cellRef] = cell;
![image](https://cloud.githubusercontent.com/assets/20221255/25212971/502ba0fc-25ab-11e7-9983-b07e9c382076.png)

**Comment by SheetJSDev** [comment]
@hawasthi02 are you sure you are writing to cell C2? check what `c` and `r` are.  Add the line `console.log(c,r,cellRef)` and confirm that you see `2,1,"C2"`.

**Comment by hawasthi02** [comment]
@SheetJSDev 
I printed console.log(allFields[column],column,row,cellRef);
and the output is 
 TotalCost 2 1 C2

**Comment by SheetJSDev** [comment]
@hawasthi02 can you share the output XLSX file?  From the bit of code you sent, it should have written both the value and the formula.

**Comment by hawasthi02** [comment]
[test.xlsx](https://github.com/SheetJS/js-xlsx/files/940171/test.xlsx)
Please find the file here.

**Comment by SheetJSDev** [comment]
Thanks for sharing, can confirm the file is missing formula.  Just before writing the file, can you put `console.log(XLSX.version)` and check what version is in use?  IT should say 0.9.11 if you are on the latest version

**Comment by hawasthi02** [comment]
Really Thanks,I was stucked here since yesterday.
It was a version issue I was on 0.8.8
![image](https://cloud.githubusercontent.com/assets/20221255/25213745/3e38cb68-25b0-11e7-8ffd-3485c7c70dc4.png)
