### ISSUE TITLE
Error when parsing CSV file 0.9.11

### ISSUE THREAD

**Issue by famu1hundred** [SheetJS/js-xlsx#636]
This lib is awesome. It works perfectly for xls and xlsx. I upgraded to 0.9.11 and I thought I would be able to read CSV files. However, I am receiving the following error in the console:

The same file works in the In-Browser Demo but not in my code but I don't see a difference

Uncaught Error: Corrupted zip : can't find end of central directory
    at ZipEntries.readEndOfCentral (jzip.js:2264)
    at ZipEntries.load (jzip.js:2326)
    at ZipEntries (jzip.js:2150)
    at JSZip.module.exports [as load] (jzip.js:567)
    at JSZip (jzip.js:514)
    at read_zip (xlsx.js:14064)
    at Object.readSync [as read] (xlsx.js:14097)

**Comment by SheetJSDev** [comment]
If the file works in the demo but not in your code, there's most likely a problem in your integration code.

1) confirm you are using the right version: `console.log(XLSX.version)` just before the part that reads in the file.

2) just before reading the file, try to console.log the data just before calling `read`, and confirm that it looks like the original file

if the content is the same and you are using the right version, share the code snippet that actually reads the file (the part including the XLSX.read call).  But a glance at the line numbers suggests that you may be using an older version -- readSync is defined in [line 16114](https://github.com/SheetJS/js-xlsx/blob/v0.9.11/xlsx.js#L16114) in version 0.9.11

**Comment by famu1hundred** [comment]
Thanks for the quick reply!

So I confirmed with XLSX.version that the version is still 0.8.7. However, I also confirmed that there are 2 xlsx.js files in separate libs in bower_components. One is located in js-xlsx (0.9.11) and the other is in xlsx-js (0.8.7). I tried removing them both and reinstalling with bower, but they both came back. Is this right?

**Comment by SheetJSDev** [comment]
Our [bower.json](https://github.com/SheetJS/js-xlsx/blob/master/bower.json#L2) is configured to publish as `js-xlsx`.  The [manifest page](https://libraries.io/bower/js-xlsx) appears to be correct. 
 `xlsx-js` points to a separate fork.

It's likely that you either included both names in your bower.json, or a dependency pulls in the other version.  I would check your local bower.json first.

The correct name is noted in the README: https://github.com/sheetjs/js-xlsx#installation

**Comment by famu1hundred** [comment]
The xlsx-js lib (0.8.7) gets installed due to another lib "tableexport.js" that has a dependency on xlsx-js (^0.8.7) and my bower.json installs js-xlsx 0.9.11, thus making two separate instead of updating the older version.
