### ISSUE TITLE
Double Headers Parsing 

### ISSUE THREAD

**Issue by r1z1a** [SheetJS/js-xlsx#637]
Not sure if this is right place to post this. I have question. 
Is there a way to parse a .xlsx file that has a set of 2 headers where the row 1 is header 1 (with merged sells) and row 2 is standard header per column?
As an example:
| Personal info |              Contacts           |                          Interests                             |
| Name | Age   | Email | Phone | Address | Football | Basketball | Hockey | Swimming |
| value10 | value11 | value12 | value13 | value14 | value15 | value16 | value17 | value18 |
| value20 | value21 | value22 | value23 | value24 | value25 | value26 | value27 | value28 |

The way it parses now is {"Personal info":"Name","Contacts":"Email", "Interests":"Football"},
{"Personal info":"value10","Contacts":"value12", "Interests":"value15"},
{"Personal info":"value20","Contacts":"value22", "Interests":"value 25"}

Is there a way to get something like this by default or some sort of work around to get it, since the first header is something that is controlling how data is later used, and second header there for data, id that makes sense.
 {
       "Personal info": {
                 "Name": "value10",
                 "Age": "value11"
                  },
        "Contacts": {
                 "Email": "value12",
                 "Phone": "value13",
                 "Address": "value14"
                },
          "Interests" : {
                   "Football":"value15"
              and so on 
                }
    }

**Comment by SheetJSDev** [comment]
The library functions can't do that directly, but if you pass the option `header:1` to `sheet_to_json` you'll get a raw array of arrays that you can work with.  For your example, `var output = XLSX.utils.sheet_to_json(worksheet, {header:1})` would return:

```js
[
  ["Personal info", , "Contacts", , , "Interests"],
  ["Name", "Age", "Email", "Phone", "Address", "Football", "Basketball", "Hockey", "Swimming"],
  ["value10", "value11", "value12", "value13", "value14", "value15", "value16", "value17", "value18"],
  ["value20", "value21", "value22", "value23", "value24", "value25", "value26", "value27", "value28"]
]
```

You can loop through the data rows (in this case, `output.slice(2)`) and convert each row to JS object that you want.

The option is explained in https://github.com/sheetjs/js-xlsx/#json.
