### ISSUE TITLE
[Help me] XLSX + WebWorker not working

### ISSUE THREAD

**Issue by seunggabi** [SheetJS/js-xlsx#638]
Hello @SheetJSDev !
I am a user of JS-XLSX

There was a problem when working with web worker..
error: 
```javascript
Main.js:80 Uncaught DOMException: Failed to execute 'postMessage' on 'Worker': function parse_xlscfb(cfb, options) {
  if(!options) options = {};
  fix_read_opts(options);
  reset_cp();
  va...<omitted>... } could not be cloned.
```

Bug code
```javascript
var w = new Worker('/excel-merge-tool-webworker.js')
w.postMessage({
	XLSX: XLSX,
})
```
I want to copy XLSX object!!!
What should I do?

**Comment by SheetJSDev** [comment]
You are copying the whole module, did you mean to send back a workbook?

The included worker script parses the workbook and calls `JSON.stringify` on the result, so it sends a string back:

https://github.com/SheetJS/js-xlsx/blob/master/xlsxworker.js#L11-L13

This is ultimately parsed back into a workbook object in the main thread:

https://github.com/SheetJS/js-xlsx/blob/master/index.html#L114

In the [demo](http://oss.sheetjs.com/js-xlsx/) data is sent to the web worker and the worker parses the workbook.  It stringifies the object and sends back.  The main browser thread receives the JSON string, parses it, then converts it to the specified format.

**Comment by seunggabi** [comment]
@SheetJSDev 
Thank you! :)

**Comment by calebeaires** [comment]
@SheetJSDev I have tried to do it in a Angular 6 app, but I had no success. I have seen the demo and tried to implement an similar logic. May you help us with an example?
