### ISSUE TITLE
Examples and documentation improvements

### ISSUE THREAD

**Issue by nukulb** [SheetJS/js-xlsx#64]
I am looking for an example on writing a JSON into xlxs file.

The read works great but I unable to find a working example. Can someone help me with a link or simply point me in the right direction.

**Comment by blakek** [comment]
It would be great if the documentation listed accepted "type" values for the read() function (and what those options mean).  For example: buffer, base64, file, binary, etc.

Are pull requests being looked at?  If so, I'd be up for helping out on this.

**Comment by SheetJSDev** [comment]
We're slowly improving the documentation.  The underlying structure is stabilizing, and for most supported features all of the parsers should generate the same fields consistent with the README.

At the moment we're trying to go feature by feature and hammer out documentation while we ensure the main supported parsers (XLS/XLSX/XLSB/SpreadsheetML) produce similar parsed objects.  If there is anything unclear in the README please let us know where we can improve.

@blakek if you are interested in contributing documentation, we'd gladly accept a PR!  Documentation is the one area that doesn't involve hours of testing :D If you have any demos or projects, please add a link to the wiki page so others can find it!

**Comment by SheetJSDev** [comment]
We set up a gitbook integration: https://sheetjs.gitbooks.io/docs/
