### ISSUE TITLE
Exporting Date-Times in Iso Format 

### ISSUE THREAD

**Issue by SCullman** [SheetJS/js-xlsx#640]
I want to export date/time values to JSON formatted as ISO 8601 values

My current script:

```javascript
const XLSX = require('xlsx');
...
const file = XLSX.readFile(path,{cellDates:true, cellNF:false});
for (sheet in file.Sheets){
     //remove prerendered values, otherwise dateNF is ignored
     for (cellref in sheet){
         const c = sheet[cellref];
         if(c.t==="d"){
             delete c.w;
             delete c.z; 
         }
    }
   const format = "YYYY-MM-DD hh:mm:ss";
   //const format = "YYYY-MM-DDThh:mm:ss"; throws exception as it doesn't recognize T
   const data = XLSX.utils.sheet_to_json(sheet, {header: 1, dateNF:format});
   .....
}
```
The cells itself already contain the correct datetime inside the v(alue) attribute.

I suggest an option like
XLSX.utils.sheet_to_json(sheet, {header: 1, ExportDatesAsISO:true});

Test data:
[datum.xlsx](https://github.com/SheetJS/js-xlsx/files/947214/datum.xlsx)

**Comment by SCullman** [comment]
This script would work for me but feels just wrong:

```javascript
const XLSX = require('xlsx');
...
const file = XLSX.readFile(path,{cellDates:true});
for (sheet in file.Sheets){
     for (cellref in sheet){
         const c = sheet[cellref];
         if(c.t==="d"){
             c.w = c.v;
         }
    }
   const data = XLSX.utils.sheet_to_json(sheet, {header: 1});
   .....
}
```

**Comment by SheetJSDev** [comment]
Would it make more sense to add an option that suppresses the formatted text for all cells? something like `cellText` which would not generate the `.w` text if it is set to `false`?

**Comment by SCullman** [comment]
This would help; the parsing through the cells could be avoided.
But even then it is not possible to return the date in ISO format, as YYYY-MM-DD**T**hh:mm:ss is not accepted as _dateNF_.

**Comment by SheetJSDev** [comment]
@SCullman so the first part was pushed (`cellText:false` will not generate the format).

For your specific format, the correct code is `YYYY-MM-DD"T"hh:mm:ss`.  The double-quotes are necessary to indicate that T is a literal T and not a format element.  If you try to enter `YYYY-MM-DDThh:mm:ss` and save the file, the actual format is encoded in the xml as

```xml
yyyy\-mm\-dd&quot;T&quot;hh:mm:ss
```

**Comment by SCullman** [comment]
Thank you, works perfect!

**Comment by vinodjoshi11** [comment]
i am facing date time issue 
I have try this code xlsx js 
 let wb = XLSX.utils.book_new();
        let ws  = XLSX.ws = XLSX.utils.json_to_sheet(exportXLSXData, {dateNF: 'mmm dd, yyyy hh:mm', cellDates: true });
        /*var ws = XLSX.utils.json_to_sheet(exportdata, {header: ["string","string", "number","date","string","string","string","string","string","string","string","string",], cellDates: true});	 */
        // Headers
        ws['A1'].v = "Issue Key";
        ws['B1'].v = "Summary";
        ws['C1'].v = "Time Spent (Hours)";
        ws['D1'].v = "Date";
        ws['E1'].v = "Work Description";
        ws['F1'].v = "Task Type";
        ws['G1'].v = "User";
        ws['H1'].v = "Account";
        ws['I1'].v = "Parent Issue Key";
        ws['J1'].v = "Issue Type";
        ws['K1'].v = "Issue Status";
        ws['L1'].v = "Issue Priority";
        ws['M1'].v = "Issue Reporter";
        ws['N1'].v = "Project Key";
        ws['O1'].v = "Project Name";
        ws['P1'].v = "Component";
        ws['Q1'].v = "All Components";
        ws['R1'].v = "Fix Version";
        ws['S1'].v = "All Fix versions";
        for (var i = 0; i < exportXLSXData.length; ++i) {
            ws[`D${i + 2}`].z = 'mmm dd, yyyy hh:mm';
            ws[`D${i + 2}`].t= 'd';
        }
        ws['!cols'] = wscolls;
        ws['!rows'] = allRows;console.log(ws)
        XLSX.utils.book_append_sheet(wb, ws, sheetNames);
        XLSX.writeFile(wb,fileName + EXCEL_EXTENSION);
I have add utc date 
"Mar 10, 2020 08:00"


the output excels file date i have found wrong? 
Mar 10, 2020 07:59
--
