### ISSUE TITLE
export xls with a image

### ISSUE THREAD

**Issue by oreillyj1** [SheetJS/js-xlsx#642]
Hi does this library allow me to export a xls with a image somewhere on the sheet? if there are any jsfiddles on the web showing this it would also be great..
thanks

**Comment by oreillyj1** [comment]
hi Ive a query - does js-xlsx allow images to be exported to a xls file?

**Comment by SheetJSDev** [comment]
Not currently.  A partial implementation for XLSX image export was submitted as a [pull request](https://github.com/SheetJS/js-xlsx/pull/509/) but there are more details to work out.

**Comment by oreillyj1** [comment]
ok thanks, would there be a jsfiddle somewhere of the pull request do you know?

**Comment by xSirrioNx** [comment]
@oreillyj1 , i just make a fork, where try to implement styles and images from another forks to current version in main project (0.10.2)
https://github.com/xSirrioNx/js-xlsx

**Comment by oreillyj1** [comment]
hi xSirrioNx,
thanks for your help, im from a winform background  [so apologies] but how would I take your folk and apply it into one of the sheetJs examples (ive copied to the jsfiddle) - [https://plnkr.co/edit/OwwK00?p=preview](url)

like how do you add 
`  var data = "iVBORw0KGgoAA....`
`ws["!images"] = [{...`
into a existing sheetJs example ?...would you have capacity to outline?

**Comment by xSirrioNx** [comment]
@oreillyj1, i make a JS fiddle how i use it in my project: https://jsfiddle.net/1g24vowu/1/

**Comment by oreillyj1** [comment]
great thanks for that looks like a nice approach

**Comment by HeroSony** [comment]
@xSirrioNx , your demo was great. Anyway do u know how can your code export with multiple sheets?

**Comment by xSirrioNx** [comment]
@HeroSony 
Hi!
Thank you =) I just update xlsx.js in my fork and update fiddle: https://jsfiddle.net/1g24vowu/17/
Where are two sheets and two images on each.

**Comment by HeroSony** [comment]
Hi @xSirrioNx , Thank so much for your help and it really useful.

But now I've got another problem with rowspan and colspan. it's not working while export to excel.
Do you have any ideas?

**Comment by xSirrioNx** [comment]
@HeroSony , what's wrong?
Update Fiddle with merges: https://jsfiddle.net/1g24vowu/18/

**Comment by HeroSony** [comment]
@xSirrioNx , Greate.... Thank you very much... :+1:

**Comment by Aymkdn** [comment]
@HeroSony I think you should open an issue on the fork of @xSirrioNx instead of using this thread....

**Comment by bys-wallance-zhang** [comment]
Hi@xSirrioNx, 
I find a issue in  https://jsfiddle.net/1g24vowu/1/, insert image can not work with add cell.l = {Target:""}, the export xlsx will remove image.

**Comment by bys-wallance-zhang** [comment]
@xSirrioNx,
Hi xSirrioNx,，I find 2 issues, one is the image only be inserted 1st sheet, if add the 2nd the image not be present in export file;
another issue is when heperlink and image add the same sheet, the image will be removed from the export file

**Comment by idr17** [comment]
yes @xSirrioNx , I would be very grateful if u reupload into jsfiddle.

**Comment by subrat7** [comment]
Can anyone send the snippet for this features ,the link provided above isn't working ,please provide the working link.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by sachinvar** [comment]
is there any plan to make it available as open source?

**Comment by sachinvar** [comment]
Is there any other react node modules, which is providing support for exporting image in generated excel?

**Comment by nglpx1** [comment]
Hi, is it now possible export in xlsx an html table with an associated image?
Thanks.

**Comment by balihoo-svarma** [comment]
> Hi, is it now possible export in xlsx an html table with an associated image?
> Thanks.

No luck so far

**Comment by rifaldyaristya** [comment]
> @HeroSony Hi! Thank you =) I just update xlsx.js in my fork and update fiddle: https://jsfiddle.net/1g24vowu/17/ Where are two sheets and two images on each.

Hey can you reopen this. This link doesn't exist anymore @xSirrioNx

**Comment by ka11den** [comment]
> > @HeroSony Hi! Thank you =) I just update xlsx.js in my fork and update fiddle: https://jsfiddle.net/1g24vowu/17/ Where are two sheets and two images on each.
> 
> Hey can you reopen this? This link doesn't exist anymore @xSirrioNx . Thanks in advance!

fill it up again please
