### ISSUE TITLE
Tests failing because ENOENT ./test_files/apachepoi_SimpleWithComments.xls

### ISSUE THREAD

**Issue by wolfgang42** [SheetJS/js-xlsx#654]
I've cloned `master` and installed the NPM packages. When I run `make test` I get the following failure:

```
  4705 passing (1m)
  5 pending
  1 failing

  1) corner cases CFB:
     Error: ENOENT: no such file or directory, open './test_files/apachepoi_SimpleWithComments.xls'
      at Error (native)
      at Object.fs.openSync (fs.js:641:18)
      at Object.fs.readFileSync (fs.js:509:33)
      at readFileSync (xlsx.js:1306:18)
      at Object.readSync [as read] (xlsx.js:1311:23)
      at Context.<anonymous> (test.js:1782:19)



Makefile:95: recipe for target 'test' failed
make: *** [test] Error 1
```

I'm not sure how to diagnose this issue: the file isn't there, but I can't figure out how it's supposed to have gotten there either.

**Comment by SheetJSDev** [comment]
@wolfgang42 that test is a holdover from how XLS used to be structured.  It can be safely removed.  Give me one minute, we'll remove that along with a few other test changes.

For testing: on OSX/Linux you need to run `make init` to pull in the test files.  In windows you need to download the last release from https://github.com/SheetJS/test_files/releases ,

**Comment by wolfgang42** [comment]
@SheetJSDev Where does `make init` come in? It looks like it's trying to use SVN to get test data from somewhere (which doesn't work on my system because I don't have Subversion installed), but I ran `npm run pretest` and after your update `make test` is working fine.

**Comment by SheetJSDev** [comment]
@wolfgang42 don't worry about it :) `make init` pulls a bunch of external test files for a larger test that we run before cutting releases.  If the base tests work with `npm run pretest` we'll update the docs

**Comment by krutikpatel** [comment]
i see this issue just with basic .readFile function usage
