### ISSUE TITLE
Change header´s title when using JSON_to_XLSX

### ISSUE THREAD

**Issue by martinnov92** [SheetJS/js-xlsx#659]
Hello,

I would like to know, if there is any way how to change header´s title when using `json_to_xlsx` function. Now I am gettings object´s keys and I would like to change it to something more readable.

Thank you very much.

**Comment by SheetJSDev** [comment]
There's no `json_to_xlsx` function, you probably mean `json_to_sheet`.

That being said, the easiest way is to change the worksheet after the fact.  We'll start from a simple example:

```js
> var data = [{name:"Sheet", age: 12}, {name:"JS", age: 24}]
> var ws = XLSX.utils.json_to_sheet();
> ws
{ A2: { t: 's', v: 'Sheet' },
  B2: { t: 'n', v: 12 },
  A3: { t: 's', v: 'JS' },
  B3: { t: 'n', v: 24 },
  A1: { t: 's', v: 'name' },
  B1: { t: 's', v: 'age' },
  '!ref': 'A1:B3' }
```

The headers are automatically inserted in the first row (the A1/B1 from above).  You can directly change the values.  Let's say "name" -> "Name":

```js
ws.A1.s = "Name";
```

If you want to loop through every header and make them uppercase:

```js
var range = XLSX.utils.decode_range(ws['!ref']);
for(var C = range.s.r; C <= range.e.r; ++C) {
  var address = XLSX.utils.encode_col(C) + "1"; // <-- first row, column number C
  if(!ws[address]) continue;
  ws[address].v = ws[address].v.toUpperCase();
}
```

**Comment by samuelkavin** [comment]
Hi @martinnov92,

I'm new to js-xlsx. Can u share some sample code how did you generate the json to xlsx format? 
This will be really helpful for me.

This is sample data from me
` var data = [  
   {  
      "agentNo":"324234",
      "subName":"30, Jul 2013 09:24 AM"
   },
   {  
      "agentNo":"444443",
      "subName":"30, Jul 2013 09:24 AM"
   }
];`
` var wb = XLSX.utils.json_to_sheet(ge);`

**Comment by martinnov92** [comment]
Hello @samuelkavin ,

I am new to js-xlsx as well :D But I will try my best and help you.

The first thing you have to do is set writing options for xlsx:
`const wopts = { bookType: 'xlsx', bookSST: false, type: 'binary' };`

Then you create the worksheet like this:
`const ws = xlsx.utils.json_to_sheet(data);`

Then you create the workbook:
`const wb = { SheetNames: ['Export'], Sheets: {}, Props: {} };`

Next you put data in the sheet:
`wb.Sheets['Export'] = ws;`

And the final step is from documentation:
`

        // make a file
        var wbout = xlsx.write(wb, wopts);

        function sheetToArrayBuffer(s) {
            var buf = new ArrayBuffer(s.length);
            var view = new Uint8Array(buf);
            for (var i = 0; i != s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
            return buf;
        }

        // the saveAs call downloads a file on the local machine
        saveAs(new Blob([sheetToArrayBuffer(wbout)], { type: "application/octet-stream" }), "Export.xlsx");
`

I hope this will be somehow helpful.

**Comment by samuelkavin** [comment]
Hi @martinnov92, thank you for quick respone. 
I got `Uncaught ReferenceError: xlsx is not defined`

Here is my js
`function export_json_to_excel() {
  var wopts = {
    bookType: 'xlsx',
    bookSST: false,
    type: 'binary'
  };

  var ws = xlsx.utils.json_to_sheet(data);

  var wb = {
    SheetNames: ['Export'],
    Sheets: {},
    Props: {}
  };

  wb.Sheets['Export'] = ws;

  // make a file
  var wbout = xlsx.write(wb, wopts);

  function sheetToArrayBuffer(s) {
    var buf = new ArrayBuffer(s.length);
    var view = new Uint8Array(buf);
    for (var i = 0; i != s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
    return buf;
  }

  // the saveAs call downloads a file on the local machine
  saveAs(new Blob([sheetToArrayBuffer(wbout)], {
    type: "application/octet-stream"
  }), "Export.xlsx");


  return wbout;

}
`

HTML:
`<p id="xportxlsx" class="xport">
                        <input type="submit" value="Export to XLSX!" onclick="export_table_to_excel();">
                    </p>`

Json:
`var data = [ { "agentNo":"324234", "subName":"30, Jul 2013 09:24 AM" }, { "agentNo":"444443", "subName":"30, Jul 2013 09:24 AM" } ];
`

**Comment by martinnov92** [comment]
@samuelkavin how do you import this library? With <script> tag? then you might try to use window.xlsx..., I am using this in React `import xlsx from 'xlsx'`

**Comment by samuelkavin** [comment]
@martinnov92 oh ok. I'm using <script> tag. After add

`var ws = window.xlsx.utils.json_to_sheet(data);`

now getting:
> Cannot read property 'utils' of undefined

I was trying this since yesterday

**Comment by samuelkavin** [comment]
@martinnov92 Fixed it 👯‍♂️ 

Just replace `xlsx to XLSX`

Thank you man!!
I really appreciate you help :)

**Comment by martinnov92** [comment]
@samuelkavin You are welcome, I am happy I helped :)

**Comment by artaniszeratul** [comment]
No worries @martinnov92 .

Hi @SheetJSDev , 

Please allow me to ask you a question.

I wanted to make the headers of my excel data to be in bold fonts and with filters.
I am currently stuck on looking for possible ways to do this.

I would appreciate it so much if you can point me into something.
Or better yet, if you can show me an example.

Cheers,
Artanis

**Comment by jdhines** [comment]
I don't think that kind of formatting is possible, but to address your earlier question, the way I did it, since I also needed to change the order of the columns sometimes (although I know you can use the `headers` prop to do it), was to just map the keys of the JSON object to new keys:

```
newJson = oldJson.map(rec => {
  return {
    'Last Name': rec.lastName,
    'First Name': rec.firstName,
    ...
  }
}
```

**Comment by cmfc31** [comment]
> ```js
> ws.A1.s = "Name";
> ```
Shouldn't be .v?
```js
ws.A1.v = "Name"
```

**Comment by SheetJSDev** [comment]
Thanks @cmfc31 corrected the snippet

**Comment by soanvig** [comment]
@SheetJSDev and it should be

```js
range.e.c
```

and

``js
range.s.c
```

if we want to iterate columns

**Comment by christiaanwesterbeek** [comment]
I followed the same strategy as @jdhines . I think it's the simplest way to go since it doesn't require any knowledge of the SheetJS api. Just plain modern javascript altering the data before you pass it `json_to_sheet`.

There's a complete example here: https://github.com/mbrn/material-table/issues/1534#issuecomment-601603029

**Comment by thomascayne** [comment]
> I don't think that kind of formatting is possible, but to address your earlier question, the way I did it, since I also needed to change the order of the columns sometimes (although I know you can use the `headers` prop to do it), was to just map the keys of the JSON object to new keys:
> 
> ```
> newJson = oldJson.map(rec => {
>   return {
>     'Last Name': rec.lastName,
>     'First Name': rec.firstName,
>     ...
>   }
> }
> ```

This is fabulous because it automatically omits unwanted data and can be used application wide. Most useful. Thank you @jdhines

**Comment by SheetJSDev** [comment]
Thanks @soanvig fixed the snippet

@jdhines love the simplicity 👍 For complete control, we normally recommend an array of arrays, but your approach is definitely more straightforward

@artaniszeratul bold and other style formatting is supported in our [Pro builds](https://sheetjs.com/pro)

**Comment by mitul327** [comment]
Hello,
Thanks for help in advance,

Now, we have multiple tagArrays
1. [id:'someid', error: {code:0, success: true}, data: [[1604395417575, 608, 3], [1604395421453, 279, 3]].......50-69K []]
2. [id:'someid 2', error: {code:0, success: true}, data: [[1604395417575, 608, 3], [1604395421453, 279, 3]].......50-69K []]

Eg Note: 1604395417575 - timestamp, 608 - value, 3- quality

![image](https://user-images.githubusercontent.com/10165068/114265742-296b8a80-9a10-11eb-9460-eaaa4436f676.png)

I want to show in Excel sheet as in the below format

![image](https://user-images.githubusercontent.com/10165068/114265940-350b8100-9a11-11eb-9970-22f607ed5321.png)
