### ISSUE TITLE
Can not change scope variable in AngularJS

### ISSUE THREAD

**Issue by huchenhai** [SheetJS/js-xlsx#660]
`$scope.read = function (workbook) {
           var first_sheet_name = workbook.SheetNames[0];
           var worksheet = workbook.Sheets[first_sheet_name];
            $scope.data=[{name:worksheet['B2'].v,y:worksheet['B6'].v*100},{name:worksheet['C2'].v,y:worksheet['C6'].v*100}];
       }`

**Comment by huchenhai** [comment]
I just fixed this issue by adding $scope.apply inside read function, and put everything inside apply function. Then angular will realize what happen to $scope

**Comment by huchenhai** [comment]
`$scope.read = function (workbook) {
           $scope.$apply(function(){
               var first_sheet_name = workbook.SheetNames[0];
               var worksheet = workbook.Sheets[first_sheet_name];
               $scope.data=[{name:worksheet['B2'].v,y:worksheet['B6'].v*100},
                   {name:worksheet['C2'].v,y:worksheet['C6'].v*100}];
           });
       }`

**Comment by SheetJSDev** [comment]
@huchenhai we will revisit the angular bindings soon.  FYI if you wrap multi-line code segments in triple backticks, it will preserve the newlines.  And if you add js GH will automatically provide JS syntax highlighting.
