### ISSUE TITLE
Newbie to js-xlsx - JSON to xlsx conversion with using angular

### ISSUE THREAD

**Issue by samuelkavin** [SheetJS/js-xlsx#666]
Anyone can guide me how to convert json to xlsx with using angular? 

Here is sample json format:
`[  
   {  
      "agentNo":"324234",
      "subName":"30, Jul 2013 09:24 AM",
      "Location":"Singapore",
      "memberName":42,
      "certNo": "2342234",
      "Gender":"Male",
      "dob":"1 may 1987"
   },
   {  
      "agentNo":"444443",
      "subName":"30, Jul 2013 09:24 AM",
      "Location":"Malaysia",
      "memberName":42,
      "certNo": "2342234",
      "Gender":"Male",
      "dob":"1 may 1987"
   },
   {  
      "agentNo":"2342234",
      "subName":"30, Jul 2013 09:24 AM",
      "Location":"India",
      "memberName":42,
      "certNo": "2342234",
      "Gender":"Male",
      "dob":"1 may 1987"
   }
]`

Here is xlsx sample that need to be generated:
<img width="1003" alt="screen shot 2017-05-24 at 6 16 18 pm" src="https://cloud.githubusercontent.com/assets/5300968/26399488/b2cc8ab8-40af-11e7-9302-d710cbd2cce0.png">

Thanks in advance

**Comment by jomel** [comment]
@samuelkavin  see my answer to your comment on #610

**Comment by samuelkavin** [comment]
@jomel, thank you for response. All done. Now, I stuck with settting up the title of the excel file which is Member Listing, Company Name and Report Date on A1, A2 and A3 cell. Any idea?

**Comment by samuelkavin** [comment]
@martinnov92, is it possible insert 3 row before header? something like this:
<img width="1003" alt="screen shot 2017-05-24 at 6 16 18 pm" src="https://cloud.githubusercontent.com/assets/5300968/26525313/caefd116-4386-11e7-9d55-a49c846adc0f.png">

**Comment by martinnov92** [comment]
Hello @samuelkavin I really don´t know this, sorry

**Comment by bogdancar** [comment]
I added an example on exporting a xlsx file from an array of jsons on Angular2/4:

[https://github.com/bogdancar/xlsx-json-to-xlsx-demo-Angular2](url)

**Comment by indunilw** [comment]
@bogdancar your demo isnt avaialble

**Comment by bogdancar** [comment]
[indunilw](https://github.com/indunilw) Sorry, fixed the link.

**Comment by gnasit** [comment]
@samuelkavin @jomel did you solve the custom header portion of the sheet, where you want common data for the table in a top section, is this possible? the memberListing portion in the OPs example

**Comment by SheetJSDev** [comment]
The new `sheet_add_json` function can add to an existing worksheet:

```js
var ws = XLSX.utils.aoa_to_sheet([
  ["Member Listing"],
  ["Company Name:", "<Master Policy Holder Name>"],
  ["Report Date:", "<DD/MM/YYYY>"]
]);
XLSX.utils.sheet_add_json(ws, [ { "agentNo":"324234", "subName":"30, Jul 2013 09:24 AM", "Location":"Singapore", "memberName":42, "certNo": "2342234", "Gender":"Male", "dob":"1 may 1987" }, { "agentNo":"444443", "subName":"30, Jul 2013 09:24 AM", "Location":"Malaysia", "memberName":42, "certNo": "2342234", "Gender":"Male", "dob":"1 may 1987" }, { "agentNo":"2342234", "subName":"30, Jul 2013 09:24 AM", "Location":"India", "memberName":42, "certNo": "2342234", "Gender":"Male", "dob":"1 may 1987" } ],{origin:-1});
```

To control the order of the fields, pass a header option to sheet_add_json:

```js
XLSX.utils.sheet_add_json(ws, [ ... ], {header: ["agentNo", "subName", "memberName", "certNo", "Gender", "dob"], origin:-1});
```

And to rewrite the column headers, if the objects don't have the same name as the titles you want, go back and rewrite a new header array in the fourth row (index 3):

```js
XLSX.utils.sheet_add_aoa(ws, [["Agent no", "Subsidiary name", "Member Name", "Cert No", "Gender", "Date of Birth"]], {origin:3});
```

**Comment by jomel** [comment]
@SheetJSDev OMG! Amazing! This makes it SO much easier. Thank you!
