### ISSUE TITLE
How do I load a table from a folder directly into the browser?

### ISSUE THREAD

**Issue by danbrsp** [SheetJS/js-xlsx#667]
I have a table in a folder C:\spreadhsheet and I`m making a HTML with some  JS scripts and I need this script to read the file directly.

How can I do it?

**Comment by SheetJSDev** [comment]
You can't request a local file from the browser directly, that's a big security risk.  The user has to submit the file some way.  For example, http://oss.sheetjs.com/js-xlsx/ allows the user to submit a file by dragging and dropping or by hitting the file input.

If you can make the workbook public, then you can use xmlhttprequest to download the file and read it from the browser.  See http://oss.sheetjs.com/js-xlsx/ajax.html for an example
