### ISSUE TITLE
insert row before header

### ISSUE THREAD

**Issue by samuelkavin** [SheetJS/js-xlsx#669]
@SheetJSDev is it possible insert custom 3 row before header? something like this:
Example: A1, A2, A3 
<img width="1003" alt="screen shot 2017-05-24 at 6 16 18 pm" src="https://cloud.githubusercontent.com/assets/5300968/26537398/ba67f512-4471-11e7-88bd-e47f29fd7cc2.png">

**Comment by jomel** [comment]
Related to #301

**Comment by reviewher** [comment]
Duplicate of #301
