### ISSUE TITLE
Unable to read the created xlsx file untill we save it one again..

### ISSUE THREAD

**Issue by Bikasa** [SheetJS/js-xlsx#670]
Hi,
I am unable to read my .xlsx file via my code until unless i ll save it once again.I am unable to figure out the issue.I have attached the file that I have created by using this module.Can you please figure out the issue and help me in resolving this.
the module that I am using to read is xlsx-stream-reader.
Please find below link for more clarification on this
https://github.com/DaSpawn/xlsx-stream-reader/issues/8

[F1_without_Save.xlsx](https://github.com/SheetJS/js-xlsx/files/1036172/F1_without_Save.xlsx)

thanks

**Comment by reviewher** [comment]
Can you check http://oss.sheetjs.com/js-xlsx/ ?  The file works ...

![screen shot 2017-05-29 at 13 12 14](https://cloud.githubusercontent.com/assets/24845478/26557581/77447eb4-4470-11e7-92da-9f639990e2cb.png)

**Comment by jcready** [comment]
This was [an issue with the xlsx-stream-reader package](https://github.com/DaSpawn/xlsx-stream-reader/issues/8#issuecomment-304721631).
