### ISSUE TITLE
[Feature Request?] Workbook Encryption

### ISSUE THREAD

**Issue by Magnamura** [SheetJS/js-xlsx#672]
Greetings!

I need to Encrypt the generated XLSX File with a Password.
(When opening the File in Excel the Password needs to be correct to view the Data)
I implemented the workbookProtection mentioned in  #457 and it worked quite well but it was not what i was looking for.
So any idea on how to realize my desired kind of protection? 
Or is this maybe a Pro Feature?

**Comment by reviewher** [comment]
Closing in favor of #791
