### ISSUE TITLE
Blob is not defined

### ISSUE THREAD

**Issue by pumpkinp** [SheetJS/js-xlsx#674]
i am copy the node demo and node .but is wrong 
"BLod is not defined"

> 
> `var wopts = { bookType:'xlsx', bookSST:false, type:'binary' };
> var wbout = XLSX.write(wb,wopts);
> function s2ab(s) {
> var buf = new ArrayBuffer(s.length);
> var view = new Uint8Array(buf);
> for (var i=0; i!=s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
> return buf;
> }
> /* the saveAs call downloads a file on the local machine */
> saveAs(new Blob([s2ab(wbout)],{type:""}), "test.xlsx")`

**Comment by SheetJSDev** [comment]
If you are running in nodejs, the browser-specific strategies like the one you referenced don't work.  You have to use a node strategy like writing to a file or writing to a buffer/string and sending to a client.

If you are running in the browser, you may need to include a [Blob shim](https://github.com/eligrey/Blob.js/blob/master/Blob.js).  This is explained in the [FileSaver.js readme](https://github.com/eligrey/filesaver.js#supported-browsers).  If you are still having issues with `Blob` being undefined, that's most likely a bug with the FileSaver.js dependency or the Blob.js shim.
