### ISSUE TITLE
aoa_to_sheet for fomulae cells

### ISSUE THREAD

**Issue by SevenOutman** [SheetJS/js-xlsx#675]
I was wondering how I can define a fomulae cell in the data array to be put into `aoa_to_sheet`.
Later I found in source code of `aoa_to_sheet` that I can do that by giving an array with `array[1]` being the formulae.
But I can't find any tips about that in the documentation, so I hope this can be improved.

**Comment by SheetJSDev** [comment]
@SevenOutman The array workaround in `aoa_to_sheet` is a backdoor specifically designed for SYLK processing.  When we make the next push on the SYLK format we'll likely remove it.

If you need to add a formula to a cell, the safe way is to build the worksheet up first then add the formula.  For example, based on the [`write.js sample`](https://github.com/SheetJS/js-xlsx/blob/master/tests/write.js):

```js
var data = [
	[1, 2, 3],
	[true, false, null, "sheetjs"],
	["foo", "bar", new Date("2014-02-19T14:30Z"), "0.3"],
	["baz", null, "qux", 3.14159]
];
var ws = XLSX.utils.aoa_to_sheet(data, {cellDates:true});

/* C1 is a cell with value `3` type `n`, so it is safe to set the `f` key */
ws['C1'].f = "A1+B1";
/* C2 was not created, so we have to build up the cell */
ws['C2'] = {t:'n', f:"A1+B1"};
```

A small helper function to cover those cases:

```js
function set_sheet_formula(ws/*:Worksheet*/, addr/*:string*/, formula/*:string*/) {
  if(!ws[addr]) ws[addr] = { t:'n', f:formula };
  else ws[addr].f = formula;
}
```

(on the issue of documentation: at this point, any undocumented "features" may change without notice and should not be relied upon)

**Comment by SevenOutman** [comment]
@SheetJSDev Actually I was using the build worksheet first approach in the first place, however I then find it inconvenient if `!refs` doesn't update automatically.

**Comment by SheetJSDev** [comment]
We have a few helper functions in the wiki: https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions -- they are based on [a related issue](https://github.com/SheetJS/js-xlsx/issues/260)

**Comment by SevenOutman** [comment]
@SheetJSDev Thanks. It really helps.
