### ISSUE TITLE
Format `0.0#` not displaying second decimal digit

### ISSUE THREAD

**Issue by kuhu19** [SheetJS/js-xlsx#677]
When trying to read decimal numbers from excel, numbers are getting rounded off. E.g. 15.06 comes as 15.1 in json.

**Comment by SheetJSDev** [comment]
@kuhu19 The only time the library should be rounding a cell is if the cell format forces a round.  For example, if the cell is formatted as Number with 1 decimal place, Excel will draw `15.1` on the worksheet but show `15.06` in the formula bar.

If you want to see the underlying raw value, you can pass the option [`raw:false`](https://github.com/sheetjs/js-xlsx#json)

If you have a file where Excel is showing the value `15.06` but the library is showing `15.1`, please share the file (you can email dev@sheetjs.com) and we will take a look

**Comment by kuhu19** [comment]
To add more info here, rounding is always upto 1 decimal place.
