### ISSUE TITLE
xlsx 0.10.4 fails to write any of the XLS format

### ISSUE THREAD

**Issue by buserror** [SheetJS/js-xlsx#678]
(From npm fresh install)
I can load the workbook, manipulate it, and write it out, but the file doesn't open in excel or LibreOffice or crashes as displayed below. File has four sheets.
Even he command line tool fails to create any form of working output without any changes... I tried pretty much every combination of BIFF, XML, SST, compression, you name it...
I can write alternate formats, but I lose quite a bit of the formatting...

$ file S-EN-EN-FS733-01.xls 
S-EN-EN-FS733-01.xls: Composite Document File V2 Document, Little Endian, Os: Windows, Version 6.1, Code page: 1252, Title: EM-PRJ9A

$ xlsx --all -X -o output.xls  S-EN-EN-FS733-01.xls

node_modules/xlsx/xlsx.js:16050
			var cell = dense ? ws[R][C] : ws[ref];
			                        ^
TypeError: Cannot read property '0' of undefined
    at write_biff_ws (/home/michel/node_modules/xlsx/xlsx.js:16050:28)
    at write_biff_buf (/home/michel/node_modules/xlsx/xlsx.js:16068:2)

**Comment by SheetJSDev** [comment]
@buserror It looks like there's a read error in one of the worksheets.  Can you share that `S-EN-EN-FS733-01.xls` file (you can email dev@sheetjs.com)?  If not, can you share the output of the following commands:

```bash
$ xlsx --dev --all S-EN-EN-FS733-01.xls
$ xlsx --dev --all -2 S-EN-EN-FS733-01.xls
$ xlsx --dev --all -X S-EN-EN-FS733-01.xls
```

**Comment by buserror** [comment]
I also tried the latest version from npm, and now the file gets written, but excel complains a lot about it when opening it, and the whole style, formulas etc are nuked... progress tho :-)
