### ISSUE TITLE
Excel found unreadable content in 'XXXXX.xlsx'

### ISSUE THREAD

**Issue by Bikasa** [SheetJS/js-xlsx#679]
Hi Team ,
 I am generating files using this module.Some files I am able to open without any issues.But some other file 
 I am getting error like  " Excel found unreadable content in XXXX.xlsx ".I am unable to resolve the issue.Can you please confirm ,if it is the issue with the file or with the module and help me to fix it out. I have attached two files out of which the file  I am able to open with out any issue is "Export_201605.xlsx".

Please find below attached screen shot an the file.
[Export_201605.xlsx](https://github.com/SheetJS/js-xlsx/files/1064395/Export_201605.xlsx)
[Account_201601.xlsx](https://github.com/SheetJS/js-xlsx/files/1064370/Account_201601.xlsx)
![error](https://user-images.githubusercontent.com/23119692/26980959-44ad8466-4d51-11e7-8f9e-47d73730f31d.png)

Thanks

**Comment by SheetJSDev** [comment]
The offending fields involve what appear to be dates that use a decimal point as a separator:

```xml
<c r="I92"><v>28.01.2007</v></c>
<c r="I2217"><v>17.12.2007</v></c>
<c r="I4009"><v>27.11.07</v></c>
```

This is easily reproduced by passing a string where a number is required:

```js
var XLSX = require('xlsx');
var wb = {
	SheetNames: ["Sheet1"],
	Sheets: {
		Sheet1: {
			"!ref":"A1:A1",
			A1: { v:"28.01.2007", t:'n' }
		}
	}
}
XLSX.writeFile(wb, "issue679.xlsx");
```

Somewhere a field that is supposed to be a date is stored as a numeric cell.  How are you building the workbook object?

**Comment by Bikasa** [comment]
Thanks @SheetJSDev ..I got the issue.

**Comment by reviewher** [comment]
Good to hear you figured it out!

**Comment by azlochevsky** [comment]
I am still having this error - no numbers - only strings. Please, help!
[View_Screen_Permissions_-_Screen_Permissions (3).xlsx](https://github.com/SheetJS/js-xlsx/files/1073203/View_Screen_Permissions_-_Screen_Permissions.3.xlsx)

**Comment by azlochevsky** [comment]
I am still having problems. It says there is '<' symbol in the attribute but I don't think it is true.
[View_Accounts_Charged_by_Employee (2).xlsx](https://github.com/SheetJS/js-xlsx/files/1073209/View_Accounts_Charged_by_Employee.2.xlsx)

**Comment by SheetJSDev** [comment]
@azlochevsky are you using the latest version? The error is coming from the styles XML:

```xml
<fgColor rgb="FF<TD></TD>"/>
```

which looks extremely strange.

**Comment by azlochevsky** [comment]
Thank you so much for your response! What is the latest version 0.10.0 ?

**Comment by azlochevsky** [comment]
Thank you again for pointing the error - i fixed my code and it works great!
No I have a different manifestation of the same problem (the same error message but I after I recover the file the recovery message shows the following:

**Excel was able to open the file by repairing or removing the unreadable content**
Excel completed file level validation and repair. Some parts of this workbook may have been repaired or discarded.
Removed Records: Merge cells from /xl/worksheets/sheet1.xml part.
[View_Screen_Permissions_-_Screen_Permissions (11).xlsx](https://github.com/SheetJS/js-xlsx/files/1075267/View_Screen_Permissions_-_Screen_Permissions.11.xlsx)

**Comment by AshalathaP** [comment]
use .xls instead of .xlsx. Error due to version issue of Excel
