### ISSUE TITLE
The Docs page freezing up my browser

### ISSUE THREAD

**Issue by GreggOD** [SheetJS/js-xlsx#681]
Hello Team,

Thanks for Sheetjs! I am relatively new to Javascript and still trying to wrap my head around the workings of this. Documentation could use more examples of implementation to help us newbies.

Anyways the https://sheetjs.gitbooks.io/docs/ page keeps freezing my browser :/

Im in Chrome Version 57.0.2987.133 (64-bit)

**Comment by reviewher** [comment]
There are many problems with gitbook like https://github.com/GitbookIO/gitbook/issues/1788

Use the [README.md](https://github.com/sheetjs/js-xlsx)
