### ISSUE TITLE
I read a file, save the fIle, background colors are lost,and some other style lost 

### ISSUE THREAD

**Issue by pumpkinp** [SheetJS/js-xlsx#682]
```
var workbook=XLSX.readfile('aa.xlsx',{cellStyles:true});
XLSX.writeFile(workbook,'aaaa.xlsx')
```
why??
no suport?

**Comment by pumpkinp** [comment]
before:
![be5ad688cf7821eec35102d12a724cd2](https://user-images.githubusercontent.com/21173134/27028575-bc7a4b30-4f97-11e7-9a84-2146d0d036d9.jpg)

after：
![7dc3377142216ea6e23d5189c0edc767](https://user-images.githubusercontent.com/21173134/27028592-caca05d6-4f97-11e7-8b8f-30010068bc91.jpg)

**Comment by shikelong** [comment]
protobi/js-xlsx  support write style to cell

**Comment by LennyYi** [comment]
@shikelong can you give a demo js for useing how to use the test-style.js for setting style? I am new one for sheetJS

**Comment by vinhboy** [comment]
To answer the original question, there is no support for writing styles. Just reading.

**Comment by pumpkinp** [comment]
protobi/js-xlsx support write style to cell

**Comment by juanjuaner** [comment]
@vinhboy does function cell.s not work?

**Comment by sapfiris** [comment]
@pumpkindev could you explain how to use protobi/js-xlsx correctly?
I has installed both xlsx and xlsx-style npm packages, but style is not applyed.
