### ISSUE TITLE
Parse by columns instead of rows 

### ISSUE THREAD

**Issue by sunilkumarm080** [SheetJS/js-xlsx#683]
I Have a Spreed Sheet where i need to Read the Data Column wise. Tired writing a two loops for the sheet_to_json but the process of execution takes more time.
 
Existing sheet_to_json = [ {A:1,B:2,C:3} , {A:4,B:5,C:6} ]
Required Format  = [ {A : [1,4] } , {B : [2,5] } , {C : [3,6] } ]

**Comment by reviewher** [comment]
`sheet_to_json` is pretty simple: https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L1

It just loops [by row](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L41) and [by column](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L50).  If you need to read the other direction, just access the cells the other way around (first loop by column then by row).
