### ISSUE TITLE
How to create internal links

### ISSUE THREAD

**Issue by gawi** [SheetJS/js-xlsx#685]
I'm trying to generate an XLSX Excel document with JS-XLSX and I can't find a way to create the equivalent of an internal link.

I have this summary page in which I'd like to present clickable links pointing to other sheets.

![image](https://user-images.githubusercontent.com/813371/27062193-57543610-4fb7-11e7-8f21-27b79d26c879.png)

I've tried many combination of cell = {l: {Target: "..", Rel: {Target: "...", Type:"Internal"}}} but it doesn't work. It always ends up as an external hyperlink in the generated document.

I'm using JS-XLSX 0.10.4.

Is this a supported use case?

**Comment by SheetJSDev** [comment]
As a general rule, everything is in the README.  If it's not mentioned there, it's either currently unsupported or a bug in the README.

The write logic currently assumes an external hyperlink for [every link](https://github.com/SheetJS/js-xlsx/blob/master/bits/67_wsxml.js#L467) and every relationship, so at the moment it is not supported.  It's relatively simple to fix, we'll try to roll out something in the next release.  We will have to add a new flag to the link object.

**Comment by calbertts** [comment]
Would be great to have this feature and also the ability to add VBA code.

**Comment by UzverNumber47** [comment]
You can use formula.
sheet['A1'].f = '=HYPERLINK("#\'Section1\'!A1,"Section 1")';

**Comment by SheetJSDev** [comment]
In the internal representation, set a cell's `.l` key to be an object with `Target` set to the reference prepended by a `#` e.g.

```js
ws['A1'].l = { Target: "#Sheet2!A1" } // Link to a cell
ws['A2'].l = { Target: "#Sheet2!A1:D4" } // Link to a range
ws['A3'].l = { Target: "#SomeName" } // Link to a global or same-worksheet defined name
ws['A4'].l = { Target: "#Sheet2!SomeName" } // Link to an out-of-scope defined name
```

@UzverNumber47 's approach also works

**Comment by charlygame** [comment]
ws['A1'].l = { Target: "'#SheetName'!A1" }  is work
