### ISSUE TITLE
xlsx.core.min.js has snoman character instead of code \u2603 due to whihc xlsx generation on IE 11 browser fails

### ISSUE THREAD

**Issue by clgnik** [SheetJS/js-xlsx#687]
xlsx.core.min.js has snoman character instead of code \u2603 due to whihc xlsx generation on some IE 11 browser fails.

Step to find this code : search for ^☃]*) in xlsx.core.min.js

the Fix for this issue is :  simply replace   ^☃]*)  by  \u2603]*)  in xlsx.core.min.js

**Comment by SheetJSDev** [comment]
@clgnik that is very strange! Can you share a small example?  Also, can you test if http://sheetjs.com/demos/modify.html works on your computer? I've manually tested it back to IE6 without issue.

We run the browser test suite against IE8+, so I'm surprised that something like the snowman char would not work on IE11:

[![Build Status](https://saucelabs.com/browser-matrix/sheetjs.svg)](https://saucelabs.com/u/sheetjs)

**Comment by SheetJSDev** [comment]
@clgnik replaced the relevant regular expressions, please reopen if the issue persists after updating

**Comment by clgnik** [comment]
Its working fine now!
