### ISSUE TITLE
Written XLSX file is larger than expected

### ISSUE THREAD

**Issue by doilyrack** [SheetJS/js-xlsx#690]
Using either
```
XLSX.writeFile(workbook, outputFile, { bookType: 'xlsx', bookSST: false, type: 'binary' });
```
or
```
XLSX.writeFile(workbook, 'outputFile.xlsx');
```
i.e. auto-detect, I end up with a file that is 3-4 times larger than what I get if I open and re-save it with Excel.

Is there a way to get smaller file sizes? My worksheets need only contain data - no style info required.

(Using xlsx version 0.10.1)

**Comment by SheetJSDev** [comment]
@doilyrack XLSX files are usually ZIP containers (there are some exceptions like encrypted documents, but by and large they use ZIP).  By default `compression` is disabled, which results in faster generation times but much larger documents.  To reduce the file size, pass the option `compression:true` to writeFile:

```js
XLSX.writeFile(workbook, outputFile, { bookType: 'xlsx', bookSST:false, compression:true, type: 'binary' });
```

If you have many repeated strings, setting `bookSST:true` will help, but if you only have a few labels then keeping `bookSST:false` is more space efficient

**Comment by doilyrack** [comment]
Excellent, that's it. I hadn't spotted that in the docs.
Thanks.
