### ISSUE TITLE
Read/convert column orientated spreadsheets

### ISSUE THREAD

**Issue by mrb1090** [SheetJS/js-xlsx#691]
Looking to read/convert column orientated spreadsheets into JSON with keys in the first column.  Does SheetJS support this spreadsheet layout/format?

Thanks,

Mike Brown

**Comment by SheetJSDev** [comment]
The utility functions are row-oriented, but it's not too hard to add a flag to support column-oriented accesses.  They aren't that complex, so you can actually change them yourself while waiting!

The actual `sheet_to_json` definition is pretty short: https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L1 .  The [header loop](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L25) iterates over the first row, the [core loop](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L41) iterates over the rows and the [inner loop](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L50) iterates over the sheets.  Those can be flipped for column-oriented access.

**Comment by mrb1090** [comment]
Thanks for the pointer.  Much appreciated.

**Comment by uiforchange** [comment]
Can you please provide the ode to proceed
