### ISSUE TITLE
Do we support to convert print area to image file? Is there sample?

### ISSUE THREAD

**Issue by yhBluescape** [SheetJS/js-xlsx#693]
Hi,

Do we support to convert a  print area of a excel file to a image file, like png, jpg or others,...
Is there a sample code to test it?

Thanks,

**Comment by SheetJSDev** [comment]
Generating an image is currently outside of the scope of this library.  There are other libraries like https://github.com/niklasvh/html2canvas that can take a screenshot.

**Comment by yhBluescape** [comment]
Hi,

Thanks for the reply,

The resource on your link is for web page, not for excel doc, is it?

Do your package compete with aspose cells ?

The best,
