### ISSUE TITLE
table_to_book is reading a string as a date

### ISSUE THREAD

**Issue by khalilTN** [SheetJS/js-xlsx#697]
Hi,

I have a td tag in a table that contains the string value `1,13` (a formatted number with toLocaleString)
`<td>1,13</td>`
The value that was read in the generated xlsx is `13/01/2001` wich is a date.
The object that was read
`Object {t: "n", v: 36904.041666666664, z: "m/d/yy"}`

What can be the cause ?
Thanks!

**Comment by SheetJSDev** [comment]
Same as https://github.com/SheetJS/js-xlsx/issues/673 , let's keep it to one tracking issue for now
