### ISSUE TITLE
0.8.3 seems missing from npm registry

### ISSUE THREAD

**Issue by renjith7189** [SheetJS/js-xlsx#699]
The module was working fine till last week, but now I am getting 

npm install xlsx@0.8.3
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "xlsx@0.8.3"
npm ERR! node v6.9.1
npm ERR! npm  v4.0.2
npm ERR! notarget No compatible version found: xlsx@0.8.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.10.5, 0.10.4, 0.10.3, 0.10.2, 0.10.1, 0.10.0, 0.9.13, 0.9.12, 0.9.11, 0.9.10, 0.9.9, 0.9.8, 0.9.7, 0.9.6, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0, 0.8.8, 0.8.7, 0.8.6, 0.8.5, 0.8.4, 0.8.1, 0.8.0, 0.7.12, 0.7.0, 0.6.1, 0.6.0, 0.5.17, 0.5.8, 0.5.7, 0.5.6, 0.5.0, 0.4.3, 0.3.10, 0.3.9, 0.3.7, 0.3.6, 0.3.5, 0.3.3
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by SheetJSDev** [comment]
@renjith7189 Prior to 0.9.2 some of the dependencies had unspecified version numbers.  For 0.8.3: https://github.com/SheetJS/js-xlsx/blob/v0.8.3/package.json#L11 .

There are some NPM related bugs related to missing version numbers, like https://github.com/npm/npm/issues/11493, and we've received quite a few inquiries about problems in NPM5 related to the unspecified version numbers, so we recommend switching to a version above 0.9.2.
