### ISSUE TITLE
Is there a way to convert nested objects?

### ISSUE THREAD

**Issue by everthis** [SheetJS/js-xlsx#702]
```js
  [{
      "id": "1759319",
      "current": "random_v",
      "type": "some",
      "category": "some",
      "log": [{
          "user": "jim",
          "status": "ok"
      }, {
          "user": "jack",
          "status": "ok"
      }]
  }, {
      "id": "1759345",
      "current": "another",
      "type": "anothertype",
      "category": "another",
      "log": [{
          "user": "jim",
          "status": "ok"
      }, {
          "user": "jack",
          "status": "ok"
      }]
  }]
```

current `json_to_sheet` not processing `log` content, the log column in the result `.xlsx` file is blank.
Is there a way to make log content present in the result `.xlsx` file ?

**Comment by SheetJSDev** [comment]
There's no obvious solution to mapping nested objects to a flat row.  For example:

- generate keys like `"log0_user"`, `"log1_status"` 

- generate a multi-row header with merge cells, so something like

```
| log0          | log1          | 
| user | status | user | status |
```

You can flatten the objects manually before passing to `json_to_sheet`.
