### ISSUE TITLE
First Row Blank then Column Skipped

### ISSUE THREAD

**Issue by GreggOD** [SheetJS/js-xlsx#707]
Hi Guys,

I have a xls sheet with headers and im converting it to json- i've noticed if the first cell of a column (under the header) is blank, that column will not be added to the file object.

How do i get all columns to be added?

I have tried: 
`{blankrows: true, header:1, sheetStubs:true}`
and am still facing the issue.

Thanks,
Gregg

**Comment by reviewher** [comment]
Can you share an example xls sheet and what you want to see?

https://github.com/SheetJS/js-xlsx#json  `defval:""`.

**Comment by GreggOD** [comment]
Thank you! I have fixed it by doing adding `{defval:""}` to my json converter.

For anyone else who comes across this, my function, taken from the [sheetjs website demo](http://oss.sheetjs.com/js-xlsx/)
looks like:

```
// Create Json object from file
function to_json(workbook) {
    var result = {};

    // build object
    workbook.SheetNames.forEach(function(sheetName) {
        var roa = X.utils.sheet_to_row_object_array(workbook.Sheets[sheetName], {defval:""});
        if(roa.length > 0){
            result[sheetName] = roa;
        }
    });
    return result;
}

```
