### ISSUE TITLE
"new Date()" function   work in chrome not expected 

### ISSUE THREAD

**Issue by mz121star** [SheetJS/js-xlsx#709]
if (v != null && v.length) { 
                    if (!isNaN(Number(v)))
                        o = {
                            t: "n",
                            v: Number(v)
                        };
                    else if (!isNaN(fuzzydate(v).getDate())) {
                        o = {
                            t: "d",
                            v: parseDate(v)
                        };
                        if (!opts.cellDates)
                            o = {
                                t: "n",
                                v: datenum(o.v)
                            };
                        o.z = opts.dateNF || SSF._table[14]
                    }
                }

example: 
Number('4,001')
chrome input: Sun Apr 01 2001 00:00:00 GMT+0800 (CST)
firefox input:Invalid Date

**Comment by SheetJSDev** [comment]
@mz121star we started digging into how to properly detect numbers versus potential dates.  To first order, we strip the `$` currency symbol now and remove commas between numbers, which does work for the case `4,001`.
