### ISSUE TITLE
Rendered Documentation Freezes

### ISSUE THREAD

**Issue by mlhan1993** [SheetJS/js-xlsx#710]
There's seems to be some issues with the docs page. 
It's been freezing: https://sheetjs.gitbooks.io/docs/

Browser tried: chrome, firefox, safari
OS tried: ubuntu,  mac os

**Comment by reviewher** [comment]
There's an open issue with the gitbook service: https://github.com/GitbookIO/gitbook/issues/1788 

The rendered documentation displays the https://github.com/SheetJS/js-xlsx/blob/master/README.md with a table of contents on the left column.  The content is the same, so use the README in the meanwhile.
