### ISSUE TITLE
Example to create excel chart from JSON object

### ISSUE THREAD

**Issue by er-shrey** [SheetJS/js-xlsx#713]
I am not able to find proper documentation or any example to create chart in a worksheet/chartsheet from a json object

**Comment by reviewher** [comment]
It is in the backlog for the community version.

**Comment by er-shrey** [comment]
https://sheetjs.gitbooks.io/docs/#chartsheet-object

here also I didn't found any example or proper documentation

**Comment by er-shrey** [comment]
@reviewher kindly respond

**Comment by er-shrey** [comment]
closing as no one is responding

**Comment by Tollman** [comment]
So were I can find example of creating chart?

**Comment by adnirjhar** [comment]
Any documentation? Do they have a different codebase of codebase for the pro features ?
