### ISSUE TITLE
Save edited xlsx into local storage

### ISSUE THREAD

**Issue by ImmanuelJL** [SheetJS/js-xlsx#714]
Dear, may i know how to save my edited xlsx into local storage? Thank You

**Comment by er-shrey** [comment]
$localstorage.editedXlsx = XLSX.write(wb, { type: 'buffer' });

**Comment by reviewher** [comment]
@ImmanuelJL If you are asking about the `localStorage` API, you can:

- write to a binary string and store it:

```js
localStorage.setItem("file", XLSX.write(wb, { type: 'binary' }));
```

- store a workbook object and generate the XLSX file when you need it:

```js
localStorage.setItem("data", JSON.stringify(wb));

/* when you need it */
var wb = JSON.parse(localStorage.getItem("data"));
```

If you are asking about a local download:

- the [README](https://github.com/SheetJS/js-xlsx#writing-workbooks) has an example of generating a download using [FileSaver.js](https://github.com/eligrey/FileSaver.js/)  

- Some of the [write demos](http://sheetjs.com/demos/table.html) also show how to use [downloadify.js](https://github.com/dcneiner/downloadify) for older IE support

- IE has [`msSaveBlob` and `msSaveOrOpenBlob`](https://msdn.microsoft.com/en-us/library/hh779016.aspx) to generate a download -- you can construct a new blob with the "binary" output type

- newer versions of IE and other browsers have [createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) for similar effect.

**Comment by ImmanuelJL** [comment]
@reviewher Hi thanks for reply, how about save on local directory and database?

**Comment by ImmanuelJL** [comment]
@er-shrey @reviewher how about save edited file into project folder?

**Comment by dave-wind** [comment]
you can try to see~
https://github.com/dave-wind/excel

**Comment by nithin-neewee** [comment]
@ImmanuelJL : I am using the Xlsx but the challenge here is when i upload file and route to another page and using the angular rxjs behaviour for the state and the uploaded excel sheet would render in the routed page but when i refresh the page even though setting it to the localstorage the data does not get stored any option in the xlsx
