### ISSUE TITLE
Direct open xlsx file from folder without drag and drop

### ISSUE THREAD

**Issue by ImmanuelJL** [SheetJS/js-xlsx#716]
Hi, anyone know how to direct open the file from folder? i am using this code:

/* set up XMLHttpRequest */
var url = "http://localhost/test.xlsx";
var oReq = new XMLHttpRequest();
oReq.open("GET", url, true);
oReq.responseType = "arraybuffer";

oReq.onload = function(e) {
  var arraybuffer = oReq.response;

  /* convert data to binary string */
  var data = new Uint8Array(arraybuffer);
  var arr = new Array();
  for(var i = 0; i != data.length; ++i) arr[i] = String.fromCharCode(data[i]);
  var bstr = arr.join("");

  /* Call XLSX */
  var workbook = XLSX.read(bstr, {type:"binary"});

  /* DO SOMETHING WITH workbook HERE */
  firstSheet = workbook.SheetNames[0];
  document.write(JSON.stringify(workbook));
  parsed = XLSX.utils.sheet_to_csv(firstSheet);
}

oReq.send();  

i know its just throw json, what i want is its parsed like this example http://oss.sheetjs.com/ not only a json.

 thanks

**Comment by SheetJSDev** [comment]
There's no standard way for a web browser to break the sandbox and proactively read from your computer.  You have to somehow provide the file.  The [README](https://github.com/sheetjs/js-xlsx#parsing-workbooks) includes a few examples using drag-and-drop / file input element.   http://oss.sheetjs.com/js-xlsx provides both input methods.
