### ISSUE TITLE
Date in XLS sheet not parsing correctly

### ISSUE THREAD

**Issue by Piyush95aadi** [SheetJS/js-xlsx#721]
I am trying to read a XLS file with a column having dates. After parsing the file what I found is that the dates are of few dates back from that of the dates in the sheet.
This is what I a doing.
```
var workbook = XLSX.readFile(filePath);
var grossPayoutSheet = workbook.Sheets[worksheets[1]];
for (var i in grossPayoutSheet) {
				if (i[0] === "!") continue;
				var col = (!isNaN(parseInt(i.substring(1)))) ? i.substring(0,1) : i.substring(0,2);
				var row = (!isNaN(parseInt(i.substring(1)))) ? parseInt(i.substring(1)) : parseInt(i.substring(2));
				var value = grossPayoutSheet[i].v;
				if (row === 2) {
					var value = grossPayoutSheet[i].v;
					headers[col] = value.trim();
					continue;
				}
				if (row !== 1 && !data[row]) {
					data[row] = {};
				} else if (row !== 1){
					data[row][headers[col]] = value;
				}
			}
```
the value in the cell is 

> 05/07/2017

but after parsing the value is 

> B3: { t: 'n', v: 42921, w: '42921' }

I want the date in string format that is I want to change the cell format from 'n' to 's'

Can anyone please help me out with this ?

**Comment by reviewher** [comment]
XLS files always store dates as numeric codes.  To get the date objects, change the first line to

```js
var workbook = XLSX.readFile(filePath, {cellDates:true});
```

This is explained in https://sheetjs.gitbooks.io/docs/#dates
