### ISSUE TITLE
Let me know If this Node Packege manager do support .xlsm

### ISSUE THREAD

**Issue by Atique12** [SheetJS/js-xlsx#725]
Hi I want to convert particular .xlsm file particular field to JSON format. I didn't find the code. Looks like huge thing is there. Can you help me to solve the problem??

**Comment by reviewher** [comment]
All of the read examples, like http://oss.sheetjs.com/js-xlsx/, should work with any of the supported file formats. The full list is in [the README](https://github.com/SheetJS/js-xlsx#file-formats) and includes XLSM.
