### ISSUE TITLE
sheet_to_json set range by columns

### ISSUE THREAD

**Issue by norimori** [SheetJS/js-xlsx#728]
I am trying to read a xlsx/csv file, but I would like to restrict the columns I am reading. For example, I would like to read the entire file, but only read from column A to column G.

I've attempted to do this with the following, but it appears that the range does not get properly set:

```
var excelInJSON = xlsx.utils.sheet_to_json(workbook.Sheets[firstSheet], {blankRows: false, defval: '', range: "A:G"});
```

Would appreciate some assistance in this. Thanks!

**Comment by reviewher** [comment]
The [range argument is expected to be a finite range](https://github.com/sheetjs/js-xlsx#json) but it probably should accept an incomplete spec.

The easiest way is to calculate the range directly:

```js
var range = XLSX.utils.decode_range(workbook.Sheets[firstSheet]['!ref']);
range.s.c = 0; // 0 == XLSX.utils.decode_col("A")
range.e.c = 6; // 6 == XLSX.utils.decode_col("G")
var new_range = XLSX.utils.encode_range(range);
var excelInJSON = xlsx.utils.sheet_to_json(workbook.Sheets[firstSheet], {blankRows: false, defval: '', range: new_range});
```
