### ISSUE TITLE
Question: Is there a way to access the unparsed PTG bytecodes for a formula?

### ISSUE THREAD

**Issue by MisanthropicBit** [SheetJS/js-xlsx#730]
My javascript is not great but as far as I can tell, there is currently no API function for getting the raw byte representation for a formula in a cell (or any other cell contents for that matter) as opposed to their value or string representation as they are parsed before being returned.

Is this true or have I overlooked something? Would it be possible to implement this functionality somehow?

Sorry if this is not the place for asking questions, but the contribution guidelines did not mention anything about asking questions.

**Comment by SheetJSDev** [comment]
Currently there is no way.  If there's some issue with the formula parsing, please share an example so we can take a look.  

As you probably know, there are [4 types of formula representations](https://github.com/SheetJS/js-xlsx#formulae) and we decided to settle on converting everything into A1-style strings.  We are unlikely to add the raw bytes back into the representation until we can convert from strings to the Ptg representation.

If you just wanted a raw dump of the bytes, you can add them into the respective formula record parsers.  The code is littered with references to MS-XLS and MS-XLSB and every XLS/XLSB record type has a named entry in the [big record tables](https://github.com/SheetJS/js-xlsx/blob/master/bits/77_parsetab.js)
