### ISSUE TITLE
upload the files automatically to server 

### ISSUE THREAD

**Issue by barneyliu708** [SheetJS/js-xlsx#731]
Currently I am using combination of XLSX.write() and saveAs() to export excel at client side 
Here is my code:
var wbout = XLSX.write(wb, wopts);
saveAs(new Blob([s2ab(wbout)], { type: 'application/octet-stream' }), fileName);

But now I also need to automatically upload the xlsx file to server for backup purpose. Is there any way to upload the file before it's downloaded to client side and automatically upload to server?

**Comment by SheetJSDev** [comment]
`var wbout = XLSX.write(wb, wopts);` generates the output and you can send that to the server via XHR.  See https://github.com/SheetJS/js-xlsx/tree/master/demos/xhr for some examples of uploading back to a server
