### ISSUE TITLE
Empty file is created with filesaver.js while saving

### ISSUE THREAD

**Issue by gurjit03** [SheetJS/js-xlsx#733]
Hi all,

I am trying to create excel file and save the data using the `filesaver.js`, tried with various options but neither of it works. Ironically I can see in the console that data is being successfully created , along with that I have consoled the output of `arrayBuffer` which also gives the length around 14k but not sure why the data is not being saved using `filesaver.js`. 

Here is the code snippet :-
```
const exportExcelReport = (reportData) => {
  /* bookType can be any supported output type */
  const wopts = { bookType:'xlsx', bookSST:false, type:'binary' }; //tried using base64 

  const workbook = XLSX.utils.book_new(); // declaring workbook...
  const ws = constructWorkSheet(reportData);
  const wsName = 'report'
  workbook.SheetNames.push(wsName)
  workbook.Sheets[wsName] = ws;

  console.log(workbook,"bc.....") // This clearly shows the data for workbook there
  let wbout = XLSX.write(workbook,wopts);
   console.log(wbout,"wbout....")
  /* the saveAs call downloads a file on the local machine */
  // const blob = base64ToBlob(wbout); // tried with base64 as well

  saveAs(new Blob([s2ab(wbout)],{type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}), "meteor.xlsx"); // tried with octet-stream as well
}
```
My work enviroment is
**Chrome 58
ubuntu 16.04**

Any help is greatly appreciated.

**Comment by SheetJSDev** [comment]
If you can see the output data in `console.log(wbout,"wbout....")`, that is probably a bug with FileSaver.js and you should raise an issue there: https://github.com/eligrey/FileSaver.js/issues .

One possible issue: the demos use type `application/octet-stream` -- does that work?
