### ISSUE TITLE
Broken releases

### ISSUE THREAD

**Issue by calbertts** [SheetJS/js-xlsx#734]
Hi guys,

I'm gonna skip the rules because this is a question.

What's going on with the npm releases from 0.8.1 to 0.8.7? They aren't in the NPM registry anymore and my project is broken now, I had to upgrade to 0.8.8, so I'm not sure if there's a good reason for this, but it's pretty annoying.

How can we check if this is a NPM issue? or were those releases removed? why?

Thanks

**Comment by SheetJSDev** [comment]
NPM 5 completely broke packages that used empty strings to specify dependency versions, see https://github.com/npm/npm/issues/17227 

The first release that complies with NPM 5 requirements is 0.9.2, so we encourage people to upgrade.  The only reason we bumped the minor version in the 0.9.0 release was to fold the separate ods.js script into the main script: pre-0.9.0 the ODS script was an optional feature in a separate file, but that confused webpack and other systems.
