### ISSUE TITLE
How do you bold a cell?

### ISSUE THREAD

**Issue by djMax** [SheetJS/js-xlsx#74]
I've tried a bunch of different things (setting r, setting s:{fontId:1}, other stuff) but I can't seem to bold a cell when writing a workbook. How should this work?

**Comment by bchr02** [comment]
@SheetJSDev first off just want to say thanks for this great repo.

In regards to what you wrote here: https://github.com/SheetJS/js-xlsx/issues/74#issuecomment-46981775 I don't understand a few things.

For example, in item 1 you write:

> You can manually add a font with ````<b/>```` there.

I don't understand that sentence at all. Can you clarify?

You then mention to take a look at a rich text stress, which generates a file with formatted cells, which is exactly what I am trying to accomplish. How do I do that? I didn't see a way to pull up the source code that generates this file for the purposes of trying to figure out how it was done. 

Building off one of your example source codes, I added a function that takes an array of objects and builds the data needed for the excel file.  Below is what it looks like. For now, what I am trying to do is make the header row bold and underline. How can I change the code to accomplish this?

By the way, for anyone else wanting to use this function, it requires the use of either the lodash or underscore library.

````javascript
function sheet_from_array_of_objects(data, opts) {
		var ws		= {},
			range	= {s: {c:10000000, r:10000000}, e: {c:0, r:0 }},
			cell,
			cell_ref,
			R_loc = 0;
			C_loc = 0;
		
		// Add Header Row
		_.forEach(data[0], function(value, key) {
			cell = { v: key };
			cell.t = 's';
			cell_ref = XLSX.utils.encode_cell({c: C_loc,r: R_loc});
			ws[cell_ref] = cell;
			range.e.c++;
			C_loc++;
		});
		R_loc++;
		
		// Add rows and their cells
		for(var R = 0; R != data.length; R++) {
			C_loc = 0;
			_.forEach(data[R], function(value, key) {
				if(range.s.r > R) range.s.r = R;
				if(range.s.c > C_loc) range.s.c = C_loc;
				if(range.e.r < R) range.e.r = R;
				if(range.e.c < C_loc) range.e.c = C_loc;
				
				cell = { v: data[R][key] };
				
				if(cell.v != null) {
					cell_ref = XLSX.utils.encode_cell({c: C_loc,r: R_loc});
					if(typeof cell.v === 'number') cell.t = 'n';
					else if(typeof cell.v === 'boolean') cell.t = 'b';
					else if(cell.v instanceof Date) {
						cell.t = 'n'; cell.z = XLSX.SSF._table[14];
						cell.v = datenum(cell.v);
					}
					else cell.t = 's';
					
					ws[cell_ref] = cell;
				}
				range.e.c++;
				C_loc++;
			});
			range.e.r++;
			R_loc++;
		}
		if(range.s.c < 10000000) ws['!ref'] = XLSX.utils.encode_range(range);
		return ws;
	}
````

**Comment by nathanKramer** [comment]
@bchr02 Just thought I'd respond to you in case anyone else is confused, even though you've probably worked it out by now.

If you unzip the [rich text stress](https://github.com/SheetJS/test_files/blob/master/rich_text_stress.xlsx?raw=true) that SheetJS linked and open the xl/style.xml you'll see what he meant by being able to add `<b/>` to a new font. 

He provides the following example:
```
o.push('<fonts count="2"><font><sz val="12"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font><font><b/><sz val="12"/><color theme="1"/><name val="Calibri"/><family val="2"/><scheme val="minor"/></font></fonts>');
```

Presumably that was to replace line 158 [here](https://github.com/SheetJS/js-xlsx/blob/master/bits/47_styxml.js#L152)

That's pretty much all that's required to get his workaround working, he then referred to his newly created font in the `get_cell_style` function. 

```
function get_cell_style(styles, cell, opts) {
    var z = opts.revssf[cell.z||"General"];
    for(var i = 0; i != styles.length; ++i) if(styles[i].numFmtId === z && (styles[i].fontId === 1 ? cell.bold : !cell.bold)) return i;
    styles[styles.length] = {
        numFmtId:z,
        fontId:cell.bold ? 1 : 0, // This line!
        fillId:0,
        borderId:0,
        xfId:0,
        applyNumberFormat:1
    };
    return styles.length-1;
}
```

**Comment by bchr02** [comment]
@nathanKramer thanks very much for the clarification. Actually, I moved on to another library called [exceljs](https://github.com/guyonroche/exceljs) which in my opinion is more in line with the node philosophy because it offers streaming support in addition to styles. This allows me to to build excel files in pieces (or streams of data) which is extremely beneficial with large data sets. And it is not blocking and does not consume as much memory.

**Comment by Farooq708** [comment]
Hi could any one help me in changing the deader of the table style, i want to change header cell color.. Please help me..

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by barfuin** [comment]
Setting a cell to bold is a pro feature? Seriously?

**Comment by norbertas-gaulia** [comment]
> Setting a cell to bold is a pro feature? Seriously?

lol, oneliner csv export is much easier

**Comment by SheetJSDev** [comment]
The open source libraries were originally created to solve a specific problem involving data import and export.  In fact, at the very beginning the CLI tools actually were called xlsx2csv and xls2csv (which, as you can imagine, converted xlsx and xls files respectively to csv).  Once you get past the easy 90% of the problem, the last 10% takes some serious testing and corner case discovery.

Prior to what is now the "Pro version", my personal savings and time, as well as the patience and monetary contributions from my younger sister and parents, subsidized that research and development.  Thanks to sales of the Pro version, we are able to continue providing support for the open source build without having to resort to questionable tactics like [relicensing to a non-free license](https://github.com/handsontable/handsontable/issues/5831#issuecomment-476431217) or [abandoning entirely](https://github.com/GitbookIO/gitbook#%EF%B8%8F-deprecation-warning).

If you genuinely feel that removing the open source option or abandoning the open source project is a better outcome than the current situation, definitely let us know.  We were under the impression that keeping the main projects free and open source under an Apache 2.0 License was the best decision for us and the best outcome for the community.

PS: [Microsoft uses the open source library in Office 365 Apps](https://tasks.office.com/License.html).  The fact that they continue to use this library despite its current shortcomings certainly suggests the current free/pro split is in a reasonable place (and no, they have not reached out to us in the interest of purchasing a Pro license, so Microsoft developers probably never once asked about the necessity of "setting a cell to bold")

**Comment by barfuin** [comment]
> Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.

Actually, not really. It is common practice for other teams, [for example at GitLab](https://about.gitlab.com/blog/2020/03/30/new-features-to-core/). You might need to review your pricing model for the paid plans, as people may not want to continue paying money just for setting a cell to bold. (But maybe they would for advanced colorization, or support of certain format versions etc. This is somethings that will keep evolving.)
