### ISSUE TITLE
Empty version specifiers in package.json

### ISSUE THREAD

**Issue by the-spyke** [SheetJS/js-xlsx#740]
Please replace empty version specifiers like `"mocha":""` at least with asterisks `"*"` . Npm always checks for newer version on-line on `npm install` in empty case, even if the package is already in `node_modules`. Also it shows the package as invalid on `npm list`. All this is not an issue with asterisk.

Please do this in sub packages too. Thank you.

**Comment by SheetJSDev** [comment]
@the-spyke js-xlsx 0.10.9 has properly pinned dependencies and devDependencies.  We updated the tree so it should work properly now.  Please test and let us know if there are any issues

**Comment by the-spyke** [comment]
@SheetJSDev Looks like `frac` package still has empty version specifiers. Other packages are good. Thanks.

**Comment by the-spyke** [comment]
@SheetJSDev All looks fine now. Thank you.

**Comment by SheetJSDev** [comment]
@the-spyke we bumped the minor version number because we also changed a build step for the dist files -- all of the require statements were stripped out, as they were confusing webpack when trying to bundle the minified files.  The node and standard webpack usage should not have been changed.

**Comment by the-spyke** [comment]
Yeah, works good. Thank you.
