### ISSUE TITLE
Remove thousand separator on number cell when using XLSX.stream.to_csv

### ISSUE THREAD

**Issue by calebeaires** [SheetJS/js-xlsx#742]
I am writing an tool that convert xlsx to csv then import it to MySQL/MariaDB/MemSQL. I have done some customizations to make fields works on the same type direction.

I need, for example, that when an XLSX has an cell with a formatted number like `12.000,97`, it will be set to `12000,97` (without thousand separator) when converting to CSV.

```node
            const wb = XLSX.readFile(this._filePath, {
                dateNF: 'yyyy-mm-dd'
            });
            const ws = wb.Sheets[wb.SheetNames[0]];

            const write = await XLSX.stream.to_csv(ws, { FS: '\t', RS: '\n', blankrows: false });

            await write.pipe(
                fs.createWriteStream(
                    this._config.gaioPath.path_directories + '/apps/' + appId + '/' + this._fileName + '_xlsx.csv'
                )
            );
```

Does I need to put cellNF to true and cellText to false? Is there some another property I am missing?

**Comment by SheetJSDev** [comment]
Setting `cellNF:true, cellText:false` will force the library not to generate the original formatted text, so that should be sufficient.

But if you are really just interested in the values, I would suggest reading with `cellDates:true` and writing with `raw:true`.
