### ISSUE TITLE
Unexpected token < at make_xlsx xlsx.js

### ISSUE THREAD

**Issue by mg9313** [SheetJS/js-xlsx#743]
Angular 2, Typescript 2.3

When i include xlsx library as "import * as xlsx from 'xlsx';" in my component(.ts) and run the app, the component doesn't load at all. I keep getting error in the browser console: "ERROR Error: Uncaught (in promise): Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at make_xlsx (http://localhost:34385/node_modules/xlsx/xlsx.js:1581:9)
	    at Object.eval (http://localhost:34385/node_modules/xlsx/xlsx.js:17955:3)
	    at eval (http://localhost:34385/node_modules/xlsx/xlsx.js:17961:4)
	    at eval (http://localhost:34385/node_modules/xlsx/xlsx.js:17962:3)
	    at eval (<anonymous>)
	Evaluating http://localhost:34385/fs"

**Comment by mg9313** [comment]
When I debug it in Chrome, the error is at this line(#1581) : "_fs = require('fs');" - not sure why it says unexpected token

**Comment by reviewher** [comment]
@mg9313 Did you suppress `fs`? See https://github.com/SheetJS/js-xlsx/tree/master/demos/systemjs#browser for the SystemJS config.  Based on the error message, it almost looks like SystemJS is trying to request a nonexistent file and is getting a 404 web page, hence the `<`

**Comment by mg9313** [comment]
Excellent - thanks a lot, I had not suppressed fs, the error disappear after suppressing it!
