### ISSUE TITLE
XLSX.read is not a function

### ISSUE THREAD

**Issue by mg9313** [SheetJS/js-xlsx#747]
In my systemjs, i have mapped xlsx to dist/xlsx.full.min.js - I have also suppressed fs, crypto and stream. Systemjs also exports xlsx module : 
    var config = {
        meta: {
            '*': {
                authorization: true
            },
            'xlsx': {
                exports: 'XLSX' // <-- tell SystemJS to expose the XLSX variable
            }
        },
        map: map,
        packages: packages,
        defaultJSExtensions: false
    };

However, when i try to use read function, i get an error saying XLSX.read is not a function -  
html:    <input id="file2" (change)="changeListener($event)" type="file" ng2FileSelect [uploader]="uploader" />
component code:
var xlsx = require('xlsx');
changeListener($event): void {
        this.readThis($event.target);
    }

 readThis(inputValue: any): void {
        var file: File = inputValue.files[0];
        var myReader: FileReader = new FileReader();
          myReader.onload = function(e) {
            var data = myReader.result;
            var workbook = xlsx.read(data, { type: "binary" });
            console.log(workbook);
        }
        myReader.readAsBinaryString(file);
}

**Comment by mg9313** [comment]
When I try to see what xlsx object is - Chrome just shows it as "xlsx = function JSZip(data,options) {if(!this instanceof JSZip)) return new JSZip(data, options)..." - is this the possible reason ? seems like xlsx is not getting loaded. I tried replacing "var xlsx = require('xlsx');" with "import * as xlsx from 'xlsx';" but same behaviour!

**Comment by mg9313** [comment]
Just wanted to provide an update if anyone else faces similar issue: I updated my tsconfig.json to replace "es2015" with "es2016" under "compilerOptions"/"lib" property and this error is resolved. Strange enough - "compilerOptions"/"target" property is still "es5" (targetting to "es6" introduces other issues when app is launched in IE11)

**Comment by SheetJSDev** [comment]
@mg9313 We omitted the html version of the test in the repo!

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.20.16/system.js"></script>
<script>
	SystemJS.config({
		meta: {
			'xlsx': {
				exports: 'XLSX'
			}
		},
		map: {
			'xlsx': 'xlsx.full.min.js',
			'fs': '',
			'crypto': '', 
			'stream': ''
		}
	});
  SystemJS.import('main.js');
</script>
```

If you are using TS, https://github.com/SheetJS/js-xlsx/blob/master/demos/angular2/tsconfig.json is the config we use in the [angular2/4 demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2)

**Comment by muskan21** [comment]
Same issue.
Using loopback 2.22.0

**Comment by SheetJSDev** [comment]
@muskan21 @mg9313 can you share a small project demonstrating this?

**Comment by muskan21** [comment]
I figured it out.. In loopback, it was xlsx.parse not read.. For some reason.

**Comment by reviewher** [comment]
@mg9313 the angular2 demo uses that setting in [`tsconfig.json`](https://github.com/SheetJS/js-xlsx/blob/master/demos/angular2/tsconfig.json#L16), which is probably why it wasn't obvious initially.  That sounds like a TS issue.

@muskan21 cheers!
