### ISSUE TITLE
Convert HTML to Excel

### ISSUE THREAD

**Issue by sangpuion** [SheetJS/js-xlsx#748]
When convert HTML table to Excel, is there any way to force all output as string?

		var wopts = { bookType: type, bookSST: false, type: 'binary' },
			wb = {
				SheetNames: [],
				Sheets: {}
			},
			fname = (String(fn).replace(/\W/g, "") || 'Report.').substring(0,25) + "." + type,
			ws = XLSX.utils.table_to_sheet(document.getElementById(newId));

			wb.SheetNames.push(fname);
			wb.Sheets[fname] = ws;
			wbout = XLSX.write(wb, wopts);

By default, the leading zero for code was trimmed upon export.
Also, number field with "," was considered as string where same data piece less than 1000 was considered as number.  The output is annoying.

Any suggestion?
Thanks.

**Comment by SheetJSDev** [comment]
@sangpuion the option `raw:true` should be passing the raw strings, but it currently isn't.  The equivalent for CSV was added in https://github.com/SheetJS/js-xlsx/pull/722 and a similar change would have to be made in https://github.com/SheetJS/js-xlsx/blob/master/bits/79_html.js#L133

**Comment by medeirosjoaquim** [comment]
> When convert HTML table to Excel, is there any way to force all output as string?
> 
> ```
> 	var wopts = { bookType: type, bookSST: false, type: 'binary' },
> 		wb = {
> 			SheetNames: [],
> 			Sheets: {}
> 		},
> 		fname = (String(fn).replace(/\W/g, "") || 'Report.').substring(0,25) + "." + type,
> 		ws = XLSX.utils.table_to_sheet(document.getElementById(newId));
> 
> 		wb.SheetNames.push(fname);
> 		wb.Sheets[fname] = ws;
> 		wbout = XLSX.write(wb, wopts);
> ```
> 
> By default, the leading zero for code was trimmed upon export.
> Also, number field with "," was considered as string where same data piece less than 1000 was considered as number. The output is annoying.
> 
> Any suggestion?
> Thanks.

Use Sheet instead of WorkSheet. Like: 

```
 const worksheet: XLSX.Sheet = XLSX.utils.table_to_sheet(this.table.nativeElement, {raw: true});
```
