### ISSUE TITLE
saveAs in Meteor demo causes an error "Exception in delivering result of invoking 'download': "

### ISSUE THREAD

**Issue by NorthDecoder** [SheetJS/js-xlsx#751]
While testing with Firefox browser v54.0.1, in the meteor demo on line 39 of client/main.js [:link:](https://github.com/SheetJS/js-xlsx/blob/master/demos/meteor/client/main.js#L39) the saveAs call is causing an error, because it seems to be undefined.

If I add to file `package.json` dependencies:
    `    "file-saver": "1.3.3" `

and add somewhere near to the top of the file `main.js`:
` const FILESAVER = require('file-saver'); `

then change at line 39 of `main.js`
    from: ` saveAs( `
    to:     ` FILESAVER.saveAs(... `

The errors go away and the file save as dialog appears as expected.

**Comment by SheetJSDev** [comment]
The [Makefile for the demo](https://github.com/SheetJS/js-xlsx/blob/master/demos/meteor/Makefile#L8) installs the [`pfafman:filesaver` wrapper](https://atmospherejs.com/pfafman/filesaver).  Can you try the following steps from a fresh clone of the repo and see if you still see the error:

```bash
cd demos/meteor
meteor create .
npm install babel-runtime meteor-node-stubs xlsx
meteor add pfafman:filesaver
meteor
```

Not too familiar with meteor, but assumably `meteor add` performs some magic.

Those lines probably should be mentioned in the README (PR welcome :)
