### ISSUE TITLE
Other way to export xls file ?

### ISSUE THREAD

**Issue by BenBenz** [SheetJS/js-xlsx#752]
There is another way to export xls file ? I need to create a file with parse server,

If we can have a string with all xls file this is great

**Comment by reviewher** [comment]
The `write` function accepts [a `type` argument](https://docs.sheetjs.com/#output-type) and one of the output types is `"base64"`.  That returns a base64 string.

For example:

```js
/* make a workbook */
var data = [["a","b","c"],[1,2,3],[4,5,6]];
var ws = XLSX.utils.aoa_to_sheet(data);
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Test1");

/* generate base64 string */
var out = XLSX.write(wb, {type:'base64'});
```

If you want to read it back, the `read` function takes the same type argument:

```js
var new_wb = XLSX.read(base64string, {type:'base64'});
```
