### ISSUE TITLE
XLSX parsing

### ISSUE THREAD

**Issue by louiepiol** [SheetJS/js-xlsx#753]
Question about parsing a excel file.
Can I get the value of a cell through a loop by column cell.
`A1 + 14 = O1`
A1 has 13 column difference to O1.

> var workbook = XLSX.read(data, { type: 'binary' });
> var worksheet = workbook.Sheets['Sheetname'];
> var value = worksheet['A1'...'O1'];

Is there any way to make it possible?

**Comment by harmon25** [comment]
Could decode and reencode a cell to do this...
```js
let A1 = XLSX.utils.decode_cell("A1");
let O1 = XLSX.utils.encode_cell({ c: A1.c + 14, r: A1.r });
console.log(O1); // "O1"

```

**Comment by reviewher** [comment]
@louiepiol you have to manually expand the range.  In this case, you can do something like:

```js
var range_string = "A1:O1";
var range = XLSX.utils.decode_range(range_string);
for(var C = range.s.c; C <= range.e.c; ++C) {
  var addr = {r:0, c:C}; // row and col are 0-indexed, so r:0 is Row 1 
  var addr_str = XLSX.utils.encode_cell(addr);
  var cell = worksheet[addr_str];
  // do something with cell here
}
```
