### ISSUE TITLE
sheet_to_csv utility method doesn't respect hidden columns

### ISSUE THREAD

**Issue by the-spyke** [SheetJS/js-xlsx#755]
If sheet object contains hidden columns, I should not find them in the output of `csv`.

**Comment by SheetJSDev** [comment]
Both Excel 2013 and Excel 2016 export hidden rows and columns in CSV (to test this, make a new file, set each cell in the range A1:C3, then hide column B and row 2 and save as CSV).  It would probably make more sense to add that as an `hidden` option to the writer, keeping the default consistent with Excel.
