### ISSUE TITLE
Convert xlsx to JSON offline without hosting file

### ISSUE THREAD

**Issue by Joselz** [SheetJS/js-xlsx#762]
Hello! 
In my project im using the browser to print a table with data from an Excel file. The aplication will not be used in the network, I have a shared hard Drive and I was trying to develop this only by reading the file without the need to host it. I try to use XLSX.readFile() to do that but I am having some trouble because it looks like I have to use nodejs. 
Is it possible to use js-xlsx for doing that or do i have any other alternative?
Thanks!

**Comment by SheetJSDev** [comment]
XLSX.readFile is intended for nodejs only.  Browsers have no ability to proactively read from the local filesystem (security reasons).  You can add an input file element like in http://oss.sheetjs.com/js-xlsx/ but you can't use readFile in the browser.
