### ISSUE TITLE
Angular 1

### ISSUE THREAD

**Issue by jwamsley** [SheetJS/js-xlsx#770]
In the demo for Angular 1, it states:
> Strictly speaking, there should be no need for an angular demo! You can proceed as you would with any other browser-friendly library.

But how would you add this to an angular 1 app? In addition to installing with npm, I added: `<script src="xlsx.full.min.js"></script>` to my my index.html. My IDE now autocompletes the utility functions, but `grunt serve` still states ` error  'XLSX' is not defined  no-undef`

**Comment by SheetJSDev** [comment]
If you installed with NPM, you probably need to point to the correct location of the dist file, which would be something like `node_modules/xlsx/dist/xlsx.full.min.js`.

Upon reflection, it looks like we forgot to upload the HTML file in the angular demo.  All it does is use a script tag.  We will add it shortly.

**Comment by jwamsley** [comment]
@SheetJSDev  I have `<script src="bower_components/js-xlsx/dist/xlsx.full.min.js"></script>`. I was mostly curious if i needed to add any dependencies in the controller too. For instance, are the angular-ui-grid dependencies require for js-xlsx?

**Comment by SheetJSDev** [comment]
No those are for the demo only (which integrates with ui grid). The raw library is usable as-is with no additional dependencies.

**Comment by jwamsley** [comment]
@SheetJSDev I guess it was being deleted from my index.html every time the server reloaded, but it works now. Thanks.
