### ISSUE TITLE
Is it possible to have custom column on json_to_sheet?

### ISSUE THREAD

**Issue by enniob** [SheetJS/js-xlsx#771]
I want to add custom columns and not use the default object column name. Is this possible to do it?

**Comment by SheetJSDev** [comment]
If you want to change the order, set the `header` option to an array of the keys:

```js
var data = [{abc:1,def:2}];
/* force the order def, abc */
var ws = XLSX.utils.json_to_sheet(data, {header:['def','abc']});
/* force the order abc, def */
var ws = XLSX.utils.json_to_sheet(data, {header:['abc','def']});
```

The keys are written to the first row of the resulting worksheet, so if the order is correct you can set the first row values.  For example, to rename the first column to be "ABC":

```js
var data = [{abc:1,def:2}];
/* force the order abc, def */
var ws = XLSX.utils.json_to_sheet(data, {header:['abc','def']});
/* The first column header is stored in cell A1  */
var cell = ws['A1'];
/* To assign a new value, set the `v` key and clobber the old formatted text */
delete ws['A1'].w; ws['A1'].v = "ABC";
```

Just noticed [the documentation does not describe the options](https://docs.sheetjs.com/#array-of-objects-input), will update shortly.

**Comment by enniob** [comment]
When I do this I get the following error
`var ws = XLSX.utils.json_to_sheet(data, {header:['def','abc']});`

ERROR in C:/myapp/angular/src/app/topics-view/topics-view.component.ts (590,64): Argument of type '{ header: string[]
; }' is not assignable to parameter of type 'JSON2SheetOpts'.
  Object literal may only specify known properties, and 'header' does not exist in type 'JSON2SheetOpts'

**Comment by SheetJSDev** [comment]
The type definition is missing, it will show up in the next update

**Comment by rajuyadav-orchestratec** [comment]
Hi all,
How I can get data in the following format

Employee Details

Emp Name       Emp Sal
xyz                    1000
abc                    2000

Any help would be appreciated.

**Comment by sunny7899** [comment]
I also want to know how to format the above data @rajuyadav-orchestratec
