### ISSUE TITLE
Convert html to xlxs: numbers became date

### ISSUE THREAD

**Issue by sangpuion** [SheetJS/js-xlsx#772]
We are converting html table to xlxs/csv, for some data, the number became date.
For example, $41.08 was exported as "31-07-2041  4:00:00 PM"
Different combination of options have be tested:

var wopts = { bookType: type, bookSST: false, type: 'binary', raw: true, cellNF: true, cellDates : false, dateNF: 2}, 

Any suggestion?

**Comment by SheetJSDev** [comment]
We are pushing a change in the next release so that currencies and thousands-separated numbers are properly recognized as numbers.  IF you find any other strange cases, please let us know

**Comment by jyyan** [comment]
i just found that in case UTF-8 encoded, one ore more chinese & japanese character/string combine with one space and one number ending (ex. "漢 1" or "漢漢漢漢 123" or "あ 1") in a HTML table cell (ex `<td>あ 1</td>` ), will cause output as xlsx format error as Date format (such like `<c r="B2" s="1"><v>36892</v></c>`) 

but when i replace the space character in the HTML table with HTML special char **&amp;nbsp;** (ex. "漢漢漢漢**&amp;nbsp;**123") , it will export the right format as string cell.

i got the same issue in the [demo table](http://sheetjs.com/demos/table.html).

**Comment by SheetJSDev** [comment]
@jyyan that's coming from a combination of two problems:

1) V8 date parsing is extremely robust.  Try `new Date("absolute nonsense 1")` or `new Date("漢 1")` to see

2) The original correction rejected dates if it contained English letters that weren't part of a month name.  We're going to flip this to reject if any letters are detected.
