### ISSUE TITLE
Read a xlsx file protected with password

### ISSUE THREAD

**Issue by DaviD-Elbaze** [SheetJS/js-xlsx#774]
Hi.

I try to read a xlsx file protected with a password.
I use this syntax : 
`readFile('myfile.xlsx',{"password":'aaa'})`

but I receive this response:
`File is password-protected`

How can I fix this ?

Thanks

**Comment by shivamadhavan** [comment]
@SheetJSDev would be very useful to have this feature implemented. Are there any tentative timelines ?
Understanding your current thought process on how this could be implemented would be appreciated as well.

**Comment by ZackBarnes** [comment]
@SheetJSDev is this feature going to be implemented?

**Comment by SheetJSDev** [comment]
We're trying to tighten the scope of this project so that we can eventually reach a stable 1.0.0 version.  This may be implemented in the open source version at some point, but there are no plans at the moment.

**Comment by ytilis** [comment]
Why is this feature listed under "Parsing Options" in the documentation if it hasn't been implemented yet? This is very confusing for users looking to use this library for protected files.
https://docs.sheetjs.com/#parsing-options

**Comment by SheetJSDev** [comment]
There are quite a few formats @ytilis -- the library currently has code for the weak encryption used in older XLS files.  For modern XLS files and the XLSX/XLSB format, the password protection schemes are different (those are supported in the Pro encryption package).  In the push to 1.0 we're unlikely to add it to the Community version.

**Comment by ytilis** [comment]
I think that's perfectly understandable, but in that case, the error message returned needs to be clearer, because as it stands it makes it seem like a bug where it's not reading the provided password, rather than a limitation of the Community Edition in conjunction with the file version.

**Comment by mmurillo96** [comment]
Hello,
is this feature already implemented?
I wish i could be able to read a XLSX file protected by password!
If there is something that could be done to solve this please let me know

thks
