### ISSUE TITLE
table_to_sheet/book transforms blank cells to 0

### ISSUE THREAD

**Issue by domxa** [SheetJS/js-xlsx#779]
This also includes cells filled with only white spaces (e.g. '   ').

**Comment by the-spyke** [comment]
Yeah, I even have this code as temporary solution:
```
// Fix empty values parsed as number 0 by SheetJS just in case
if (cell.v === 0 && cell.w === "" && cell.t === "n") {
    cell.v = "";
    cell.t = "s";
}
```

**Comment by SheetJSDev** [comment]
Put the wrong number in the commit message :/ commit 2ea9c95839ddf439873d652a27e88e6ed0535013 resolves the issue by skipping blank cells.  There are new tests for the DOM methods (using JSDOM in nodejs and the standard facilities in the browser)

**Comment by domxa** [comment]
Thanks for the quick fix, I appreciate it!

**Comment by danxfisher** [comment]
@domxa Did this work for you in 0.11.4?  I am still seeing 0's where there should be blanks or white space.

**Comment by SheetJSDev** [comment]
@danxfisher can you share a fiddle? https://jsfiddle.net/0w8b1qry/ appears to work

<details><summary>Fiddle Code (click to show)</summary>

```js
/* external references:
 - https://unpkg.com/xlsx/dist/xlsx.full.min.js
 - https://rawgit.com/eligrey/FileSaver.js/master/FileSaver.js

HTML:
<table id="tableau">
<tr><td>The next cell is blank:</td><td></td><td>The previous cell is blank</td></tr>
</table>

<pre id="out"></pre>
*/

var wb = XLSX.utils.table_to_book(document.getElementById('tableau'));

document.getElementById('out').innerText = JSON.stringify(wb.Sheets.Sheet1, 2, 2);

/* write workbook (use type 'binary') */
var wbout = XLSX.write(wb, {bookType:'xlsx', type:'binary'});

/* generate a download */
function s2ab(s) {
	var buf = new ArrayBuffer(s.length);
	var view = new Uint8Array(buf);
	for (var i=0; i!=s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
	return buf;
}

saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), "sheetjs.xlsx");
```

</details>

**Comment by danxfisher** [comment]
@SheetJSDev Ah, I see what the issue is.  If the formatting doesn't have `<td></td>` on the same line but rather like this:
```
<td>

</td>
```

Then it will return 0.

Fiddle: https://jsfiddle.net/b3asc8jm/

**Comment by danxfisher** [comment]
@SheetJSDev Sorry to reply to this again but just wanted to clarify: Is my above comment by design or a bug?  If it's a bug, I'll create a separate issue so that this one can remain closed.  Otherwise I'll try and find a workaround for my tables being generated by EJS.  Thanks!

**Comment by SheetJSDev** [comment]
it's a bug, the uncertainty surrounded inconsistencies in how you get text data from a cell.  We're testing a new technique that we should be able to push out tonight.  No need to raise a new issue, although you can if you feel like :)

**Comment by danxfisher** [comment]
If there's no need, then there's no need! I am honestly baffled by the response time from the team--thanks for continuing to make everyone's life easier at such an incredible pace.

**Comment by SheetJSDev** [comment]
@danxfisher we suffer for the art :)
