### ISSUE TITLE
Read frozen panes / rows?

### ISSUE THREAD

**Issue by jasoncrawford** [SheetJS/js-xlsx#785]
When reading a file, is there a way to get information about how many rows are frozen at the top, and/or columns frozen at the left? I believe this is called “freeze panes” in spreadsheet terminology. I would expect this to be in the meta properties for each sheet, but I don't see it, and I can't find any reference to this in the README. Thanks!

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by AppWerft** [comment]
export default function countEBMandICDs(data) {
   

    // Funktion zum Zählen der Werte
    const countOccurrences = (obj, key) => {
        obj[key] = (obj[key] || 0) + 1;
    };

    // Zähler für GOPs und Diagnosen
    const gopCounter = {};
    const diagCounter = {};

    // Daten durchlaufen und Werte sammeln
    data.patienten.forEach(({ besuche }) => {
        besuche.forEach(({ diagnosen, gops }) => {
            gops.forEach(gop => countOccurrences(gopCounter, gop));
            diagnosen.forEach(diagnose => {
                const key = diagnose.split(".")[0]; // Nur den Teil vor dem Punkt nehmen
                countOccurrences(diagCounter, key);
            });
        });
    });

    // Absteigend nach Häufigkeit sortieren
    const sortDescending = obj =>
        Object.fromEntries(Object.entries(obj).sort((a, b) => b[1] - a[1]));

    return {
        gops: sortDescending(gopCounter),  
        diags: sortDescending(diagCounter) 
    };
}


Hier brauche ich die 100 häufigsten GOP und 100 häufigsten ICDS
