### ISSUE TITLE
Excel size increase

### ISSUE THREAD

**Issue by jlameiro87** [SheetJS/js-xlsx#787]
I'm testing with an Excel as template, read a mongoDb looking for items to add into Excel, when I write the Excel it increase size up to 6 mg, but the template i'm using only have 800 kb, and the cells number i'm writing for the reading to db, only have 6 rows.
The code i'm using is:

var wb = XLSX.readFile('C://myTemplateFile.xlsx', { type: 'binary', cellStyles: true, cellNF: true, cellDates: true });
for (var i = 0; i < items.length; i++) {
//Add items to base template
}
var wopts = { bookType: 'xlsx', type: 'binary', cellStyles: true, cellNF: true, cellDates: true };
XLSX.writeFile(wb, 'C://myTemplateFile_out.xlsx', wopts);

**Comment by reviewher** [comment]
Set [`compression` option](https://docs.sheetjs.com/#writing-options)

**Comment by jlameiro87** [comment]
According to official documentation site: https://www.npmjs.com/package/xlsx
compression, only applies to formats with ZIP containers.
But I want generate and .xlsx file not .zip file

**Comment by reviewher** [comment]
https://www.npmjs.com/package/xlsx#supported-output-formats 

XLSX, XLSM, XLSB, and ODS are zip-based formats.  You can rename an XLSX file to .zip and extract!

**Comment by jlameiro87** [comment]
Still remain the generated excel file much more bigger than the original one
Original file size: 848 KB.
// Without styles
var wb = XLSX.readFile('C://myOriginalFile.xlsx', { type: 'binary' });
var wopts = { bookType: 'xlsx', type: 'binary', compression: true };
XLSX.writeFile(wb, 'C://myModifiedFile.xlsx', wopts);

After read and write xlx file it increase up to: 3616 KB

if I want to keep the excel cells styles the file increase up to: 5617 KB
var wb = XLSX.readFile('C://myOriginalFile.xlsx', { type: 'binary', cellStyles: true, cellNF: true, cellDates: true });
var wopts = { bookType: 'xlsx', type: 'binary', cellStyles: true, cellNF: true, cellDates: true, compression: true };
XLSX.writeFile(wb, 'C://myModifiedFile.xlsx', wopts);

Using the parameter compression: true, I get the same values in file size.

**Comment by jlameiro87** [comment]
Remark that only read and write the excel file in another file, increase the size

**Comment by yishengtanxi** [comment]
I has the same issue.Has this problem been solved? @jlameiro87
