### ISSUE TITLE
Property 'book_new' does not exist on type 'IUtils'.

### ISSUE THREAD

**Issue by claudiadonea4resilient** [SheetJS/js-xlsx#789]
Hello,

When I try to create a new workbook it cannot find 'book_new' (Property 'book_new' does not exist on type 'IUtils')
The function declaration appears in index.d.ts but is not exported in the utils object from xlsx.js

Is it possible to get access in order to manually create a new work book?  

Thanks in advance

**Comment by kernkonzentrat** [comment]
@claudiadonea4resilient try to manually install the latest version of xlsx

`npm i xlsx@0.11.3 --save`

if you fetch the lib without the version it currently installs v0.8.*

**Comment by reviewher** [comment]
@claudiadonea4resilient `IUtils` is not part of the [official definitions](https://github.com/SheetJS/js-xlsx/blob/master/types/index.d.ts).

You probably have a copy of `ts-xlsx` or `@types/xlsx` hanging around -- try removing them if you have them installed and install `xlsx` directly.

**Comment by claudiadonea4resilient** [comment]
Thank you, it works just by installing xlsx@0.11.3
