### ISSUE TITLE
How to auto adjusted columns (auto wrap) in excel exported files in angular4?

### ISSUE THREAD

**Issue by Sandeepvedam** [SheetJS/js-xlsx#790]
Hi,

I have JSON array and i am able to export as excel files in angular4. It doesn't have autowrap text in exported file? How to do this in angular4. Is it possible through js-xlsx?

Thanks,
Sandeep.

**Comment by SheetJSDev** [comment]
Unfortunately Excel stores the text wrapping attributes as part of the cell styles, part of our [Pro offering](https://sheetjs.com/pro)
