### ISSUE TITLE
Can't insert more than one image in sheet

### ISSUE THREAD

**Issue by jitendra-rsi** [SheetJS/js-xlsx#795]
ws["!images"] = [];
		$.each(images, function(index, image){						
			ws["!images"].push({
		  	name: 'image' + index + '.png',
		    data: image.imageData,
		    opts: {base64: true},
		    type: "png",
		    position: {
		      type: 'twoCellAnchor',
		      attrs: {editAs: 'oneCell'},
		      from: {col: image.c, row: image.r},
		      to: {col: image.c + 1, row: image.r + 1}
		    }
		  });
		});

**Comment by jitendra-rsi** [comment]
Hi ,
when inserting multiple image it's repeating first image

**Comment by krishnakommuri** [comment]
replace rId with for loop i value 
   function write_drawing(images, rId) {
        var o = [];
        o[o.length] = (XML_HEADER);
        o[o.length] = (DRAW_ROOT);

        for (var i = 0; i < images.length; i++) {
            var image = images[i];
            var pos = image.position || {};
            if (pos.type === 'twoCellAnchor') {
                var from = pos.from || {}, to = pos.to || {},
                    fromCol = from.col || 0, toCol = to.col || 0,
                    fromRow = from.row || 0, toRow = to.row || 0;

                var twoCell = '<xdr:from><xdr:col>' + fromCol + '</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>' + fromRow + '</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from>';
                twoCell += '<xdr:to><xdr:col>' + toCol + '</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>' + toRow + '</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to>';
                twoCell += '<xdr:pic><xdr:nvPicPr><xdr:cNvPr id="' + (i+1) + '" name="' + image.name + '">';
                twoCell += '</xdr:cNvPr><xdr:cNvPicPr><a:picLocks noChangeAspect="1"/></xdr:cNvPicPr></xdr:nvPicPr>';
                twoCell += '<xdr:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="rId' + (i+1) + '"/>';
                twoCell += '<a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/>';
                o[o.length] = (writextag('xdr:twoCellAnchor', twoCell, images[i].attrs));
            }
        }

        if (o.length > 2) {
            o[o.length] = ('</xdr:wsDr>');
            o[1] = o[1].replace("/>", ">");
        }
        return o.join("");
    }

**Comment by demotascha** [comment]
@krishnakommuri Thank you very much.

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

**Comment by lucasverra** [comment]
> replace rId with for loop i value
> function write_drawing(images, rId) {
> var o = [];
> o[o.length] = (XML_HEADER);
> o[o.length] = (DRAW_ROOT);
> 
> ```
>     for (var i = 0; i < images.length; i++) {
>         var image = images[i];
>         var pos = image.position || {};
>         if (pos.type === 'twoCellAnchor') {
>             var from = pos.from || {}, to = pos.to || {},
>                 fromCol = from.col || 0, toCol = to.col || 0,
>                 fromRow = from.row || 0, toRow = to.row || 0;
> 
>             var twoCell = '<xdr:from><xdr:col>' + fromCol + '</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>' + fromRow + '</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:from>';
>             twoCell += '<xdr:to><xdr:col>' + toCol + '</xdr:col><xdr:colOff>0</xdr:colOff><xdr:row>' + toRow + '</xdr:row><xdr:rowOff>0</xdr:rowOff></xdr:to>';
>             twoCell += '<xdr:pic><xdr:nvPicPr><xdr:cNvPr id="' + (i+1) + '" name="' + image.name + '">';
>             twoCell += '</xdr:cNvPr><xdr:cNvPicPr><a:picLocks noChangeAspect="1"/></xdr:cNvPicPr></xdr:nvPicPr>';
>             twoCell += '<xdr:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="rId' + (i+1) + '"/>';
>             twoCell += '<a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/>';
>             o[o.length] = (writextag('xdr:twoCellAnchor', twoCell, images[i].attrs));
>         }
>     }
> 
>     if (o.length > 2) {
>         o[o.length] = ('</xdr:wsDr>');
>         o[1] = o[1].replace("/>", ">");
>     }
>     return o.join("");
> }
> ```


@krishnakommuri can i contact you for advice on implementation ?

**Comment by krishnakommuri** [comment]
Hi Verra,

     I don't have much knowledge on this one. One of the client we had requirement so used this sheetjs and just edited that line of code.

Thanks,
Krishna

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
