### ISSUE TITLE
convert xls to xlsm

### ISSUE THREAD

**Issue by 271bibi** [SheetJS/js-xlsx#796]
Hi, how do I save a xls file in xlsm format? Thanks!

**Comment by reviewher** [comment]
Open the XLS file and write as XLSM.  The docs show how to [open XLS files](https://docs.sheetjs.com/#parsing-workbooks) and [write XLSM files](https://docs.sheetjs.com/#writing-workbooks).  NodeJS read/write example:

```js
var original_file = XLSX.readFile('test.xls');
XLSX.writeFile('test.xlsm');
```

**Comment by 271bibi** [comment]
Thanks, but if I do it the other way round (xlsm -> xls), I loose all my information..
