### ISSUE TITLE
writing xls file is crushed

### ISSUE THREAD

**Issue by didwjdcks** [SheetJS/js-xlsx#797]
I'm trying to write excel(xlsx, xls, csv)

xlsx, csv files write OK.

but writing xls file format is crushed

this is my code.

Please, help me.

```
if (booktype == 'xls')
    booktype = 'xlml';
var wopts = {
    bookType: booktype,
    bookSST: false,
    type: 'binary',
    cellStyles: 'true'
};
if (booktype == 'xlml')
    booktype = 'xls';

var wbout = XLSX.write(wb, wopts);

saveAs(new Blob([this.__s2ab(wbout)], {
     type: "application/octet-stream"
}), "table_to_excel." + booktype);
```

**Comment by SheetJSDev** [comment]
Can you update to the latest version and test?  If that is not working, please share the full workbook object you are trying to write (run `console.log(JSON.stringify(wb))` and share the result)
