### ISSUE TITLE
Need help modifying range of a cell

### ISSUE THREAD

**Issue by riv3n** [SheetJS/js-xlsx#799]
If I have a cell at A1, and I want to modify the range to A1:A7, how would I accomplish this? I'm sorry if I missed something in the doc.

**Comment by reviewher** [comment]
Your question is really unclear.  What range do you want to modify?  Are you trying to "fill down" or change the workbook range or something else?

**Comment by riv3n** [comment]
Sorry, how do I merge cells A1:F1.

**Comment by reviewher** [comment]
No worries @riv3n, seems that isn't really discussed in the README.  The actual merge ranges are stored in an array `worksheet['!merges']`.  You have to set the upper-left cell in the range, as that is the cell that will be merged (the other addresses will be ignored).  Here's an example function to add a merge:

```js
function sheet_merge_range(worksheet, range) {
  if(! worksheet['!merges']) worksheet['!merges'] = [];
  worksheet['!merges'].push(XLSX.utils.decode_range(range));
}

sheet_merge_range(worksheet, "A1:F1");
```

If you want to see a more complete example, open these files in Excel and also try reading the files with the library to see the representation:

- https://github.com/SheetJS/test_files/blob/master/merge_cells.ods?raw=true
- https://github.com/SheetJS/test_files/blob/master/merge_cells.xls?raw=true
- https://github.com/SheetJS/test_files/blob/master/merge_cells.xlsb?raw=true
- https://github.com/SheetJS/test_files/blob/master/merge_cells.xls.xml?raw=true

**Comment by riv3n** [comment]
How can I see the code that generated the files?

**Comment by tayfunyasar** [comment]
Can I also see? :)
