### ISSUE TITLE
Please help me modify this worksheet

### ISSUE THREAD

**Issue by riv3n** [SheetJS/js-xlsx#800]
![screen shot 2017-09-01 at 8 45 54 pm](https://user-images.githubusercontent.com/10247894/29991525-a10ec1ba-8f56-11e7-8dca-84377a6541c1.png)

I'm copying this workbook and I would like to start filling in the rows starting at A4. How do I accomplish this?

**Comment by scholar-ink** [comment]
How to implement cell style？

**Comment by SheetJSDev** [comment]
This is supported now using [`sheet_add_aoa` and `sheet_add_json` with `origin:-1`](https://docs.sheetjs.com/#array-of-arrays-input)
