### ISSUE TITLE
Can I use this library with ReactNative on android?

### ISSUE THREAD

**Issue by DanDance** [SheetJS/js-xlsx#801]
I need to write  xls/xlsx files to android file system.

**Comment by SheetJSDev** [comment]
`XLSX.write(wb, {type:"base64"})` generates a base64 string.  You should be able to use a library like [react-native-fs](https://github.com/itinance/react-native-fs) to write the file using the base64 encoding.

**Comment by DanDance** [comment]
Thanks! I created base 64 as in your example and wrote file using [react-native-fs](https://github.com/itinance/react-native-fs)
`RNFS.RNFS.writeFile('file:///sdcard/Test/test.xlsx', file, 'base64')`

**Comment by SheetJSDev** [comment]
@DanDance glad to hear it worked! Out of curiosity, does `var file = XLSX.write(wb, {type:"binary"})` work with `RNFS.RNFS.writeFile('file:///sdcard/Test/test.xlsx', file, 'ascii')` ?

**Comment by DanDance** [comment]
@SheetJSDev 
Yes, 'ascii' also worked fine! Thank you very much
