### ISSUE TITLE
Unlock cells on protected sheet

### ISSUE THREAD

**Issue by wakeupgit** [SheetJS/js-xlsx#804]
Is it possible in that library to unlock some cells ?
When i create a file i need to unlock some cells(the second half of the columns) to be able to edit them when the sheet will be protected by the password so nobody can edit the rest of the cells(they all locked by default)
For now i can protect the whole sheet by the password but can't edit any of the cells
Can anybody tell me how to do it ?

**Comment by daggett206** [comment]
any updates?

**Comment by SheetJSDev** [comment]
Unfortunately Excel stores the locked / hidden attributes as part of the cell styles.  Cell-level protection along with other cell styles are part of our [Pro offering](https://sheetjs.com/pro)
