### ISSUE TITLE
Pro version?

### ISSUE THREAD

**Issue by lauantai** [SheetJS/js-xlsx#806]
Sorry for the off-topic, I'm trying to contact the SheetJS team via email to inquire about the Pro version but getting no response. Is there another way to contact?

**Comment by Kylir** [comment]
Same issue. I tried the email, the chat and twitter...

**Comment by lauantai** [comment]
Thanks for the info, @Kylir, I hope the author is fine!

**Comment by SheetJSDev** [comment]
@lauantai @Kylir We've been swamped the last few weeks as some of our teammates have been affected by recent weather events.  @lauantai I can't find a message from you in the inbox, please send directly to dev@sheetjs.com and reference this issue.

**Comment by lauantai** [comment]
Thanks, @SheetJSDev,  sent!

**Comment by BryanLi93** [comment]
@SheetJSDev Reply my email, plz... I need a full SHEETJS 🤓 🤓

**Comment by nightow85** [comment]
@SheetJSDev i also, reply my mail, too. want to pro sheetjs

**Comment by CarlosJimenez** [comment]
@SheetJSDev i also, reply my mail, too. want to pro sheetjs

**Comment by bill-griffin-aimia** [comment]
Has anybody on this thread heard from @SheetJSDev ?
It would be useful to have more information available about SheetJS Pro.

**Comment by nkev** [comment]
@SheetJSDev Since you are not easily contactable, can you at least publish basic information about your sheetjs pro product [on your website](http://sheetjs.com/pro), like price, license terms, etc?

**Comment by ismarf9** [comment]
Hi @SheetJSDev i wanna get the pro version, i sent a email but not reply yet, can you help me? this is my email: ismarf9@gmail.com

**Comment by MercusChan** [comment]
@SheetJSDev 
Please also send me the pro version.

**Comment by raudabaugh** [comment]
My company is also interested in a license.

**Comment by tsingyee** [comment]
@SheetJSDev I have also sent an email for pricing.

**Comment by CarlosJimenez** [comment]
I didn’t receive prices.
Only a PDF with features

Please, could you be so kind to resend the prices to me?

Thanks a lot
Carlos

**Comment by RyanSMurphyDMCo** [comment]
This is crazy. They must be loosing a high % of potential revenue by being so unresponsive

**Comment by notchris** [comment]
Have you used the contact information on the website? I've generally received a response within 24 hours if not within a couple hours.

**Comment by raudabaugh** [comment]
Our company sent an email to pro@sheetjs.com back in early November and got no reply. In the meantime, we've been able to develop our project with ExcelJS (github.com/raudabaugh/exceljs) pretty successfully. Mainly, we just needed to insert images into cells, which ExcelJS does for free. Highly recommend if anyone is looking for something similar.

**Comment by SheetJSDev** [comment]
@RyanSMurphyDMCo @raudabaugh no emails from either of you show up in the inbox.  If you sent from a nondescript gmail / yahoo / hotmail / 163.com address it may have been marked as spam
