### ISSUE TITLE
Simple Two Dimensional Representation

### ISSUE THREAD

**Issue by hdon** [SheetJS/js-xlsx#807]
For my purposes, CSV is the most convenient format, but my users keep giving me XLSX spreadsheets with all kinds of ad hoc conventions for organizing their data.

js-xlsx gets me much closer to my goal by allowing me to parse these different spreadsheet formats.

However, there doesn't seem to be a simple means of accessing spreadsheet data in a two dimensional representation.

Each sheet has properties like `A1` and `J5` which I assume identifies individual cells in the sheet, but is still pretty remote from the representation I seek.

For anyone else looking for such a solution, one possible solution is below.

Maybe something to add to the library?

```javascript
const filename = 'whatever.xlsx';
const _=require('lodash')
const col2int = col => _.map(col, (c,i) => {let p=col.length-i-1; return (c.charCodeAt(0)-65+1) * (26**p) }).reduce((a,b)=>a+b)-1;
const pos2vec = pos => { pos=pos.match(/^([A-Z]+)([0-9]+)$/); return pos && [Number(pos[2]), col2int(pos[1])] }
const f = require('xlsx').readFile(filename)
const sheets = _.mapValues(f.Sheets, inputSheetData => {
  const out = [];
  _.each(inputSheetData, (cell, pos_) => {
    console.log(pos_, cell.v, pos2vec(pos_))
    const pos = pos2vec(pos_);
    if (!pos) return;
    const row = (out[pos[0]] || (out[pos[0]] = []));
    row[pos[1]] = cell.v;
  })
  return out
})  
```

**Comment by SheetJSDev** [comment]
https://docs.sheetjs.com/#utilities

- `col2int` is already available as `XLSX.utils.decode_col` 
- `pos2vec` is similar to `XLSX.utils.decode_cell`

https://docs.sheetjs.com/#json

- `sheets` can be replicated with `sheet_to_json` with header `"1"`:

```js
const sheets = _.mapValues(f.Sheets, ws => XLSX.utils.sheet_to_json(ws, {header:1}))
```

The fact that this is not immediately obvious means there's something missing in the documentation.  What needs to be clarified?

**Comment by hdon** [comment]
`sheet_to_json` is a little counterintuitive as JSON is a serialization format. Neither the name nor the mentions on the README really make it clear that it also reshapes the data into a two dimensional representation.

The other functions you commented on are nice to know about, but from your comment, it looks like I really only need `sheet_2_json`.

Thanks :)
