### ISSUE TITLE
How to select file save path when export a file?

### ISSUE THREAD

**Issue by yueyesuifeng** [SheetJS/js-xlsx#808]

**Comment by SheetJSDev** [comment]
Browsers in general don't have a standard way for showing the "Save as" window.  For IE, there is a function [`msSaveOrOpenBlob`](https://msdn.microsoft.com/en-us/library/hh772332.aspx), but none of the other browsers have a good way of triggering that window.

That being said, to specify the file name, [`XLSX.writeFile`](https://github.com/SheetJS/js-xlsx#writing-functions) in node accepts a filename argument.  In the browser, there are techniques like URL.createObjectURL that have configurable filename.  The demos generally use the [`filesaver.js`](https://github.com/eligrey/filesaver.js) wrapper and it takes a filename (see the ["Browser download file" code sample](https://github.com/SheetJS/js-xlsx#writing-workbooks))
