### ISSUE TITLE
How to get the content of a cell without the leading and trailing double quote (text qualifiers)

### ISSUE THREAD

**Issue by kdeclerck** [SheetJS/js-xlsx#809]
I am using XSLX.read with the raw option set to true (to avoid any parsing) to read a .csv file. This results in the content of cells still being enclosed in double quotes if the values in the .csv file were enclosed with double quotes (text qualifiers). 

Am i missing an option to trim these double quotes? I see that using raw: false gets rid of these quotes but this also results in unwanted parsing... Cell values like "Street 35" for example then will be parsed as numbers/dates giving me weird results. Can you suggest the correct way to deal with this situation please?

Thanks!

**Comment by SheetJSDev** [comment]
That's a whole can of worms (isn't string parsing counted as parsing?) but the particular case of "Street 35" should have been resolved in 0.11.4:

```
> require('xlsx').read("Street 35,Street 36", {type:"binary"}).Sheets.Sheet1
{ A1: { t: 's', v: 'Street 35' },
  B1: { t: 's', v: 'Street 36' },
  '!ref': 'A1:B1' }
```
