### ISSUE TITLE
 column type

### ISSUE THREAD

**Issue by mohamed-hendawy** [SheetJS/js-xlsx#810]
how  can i make column type  string or boolean only ?

**Comment by reviewher** [comment]
Excel doesn't really have a "column type" like a database value type.  To set a specific cell to be a boolean, set the cell type to `b` and the value to `true` or `false`.  String cells have type `s`:

```js
var true_cell = {t:'b', v:true};
var false_cell = {t:'b', v:false};
var hello = {t:'s', v:'Hello!'};
```

**Comment by mohamed-hendawy** [comment]
I export excel to user to insert data (string in column and bool in other ) and i don't know how many rows user insert to use your solution !

you can change the column type in excel sheet by right click on column name and change col type to string , bool , number ..etc i need to this using xlsx any idea ?

**Comment by Vinoth-LearningThings** [comment]
> I export excel to user to insert data (string in column and bool in other ) and i don't know how many rows user insert to use your solution !
> 
> you can change the column type in excel sheet by right click on column name and change col type to string , bool , number ..etc i need to this using xlsx any idea ?

Did you get any solution for the above problem ?

**Comment by mohamed-hendawy** [comment]
Unfortunately i didn't complete search.
