### ISSUE TITLE
function write_num_flt() not handling certain decimal numbers properly

### ISSUE THREAD

**Issue by NikunjPatel90** [SheetJS/js-xlsx#816]
I am trying to read excel file having amount in one of the columns, it needs to be rounded to 2 decimal places. It fails when rounding certain values after decimal point(e.g. .999345). For example 56.9999456 becomes 56.10 instead of 57.00. 

After debugging the issue, I have found the reason for this strange behavior.

faulty code: 
if((r = fmt.match(/^#,##0\.([#0]*0)$/)) !== null) {
		return val < 0 ? "-" + write_num_flt(type, fmt, -val) : commaify(""+(Math.floor(val))) + "." + pad0(dec(val, r[1].length),r[1].length);
	}

Here, function dec() returns 100 and it results in "56" + "." + "10". I believe, the code should be handling this specific scenario.

**Comment by reviewher** [comment]
This was fixed a while ago, you should use the current version.

FWIW The number formatting logic can be tested in the project page http://oss.sheetjs.com/ssf/ :

<img width="492" alt="screen shot 2017-09-22 at 15 02 21" src="https://user-images.githubusercontent.com/24845478/30760196-38b2cd8a-9fa7-11e7-93cd-d4bcbee17b3a.png">
