### ISSUE TITLE
In react, the FS module cannot be loaded

### ISSUE THREAD

**Issue by Kunoky** [SheetJS/js-xlsx#818]
```js
import React from 'react';
import { connect } from 'dva';
import styles from './IndexPage.css';
import * as XLSX from 'xlsx';

function IndexPage() {
  const workbook = XLSX.readFile('./test.xlsx');
  console.log(workbook);

  return (
    <div className={styles.normal}>

    </div>
  );
}

IndexPage.propTypes = {
};

export default connect()(IndexPage);
```

```
=========================================================

660:189 TypeError: _fs.readFileSync is not a function
    at readSync (963:17961)
    at Object.readFileSync (963:17983)
    at IndexPage (825:44)
    at eval (574:305)
    at measureLifeCyclePerf (574:75)
    at ReactCompositeComponentWrapper._constructComponentWithoutOwner (574:304)
    at ReactCompositeComponentWrapper._constructComponent (574:279)
    at ReactCompositeComponentWrapper.mountComponent (574:187)
    at Object.mountComponent (67:45)
    at ReactCompositeComponentWrapper.performInitialMount (574:370)
```

**Comment by SheetJSDev** [comment]
`readFile` and `writeFile` are only available in nodejs.  That's apparently missing in the docs, we'll add a comment.  You need to get the data into your app somehow (either downloading the file or attaching to a file input element).  https://github.com/SheetJS/js-xlsx/blob/master/demos/react/sheetjs.jsx shows how to interact with a file element. 
 http://embed.plnkr.co/o2QCB0MgrnxYou50hDXU/ is the code copied to a `plnkr`

**Comment by Kunoky** [comment]
Thank you very much. It's a solution. But it destroys the original project structure and hopes to have other solutions.

**Comment by SheetJSDev** [comment]
For obvious security reasons it's not possible for a webpage to proactively request a file from the client system -- the user has to submit the file through an input file element or drag-and-drop.  This is a hard limitation until browser vendors decide to add support.

**Comment by Kunoky** [comment]
OK, thanks again!
