### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by jesah** [SheetJS/js-xlsx#819]
When formatting date it should never use only two digits in year. Take a look at init_table. 
When reading a Excel it parses date and representate "2014-05-06" as 06/05/14. That date will IE say it is 1914-05-06 and Chrome something else.

**Comment by SheetJSDev** [comment]
What you are seeing is Excel's default behavior.  When you type `2014-05-06` in cell A1, Excel interprets the value as a date and renders in the current locale, which is `5/6/14` for English (United States):

<img width="144" alt="" src="https://user-images.githubusercontent.com/6070939/30877889-24030d30-a2c9-11e7-89f3-1a86dd9a59da.png">

To force a cell to display the specific format, as in the case of cell D2 in the picture, you either have to pass it as a literal string or set the cell format to `yyyy-mm-dd`.  Here's a fiddle: https://jsfiddle.net/67hnjuro/

<details>
<summary><b>Fiddle Code</b> (click to show)</summary>

```js
/* see https://github.com/SheetJS/js-xlsx/issues/819 */
/* original date string */
var datestr = "2014-05-06"

/* generate the date in local time */
var dateobj = new Date(datestr);
dateobj.setTime(dateobj.getTime() + (new Date()).getTimezoneOffset() * 60000);

/* make the worksheet */
var ws = {
	'!ref': "A1:A2",
	'A1': { t:"s", v:datestr }, // <-- literal string '2014-05-06
  "A2": { t:"d", v:dateobj, z:"yyyy-mm-dd" }  // <-- date
};


/* add to workbook */
var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "Dates");

/* write workbook (use type 'binary') */
var wbout = XLSX.write(wb, {bookType:'xlsx', type:'binary'});

/* generate a download */
function s2ab(s) {
	var buf = new ArrayBuffer(s.length);
	var view = new Uint8Array(buf);
	for (var i=0; i!=s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
	return buf;
}

saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), "sheetjs.xlsx");
```

</details>

As for the IE issue of interpreting 2-digit years as if they were in the 1900s, we [correct for that when reading plaintext dates](https://github.com/SheetJS/js-xlsx/blob/master/bits/20_jsutils.js#L72)


If you are finding issues with IE date parsing, please share a test file and we can take a look.
