### ISSUE TITLE
injection file taken since bower

### ISSUE THREAD

**Issue by newmesiss** [SheetJS/js-xlsx#820]
Hi, I'm using gulp, this injects me by default core.min.js, in the documentation speaks that it should be full.min.js this is due to some definition problem in bower or gulp config?

**Comment by reviewher** [comment]
The `bower.json` [main file](https://github.com/SheetJS/js-xlsx/blob/master/bower.json#L4) should be fixed, but the full should be available anyway at `bower_components/js-xlsx/dist/xlsx.full.min.js`.

**Comment by SheetJSDev** [comment]
`bower.json` now points to the full version
