### ISSUE TITLE
SheetNames Issues Raised...

### ISSUE THREAD

**Issue by EthirajG** [SheetJS/js-xlsx#821]
Hi, i'm getting this error so i'm unable to convert excel to JSON Data
here is error name:
**0x800a138f - JavaScript runtime error: Unable to get property 'SheetNames' of undefined or null reference**

can you please send working code to my mail : - ethirajg@ho.netaccess-india.com

**Comment by reviewher** [comment]
test against the demos like http://oss.sheetjs.com/js-xlsx/ (reading) http://sheetjs.com/demos/table.html (writing).  If you see the same problem against those pages, please share a file and tell us what browser version you are using.

**Comment by EthirajG** [comment]
Dear Team,

                                HI, Ref : #821 in GitHub, I tried with your site source even i’m getting this error - 0x800a139e - JavaScript runtime error: Unsupported file 162|186|90|178

When convert as JSON through your site it convert fine but when i put in my development Framework 4.5 this issues has been facing, 

Please send any idea.

 

Here is my Code:

<!DOCTYPE HTML>

 

<HTML><HEAD><META />

content="IE=11.0000" http-equiv="X-UA-Compatible">

 

<META http-equiv="Content-Type" content="text/html; charset=UTF-8"> 

<TITLE>SheetJS Live Demo</TITLE> 

<STYLE>

#drop{

       border:2px dashed #bbb;

       -moz-border-radius:5px;

       -webkit-border-radius:5px;

       border-radius:5px;

       padding:25px;

       text-align:center;

       font:20pt bold,"Vollkorn";color:#bbb

}

#b64data{

       width:100%;

}

a { text-decoration: none }

</STYLE>

 

<META name="GENERATOR" content="MSHTML 11.00.9600.18792"></HEAD> 

<BODY>

<PRE>

Output Format: <SELECT name="format" onchange="setfmt()">

<OPTION value="csv" selected=""> CSV</OPTION>

<OPTION value="json"> JSON</OPTION>

<OPTION value="form"> FORMULAE</OPTION>

<OPTION value="html"> HTML</OPTION>

</SELECT><BR>

 

<DIV id="drop">Drop a spreadsheet file here to see sheet data</DIV>

<INPUT name="xlfile" id="xlf" type="file"> ... or click here to select a file

 

<TEXTAREA id="b64data">... or paste a base64-encoding here</TEXTAREA>

<INPUT id="dotext" onclick="b64it();" type="button" value="Click here to process the base64 text"><BR>

<B>Advanced Demo Options:</B>

Use Web Workers: (when available) <INPUT name="useworker" type="checkbox" checked="">

Use readAsBinaryString: (when available) <INPUT name="userabs" type="checkbox" checked="">

</PRE>

<PRE id="out"></PRE>

<DIV id="htmlout"></DIV><BR>

 

<script src="shim.js"></script>

<script src="xlsx.full.min.js"></script>



 

<SCRIPT>

 

var X = XLSX;

var XW = {

       msg: 'xlsx',  

       worker: './xlsxworker.js'

};

 

var global_wb;

 

var process_wb = (function() {

       var OUT = document.getElementById('out');

       var HTMLOUT = document.getElementById('htmlout');

 

       var get_format = (function() {

              var radios = document.getElementsByName( "format" );

              return function() {

                     for(var i = 0; i < radios.length; ++i) if(radios[i].checked || radios.length === 1) return radios[i].value;

              };

       })();

 

       var to_json = function to_json(workbook) {

              var result = {};

              workbook.SheetNames.forEach(function(sheetName) {

                     var roa = X.utils.sheet_to_json(workbook.Sheets[sheetName]);

                     if(roa.length) result[sheetName] = roa;

              });

              return JSON.stringify(result, 2, 2);

       };

 

       var to_csv = function to_csv(workbook) {

              var result = [];

              workbook.SheetNames.forEach(function(sheetName) {

                     var csv = X.utils.sheet_to_csv(workbook.Sheets[sheetName]);

                     if(csv.length){

                           result.push("SHEET: " + sheetName);

                           result.push("");

                           result.push(csv);

                     }

              });

              return result.join("\n");

       };

 

       var to_fmla = function to_fmla(workbook) {

              var result = [];

              workbook.SheetNames.forEach(function(sheetName) {

                     var formulae = X.utils.get_formulae(workbook.Sheets[sheetName]);

                     if(formulae.length){

                           result.push("SHEET: " + sheetName);

                           result.push("");

                           result.push(formulae.join("\n"));

                     }

              });

              return result.join("\n");

       };

 

       var to_html = function to_html(workbook) {

              HTMLOUT.innerHTML = "";

              workbook.SheetNames.forEach(function(sheetName) {

                     var htmlstr = X.write(workbook, {sheet:sheetName, type:'binary', bookType:'html'});

                     HTMLOUT.innerHTML += htmlstr;

              });

              return "";

       };

 

       return function process_wb(wb) {

              global_wb = wb;

              var output = "";

              switch(get_format()) {

                     case "form": output = to_fmla(wb); break;

                     case "html": output = to_html(wb); break;

                     case "json": output = to_json(wb); break;

                     default: output = to_csv(wb);

              }

              if(OUT.innerText === undefined) OUT.textContent = output;

              else OUT.innerText = output;

              if(typeof console !== 'undefined') console.log("output", new Date());

       };

})();

 

var setfmt = window.setfmt = function setfmt() { if(global_wb) process_wb(global_wb); };

 

var b64it = window.b64it = (function() {

       var tarea = document.getElementById('b64data');

       return function b64it() {

              if(typeof console !== 'undefined') console.log("onload", new Date());

              var wb = X.read(tarea.value, {type:'base64', WTF:false});

              process_wb(wb);

       };

})();

 

var do_file = (function() {

       var rABS = typeof FileReader !== "undefined" && (FileReader.prototype||{}).readAsBinaryString;

       var domrabs = document.getElementsByName("userabs")[0];

       if(!rABS) domrabs.disabled = !(domrabs.checked = false);

 

       var use_worker = typeof Worker !== 'undefined';

       var domwork = document.getElementsByName("useworker")[0];

       if(!use_worker) domwork.disabled = !(domwork.checked = false);

 

       var xw = function xw(data, cb) {

              var worker = new Worker(XW.worker);

              worker.onmessage = function(e) {

                     switch(e.data.t) {

                           case 'ready': break;

                           case 'e': console.error(e.data.d); break;

                           case XW.msg: cb(JSON.parse(e.data.d)); break;

                     }

              };

              worker.postMessage({d:data,b:rABS?'binary':'array'});

       };

 

       return function do_file(files) {

              rABS = domrabs.checked;

              use_worker = domwork.checked;

              var f = files[0];

              var reader = new FileReader();

              reader.onload = function(e) {

                     if(typeof console !== 'undefined') console.log("onload", new Date(), rABS, use_worker);

                     var data = e.target.result;

                     if(!rABS) data = new Uint8Array(data);

                     if(use_worker) xw(data, process_wb);

                     else process_wb(X.read(data, {type: rABS ? 'binary' : 'array'}));

              };

              if(rABS) reader.readAsBinaryString(f);

              else reader.readAsArrayBuffer(f);

       };

})();

 

(function() {

       var drop = document.getElementById('drop');

       if(!drop.addEventListener) return;

 

       function handleDrop(e) {

              e.stopPropagation();

              e.preventDefault();

              do_file(e.dataTransfer.files);

       }

 

       function handleDragover(e) {

              e.stopPropagation();

              e.preventDefault();

              e.dataTransfer.dropEffect = 'copy';

       }

 

       drop.addEventListener('dragenter', handleDragover, false);

       drop.addEventListener('dragover', handleDragover, false);

       drop.addEventListener('drop', handleDrop, false);

})();

 

(function() {

       var xlf = document.getElementById('xlf');

       if(!xlf.addEventListener) return;

       function handleFile(e) { do_file(e.target.files); }

       xlf.addEventListener('change', handleFile, false);

})();

</SCRIPT>

 

<SCRIPT type="text/javascript">

       var _gaq = _gaq || [];

       _gaq.push(['_setAccount', 'UA-36810333-1']);

       _gaq.push(['_trackPageview']);

 

       (function() {

              var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

              ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

       })();

</SCRIPT>

 </BODY></HTML>

 

 

Regards

Ethiraj

**Comment by SheetJSDev** [comment]
`Unsupported file 162|186|90|178` that error is showing the first four bytes of the file.  Can you share the file that is causing this error?  Also, what browser are you using?

**Comment by EthirajG** [comment]
Dear team,

 

<!DOCTYPE HTML>

 

<HTML><HEAD><META />

content="IE=11.0000" http-equiv="X-UA-Compatible">

 

<META http-equiv="Content-Type" content="text/html; charset=UTF-8"> 

<TITLE>SheetJS Live Demo</TITLE> 

<STYLE>

#drop{

       border:2px dashed #bbb;

       -moz-border-radius:5px;

       -webkit-border-radius:5px;

       border-radius:5px;

       padding:25px;

       text-align:center;

       font:20pt bold,"Vollkorn";color:#bbb

}

#b64data{

       width:100%;

}

a { text-decoration: none }

</STYLE>

 

<META name="GENERATOR" content="MSHTML 11.00.9600.18792"></HEAD> 

<BODY>

<PRE>

Output Format: <SELECT name="format" onchange="setfmt()">

<OPTION value="csv" selected=""> CSV</OPTION>

<OPTION value="json"> JSON</OPTION>

<OPTION value="form"> FORMULAE</OPTION>

<OPTION value="html"> HTML</OPTION>

</SELECT><BR>

 

<DIV id="drop">Drop a spreadsheet file here to see sheet data</DIV>

<INPUT name="xlfile" id="xlf" type="file"> ... or click here to select a file

 

<TEXTAREA id="b64data">... or paste a base64-encoding here</TEXTAREA>

<INPUT id="dotext" onclick="b64it();" type="button" value="Click here to process the base64 text"><BR>

<B>Advanced Demo Options:</B>

Use Web Workers: (when available) <INPUT name="useworker" type="checkbox" checked="">

Use readAsBinaryString: (when available) <INPUT name="userabs" type="checkbox" checked="">

</PRE>

<PRE id="out"></PRE>

<DIV id="htmlout"></DIV><BR>

 

<script src="shim.js"></script>

<script src="xlsx.full.min.js"></script>



 

<SCRIPT>

 

var X = XLSX;

var XW = {

       msg: 'xlsx',  

       worker: './xlsxworker.js'

};

 

var global_wb;

 

var process_wb = (function() {

       var OUT = document.getElementById('out');

       var HTMLOUT = document.getElementById('htmlout');

 

       var get_format = (function() {

              var radios = document.getElementsByName( "format" );

              return function() {

                     for(var i = 0; i < radios.length; ++i) if(radios[i].checked || radios.length === 1) return radios[i].value;

              };

       })();

 

       var to_json = function to_json(workbook) {

              var result = {};

              workbook.SheetNames.forEach(function(sheetName) {

                     var roa = X.utils.sheet_to_json(workbook.Sheets[sheetName]);

                     if(roa.length) result[sheetName] = roa;

              });

              return JSON.stringify(result, 2, 2);

       };

 

       var to_csv = function to_csv(workbook) {

              var result = [];

              workbook.SheetNames.forEach(function(sheetName) {

                     var csv = X.utils.sheet_to_csv(workbook.Sheets[sheetName]);

                     if(csv.length){

                           result.push("SHEET: " + sheetName);

                           result.push("");

                           result.push(csv);

                     }

              });

              return result.join("\n");

       };

 

       var to_fmla = function to_fmla(workbook) {

              var result = [];

              workbook.SheetNames.forEach(function(sheetName) {

                     var formulae = X.utils.get_formulae(workbook.Sheets[sheetName]);

                     if(formulae.length){

                           result.push("SHEET: " + sheetName);

                           result.push("");

                           result.push(formulae.join("\n"));

                     }

              });

              return result.join("\n");

       };

 

       var to_html = function to_html(workbook) {

              HTMLOUT.innerHTML = "";

              workbook.SheetNames.forEach(function(sheetName) {

                     var htmlstr = X.write(workbook, {sheet:sheetName, type:'binary', bookType:'html'});

                     HTMLOUT.innerHTML += htmlstr;

              });

              return "";

       };

 

       return function process_wb(wb) {

              global_wb = wb;

              var output = "";

              switch(get_format()) {

                     case "form": output = to_fmla(wb); break;

                     case "html": output = to_html(wb); break;

                     case "json": output = to_json(wb); break;

                     default: output = to_csv(wb);

              }

              if(OUT.innerText === undefined) OUT.textContent = output;

              else OUT.innerText = output;

              if(typeof console !== 'undefined') console.log("output", new Date());

       };

})();

 

var setfmt = window.setfmt = function setfmt() { if(global_wb) process_wb(global_wb); };

 

var b64it = window.b64it = (function() {

       var tarea = document.getElementById('b64data');

       return function b64it() {

              if(typeof console !== 'undefined') console.log("onload", new Date());

              var wb = X.read(tarea.value, {type:'base64', WTF:false});

              process_wb(wb);

       };

})();

 

var do_file = (function() {

       var rABS = typeof FileReader !== "undefined" && (FileReader.prototype||{}).readAsBinaryString;

       var domrabs = document.getElementsByName("userabs")[0];

       if(!rABS) domrabs.disabled = !(domrabs.checked = false);

 

       var use_worker = typeof Worker !== 'undefined';

       var domwork = document.getElementsByName("useworker")[0];

       if(!use_worker) domwork.disabled = !(domwork.checked = false);

 

       var xw = function xw(data, cb) {

              var worker = new Worker(XW.worker);

              worker.onmessage = function(e) {

                     switch(e.data.t) {

                           case 'ready': break;

                           case 'e': console.error(e.data.d); break;

                           case XW.msg: cb(JSON.parse(e.data.d)); break;

                     }

              };

              worker.postMessage({d:data,b:rABS?'binary':'array'});

       };

 

       return function do_file(files) {

              rABS = domrabs.checked;

              use_worker = domwork.checked;

              var f = files[0];

              var reader = new FileReader();

              reader.onload = function(e) {

                     if(typeof console !== 'undefined') console.log("onload", new Date(), rABS, use_worker);

                     var data = e.target.result;

                     if(!rABS) data = new Uint8Array(data);

                     if(use_worker) xw(data, process_wb);

                     else process_wb(X.read(data, {type: rABS ? 'binary' : 'array'}));

              };

              if(rABS) reader.readAsBinaryString(f);

              else reader.readAsArrayBuffer(f);

       };

})();

 

(function() {

       var drop = document.getElementById('drop');

       if(!drop.addEventListener) return;

 

       function handleDrop(e) {

              e.stopPropagation();

              e.preventDefault();

              do_file(e.dataTransfer.files);

       }

 

       function handleDragover(e) {

              e.stopPropagation();

              e.preventDefault();

              e.dataTransfer.dropEffect = 'copy';

       }

 

       drop.addEventListener('dragenter', handleDragover, false);

       drop.addEventListener('dragover', handleDragover, false);

       drop.addEventListener('drop', handleDrop, false);

})();

 

(function() {

       var xlf = document.getElementById('xlf');

       if(!xlf.addEventListener) return;

       function handleFile(e) { do_file(e.target.files); }

       xlf.addEventListener('change', handleFile, false);

})();

</SCRIPT>

 

<SCRIPT type="text/javascript">

       var _gaq = _gaq || [];

       _gaq.push(['_setAccount', 'UA-36810333-1']);

       _gaq.push(['_trackPageview']);

 

       (function() {

              var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

              ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

       })();

</SCRIPT>

 </BODY></HTML>

 

Regards

Ethiraj

**Comment by SheetJSDev** [comment]
@EthirajG that error is showing up when you are reading a spreadsheet.  Can you share the spreadsheet you tested with (not the code you used)?

**Comment by EthirajG** [comment]
Dear Team,

                                Please find the file above

 

Regards

Ethiraj

**Comment by SheetJSDev** [comment]
@EthirajG github does not expose attachments -- please send to sheetjs@gmail.com
