### ISSUE TITLE
Text encoding issues in Props.LastAuthor property

### ISSUE THREAD

**Issue by fureweb-com** [SheetJS/js-xlsx#822]
const bstr: string = e.target.result;
const wb = XLSX.read (bstr, {type: 'binary'});

There is a problem that the LastAuthor of the Props property of the workbook data read by the above command does not parse properly.

I checked the source a bit and found that in this case, data.asBinary () is used in xlsx's getdatastr function, so it can not be decoded in UTF-8. If you take data.asText () from here, it seems that you can get the XML document that is normally UTF-8 decoded successfully.

I think we need to fix this issue.

**Comment by SheetJSDev** [comment]
Good catch! The change should be 

```diff
-		propdata = getzipstr(zip, strip_front_slash(dir.coreprops[0]), true);
+		propdata = utf8read(getzipdata(zip, strip_front_slash(dir.coreprops[0]), true));
```

We'll roll that out tomorrow with a test

**Comment by fureweb-com** [comment]
thanks! :)

**Comment by SheetJSDev** [comment]
We added the changes in 0.11.5 along with some [fun test files with author `☃`](https://github.com/SheetJS/test_files/blob/master/author_snowman.xlsx?raw=true) -- please update and check if that works

**Comment by fureweb-com** [comment]
Thank you! Now I can see a cute snowman :)

![Image of snowman](http://fureweb.com/issue-822-after.png)
