### ISSUE TITLE
Get JSON Object which has first column as Headers

### ISSUE THREAD

**Issue by sathish804** [SheetJS/js-xlsx#823]
Hi All,

The current sheet_to_json function is only considers rows as headers. 

var jsonObj = XLSX.utils.sheet_to_json(worksheet, {raw: true,header:0});

Is it possible to get the JSON object for the sheet having first column as header?

Attached the sample excel below.

Regards,
Sathish.
[Col_Headers.xlsx](https://github.com/SheetJS/js-xlsx/files/1340386/Col_Headers.xlsx)

**Comment by SheetJSDev** [comment]
If you convert with `header:1`, the output format will be an array of arrays, like

```js
data = [ 
  ["a", 1, 2],
  ["b", 3, 4],
  ["c", 5, 6]
]
```

That can be manually converted to an array of objects based on columns:

```js
var max = d.reduce((x,y) => Math.max(x,y.length), 0)
var o = new Array(max-1);
for(var i = 0; i < max-1; ++i) o[i] = {};
data.forEach(row => { row.slice(1).forEach((elt, i) => { o[i][row[0]] = elt }); });

// now o will be [ { a: 1, b: 3, c: 5 }, { a: 2, b: 4, c: 6 } ]
```

**Comment by sathish804** [comment]
Hi SheetJSDev, Thank you for the quick answer.

I modified the sheet_to_json with extra parameter to create the json object on column headers.

`if(isColHeader){
		var max = out.reduce((x,y) => Math.max(x,y.length), 0)
		var o = new Array(max-1);
		for(var i = 0; i < max-1; ++i) o[i] = {};
		out.forEach(row => { row.slice(1).forEach((elt, i) => { o[i][row[0]] = elt }); });
		return o;
	}else{
	
	return out;
	
	}`

But the output is not similar as you mentioned above.

`[["a",1,2],["b",3,4],["c",5,6]]`

Please advise what I am doing wrong here.

Regards,
Sathish.

**Comment by SheetJSDev** [comment]
https://jsfiddle.net/1jwkyx13/ is a complete example starting from a workbook object generated from a CSV:

```js
/*
  External Resources:
  -  https://unpkg.com/xlsx/dist/xlsx.full.min.js
*/

/* start with a worksheet */
var original_csv = "a,1,2\nb,3,4\nc,5,6";
var wb = XLSX.read(original_csv, {type:'string'});
var ws = wb.Sheets[wb.SheetNames[0]];

/* convert to array-of-arrays */
var data = XLSX.utils.sheet_to_json(ws, {raw:true, header:1});

/* convert to column-major objects */
var max = data.reduce(function (x, y) { return Math.max(x, y.length); }, 0);
var o = new Array(max-1);
for(var i = 0; i < max-1; ++i) o[i] = {};
data.forEach(function (row) { row.slice(1).forEach(function (elt, i) { o[i][row[0]] = elt; }); });

/* display the result */
console.log(o);
```

**Comment by sathish804** [comment]
Thank You!!

**Comment by dhananjay4985** [comment]
Hi,
I have XL sheet where some column names are like(Area,Comarch),I want to convert them into (area,comarch).
I want to do this for particular column names not for all.
any suggestion how should I do it..??  (I am new in Angular)

Thanks

**Comment by fredrivett** [comment]
Building on @SheetJSDev's super helpful answer, here's my utility function in typescript:

```ts
import xlsx from "xlsx";

/**
 * xlsx expects sheets to have headers on the first row, this util allows us to
 * parse a horizontal oriented sheet with headers in the first *column*
 *
 * @param sheet The horizontally oriented worksheet to convert
 *
 * @return An array of row objects, with the header as the key
 */
export const getJsonFromHorizontalSheet = (sheet: xlsx.WorkSheet) => {
  // convert to array of arrays
  const data: unknown[][] = xlsx.utils.sheet_to_json(sheet, {
    raw: true,
    header: 1,
  });

  // ensure that each row uploaded has a string in the first column
  data.forEach((item) => {
    if (typeof item[0] !== "string") {
      throw new TypeError(
        `Failed converting horizontally oriented worksheet, expected a string, got ${typeof item[0]}`,
      );
    }
  });

  // assert the types now we've done our type check above
  const dataWithTypes = data as [string, ...unknown[]][];

  // convert to column-major objects
  const max = dataWithTypes.reduce((x, y) => Math.max(x, y.length), 0);
  const result: Record<string, unknown>[] = Array.from(
    { length: max - 1 },
    () => ({}),
  );

  // add the rows to the result object
  dataWithTypes.forEach((row) => {
    row.slice(1).forEach((elt, index: number) => {
      const header: string = row[0];
      result[index][header] = elt;
    });
  });

  return result;
};
```
