### ISSUE TITLE
 Verify charts properties in excel using xlsx 

### ISSUE THREAD

**Issue by duvemula** [SheetJS/js-xlsx#826]
Hi,
Can we verify charts properties like values and styles in excel with xlsx module.
Regards,
DurgaPrasad

**Comment by SheetJSDev** [comment]
The community version (this module) reflects the chart cache as a pseudo worksheet.  More detailed information is available in the chart component of the Pro compendium.

**Comment by duvemula** [comment]
Hi @SheetJSDev,

I am getting below output when read excel chart
{ '!ref': 'A1:I30',
  A1: { t: 's', v: '.', r: '<t>.</t>', h: '.', w: '.' },
  '!margins': 
   { left: 0.75,
     right: 0.75,
     top: 1,
     bottom: 1,
     header: 0.5,
     footer: 0.5 } } 
I am not seeing any chart related information here.

code:
 var XLSX = require('xlsx');
 var workbook = XLSX.readFile(filename, {"!type": "chart"}); 
console.log(workbook.Sheets.sheetname);

Could you please suggest me how to read the chart properties.

Please let me know if you need more information

Regards,
Durga Prasad
