### ISSUE TITLE
Text Array in Spreadsheet

### ISSUE THREAD

**Issue by mrb1090** [SheetJS/js-xlsx#828]
Curious if there is a convenient way to represent a text array in Excel so it will translate to the appropriate JSON array upon conversion?

e.g.

whitelist   [a, b, c, d]  --> whitelist:['a', 'b', 'c', 'd']

Thanks,

Mike B.

**Comment by SheetJSDev** [comment]
Not really, you have to do some post-processing.  I would probably put square brackets in the sheet header, like in this screenshot: 
<img width="347" alt="" src="https://user-images.githubusercontent.com/6070939/31094674-01375832-a784-11e7-900c-0728d48c029d.png">

First get the array of arrays output:

```js
const aoa = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], {header:1, raw:true});
// ---
[ 
  [ 'x', 'y[0]', 'y[1]', 'y[2]', 'y[3]' ],
  [ 'a', 1, 2, 3, 4 ],
  [ 'b', 'c', 'd', 'e', 'f' ]
]
```

Then with a bit of processing, you can generate objects:

```js
const dorow = (d, h) => h.reduce((o, hdr, i) => {
  const m = hdr.match(/(.*)\[(\d*)\]/);
  if(!m) o[hdr] = d[i]; else {
    if(!o[m[1]]) o[m[1]] = [];
    o[m[1]][m[2]] = d[i];
  } return o;
}, {});
const doit = (aoa) => aoa.slice(1).map(r => dorow(r, aoa[0]));
const out = doit(aoa);
// ---
[
  { x: 'a', y: [ 1, 2, 3, 4 ] },
  { x: 'b', y: [ 'c', 'd', 'e', 'f' ] }
]
```
