### ISSUE TITLE
Getting Extra Backward slash for the String values having Black Slash

### ISSUE THREAD

**Issue by sathish804** [SheetJS/js-xlsx#829]
Hi,

I have a work book where the values as below. 

\\VM1\Folder1

But when I read the workbook with js xlsx  I am getting the value as 

\\\\VM1\\Folder1

is it possible to get the value without extra escape character?

Regards,
Sathish.

**Comment by SheetJSDev** [comment]
Can you share the file?  This does not appear to happen with a fresh workbook under XLS or XLSX or XLSB.

Note: when the browser or nodejs console is showing an object, it will automatically display escaped strings:

```js
> wb.Sheets.Sheet1.A1
{ t: 's',
  v: '\\VM1\\Folder1',
  r: '<t>\\VM1\\Folder1</t>',
  h: '\\VM1\\Folder1',
  w: '\\VM1\\Folder1' }
```

Those escape characters aren't in the string:

```js
> console.log(wb.Sheets.Sheet1.A1.v)
\VM1\Folder1
```

**Comment by sathish804** [comment]
Hi SheetJSDev,

I was using this wonderful and excellent library for our Automation process with Static HTML to read and write the excel sheets for better performance.

In read excel after reading the excel data I am extracting the JSON object which is coming as in attached Screen shot. For now in my automation tool I handled it to replace the "\\" with "\" as a work around.

I attached the sample excel which I tried.

Regards,
Sathish.
[Book3.xlsx](https://github.com/SheetJS/js-xlsx/files/1352838/Book3.xlsx)
![capture](https://user-images.githubusercontent.com/14090242/31134041-61bf2440-a861-11e7-90cb-248b6bd1864e.JPG)

**Comment by SheetJSDev** [comment]
To verify the processing is correct, test with http://oss.sheetjs.com/js-xlsx/ .  This is the CSV output:

<img width="252" alt="screen shot 2017-10-03 at 11 39 41" src="https://user-images.githubusercontent.com/6070939/31134277-a008d502-a82f-11e7-84b3-92b9498cc120.png">

If you are doing a `JSON.stringify` at some point, extra slashes will be added, in which case a `JSON.parse` will remove them.  If you select JSON you will see:

<img width="219" alt="screen shot 2017-10-03 at 11 40 00" src="https://user-images.githubusercontent.com/6070939/31134319-ba638622-a82f-11e7-8d5c-d2abf2992e39.png">

If you drag and drop the file, you can see the raw data is correct by tinkering in the console:

<img width="267" alt="screen shot 2017-10-03 at 11 43 09" src="https://user-images.githubusercontent.com/6070939/31134433-0c91b234-a830-11e7-95e9-116bdc150cc1.png">

I would go through the pipeline and see if some step is escaping backslashes.

**Comment by sathish804** [comment]
Hi SheetJSDev,

I am not using JSON.stringify in my code I am directly populating the HTML text area with the JSON object returned by the sheet_to_json function.

With or without JSON.stringify I am getting the same output.

Please find the attached screen shot showing the output in html page with JSON.stringify.

![capture1](https://user-images.githubusercontent.com/14090242/31164105-efeeb10c-a8e5-11e7-98ed-90c30401cb3a.JPG)

Thanks and Regards,
Sathish.

**Comment by josekmathew317** [comment]
Hi SheetJSDev, 

I need to convert XLSX to JSON only. 

When the result showing in HTML, it looks fine. I want to store the same data in local storage for future use. At the same time, backslash coming double. 

If I convert it into CSV, it is fine. But I want in JSON format only. 

My issue is comimg like 

expected : "one\two"
actual result : "one\\two"

Extra backslash coming.

Any possible way for this ?

Regards
Jose K Mathew
