### ISSUE TITLE
Access defined names and assigned values

### ISSUE THREAD

**Issue by developergdd** [SheetJS/js-xlsx#83]
Hi,

Congrats on your project.
I am trying to obtain all values and formulas of a file.
I have managed to get it to work, however some formulas use defined names instead of cells. 

For example:
works well,            A2=A1

doesn't work ,       A2=First_Value, where the name "First_Value" is assigned to A1

Is there a way to get all the defined names and assignations? Or each cell formula with the assigned value instead of the name?

Best Regards 
João Bernardino

**Comment by jasconius** [comment]
Seeking an update on this. I have need for using Defined Names

**Comment by jasconius** [comment]
So I'm feeling my way through this and trying to make a patch that will add DefinedNames and I am stuck on a fundamental problem. The parsing routine in 77_wbxml.js is oriented to only be concerned with parsing the contents of an XML tag as follows

<myTag myProp="value">

Which works for basically everything except for DefinedNames which routinely look more like the following:

<myTag>value</myTag>

Looks like another data.match().forEach will need to be added to focus on the internals of the tag and it needs to fuse itself into the data in an orderly fashion. I'll see what I can come up with.

**Comment by jasconius** [comment]
I have a working draft of this in a fork. Need to do a little more testing but I hope to get a pull request out in the next week or so.

**Comment by SheetJSDev** [comment]
Defined names are captured in workbook object's `Workbook.Names` field.  For the [defined_names_simple.xlsx sample test file](https://github.com/SheetJS/test_files/blob/master/defined_names_simple.xlsx?raw=true) the object looks like this: 

```js
{
  '!names': [ 'SHEETjs', 'SheetJS' ],
  SHEETjs: {
    Name: 'SHEETjs',
    Comment: 'This is a sheet-scope reference',
    Ref: 'Sheet1!$A$2'
  },
  SheetJS: { 
    Name: 'SheetJS',
    Comment: 'defined names just suck  excel formulae are bad  MS should feel bad',
    Ref: 'Sheet1!$A$1'
  } 
}
```

The `!names` field is an ordered list of the defined names, while each name is its own key.  The keys of the object include `Name` for the name of the defined name, `Comment` for the comment and `Ref` for the actual reference string.  XLSB follows the same pattern.  We will be filling out the other formats soon (issue #599 tracks progress for the other formats)

**Comment by capndave** [comment]
Did this ever get worked out? I'm also trying to parse a file with tons of defined names

**Comment by jwhitmarsh** [comment]
@capndave did you ever find a solution to this?

**Comment by capndave** [comment]
No but I moved on and used another tool.

**Comment by jwhitmarsh** [comment]
Thanks for letting me know - would you recommend the new tool you're using? What is it?

**Comment by SheetJSDev** [comment]
@jwhitmarsh If `wb` is your workbook, then `wb.Workbook.Names` is an array of the defined names as described in https://docs.sheetjs.com/#defined-names

@capndave if https://github.com/fabiooshiro/xlsx-calc/issues/20 was your issue, the in-workbook names should have been addressed (at least the issue is marked closed).  The names with square brackets reference external workbooks, which is something not supported in our open source build but we offer as part of our [Pro formula calculator](https://sheetjs.com/pro) -- that build will inspect the external reference caches if they exist

**Comment by capndave** [comment]
I used the Python package pywin32, which ended up being pretty flexible and
easy!
