### ISSUE TITLE
Update or change the header value

### ISSUE THREAD

**Issue by jrmpgduan** [SheetJS/js-xlsx#833]
I have a project required to export/write excel file, the problem is I'm getting the JSON key as the header of the excel file and when I'm trying to use {header: 1} I'm getting error "Uncaught TypeError: s.indexOf is not a function". i nee d sample on how to change/update header value using js xlsx. Thanks.

**Comment by reviewher** [comment]
Can you share a small code sample that elicits the error?  Please share a way to reproduce and we can take a look.
