### ISSUE TITLE
[ODS] multiple space characters are not parsed correctly

### ISSUE THREAD

**Issue by gttds** [SheetJS/js-xlsx#835]
[example.zip](https://github.com/SheetJS/js-xlsx/files/1367744/example.zip) contains a simple .ODS file which has a text with 3 spaces enclosed in square braces.

SheetJS is not parsing multiple space characters correctly. There should be 3 space characters but it has parsed only 1 space character.

Expected:
```
> xlsx.utils.sheet_to_csv(ws);
'[   ]\n'
```
Actual:
```
> xlsx.utils.sheet_to_csv(ws);
'[ ]\n'
```

**Comment by SheetJSDev** [comment]
The cell in question has the XML representation

```xml
            <text:p>[ <text:s text:c="2"/>]</text:p>
```

https://github.com/SheetJS/js-xlsx/blob/master/bits/80_parseods.js#L5 removes those tags with the `c` attribute, but the parameter should be parsed.

**Comment by SheetJSDev** [comment]
Thanks a lot!  If you are feeling up for it @gttds there are a few other tags encoding whitespace: `text:tab` and `text:line-break`.  Here is the relevant part from the spec:
[ODv12Part1pp120_121.pdf](https://github.com/SheetJS/js-xlsx/files/1372177/ODv12Part1pp120_121.pdf)
