### ISSUE TITLE
Is there a way to show a progress bar by using the xlxs.write method on the client？

### ISSUE THREAD

**Issue by BeAce** [SheetJS/js-xlsx#845]
In the web page, I want to know the time that this code consumes and show a progress bar for writing files. Is there any way?

```jsx
const wbout = XLSX.write(wb, {
  bookType: 'xlsx',
  bookSST: true,
  type: 'binary',
});
```

**Comment by SheetJSDev** [comment]
There's no easy way to determine that upfront since there are issues like garbage collection involved.  You can always show a CSS spin animation.
