### ISSUE TITLE
Writing strings like "2017-S08 (20/02)" causes the unreadable file message

### ISSUE THREAD

**Issue by khalilTN** [SheetJS/js-xlsx#846]
Writing strings like "2017-S08 (20/02)" causes the unreadable file message even the cell type is "s" for String

**Comment by SheetJSDev** [comment]
Can't reproduce using http://sheetjs.com/demos/table .  Double-click the bottom-left cell, change the contents to `2017-S08 (20/02)` and export as XLSX:

<img width="557" alt="" src="https://user-images.githubusercontent.com/6070939/31720018-5e4378b0-b3e3-11e7-809a-9662ad6d37b6.png">

Can you share a code example and the generated file?

**Comment by khalilTN** [comment]
Sorry for your lost time, i was using this string as sheet name, excel seems to not accpet such format as shhet name

**Comment by SheetJSDev** [comment]
We added a sheet name checker a while back.  `write` and `writeFile` will throw errors if you use a bad sheet name, as you can see in this fiddle: https://jsfiddle.net/upvd8trj/
