### ISSUE TITLE
How to specify to trim whitespaces using XLSX.utils.table_to_sheet

### ISSUE THREAD

**Issue by laurentauthier** [SheetJS/js-xlsx#849]
is it possible to add this feature?

**Comment by Andreas-Hjortland** [comment]
As a workaround you can do something like 
```javascript
table.querySelectorAll('tr,th').forEach(elt => elt.innerHTML = elt.innterHTML.trim());
```

**Comment by laurentauthier** [comment]
I tried this:
var table = document.getElementById(id);
table.querySelectorAll('tr,th').forEach(elt => elt.innerHTML = elt.innerHTML.trim());
var ws = XLSX.utils.table_to_sheet(table, {raw:true });
no effect, allways whitespaces before and after the value
