### ISSUE TITLE
Editing Table On Page - IE

### ISSUE THREAD

**Issue by elogicmedia** [SheetJS/js-xlsx#851]
Hi All,

I found this demo: http://sheetjs.com/demos/modify.html which is perfect for what we are after, I have however run into a snag, the editing sheet on the page doesn't seem to work for any versions of IE.

Going by the demo link it takes me to this page: http://caniuse.com/#search=contenteditable which says IE 11 does support the theml5 contenteditable tag, however on further research it seems like it only works on span or div tags, the script sets this up as a HTML table with the contenteditable tag on the td.

Has anyone come up with a work-around for this? or am I doing something incorrectly? I'm using the demo at the above link, that doesn't work in IE for me either.

Thanks

**Comment by elogicmedia** [comment]
As a hack, I did this within the xlsx file, which does work. I was hoping there may be a better way.

function writextag(f,g,h) { return '<' + f + (isval(h) ? wxt_helper(h) : "") + (isval(g) ? (g.match(wtregex)?' xml:space="preserve"' : "") + '><span contenteditable="true">' + g + '</span></' + f : "/") + '>';}

**Comment by reviewher** [comment]
The relevant part is in [`make_html_row`](https://github.com/SheetJS/js-xlsx/blob/master/bits/79_html.js#L87-L89) -- it makes more sense to add the span there:

```js
if(o.editable) w =  '<span contenteditable="true">' + w + '</span>'
oo.push(writextag('td', w, sp));
```

More generally, we definitely recommend using a proper JS grid component.  We like the canvas-based approach taken by [`canvas-datagrid`](https://github.com/TonyGermaneri/canvas-datagrid) -- the included [datagrid demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/datagrid) is an example integration that is publicly deployed at http://oss.sheetjs.com/js-xlsx/datagrid

**Comment by notyeti** [comment]
This is also failing on Edge 14
