### ISSUE TITLE
How to read a big 'csv' formatted file(~3.5g)?

### ISSUE THREAD

**Issue by patientayo** [SheetJS/js-xlsx#853]
log: RangeError: "size" argument must not be larger than 2147483647.

thank you.

**Comment by reviewher** [comment]
[Excel itself does not support more than 1048576 rows](https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3), so you're likely dealing with a file outside of Excel's limits.  There are dedicated CSV reading libraries designed for "beyond Excel" datasets like [`csv-parse`](https://www.npmjs.com/package/csv-parse)

**Comment by patientayo** [comment]
Thanks a lot.
