### ISSUE TITLE
XLSX.utils.json_to_sheet error: "js.forEach is not a function" 

### ISSUE THREAD

**Issue by bysja** [SheetJS/js-xlsx#857]
I am trying to convert an array of objects to an .xlsx file using Node.js with js-xlsx.

When I run this code from my file `vinnsla.js`:

`var output = JSON.stringify(obj);`
`var workbook = XLSX.utils.json_to_sheet(output);`

By typing this into my terminal:

`node vinnsla.js`

I get the following error:

```
/Users/.../node_modules/xlsx/xlsx.js:18592
	js.forEach(function (JS, R) {
	   ^
TypeError: js.forEach is not a function
    at Object.json_to_sheet (/Users/.../node_modules/xlsx/xlsx.js:18592:5)
    at Object.<anonymous> (/Users/.../vinnsla.js:62:27)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

Attached is the JSON string I am trying to convert as well as my package.json file (both are renamed with .txt extensions so I could upload them.

[fasteignir.txt](https://github.com/SheetJS/js-xlsx/files/1412833/fasteignir.txt)
[package-json.txt](https://github.com/SheetJS/js-xlsx/files/1412836/package-json.txt)

**Comment by reviewher** [comment]
The function [actually deals with an array of plain JS objects](https://docs.sheetjs.com/#array-of-objects-input).  You should be able to run `var workbook = XLSX.utils.json_to_sheet(obj);` directly.

**Comment by bysja** [comment]
Thank you - that worked. 

However, now I get the following error when attempting to execute `XLSX.writeFile(workbook, 'output.xlsx');` afterwards:

```
/Users/.../node_modules/xlsx/xlsx.js:12814
	if(!wb || !wb.SheetNames || !wb.Sheets) throw new Error("Invalid Workbook");
	                                        ^

Error: Invalid Workbook
    at check_wb (/Users/.../node_modules/xlsx/xlsx.js:12814:48)
    at writeSync (/Users/.../node_modules/xlsx/xlsx.js:18350:2)
    at Object.writeFileSync (/Users/.../node_modules/xlsx/xlsx.js:18404:9)
    at Object.<anonymous> (/Users/.../vinnsla.js:61:6)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
```

I cannot figure this out from the documentation. Is there something wrong with my javascript object array? (attached above)

**Comment by reviewher** [comment]
That was an oversight.  `json_to_sheet` returns a worksheet, you need to build up a new workbook from it:

```js
/* new worksheet from JS objects */
var ws = XLSX.utils.json_to_sheet(obj);

/* new workbook */
var wb = XLSX.utils.book_new();
XLSX.book_append_sheet(wb, ws, "SheetJS");

/* write file */
XLSX.writeFile(wb, "output.xlsx");
```

Here's a node sample hosted on Runkit: https://runkit.com/sheetjs/59c5c7dd804721001214aa74

**Comment by bysja** [comment]
Thank you for the quick and helpful responses, everything worked perfectly now. 

For others who may read this in the future, the following command in your reply:

`XLSX.book_append_sheet(wb, ws, "SheetJS");`

Should actually be:

`XLSX.utils.book_append_sheet(wb, ws, "SheetJS");`

**Comment by Ptlancers** [comment]
kingkinHi Guys, I'm working with ```next.js```
![Screenshot from 2024-02-25 20-20-48](https://github.com/SheetJS/sheetjs/assets/148335618/0a70cd48-5fc3-4510-8bde-26e1bee0efca)
![image](https://github.com/SheetJS/sheetjs/assets/148335618/6dd4cf25-2acf-4366-aa3c-baef8b4709b1)

The second image the type/Interface of the data from the frontend.
I am working on something with Json to excel sheet/data. 

I'm always getting this error : -
![Screenshot from 2024-02-25 20-23-26](https://github.com/SheetJS/sheetjs/assets/148335618/b751a956-9bc0-4998-9782-3b0285f6d980)

whatever I tried changes the types like  type DataTemplate ={...} and interface DataTemplateInterface {....} ; type DataTemplate = DatatemplateInterface[].

Kindly help me on this guys please.

#xlsx #jsObject_to_xlsx #next.js

**Comment by alexandermirzoyan** [comment]
Same issue

**Comment by alexandermirzoyan** [comment]
For me the problem was that the argument should be Array instead of Object.
So as a solution I wrapped my JSON into Array.

**Comment by spin95** [comment]
I use the package 'xlsx-js-style' and its work with style

import XLSX from 'xlsx-js-style'

...

function exportExcel() {

    const wb = XLSX.utils.book_new()
    let dataTitle = [
        { v: "Title", s: { font: { name: "Brush Script MT", bold: true, sz: 20, }, fill: { type: 'pattern', pattern: 'solid', fgColor: { rgb: 'D5E0D2' }, bgColor: { rgb: 'D5E0D2' } } } },
    ]
    let dataHeader = [
        { v: "Col1", s: { font: { name: "Calibri", bold: true, sz: 16, }, fill: { type: 'pattern', pattern: 'solid', fgColor: { rgb: 'D5E0D2' }, bgColor: { rgb: 'D5E0D2' } } } },
        { v: "Col2", s: { font: { name: "Calibri", bold: true, sz: 16, }, fill: { type: 'pattern', pattern: 'solid', fgColor: { rgb: 'D5E0D2' }, bgColor: { rgb: 'D5E0D2' } } } },
        { v: "Col3", s: { font: { name: "Calibri", bold: true, sz: 16, }, fill: { type: 'pattern', pattern: 'solid', fgColor: { rgb: 'D5E0D2' }, bgColor: { rgb: 'D5E0D2' } } } },
    ]
    let dataBody = []
    data.forEach((item) => {
        dataBody.push([
            { v: 'C1 value', s: { font: { name: "Calibri", sz: 12, } } },
            { v: 'C2 value', s: { font: { name: "Calibri", sz: 12, } } },
            { v: 'C3 value', s: { font: { name: "Calibri", sz: 12, } } }
        ])
    })
    const ws = XLSX.utils.aoa_to_sheet([dataTitle, [], [], dataHeader, ...dataBody])
    ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 1, c: 2 } }, { s: { r: 2, c: 0 }, e: { r: 2, c: 2 } }]
    ws['!cols'] = [{ wch: 20 }, { wch: 20 }, { wch: 30 }]
    XLSX.utils.book_append_sheet(wb, ws, "Sheet1")
    XLSX.writeFile(wb, "File Export (" + new Date().toLocaleDateString('fr-FR', { year: 'numeric', month: 'numeric', day: 'numeric' }) + ")" + ".xlsx")

}

...

<Button onClick={() => exportExcel()} />
