### ISSUE TITLE
Pro Version

### ISSUE THREAD

**Issue by zgriesinger** [SheetJS/js-xlsx#859]
I am very interested in using the Pro Version for the project I am working on. The features seem to be quite enticing and would help immensely. I sent an email awhile back to support@sheetjs.com and received no response. @SheetJSDev do you have any more information on how I can inquire on this? 

If this is better suited for a private message let me know.

**Comment by nightow85** [comment]
I was send to mail a month ago, but they don`t do reply.
IRC Chat Better that.

**Comment by zgriesinger** [comment]
@ffissore Nope, nothing

**Comment by ffissore** [comment]
@SheetJSDev any ETA for the inquiries we sent by email?

**Comment by SheetJSDev** [comment]
We have caught up with the backlog at this point.

**Comment by ffissore** [comment]
I have not received any response email with a quote for the pro version

**Comment by vuonghominh** [comment]
I sent an email to get the pro version, nobody response
