### ISSUE TITLE
ng-packagr replaces all the xlsx var to undefined during packaging angular-cli project 

### ISSUE THREAD

**Issue by sbibek** [SheetJS/js-xlsx#860]
I followed the mentioned steps of using xslx with angular4 and had to package it into distribute able module. I used ng-packagr for that with angular-cli project. The build process replaces all XSLX related vars to undefined.

**Comment by reviewher** [comment]
This is the first time I've heard of this tool.  Most likely you stumbled upon an issue with the tool and I recommend raising an issue with them.

The library works with a standard angular-cli setup, as shown in [the demo](https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2).  Note that the import is [`import * as XLSX from 'xlsx';`](https://github.com/SheetJS/js-xlsx/blob/master/demos/angular2/src/app/sheetjs.component.ts#L5)
