### ISSUE TITLE
Parsing XLSX from angular 2 http (not closed)

### ISSUE THREAD

**Issue by seanmcilvenna** [SheetJS/js-xlsx#862]
Not sure why my issue was closed... it wasn't resolved yet. RE: https://github.com/SheetJS/js-xlsx/issues/861
The suggestion you provided did not solve my problem.
Now I get "Argument of type 'Blob' is not assignable to parameter of type 'ArrayBuffer'."

**Comment by reviewher** [comment]
The README includes examples where files are being downloaded in plain JS.  There are also some examples in the [`xhr` demos directory](https://github.com/SheetJS/js-xlsx/tree/master/demos/xhr) as well as a simple example http://oss.sheetjs.com/js-xlsx/ajax.html that runs in IE6+.  If those are working, then the issue likely lies with your code and not the library.
