### ISSUE TITLE
Retrieve value from cell reference of multiple excel files at once

### ISSUE THREAD

**Issue by A-Dummy** [SheetJS/js-xlsx#865]
Hello,

To get the value of cell reference C3 from an excel file I use the following code.
Is it however possible to select multiple excel files at once and get for example all values stored in cell C3 from all these files?

`var first_sheet_name = workbook.SheetNames[0];
      var address_of_cell = 'C3';
      var worksheet = workbook.Sheets[first_sheet_name];
      var desired_cell = worksheet[address_of_cell];
      var desired_value = (desired_cell ? desired_cell.v : undefined);
       container.innerHTML = desired_value;`

**Comment by reviewher** [comment]
Read each workbook then run the code for each object:

```js
function process(workbook, container) {
var first_sheet_name = workbook.SheetNames[0]; var address_of_cell = 'C3'; var worksheet = workbook.Sheets[first_sheet_name]; var desired_cell = worksheet[address_of_cell]; var desired_value = (desired_cell ? desired_cell.v : undefined); container.innerHTML = desired_value; }

process(first_workbook, first_container);
process(second_workbook, second_container);
// ...
```
