### ISSUE TITLE
Sheet names cannot exceed 31 chars

### ISSUE THREAD

**Issue by prajwal78** [SheetJS/js-xlsx#870]
I have a situation where some of my worksheet names exceed 31 characters. In this situation, it throws me the error **Sheet names cannot exceed 31 chars**. 
It went through the code in the library and came through a function which throws the above error:
`var badchars = "][*?\/\\".split("");
function check_ws_name(n, safe) {
	if(n.length > 31) { if(safe) return false; throw new Error("Sheet names cannot exceed 31 chars"); }
	var _good = true;
	badchars.forEach(function(c) {
		if(n.indexOf(c) == -1) return;
		if(!safe) throw new Error("Sheet name cannot contain : \\ / ? * [ ]");
		_good = false;
	});
	return _good;
}`

Is it worksheet names can't exceed 31 characters ? If this is the case, how can I allow worksheet names more than 31 characters for not throwing the above error ?

**Comment by reviewher** [comment]
That's an Excel limitation: https://support.office.com/en-us/article/Rename-a-worksheet-3F1F7148-EE83-404D-8EF0-9FF99FBAD1F9

> IMPORTANT: Worksheet names cannot:

> Contain more than 31 characters.

> Contain any of the following characters: / \ ? * : [ ]

**Comment by prajwal78** [comment]
@reviewher - That means we can't do anything with Excel limitations.

**Comment by xgqfrms** [comment]
# my solution

> just wrap the title and pass a short title for the `sheetjs` lib.

```js

```

**Comment by xgqfrms** [comment]
https://github.com/SheetJS/js-xlsx#writing-functions
https://github.com/SheetJS/js-xlsx#utilities

https://docs.sheetjs.com/#html-table-input
https://github.com/SheetJS/js-xlsx#html-table-input
