### ISSUE TITLE
Uncaught TypeError: jszip is not a constructor

### ISSUE THREAD

**Issue by sanny16** [SheetJS/js-xlsx#872]
Hi,
i am trying to extract xlsx file data in a sap ui5 application and i have included two files : " xlsx.js" and "jszip.js". I am able to see both files at run time in source tab.  I referred this link "https://archive.sap.com/discussions/thread/3782341" to embed these files in application and modify jszip.js in an attempt to over come the error.

Is anyone else is facing this issue?

Please advice how to proceed further.

Thanks,

Sanny.

**Comment by renatobenks** [comment]
Let me know if you already fixed it? Case yes, you could fix it adding the missing lib to package.json in your `node_modules`.

```bash
$ cd node_modules && npm i jszip
```

This issue it's about that: #873

**Comment by reviewher** [comment]
Use the `dist/xlsx.full.min.js` script by itself, not the individual files.  It's available in the [source tree](https://github.com/SheetJS/js-xlsx/blob/master/dist/xlsx.full.min.js) as well as on [CDNs like unpkg](https://unpkg.com/xlsx/dist/xlsx.full.min.js)

**Comment by anmolchadha111** [comment]
Hi sanny16,

Are you able to solve the issue? M still unable to Extract Data. Getting the error "jszip is not a constructor"

Thanks 
Anmol

**Comment by ividrine** [comment]
+1 Im still getting this error on version 0.8.0 using full.min.js..... also I tried on new versions and I was getting `XLSX.read is not a function`

**Comment by ividrine** [comment]
Update: While version 0.8 was throwing the `jzip is not a constructor` error and 0.14 was throwing the `XLSX.read is not a function` error I found that version 0.10.0 actually worked lol. Hopefully that helps someone. 

Ill also add that Im using Angular 1 and RequireJS so that might have something to do with it.

**Comment by SheetJSDev** [comment]
@ividrine can you share a small project setup with angularjs + requirejs?  Both individual demos https://github.com/SheetJS/js-xlsx/tree/master/demos/angular and https://github.com/SheetJS/js-xlsx/tree/master/demos/requirejs work against the latest 0.14.0

**Comment by salehins** [comment]
> Update: While version 0.8 was throwing the `jzip is not a constructor` error and 0.14 was throwing the `XLSX.read is not a function` error I found that version 0.10.0 actually worked lol. Hopefully that helps someone.
> 
> Ill also add that Im using Angular 1 and RequireJS so that might have something to do with it.

Thanks for that, 0.10.0 version worked for me too!

**Comment by matthewlamhk01** [comment]
is downgrading the only way to solve this?

**Comment by doston92** [comment]
https://github.com/markatil/xlsx-style/pull/1
Please accept this pull request, I corrected the error

**Comment by AliCan1033** [comment]
Guys i gave this error on reac and i dont solve it. Please help me
