### ISSUE TITLE
Xslx -> Json -> Add column in Json -> Array of Array object -> Xslx

### ISSUE THREAD

**Issue by olivier-d** [SheetJS/js-xlsx#877]
Hello,

To explain my problem, i have an xslx file that contains multiple sheet and in a sheet multiple columns with data. 

The user selects a sheet name and a column (from this sheet). I convert all sheets into JSON (sheet_to_json).
I send to my server the correct sheet and the name of the column, i make some operations and for that i need to add a column to this sheet with the same number of data that the column selected by the user. 
So i iterate the array of this sheet and for each json object, i add a property.

After that i send back to my browser the new sheet. But how can i save that to my workbook ? 
I have try to do that with the function below but with an array of object, i'm not sure if it's the best way to do that. 

`		function add_cell_to_sheet(worksheet, address, value) {
			/* cell object */
			var cell = {t:'?', v:value};

			/* assign type */
			if(typeof value == "string") cell.t = 's'; // string
			else if(typeof value == "number") cell.t = 'n'; // number
			else if(value === true || value === false) cell.t = 'b'; // boolean
			else if(value instanceof Date) cell.t = 'd';
			else throw new Error("cannot store value");

			/* add to worksheet, overwriting a cell if it exists */
			worksheet[address] = cell;

			/* find the cell range */
			var range = XLSX.utils.decode_range(worksheet['!ref']);
			var addr = XLSX.utils.decode_cell(address);

			/* extend the range to include the new cell */
			if(range.s.c > addr.c) range.s.c = addr.c;
			if(range.s.r > addr.r) range.s.r = addr.r;
			if(range.e.c < addr.c) range.e.c = addr.c;
			if(range.e.r < addr.r) range.e.r = addr.r;

			/* update range */
			worksheet['!ref'] = XLSX.utils.encode_range(range);
			console.log("worksheet -> " + workseet);
		}`

And the write function 
`	var wopts = { bookType:'xlsx', bookSST:false, type:'binary' };
        XLSX.write(workbook, wopts);`

I really want to keep an array of object for my operations.

**Comment by reviewher** [comment]
If you have an array of objects, [`json_to_sheet`](https://docs.sheetjs.com/#array-of-objects-input) converts back from the array of objects to a worksheet.  See https://github.com/SheetJS/js-xlsx/issues/817#issuecomment-331605640 for an example
