### ISSUE TITLE
Is it possible to update back changes to the original excel/csv file ?

### ISSUE THREAD

**Issue by hkbeer** [SheetJS/js-xlsx#878]
Is it possible to update back changes to the original excel/csv file ?

**Comment by reviewher** [comment]
You can read a file, make changes to the workbook object, and write to a new file.  The read / readFile functions can handle any of the supported formats and the write / writeFile functions can write any of the supported formats https://docs.sheetjs.com/#file-formats

The modify demo http://sheetjs.com/demos/modify can read files, generate an editable HTML table based on the contents, and export the changes to a new file.  The underlying object structure is described in the documentation: https://docs.sheetjs.com/#general-structures .
