### ISSUE TITLE
MS Excel Viewer problem...

### ISSUE THREAD

**Issue by soohyunko** [SheetJS/js-xlsx#880]
The file will run normally on the computer where MS Excel is installed, 
but the .xlsx file can not be opened on the computer where only MS Excel Viewer is installed.
 It seems that the Excel Viewer does not recognize the file.
 Is there a solution?

**Comment by reviewher** [comment]
Can you test against the XLS file from http://sheetjs.com/demos/table ? Next to "XLS Excel 97-2004 Binary" you will see a button "Export to XLS!".  Click it and try viewing the downloaded file.

**Comment by SheetJSDev** [comment]
Tested against Excel Viewer (12.0.6219.1000) using the generated files from the test write script https://github.com/SheetJS/js-xlsx/blob/master/tests/write.js .  Here's the generated XLSX file:
[sheetjs.xlsx](https://github.com/SheetJS/js-xlsx/files/1489098/sheetjs.xlsx)

<img width="219" alt="xlvu" src="https://user-images.githubusercontent.com/6070939/33040929-9e10558a-ce0a-11e7-8238-7a730f410ea1.png">

Excel viewer opens the file, but it shows 3.5E+308 for array formulae with no precomputed values.  Those cells were generated with the command:

```js
XLSX.utils.sheet_set_array_formula(ws, 'E1:E4', "TRANSPOSE(A1:D1)");
```

My best guess is that it uses the cached values and does not actually perform the calculations.  It even shows unicode characters properly, like unicode `U+0BEE` ௮.  If you can share a reproduction (a bad file generated by the library) we can take a deeper dive.
