### ISSUE TITLE
Unable to parse xlsx, only partial data returned

### ISSUE THREAD

**Issue by hardyscc** [SheetJS/js-xlsx#881]
I am testing xlsx parser using http://oss.sheetjs.com/js-xlsx/
with
https://www.hkex.com.hk/eng/services/trading/securities/securitieslists/ListOfSecurities.xlsx
however only 8 lines returned

Please give me some hints how to solve it, Thanks!

**Comment by SheetJSDev** [comment]
The file claims the range is `A1:Q8`.  Here is the relevant XML snippet from the worksheet data:

```xml
<x:dimension ref="A1:Q8"/>
```

To recalculate the range programmatically, [see the `update_sheet_range` note](https://github.com/SheetJS/js-xlsx/wiki/General-Utility-Functions#updating-worksheet-range):

```js
function update_sheet_range(ws) {
  var range = {s:{r:20000000, c:20000000},e:{r:0,c:0}};
  Object.keys(ws).filter(function(x) { return x.charAt(0) != "!"; }).map(XLSX.utils.decode_cell).forEach(function(x) {
    range.s.c = Math.min(range.s.c, x.c); range.s.r = Math.min(range.s.r, x.r);
    range.e.c = Math.max(range.e.c, x.c); range.e.r = Math.max(range.e.r, x.r);
  });
  ws['!ref'] = XLSX.utils.encode_range(range);
}
update_sheet_range(wb.Sheets["ListOfSecuritites"]); // range is now A1:N12283
```

Unfortunately the web demo doesn't expose that option, but here is a "repaired" file where the old range A1:Q8 was replaced by the actual file range A1:N12283.  That should work in http://oss.sheetjs.com .

[ListOfSecuritiesNew.xlsx](https://github.com/SheetJS/js-xlsx/files/1458296/ListOfSecuritiesNew.xlsx)

**Comment by hardyscc** [comment]
Thank you so much! it is working!
