### ISSUE TITLE
demo -> browserify  can't find ‘xlsx’ global moudle

### ISSUE THREAD

**Issue by yaderick** [SheetJS/js-xlsx#887]
browserify app.js > browserify.js  but throw err can't find 'xlsx' from ... 
why this？

**Comment by yaderick** [comment]
var X = require('xlsx');

**Comment by SheetJSDev** [comment]
You have to install the library with `npm install xlsx`.  Full reproduction:

```bash
## download demo files
$ curl -O https://raw.githubusercontent.com/SheetJS/js-xlsx/master/demos/browserify/app.js
$ curl -O https://raw.githubusercontent.com/SheetJS/js-xlsx/master/demos/browserify/xlsxworker.js
$ curl -O https://raw.githubusercontent.com/SheetJS/js-xlsx/master/demos/browserify/browserify.html

## install library
$ npm install xlsx

## demo is set up for development, change require statements to use xlsx
$ sed -i.bak "s#'../../'#'xlsx'#" app.js xlsxworker.js

## browserify
$ browserify app.js > browserify.js
$ uglifyjs browserify.js > browserify.min.js
$ browserify xlsxworker.js > worker.js
$ uglifyjs worker.js > worker.min.js
```

**Comment by yaderick** [comment]
Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///Users/yaderick/Documents/Demo/webWorker/worker.min.js' cannot be accessed from origin 'null'.
at xw (file:///Users/yaderick/Documents/Demo/webWorker/browserify.min.js:1:2980)
    at FileReader.reader.onload (
at FileReader.reader.onload (file:///Users/yaderick/Documents/Demo/webWorker/browserify.min.js:1:3502)

**Comment by reviewher** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Browser_compatibility

> Chrome and Opera give an error "Uncaught SecurityError: Failed to construct 'Worker': Script at 'file:///Path/to/worker.js' cannot be accessed from origin 'null'." when you try to run a worker locally. It needs to be on a proper domain.

Uncheck "Use Web Workers" or spin up a local web server

**Comment by yaderick** [comment]
spin up web server  demo is ok
