### ISSUE TITLE
Change the XLSX Headers instead of keys during json_to_sheet

### ISSUE THREAD

**Issue by dstvishnu** [SheetJS/js-xlsx#890]
Hi
I need to have the custom headers instead of the headers generated from the object keys while writing the workbook using json_to_sheet.

I mentioned the sample code which i was trying to use:

XLSX.utils.json_to_sheet(json, {header:headers,cellDates:true});

where headers=['Header'];

But what i get from the Exported Excel is having both the Header column generated from the  _headers_ variable and as well the header column consists of _Object Keys_

**Comment by reviewher** [comment]
The first row will include every header label from the header array as well as every object key.  For example, suppose your data was:

```
var data =[{A:1,B:2},{B:2,C:3}]
```

The function will produce a worksheet that looks like this:

```js
> XLSX.utils.json_to_sheet([{A:1,B:2},{B:2,C:3}])
{ A2: { t: 'n', v: 1 },
  B2: { t: 'n', v: 2 },
  B3: { t: 'n', v: 2 },
  C3: { t: 'n', v: 3 },
  A1: { t: 's', v: 'A' },
  B1: { t: 's', v: 'B' },
  C1: { t: 's', v: 'C' },
  '!ref': 'A1:C3' }
/* sheet shape
XXX| A | B | C |
---+---+---+---+
 1 | A | B | C |
 2 | 1 | 2 |   |
 3 |   | 2 | 3 |
*/
```

The purpose of the header option is to control the column order.  For example, if we want C to be the first column, specify `header:["C"]` to get:

```js
> XLSX.utils.json_to_sheet([{A:1,B:2},{B:2,C:3}], {header:['C']})
{ B2: { t: 'n', v: 1 },
  C2: { t: 'n', v: 2 },
  C3: { t: 'n', v: 2 },
  A3: { t: 'n', v: 3 },
  A1: { t: 's', v: 'C' },
  B1: { t: 's', v: 'A' },
  C1: { t: 's', v: 'B' },
  '!ref': 'A1:C3' }
/* sheet shape
XXX| A | B | C |
---+---+---+---+
 1 | C | A | B |
 2 |   | 1 | 2 |
 3 | 2 |   | 2 |
*/
```

If no row object contains a particular header key, there will be a blank column (this is intended)

**Comment by mitul327** [comment]
Hello,
Thanks for help in advance,

Now, we have multiple tagArrays(I'm using NPM XLSX package )
1. [id:'someid', error: {code:0, success: true}, data: [[1604395417575, 608, 3], [1604395421453, 279, 3]].......50-69K []]
2. [id:'someid 2', error: {code:0, success: true}, data: [[1604395417575, 608, 3], [1604395421453, 279, 3]].......50-69K []]

Eg Note: 1604395417575 - timestamp, 608 - value, 3- quality

![image](https://user-images.githubusercontent.com/10165068/114265742-296b8a80-9a10-11eb-9460-eaaa4436f676.png)

I want to show in Excel sheet as in the below format

![image](https://user-images.githubusercontent.com/10165068/114265940-350b8100-9a11-11eb-9970-22f607ed5321.png)


How can i format? 

Thanks for the help in advance!!
