### ISSUE TITLE
when the csv file's format is Ansi,

### ISSUE THREAD

**Issue by howbuy** [SheetJS/js-xlsx#892]
When the csv file's format is Ansi,but our app is work in utf-8,
Many Chinese strings become garbled,how can i fix it.

**Comment by SheetJSDev** [comment]
The library can't magically guess the codepage by default.  The best approach is to read using our [codepage library](https://github.com/sheetjs/js-codepage) to convert.  If you are running in the web browser, make sure to use the `xlsx.full.min.js` file.  If you are in node, the `cptable` global is exposed once you require `xlsx`.

There are 2 ANSI Chinese codepages: 936 for Simplified Chinese and 950 for Traditional Chinese.  Let's suppose you know it is simplified Chinese.  You can convert the ANSI bytes back to a JS string and parse with:

```js
/* assuming you have a buffer */
var str = cptable.utils.decode(936, buffer);
var wb = XLSX.read(str, {type:"string"});
```

**Comment by howbuy** [comment]
First of all thank you for your reply,

I want to use this library to convert csv format files to json format,
the following is the rewrite of the demo program. 
I insert "var str = cptable.utils.decode(936,data);" before "data = new Uin8Array(data)";
return function do_file(files) {
    rABS = domrabs.checked;
    use_worker = domwork.checked;
    var f = files[0];
    var reader = new FileReader();
    reader.onload = function(e) {

        var data = e.target.result;

        if( !FileReader.prototype.readAsBinaryString) {

            var str = cptable.utils.decode(936,data);//字符编码转utf-8

            data = new Uint8Array(str);
        }
        else
        {
            data = cptable.utils.decode(936,data);//字符编码转utf-8
        }

        if(use_worker) xw(data, process_wb);
        else process_wb(X.read(data, {type:FileReader.prototype.readAsBinaryString ? 'binary' : 'array'}));
    };

    if( !FileReader.prototype.readAsBinaryString){
        reader.readAsArrayBuffer(f);
    }
    else
    {
        reader.readAsBinaryString(f);
    }
};
now the IE 11 browser prompts the error is "The constructor parameter of the typed array is invalid" , 
can your tell me how can I fix this error,
thank you very much



howbuy@qq.com
 
From: SheetJSDev
Date: 2017-11-20 10:49
To: SheetJS/js-xlsx
CC: howbuy; Author
Subject: Re: [SheetJS/js-xlsx] when the csv file's format is Ansi, (#892)
The library can't magically guess the codepage by default. The best approach is to read using our codepage library to convert. If you are running in the web browser, make sure to use the xlsx.full.min.js file. If you are in node, the cptable global is exposed once you require xlsx.
There are 2 ANSI Chinese codepages: 936 for Simplified Chinese and 950 for Traditional Chinese. Let's suppose you know it is simplified Chinese. You can convert the ANSI bytes back to a JS string and parse with:
/* assuming you have a buffer */
var str = cptable.utils.decode(936, buffer);
var wb = XLSX.read(str, {type:"string"});

**Comment by slimtom95** [comment]
Hi @SheetJSDev it's an old issue and let me quote it first.

> The library can't magically guess the codepage by default. The best approach is to read using our [codepage library](https://github.com/sheetjs/js-codepage) to convert. If you are running in the web browser, make sure to use the `xlsx.full.min.js` file. If you are in node, the `cptable` global is exposed once you require `xlsx`.
> 
> There are 2 ANSI Chinese codepages: 936 for Simplified Chinese and 950 for Traditional Chinese. Let's suppose you know it is simplified Chinese. You can convert the ANSI bytes back to a JS string and parse with:
> 
> ```js
> /* assuming you have a buffer */
> var str = cptable.utils.decode(936, buffer);
> var wb = XLSX.read(str, {type:"string"});
> ```

I do agree `the library can't magically guess the codepage`, that's why we have codepage option. To make a non-unicode csv parse correctly, you suggested to convert it before applying XLSX.read. It does works, **but the thing is, the app cannot guess what type of file user would upload neither**. This approach assumes the app already known it would be a csv file, while type detection is handled by XLSX.
**I think this should be a builtin feature, when XLSX.read find out it's a csv file, then, XLSX will using the codepage option(which basically ignored in csv handling now) to decode data.**

regards,
tom

**Comment by xxloveslife** [comment]
> When the csv file's format is Ansi,but our app is work in utf-8,
> Many Chinese strings become garbled,how can i fix it.



> The library can't magically guess the codepage by default. The best approach is to read using our [codepage library](https://github.com/sheetjs/js-codepage) to convert. If you are running in the web browser, make sure to use the `xlsx.full.min.js` file. If you are in node, the `cptable` global is exposed once you require `xlsx`.
> 
> There are 2 ANSI Chinese codepages: 936 for Simplified Chinese and 950 for Traditional Chinese. Let's suppose you know it is simplified Chinese. You can convert the ANSI bytes back to a JS string and parse with:
> 
> ```js
> /* assuming you have a buffer */
> var str = cptable.utils.decode(936, buffer);
> var wb = XLSX.read(str, {type:"string"});
> ```

how to fix   .dbf  file   Chinese strings  became garbled?
