### ISSUE TITLE
Support for Pivot Tables

### ISSUE THREAD

**Issue by sathish804** [SheetJS/js-xlsx#894]
Dear SheetJS,

Please add the support for Pivot Tables reading and writing from a existing xlsx or xlsm file.

Regards,
Sathish

**Comment by sathish804** [comment]
![image](https://user-images.githubusercontent.com/14090242/33177351-a01afc18-d062-11e7-83b6-088c502ad06e.png)
Dear SheetJS,

I was trying to experiment with parsing of the Pivot tables I was able to parse the pivot data needed as shown in the screen shot.

I was checking the relations to write for the pivot data.
I wrote the pivotCache, pivotTables and _rels files for the 2 folders.
I updated the code to write the pivot information into workbook.xml and [Content_Types].xml.

When I looked into the extracted content of the workbook generated I don't see any difference between them but I was getting excel work book corrupted issue and on opening pivotTable xml files are deleted.

Find the attached Input file and output file generated.

Could you please help me to find what went wrong?

[2.zip](https://github.com/SheetJS/js-xlsx/files/1499510/2.zip)

Regards,
Sathish.

**Comment by reviewher** [comment]
We unfortunately don't have the time and resources to contribute to free support for third party code.
