### ISSUE TITLE
readFile issue

### ISSUE THREAD

**Issue by MMrj9** [SheetJS/js-xlsx#895]
I'm trying to parse a xlsx file 

      let workbook = xlsx.readFile(file.path, {type: "binary"});

      console.log(workbook);

When I user readFile  like this, and then log the result. It starts to print infinite commas ",".

Any help woud be great

**Comment by reviewher** [comment]
You're dumping the [entire workbook object](https://docs.sheetjs.com/#workbook-object).  There are some corner cases, like a really sparse worksheet with a cell at XFD1048576, which could print many commas.  Likely you want a snapshot like [array of arrays of a worksheet](https://docs.sheetjs.com/#array-of-arrays-input).
