### ISSUE TITLE
how to rotate cell data?

### ISSUE THREAD

**Issue by surenkhuu** [SheetJS/js-xlsx#897]

**Comment by SheetJSDev** [comment]
Are you trying to rotate the actual cell text (text rotation) or trying to rotate the entire table (moving cells around / transposition)?

**Comment by surenkhuu** [comment]
yeah i trying to rotate the actual cell text (text rotation)

**Comment by nik0145** [comment]
> yeah i trying to rotate the actual cell text (text rotation)

Did you do it ?
I have same problem

**Comment by SheetJSDev** [comment]
text rotation is a style feature included in our [Pro Compendium](https://sheetjs.com/pro) and we cannot say when it will make its way to the open source
