### ISSUE TITLE
How to extract VBA code from object exposed by bookVBA

### ISSUE THREAD

**Issue by jjbeach** [SheetJS/js-xlsx#898]
I'm looking for a way to extract the user-created VBA code in each macro/module. So far, I've been successful in using CFB.parse to return a parsed representation of the raw VBA CFB Object exposed by bookVBA, but I can't quite seem to take that one step further and get the original code. Suggestions?

**Comment by SheetJSDev** [comment]
We have some unreleased code to read and write the normalized VBA containers, including standard modules and forms, but it is definitely outside the scope of this library (the goal is to unify the various file formats, so the natural endpoint for VBA is a normalized data blob for XLS/XLSB/XLSM that you can read in and write out).

In short, there's a small song and dance if you are just interested in extracting the module code (parse the reshaped `/VBA/dir` stream to figure out the types, locations and offsets for each code module then slice and decompress the individual `/VBA/<name>` entries for the code).  That part is discussed in [`[MS-OVBA]`](http://interoperability.blob.core.windows.net/files/MS-OVBA/[MS-OVBA].pdf), and the [blob reshaping logic](https://github.com/SheetJS/js-xlsx/blob/master/bits/59_vba.js) aligns the paths to the spec.  The logic for reading and writing VBA Forms is much more complex and dives into the OLE specs.

If you are interested in discussing further, drop us an email.
