### ISSUE TITLE
Firefox throw an exception: XLSX is not defined

### ISSUE THREAD

**Issue by darrenfei** [SheetJS/js-xlsx#899]
<pre>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<input type="file"onchange="importf(this)" />
    <div id="demo"></div>

</body>
</html>
<script type="text/javascript" src='C:/Users/60052398/Downloads/js-xlsx-master/js-xlsx-master/shim.js'></script>
<script type="text/javascript" src='C:/Users/60052398/Downloads/js-xlsx-master/js-xlsx-master/dist/xlsx.full.min.js'></script>
<script type="text/javascript">
    var wb;
    var rABS = false;

    function importf(obj) {
        if(!obj.files) {
            return;
        }
        var f = obj.files[0];
        var reader = new FileReader();
        reader.onload = function(e) {
            var data = e.target.result;
            if(rABS) {
                wb = XLSX.read(btoa(fixdata(data)), {
                    type: 'base64'
                });
            } else {
                wb = XLSX.read(data, {
                    type: 'binary'
                });
            }

            document.getElementById("demo").innerHTML= JSON.stringify( XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]) );
        };
        if(rABS) {
            reader.readAsArrayBuffer(f);
        } else {
            reader.readAsBinaryString(f);
        }
    }

    function fixdata(data) { 
        var o = "",
            l = 0,
            w = 10240;
        for(; l < data.byteLength / w; ++l) o += String.fromCharCode.apply(null, new Uint8Array(data.slice(l * w, l * w + w)));
        o += String.fromCharCode.apply(null, new Uint8Array(data.slice(l * w)));
        return o;
    }
</script>

</pre>

**Comment by reviewher** [comment]
Check your browser error console -- it probably isn't loading the dist script.  If you have to load from the file system, the proper URL uses the file:/// scheme. But we recommend spinning up a local web server (apache or IIS or even nodejs with the simplehttpserver module)
