### ISSUE TITLE
Differences between IE and Chrome in AJAX demo

### ISSUE THREAD

**Issue by SheetJSDev** [SheetJS/js-xlsx#90]
http://oss.sheetjs.com/js-xlsx/ajax.html

for example, the first column is completely missing in IE.

h/t @wintersm 

See related discussion: https://github.com/SheetJS/js-xlsx/issues/88

**Comment by C0d3ine** [comment]
has a solution been found for this ?

**Comment by SheetJSDev** [comment]
This has been fixed, the ajax demo currently draws the first column in IE6+, see https://github.com/SheetJS/js-xlsx/issues/350 for an explanation of the issue.  Here is a screenshot of IE6

<img width="386" alt="ie6-ajax" src="https://cloud.githubusercontent.com/assets/6070939/23600230/71a5e6ea-0213-11e7-9a23-b73e48a8bcd7.png">
