### ISSUE TITLE
How to remove a row in time parse of excel sheet to JSON

### ISSUE THREAD

**Issue by manisoups** [SheetJS/js-xlsx#902]
suppose, In my Excel sheet, A client is Entry a Duplicate Column. Then How to I fetch and Delete Or remove the Column.

[xls.xlsx](https://github.com/SheetJS/js-xlsx/files/1500849/xls.xlsx)

In The Attachments I have created to Roll no  Column is Duplicated.
And How remove the column in the JSON.

![screenshot](https://user-images.githubusercontent.com/31241314/33199463-8d2a7836-d116-11e7-9569-c874bd632ada.png)

**Comment by sathish804** [comment]
I am using the below modified version of sheet_to_Json function which returns the duplicate rows as name_1,name_2 and ignores the blank rows.

function sheet_to_json(sheet, opts) {
        if(sheet == null || sheet["!ref"] == null) return [];
        var val = {t:'n',v:0}, header = 0, offset = 1, hdr = [], isempty = true, v=0, vv="";
        var r = {s:{r:0,c:0},e:{r:0,c:0}};
        var o = opts || {};
        var raw = o.raw;
        var defval = o.defval;
        var range = o.range != null ? o.range : sheet["!ref"];
        if(o.header === 1) header = 1;
        else if(o.header === "A") header = 2;
        else if(Array.isArray(o.header)) header = 3;
        switch(typeof range) {
            case 'string': r = safe_decode_range(range); break;
            case 'number': r = safe_decode_range(sheet["!ref"]); r.s.r = range; break;
            default: r = range;
        }
        if(header > 0) offset = 0;
        var rr = encode_row(r.s.r);
        var cols = [];
        var out = [];
        var outi = 0, counter = 0;
        var dense = Array.isArray(sheet);
        var R = r.s.r, C = 0, CC = 0;
        if(dense && !sheet[R]) sheet[R] = [];
        for(C = r.s.c; C <= r.e.c; ++C) {
            cols[C] = encode_col(C);
            val = dense ? sheet[R][C] : sheet[cols[C] + rr];
            switch(header) {
                case 1: hdr[C] = C - r.s.c; break;
                case 2: hdr[C] = cols[C]; break;
                case 3: hdr[C] = o.header[C - r.s.c]; break;
                default:
                    if(val == null) continue;
                    vv = v = format_cell(val, null, o);
                    counter = 0;
                    for(CC = 0; CC < hdr.length; ++CC) if(hdr[CC] == vv) vv = v + "_" + (++counter);
                    hdr[C] = vv;
            }
        }
        var row = (header === 1) ? [] : {};
        for (R = r.s.r + offset; R <= r.e.r; ++R) {
            rr = encode_row(R);
            isempty = true;
            if(header === 1) row = [];
            else {
                row = {};
                if(Object.defineProperty) try { Object.defineProperty(row, '__rowNum__', {value:R, enumerable:false}); } catch(e) { row.__rowNum__ = R; }
                else row.__rowNum__ = R;
            }
            if(!dense || sheet[R]) for (C = r.s.c; C <= r.e.c; ++C) {
                val = dense ? sheet[R][C] : sheet[cols[C] + rr];
                if(val === undefined || val.t === undefined) {
                    if(defval === undefined) continue;
                    if(hdr[C] != null) { row[hdr[C]] = defval; isempty = false; }
                    continue;
                }
                v = val.v;
                switch(val.t){
                    case 'z': if(v == null) break; continue;
                    case 'e': continue;
                    case 's': case 'd': case 'b': case 'n': break;
                    default: throw new Error('unrecognized type ' + val.t);
                }
                if(hdr[C] != null) {
                    var len = 0;
                    try{
                        len = v.length;
                    }catch(err){

                    }
                    //if(v == null || v === undefined || ) {
                        if(len ===0) {
                        if(defval !== undefined) row[hdr[C]] = defval;
                        else if(raw && v === null) row[hdr[C]] = null;
                        else continue;
                    } else {
                        row[hdr[C]] = raw ? v : format_cell(val,v,o);
                    }
                    isempty = false;
                }
            }
            if((isempty === false) || (header === 1 ? o.blankrows !== false : !!o.blankrows)) out[outi++] = row;
        }
        out.length = outi;
        return out;
    }

![image](https://user-images.githubusercontent.com/14090242/33207885-bdbc294c-d10f-11e7-8750-1d4503b8522b.png)

![image](https://user-images.githubusercontent.com/14090242/33207903-d090c12c-d10f-11e7-8c0d-85c61915d867.png)

Regards,
Sathsh.

**Comment by SheetJSDev** [comment]
The default behavior is deduplication by suffix: if a header appears multiple times, the first instance will be the original name, the second one will be the name followed by `_1`, the third will be the name followed by `_2`, etc.

If you would prefer a different behavior, you can convert to array of arrays with the `header:1` option.  For the example it would return

```js
[
  ["names", "rollno", "rollno"],
  ["mani", 12, 12],
  ["shyam", 13, 13],
  ...
]
```

Then you can generate any object shape you like.  For example, to preserve the duplicates, you can generate an array for every header column:

```js
var aoa = XLSX.utils.sheet_to_json(ws, {header:1, raw:true});
var headers = aoa[0];
var out = aoa.slice(1).filter(x => x && x.length).map(row => row.reduce((acc,v,i) => { if(acc[headers[i]] == null) acc[headers[i]] = []; acc[headers[i]].push(v); return acc; }, {}));
/*
[ { names: [ 'mani' ], rollno: [ 12, 12 ] },
  { names: [ 'shyam' ], rollno: [ 13, 13 ] },
  { names: [ 'bharathy' ], rollno: [ 14, 14 ] } ]
*/
```
