### ISSUE TITLE
Can't install with @angular/cli

### ISSUE THREAD

**Issue by RChoque** [SheetJS/js-xlsx#903]
I tried to install js-xlsx on an Angular2 project build with angular-cli but I failed and have no clue what I missed.
Every time I launch the command "ng serve" I get the message "Cannot find module 'xlsx'" refering to the line "import * as XLSX from 'xlsx';"

I tried a lot of things : 
- First, I only did "npm install --save xlsx" and import the lib in my component with "import * as XLSX from 'xlsx';"
- Then I tried to add typings with "npm install --save @types/xlsx"
- I also tried to manually add the js file into angular-cli.json : 
"scripts": [
        "../node_modules/xlsx/dist/xlsx.full.min.js"
      ],
- I tried to install jszip because it seems to be a dependency

What am I missing ?
Can somebody help me ?

**Comment by SheetJSDev** [comment]
The demo in https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2 still works in angular2.  Based on https://github.com/SheetJS/js-xlsx/issues/610#issuecomment-345380519 you probably need to add some of the fields from the [demo `tsconfig.json`](https://github.com/SheetJS/js-xlsx/blob/master/demos/angular2/tsconfig.json).

**Comment by RChoque** [comment]
I am sorry, but NO, your demo does not work.
When I launch the 'npm run start' command I get the error "ERROR in src/app/sheetjs.component.ts(5,23): error TS2307: Cannot find module 'xlsx'." exactly the same  that when I do it on my own project.

I tried to modify the tsconfig.json file based on #610 example, without any success.

**Comment by reviewher** [comment]
Can you share a small project reproducing the problem?

**Comment by reviewher** [comment]
@RChoque did you install `xlsx` or `js-xlsx`?  The correct module to install is [`xlsx`](https://www.npmjs.com/package/xlsx):

```bash
$ npm install xlsx
```

**Comment by Vamsidhar949** [comment]
$ npm install xlsx
 not working'
