### ISSUE TITLE
sheet_to_txt written but not in utils

### ISSUE THREAD

**Issue by aj4mq** [SheetJS/js-xlsx#905]
Been having troubles with the sheet_to_json, but I noticed there was a sheet_to_txt designed, but not in the utils. added in my copy, works perfect for my needs.

If this could be fixed in the online copy, would be cool.

Great package.

**Comment by SheetJSDev** [comment]
It could be useful to expose, but there are likely other ways to do what you want.  If you just want a tab-delimited rendering, you can pass the [`FS:"\t"` option to `sheet_to_csv`](https://docs.sheetjs.com/#delimiter-separated-output).  If you want the full behavior, including the codepage conversion, we will accept a PR that adds the export line in the [`utils` definition](https://github.com/SheetJS/js-xlsx/blob/master/bits/90_utils.js#L202)

N.B.: `sheet_to_txt` is directly exposed in the generic `write` and `writeFile` functions using the [`bookType:"txt"` option](https://docs.sheetjs.com/#writing-options).   The specific sheet is controlled by the `sheet` parameter.
