### ISSUE TITLE
Is it possible to export into keyed json?

### ISSUE THREAD

**Issue by matekhong** [SheetJS/js-xlsx#908]
Hi there!

Thanks for creating superb script.
I've a question about keyed json export.

I have data like this
<table style="width:100%">
  <tr>
    <th>Key</th>
    <th>en</th> 
    <th>th</th>
  </tr>
  <tr>
    <td>A-001</td>
    <td>one</td> 
    <td>หนึ่ง</td>
  </tr>
  <tr>
    <td>A-002</td>
    <td>two</td> 
    <td>สอง</td>
  </tr>
  <tr>
    <td>A-003</td>
    <td>three</td> 
    <td>สาม</td>
  </tr>
</table>

After I tried to use this below command

  	XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],  "A");
       console.log(to_json(workbook));

The result will be
{
  "Sheet1": [
    {
      "A": "key",
      "B": "en",
      "C": "th"
    },
    {
      "A": "A001",
      "B": "one",
      "C": "หนึ่ง"
    },
    {
      "A": "A002",
      "B": "two",
      "C": "สอง"
    },
    {
      "A": "A003",
      "B": "three",
      "C": "สาม"
    }
  ]
}

But is it possible to export into keyed json like this below?

{
   "A001": {
      "en": "one",
      "th": "หนึ่ง"
   },
   "A002": {
      "en": "two",
      "th": "สอง"
   },
   "A003": {
      "en": "three",
      "th": "สาม"
   }
}

**Comment by reviewher** [comment]
It is impossible to support every conceivable JS shape, so we won't be adding this particular form to the export.  However, you can use `{header:1}` to generate an array of arrays:

```js
// XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],  {header:1});
[
  ["key", "en", "th"],
  ["A001", "one", "หนึ่ง"],
  ["A002", "two", "สอง"],
  ["A003", "three", "สาม"]
]
```

Once you have that, you can generate whatever shape you like with some JS magic:

```js
var data = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],  {header:1});
var out = data.slice(1).reduce((a,x)=>(a[x[0]]=data[0].slice(1).reduce((h,y,i)=>(h[y]=x[i],h),{}),a),{});
/*
{ A001: { en: 'one', th: 'หนึ่ง' },
  A002: { en: 'two', th: 'สอง' },
  A003: { en: 'three', th: 'สาม' } } */
```

**Comment by matekhong** [comment]
I've never know JS Magic before you told me, Thanks A LOT!
