### ISSUE TITLE
Missing shim.js from npm release

### ISSUE THREAD

**Issue by dackmin** [SheetJS/js-xlsx#911]
Hi guys,

Despite clearly understanding that `shim.js` is not needed when running `js-xlsx` as a node module, as we are all slowly removing bower from all our projects and moving to yarn, I think it still needs to be part of the npm release (e.g removed from `.npmignore`) so we can use it for front-end projects without using bower anymore.

Any thought/opposition about/to this ?

**Comment by SheetJSDev** [comment]
The minified dist files are in the node module so we might as well include the shim.  It'll be in the next release.
