### ISSUE TITLE
& inside html string

### ISSUE THREAD

**Issue by razvanioan** [SheetJS/js-xlsx#914]
I am trying to export / save to XLSX a HTML table, where some values might contain "&" sign
This is always converted into `&amp;` inside XLSX file (due to `innerHTML()` call)

I think that the `htmldecode()` function should also replace `&amp;` with `&`

**Comment by SheetJSDev** [comment]
This appears to be fixed in 0.11.13, testing against http://sheetjs.com/demos/table .  There are plenty of missing html entities but we'll grind through them in the coming versions.
