### ISSUE TITLE
Newline parsing does not handle entity reference

### ISSUE THREAD

**Issue by pbrickell** [SheetJS/js-xlsx#915]
Use Libre Office to save a spreadsheet with a text cell containing newlines. The file will contain &#10; to represent the newlines. Both Excel and Libre Office understand these to be new lines. js-xlsx treats them as text.

**Comment by SheetJSDev** [comment]
You are probably using an older version of the library.  Can you test against http://oss.sheetjs.com/js-xlsx/ and see if the newlines show up?

Here's a sample file from LO 5.2.4.2: [newline.xlsx](https://github.com/SheetJS/js-xlsx/files/1543884/newline.xlsx)

The shared string table shows entities:

```xml
<si><t xml:space="preserve">|&#10;|</t></si>
```

And the webpage shows the correct newline characters:

<img width="112" alt="" src="https://user-images.githubusercontent.com/6070939/33786435-2cd408fe-dc37-11e7-8fb3-69e23a1cc3a8.png">

**Comment by pbrickell** [comment]
Apologies. You are quite right. I thought I had updated but had not. Once I got the latest it works perfectly.
