### ISSUE TITLE
Reading information from multiple rows when mixed

### ISSUE THREAD

**Issue by Irikos** [SheetJS/js-xlsx#922]
First of all, thanks for the great job! You've saved me a lot of time. 

I've recently received an xlsx that I am unable to read completely. It might be a different or weird format, but not sure.

Anyway, the main information takes 4 rows(A10:13) and can be easily accessed. However, one of the columns has information on each of these rows as well (H10, H11, H12, H13). I can read all the information in the file, except when it comes to the H column, out of which I can only read the first row. 
I attached two pictures to clear up the explanation. Any ideas on the approach? The information is basically not visible in the workbook.
![image](https://user-images.githubusercontent.com/2596078/34089505-347fb4a2-e3b9-11e7-88c2-d67ef3e23ae8.png)
![image](https://user-images.githubusercontent.com/2596078/34089510-3c47b02c-e3b9-11e7-8bf8-b97a3baee7f4.png)

P.S. I also take suggestions in renaming the issue.

**Comment by SheetJSDev** [comment]
You're describing merge cells.  It looks like cells G10:G13 are merged but H10:H13 are not.  The merge cells are accessible from the topleft cell of the range (in this case G10:G13).

It's complex enough that you should [dig into the worksheet object directly](https://docs.sheetjs.com/#common-spreadsheet-format)

<img width="571" alt="" src="https://user-images.githubusercontent.com/6070939/34116676-4975d14c-e3e7-11e7-8c34-8d274c8de720.png">

The worksheet `!merges` key holds an array of the merge ranges:

```js
// console.log(ws['!merges']);
[ { s: { c: 6, r: 9 }, e: { c: 6, r: 12 } },
  { s: { c: 0, r: 9 }, e: { c: 0, r: 12 } },
  { s: { c: 1, r: 9 }, e: { c: 1, r: 12 } },
  { s: { c: 2, r: 9 }, e: { c: 2, r: 12 } },
  { s: { c: 3, r: 9 }, e: { c: 3, r: 12 } },
  { s: { c: 4, r: 9 }, e: { c: 4, r: 12 } },
  { s: { c: 5, r: 9 }, e: { c: 5, r: 12 } } ]
// console.log(ws['!merges'].map(r => XLSX.utils.encode_range(r)))
[ 'G10:G13',
  'A10:A13',
  'B10:B13',
  'C10:C13',
  'D10:D13',
  'E10:E13',
  'F10:F13' ]
```

To access the individual cells, use the cell address:

```js
// console.log(["G10", "H10", "H11", "H12"].map(x => ws[x].v))
[ 7, 'Can only read this', 'But not this', 'Or this' ]
```

Note that for the merge cells you need to access from the top.  `G11:G13` are nonexistent

**Comment by Irikos** [comment]
Thanks for the detaled reply! My problem was a direct cause of #929  (I did not know at the time of writting this) and fortunately it ended up being solved with the fix.

All the best!
