### ISSUE TITLE
gsheet support [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [SheetJS/js-xlsx#924]
Would it be possible to add gsheet support as xlsx to this awesome library?

**Comment by SheetJSDev** [comment]
"gsheet support as xlsx" can mean:

A) interoperating with google sheets via XLSX: if the library can't read a file generated by google sheets that's a bug.  It may or may not be a bug if google sheets can't read a file generated by this library.  In any case, file an issue if you come across a bad import or export.

B) programmatically interacting with google sheets.  This is definitely out of scope, but if you follow the quickstart in https://developers.google.com/sheets/api/quickstart/js or https://developers.google.com/sheets/api/quickstart/nodejs , you can [request or put arrays of arrays](https://developers.google.com/sheets/api/samples/reading#read_a_single_range) (which line up with `aoa_to_sheet` and `sheet_to_json` with `header:1`)

C) .gsheet file support:  The .GSHEET file is a JSON file with a `url` key corresponding to a google drive URL and a `doc_id` key corresponding to the Google Sheet key, so processing .GSHEET files means dealing with the google sheets API

**Comment by damianobarbati** [comment]
Oh I see now, thanks @SheetJSDev for clarifying: I thought gsheet files actually had the payload like any file instead of carrying just the metadata to interact with gdoc service.
Thanks and sorry for the noise!
