### ISSUE TITLE
page layout: sheet right-to-left

### ISSUE THREAD

**Issue by mghayour** [SheetJS/js-xlsx#927]
hi
i need to export right-to-left sheet, that A1 column is in right side of page (not left side)
in microsoft excel we have this option in "Pagelayout" tab > "sheet options" > "Sheet-Right-to-Left"
i searched all readme and codes for "righttoleft" or sth like that, but nothing was founded

are we have this option in sheetjs ?

thank you.

**Comment by mghayour** [comment]
i found it !

i changed source code.
its works correctly.

we should change this line 
https://github.com/SheetJS/js-xlsx/blob/b3873ea61583549a0ce1790b724e2a129ee38eb5/bits/67_wsxml.js#L196

from
`return writextag("sheetViews", writextag("sheetView", null, {workbookViewId:"0"}), {});`
to
`return writextag("sheetViews", writextag("sheetView", null, {workbookViewId:"0", rightToLeft: "1"}), {});`


but, as you know, it always use Right-to-Left, you can add an option for it

**Comment by reviewher** [comment]
The `sheetViews` block should be generated dynamically.  If you have patience, we could accept a PR with the following changes:

The spec 18.3.1.88 states that there can be multiple sheet views, so the best place to store the information would be as an array within the [`Workbook` attributes](https://docs.sheetjs.com/#workbook-level-attributes), namely `Workbook.Views`:

```js
var wb = {
    Workbook: {
        Views: [
            {RTL:true}
        ]
        ...
    }
    ...
    Sheets: {...},
    SheetNames: [ ... ]
}
```

This would correspond to the following code:

```js
var sview = {workbookViewId:"0"};
if( (((wb||{}).Workbook||{}).Views||[])[0] ) sview["rightToLeft"] = wb.Workbook.Views[0].RTL ? "1" : "0";
return writextag("sheetViews", writextag("sheetView", null, sview), {});
```

And your code would use:

```js
function set_right_to_left(wb/*:Workbook*/) {
    if(!wb.Workbook) wb.Workbook = {};
    if(!wb.Workbook.Views) wb.Workbook.Views = [];
    if(!wb.Workbook.Views[0]) wb.Workbook.Views[0] = {};
    wb.Workbook.Views[0].RTL = true;
}
```

**Comment by mghayour** [comment]
thank u very much 👍

**Comment by bresleveloper** [comment]
Hi huys, the issue doesnt seems to be resolved.
I tried to add `wb.Workbook.Views[0].RTL = true;` but with no results.
when I changed (in the depths of the `dist`) to
`return writextag("sheetViews", writextag("sheetView", null, {workbookViewId:"0", rightToLeft: "1"}), {});`
it worked

**Comment by mahmoudmohamedramadan** [comment]
I have written the code that will do that after many tries, the code must be like this so

```JAVASCRIPT
var wb = { Workbook: { Views: [{ RTL: true }] }, Sheets: {}, SheetNames: [] }
var worksheet = XLSX.utils.aoa_to_sheet([insert_your_data_here]);

XLSX.utils.book_append_sheet(wb, worksheet, "Sheet 1");
XLSX.writeFile(wb, "excel_template.xlsx");
```

**Comment by JonathanDn** [comment]
Is this capability of changing the main X/Y axis from top left to top right (LTR To RTL) still supported in the community version?

**Comment by JonathanDn** [comment]
@mahmoudmohamedramadan 
Do you know if it is mandatory to first work with **aoa** and use the 2nd row you shared that utilizes `aoa_to_sheet(...)` in order for the RTL customization to work properly?
