### ISSUE TITLE
Data import issue

### ISSUE THREAD

**Issue by jaydippalgit** [SheetJS/js-xlsx#928]
Data import  from excel is working on Firefox browser but not working on the Chrome browser. Please suggest how to fix this.

**Comment by reviewher** [comment]
Just checked the demos at http://oss.sheetjs.com/ and http://oss.sheetjs.com/js-xlsx, both work in FF 26+.  FF26+ is needed for the grid for the first page, but the second works in FF18+.  It's likely an issue with your page.  If you can share the web console output and some code we could revisit the issue.
