### ISSUE TITLE
Reading data from html generated xls tables

### ISSUE THREAD

**Issue by Irikos** [SheetJS/js-xlsx#929]
Hello,

Is there any way to read the data from html generated tables, when the data in the td is separated on multiple lines using `<br />`?
From my tests so far it is only possible to read the first row.

Of course I could use jquery for that but was wondering since if there isn't a solution maybe I can try and implement one, for cases when you cannot know upfront how the xls(x) file was created

All the best!

**Comment by Irikos** [comment]
Sorry, duplicate, for some reason I couldn't find the previous answer. (but did now)

**Comment by SheetJSDev** [comment]
The issue can be reproduced:

```js
var table = "<table><tr><td>foo<br/>bar</td><td>baz</td></tr></table>";
var wb = XLSX.read(table, {type:"string"});
console.log(wb.Sheets.Sheet1.A1.v); // should be "foo\nbar"
```

The most recent commit resolves it.  Once the CI tests pass we'll push to npm

**Comment by Irikos** [comment]
Great, thanks! 

Also, while we're at it, XLSX.read only starts reading from the `<table>` tag. Any information that was placed before that is not accessible (although visible in .xls)

**Comment by Irikos** [comment]
Works like a charm now.
