### ISSUE TITLE
Saving an XLSX file doesn't create sharedStrings.xml file under xl folder.

### ISSUE THREAD

**Issue by rajiv82** [SheetJS/js-xlsx#932]
Using XLSX.write(wb, {bookType:'xlsx', type:'binary'}) to write XLSX doesn't save sharedStrings.xml file under xl folder. It seems like a Bug.

In write_zip function, we have:
opts.Strings = []; opts.Strings.Count = 0; opts.Strings.Unique = 0;

Down the line we have:
 if(opts.Strings != null && opts.Strings.length > 0) {
                f = "xl/sharedStrings." + wbext;
                zip.file(f, write_sst(opts.Strings, f, opts));
                ct.strs.push(f);
                add_rels(opts.wbrels, -1, "sharedStrings." + wbext, RELS.SST);
        }

So, it never creates sharedStrings.xml file.

**Comment by reviewher** [comment]
https://docs.sheetjs.com/#writing-options
