### ISSUE TITLE
IE9 not working 

### ISSUE THREAD

**Issue by chrystiansweick** [SheetJS/js-xlsx#934]
in my IE9 is not working the XLSX download.
page of teste same not work... the download button is not showing
Can you help me?
![image](https://user-images.githubusercontent.com/28606830/34412587-49a14e36-ebc5-11e7-82c4-e872a3c7b565.png)

**Comment by reviewher** [comment]
> - IE6-9 require a Flash-based shim to download files.  This demo uses Downloadify.js

You probably don't have Flash installed.

IE8 screenshot: <img width="356" alt="" src="https://user-images.githubusercontent.com/24845478/34414326-b6200bc4-ebb6-11e7-8830-7c7f82f95109.png">
