### ISSUE TITLE
How to read XLS？try but fail.

### ISSUE THREAD

**Issue by linmufeng326** [SheetJS/js-xlsx#935]
How to read XLS？
I use xlsx.full.min.js and shim.min.js.
try but fail.

**Comment by reviewher** [comment]
You need to be more specific.  Does your file work with the http://oss.sheetjs.com/ or http://oss.sheetjs.com/js-xlsx demo?  If it's failing in your project, is there an error log?

**Comment by linmufeng326** [comment]
I use this "https://github.com/SheetJS/js-xlsx/blob/master/index.html",I suppose,beacause the file is protected by the password,and the wrong content is 
`(index):164 Error: File is password-protected at parse_workbook (xlsx.js:15275) at parse_xlscfb (xlsx.js:15921) at read_cfb (xlsx.js:18819) at Object.readSync [as read] (xlsx.js:18886) at DedicatedWorkerGlobalScope.onmessage (xlsxworker.js:12)`

**Comment by yurachumak** [comment]
Hi @linmufeng326
Did you find how to open protected excel file?
