### ISSUE TITLE
Bug att xlsx.read

### ISSUE THREAD

**Issue by benjaminleetmaa** [SheetJS/js-xlsx#938]
ERROR TypeError: Cannot read property 't' of undefined
    at parse_workbook (xlsx.js:15493)
    at parse_xlscfb (xlsx.js:15924)
    at read_cfb (xlsx.js:18822)
    at Object.readSync [as read] (xlsx.js:18889)

Fixed it by checking t first.

```
// if (sst[val.isst] && sst[val.isst].t) {	
	temp_val=make_cell(sst[val.isst].t, val.ixfe, 's');
	temp_val.XF = XFs[temp_val.ixfe];
	if(BIFF2Fmt > 0) temp_val.z = BIFF2FmtTable[(temp_val.ixfe>>8) & 0x1F];
	safe_format_xf(temp_val, options, wb.opts.Date1904);
	addcell({c:val.c, r:val.r}, temp_val, options);
// }
```

**Comment by SheetJSDev** [comment]
Can you share a file that triggers this error?

**Comment by benjaminleetmaa** [comment]
Where can i send them? xls is unsupported.

**Comment by SheetJSDev** [comment]
Attach in an email to hello@sheetjs.com
