### ISSUE TITLE
 Cannot find module 'xlsx'

### ISSUE THREAD

**Issue by ankita199** [SheetJS/js-xlsx#939]
I am using "@angular/cli": "^1.2.2" version and  "xlsx": "^0.11.16". when i am trying to import xlsx module it is giving 'Cannot find module xlsx' in ts file

**Comment by reviewher** [comment]
Test the demos for [Angular 2+](https://github.com/SheetJS/js-xlsx/tree/master/demos/angular2) and [plain TypeScript](https://github.com/SheetJS/js-xlsx/tree/master/demos/typescript) -- there may be some missing entry in tsconfig.json
