### ISSUE TITLE
Export JSON to CSV 

### ISSUE THREAD

**Issue by ankita199** [SheetJS/js-xlsx#943]
Hi,

I am trying to export JSON to CSV file.
    const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
    const csvOutput: string = XLSX.utils.sheet_to_csv(worksheet);
csvOutput successfully generate comma seperated values but XLSX.write function needs only workbook as a object. Is any other way to generate it?

**Comment by reviewher** [comment]
As the names imply, `json_to_sheet` generates a worksheet object and `sheet_to_csv` reads a sheet object.  `read` and `write` deal with workbook objects.  You can generate a workbook manually:

```typescript
/* Raw object */
const wb1: XLSX.WorkBook = {
    Sheets: { Sheet1: worksheet },
    SheetNames: ["Sheet1"] }
};

/* New Workbook using the functions */
const wb2: XLSX.WorkBook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb2, worksheet, "Sheet1");
```

https://jsfiddle.net/uxnf00z8/ is a complete jsfiddle to generate an XLSX workbook from JS object array

**Comment by ankita199** [comment]
@reviewher but i want to export to csv format from json

**Comment by reviewher** [comment]
The example code you gave in your first comment generates CSV:

```typescript
const worksheet: XLSX.WorkSheet = XLSX.utils.json_to_sheet(json);
const csvOutput: string = XLSX.utils.sheet_to_csv(worksheet);
```

If you want to force a download, there are multiple techniques.  Here's an example using the FileSaver.js library: https://jsfiddle.net/7t0n3vqk/

```js
/* original data */
var data = [
    {"name":"John", "city": "Seattle"},
    {"name":"Mike", "city": "Los Angeles"},
    {"name":"Zach", "city": "New York"}
];

/* make the worksheet */
var ws = XLSX.utils.json_to_sheet(data);

/* write workbook (use type 'binary') */
var csv = XLSX.utils.sheet_to_csv(ws);

/* generate a download */
function s2ab(s) {
	var buf = new ArrayBuffer(s.length);
	var view = new Uint8Array(buf);
	for (var i=0; i!=s.length; ++i) view[i] = s.charCodeAt(i) & 0xFF;
	return buf;
}

saveAs(new Blob([s2ab(csv)],{type:"application/octet-stream"}), "sheetjs.csv");
```

**Comment by ggregoire** [comment]
For anybody arriving here from Google:

```javascript
const generateCSV = () => {
  const wb = XLSX.utils.book_new()

  const ws = XLSX.utils.json_to_sheet([{ a: 1, b: 2 }])

  XLSX.utils.book_append_sheet(wb, ws, 'test')

  XLSX.writeFile(wb, 'test.csv')
}
```

**Comment by michaelscheurer** [comment]
> 
> 
> For anybody arriving here from Google:
> 
> ```js
> const generateCSV = () => {
>   const wb = XLSX.utils.book_new()
>   const ws = XLSX.utils.json_to_sheet([{ a: 1, b: 2 }])
>   XLSX.utils.book_append_sheet(wb, ws, 'test')
>   XLSX.writeFile(wb, 'test.csv')
> }
> ```

@ggregoire Do you know how to set the csv delimiter to a semicolon? I wasn't able to find a way to write the csv with semicolons instead of comma.

Thanks for your help

**Comment by schalivendri** [comment]
@michaelscheurer Was you able to set semicolon instead of a comma? I have a similar usecase. Please let me know. Thanks!

**Comment by justLbee** [comment]
> @michaelscheurer Was you able to set semicolon instead of a comma? I have a similar usecase. Please let me know. Thanks!

Hello!
if you or anyone stiil trying to find the solution for csv files with ';' delimiters, here is my solution:

**Comment by juliovedovatto** [comment]
For anybody arriving here from Google, there is a documentation entry for it https://docs.sheetjs.com/docs/api/write-options/#writing-options

>  * FS and RS apply to CSV and Text output formats. The options are discussed in ["CSV and Text"](https://docs.sheetjs.com/docs/api/utilities/csv#delimiter-separated-output)

To define a **custom separator for the CSV file**, simply enter the `FS` property in the `XLSX.writeFile` options. Example: 

```js
const filename = 'test.csv`;

XLSX.writeFile(wb, filename, { bookType: 'csv', FS: ';' });
```
