### ISSUE TITLE
Generate Excel sheet with Headings

### ISSUE THREAD

**Issue by rajuyadav-orchestratec** [SheetJS/js-xlsx#946]
Hi all,
How I can get data in the following format

**Employee Details**
Emp Name       Emp Sal
xyz                    1000
abc                    2000

Any help would be appreciated.

**Comment by reviewher** [comment]
https://jsfiddle.net/hsgosmp5/ live example:

```js
var Heading = [
  ["Employee Details"],
  ["Emp Name", "Emp Sal"]
];
var Data = [
  {name:"xyz", sal:1000},
  {name:"abc", sal:2000}
];
var ws = XLSX.utils.aoa_to_sheet(Heading);
XLSX.utils.sheet_add_json(ws, Data, {
  header:["name", "sal"],
  skipHeader:true,
  origin:-1
 });

var wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, "SheetJS");
var wbout = XLSX.write(wb, {bookType:'xlsx', type:'array'});
saveAs(new Blob([wbout],{type:"application/octet-stream"}), "issue946.xlsx");
```

**Comment by rajuyadav-orchestratec** [comment]
Thank you, saved my day

**Comment by rajuyadav-orchestratec** [comment]
Hi,

I got other requirement where, I need to show excel data saved in multiple
sheets as follows

In first sheet(Named Staff Details) I need to store the data as follows

[image: Inline image 1]


In Second Sheet(Named Student Details) I need to store the data as follows

[image: Inline image 2]

Can you please help me how to achieve this.

Thanks and Regards,
Raju Yadav J

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by MrPeproni** [comment]
@rajuyadav-orchestratec were you able to achieve your last requirement?
