### ISSUE TITLE
Support for older versions for firefox

### ISSUE THREAD

**Issue by monis01** [SheetJS/js-xlsx#950]
Hi
I have not tested for older versions browser compaitibilities, does it work? any words on this?
Thanks

**Comment by reviewher** [comment]
Newer features (like ArrayBuffers and the `'array'` input type) notwithstanding, it should work on [Firefox 18+](https://docs.sheetjs.com/#tested-environments):

- NodeJS 0.8, 0.10, 0.12, 4.x, 5.x, 6.x, 7.x, 8.x
- IE 6/7/8/9/10/11 (IE 6-9 require shims)
- Chrome 24+ (including Android 4.0+)
- Safari 6+ (iOS and Desktop)
- Edge 13+, FF 18+, and Opera 12+

https://saucelabs.com/browser-matrix/sheetjs.svg

Only the latest version of FF is regularly tested, but you can run the browser test suite from http://oss.sheetjs.com/js-xlsx/tests/ in older versions
