### ISSUE TITLE
How to change currency format for numbers using Import xlsx file?

### ISSUE THREAD

**Issue by akwa770** [SheetJS/js-xlsx#951]
Hi, 
I need to collect currency format fields from xlsx file and turn it to number. how can Ido that?

Thanks

**Comment by reviewher** [comment]
Currency cells are number cells with a currency format.  The easiest way to change the format of a particular cell is to read the file with [the options `cellNF:true, cellText:false`](https://docs.sheetjs.com/#parsing-options).  Those two options save all of the original number formats and suppress formatted text generation.  Then, you can go back and change the format for the cells you want to mess with.

For example, this worksheet:
<img width="153" alt="" src="https://user-images.githubusercontent.com/24845478/34811117-40cb2540-f66d-11e7-95ad-1651b54114da.png">

Using nodejs to read in the data (you can replace this part with the browser commands):

```js
var XLSX = require('xlsx');
var wb = XLSX.readFile("issue951.xlsx", {cellNF:true, cellText:false});
var ws = wb.Sheets["Sheet1"];
```

To change a cell's number format, set the `z` property of the cell to the format you want to use.  For example, let's change cell A1 to use the currency format `$0.00` and change B1 to use the `General` format:

```js
ws["A1"].z = "$0.00";
ws["B1"].z = "General";
```

The formatted text is generally stored in the `w` field but isn't automatically updated when you change the number format.  You can do it manually:

```js
delete ws["A1"].w; // delete old formatted text if it exists
XLSX.utils.format_cell(ws["A1"]); // refresh cell
console.log(ws["A1"].w); // '$1.00'
```

Utility functions like [`sheet_to_csv`](https://docs.sheetjs.com/#delimiter-separated-output) will only reformat cells if the formatted text is deleted, so be sure to delete the old text every time you want to change the format.

**Comment by akwa770** [comment]
Thank you very much
