### ISSUE TITLE
How to Disable the Column Headers Taking from Object.Keys() in json_to_sheet()

### ISSUE THREAD

**Issue by kishoreaoe** [SheetJS/js-xlsx#953]
Hi In Current Version,
Is there any provision to Delete Automatic Column Headers(which was taking based on Key Value of the JSON.)
Just I need to my JSON data with out any column headers.

Thanks,
Kishore Kumar.K

**Comment by reviewher** [comment]
Use the [`skipHeader` option](https://docs.sheetjs.com/#array-of-objects-input).  

It was added in the 0.11.17 release so you may need to update.

https://jsfiddle.net/5kuk89sv/ is a live example:

```js
var Data = [
	{name:"abc", value:123},
	{name:"def", value:456}
];

var wb = XLSX.utils.book_new();

var ws1 = XLSX.utils.json_to_sheet(Data);
XLSX.utils.book_append_sheet(wb, ws1, "Header");

var ws2 = XLSX.utils.json_to_sheet(Data, {skipHeader:1});
XLSX.utils.book_append_sheet(wb, ws2, "No Header");

var wbout = XLSX.write(wb, {bookType:'xlsx', type:'array'});
saveAs(new Blob([wbout],{type:"application/octet-stream"}), "issue953.xlsx");
```
