### ISSUE TITLE
Removing Commas from Cells before CSV Conversion

### ISSUE THREAD

**Issue by DarthFisticuffs** [SheetJS/js-xlsx#954]
I'm trying to use js-xlsx to convert some Excel sheets to CSV, and then from there I'll parse the CSV data. The problem that I'm having is that there are commas in some of the cells in the Excel sheet, so I can't reliably parse the resulting CSV. Is there a way to either remove/convert the commas when the Excel file gets interpreted, or select a different delimiter for the CSV file, without having to manually do it in Excel? I'm trying to make a one-step system for the user, and I'd rather they not need to even open the Excel file for this to work.

**Comment by SheetJSDev** [comment]
When generating CSV, cells with commas are automatically wrapped in double quotes.  This follows Excel and RFC4180, so any reasonable CSV parser should be able to handle it.

If you're using `awk` or some other simple tool for post-processing, you can control the delimiter with the [`FS` option](https://docs.sheetjs.com/#delimiter-separated-output).  The CSV writer will only wrap cells including the field and record separator characters in quotes.  You can always choose a non display character like the ASCII unit separator `\x1F`

Here's a demo fiddle: https://jsfiddle.net/0n4vxkrw/
