### ISSUE TITLE
XLSXML - corrupt file

### ISSUE THREAD

**Issue by ankita199** [SheetJS/js-xlsx#956]
Hi,
I am using alasql in my angular 4 project for downloading xls file with formatting. this is working but when i am opening the file it says 'The file you are trying to open 'filename.xls' has a different format than specified by the extension. Verify that the file is not corrupted and it is from a trusted source before opening the file.Do you want to open the file now?'

I am opening this issue because internally they are using xlsx library. If i am trying to use xlsx library directly then it not including formatting options and 'xlsx-style' is no more maintained library. Please help me out to fix this issue.

i dont want to show this warning to my clients..is this bug or what?

let mystyle = {
headers: true,
column: {
style:{
Font:{
Bold:"1",
Color:"#DCDCDC",
Size: "10"
}
}
}
};
alasql( 'SELECT * INTO XLSXML("' + fileName + '",?) FROM ?', [mystyle,json] );

**Comment by reviewher** [comment]
There are client workarounds in [this superuser post](https://superuser.com/a/1103930), otherwise you can send with the correct `.xml` extension.

**Comment by ankita199** [comment]
@reviewher  am i doing something wrong with this code? filename is a variable which is generated dynamically and have .xls extension.

**Comment by bheda91** [comment]
@reviewher How can we send correct .xml extension? Can you please provide some demo or example?
