### ISSUE TITLE
why cell.s set cell style don't work?

### ISSUE THREAD

**Issue by juanjuaner** [SheetJS/js-xlsx#957]
```
cell.s = {
            "fill": {
              "patternType": "solid",
              "bgColor": {
                rgb: '003d79'
              },
              "fgColor": {
                rgb: '003d79'
              }
            },
            "font": {
              "color": {
                rgb: 'fff'
              },
              "bold": true
            }
          };
```

**Comment by juanjuaner** [comment]
@SheetJSDev please give me a hand

**Comment by richarepo** [comment]
@reviewher when you are going to work on styles, as this now become blocker for my project to add styles.

**Comment by 125037225** [comment]
I'm also bewildered by this

**Comment by juanjuaner** [comment]
didn't support set style now, and [branch support style](https://github.com/SheetJS/js-xlsx/pull/263) hasn't be merged by now ,we can use[ xlsx-style](https://www.npmjs.com/package/xlsx-style) @richarepo @125037225

**Comment by 125037225** [comment]
thankyou @juanjuaner  ！

**Comment by kawtakwar** [comment]
Having same problem. Is there any workaround ??

**Comment by billclinton8** [comment]
I quote xlxs-style with NPM, xlxs-style is wrong, and the error is a hint:**This relative module was not found:
* ./cptable in ./node_modules/_xlsx-style@0.8.13@xlsx-style/dist/cpexcel.js**，the file  is in existence

**Comment by dtJon** [comment]
I couldn't find any of the color-supporting branches that were compatible with other tools I am using that are dependent on js-xlsx (and those branches are pretty old) so I fitted it today.  

I can understand all of us wanting to help each other avoid the ~6 hours of work it took me.  In the end it was pretty straightforward so it's a shame that this isn't included.  I do appreciate the quality and extensiveness of this tool so I can't really complain!

BTW the trick for me to get background colors working was A: to modify the <fills> xml in write_sty_xml with the details of the background colors, B: change the get_cell_style method to accept a "fillId" which I'm passing in as a property on the cell (matches the index of the "fill" node), and C: comment out the following line in the write_sty_xml method which was causing it to ignore everything but the number formats:
`//` for(i = 0; i != len; ++i) if(styles[i].numFmtId === z) return i;

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)

@dtJon It's a shame that companies and people profiting off of open source expect the open source developers to continue to provide free support and development work.  We have to carefully weigh our passion for open source with the realities of life.

**Comment by ozshabat** [comment]
If I knew this shit before i wouldn't use your library. For the sake of the open source community, write it in your github front page
