### ISSUE TITLE
Error: This method has been removed in JSZip 3.0, please check the upgrade guide.

### ISSUE THREAD

**Issue by kadir950** [SheetJS/js-xlsx#960]
After upgrading jszip.js  to 3.0 

`XLSX.write(book, bookOptions)` throws the following error.

> Error: This method has been removed in JSZip 3.0, please check the upgrade guide.

**Comment by reviewher** [comment]
JSZip 3 removed the sync interface entirely.  Use the dist bundle [`xlsx.full.min.js`](https://unpkg.com/xlsx/dist/xlsx.full.min.js) or use the included version in the repo.

**Comment by kadir950** [comment]
Do you have plan to upgrade xlsx.js to integrate with jszip.js 3.0 in the near future?

**Comment by jameskirkpatrick23** [comment]
@reviewher not really sure I understand your message here. Would I be specifically requiring a different part of your repo in order to use the XLSX.write function? ex) import {Write} from 'xlsx'?

**Comment by rochejul** [comment]
+1 to upgrade to the last version of jszip
