### ISSUE TITLE
How to skip header and keep character encoding when export csv

### ISSUE THREAD

**Issue by ToujouAya** [SheetJS/js-xlsx#969]
How to skip header when export json to csv

My code 

```
/* make the worksheet */
                let worksheet = XLSX.utils.json_to_sheet(data, {skipHeader: true});

                /* add to workbook */
                // let wb = XLSX.utils.book_new();
                // XLSX.utils.book_append_sheet(wb, worksheet, "label");
                console.log(worksheet)
                /* write workbook (use type 'binary') */
                let wbout = XLSX.utils.sheet_to_csv(worksheet);
                // let wbout = XLSX.write(wb, {bookType: 'xlsx', type: 'binary'});
                console.log(wbout)
                return wbout
```
I tried to use skipHeader option but it's not work 

And how to keep the charcter encoding when export. 

![default](https://user-images.githubusercontent.com/21350606/35385503-1b8ea88a-01fb-11e8-99cc-6a301c6ea425.PNG)

![default](https://user-images.githubusercontent.com/21350606/35385560-447d5eee-01fb-11e8-9ff9-2fe4769e770a.PNG)

![default](https://user-images.githubusercontent.com/21350606/35385573-4fbdc7bc-01fb-11e8-9908-c78426cebf24.PNG)

**Comment by SheetJSDev** [comment]
Here's a complete example: https://jsfiddle.net/yvc9rtar/

`skipHeader` was added recently, update the library.

`sheet_to_csv` generates CSV without any BOM character.  Excel defaults to local codepage when reading a CSV, so you need to manually prepend `"\ufeff"` to the output:

```js
var data = [
  {"A": "வணக்கம்", "B": "สวัสดี"},
  {"A": "你好", "B": "가지마"},
];

/* convert to worksheet */
var ws = XLSX.utils.json_to_sheet(data, {skipHeader:true});

/* generate CSV */
let wbout = XLSX.utils.sheet_to_csv(ws);

/* prepend UTF-8 BOM */
let str = "\ufeff" + wbout;

/* force a download */
saveAs(new Blob([str],{type:"application/octet-stream"}), "out.csv");
```

**Comment by ToujouAya** [comment]
@SheetJSDev 
Thanks you.
If I open file csv in excel and excel automatic convert text value date. How could I keep text value format

**Comment by SheetJSDev** [comment]
@ToujouAya you have to push a `=""`.  The value `1/25` will be interpreted as a date, but the value `="1/25"` will be treated as a formula whose result is the string `1/25`.

```js
var possible_date_columns = [ "delivery_date" ]; // add other possible date columns here
data.forEach(function(row) {
  possible_date_columns.forEach(function(field) {
    if(row[field]) row[field] = '="' + (""+row[field]).replace(/"/g,'""') + '"';
  });
});
let worksheet = XLSX.utils.json_to_sheet(data, {skipHeader: true});
```
