### ISSUE TITLE
Excel worksheet doesn't look as desired

### ISSUE THREAD

**Issue by prajwal78** [SheetJS/js-xlsx#970]
Hi, 
 I want my excel to look like below in the image:

  
![image](https://user-images.githubusercontent.com/10049692/35396337-dbdb8860-01ec-11e8-9512-00d8a6359976.png)

My data format looks like this:
   `[['Personal Details'],
[{
    Names: 'Prajwal',
    Age: 26,
    Gender: 'Male',
    Ethincity: 'Asian'
},
{
    Names: 'Viktoria',
    Age: 23,
    Gender: 'Female',
    Ethincity: 'European'
}
{
    Names: 'Lasse',
    Age: 24,
    Gender: 'Male',
    Ethincity: 'European'
}]`
[{
    Names: 'Prajwal',
    Age: 26,
    Gender: 'Male',
    Ethincity: 'Asian'
},
{
    Names: 'Viktoria',
    Age: 23,
    Gender: 'Female',
    Ethincity: 'European'
}
{
    Names: 'Lasse',
    Age: 24,
    Gender: 'Male',
    Ethincity: 'European'
}]]`

i tried figuring out methods to use but couldn't really figure out. Can anybody give me a hint which method or way to solve it. Any sort of help will be appreciated.

**Comment by reviewher** [comment]
Build up the header with `aoa_to_sheet` then add rows with `sheet_add_json`:

```js
var header = ["Names", "Age", "Gender", "Ethnicity"]
var ws = XLSX.utils.aoa_to_sheet([
  ["Personal Details"],
  header
]);
XLSX.utils.sheet_add_json(ws, [
  { Names: 'Prajwal', Age: 26, Gender: 'Male', Ethincity: 'Asian' },
  { Names: 'Viktoria', Age: 23, Gender: 'Female', Ethincity: 'European' },
  { Names: 'Lasse', Age: 24, Gender: 'Male', Ethincity: 'European' }
], {origin:-1, header:header, skipHeader:true});
// origin:-1 adds to end, header specifies the order, skipHeader omits a second header row
```

https://jsfiddle.net/yexdj24m/ is a live example showing the result as CSV.

You can call `sheet_add_json` multiple times if you are building up a result:

```js
XLSX.utils.sheet_add_json(ws, [
  { Names: 'Prajwal', Age: 26, Gender: 'Male', Ethincity: 'Asian' },
], {origin:-1, header:header, skipHeader:true});
XLSX.utils.sheet_add_json(ws, [
  { Names: 'Viktoria', Age: 23, Gender: 'Female', Ethincity: 'European' },
  { Names: 'Lasse', Age: 24, Gender: 'Male', Ethincity: 'European' }
], {origin:-1, header:header, skipHeader:true});
```

**Comment by prajwal78** [comment]
@reviewher - The below snippet of code 

![image](https://user-images.githubusercontent.com/10049692/35432931-fdd1624c-0281-11e8-82d0-10c6f9de8204.png)

throws me this below error:
![image](https://user-images.githubusercontent.com/10049692/35432966-17d653c8-0282-11e8-8a7a-6ef8b796871a.png)


Any hints ?

**Comment by reviewher** [comment]
@prajwal78 most likely a version issue -- make sure you are using the latest version

**Comment by prajwal78** [comment]
@reviewher - I have upgraded my version to 0.11.18 which is the latest version. But, still can't find the function is missing from the stack of functions inside the object. 
![sheet](https://user-images.githubusercontent.com/10049692/35497202-76897316-04c9-11e8-8540-8b4970a4e37b.png)
