### ISSUE TITLE
Unsupported file 237|140|144|235

### ISSUE THREAD

**Issue by hr5959** [SheetJS/js-xlsx#971]
Hello,

I'm trying to read CSV file on server. I wrote test files and uploaded.
But one file below named 'csv_test_success.csv' succeeded and the other file named 'csv_test_fail.csv' failed and generated the error '237|149|132|235'.
But I don't know differences between these files.

[csv_test_success.zip](https://github.com/SheetJS/js-xlsx/files/1666392/csv_test_success.zip)
[csv_test_fail.zip](https://github.com/SheetJS/js-xlsx/files/1666394/csv_test_fail.zip)

**Comment by SheetJSDev** [comment]
The relevant line https://github.com/SheetJS/js-xlsx/blob/master/bits/87_read.js#L103 checks if the first byte is in the ASCII display range:

```js
	if(0x20>n[0]||n[0]>0x7F) throw new Error("Unsupported file " + n.join("|"));
```
 The "success" file starts with a blank space but the "fail" file starts with a byte outside the range:

```
$ xxd csv_test_success.csv | head -n 1
00000000: 2020 2020 2020 2020 2020 2020 2020 2020    
$ xxd csv_test_fail.csv | head -n 1
00000000: ed95 84eb 939c 322c ed95 84eb 939c 332c  ......2,......3,
```

You can submit a pull request that just removes that guard line.

Note that both files are technically incorrect.  Here's what the "success" file looks like in Excel 2016 in the US English locale:
<img width="175" alt="" src="https://user-images.githubusercontent.com/6070939/35422646-c04eedfa-0217-11e8-871d-6c2c9a1f443c.png">

Always prepend the UTF8 BOM `"\ufeff"` when generating CSVs for Excel.  If you don't have control over the writer but know that you are receiving BOM-less CSVs, pass the option [`codepage:65001`](https://docs.sheetjs.com/#parsing-options) to the `read` or `readFile` function
