### ISSUE TITLE
DBF

### ISSUE THREAD

**Issue by fcpauldiaz** [SheetJS/js-xlsx#972]
Is it possible to convert a XLSX to DBF?

**Comment by reviewher** [comment]
Yes, and https://jsfiddle.net/4a5nqx8L/ is a demo.

Generally, you can convert [from any of the supported input formats to any of the supported output formats](https://docs.sheetjs.com/#file-formats).  XLSX support multiple sheets but DBF only supports one table, so you have to select the worksheet you want with the `sheet` option.

Read the XLSX file using one of the read techniques, then write using [`bookType:"dbf"`](https://docs.sheetjs.com/#supported-output-formats)

In nodejs, the `xlsx` CLI tool accepts the `-U` flag for DBF conversion:

```bash
$ xlsx -U path/to/file.xlsx
```
