### ISSUE TITLE
Write json_to_sheet Cannot read property length of undefined.

### ISSUE THREAD

**Issue by NazirNoori44** [SheetJS/js-xlsx#980]
Hi, I'm trying to use this library to export a json to excel file using the angular demo provided. Below is my code.

`            $scope.getExportData = data; //this is the json data
            var worksheet = XLSX.utils.json_to_sheet($scope.getExportData);
            XLSX.utils.book_append_sheet(workbook, worksheet, "Order Request History");
            var workbook = XLSX.utils.book_new();
            var workbookOut = XLSX.write(workbook, {bookType:'xlsx', type:'array'});
            saveAs(new Blob([workbookOut],{type:"application/octet-stream"}), "Workflow Manager History Export.xlsx");`

When this is executed, it throws the following error in web console.

> TypeError: Cannot read property 'length' of undefined
    at Uk (app.angular.js:1)
    at Object.Vk [as json_to_sheet] (app.angular.js:1)
    at o.$scope.exportToExcel (manufacturing.js:348)
    at fn (eval at compile (app.angular.js:1), <anonymous>:4:230)
    at b (app.angular.js:1)
    at e (app.angular.js:1)
    at o.$eval (app.angular.js:1)
    at o.$apply (app.angular.js:1)
    at HTMLButtonElement.<anonymous> (app.angular.js:1)
    at HTMLButtonElement.dispatch (app.angular.js:1)

And below is my json data for reference.

> [
   {
      "id": 1,
      "clientNumber": 1,
      "cmInventoryItemnum": "M001GVT_V      ",
      "cmNewInventoryId": null,
      "version": "v1",
      "docketNumber": "253527",
      "soNum": 451376,
      "specialInstruction": "New Order",
      "hasartwork": true,
      "isaltered": false,
      "isrush": false,
      "requestedon": {
         "year": 2017,
         "month": "SEPTEMBER",
         "dayOfWeek": "SUNDAY",
         "era": "CE",
         "dayOfYear": 260,
         "leapYear": false,
         "dayOfMonth": 17,
         "monthValue": 9,
         "chronology": {
            "id": "ISO",
            "calendarType": "iso8601"
         }
      },
      "requester": "smithjo",
      "percentage": 100,
      "iscompleted": true,
      "currentAction": null,
      "nextAction": null,
      "jobtypeId": {
         "id": 1,
         "name": "New Card Design",
         "description": "app.workflows.CMRNew"
      },
      "paymentSchemeId": {
         "id": 4,
         "name": "MasterCard",
         "description": null,
         "imgLogo": null
      },
      "currentStatus": {
         "id": 6,
         "status": "Completed"
      },
      "cmInventoryId": {
         "id": 10158,
         "custNum": 1,
         "itemId": 433,
         "itemNum": "M001GVT_V      ",
         "itemName": "BMO 1099 GOC ACQ PSTEXMT 5569B",
         "itemIsActive": 1,
         "itemCategory": 50,
         "itemLanguage": 3,
         "itemSapNum": "10029545",
         "version": null
      },
      "requestArtId": {
         "id": 3,
         "type": null,
         "transmissionMethod": "WorkFlow",
         "filename": "M001GVT_V - Govn't of Canada 5569 B 253527 OCT14_approved.pdf",
         "arttypeId": {
            "id": 1,
            "type": "REGULAR"
         }
      },
      "requestArtcmId": {
         "id": 2,
         "filename": "M001CUS_V.pdf"
      },
      "requestCardId": {
         "id": 1,
         "format": "333 55555 333 55555",
         "ica": 12234,
         "chipPinType": "6-Pin",
         "ccColourId": {
            "id": 1,
            "name": "White",
            "description": null
         },
         "cardTypeId": {
            "id": 1,
            "name": "Mag Only",
            "description": null
         },
         "chipColourId": {
            "id": 2,
            "name": "Gold",
            "description": null
         },
         "hgBackId": {
            "id": 2,
            "name": "Gold",
            "description": null
         },
         "hgFrontId": {
            "id": 2,
            "name": "Gold",
            "description": null
         },
         "msColourId": {
            "id": 1,
            "name": "Black",
            "description": null
         },
         "msTypeId": {
            "id": 1,
            "name": "Track II Hi-Co",
            "description": null
         }
      },
      "requestMeId": null,
      "requestUgfxId": null,
      "requestVhdId": null
   },
   {
      "id": 2,
      "clientNumber": 1,
      "cmInventoryItemnum": "M001GVT_V      ",
      "cmNewInventoryId": null,
      "version": "v2",
      "docketNumber": "253527",
      "soNum": 764389,
      "specialInstruction": "Reprint Order",
      "hasartwork": true,
      "isaltered": false,
      "isrush": false,
      "requestedon": {
         "year": 2017,
         "month": "OCTOBER",
         "dayOfWeek": "TUESDAY",
         "era": "CE",
         "dayOfYear": 283,
         "leapYear": false,
         "dayOfMonth": 10,
         "monthValue": 10,
         "chronology": {
            "id": "ISO",
            "calendarType": "iso8601"
         }
      },
      "requester": "smithjo",
      "percentage": 100,
      "iscompleted": true,
      "currentAction": null,
      "nextAction": null,
      "jobtypeId": {
         "id": 2,
         "name": "Reprint",
         "description": "app.workflows.CMRReprint"
      },
      "paymentSchemeId": {
         "id": 4,
         "name": "MasterCard",
         "description": null,
         "imgLogo": null
      },
      "currentStatus": {
         "id": 6,
         "status": "Completed"
      },
      "cmInventoryId": {
         "id": 10158,
         "custNum": 1,
         "itemId": 433,
         "itemNum": "M001GVT_V      ",
         "itemName": "BMO 1099 GOC ACQ PSTEXMT 5569B",
         "itemIsActive": 1,
         "itemCategory": 50,
         "itemLanguage": 3,
         "itemSapNum": "10029545",
         "version": null
      },
      "requestArtId": {
         "id": 3,
         "type": null,
         "transmissionMethod": "WorkFlow",
         "filename": "M001GVT_V - Govn't of Canada 5569 B 253527 OCT14_approved.pdf",
         "arttypeId": {
            "id": 1,
            "type": "REGULAR"
         }
      },
      "requestArtcmId": {
         "id": 2,
         "filename": "M001CUS_V.pdf"
      },
      "requestCardId": {
         "id": 1,
         "format": "333 55555 333 55555",
         "ica": 12234,
         "chipPinType": "6-Pin",
         "ccColourId": {
            "id": 1,
            "name": "White",
            "description": null
         },
         "cardTypeId": {
            "id": 1,
            "name": "Mag Only",
            "description": null
         },
         "chipColourId": {
            "id": 2,
            "name": "Gold",
            "description": null
         },
         "hgBackId": {
            "id": 2,
            "name": "Gold",
            "description": null
         },
         "hgFrontId": {
            "id": 2,
            "name": "Gold",
            "description": null
         },
         "msColourId": {
            "id": 1,
            "name": "Black",
            "description": null
         },
         "msTypeId": {
            "id": 1,
            "name": "Track II Hi-Co",
            "description": null
         }
      },
      "requestMeId": null,
      "requestUgfxId": null,
      "requestVhdId": null
   }
]

Could this be due to my json data? Any help would be appreciated!

**Comment by NazirNoori44** [comment]
Closing this issue as I was able to correct my code.

**Comment by LUUHUY2017** [comment]
You can answer width me, please

**Comment by vishalbhushan18** [comment]
Hi Nazir. I am facing the same issue. Could you help me with it?

**Comment by soportehrm** [comment]
@NazirNoori44 Could you tell us, how did you fix it?

**Comment by reviewher** [comment]
Make sure any nested objects are flattened.  This is bad:

```js
var data = [
  {
    a: {
      b: 1,
      c:2
    }
  }
];
```
