### ISSUE TITLE
I want to export 50 thousand pieces of data, what do I do?

### ISSUE THREAD

**Issue by 125037225** [SheetJS/js-xlsx#981]
Now that the 20 thousand is exported, the browser dies！！！

**Comment by reviewher** [comment]
http://sheetjs.com/demos/100001.html generates 100K rows and works locally.  Can you share an example dataset that's failing?

**Comment by 125037225** [comment]
@reviewher  
let _this = {}
  _this.fileName = option.fileName || 'download'
  _this.datas = option.datas
  _this.workbook = {
    SheetNames: [],
    Sheets: {}
  }
  let workbook = _this.workbook
  _this.datas.forEach((data, index) => {
    let sheetHeader = data.sheetHeader || null
    let sheetData = data.sheetData
    let sheetName = data.sheetName || `sheet${index + 1})`

    if (sheetHeader) {
      sheetData.unshift(sheetHeader)
    }

    let sheetFormatData = sheetChangeData(sheetData, option.excelDataType, option.columnWidths)
    // sheetFormatData['!merges'] = []

    workbook.SheetNames.push(sheetName)
    workbook.Sheets[sheetName] = sheetFormatData
  })
  let wbout = XLSX.write(workbook, {
    bookType: 'xlsx',
    bookSST: false,
    type: 'binary'
  })
  let blobData = new Blob([tooArrayBufferView(wbout)], { type: 'application/vnd.ms-excel' })
  saveAs(blobData, `${_this.fileName}.xlsx`)

-----------------------------------------------
I has 50000 data , The program runs to 'XLSX.writ', and the browser crashes！
my cell has style , for example：
style = {
    font: {
      sz: 8,
      name: 'Microsoft YaHei',
    },
    border: {
      top: { style: 'thin', color: { rgb: '000000' } },
      right: { style: 'thin', color: { rgb: '000000' } },
      bottom: { style: 'thin', color: { rgb: '000000' } },
      left: { style: 'thin', color: { rgb: '000000' } }
    },
    alignment: {
      horizontal: 'center'
    }
  }

**Comment by JonathanFu** [comment]
@125037225 
Not sure it is related, it seems you are using old content type.

> let blobData = new Blob([tooArrayBufferView(wbout)], { type: 'application/`vnd.ms-excel`' })
```js
let blobData = new Blob([tooArrayBufferView(wbout)], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' })
```
For BIFF .xls files
**application/vnd.ms-excel**
For Excel2007 and above .xlsx files
**application/vnd.openxmlformats-officedocument.spreadsheetml.sheet**

**Comment by 125037225** [comment]
@JonathanFu jon
I have a large amount of data.And Add cell style.
The code runs here and the browser crashes.
--------------------
let wbout = XLSX.write(workbook, {
    bookType: 'xlsx',
    bookSST: false,
    type: 'binary'
  })

**Comment by SheetJSDev** [comment]
Without a reproduction it's hard to say what's happening.  If you can share a demo we can take a look.
