### ISSUE TITLE
Generate excel with styles in javascript

### ISSUE THREAD

**Issue by magtuan** [SheetJS/js-xlsx#982]
hi, you could tell me how to generate an excel with styles, I generate the xlsx but I can not show the styles, but the cells object does contain the s parameter with the defined style.
I attach images of the code.
Thank you very much for your help.

function GenerateExcelFile(inData){
    console.log("Generate");
    wb =  new Workbook();
    wb.cellStyles=true;
    ws = sheet_from_array_of_arrays(inData);
    var ws_name = "Hoja1";

    console.log("Datos: ",ws);
    wb.SheetNames.push(ws_name);
    ws.cellStyles=true;
    wb.Sheets[ws_name] = ws;

    var wbout = XLSX.write(wb, {bookType:'xlsx', bookSST:true,  type: 'binary'});

    saveAs(new Blob([s2ab(wbout)],
        {type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"}),
        "Libro.xlsx");
    //saveAs(new Blob([s2ab(wbout)],{type:"application/octet-stream"}), "Libro.xlsx")

}

![image](https://user-images.githubusercontent.com/34962721/35727210-a8a1ddf2-0807-11e8-8861-5403aad74c09.png)

**Comment by magtuan** [comment]
how do you have to report the s parameter of the cell?
Option 1: s: fill: {patterntype: ...}
Option 2: s: {patterntype ...}

![image](https://user-images.githubusercontent.com/34962721/35728416-cdf137d4-080b-11e8-96ec-f6066022c7f7.png)


Thank you very much

**Comment by afeezaziz** [comment]
@magtuan , have you found out on how to achieve this?

**Comment by SheetJSDev** [comment]
We offer this in the [Pro compendium](https://sheetjs.com/pro).  Since companies have paid for the features already, it would be unfair to them if we turned around and made it available as open source.  [We have a longer comment in a gist.](https://gist.github.com/SheetJSDev/24b8acd317d01999d721b38de7c53021)
