### ISSUE TITLE
Hiding columns

### ISSUE THREAD

**Issue by AviAkGlobal** [SheetJS/js-xlsx#983]
How would you hide a column?

I've trying 'playing' with the width of columns, but whenever there's text, the column is being displayed...

**Comment by AviAkGlobal** [comment]
not relevant

**Comment by aescobar-icc** [comment]
var wb = XLSX.utils.table_to_book(elt, {sheet:"Sheet JS",**display:true**});

works for me, ignore all th in 'display:none'

**Comment by theppiwat** [comment]
> var wb = XLSX.utils.table_to_book(elt, {sheet:"Sheet JS",**display:true**});
> 
> works for me, ignore all th in 'display:none'
it's work thank you
