### ISSUE TITLE
Changing cell number format to 'text' doesn't work for .xls

### ISSUE THREAD

**Issue by scwood** [SheetJS/js-xlsx#987]
Here's a fiddle:

https://jsfiddle.net/jq0cr4gu/

```js
var data = [
  {a: '01234', b: '01234'},
  {a: '01234', b: '01234'},
];

var worksheet = XLSX.utils.json_to_sheet(data);

var range = XLSX.utils.decode_range(worksheet['!ref']);
for (var r = range.s.r; r <= range.e.r; r++) {
  for (var c = range.s.c; c <= range.e.c; c++) {
    var cellName = XLSX.utils.encode_cell({c: c, r: r});
    worksheet[cellName].z = '@';
  }
}

var workbook = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(workbook, worksheet, 'sheet1');

var wbout = XLSX.write(workbook, {type: 'array', bookType: 'xls'});
saveAs(new Blob([wbout], {type: 'application/octet-stream'}), 'test.xls');
```

All the cells should be formatted as 'Text' however opening the file in Excel they're formatted as 'General'.

If I instead change the above code to write the file as .xlsx I get the correct cell formatting. End goal here is to preserve leading zeros in numeric fields, but we need the compatibility of .xls.

Is this an expected limitation?

**Comment by SheetJSDev** [comment]
The BIFF2/5/8 XLS formats are not currently persisting the number formats.  You can still pass numbers as text and the values will be stored as text.

Note: Passing `@` as the format won't preserve the leading zeroes.  If you are passing a raw number, you actually need a format that mandates leading zeroes like `0000000000`.  The reason it "seems to work" for both XLS and XLSX is that you were actually passing a text string.  Here's a fiddle showing the difference between passing text and numeric values: https://jsfiddle.net/oq7Lo3m0/

**Comment by scwood** [comment]
Wow, appreciate the quick turnaround. We grabbed the latest version and it's working great. Thank you 👍

**Comment by anuuzsoni** [comment]
@scwood i am still facing this issue, can you please help me out 
![image](https://user-images.githubusercontent.com/59569445/230015371-e51bf9f3-e986-43c3-8eb6-fe3664ccd715.png)
![image](https://user-images.githubusercontent.com/59569445/230015406-15a744eb-1331-4813-95ec-76439305e0c9.png)

**Comment by scwood** [comment]
@anuuzsoni TBH I have no idea how any of this works anymore, it was five years ago, but if I remember correctly I think we ended up just going to a .xlsx format to resolve these types of issues.
