### ISSUE TITLE
Executing macros

### ISSUE THREAD

**Issue by AustinTexasChrisK** [SheetJS/js-xlsx#994]
I am loading an Excel file that has a macro which is run by press of a button. Is there any chance to execute the macro after loading the file?

**Comment by SheetJSDev** [comment]
Just a note on the feature: There are obvious limitations, like the Win32 API that is unavailable in the browser, but in theory very basic UDFs could be evaluated.  The required features (VBA parsing and evaluation, in-browser model of Excel) are definitely out of scope.
