### ISSUE TITLE
Excel comment window not closing when mouse out/away from cell

### ISSUE THREAD

**Issue by cmuruganmsc** [SheetJS/js-xlsx#998]
Hi, we are using xlsx@v0.12.1 plugin (https://www.npmjs.com/package/xlsx) for writing data in exported excel file also try to add cell comment. After export the data the cell comment added for applicable cells and when we hover on cell the comment window open/close working fine with Read Only mode. When we edit the download excel file from internet/my server. The comment window failed to close when away from cell. 

Please let me know if we need to add any new configuration properties in write_comments_vml() method to avoiding comment window close issue and its get works as expected. Also attached screen shot and download file for reference.

Note: Please not down the excel comment working as expected in Read Only mode.
[Excel-cell-comment-window-not-close.xlsx](https://github.com/SheetJS/js-xlsx/files/1731219/Excel-cell-comment-window-not-close.xlsx)
![excel-comment-window-not-close](https://user-images.githubusercontent.com/5468492/36306834-51354e42-12ce-11e8-97e3-a0b1162a279e.png)

**Comment by SheetJSDev** [comment]
That is controlled by the [`<x:Visible>` tag](https://github.com/SheetJS/js-xlsx/blob/master/bits/55_vml.js#L38) and [default shape css style](https://github.com/SheetJS/js-xlsx/blob/master/bits/55_vml.js#L22).  The fix, which we will push in the next version, will control both through a `hidden` property on the comment object.

**Comment by dylan-shao** [comment]
Hi, I am using 0.14 version, still not fixed here
